### ISSUE TITLE
Invio Fattura XML via PEC

### ISSUE THREAD

**Issue by gscalone** [OCA/l10n-italy#1002]
salve
ho configurato la versione 11 di odoo con la fatturazione elettronica.
Riesco tranquillamente a generare il file xml, ho compilato tutti i campi per l'invio della fattura via pec all'indirizzo sdi ma non ho nessun pulsante che mi permetta di inviarla direttamente.
c'è qualche automatismo o mi manca qualche procedura?

utilizzo la versione 11 su windows server 2019.

grazie
g.

**Comment by GSLabIt** [comment]
Manca ancora https://github.com/OCA/l10n-italy/pull/685

**Comment by primes2h** [comment]
> Manca ancora #685

Dato che è stato fatto il merge, chiudo.
