### ISSUE TITLE
l10n_it_fatturapa_out out_fiscal_document_type

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#1014]
Per riprodurre l'errore:
dal partner--> accounting --> sale --> imposto: Tipo documento fiscale: fattura
![image](https://user-images.githubusercontent.com/25057933/52713446-9e111e80-2f97-11e9-836a-45c7bc255bb1.png)

poi, dal menu fatturazione, creo una nuova nota di credito per quel cliente.

Non vado a vedere sul secondo tab Other info quale tipo di documento ha preso, visto che sono partito dalla creazione di una nota di credito, penso sia tutto apposto.... invece:

Il documento creato è di tipo Nota di credito, ma il tipo di documento fiscale é una fattura TD01
![image](https://user-images.githubusercontent.com/25057933/52713698-4626e780-2f98-11e9-87cd-4e876fa12411.png)
 
La mia proposta è quella di eliminare il peccato originale, quindi togliere dalla anagrafica partner il tipo di documento predefinito (sia in acquisti che in vendita) se non ha un motivo preciso per il quale è stato messo lì.

 - [ ] 8.0
 - [x] 10.0: https://github.com/OCA/l10n-italy/pull/1424 ~~https://github.com/OCA/l10n-italy/pull/1427~~
 - [x] 11.0: https://github.com/OCA/l10n-italy/pull/1422
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1390

**Comment by labaggio** [comment]
Nella call di oggi si è pensato di fare in questo modo:

- Mantenere il tipo documento originale, ma nominarlo "Tipo documento fiscale attivo"
- Aggiungere un nuovo campo "Tipo documento fiscale passivo"
- Aggiungere questo nuovo campo in Customer, Fiscal Position e Journal.
- Aggiungere Nota: Compilare solo per gestire eccezioni. es. TD10

**Comment by primes2h** [comment]
> Nella call di oggi si è pensato di fare in questo modo:
> 
>     * Mantenere il tipo documento originale, ma nominarlo "Tipo documento fiscale attivo"
>     * Aggiungere un nuovo campo "Tipo documento fiscale passivo"
>     * Aggiungere questo nuovo campo in Customer, Fiscal Position e Journal. 
>     * Aggiungere Nota: Compilare solo per gestire eccezioni. es. TD10

La proposta di Marcelo di risolvere la issue togliendo semplicemente dalla anagrafica partner il "tipo documento" mi sembra la più ovvia e naturale.

Le modifiche proposte qui sopra mi sembrano inutilmente complicate, a meno che non vadano a coprire casi d'uso che esulano dalla issue stessa.

**Comment by primes2h** [comment]
Restando sempre su questa issue, forse un'altra soluzione potrebbe essere quella di di rendere prioritario il "tipo documento" definito sulla fattura/nota di credito rispetto a quello definito sul partner.

**Comment by stevech091** [comment]
in realtà il campo serve proprio per gestire le eccezioni pero' deve essere gestito sia il caso attivo che passivo dove è l'anagrafica che deve vincere rispetto al documento (che risulta quindi di base lo standard).
Per quello a livello di community si è decisa questa strada per rendere il tutto il piu' flessibile.
Quindi in un flusso "standard" entrambi i campi sul partner devono semplicemente rimanere vuoti.

**Comment by eLBati** [comment]
In prima battuta io propongo questa fix veloce: https://github.com/OCA/l10n-italy/pull/1390

Poichè ritengo comunque sbagliato  utilizzare il campo `Out Fiscal Document Type` (o `In Fiscal Document Type`) impostato sul partner, quando si stanno creando note di credito

**Comment by primes2h** [comment]
> In prima battuta io propongo questa fix veloce: #1390
> 
> Poichè ritengo comunque sbagliato utilizzare il campo `Out Fiscal Document Type` (o `In Fiscal Document Type`) impostato sul partner, quando si stanno creando note di credito

:+1:

**Comment by marcelofrare** [comment]
> In prima battuta io propongo questa fix veloce: #1390
> 
> Poichè ritengo comunque sbagliato utilizzare il campo `Out Fiscal Document Type` (o `In Fiscal Document Type`) impostato sul partner, quando si stanno creando note di credito

e fin qua, sono d'accordo anch'io.

**Comment by marcelofrare** [comment]
scusate... ho chiuso per errore.
Cmq la fix proposta da @eLBati é in linea con quanto affermato da @stevech091:
**il tipo di documento impostato sul partner lo si utilizza per le fatture.**
Aggiungere un secondo tipo di documento per le n.c. è un di più che ha senso solo se esistono dei meccanismi automatici che potrebbero averne bisogno.
Al momento io non ne conosco nessuno...

**Comment by marcelofrare** [comment]
Come d'accordo chiudo la issue visto che il fix #1390 di @eLBati ha risolto il motivo per il quale era stata aperta. 
Invito eventualmente @stevech091 ad aprire una nuova per la gestione dei documenti passivi.
Grazie

**Comment by stevech091** [comment]
@marcelofrare per ora direi che va bene così

**Comment by andreampiovesana** [comment]
versione 11.0
https://github.com/OCA/l10n-italy/pull/1422

**Comment by eLBati** [comment]
Riapro per tracciare le altre versioni

**Comment by stevech091** [comment]
noi ci occupiamo della V10.

**Comment by eLBati** [comment]
Chiudo perchè la 8 è fuori dagli interessi principali.
Se qualcuno volesse fare la PR, riapriamo.
