### ISSUE TITLE
Bug codice REA univoco nella creazione delle fatture elettroniche

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1029]
Salve,

il modulo _l10n_it_fatturapa_in_, nel generare le fatture elettroniche in ingresso, fa scattare la constraint SQL del modulo _l10n_it_rea_ `rea_code_uniq`, impedendo di portare a termine la creazione del nuovo record.

I passaggi del bug sono i seguenti:
1. viene creata una fattura elettronica in ingresso con file allegato;
2. scatta la compute `_compute_xml_data()` del model `fatturapa.attachment.in`;
3. dentro la compute, il metodo `getCedPrest()` va a modificare i dati del partner;
4. la `write()` alla penultima riga di `getCedPrest()` modifica (o quantomeno, può modificare) il `rea_code` del partner, senza però controllare se quello stesso valore sia già impostato su un altro record;
5. scatta la constraint SQL `rea_code_uniq`.

Il bug è purtroppo bloccante, soprattutto nei casi di download massivo di fatture attraverso il servizio di API di vari intermediari, dove la constraint può bloccare l'intero processo anche dopo svariate fatture andate a buon fine e non si può intercettare l'errore con un blocco `try/except`.

Una possibile soluzione potrebbe essere, appunto, quella di fare un `raise` nel caso si verifichi la presenza (tramite `search()`) di due o più record di `res.partner` che condividono lo stesso codice REA che il metodo `getCedPrest()` sta per scrivere sul partner (possibilmente specificando nome ed id del `res.partner` doppione).
In questo modo, nella creazione manuale della fattura, l'utente avrebbe i dati necessari per fare le dovute modifiche sulle anagrafiche dei partner prima di creare la fattura in ingresso; nel caso di download massivi tramite API, invece, si darebbe modo al download di proseguire per le restanti fatture elettroniche e gestire indipendentemente l'errore.

# fixes

 - [x] v8: https://github.com/OCA/l10n-italy/pull/1061
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1060
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1059
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1295

**Comment by sergiocorato** [comment]
@SilvioGregorini grazie, pensavi di fare una PR?

**Comment by SilvioGregorini** [comment]
@sergiocorato sì, farei tre PR per le versioni 8.0, 10.0 e 11.0

**Comment by eLBati** [comment]
@sergiocorato @SilvioGregorini https://github.com/OCA/l10n-italy/pull/1059/files#r261341708 magari parliamone qui nella issue, per decidere la fix e poi applicarla a tutte le versioni

**Comment by sergiocorato** [comment]
@SilvioGregorini @eLBati qualcosa del tipo #1063

**Comment by sergiocorato** [comment]
> @SilvioGregorini @eLBati qualcosa del tipo #1063

chiudo la #1063 perchè è preferibile segnalare una inconsistenza invece di ricercare per codice REA

**Comment by sergiocorato** [comment]
quindi se riassumo bene in base alla call OCA di stamattina:
1. ricercare se il codice REA è già presente in un partner diverso da quello trovato:
se sì:
  a. non inserirlo sul partner trovato
  b. metterlo nelle inconsistenze della e-fattura

**Comment by eLBati** [comment]
@sergiocorato esatto

**Comment by SilvioGregorini** [comment]
@sergiocorato @eLBati ho aggiornato le PR, potete vedere se manca qualcosa?
Grazie!

**Comment by sergiocorato** [comment]
@SilvioGregorini a me pare ok, ho fatto una piccola segnalazione sul messaggio, ma potrei aver frainteso, grazie!

**Comment by SilvioGregorini** [comment]
@sergiocorato la segnalazione è corretta, non avevo pensato a modificare il messaggio. Sto già rimediando.
Quando poi lo riterrete pronto per il merge, farò squash dei commit così da averne uno solo.

**Comment by SilvioGregorini** [comment]
@eLBati ho sistemato le versioni del modulo e squashato i commit nelle PR, puoi segnalarmi se c'è altro da fare?

**Comment by eLBati** [comment]
per la 12 https://github.com/OCA/l10n-italy/pull/1295 merge?

**Comment by SilvioGregorini** [comment]
Tutte le PR sono state mergiate, chiudo
