### ISSUE TITLE
l10n_it_ddt, corriere mancante

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#1043]
Su 10, ma anche 11, sul partner e sull'ordine di vendita è possibile specificare i dati di spedizione che verranno poi riportati sul DDT.

Questi vengono riportati correttamente se si usa il flag "crea automaticamente il ddt" sull'ordine, ma se si passa dal wizard "DDT da Picking", il campo "corriere" ad esempio, non viene riportato.

# Fixes

 - [ ] v8:
 - [x] v10: #1044
 - [x] v11: #1103 
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1111

**Comment by baba75** [comment]
Ho creato qui una PR. Non ho testato sulla 11
https://github.com/OCA/l10n-italy/pull/1044

**Comment by GSLabIt** [comment]
11.0 - https://github.com/OCA/l10n-italy/pull/1075

**Comment by eLBati** [comment]
@OCA/local-italy-developers per v8 è da fare?

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
