### ISSUE TITLE
l10n_it_corrispettivi_sale: use_corrispettive not correcly propagated from partner

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1045]
1. set use corrispettivo in partner
2. create a sale order for the partner
3. from sale order create a receipt with down payment.
4. check journal on receipt (actually it create an invoice instead of recepit).

# Fixes

v8: module not available
v10: https://github.com/OCA/l10n-italy/pull/1049
v11: https://github.com/OCA/l10n-italy/pull/1027
v12:

**Comment by eLBati** [comment]
@GSLabIt sai mica se anche 10.0 ne soffre?

cc @OCA/local-italy-developers

**Comment by GSLabIt** [comment]
@eLBati non ho testato, provo il runbot

**Comment by GSLabIt** [comment]
@eLBati provato sul runbot e anche la 10 ha lo stesso problema.

**Comment by GSLabIt** [comment]
v 10.0 fix https://github.com/OCA/l10n-italy/pull/1049

**Comment by eLBati** [comment]
@GSLabIt @monen17 @elvise questa issue mi pare duplicata della https://github.com/OCA/l10n-italy/issues/835, quindi la chiuderei.

Anche le PR collegate a questa issue sarebbero da chiudere, a meno che non si riesca a identificare quale problema risolvano.

**Comment by GSLabIt** [comment]
@eLBati potrebbe anche essere un duplicato se viene fatto il fix qui
https://github.com/OCA/l10n-italy/pull/976, altrimenti non il problema persiste; se fosse possibile testare su runbot si potrebbe verificare.

**Comment by eLBati** [comment]
@GSLabIt per testare su runbot vai su https://github.com/OCA/l10n-italy/pull/976, click `show all checks`, click sui dettagli di runbot e `force rebuild`. Aspetti che la build venga completata e puoi testare.

Allora per ora chiudo. Se venisse identificato un problema diverso da https://github.com/OCA/l10n-italy/issues/835, riapriamo

**Comment by GSLabIt** [comment]
@eLBati 👍
