### ISSUE TITLE
Add supplier in fatturapa.attachment.in search

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1046]
- [x] v8: https://github.com/OCA/l10n-italy/pull/1034
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1035
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1055
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1056

**Comment by eLBati** [comment]
@OCA/local-italy-developers

**Comment by jado95** [comment]
v10 : https://github.com/OCA/l10n-italy/pull/1035 (to merge)

**Comment by eLBati** [comment]
:tada:
