### ISSUE TITLE
[l10n_it_fatturapa_in] Relax check on tax natura to permit to import

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1048]
- [ ] v8: #1096 
 - [ ] v10: https://github.com/OCA/l10n-italy/pull/1042 (manca https://github.com/OCA/l10n-italy/pull/1096#discussion_r264001479)
 - [ ] v11:
 - [x] v12: https://github.com/OCA/l10n-italy/pull/809 , https://github.com/OCA/l10n-italy/pull/1062 e https://github.com/OCA/l10n-italy/pull/1148

**Comment by eLBati** [comment]
v12 https://github.com/OCA/l10n-italy/pull/1148 (ultima parte)

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v12, è stato fatto il merge di tutte e tre le PR.

**Comment by tafaRU** [comment]
Grazie @primes2h, fatto.

**Comment by sergiocorato** [comment]
chiudo per inattività
