### ISSUE TITLE
[FIX][11.0]l10n_it_fatturapa_in - dati cassa previdenziale

### ISSUE THREAD

**Issue by labaggio** [OCA/l10n-italy#1070]
In caso di fattura con riga di tipo Cassa Previdenziale, e database con più imposte con la stessa aliquota.

  File "/usr/local/lib/python3.5/dist-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 316, in _prepare_generic_line_data
    ) % (line.Descrizione, line.AliquotaIVA))
AttributeError: 'DatiCassaPrevidenzialeType' object has no attribute 'Descrizione'

- [ ] v11: #1069

**Comment by eLBati** [comment]
@labaggio questa quindi si può chiudere in favore di https://github.com/OCA/l10n-italy/pull/1011 ?

**Comment by labaggio** [comment]
> @labaggio questa quindi si può chiudere in favore di #1011 ?

Si, si possiamo chiudere

**Comment by roccocesetti** [comment]
quando verrà fatto il merge per l'aggiunta della voci di fattura per la casa previdenziale?

**Comment by eLBati** [comment]
@roccocesetti quando qualcuno testa o revisiona la relativa PR (per la 11: https://github.com/OCA/l10n-italy/pull/1011)
