### ISSUE TITLE
e-fattura multi azienda

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1072]
- [x] v8: #887 
 - [x] v10: https://github.com/OCA/l10n-italy/pull/851
 - [ ] v11
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1394

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v12, è stato fatto il merge.

**Comment by tafaRU** [comment]
Grazie @primes2h, fatto.

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
