### ISSUE TITLE
Restore DatiCassaPrevidenziale handling: when present, add it as invoice line

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1074]
- [x] v8: https://github.com/OCA/l10n-italy/pull/1015
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1009
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1011
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1010

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v8 visto che è stato fatto il merge della relativa PR. Si può anche chiudere visto che poi completa la serie.

**Comment by tafaRU** [comment]
Grazie @primes2h, fatto.
