### ISSUE TITLE
Possibilità di emettere fatture elettroniche per clienti stranieri

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1080]
- [x] v8: https://github.com/OCA/l10n-italy/pull/861
 - [x] v10: https://github.com/OCA/l10n-italy/pull/888
 - [x] v11: https://github.com/OCA/l10n-italy/pull/901
 - [x] v12: https://github.com/OCA/l10n-italy/pull/912

**Comment by eLBati** [comment]
:tada:

**Comment by sergiocorato** [comment]
:birthday:
