### ISSUE TITLE
REF moduli e-fattura per poter generare più di 99999 fatture

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1086]
- [ ] v8
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1085
 - [ ] v11
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1087

**Comment by eLBati** [comment]
@OCA/local-italy-developers per v12: https://github.com/OCA/l10n-italy/pull/1087 plis review

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
