### ISSUE TITLE
Latin encode default_code or product to pass validation

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1092]
- [x] v. 8: https://github.com/OCA/l10n-italy/pull/1091
- [ ] v. 10: https://github.com/OCA/l10n-italy/pull/1520
- [ ] v. 11: https://github.com/OCA/l10n-italy/pull/1519
- [ ] v. 12: https://github.com/OCA/l10n-italy/pull/1518

**Comment by sherpya** [comment]
ma come si fa se c'è un nome non latin? l'ADE come intende fare quando la fattura elettronica sarà usata anche intra stato?

**Comment by sergiocorato** [comment]
@sherpya la codifica a latin è impostata in diversi campi, mica solo questo, al punto che visto che con la versione attuale è un requisito, sarebbe da mettere in una funzione unica secondo me, che comprendesse anche il trunk al numero di caratteri. @eLBati che dici?
Per il futuro non ti so rispondere, lo sapremo vivendo :D

**Comment by eLBati** [comment]
Ok per una funzione generica da applicare sui campi che lo necessitano.

@sherpya in effetti bisognerebbe chiedere all'ADE

**Comment by sherpya** [comment]
eh l'avevo visto, rimango comunque curioso

**Comment by OpenCode** [comment]
Create le PR: 
- 10.0 #1520 
- 11.0 #1519 
- 12.0 #1518

**Comment by OpenCode** [comment]
Chiudo la issue perché resa inutile da #1506
