### ISSUE TITLE
Notifica contatti per ricezione pec non fatture e aggiunta test generici su pec

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1097]
- [x] v. 8: #995 [compreso test]
 - [x] v. 10: #696 and #704 [aggiunge test]
 - [x] v. 11: 
 - [x] v. 12: #733 e https://github.com/OCA/l10n-italy/pull/719

**Comment by eLBati** [comment]
@sergiocorato non mi pare che la https://github.com/OCA/l10n-italy/pull/704 aggiunga test per la parte di notifica da fetchmail, sbaglio?

**Comment by sergiocorato** [comment]
> @sergiocorato non mi pare che la #704 aggiunga test per la parte di notifica da fetchmail, sbaglio?

@eLBati esatto, aggiunge i test generici per la pec, specifico nel titolo

**Comment by eLBati** [comment]
Sulla 11 `e_inv_notify_partner_ids` c'è ed i test pure. Quindi penso che questa issue si possa chiuedere @OCA/local-italy-developers

**Comment by sergiocorato** [comment]
:+1
