### ISSUE TITLE
In Odoo 12 l10n_it_account dipende da account_fiscal_year

### ISSUE THREAD

**Issue by fchiri** [OCA/l10n-italy#1098]
In Odoo 12 l10n_it_account dipende da account_fiscal_year ma quest'ultimo non è presente in Odoo 12.
Quindi risulta impossibile installare l10n_it_account in Odoo 12 perchè il controllo delle dipendenze blocca il processo.

**Comment by eLBati** [comment]
Il modulo si trova qui
https://github.com/OCA/account-financial-tools/tree/12.0/account_fiscal_year

**Comment by fchiri** [comment]
> Il modulo si trova qui
> https://github.com/OCA/account-financial-tools/tree/12.0/account_fiscal_year

Ok, ma ora mi manca account_tax_balance. Che non riesco a trovare.

**Comment by eLBati** [comment]
@fchiri in generale nel file file https://github.com/OCA/l10n-italy/blob/12.0/oca_dependencies.txt trovi i repository OCA che contengono i moduli da cui dipendono quelli di l10n-italy

**Comment by fchiri** [comment]
> @fchiri in generale nel file file https://github.com/OCA/l10n-italy/blob/12.0/oca_dependencies.txt trovi i repository OCA che contengono i moduli da cui dipendono quelli di l10n-italy

Ok, informazione che recupero anche dai rispettivi __manifest__.py. Il problema diventa fare il gioco dell'OCA alla ricerca di tutti gli addons necessari ad installare uno specifico addons.
Suggerisco (fuori da ogni polemica ed in maniera totalmente costruttiva, e a proposito provvederò ad aprire apposito issue) di adottare una qualche tecnologia di gestione delle dipendenze come fa Ubuntu o come fa NPM.
Quello della catena delle dipendenze è la complicazione che ha fatto fuggire (e gettare discredito) sulle prime distribuzioni Linux.

F.

**Comment by fchiri** [comment]
cmq: "Impossibile installare il modulo "account_fiscal_year". Dipende dal "date_range" che non è disponibile nel sistema.

Ci rinuncio.

F.

**Comment by eLBati** [comment]
`date_range` è in `server-ux`. Strano che le build funzionino anche senza `server-ux` in `oca_dependencies.txt` :sweat_smile: 

> Suggerisco (fuori da ogni polemica ed in maniera totalmente costruttiva, e a proposito provvederò ad aprire apposito issue) di adottare una qualche tecnologia di gestione delle dipendenze come fa Ubuntu o come fa NPM

Tutti i moduli OCA sono su pypi, quindi se vuoi disinteressarti delle dipendenze, puoi usare pip per installarli (dopo aver installato odoo ad esempio con `pip install http://nightly.odoo.com/12.0/nightly/src/odoo_12.0.latest.tar.gz`).
In questo caso il modulo su pypi è https://pypi.org/project/odoo12-addon-l10n-it-account

**Comment by eLBati** [comment]
> Strano che le build funzionino anche senza server-ux in oca_dependencies.txt

Capito: funzionano perchè `server-ux` è nelle dipendenze di `account-financial-tools` https://github.com/OCA/account-financial-tools/blob/12.0/oca_dependencies.txt
