### ISSUE TITLE
Gestione DatiGestionali nelle fatture elettroniche attive

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1101]
- [ ] v. 8: #980 
 - [ ] v. 10: https://github.com/OCA/l10n-italy/pull/1309
 - [ ] v. 11: 
 - [ ] v. 12: https://github.com/OCA/l10n-italy/pull/1318

**Comment by OpenCode** [comment]
@sergiocorato 

Optiamo per l'integrazione delle modifiche nei moduli già esistenti essendo i DatiGestionale parte integrante dello standard delle fatture. Prenderei la parte di account.invoice e la collocherei nel modulo base di fatture pa e poi integrerei fatturapa_out e fatturapa_in per leggere e scrivere le informazioni necessarie.

**Comment by sergiocorato** [comment]
> @sergiocorato
> 
> Optiamo per l'integrazione delle modifiche nei moduli già esistenti essendo i DatiGestionale parte integrante dello standard delle fatture. Prenderei la parte di account.invoice e la collocherei nel modulo base di fatture pa e poi integrerei fatturapa_out e fatturapa_in per leggere e scrivere le informazioni necessarie.

@OCA/local-italy-developers condividete? le modifiche poi andrebbero in tutte le versioni

**Comment by eLBati** [comment]
@OpenCode @sergiocorato invece di creare un nuovo modulo? Per me OK

**Comment by TheMule71** [comment]
Domanda, si applica anche alla 14?
