### ISSUE TITLE
Spostare controllo Stato del partner all'inizio durante il controllo nelle fatture elettroniche

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1102]
- [x] v. 8: #1040 
 - [ ] v. 10: 
 - [ ] v. 11: 
 - [ ] v. 12:

**Comment by eLBati** [comment]
@sergiocorato come mai?

**Comment by sergiocorato** [comment]
@eLBati perchè poi il `country_id` viene usato per la verifica successiva

**Comment by sergiocorato** [comment]
[vedi](https://github.com/OCA/l10n-italy/pull/1040#issuecomment-470983859)

**Comment by eLBati** [comment]
@sergiocorato questo sulla 8 dava proprio errore?
Se non sbaglio, però, nelle versioni successive no
