### ISSUE TITLE
Performance per la fatturazione da DDT

### ISSUE THREAD

**Issue by OpenCode** [OCA/l10n-italy#1109]
- [x] v 8.0 #1107 
- [ ] v 10.0
- [ ] v 11.0
- [ ] v 12.0

**Comment by eLBati** [comment]
@OCA/local-italy-developers la correzione è necessaria per le altre versioni?

**Comment by OpenCode** [comment]
@eLBati essendo stata modificata la procedura originale di fatturazione, io chiuderei la issue per adesso. Dovesse essere il caso, possiamo riprenderla

**Comment by sergiocorato** [comment]
:+1:

**Comment by eLBati** [comment]
:+1:
