### ISSUE TITLE
Permettere di specificare CodiceTipo nelle righe e-fattura

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1113]
Versioni coinvolte:
 - [x] v. 8.0: #969 (incompleta per https://github.com/OCA/l10n-italy/pull/819#issuecomment-471487916) completata in #1118
 - [x] v. 10.0: #820 
 - [x] v. 11.0: #819 (incompleta per https://github.com/OCA/l10n-italy/pull/819#issuecomment-471487916) completata in #1117 
 - [x] v. 12.0: https://github.com/OCA/l10n-italy/pull/1142

Passi per riprodurre: esportare la e-invoice

Comportamento osservato: il CodiceTipo nelle righe fattura è predefinito e fisso 

Comportamento atteso: il CodiceTipo nelle righe fattura è personalizzabile, visto che alcuni clienti richiedono un CodiceTipo specifico.
n.b.: la proposta attuale è basica, una implementazione più completa dovrebbe basare il CodiceTipo sul partner ed in via residuale su un parametro, in modo da coprire le esigenze di diversi clienti.

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Anche per la 8.0 è stato fatto merge di una PR incompleta, come per https://github.com/OCA/l10n-italy/pull/819#issuecomment-471487916

@sergiocorato nel caso non fossi d'accordo con la richiesta di modifica, lo dovresti fare presente invece di fare merge ignorandola.
Il processo di revisione è una discussione aperta, nella quale se qualcuno solleva un problema, questo deve essere discusso.
Se non si arriva ad una soluzione condivisa da tutti, deciderà il PSC.

cc @OCA/local-italy-developers

**Comment by sergiocorato** [comment]
> Anche per la 8.0 è stato fatto merge di una PR incompleta, come per [#819 (comment)](https://github.com/OCA/l10n-italy/pull/819#issuecomment-471487916)
> 
> @sergiocorato nel caso non fossi d'accordo con la richiesta di modifica, lo dovresti fare presente invece di fare merge ignorandola.
> Il processo di revisione è una discussione aperta, nella quale se qualcuno solleva un problema, questo deve essere discusso.
> Se non si arriva ad una soluzione condivisa da tutti, deciderà il PSC.
> 
> cc @OCA/local-italy-developers

@eLBati :sob: non l'ho proprio vista

**Comment by eLBati** [comment]
@sergiocorato ah ok, nessun problema.

Tornando alla questione https://github.com/OCA/l10n-italy/pull/819#issuecomment-466335967, secondo me la cosa dovrebbe essere un minimo documentata nel README.
Quindi per 8.0 e 11.0 ci vorrebbero 2 ulteriori PR per farlo

**Comment by sergiocorato** [comment]
@eLBati nessun problema, risolvo

**Comment by taifu** [comment]
[10.0] sistemato conflitto, cambiata versione e aggiunto readme (vita l'Italia) #820
