### ISSUE TITLE
[FIX] l10n_it_reverse_charge: Assign RC flag when invoice line is created from PO

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1116]
Versioni coinvolte:

* [x] v10: https://github.com/OCA/l10n-italy/pull/1076
* [ ] v12: ?
* [ ] v14: ?

Passi per riprodurre:

0. Install Purchase
1. Set Reverse Charge type for a new fiscal position _fp_rc_
2. Assign _fp_rc_ to a new partner _partner_rc_
3. Create a new PO with one line for _partner_rc_, confirm, receive the products
4. Create a new vendor bill and add the created PO

Comportamento osservato:
RC flag is not set in the line of the created invoice

Comportamento atteso:
RC flag is set in the line of the created invoice

**Comment by sergiocorato** [comment]
@SimoRubi probabilmente la copia non è andata bene, i campi diventano cliccabili se fatti così:
- [ ] v. 8

**Comment by SimoRubi** [comment]
ok grazie @sergiocorato, ho corretto: ci vuole uno spazio in mezzo alle parentesi quadre.
Se puoi correggi le linee guida segnalate da @tafaRU in https://github.com/OCA/l10n-italy/pull/1076#issuecomment-471484780

**Comment by SimoRubi** [comment]
Ho aggiornato la descrizione includendo le versioni supportate 12 e 14:
> dato che la frequenza annuale dei rilasci di Odoo implica un notevole sforzo tecnico di porting dei moduli di localizzazione, il PSC OCA Italia ha deciso di concentrare gli sforzi sulle ultime due versioni pari.

(da https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#apertura-issue)
