### ISSUE TITLE
[11.0] Issue creazione fattura da ddt, non vengono rilevate righe da fatturare.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#1120]
Versioni coinvolte: Testata su runbot 11.0

Passi per riprodurre:

- Creare SO e DDT oppure ddt da picking
- Validare picking e ddt
- Creare fattura da DDT

Comportamento osservato: 
Non vengono rilevate righe da fatturare nonostante siano presenti.

<img width="1033" alt="Schermata 2019-03-12 alle 12 44 41" src="https://user-images.githubusercontent.com/11652845/54197726-ff5bdd00-44c4-11e9-8a71-a0defe4834d6.png">

<img width="995" alt="Schermata 2019-03-12 alle 12 44 59" src="https://user-images.githubusercontent.com/11652845/54197750-0d116280-44c5-11e9-8c59-c71252ee383f.png">

<img width="979" alt="Schermata 2019-03-12 alle 12 44 52" src="https://user-images.githubusercontent.com/11652845/54197748-0c78cc00-44c5-11e9-994b-e6877b422213.png">

Comportamento atteso: Rilevazione righe da fatturare e  creazione della fattura. 

Video/Screenshot (opzionale):

**Comment by difra** [comment]
Dagli screenshot vedo il flag "To be Invoiced" = False, quindi dovrebbe essere un problema nella configurazione. Suppongo nel ddt.transportation_reason_id.to_be_invoiced . Dovresti quindi settare il flag to_be_invoiced=True nella causale di trasporto utilizzata nel DDT

**Comment by GSLabIt** [comment]
@difra trovato ..grazie.
