### ISSUE TITLE
[10.0] Notifica consegna e-fattura non riconosciuta

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1125]
Ricevo questa mail da Odoo:"_Il messaggio PEC con message-ID è stato letto ma non elaborato, perché **non è relativo a una e-fattura**. Controllare la casella PEC ..._"

Si tratta della notifica dell'avvenuta consegna di una e-fattura, che pare uguale alle altre:

_Ricevuta di avvenuta consegna
Il giorno ... alle ore ... il messaggio
"IT04209610270_00011.xml" proveniente da ...
ed indirizzato a "sdixx@pec.fatturapa.it"
è stato consegnato nella casella di destinazione.
Identificativo messaggio: ****@pec.aruba.it_

Questo è l'XML: [IT04209610270_00011.xml.txt](https://github.com/OCA/l10n-italy/files/2970250/IT04209610270_00011.xml.txt)

**Comment by eLBati** [comment]
Questo messaggio sembra la notifica PEC di avvenuta consegna nella mailbox del SDI, non la ricevuta di consegna inviata dal SDI

**Comment by sergiocorato** [comment]
Si, sembra il normale messaggio che ti invia il gestore della pec (ne spediscono sempre 2, uno di accettazione e uno di consegna)

**Comment by protontrigg3r** [comment]
Infatti a livello di gestione dello stato di consegna della eFt è andato tutto apposto senza dover intervenire. Non mi era però mai successo, con le precedenti fatture, di rivere la mail "_... è stato letto ma non elaborato ..._", quindi ho pensato ci fosse qualche problema.
