### ISSUE TITLE
Hook for extension to permit to export multiple discounts

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1127]
- [ ] v8:
- [x] v10: #829 
- [ ] v11: 
- [x] v12: #1126

**Comment by tafaRU** [comment]
Grazie @robyf70, il checked indica che la PR è stat mergiata pertanto la v12 non dovrebbe ancora esserlo.

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
