### ISSUE TITLE
[FIX] l10n_it_fatturapa_in: IstitutoFinanziario and BIC are not mandatory in XML

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1129]
Versioni coinvolte:
 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1128
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1885

**Passi per riprodurre**
Importazione di una fattura fornitore avente in Dettagli pagamento sia BIC (per una banca già esistente in Odoo) che IBAN.

**Comportamento osservato**
Durante l'importazione della fattura elettronica viene visualizzato l'errore:
```
L'operazione non può essere conclusa probabilmente per le seguenti ragioni:
- eliminazione: altre registrazioni fanno riferimento alla registrazione che ci vuole eliminare
- creazione/modifica: un campo obbligatorio non è compilato correttamente
[oggetto con referenza: name - name]
```
L'errore riportato nel log è:
```
bad query: UPDATE "res_bank" SET "name"=NULL,"write_uid"=1,"write_date"=(now() at time zone 'UTC') WHERE id IN (6)
```

**Comportamento atteso**
L'importazione avviene con successo

**Comment by TheMule71** [comment]
Qual è la situazione per la 14.0? Anche se il baco non ci fosse (per la 12.0 la #1885) è stata mergiata prima che io aprissi la #1958, è il caso di modificare un test esistente per coprire la casistica? (o aggiungerne uno nuovo, ma io non sono super favorevole alla proliferazione dei test, se è possibile raggiungere lo scopo con un test pre-esistente)
