### ISSUE TITLE
l10n_it_fatturapa: Add cross check pec_destinatario and codice_destinatario

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1131]
Versioni coinvolte:

 - [ ] v8: #1134 
 - [x] v10: commit 723c0d033af1cd70dc9451589a0994d2838644e8 in https://github.com/OCA/l10n-italy/pull/978
 - [ ] v11
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1153

Passi per riprodurre:

Nel form di un cliente soggetto a fattura elettronica, inserire PEC destinatario ed un codice destinatario diverso da 0000000

Comportamento osservato:

Il sistema lo permette

Comportamento atteso:

Il sistema blocca l'utente

**Comment by eLBati** [comment]
@sergiocorato sì, è per non rischiare che l'utente metta dati incoerenti.
Il sistema considera la PEC solo se il codice è 0000000.
Però se l'utente inserisce un codice diverso da 0000000 ed una PEC, come lo dovremmo interpretare?

Considera che la modifica è nata per `l10n_it_website_portal_fatturapa` e similari, dove l'utente è di frontend, e potrebbe essere poco pratico di odoo e campi per la fatturazione elettronica.

**Comment by sergiocorato** [comment]
@eLBati  ok, se mette una PEC mi pare venga ignorata comunque, visto che è prioritario il codice

**Comment by eLBati** [comment]
Esatto

Il sab 16 mar 2019, 14:25 Sergio Corato <notifications@github.com> ha
scritto:

**Comment by primes2h** [comment]
@sergiocorato ho visto che hai chiuso la PR della v. 8.0 
Posso chiudere anche la issue?
