### ISSUE TITLE
l10n_it_fatturapa_in Set the supplier flag only where necessary

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1135]
Versioni coinvolte:

 - [ ] v8
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1121
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1168
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1122

Passi per riprodurre:

Quando si importa un fattura elettronica sia il rappresentate fiscale che l'eventuale intermediario vengono creati come fornitori se non presenti nel sistema

Comportamento osservato:

Rappresentanti fiscali e intermediari vengono creati come fornitori

Comportamento atteso:

I rappresentanti fiscali ed eventuali intemediari non sono fornitori di una azienda e pertanto la PR corrente non li imposta più come tali

**Comment by robyf70** [comment]
La v10 è su #1121

**Comment by tafaRU** [comment]
Ho aggiornato la To Do List. Grazie @robyf70.

**Comment by robyf70** [comment]
la v11 è su #1168

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
