### ISSUE TITLE
Fattura elettronica : generazione xml in caso di acconto

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#1136]
Versioni coinvolte:

- [ ] 10
- [ ] 11
- [ ] 12

Passi per riprodurre:
Creazione ordine di vendita, 
aggiungere una riga con prodotto con policy di fatturazione sul consegnato.
Fatturare subito un acconto.
Fare poi un'altra fattura a completamento dell'ordine.
Generare fattura elettronica

Comportamento osservato:
La seconda fattura elettronica, avrà una riga in cui viene storanto l'acconto.
Questa riga ha una quantità negativa e un prezzo positivo.
Il fatto di avere una riga negativa impedisce la validazione dell'xml generato.
Modificare la riga mettendo una qta positiva e un prezzo negativo comporta però un errato calcolo nel valore fatturato dell'ordine di vendita d'origine.

Comportamento atteso:
In fase di generazione dell'xml, la qta deve essere impostata positivamente, mentre il valore della riga deve essere negativo

Video/Screenshot (opzionale):

**Comment by primes2h** [comment]
C'è per caso già qualche PR aperta al riguardo?

**Comment by eLBati** [comment]
Chiudiamo in favore della https://github.com/OCA/l10n-italy/issues/2090 ?
