### ISSUE TITLE
l10n_it_reverse_charge: avoid creating autoinvoice with payment term

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#1138]
Versioni coinvolte:

 - [ ] v8
 - [x] v10: #1137
 - [ ] v11
 - [x] v12

Passi per riprodurre:
* creare una fattura fornitore intra UE (con termini di pagamento del cliente che prevede un pagamento scaglionato)
* validare la fattura
* aprire la autofattura generata

Comportamento osservato:
l'autofattura generata non risulta totalmente pagata.

Comportamento atteso:
l'autofattura generata risulta totalmente pagata.

Video/Screenshot (opzionale):

**Comment by primes2h** [comment]
> Versioni coinvolte:
> 
>     * [ ]  v8
> 
>     * [x]  v10: #1137
> 
>     * [x]  ~v11~: **modulo non presente**
> 
>     * [x]  ~v12~: **modulo non presente**
> 

Adesso il modulo l10n_it_reverse_charge è presente sia nella v11 che nella v12.

**Comment by tafaRU** [comment]
Grazie @primes2h, sistemato.

**Comment by eLBati** [comment]
Nella 12 la modifica è già inclusa

**Comment by primes2h** [comment]
Merge effettuato per la 10.0, nella 12.0 la modifica è già inclusa. Chiudo.
