### ISSUE TITLE
[10.0] l10n_it_fatturapa_out: tag Causale assente

### ISSUE THREAD

**Issue by borgogelli** [OCA/l10n-italy#1139]
Il modulo in oggetto non valorizza il tag xml Causale (di DatiGenerali).
Se la situazione è accettabile per la normale fatturazione, non lo è quando si predispongono ad esempio, delle note di credito o debito. Infatti in tale situazione il tag Causale deve essere utilizzato per indicare il riferimento alla fattura che si desidera stornare. Preciso che la necessità di valorizzare il tag non è formale, infatti il tag è facoltativo e l'xml sarebbe valido comunque, ma è sostanziale.
Una soluzione potrebbe essere quella di valorizzare il tag Causale con il valore del campo Descrizione della fattura. Così l'utente sarebbe libero di specificare il testo.
Oppure in caso di Nota di Credito/Debito si potrebbe valorizzare il tag Causale con un valore fisso come ad esempio "Riferimento documento [valore campo Origine]"

**Comment by borgogelli** [comment]
Guardando il codice (https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L535)
Ho notato  la seguente condizione:
```
if invoice.comment: 
caus_list = invoice.comment.split('\n')
```
Cosa significa ? Forse, devo installare il modulo "Invoice Comments" per poter valorizzare il tag "Causale" ?

**Comment by sergiocorato** [comment]
la causale è valorizzata dal campo `comment` che è presente di default
(solo le note)
Sergio Corato


Il giorno mer 20 mar 2019 alle ore 13:07 Andrea Borgogelli Avveduti <
notifications@github.com> ha scritto:

**Comment by borgogelli** [comment]
Le note a cui fai riferimento sarebbero quelle illustrate di seguito ?
![image](https://user-images.githubusercontent.com/7045594/54692606-8ba17c00-4b25-11e9-8e21-4ba8f9b29a95.png)

**Comment by eLBati** [comment]
@borgogelli no:

![image](https://user-images.githubusercontent.com/1033131/54769636-e27c8380-4c01-11e9-8366-79a8f43f7a9d.png)

**Comment by borgogelli** [comment]
Non so per quale motivo ma nella mia installazione di Odoo 10, il campo è denominato "Termini e Condizioni"
![image](https://user-images.githubusercontent.com/7045594/54809721-65deb900-4c84-11e9-9687-970a5d4fd168.png)

**Comment by eLBati** [comment]
@borgogelli sì `termini e condizioni` è il placeholder di default

**Comment by borgogelli** [comment]
Grazie mille a tutti
