### ISSUE TITLE
FIX l10n_it_fatturapa_out exporting REA data: if StatoLiquidazione is not valorized, don't export IscrizioneREA

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1140]
Versioni coinvolte:

 - [ ] v8
 - [x] v10: https://github.com/OCA/l10n-italy/pull/876
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1025
 - [x] v12: https://github.com/OCA/l10n-italy/pull/974

**Comment by eLBati** [comment]
@OCA/local-italy-developers per v8 serve?

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v11, è stato fatto il merge della relativa PR.

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
