### ISSUE TITLE
[8.0] [10.0] errore registrazione insoluto

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#1147]
richiamo una mia precedente issue https://github.com/OCA/l10n-italy/issues/347
e riporto questa riga di codice:
https://github.com/OCA/l10n-italy/blob/7187ea6a7379be1ff0edb1f34e388dfcae9b0256/l10n_it_ricevute_bancarie/wizard/wizard_unsolved.py#L198

credo che eliminando questa riconciliazione e lasciando la registrazione con le seguenti righe:

> - spese    (dare)
> - banca   (avere)
> - clienti    (dare)

risolviamo questo bug.
mentre ora alla registrazione di sopra, viene accodata anche la seguente

> - riba (dare)
> - clienti (avere)

la quale dovrebbe essere lo storno della riba precedentemente emessa

**Comment by sergiocorato** [comment]
chiudo per inattività
