### ISSUE TITLE
Errata importazione fatturapa

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1151]
https://github.com/OCA/l10n-italy/blob/ad604259349b180f87885627b9d47ca7c14544d2/l10n_it_fatturapa/bindings/__init__.py#L11

- [x] v8:  #776 
- [x] v10: https://github.com/OCA/l10n-italy/pull/998
- [ ] v11:
- [x] v12: https://github.com/OCA/l10n-italy/pull/1050

**Comment by primes2h** [comment]
È stato fatto il merge per le PR delle principali versioni supportate. Chiudo.
