### ISSUE TITLE
l10n_it_corrispettivi: Trova posizioni fiscali senza azienda

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1156]
**Versioni coinvolte:**
 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1157
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1170

**Passi per riprodurre:**
1. Creare una posizione fiscale avente il flag 'Corrispettivi';
2. Creare un nuovo partner e abilitare 'usa corrispettivi'.

**Comportamento osservato:**
La posizione fiscale non viene assegnata al partner

**Comportamento atteso:**
La posizione fiscale (pur non avendo valori nel campo `company_id`) viene assegnata al partner

**Comment by eLBati** [comment]
@OCA/local-italy-developers for v12: https://github.com/OCA/l10n-italy/pull/1170

**Comment by primes2h** [comment]
È stato fatto il merge per le PR delle principali versioni supportate. Chiudo.
