### ISSUE TITLE
l10n_it_corrispettivi: Mostra la vista lista dei corrispettivi dopo nota di credito

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1158]
**Versioni coinvolte:**
 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1159
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1169

**Passi per riprodurre:**
1. Creare un corrispettivo e validarlo;
2. Creare una nota di credito (in bozza) dal corrispettivo creato

**Comportamento osservato:**
All'uscita dal wizard, viene presentata una vista lista vuota

**Comportamento atteso:**
All'uscita dal wizard, viene presentata una vista lista contenente la nota di credito creata

**Comment by eLBati** [comment]
@OCA/local-italy-developers per v12: https://github.com/OCA/l10n-italy/pull/1169

**Comment by primes2h** [comment]
È stato fatto il merge per le PR delle principali versioni supportate. Chiudo.
