### ISSUE TITLE
auto_install e-commerce modules

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1167]
Versioni coinvolte:

 - [x] v10: https://github.com/OCA/l10n-italy/pull/1521
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1166

Per i moduli
l10n_it_website_sale_fatturapa
l10n_it_website_sale_fiscalcode
quando le loro dipendenze sono installate, non ha senso lasciarli disinstallati

**Comment by OpenCode** [comment]
10.0 -> #1521

**Comment by OpenCode** [comment]
Per la 8.0 e la 11.0 i moduli non esistono. Gli togliamo dalla lista? Chi fa porting e/o backporting adesso si troverà già il flag nel __manifest__

**Comment by eLBati** [comment]
@OpenCode grazie. Tolti
