### ISSUE TITLE
OverflowError: date value out of range > XML doctor

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1172]
Importando un xml ottengo questo errore: [OverflowError: date value out of range](https://github.com/OCA/l10n-italy/files/3054236/odoo_invoice_import_error.txt)

Nella [preview del file XML](https://github.com/OCA/l10n-italy/files/3054231/invoice_xml_preview.pdf) le date sembrano ok.

 - [ ] v8:
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1218
 - [ ] v11:
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1243

**Comment by sergiocorato** [comment]
Sarebbe utile vedere l'xml originale e non la preview, visto che potrebbe aver già pulito i campi

**Comment by protontrigg3r** [comment]
Eccolo. Grazie.

[fattura_odoo.xml.txt](https://github.com/OCA/l10n-italy/files/3057611/fattura_odoo.xml.txt)

**Comment by eLBati** [comment]
@protontrigg3r prova ad aggiornare 10.0, perchè dovrebbe essere risolto da https://github.com/OCA/l10n-italy/commit/354704da7278c029478c14de0ef1e3d50e505919

**Comment by protontrigg3r** [comment]
Ok. Grazie ancora.

**Comment by eLBati** [comment]
Risolve?

**Comment by protontrigg3r** [comment]
Riesco a fare l'upgrade domani pomeriggio. Vi faccio sapere

**Comment by protontrigg3r** [comment]
Ho dato un occhio alla "patch": se mi confermi che si tratta solo di upgradare PyXB a 1.2.6 faccio ssh ...

**Comment by eLBati** [comment]
No, c'è anche da aggiornare `l10n_it_fatturapa`

**Comment by protontrigg3r** [comment]
Ho aggiornato, ma il problema persiste :\

**Comment by eLBati** [comment]
@protontrigg3r confermo: il problema esiste sui moduli rilasciati. Ho fatto la PR https://github.com/OCA/l10n-italy/pull/1187 per riprodurlo.

**Comment by sergiocorato** [comment]
PR #1186

**Comment by sherpya** [comment]
@protontrigg3r ma chi è che produce questa fattura? qualcuno ha idea di cosa dovrebbe rappresentare? Il campo è opzionale quindi se non è utilizzato in teoria dovrebbe metterlo vuoto

**Comment by eLBati** [comment]
@sherpya sicuramente è uno schifo, però se SDI la accetta, odoo non deve andare in errore. Cosa ne pensi di https://github.com/OCA/l10n-italy/pull/1186 ?

@protontrigg3r la correzione https://github.com/OCA/l10n-italy/pull/1186 dovrebbe risolvere

**Comment by sherpya** [comment]
@eLBati a parte `PreserveInputTimeZone` a `True` sarebbe meglio metterlo in `__init__.py` comunque lo sconsigliano:
https://github.com/pabigot/pyxb/issues/106

ma in ogni caso è sbagliato, fai entrare nel sistema una data che python no supporta (ovvero prima dell'anno 1)

```python
>>> from datetime import datetime, timedelta
>>> datetime(1, 1, 1)
datetime.datetime(1, 1, 1, 0, 0)
>>> datetime(1, 1, 1) - timedelta(hours=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: date value out of range
```

**Comment by eLBati** [comment]
Cioè in questo caso che data risulta in odoo? @sergiocorato hai provato?

@sherpya altrimenti come si potrebbe fare?

**Comment by sherpya** [comment]
@eLBati buttare via queste date sbagliate ma la differenza tra ignorarle e dare errore non è facile, idealmente bisognerebbe contattare chi ha fatto il sw che crea sta roba e farlo smettere, inoltre contatare l'ADE e chiedere perché si accollano ste date rotte, ma capisco che somiglia molto alla fantascienza :D

**Comment by protontrigg3r** [comment]
> idealmente bisognerebbe contattare chi ha fatto il sw che crea sta roba e farlo smettere

Considera che in questo caso la fattura è pure stata emessa erroneamente, tanto che è già arrivata anche la nota di accredito, quindi figurati se ti stanno a sentire quando gli dici che il loro gestionale ha un problema ...

Provo #1186 e vi faccio sapere.

**Comment by sergiocorato** [comment]
> Cioè in questo caso che data risulta in odoo? @sergiocorato hai provato?
> 
> @sherpya altrimenti come si potrebbe fare?

![Screenshot_2019-04-19 Odoo](https://user-images.githubusercontent.com/7657311/56412462-84849f80-6284-11e9-8d27-a79628855193.png)

**Comment by sherpya** [comment]
> > Cioè in questo caso che data risulta in odoo? @sergiocorato hai provato?
> > @sherpya altrimenti come si potrebbe fare?
> 
> ![Screenshot_2019-04-19 Odoo](https://user-images.githubusercontent.com/7657311/56412462-84849f80-6284-11e9-8d27-a79628855193.png)

è una data a caso praticamente inoltre non credo la patch faccia passare una data tipo:
`0000-01-01T00:00:00.000+00:00` mentre suppongo l'ade se l'accolli.

Ho paura invece che le date giuste perdano il timezone quindi sballino di uno o due ore

**Comment by sergiocorato** [comment]
Beh, la data è quella indicata nel file, l'ora è a caso.
Sì, credo le date giuste sballino del timezone con questa correzione

**Comment by eLBati** [comment]
> buttare via queste date sbagliate

Si potrebbe allora intercettare l'eccezione `OverflowError` e buttarle, cheddite?

**Comment by sherpya** [comment]
> Beh, la data è quella indicata nel file, l'ora è a caso.
> Sì, credo le date giuste sballino del timezone con questa correzione

in realtà nemmeno :D quella data in utc è il giorno prima, il 31 dicembre dell'anno 0 alle 22 :D

**Comment by sherpya** [comment]
> > buttare via queste date sbagliate
> 
> Si potrebbe allora intercettare l'eccezione `OverflowError` e buttarle, cheddite?

se l'idea è quella di rimbalzarle sì, se le vogliamo far passare non saprei, bisognerebbe strippare le date ma diventa un po' una palla

**Comment by eLBati** [comment]
Con "buttarle" mi riferivo alle date assurde, non alle fatture

**Comment by sherpya** [comment]
> Con "buttarle" mi riferivo alle date assurde, non alle fatture

la vedo rognosa, bisogna cercare tutti gli `xsd:dateTime` del documento, controllare se fa overflow ed eliminarla

**Comment by sherpya** [comment]
non si può mandare le bestemmie a sogei?

**Comment by eLBati** [comment]
beh certo :joy: basta che le firmi digitalmente

**Comment by sherpya** [comment]
per comodità aggiungo lo stacktrace inline:

```
Traceback (most recent call last):
  File "/opt/odoo/OCB/odoo/http.py", line 642, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/OCB/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/OCB/odoo/http.py", line 334, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/service/model.py", line 101, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/OCB/odoo/http.py", line 327, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/OCB/odoo/http.py", line 942, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/OCB/odoo/http.py", line 507, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 899, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/OCB/addons/web/controllers/main.py", line 887, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/OCB/odoo/api.py", line 689, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/OCB/odoo/api.py", line 680, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1181, in importFatturaPA
    fatt = self.get_invoice_obj(fatturapa_attachment)
  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1164, in get_invoice_obj
    return fatturapa_v_1_2.CreateFromDocument(xml_string)
  File "/opt/odoo/addons-extra/l10n-italy/l10n_it_fatturapa/bindings/fatturapa_v_1_2.py", line 84, in CreateFromDocument
    saxer.parse(io.BytesIO(xmld))
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/usr/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/usr/lib/python2.7/xml/sax/expatreader.py", line 365, in end_element_ns
    self._cont_handler.endElementNS(pair, None)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 388, in endElementNS
    binding_object = this_state.endBindingElement()
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 226, in endBindingElement
    self.__constructElement(self.__delayedConstructor, self.__attributes, args)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/saxer.py", line 116, in __constructElement
    self.__bindingInstance = new_object_factory(*content, **kw)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/basis.py", line 1614, in __call__
    rv = self.typeDefinition().Factory(*args, **kw)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/basis.py", line 305, in Factory
    rv = cls._DynamicCreate(*args, **kw)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/basis.py", line 691, in _DynamicCreate
    return ctor(*args, **kw)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/datatypes.py", line 540, in __new__
    cls._AdjustForTimezone(ctor_kw)
  File "/opt/odoo/env-odoo/local/lib/python2.7/site-packages/pyxb/binding/datatypes.py", line 474, in _AdjustForTimezone
    dt -= tzoffs.utcoffset(dt)
OverflowError: date value out of range
```

**Comment by sherpya** [comment]
@eLBati @sergiocorato aspettiamo travis nel frattempo ditemi che ve ne pare

**Comment by sherpya** [comment]
volendo si può evitare di rinominare in giro fatturapa_v_1_2 ma mi pareva sensato non mettere la versione in giro per gli altri moduli

**Comment by sherpya** [comment]
ok, la PR è semi definitiva, se potete provatela, forse i warn possono essere aggiunti a `inconsistencies`

**Comment by eLBati** [comment]
>
> ok, la PR è semi definitiva, se potete provatela, forse i warn possono
> essere aggiunti a inconsistencies
>

Non sarebbe male

**Comment by eLBati** [comment]
Per la 12: https://github.com/OCA/l10n-italy/pull/1243
Una revisione?

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
