### ISSUE TITLE
XML contenente più fatture stesso soggetto, ne viene importata solo una

### ISSUE THREAD

**Issue by askweb2019** [OCA/l10n-italy#1177]
Versioni coinvolte: 10

Passi per riprodurre: Quando provo ad salvare un file XML contentente più fatture dello stesso soggetto, quando vado ad importare l'xml contenente più fatture, ne viene importata solo una. Dopo l'import sul sito dell'agenzia delle entrate, l'xml contiene una sola fattura, mentre in anteprima su odoo ne vengono visualizzate N

Comportamento osservato:

Comportamento atteso:

Video/Screenshot (opzionale):
![xml](https://user-images.githubusercontent.com/46442430/55957775-6d7ff500-5c67-11e9-9596-20f80be1e7a9.jpg)

**Comment by eLBati** [comment]
@askweb2019 non ho capito: stai importando o esportando fatture? Nello screenshot vedo un'esportazione

**Comment by askweb2019** [comment]
Ciao ,
esporto da ODOO, ed importo nel sito dell'agenzia delle entrate
