### ISSUE TITLE
[l10n_it_rea] Use rea_office in sql_constraints to avoid 'false' uniqueness

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1182]
Versioni coinvolte:

- [ ] 8.0
- [x] 10.0 #1181
- [x] 11.0 https://github.com/OCA/l10n-italy/pull/1059#issuecomment-500443610
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/1295

Passi per riprodurre:

Il `rea_code` ha il un `_sql_constraints` che non tiene in considerazione `rea_office` per garantire l'unicità del codice. Tuttavia, capita spesso che il `rea_code` abbia valori tipo `0` che creano il problema di non importare le fatture di acquisto.

Comportamento osservato:

Se due `rea_code` uguali ma sono stati assegnati in due province diverse, non sarà possibile creare il partner e neppure importare automaticamente un fattura di acquisto elettronica. 

Comportamento atteso:

Viene aggiunto il `rea_office` all'`_sql_constraints` per evitare di avere una restrizione troppo forte e non corretta. Personalmente eliminerei totalmente questo constraint.

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

**Comment by eLBati** [comment]
@robyf70 si sovrappone o estende la https://github.com/OCA/l10n-italy/issues/1029 ?
cc @sergiocorato @SilvioGregorini

**Comment by robyf70** [comment]
@eLBati La vedrei come "estende" la #1029. Questa PR rilassa il constraint sul codice REA in `l10n_it_rea`. Fosse per me toglierei direttamente il constraint dato cge esiste già il check sulla partita iva.

**Comment by primes2h** [comment]
È stato fatto il merge per le PR delle principali versioni supportate. Chiudo.
