### ISSUE TITLE
[IMP] l10n_it_fatturapa_in: Add total in attachment's tree view

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1193]
Aggiungere il totale delle fatture fornitore nella vista lista dei file XML

 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1194
 - [ ] v11: ?
 - [x] v12: ?

**Comment by eLBati** [comment]
La 12 contiene la modifica
