### ISSUE TITLE
[10] Bollo virtuale non riconosciuto correttamente dal SDI

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1195]
Versioni coinvolte:[10]

Buon giorno, entrando nel  portale agenzie dell'entrate https://ivaservizi.agenziaentrate.gov.it/portale/ nelle fatture trasmesse non viene identificato il bollo; questo comporta che quando  vado a pagare il bollo per il trimestre, sempre sul sito dell'agenzia dell'e entrate,  l'importo risulti zero. 
poco male faccio F24

ma questa funzione zarebbe apprezzata; cosa manca:
  da questo documento 
https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Rappresentazione_tabellare_del_tracciato_FatturaPA_versione_1.2.1.pdf
il bollo andrebbe contrassegnato con questi campi xml: 
2.1.1.6 " DatiBollo "
2.1.1.6.1" BolloVirtuale"
2.1.1.6.2" ImportoBollo"

guardando il file xml emesso e inviato non li trovo; ho sbagliato qualcosa io ?

Enrico 
![bollo1](https://user-images.githubusercontent.com/43685677/56419881-1fd53f00-629c-11e9-9531-43fd709310ed.jpg)

**Comment by sergiocorato** [comment]
hai installato il modulo per il bollo virtuale? l'hai configurato? risulta presente nel file xml prodotto?

**Comment by bitit-it** [comment]
ho installato 
# Italian Localization - Fattura elettronica - Integrazione bollo
# Italian Localization - Tax Stamp

poi in cofigurazione ho prodotto marca da bollo > Bollo virtuale 2 euro

nell xml della fattura c'è , ma non è indicato con i campi  xml che ho indicato sopra . 
2.1.1.6 " DatiBollo "
2.1.1.6.1" BolloVirtuale"
2.1.1.6.2" ImportoBollo"

quando faccio fattura, in caso sia maggiore a 77, 47 aggiungo il bollo virtuale  in una riga fattura .

Enrico

**Comment by sergiocorato** [comment]
> ho installato
> # Italian Localization - Fattura elettronica - Integrazione bollo
> # Italian Localization - Tax Stamp
> 
> poi in cofigurazione ho prodotto marca da bollo > Bollo virtuale 2 euro
> 
> nell xml della fattura c'è , ma non è indicato con i campi xml che ho indicato sopra .
> 2.1.1.6 " DatiBollo "
> 2.1.1.6.1" BolloVirtuale"
> 2.1.1.6.2" ImportoBollo"
quindi c'è dove? nelle righe? quello è solo per l'addebito al cliente, non è rilevante
> 
> quando faccio fattura, in caso sia maggiore a 77, 47 aggiungo il bollo virtuale in una riga fattura .
> 
questo non è rilevante, è solo l'addebito al cliente. Lo aggiungi con il tasto? Si vede se c'è il flag nel tab successivo alle righe fattura
> Enrico

**Comment by bitit-it** [comment]
![Screenshot_20190420_105342](https://user-images.githubusercontent.com/43685677/56455110-f29b9600-635a-11e9-909d-3d5879e02995.png)
ma a voi nel xml escono i campi DatiBollo , BolloVirtuale, ImportoBollo ?
forse ho da aggiornare qualche  plugin?

**Comment by bitit-it** [comment]
Non ho capito dove il flag?

**Comment by eLBati** [comment]
@bitit-it nel tab `altre informazioni`

**Comment by bitit-it** [comment]
Ok in effetti dimenticavo di flaggare, una volta flaggato nel xml i campi che mi  macavano ci sono; domani dovrei averlo nel sdi e verifico se riconosce tutto. 

Scusate  :(

**Comment by eLBati** [comment]
Figurati

**Comment by sergiocorato** [comment]
il flag effettivamente dovrebbe esserci in automatico, impostando le imposte su cui si applica il bollo (nel prodotto bollo), cmq ok
