### ISSUE TITLE
[FIX] account_vat_period_end_statement: New statements had the reconciled check set to True, but it should be False

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1198]
**Versioni coinvolte**
 - [ ] v8: ?
 - [ ] v10: ?
 - [ ] v11: sì
 - [x] ~~v12: https://github.com/OCA/l10n-italy/pull/1176/commits/9c7f4963ee6a4271dacb7c97ee4049dd2973a484~~

**Passi per riprodurre**
Notato la prima volta in https://github.com/OCA/l10n-italy/pull/1176#pullrequestreview-228658541.
Creare una nuova liquidazione IVA.

**Comportamento osservato**
Il check **Pagata/Riconciliata** è `True`.

**Comportamento atteso**
Il check **Pagata/Riconciliata** è `False`

**Comment by primes2h** [comment]
> **Versioni coinvolte**
> 
>     * [ ]  v8: ?
> 
>     * [ ]  v10: ?
> 
>     * [ ]  v11: sì
> 
>     * [x]  ~v12: [9c7f496](https://github.com/OCA/l10n-italy/commit/9c7f4963ee6a4271dacb7c97ee4049dd2973a484)~
>

@SimoRubi 
Cosa indica quel sì per la v11?

**Comment by SimoRubi** [comment]
Indica che la versione 11 è **coinvolta** (come scritto in descrizione): cioè ha il problema segnalato nella issue

**Comment by primes2h** [comment]
> Indica che la versione 11 è **coinvolta** (come scritto in descrizione): cioè ha il problema segnalato nella issue

Ah ok, avevo frainteso. Sorry.
