### ISSUE TITLE
[Odoo 11], esportazione file di fattura elettronica

### ISSUE THREAD

**Issue by denisgottardello** [OCA/l10n-italy#1199]
Salve a tutti. Ho dovuto spostare il Odoo 11 su altro server. Ho quindi reistallato tutto ed eseguito il restore del database.
Per quanto riguarda il modulo **"l10n_it_fatturapa_out"**
In Fatttua elettronica -> File e-fattura esportati manca il tasto per poter scaricare il file xml.
Per caso è stato tolto volontariamente dagli sviluppatori? Sembra infatti che il sistema a tutti i costi voglia che il file si invii via pec e che non permetta di salvarlo.

**Comment by denisgottardello** [comment]
Salve a tutti. Ho dovuto spostare il Odoo 11 su altro server. Ho quindi reistallato tutto ed eseguito il restore del database.
Se Fatttua elettronica -> File e-fattura esportati manca il tasto per poter scaricare il file xml.
Sembra infatti che manchino il tasto che permette di produrre il file xml. Se vado in Action -> Esporta fattura elettronica ottengo l'errore

odoo.exceptions.UserError: ('File e-fattura già presente per la fattura INV/2019/0017.', '')
except (SimpleFacetValueError, SimpleTypeValueError) as e:
NameError: name 'SimpleFacetValueError' is not defined

Sembra che manchi il tasto che permetteva di salvare il file xml in locale.

**Comment by denisgottardello** [comment]
Up!

**Comment by sergiocorato** [comment]
ciao Denis,
non si capisce bene la richiesta, il file è possibile generarlo se non c'è già (nella prima versione la risposta di Odoo era appunto quella). Se non hai ripristinato il filestore, chiaramente non lo troverebbe. Ti confermo che non è stato tolto il bottone, il file è sempre accessibile e salvabile.

**Comment by denisgottardello** [comment]
Porta pazienza, mi aiuto con uno screenshot.
http://www.denisgottardello.it/01.png
Come si vede la scritta puntata dalla freccia rossa non è cliccabile. A me sembra di ricordare che cliccando lì si potesse scaricare il file. Altri modi non ne vedo.

Se clicco sul pulsante puntato dalla freccia gialla ottengo l'errore
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by sergiocorato** [comment]
Nessun problema,
il file cliccabile sarebbe in corrispondenza del campo `File content` che qui non c'è, probabilmente non hai ripristinato il filestore, che è la cartella in cui Odoo salva gli allegati e i file in generale.

**Comment by denisgottardello** [comment]
Ero convinto che per fare il backup completo bastasse fare il backup da manage database.
Oltre a quei file posso aver perduto altro?

**Comment by eLBati** [comment]
Chiudo in quanto sembra una richeista di supporto.

@denisgottardello in caso fosse un malfunzionamento, ti chiedo di descriverlo con i passi per riprodurlo, il comportmaneto osservato ed il comportamento atteso.

Per domande generali su odoo, puoi usare il forum https://www.odoo-italia.org/forum/forum-1
Per discussioni relative ai gruppi di lavoro, le mailing list https://www.odoo-italia.org/groups
