### ISSUE TITLE
public chat, reachable from any project

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/l10n-italy#120]
Hello World!
May I offer you a useful public chat?
It is gitter and it is reachable from any project, simply adding some text in README file.

You can see https://github.com/antoniov/tools just for example
This README.rst contains:
- build ref
- coverall ref
- rst text
-chat ref link   <---

Everybody would chat with you can click from github.
Simple, easy and free

Thanks

**Comment by eLBati** [comment]
Additional Italian info at http://www.odoo-italia.org/index.php/kunena/14-pianificazione-attivita/12776-chat-sviluppatori
