### ISSUE TITLE
[10.0] l10n_it_ddt: valore del campo product_id.note

### ISSUE THREAD

**Issue by mamojdick** [OCA/l10n-italy#1201]
Versioni coinvolte: 10.0
Salve,
sottopongo  qui la problematica anche se credo dipenda dal modulo dipendenza: stock_picking_package_preparation

Passi per riprodurre: 
  creare un movimento con DDT inserendo un  NOTA nella riga prodotto

Comportamento osservato:
  cliccando sul tasto "Pacco completo" (stock_picking_package_preparation.action_done) il valore del campo "product_id.note" nel DB viene cancellato/perso

Comportamento atteso:
  il valore dovrebbe propagarsi.

Video/Screenshot (opzionale):
![Schermata a 2019-04-23 16-59-37](https://user-images.githubusercontent.com/48570656/56592104-41ab2a80-65ea-11e9-8400-4b57d5b600a6.png)

![Schermata a 2019-04-23 17-03-21](https://user-images.githubusercontent.com/48570656/56592125-4ec81980-65ea-11e9-8b77-40d41aa77a52.png)

![Schermata a 2019-04-23 17-07-01](https://user-images.githubusercontent.com/48570656/56592133-525ba080-65ea-11e9-955e-118e3de8467a.png)

**Comment by sergiocorato** [comment]
chiudo per inattività
