### ISSUE TITLE
Come usare se uso portale del commercialista?

### ISSUE THREAD

**Issue by gbounch** [OCA/l10n-italy#1202]
Versioni coinvolte: 11

Sto usando il modulo per emettere le fatture, poi le esporto singolarmente e le carico sul portale fornito dal commercialista (Sistemi).
Come é possibile usarlo in questo modo visto che non posso usare il canale pec?
Devo per forza fare tutto a mano? sia in spedizione sia in ricezione?
Se si é prevista una procedura di esportazione massiva degli xml e di importazione massiva degli stessi?
Grazie

**Comment by gbounch** [comment]
Sto usando il modulo per emettere le fatture, poi le esporto singolarmente e le carico sul portale fornito dal commercialista (Sistemi).
Come é possibile usarlo in questo modo visto che non posso usare il canale pec?
Devo per forza fare tutto a mano? sia in spedizione sia in ricezione?
Grazie

**Comment by sergiocorato** [comment]
Puoi informarti se qualcuno ha sviluppato un connettore, per la localizzazione è stato scelto di sviluppare quello che non prevede dipendenze da fornitori esterni.

**Comment by sergiocorato** [comment]
(tra parentesi, per l'esportazione massiva c'è un modulo)

**Comment by eLBati** [comment]
Che per la 11 è da portare: https://github.com/OCA/l10n-italy/issues/1051
