### ISSUE TITLE
[FIX] l10n_it_fatturapa_out: DatiRiepilogo is mandatory but tax_line_ids is not required

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1204]
**Versioni coinvolte**
 - [x] v8: #1226 
 - [x] v10: #1205
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1604

**Passi per riprodurre**
1. Creare una fattura cliente, senza le Voci imposta
2. Validare la fattura
3. Aprire il wizard di generazione della fattura elettronica e confermare

**Comportamento osservato**
Errore:
```
IncompleteElementContentError: (<odoo.addons.l10n_it_fatturapa.bindings.fatturapa_v_1_2.DatiBeniServiziType object at 0x7f6fb8653ad0>, <pyxb.utils.fac.Configuration object at 0x7f6fb7d137d0>, [<pyxb.binding.basis.ElementContent object at 0x7f6fb8168410>, <pyxb.binding.basis.ElementContent object at 0x7f6fb8168350>, <pyxb.binding.basis.ElementContent object at 0x7f6fb87d8c90>], {})
```
**Comportamento atteso**
Un errore parlante, che spieghi cosa c'è di sbagliato nella fattura che restituisce errore

**Comment by sergiocorato** [comment]
sarebbe da rendere obbligatorio il modulo per l'imposta obbligatoria nelle righe fattura

**Comment by SimoRubi** [comment]
> sarebbe da rendere obbligatorio il modulo per l'imposta obbligatoria nelle righe fattura

non so che modulo sia.

@sergiocorato le imposte nelle righe fattura c'erano, e c'è già un controllo che solleva un'eccezione quando qualche riga è senza imposte: https://github.com/OCA/l10n-italy/blob/01b815f74996b8581d9a025ddbeb61047a45f5a6/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L626

Non so come sia stato possibile, ma in quella fattura non c'erano le Voci imposta 'riassuntive'.
Siccome c'è la discrepanza in oggetto, credo che la soluzione meno invasiva sia il controllo che aggiungo in https://github.com/OCA/l10n-italy/pull/1205

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v18, è stato fatto il merge della relativa PR.

**Comment by eLBati** [comment]
Per v12: https://github.com/OCA/l10n-italy/pull/1604

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
