### ISSUE TITLE
[IMP] l10n_fatturapa_in: Durante il link, riportare i dati della fattura elettronica nella fattura fornitore 

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1208]
Versioni coinvolte:
 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1209
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1305

Nel wizard che collega una fattura elettronica a una fattura in Odoo, permetto di collegare ogni fattura del file ad una fattura in Odoo.

Durante il collegamento, vengono riportati i dati della fattura elettronica nel tab **Dettagli e-fattura** della fattura odoo.

I campi **Riferimento fornitore** e **Data fattura** vengono controllati e impediscono la validazione (analogamente ai campi del totale).

**Comment by eLBati** [comment]
@SimoRubi puoi mettere un titolo che riassuma meglio le modifiche?

**Comment by SimoRubi** [comment]
Fatto @eLBati, così va bene?

**Comment by eLBati** [comment]
Mi pare di sì

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
