### ISSUE TITLE
re: errore nell'import del modulo l10n_it_fiscalcode-8.0.0.1

### ISSUE THREAD

**Issue by antwal** [OCA/l10n-italy#121]
Salve,

io non riesco ad importarlo questo modulo; l'errore è il seguente:

Traceback (most recent call last):
  File "/opt/odoo/openerp/http.py", line 537, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/openerp/http.py", line 574, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/openerp/http.py", line 310, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/openerp/service/model.py", line 113, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/openerp/http.py", line 307, in checked_call
    return self.endpoint(*a, **kw)
  File "/opt/odoo/openerp/http.py", line 803, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/openerp/http.py", line 403, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/addons/web/controllers/main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "/opt/odoo/addons/web/controllers/main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 450, in button_immediate_install
    return self._button_immediate_function(cr, uid, ids, self.button_install, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 494, in _button_immediate_function
    function(cr, uid, ids, context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 417, in button_install
    self.state_update(cr, uid, ids, 'to install', ['uninstalled'], context=context)
  File "/opt/odoo/openerp/api.py", line 241, in wrapper
    return old_api(self, *args, **kwargs)
  File "/opt/odoo/openerp/api.py", line 363, in old_api
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 408, in state_update
    self.check_external_dependencies(module.name, newstate)
  File "/opt/odoo/openerp/addons/base/module/module.py", line 381, in check_external_dependencies
    raise orm.except_orm(_('Error'), msg % (module_name, e.args[0]))
except_orm: (u'Errore', u'Non \xe8 possibile installare il modulo "l10n_it_fiscalcode" perch\xe8 alcune dipendenze esterne non sono presenti: No module named codicefiscale')

il modulo installato è questo:
...
drwxr-xr-x   3 root root   4096  6 apr 18.14 cfnbootstrap
-rw-r--r--   1 root root   7531 14 lug 17.19 codicefiscale-0.8-py2.7.egg
drwxr-xr-x   2 root root   4096  6 apr 18.16 colorama
drwxr-xr-x   2 root root   4096  6 apr 18.16 colorama-0.3.3.egg-info
...

test python path inclusi:

Python 2.7.9 (default, Apr  1 2015, 18:18:03) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print sys.path
['', '/usr/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/site-packages/pip-6.0.8-py2.7.egg', '/usr/local/lib/python2.7/site-packages/Werkzeug-0.10.4-py2.7.egg', '/usr/local/lib/python2.7/site-packages/codicefiscale-0.8-py2.7.egg', '/usr/local/lib/python2.7/site-packages/unicodecsv-0.13.0-py2.7.egg', '/usr/lib64/python27.zip', '/usr/lib64/python2.7', '/usr/lib64/python2.7/plat-linux2', '/usr/lib64/python2.7/lib-tk', '/usr/lib64/python2.7/lib-old', '/usr/lib64/python2.7/lib-dynload', '/usr/local/lib64/python2.7/site-packages', '/usr/local/lib/python2.7/site-packages', '/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/usr/lib64/python2.7/dist-packages', '/usr/lib64/python2.7/dist-packages/PIL']

Moduli installati su python 2.7:

[root@ip-172-30-1-108 ~]# pip2.7 freeze
You are using pip version 6.0.8, however version 7.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
aws-cfn-bootstrap==1.4
awscli==1.7.23
Babel==1.3
bcdoc==0.13.0
botocore==0.104.0
codicefiscale==0.8
colorama==0.3.3
decorator==3.4.0
docutils==0.12
feedparser==5.1.3
gdata==2.0.18
gevent==1.0.1
greenlet==0.4.2
jcconv==0.2.3
Jinja2==2.7.3
jmespath==0.6.2
lxml==3.3.5
Mako==1.0.0
MarkupSafe==0.23
mock==1.0.1
passlib==1.6.2
Pillow==2.5.1
psutil==2.1.1
psycogreen==1.0
psycopg2==2.5.3
pyasn1==0.1.7
PyChart==1.39
pycrypto==2.6.1
pydot==1.0.2
pyparsing==1.5.7
pyPdf==1.13
pyserial==2.7
python-dateutil==1.5
python-ldap==2.4.15
python-openid==2.2.5
python-stdnum==1.0
pytz==2014.4
pyusb==1.0.0b1
PyYAML==3.11
qrcode==5.0.1
reportlab==3.1.8
requests==2.3.0
rsa==3.1.4
simplejson==3.5.3
six==1.7.3
unicodecsv==0.13.0
unittest2==0.5.1
vatnumber==1.2
vobject==0.6.6
Werkzeug==0.10.4
xlwt==0.7.5
yum-metadata-parser==1.1.4

se faccio un test con python facendo l'import funziona tutto, 
però non riesco ad installare questo modulo per il codice fiscale xkè manca sempre codicefiscale

Non sò quale sia il problema.

Grazie.

**Comment by antwal** [comment]
Salve,

sul sorgente vedo nel file /l10n_it_fiscalcode/wizard/compute_fc.py

import datetime
from codicefiscale import build

quindi ho presunto che l'errore stava nell'import di openerp delle dipendeze visto che con python funziona l'importazione come da codice

quindi ho commentato questa riga:

    'external_dependencies': {
        #'python': ['codicefiscale'],
    },

adesso l'installazione funziona 

ho testato il module e funziona anche quello; quindi presumo che l'errore sta nell'import

problema risolto, con un commento anche se non è la cosa giusta da fare; xkè dovrebbe funzionare.

**Comment by tafaRU** [comment]
Ciao

> adesso l'installazione funziona

Stai facendo riferimento all'installazione di odoo [1] o del modulo https://github.com/OCA/l10n-italy/tree/8.0/l10n_it_fiscalcode [2]?

Se [1] ti chiederei di testare https://github.com/OCA/l10n-italy/pull/122
Se [2] vedi https://github.com/OCA/l10n-italy/issues/93 ed in tal caso chiuderei la issue.

**Comment by antwal** [comment]
Ciao,

vista la issue #93 ma fatto anche "pip install codicefiscale" e da quel problema; se commento la dipendenza giustamente installa e però funziona; senza commento anche il modulo python è installato continua a dire che non lo trova; 

quindi chiudere la issue non mi sembra proprio il caso; ci sarebbe da capire qual'è il problema.

Grazie.

**Comment by tafaRU** [comment]
> quindi chiudere la issue non mi sembra proprio il caso; ci sarebbe da capire qual'è il problema.

Vedi https://github.com/OCA/l10n-italy/issues/121#issuecomment-121372974

**Comment by antwal** [comment]
come detto sopra; fatti tutti i test; il modulo è installato e funzionante; fatto anche #121 come test; se non commento il codice non riesco ad installare il vostro modulo.

**Comment by dcorio** [comment]
è un problema conosciuto.
odoo a volte non vede pacchetti egg per via del parametro zip_safe mi pare.
conviene quindi commentare la riga nel __openerp__.py e installare il modulo.

**Comment by antwal** [comment]
ok, grazie non sapevo di questo problema di Odoo; quindi possiamo chiudere.

**Comment by eLBati** [comment]
@dcorio Qual è il problema conosciuto? E' legato all'importazione del modulo come zip?

**Comment by dcorio** [comment]
@eLBati è legato a come viene pacchettizzato l'egg della libreria python.
se non erro c'è stato in passato lo stesso problema con unidecodecsv.
qualcuno (forse Bessi) disse che non ci potevamo fare nulla.
testare la presenza del modulo python con un try è quindi forse l'unica strada?

**Comment by antwal** [comment]
Confermo anche problema con il modulo "Base Location Geonames Import" che usa unicodecsv; risolto provvisoriamente commentando codice...

**Comment by ginfriz** [comment]
Buongiorno a tutti,
sono un novellino sia in odoo che python.
ho lo stesso problema riportato qui sopra, ma non ho capito dove, come e che riga devo commentare.
mi potete dare una mano?
Grazie

**Comment by eLBati** [comment]
Ciao @ginfriz 
se ti riferisci a
> No module named codicefiscale

devi installare il modulo python
```pip install codicefiscale```

**Comment by ginfriz** [comment]
Ciao eLBati
ho installato python 3.5 64bit per windows
aperto il terminale python e mi da il seguente errore:
![schermata 10-2457326 alle 15 35 27](https://cloud.githubusercontent.com/assets/15422756/10848354/e51c02fc-7f1b-11e5-99d9-6fd836cfef0c.png)
i miei problemi sono se voglio installare i seguenti moduli con i rispettivi errori:

l10n_it_fiscalcode ------> No module named codicefiscale
base_location_geonames_import ------> No module named unicodecsv 

non so proprio come risolvere
Grazie a tutti

**Comment by eLBati** [comment]
@ginfriz per questo tipo di supporto ti consiglio di scrivere su
http://www.odoo-italia.org/index.php/kunena/home
