### ISSUE TITLE
[10] Errore Bollo virtuale genera fattura non valida

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1212]
Buona sera, ho riscontrato il seguente problema:

Nella compilazione della fattura, una volta inserito il bollo virtuale dal tab "Altre informazioni"
Compare sotto le righe della fattura il pulsante "Aggiungi tax  stamp line" 

se invece di aggiungere manualmente il bollo virtuale creato nei prodotti clicco sul pulsante relativo, mi aggiunge si la riga del bollo virtuale, ma la fattura generata è errata  e mi è tornata indietro dal SDI con il seguente errore:

"SdI ID: xxxxxxxxxxxxxxxx; Message ID: xxxxxxxxxxxxxxxx; Receipt date: 2019-04-29T20:04:00.000+02:00; Error: 
[00422] 2.2.2.5 ImponibileImporto non calcolato secondo le regole definite nelle specifiche tecniche : Per la fattura: FAT/2019/0030 del 2019-04-29 Non disponibil"

verificando la differenza con una fattura precedentemente emessa ho visto che nella fattura precedentemente emessa con bollo virtuale inserito maualmente ho nel Riepilogo iva : 
-------------------------------------------------
Dati di riepilogo per aliquota IVA e natura
Aliquota IVA (%):  0.00
Natura operazioni:  N2
(non soggette) Totale imponibile/importo:  300.00
Totale imposta: 0.00
Riferimento normativo:  art1 c54-89 L. 190/2014
Aliquota IVA (%): 0.00
Natura operazioni:  N1
(escluse ex art.15)
Totale imponibile/importo:  2.00
Totale imposta:  0.00
Riferimento normativo:
------------------------------------------------

Mentre nella fattura generata cliccando sul bottone sotto le righe fattura, errata, ho:
------------------------------------------------
Dati di riepilogo per aliquota IVA e natura
Aliquota IVA (%): 0.00
Natura operazioni: N2
(non soggette)
Totale imponibile/importo: 200.00
Totale imposta: 0.00
Riferimento normativo: art1 c54-89 L. 190/2014
---------------------------
difatto manca i campi tasse per il bollo.

Grazie
Enrico

**Comment by bitit-it** [comment]
ho trovato come eliminare il file , file eliminiato  vorrei eliminare la riga del bollo e rimetterla manualmente ma ho questo errore :
The operation cannot be completed, probably due to the following:
- deletion: you may be trying to delete a record while other records still reference it
- creation/update: a mandatory field is not correctly set

[object with reference: Invoice Line - account.invoice.line]

**Comment by sergiocorato** [comment]
Il bottone serve solo ad addebitare al cliente il bollo, non fa compilare l'xml con i dati del bollo, per cui è ininfluente ai fini fiscali.
Il flag è quello che conta, e viene messo in automatico se è stato configurato correttamente il prodotto bollo (in Configurazione della Contabilità) e mettendo le aliquota iva su cui è applicabile, altrimenti lo puoi flaggare manualmente (dovrebbe comunque essere inserito nell'xml, non ti risulta?).

**Comment by bitit-it** [comment]
Se flaggo dal tab "Altre informazioni" viene inserito il bollo nel xml  ma non nell'importo in fattura; per tanto giustamente il software ti propone di aggiungere la riga del bollo; ma se l'aggiungi con il bottone, la fattura è errata, perchè nel riepilogo dati iva non viene inserito i dati relativi al bollo; se l'aggiungi manuelamente dalla lista prodotti, con il bollo che ho configurato precedentemente è corretta.

**Comment by bitit-it** [comment]
![pulsantebollo](https://user-images.githubusercontent.com/43685677/56983361-bdc1e700-6b83-11e9-9dca-57e3cf88ce0a.jpg)

**Comment by bitit-it** [comment]
![Screenshot_20190430_201056](https://user-images.githubusercontent.com/43685677/56983567-3a54c580-6b84-11e9-9e2d-fee2fe47d2d1.jpeg)

**Comment by sergiocorato** [comment]
Nel bollo hai configurato le imposte applicabili?
![Screenshot_2019-04-30 Configurazione Contabilità - Odoo](https://user-images.githubusercontent.com/7657311/56986296-aafee080-6b8a-11e9-8bb7-5a08b037d0f8.png)
I conti vendita e costo e imposte?

**Comment by bitit-it** [comment]
in: # prodotti vendibili / Bollo virtuale 2 euro 
mi pare di aver messo tutto, ma ripeto, se inserisco manualmente la riga del bollo,  selezionado dai prodotti il bollo virtuale, è tutto ok; invece se clicco sul pulsante sotto le righe fattura , che ho cerchiato nell'immagine di prima, mi  crea quell'errore che ho indicato.
![Screenshot_20190430_215426](https://user-images.githubusercontent.com/43685677/56989660-45632200-6b93-11e9-8e59-5fe03f14f456.jpeg)

**Comment by sergiocorato** [comment]
Questo flag quindi è visibile?
![Screenshot_2019-04-30 Nuovo - Odoo](https://user-images.githubusercontent.com/7657311/56994214-ba882480-6b9e-11e9-937a-66b83855d855.png)
No, vedo che non hai messo niente nel campo `Imposte marca da bollo`

**Comment by bitit-it** [comment]
> No, vedo che non hai messo niente nel campo Imposte marca da bollo

è vero, ma perchè se inserisco la riga  del bollo virtuale manualmente selezionandolo dai prodotti la fattura viene correttamente compilata, ivece se clocco sul bottone "Aggiungi tax stamp line" no?

Imposte marca da bollo non ci sono imposte è già indicato sopra, fuori campo iva, perchè dovrebbe essere messo due volte?

**Comment by sergiocorato** [comment]
> Imposte marca da bollo non ci sono imposte è già indicato sopra, fuori campo iva, perchè dovrebbe essere messo due volte?

Perchè dovrebbe esserci un campo doppio? Va impostato perchè non sono le imposte che si applicano all'imposta di bollo, ma le imposte a cui si applica l'imposta di bollo.

**Comment by bitit-it** [comment]
e che  ci metto? scusa ma il bollo mi risulti si applica all'imponibile  sopra a 77, espiccioli , al posto dell'iva , non ad una imposta.

**Comment by primes2h** [comment]
Il giorno mer 1 mag 2019 alle ore 15:10 Enrico Maria Chellini <
notifications@github.com> ha scritto:

> e che ci metto? scusa ma il bollo mi risulti si applica all'imponibile
> sopra a 77, espiccioli , al posto dell'iva , non ad una imposta.
>

L'imposta che definisci nel prodotto bollo è quella sulla quale viene
calcolato automaticamente il raggiungimento della soglia imponibile (es. 77
€ e spiccioli) nelle righe della fattura:

Esempio pratico.

Definisci un'imposta X associata al prodotto bollo.
Iinserisci 4 righe nella fattura, tre con la stessa imposta X definita nel
prodotto bollo e una con un'imposta Y differente.

Il calcolo del raggiungimento dei 77 € e spiccioli viene fatto "solo" sulle
righe che contengono l'imposta X che hai definito nel prodotto bollo, in
questo caso tre righe, la quarta non viene presa in considerazione.
Se la somma degli imponibili supera la soglia, nell'xml ti ritroverai il
campo bollo valorizzato.

**Comment by bitit-it** [comment]
@primes2h  A primo pensiero in quel campo ci metto "non soggetto" ovvero che il bollo essendo una tassa di per se non è soggietta a imposte; ma in base a quello che mi dici te i dovrei creare un altra imposta di 2 euro da associare al bollo? e inserirla in quel campo?
non è un po' macchinoso?
e ripeto il problema che mi ritrovo è: 
se (inserisco il bollo manualmente da prodotti nelle righe fattura,) {la fattura  risulta valida},  
 se (clicco sul pulsante per inserire la riga bollo con procedura semplificata) {no}.

se la riga si dovesse aggiungere automaticamente, campo bollo valorizato,  a che serve il pulsante?

Enrico

**Comment by primes2h** [comment]
Il giorno mer 1 mag 2019 alle ore 15:41 Enrico Maria Chellini <
notifications@github.com> ha scritto:

> @primes2h <https://github.com/primes2h> A primo pensiero in quel campo ci
> metto "non soggetto" ovvero che il bollo essendo una tassa di per se non è
> soggietta a imposte;
>
Esatto, "non soggetto", "esente" ecc. sono sempre tipi di imposte, solo di
tipo particolare perché sono a 0.


ma in base a quello che mi dici te i dovrei creare un altra imposta di 2
> euro da associare al bollo? e inserirla in quel campo?
>
No, puoi usare quella esistente basta che selezioni un'imposta (es "non
soggetto") corrispondente.


e ripeto il problema che mi ritrovo è:
> se (inserisco il bollo manualmente da prodotti nelle righe fattura,) {la
> fattura risulta valida},
> se (clicco sul pulsante per inserire la riga bollo con procedura
> semplificata) {no}.
>
> se la riga si dovesse aggiungere automaticamente, campo bollo valorizato,
> a che serve il pulsante?
>

Sono due cose diverse.

Dopo aver aggiunto l'imposta "non soggetto) al prodotto bollo (vedi sopra),
nella fattura non serve che selezioni la casella bollo.
Al raggiungimento automatico della soglia quella casella viene selezionata
automaticamente.
Se invece la selezioni manualmente ti comparirà nell'xml a prescindere
dalla soglia [*]

Il pulsante invece serve solo ad aggiungere una riga specifica che serve ad
addebitare il bollo al cliente, se non c'è quella riga il bollo lo paghi tu.
Ovviamente compare solo quando:
1) raggiungi la soglia dei 77 € con la modalità automatica che quindi
attiva il bollo.
2) selezioni manualmente il bollo

[*] a suo tempo avevo riscontrato qualche criticità nel passaggio da
automatico a manuale, vedi https://github.com/OCA/l10n-italy/issues/823.
La modifica che avevo proposto per la v.12.0  è stata accettata, vedi
https://github.com/OCA/l10n-italy/pull/891.
Se la ritieni valida e vuoi aprire una PR anche per la 10.0 vai pure (per
la 11.0 c'è già una PR aperta), ricordati solo di segnalarla qui
https://github.com/OCA/l10n-italy/issues/1058.

**Comment by bitit-it** [comment]
ho fatto l'aggiornamento all'ultima versione disponibile del bollo virtuale; ma non mi seleziona in automatico il bollo, passato l'imponibile di €.74, espicci .


Enrico
