### ISSUE TITLE
[10] Problema con gestione posta PEC associata a SDI

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1219]
Buon giorno, mi ritrovo il seguente problema:

ho una posta certificata che ho utilizzato per la registrazione alla camera di commercio e corrispondenza certificata varia; stessa posta l'ho collegata al SDI e configurata in Odoo per invio e ricezione fatturazione elettronica.

Riguardo l'ivio e ricezione della fatturazione elettronica nessun problema, tutto ok.
Il problema riscontrato è nell'invio della corrispondenza certificata, dalla mia casella bitit alla casella di altro utente certificato

l'invio avviene correttamente; 

come sempre DOVREI RICEVERE 2 messaggi di PEC uno di accettazione e uno di consegna.

Ricevo invece due messaggi da Odoo  così fatti:
----------------------
Message-Id: <1556788431.606771945953369.733625160461233-openerp-private@localhost>
Subject: Messaggio PEC [CONSEGNA: Richiesta Codice SDI] non elaborato
From: Chellini Enrico Maria <xxx@xxx.it>
Reply-To: Chellini Enrico Maria <xxx@xxx.it>
To: Chellini Enrico Maria <xxx@xxx.it>
Date: Thu, 02 May 2019 09:18:56 -0000

Il messaggio PEC con message-ID  è stato letto ma non elaborato, perché non è relativo a una e-fattura.
Controllare la casella PEC pec: server pop3s.pec.xxx.it, utente xxx@pec.xxx.it

--------------------------

Il problema è che spariscono i messaggi originali di Accettazione e Conferma, sembra che odoo li cancelli dal server , solo questi gli altri arrivano correttamente anche nella PEC

La configurazione che ho fatto del server in ricezione è in POP flaggando di mantenere l'originale ;  prima di provare l'IMAP vorrei capire il problema e nel caso risolverlo 

Enrico

**Comment by eLBati** [comment]
Come mai POP?
Temo che POP non sia mai stato testato e personalmente lo sconsiglio fortemente.

Idealmente sarebbe da togliere dalle opzioni o almeno documentarlo

**Comment by bitit-it** [comment]
perchè non lasciando i messaggi sul server PEC, ho pensato che mettendolo in IMAP e  cancellando i messaggi vecchi con le fatture si venisse a creare qualche problema con l'archivio di Odoo, che ha come riferimento quello che c'è in IMAP. 

Enrico
