### ISSUE TITLE
l10n_it_fatturapa NumeroCivico with empty space: SimpleFacetValueError

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1220]
Versioni coinvolte:

 - [ ] v8
 - [X] v10: https://github.com/OCA/l10n-italy/pull/1218
 - [ ] v11
 - [ ] ~v12~

Passi per riprodurre:

Importare un XML con `<NumeroCivico> </NumeroCivico>`

Comportamento osservato:

> SimpleFacetValueError: Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}NumeroCivicoType pattern constraint violated by value

Comportamento atteso:

L'XML viene importato

**Comment by sherpya** [comment]
ma esattamente quando arriva un civico con uno spazio e basta che si fa? non è che sarebbe meglio eliminare l'entry come sto provando a fare come con #1218? riduciamo anche le patch all'xsd

**Comment by eLBati** [comment]
> ma esattamente quando arriva un civico con uno spazio e basta che si fa?

In odoo viene lasciato il campo vuoto

> non è che sarebbe meglio eliminare l'entry come sto provando a fare come con #1218? riduciamo anche le patch all'xsd

Quindi anche per i vari StringNType?
Per me OK. Vuoi provare ad aggiungerlo a https://github.com/OCA/l10n-italy/pull/1218 ?

**Comment by sherpya** [comment]
per quelli con `minOccurs="0"` se uno obbligatorio è uno spazio che succede? teoricamente l'ade dovrebbe rimbalzarli, se non è opzionale suppongo che debba essere valorizzato

**Comment by eLBati** [comment]
> teoricamente l'ade dovrebbe rimbalzarli

riesci a verificare questo?

**Comment by sherpya** [comment]
> > teoricamente l'ade dovrebbe rimbalzarli
> 
> riesci a verificare questo?

devo chiedere a @letyf1988 io di solito non traffico con l'ADE :D

**Comment by sherpya** [comment]
ma non c'è un xsd ufficiale? ho appena trovato questo https://github.com/italia/fatturapa-testsdi/blob/master/core/schemas/Schema_del_file_xml_FatturaPA_versione_1.2_cleanup.xsd

rispetto a quello che ho io in più c'è:
```xml
      <xs:enumeration value="RF03">
        <xs:annotation>
          <xs:documentation>Regime delle nuove iniziative produttive (art. 13, L. 388/2000)</xs:documentation>
        </xs:annotation>
      </xs:enumeration>
```
;(

**Comment by sherpya** [comment]
pare sia stato rimosso nella 1.2.1

**Comment by eLBati** [comment]
> devo chiedere a @letyf1988 io di solito non traffico con l'ADE

Se vuoi mandarmi degli XML posso anche testarli io

> ma non c'è un xsd ufficiale?

Io mi son sempre basato su questo https://www.fatturapa.gov.it/export/fatturazione/sdi/fatturapa/v1.2.1/Schema_del_file_xml_FatturaPA_versione_1.2.1.xsd
che dovrebbe essere uguale a questo https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Schema+VFPR12./Schema_VFPR12.xsd

**Comment by sherpya** [comment]
le string obbligatorie sono tante, molte non hanno proprio senso di essere vuote, ma per sempio  `Indirizzo` dentro `IndirizzoType` potrebbe aver senso provarlo, o meglio ancora `Descrizione` in `DettaglioLineeType`, prova a mettere uno spazio vuoto e vedere se se l'accolla.

per quanto riguarda l'xsd sembra l'ultimo ufficiale sia 1.2.1, ma l'autofattura sta in un fantomatico 1.3 (introvabile)

**Comment by sherpya** [comment]
se ci metto `_` o qualche altro testo quando è vuoto?

**Comment by eLBati** [comment]
@sherpya un file con `<Descrizione> </Descrizione>` non viene scartato da SDI...

> se ci metto _ o qualche altro testo quando è vuoto?

Penso possa andare bene (mi piace di più `-` :nerd_face:  )

**Comment by SimoRubi** [comment]
In `12.0` questo dovrebbe essere risolto, c'è anche un test: https://github.com/OCA/l10n-italy/blob/4c43e0efd55035f9f9880158e2e7416dda304e96/l10n_it_fatturapa_in/tests/data/IT02780790107_11004_xml_doctor.xml#L138

**Comment by eLBati** [comment]
Sì, era già stato risolto con XML doctor (https://github.com/OCA/l10n-italy/issues/1172) e poi successivamente anche refactored con https://github.com/OCA/l10n-italy/issues/1312
Penso che questa si possa chiudere

**Comment by primes2h** [comment]
Chiudo.
