### ISSUE TITLE
Acconto su fattura "Down payment" , da foglio di stile 

### ISSUE THREAD

**Issue by DavideSavoneEVE** [OCA/l10n-italy#1223]
Versioni coinvolte:

Passi per riprodurre:

Comportamento osservato:

Comportamento atteso:

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
@DavideSavoneEVE puoi descrivere i Passi per riprodurre, il Comportamento osservato ed il Comportamento atteso?

**Comment by primes2h** [comment]
Nessuna risposta da chi aveva aperto la issue molto tempo fa, chiudo.
