### ISSUE TITLE
[FIX] l10n_it_corrispettivi_sale: Cambia flag corrispettivi da posizione fiscale

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1224]
**Versioni coinvolte**
 - [ ] v8: 
 - [x] v10: #1225 
 - [ ] v11: 
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1417

Passi per riprodurre:
1. Creare una posizione fiscale avente il flag 'corrispettivi' abilitato
2. Creare un ordine di vendita
3. Assegnare la posizione fiscale del punto 1

**Comportamento osservato**
Il flag corrispettivi non cambia

**Comportamento atteso**
Il flag corrispettivi prende il valore del rispettivo flag nella posizione fiscale

**Comment by eLBati** [comment]
@SimoRubi plis review https://github.com/OCA/l10n-italy/pull/1417

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
