### ISSUE TITLE
Data fattura elettronica non prevista

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1228]
Versioni coinvolte:

- [ ] v. 8.0: 
- [x] v. 10.0: #1218
- [ ] v. 11.0: 
- [x] v. 12.0: https://github.com/OCA/l10n-italy/pull/1243

Passi per riprodurre: ricevere una fattura con date nel formato `<Data>2019-04-30+02:00</Data>`

Comportamento osservato: non crea la fattura

Comportamento atteso: crea la fattura

Simile alla #1172, poi non si capisce che data dovrebbe essere, 1 maggio? Forse è il caso di tagliare il campo ai primi 10 caratteri?

**Comment by eLBati** [comment]
Non crea la fattura dando errore?

**Comment by sergiocorato** [comment]
![immagine](https://user-images.githubusercontent.com/7657311/57304094-f6f7db00-70de-11e9-824a-a72e6ffb43f0.png)

**Comment by eLBati** [comment]
@sherpya non ricordo: la https://github.com/OCA/l10n-italy/pull/1218 risolve questa issue?

**Comment by sherpya** [comment]
> @sherpya non ricordo: la #1218 risolve questa issue?

ma già doveva funzionare con l'altra fix (pyxb 1.2.6), in realtà però mi sembra un errore diverso,

@sergiocorato provala con #1218

**Comment by eLBati** [comment]
@sergiocorato il problema c'è ancora?

**Comment by sergiocorato** [comment]
> @sergiocorato il problema c'è ancora?

sulla 10.0 è risolto

**Comment by eLBati** [comment]
Quindi assumo anche sulla 12.

Questa issue si può chiudere in favore della https://github.com/OCA/l10n-italy/issues/1172 ?
