### ISSUE TITLE
Fattura elettronica per indirizzi di fatturazione

### ISSUE THREAD

**Issue by jackjack82** [OCA/l10n-italy#1231]
Versioni coinvolte:
 - [ ] v8: ??
 - [x] v10: [#1229]
 - [x] v11: [#1232]
 - [x] v12: [#1233]

Descrizione del problema o della funzionalità:

La fattura elettronica ha un campo "Soggetto a fattura elettronica" (electronic_invoice_subjected) che viene ereditato dal cliente (campo related). Se questo campo è True, si vedono diversi tab con i dati della fatturazione elettronica. Se però la fattura è indirizzata all'indirizzo di fatturazione e NON al cliente principale, il campo risulta False, i tab non vengono quindi correttamente visualizzati.

Comportamento attuale prima di questa PR:

Se fatturo all'indirizzo di fatturazione di un cliente soggetto a fattura elettronica non vedo i tab aggiuntivi sulla fattura.

Comportamento desiderato dopo questa PR:

Se fatturo all'indirizzo di fatturazione di un cliente soggetto a fattura elettronica vedo correttamente i tab aggiuntivi.

**Comment by eLBati** [comment]
@sergiocorato @scigghia @OpenCode per la 8 è da fare?

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
