### ISSUE TITLE
l10n_it_fatturapa_out_wt Dettaglio pagamento include nell'importo la ritenuta

### ISSUE THREAD

**Issue by letyf1988** [OCA/l10n-italy#1240]
Versioni coinvolte:

- [ ] 8.0 #1257 
- [ ] 10.0 #1258
- [ ] 11.0
- [ ] 12.0

Passi per riprodurre:
Un  cliente  ha segnalato che, quando genera una fattura attiva con ritenuta d'acconto, il tag "Dettagli Pagamento" mostra l'importo compreso della ritenuta.
Comportamento atteso:
Il Dettaglio pagamento dovrebbe invece mostrare solo il netto da pagare
Sto riflettendo su come sistemare, il problema è che la fattura potrebbe essere suddivisa in tranche. 
Ci sono richieste simili? Avrebbe senso modficare il modulo l10n_it_fatturapa_out_wt ?

**Comment by sergiocorato** [comment]
ehm, avevo dimenticato di fare PR...
