### ISSUE TITLE
[FIX] l10n_it_invoices_data_communication: cessionario cedente

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1241]
Versioni coinvolte:
 - [ ] v8: ?
 - [ ] v10: https://github.com/OCA/l10n-italy/pull/1242
 - [ ] v11: ?
 - [ ] v12: ?

Passi per riprodurre:

1. Creare un fornitore avente CAP con meno di 5 caratteri
2. Creare e validare una fattura per il partner creato
3. Fare comunicazione dati iva contenente la fattura creata
4. Click su 'Controllo errori'

Comportamento osservato:
Eccezione:
```
AttributeError: 'comunicazione.dati.iva.fatture.ricevute' object has no attribute 'cessionario_sede_Cap'
```
Comportamento atteso:
Errore gestito:
```
ZIP %s of seller %s is not 5 characters
```

**Comment by eLBati** [comment]
Sulle altre versioni il modulo non è presente
