### ISSUE TITLE
DettaglioPagamento creation

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1245]
**Versioni coinvolte**
 - [ ] v8: ?
 - [x] v10: #1246
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1265

**Passi per riprodurre**
1. Creare un partner con un conto bancario lasciando però il campo **Banca** vuoto
2. Creare una fattura per il partner e validarla
3. Pagare la fattura in modo che coinvolga il conto bancario creato
4. Esportare la fattura elettronica

**Comportamento osservato**
Errore:
```
Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String80LatinType cannot be created from: False
```

**Comportamento atteso**
La fattura viene esportata

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
