### ISSUE TITLE
Considerare le fatture di anticipo dell'ordine di vendita fatturando il DDT

### ISSUE THREAD

**Issue by OpenCode** [OCA/l10n-italy#1256]
- [x] v8: Comportamento di default
 - [ ] v10: #1255
 - [ ] v11: 
 - [ ] v12:

**Comment by sergiocorato** [comment]
nella 8.0 è di default

**Comment by OpenCode** [comment]
> nella 8.0 è di default

Perfetto. Lo spunto come se fosse già fatto allora ;)
