### ISSUE TITLE
[10.0] Error esportando fattura: String80LatinType cannot be created from: False 

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1259]
Esportando una nota di credito (click su "Esporta e-fattura") ottengo questo errore:

Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String80LatinType cannot be created from: False

Nei log non rilevo altri errori ...

**Comment by sergiocorato** [comment]
Ciao,
Ti sta dicendo che il campo è vuoto (false)
Forse non è compilata correttamente la ritenuta?

Il lun 3 giu 2019, 12:46 protontrigg3r <notifications@github.com> ha
scritto:

**Comment by protontrigg3r** [comment]
Nel campo "Conto bancario" c'era un numero che non corrispondeva ad alcuno dei conti bancari creati in Odoo.

Grazie!
