### ISSUE TITLE
[11.0][12.0] modifica descrizione riga DdT non desiderata

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#1262]
Versioni coinvolte:
penso tutte, ma più probabile dalla 11.0 in poi, siccome prima certe variazioni sui picking non erano possibili.

Passi per riprodurre:
- Creare un picking
- Creare un ddt da quel picking
- modificare la descrizione di una delle righe di dettaglio del ddt
- confermare il picking

Comportamento osservato:
Se la descrizione sulla riga di dettaglio del ddt è stata modificata dall'utente, alla conferma del picking la descrizione della riga ddt viene resettata.

Comportamento atteso:
Se la descrizione è stata modificata manualmente dall'utente, non dovrebbe essere variata automaticamente.

**Comment by dcorio** [comment]
@eLBati @OpenCode qualcuno vi ha già segnalato questo problema? effettivamente è un po' grave siccome si perdono informazioni a volte fondamentali. Non ho verificato qual è il metodo responsabile

**Comment by dcorio** [comment]
@eLBati @OpenCode ignorate, ho analizzato il problema e direi che non si può risolvere.

Non so se la soluzione migliore è avvertire i clienti che se modificano le descrizioni nelle righe ddt, queste vengono variate automaticamente o se conviene rendere quei campo readonly ad esempio.

**Comment by OpenCode** [comment]
@dcorio in realtà io non lo ignorerei. Nella versione 10.0, ad esempio, la stessa parte di codice è colpevole di una cancellazione/riscrittura dei dettagli del DDT se cambia qualcosa nelle classi a cui è legata. Questa modifica scatta anche se si aggiunge un nuovo campo e quindi quando magari si installa un modulo nuovo.

Direi di analizzarla perchè potenzialmente pericolosa

**Comment by dcorio** [comment]
@OpenCode forse possiamo pensare ad un refactoring in vista della 14 (o 13, vediamo).
Oppure bisogna vedere come arginare il problema senza dover procedere ad un refactoring
