### ISSUE TITLE
[ADD] l10n_it_statutory_financial_statements_mapping (Mappatura dei conti per Bilancio CEE Riclassificato)

### ISSUE THREAD

**Issue by OpenCode** [OCA/l10n-italy#1275]
Modulo autoinstallante per la messa in relazione del piano dei conti creato da l10n_it con i gruppi cee introdotti da l10n_it_bilancio_civilistico

- [ ] 8.0
- [ ] 10.0
- [ ] 11.0
- [ ] 12.0 - @ilaria-franchini #1273

**Comment by primes2h** [comment]
Anche qui, come riferimento, vedi
https://github.com/OCA/l10n-italy/issues/1271#issuecomment-499807804

**Comment by eLBati** [comment]
Visto che abbiamo https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_mis_reports_pl_bs , questa la chiudiamo?

Rif https://discord.com/channels/753902328494424064/806815905006223411/885921146585886780
