### ISSUE TITLE
RI.BA. revisione metodo di calcolo costi delle riba

### ISSUE THREAD

**Issue by jackjack82** [OCA/l10n-italy#1284]
Versioni coinvolte:
- [ ] 8.0 : ??
- [ ] 10.0 : #1285
- [ ] 11.0 : ??
- [ ] 12.0 : ??

Passi per riprodurre:

Creo una fattura con termini di pagamento riba con più scadenze ed un costo di spese riba. Valido e Odoo aggiunge una riga con il costo Riba, perfetto. Creo una fattura identica, stessa data e stessi termini di pagamento, la riga di costo Riba NON viene aggiunta.

Questo perché il modulo verifica se esiste già una scadenza associata a quel partner (senza ulteriori filtri) che cade nello stesso mese della prima scadenza della fattura. Se esiste la prima scadenza, la riga di costo Riba NON viene aggiunta.

Codice di rif: https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_ricevute_bancarie/models/account/account.py#L168

Probabilmente il modulo allo stato attuale considera le riba emesse mensilmente, quesot però non è il comportamento di base ma va concordato con la banca. Si potrebbe eventualmente aggiungere un flag e.g. "raggruppamento mensile" e tenere aperte i due diversi metodi di calcolo dei costi Riba.

Comportamento osservato:

Se creo una fattura Riba la cui prima scadenza cade in un mese dove ho già scadenze per quel cliente, NON viene aggiunta in fattura la riga di costo Riba.

Comportamento atteso:

La riga di costo Riba viene SEMPRE aggiunta in fattura.

**Comment by robyf70** [comment]
E' molto strano il fatto che il comportamento del calcolo "una-tantum" mensile e per cliente sia "hard-codato" nel codice. Un comportamento simile della banca non è normale, ed è sempre concordato preventivamente. Di default la banca applica il costo per ogni RIBA emessa.

**Comment by robyf70** [comment]
@jackjack82 Comunque, non parlerei di raggruppamento che è un'altro discorso, qui la questione è che l'addebito dei costi delle RIBA al cliente avviene una tantum nel mese, questo non è un comportamento "standard" di una banca.

La PR per me è ok, magari per chi avesse necessità di ripristinare il comportamento precedente, sarebbe opportuno consentire di ridefinire il comportamento magari a livello di cliente per stabilire se questo ha un addebito flat delle spese di incasso tramite RIBA.
