### ISSUE TITLE
Reverse charge Italia, fattura elettronica

### ISSUE THREAD

**Issue by letyf1988** [OCA/l10n-italy#1287]
Versioni coinvolte:

 - [ ] 8.0
 - [x] 10.0: https://github.com/OCA/l10n-italy/pull/1377
 - [ ] 11.0
 - [x] 12.0 (~~dipende da https://github.com/OCA/l10n-italy/pull/1305~~) https://github.com/OCA/l10n-italy/pull/1403

Passi per riprodurre:
Installare il modulo RC.
Importare la fattura elettronica del fornitore soggetta a RC, aggiungere l'imposta da stornare nella registrazione e nell'autofattura.
Validare la fattura fornitore
Comportamento osservato:
La fattura non viene validata perchè l'importo differisce da quello dell'elettronica.
Comportamento atteso:
La fattura viene validata se Reverse Charge

**Comment by eLBati** [comment]
@letyf1988 mi ricordi quali sono i casi di fatture elettroniche su cui bisogna applicare reverse charge?

**Comment by letyf1988** [comment]
@eLBati  le fatture con imposta "Rev. charge art 17 dpr 633/72".
Tecnicamente stavo pensando a chi ha la posizione fiscale con il tipo RC valorizzato oppure se la fattura fornitore ha flaggato il booleano RC nelle righe della fattura .

**Comment by letyf1988** [comment]
L'imposta nella fattura elettronica ha natura N6

**Comment by eLBati** [comment]
@letyf1988 ok, allora credo che la soluzione sia in https://github.com/OCA/l10n-italy/pull/1053

@robyf70 @sergiocorato cosa resta da fare in https://github.com/OCA/l10n-italy/pull/1053 ?

**Comment by letyf1988** [comment]
@eLBati ok, grazie... se c'è bisogno di una mano o di testare per questo task io ci sono

**Comment by eLBati** [comment]
@letyf1988 puoi testare la https://github.com/OCA/l10n-italy/pull/1053 e dare feedback

**Comment by letyf1988** [comment]
Ciao, provato. Il modulo l10n_it_fatturapa_in_reverse_charge mette il flag RC se la tassa è di tipo N6. Il problema è un altro, mi blocca la validazione con il controllo sul totale della fattura elettronica con quella di ODOO quando vado ad inserire l'imposta al 22% per generare la scrittura contabile e la relativa autofattura  perchè trova la differenza del totale tra i due.

**Comment by letyf1988** [comment]
In realtà "Force invoice validation" potrebbe andar ben  ma credo che con il RC  dovrebbe essere sempre validata.

**Comment by eLBati** [comment]
@robyf70 ^

**Comment by sergiocorato** [comment]
@letyf1988 avevi provato anche la #893? quella parte dal presupposto che l'aliquota al 22% sia già configurata nell'imposta reverse (come presumo facciano gli utenti, voi fate diverso?)

**Comment by eLBati** [comment]
@sergiocorato @robyf70 sto dando un po' di amore a questo problema con https://github.com/OCA/l10n-italy/pull/1377

Se siete d'accordo possiamo chiudere https://github.com/OCA/l10n-italy/pull/1053 e https://github.com/OCA/l10n-italy/pull/893 e proseguire su https://github.com/OCA/l10n-italy/pull/1377 , che le ingloba

**Comment by robyf70** [comment]
@eLBati Per me ok

**Comment by sergiocorato** [comment]
@eLBati ottimo

**Comment by eLBati** [comment]
La https://github.com/OCA/l10n-italy/pull/1377 dovrebbe essere pronta.
@letyf1988 @sergiocorato @robyf70 potete testare/revisionare?

**Comment by robyf70** [comment]
@eLBati Ho fatto un test con solo righe N6 ed aliquota a zero ma non non riesco a validarla

**Comment by robyf70** [comment]
@eLBati Avevo la configurazione non corretta! Per me la PR è ok

**Comment by letyf1988** [comment]
@eLBati per me la PR è ok

**Comment by eLBati** [comment]
@letyf1988 @robyf70 @sergiocorato per la 12: https://github.com/OCA/l10n-italy/pull/1403

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
