### ISSUE TITLE
fatturazione servizi da DDT

### ISSUE THREAD

**Issue by jackjack82** [OCA/l10n-italy#1289]
Versioni coinvolte:

-[] 8.0
-[] 10.0: #1288
-[] 11.0
-[] 12.0

Inseriamo un nuovo metodo vuoto (con "pass") all'interno del metodo di fatturazione del ddt.

Questo può essere ereditato per integrare il flusso. Ad esempio per fatturare i servizi, altra PR.

**Comment by eLBati** [comment]
Chiudo in favore di https://github.com/OCA/l10n-italy/issues/1291
