### ISSUE TITLE
Fatturazione servizi da DDT

### ISSUE THREAD

**Issue by jackjack82** [OCA/l10n-italy#1291]
Versioni coinvolte:
- [ ] 8.0
- [x] 10.0: https://github.com/OCA/l10n-italy/pull/1288
- [ ] 11.0
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/1320

Passi per riprodurre:

Creo ordine con prodotti stoccabili, consumabili e servizi. Creo movimento di magazzino, valido e creo DDT. Quando creo fattura da DDT i servizi non sono inclusi (ovviamente). Il rischio è che il cliente dimentichi di fatturare i servizi o debba farlo manualmente o in fattura a parte.

Comportamento osservato:

Quando creo fattura da DDT i servizi non sono inclusi (ovviamente).

Comportamento atteso:

Quando creo fattura da DDT i servizi sono inclusi. Posso evitare che siano fatturati configurando campo booleano ("Escludi da fatturazione ddt"):
- sul prodotto
- sull'ordine
- sul cliente, automaticamente applicato all'ordine 

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Chiudo in favore di https://github.com/OCA/l10n-italy/issues/1291

**Comment by eLBati** [comment]
Sbagliato

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
