### ISSUE TITLE
Valore e tasse errati nel dettaglio DDT nel caso di vendita di KIT

### ISSUE THREAD

**Issue by difra** [OCA/l10n-italy#1296]
Versioni coinvolte: 11.0 / 12.0

**Passi per riprodurre:**

- creo un ordine di vendita con un prodotto con distinta base di tipo KIT
- creo un DDT con la picking generata dall'ordine di vendita
- Valido il DDT

**Comportamento osservato:**

le singole righe del ddt che contengono i componenti ereditano price_unit sconto e tasse dalla riga dell'ordine di vendita che però contiene il prodotto padre della distinta base del KIT.
La fattura creata dal DDT non è coerente con l'ordine di vendita

**Comportamento atteso:**

Nel dettaglio DDT mi aspetto di avere il KIT con lo stesso valore e quantità dell'ordine di vendita.

**Screenshot:**

ordine di vendita
![screenshot-difra-test3-app-l10n-it-ddt-586127 dev odoo com-2019 09 14-16_19_22](https://user-images.githubusercontent.com/3530485/64909482-1ba73380-d70d-11e9-8cea-42906dcd1ee9.png)
ddt
![screenshot-difra-test3-app-l10n-it-ddt-586127 dev odoo com-2019 09 14-16_21_46](https://user-images.githubusercontent.com/3530485/64909481-1b0e9d00-d70d-11e9-946f-e52199385819.png)

**Comment by eLBati** [comment]
Chiudo questa, anche se più vecchia, solo perchè sulla https://github.com/OCA/l10n-italy/issues/1335 c'è già la PR di fix

**Comment by eLBati** [comment]
Riapro dopo https://github.com/OCA/l10n-italy/pull/1336#issuecomment-533860809
