### ISSUE TITLE
Comunicazione liquidazione IVA l10n_it_vat_statement_communication

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1302]
Versioni coinvolte:
- [ ] v. 8.0 #1303 
- [ ] v. 10.0 #1196
- [ ] v. 11.0
- [x] v. 12.0 #1197 #1267 

Passi per riprodurre:

Comportamento osservato:

Comportamento atteso:

Video/Screenshot (opzionale):

**Comment by vincenzoterzulli** [comment]
Scusate ma questa si può chiudere?

**Comment by sergiocorato** [comment]
manca la 11.0

**Comment by vincenzoterzulli** [comment]
avevo capito fosse un backport dalla 11. Pardon!

**Comment by sergiocorato** [comment]
@OCA/local-italy-maintainers per la 11.0 c'è qualcuno interessato? altrimenti possiamo anche chiudere

**Comment by eLBati** [comment]
> altrimenti possiamo anche chiudere

Per la 10 e per la 8 le PR sono aperte, quindi  in realtà no

**Comment by primes2h** [comment]
> > altrimenti possiamo anche chiudere
> 
> Per la 10 e per la 8 le PR sono aperte, quindi in realtà no

@sergiocorato 
se nessuno è interessato attualmente, potrebbe invece esserlo in futuro. 

IMHO, finché non vengono coperte tutte le versioni (almeno quelle supportate ufficialmente [1]),
sarebbe il caso di lasciarle aperte.

[1] a parte la 8.0  :tongue:
