### ISSUE TITLE
Interazione flag "I want invoice" e "I want e-invoice"

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1307]
Interazione dei flag 'Voglio fattura' e 'Voglio fattura elettronica' nel checkout del eCommerce.

**Versioni coinvolte**
 - [ ] v8: ?
 - [ ] v10: sì
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/commit/0822f99134640ab2c8f0885da776dc9b8cf17bee

**Comment by eLBati** [comment]
Nella 12 la funzionalità è in https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_sale_corrispettivi

**Comment by SimoRubi** [comment]
@eLBati ho aggiornato la issue precisando che non serve un nuovo modulo ma basta portare la modifca che tu facesti in https://github.com/OCA/l10n-italy/commit/0822f99134640ab2c8f0885da776dc9b8cf17bee
