### ISSUE TITLE
How can i install that?

### ISSUE THREAD

**Issue by angelocala94** [OCA/l10n-italy#131]
Hi, how can I install l10n-italy on odoo v8? I need the translations of all the base modules on Odoo. Especially the Italian provinces.
Thanks!

**Comment by dcorio** [comment]
@angelocala94 l10n-italy is not something you install. is the name of the repository :)
btw, translation of base module is provided by odoo itself. just need to install the italian language on odoo.
then you need to install l10n_it_base_location_geonames_import to get the italian provinces

**Comment by angelocala94** [comment]
Yep, sorry, i mean the "l10n_it_base_location_geonames_import", and what is the "l10n_it_base" module? For installing i need to simply move the modules folders into odoo addons folder? Once installed, i need to do something for "activating" the modules?

**Comment by dcorio** [comment]
@angelocala94 this is something we should discuss out of github because you're asking how to use odoo. here for instance: http://www.odoo-italia.org

**Comment by angelocala94** [comment]
Thanks
