### ISSUE TITLE
[IMP] l10n_it_fatturapa_in: When linking an e-invoice to an invoice, set reference and invoice date in the invoice if empty

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1310]
Quando viene collegata una fattura elettronica a una fattura in Odoo, i campi `account.invoice.date_invoice` e `account.invoice.reference` vengono controllati rispettivamente con `DatiGenerali.DatiGeneraliDocumento.Data` e `DatiGenerali.DatiGeneraliDocumento.Numero`.

Sarebbe comodo impostare i valori corretti nella fattura in Odoo *se sono vuoti* per evitare che il controllo fallisca.

**Versioni coinvolte**
In questa
 - [ ] v8: ?
 - [x] v10: #1311 
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1392

**Passi per riprodurre**
1. Creare una fattura fornitore vuota
2. Caricare una fattura elettronica
3. Collegarla (tramite wizard) alla fattura fornitore creata al punto 1

**Comportamento osservato**
Avviso 
```
Vendor reference () does not match with e-bill vendor reference (), ...
```

**Comportamento atteso**
Nessun avviso

**Comment by eLBati** [comment]
Per v12 https://github.com/OCA/l10n-italy/pull/1392

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
