### ISSUE TITLE
[FIX] l10n_it_fatturapa: Empty element should not be filled with dash

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1312]
In fase di pre-processing dell'importazione di un XML, se un elemento obbligatorio è vuoto viene riempito con "-":
https://github.com/OCA/l10n-italy/blob/cc94a5eb1388921debe87e63c3e342e47f8f64d5/l10n_it_fatturapa/bindings/fatturapa.py#L137

Questo può comportare un errore in fase di parsing del XML del tipo:
```
NazioneType pattern constraint violated by value -
```
 - [ ] v8: ?
 - [x] v10: #1313
 - [ ] ~v11:~ 
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1349

**Step per riprodurre**
1. Modificare un file XML di fattura elettronica rimuovendo il valore di un tag Nazione (quindi il tag diventa `<Nazione></Nazione>`)
2. Verificare che il file è comunque accettato da SDI
3. Provare ad importare il file in Odoo

**Comportamento attuale**
Errore:
```
NazioneType pattern constraint violated by value -
```

**Comportamento atteso**
File importato

**Comment by Crisa221** [comment]
@SimoRubi replicato i passi su V11 non ho riscontrato errore

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
