### ISSUE TITLE
Fattura elettronica e portale vendite

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1315]
Fare i controlli per la fattura elettronica durante il pagamento di un ordine nel portale vendite.

**Versioni coinvolte**
 - [ ] v8: ?
 - [ ] v10: ?
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1316

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v12, è stato fatto il merge della relativa PR.
