### ISSUE TITLE
FIX l10n_it_ddt: quantity_by_lot to correctly compute quantities

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1326]
Versioni coinvolte:

 - [ ] 8.0: ?
 - [ ] 10.0: ?
 - [ ] 11.0: ?
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1325

Passi per riprodurre:

 - create product tracked by lot
 - set its inventory with qty 10 for lot1 and 10 for lot2
 - create a picking with quantity 6
 - deliver 3 products of lot1 and 3 of lot2
 - create another picking, with quantity 6
 - deliver 4 products of lot1 and 2 of lot2
 - create DDT from the last picking

Comportamento osservato:

Print PDF DDT and see wrong quantities: 7 and 5 instead of 4 and 2

Comportamento atteso:

Print PDF DDT and see correct quantities:  4 and 2

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v12, è stato fatto il merge della relativa PR.
