### ISSUE TITLE
Bug calcolo ritenuta (modulo l10n_it_withholding_tax)

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1327]
# Versioni coinvolte:
 - [ ] v8: #1597
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1444
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1324
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1469

# Passi per riprodurre:
1- configurare tabella "Validità Aliquote" con più righe che abbiano data d'inizio (ed eventualmente data di fine) precedente alla data attuale; 
2- validazione di fattura d'acquisto.

# Comportamento osservato:
Viene selezionata la prima riga della tabella con data d'inizio precedente alla data attuale, anche se questa è già scaduta (il campo "Data fine" è valorizzato con data precedente all'attuale).

# Comportamento atteso:
Le righe della tabella con data di fine valorizzata ed antecedente alla data attuale non dovrebbero essere tenute in considerazione.

**Comment by Crisa221** [comment]
Come si fa a configurare la tabella "Validità aliquote" nella v10?

**Comment by Crisa221** [comment]
@SilvioGregorini Ho testato su versione 10 è succede lo stesso problema, apro nuova PR per V10

**Comment by eLBati** [comment]
@SilvioGregorini @Crisa221 @SimoRubi per v12: https://github.com/OCA/l10n-italy/pull/1469

**Comment by SilvioGregorini** [comment]
@eLBati per v8 se ne sta occupando qualcuno o posso chiudere la issue?

**Comment by sergiocorato** [comment]
@SilvioGregorini lo faccio io per coerenza
