### ISSUE TITLE
Mancanze FISCALI in  modulo DDT per V8

### ISSUE THREAD

**Issue by Giuliano69** [OCA/l10n-italy#133]
Stavo provando il modulo DDT di cui a
https://github.com/hurrinico/l10n-italy/tree/hurrifix-8.0-ddt/l10n_it_ddt
e volevo ringraziare i creatori del modulo per il lavoro.

Ho notato alcune mancanze nel DDT rispetto ai requisiti fiscali e volevo, con spirito di collaborazione, 
- segnalarle dandone i riferimenti di legge, 
- chiedendo se sia possibile apportare delle correzioni.

Nel dettaglio esse sono:

1) MANCANZA della Indicazione del termine CEDENTE e CESSIONARIO 
2) Mancanza della PIVA per entrambi
3) MANCANZA della presenza del “terzo” Destinatario.
4) Numero del DDT 

1) CESSIONARIO, CEDENTE e PIVA
L'attuale DDT è regolamentato dal DPR 14 agosto 1996, n. 472, che dispone al terzo articolo:
*“3. Il documento previsto dall’articolo 21, quarto comma, secondo periodo del decreto del Presidente della Repubblica 26 ottobre 1972, n. 633 (4), contiene l’indicazione della data, delle generalità del CEDENTE del CESSIONARIO e dell’eventuale incaricato del trasporto, nonché la descrizione della natura, della qualità e della quantità dei beni ceduti.”*

Vanno quindi individuate chiaramente le FIGURE di  cedente e cessionario. Nella attuale stampa report i due partner figurano uno dopo l'altro, senza identificazione esplicita.
Generalmente questo non è sufficiente a definire il primo nome come cedente ed il secondo nominativo come cessionario (gli accertamenti fiscali tendono a diventare .... fiscali :-) )
Andrebbero anteposti i termini CEDENTE e CESSIONARIO nel Ddt, prima dei due partner

2) PIVA
Quanto alla PIVA, si applicano congiuntamente le precisazioni (nel dare significato al termine “generalità”) di cui al *D.P.R. 26 ottobre 1972, n. 633, Comma 2
[2] La fattura deve essere datata e numerata in ordine progressivo e deve contenere le seguenti indicazioni: (1)deve contenere le seguenti indicazioni: (1) 1) ditta, denominazione o ragione sociale, residenza o domicilio dei soggetti fra cui è effettuata l’operazione, nonché ubicazione della stabile organizzazione per i non residenti e, relativamente all’emittente,  **numero di partita IVA**. Se non si tratta di imprese, società o enti devono essere indicati, in luogo della ditta, denominazione o ragione sociale, il nome e il cognome;*

Vedasi al punto, anche il 3d su commercialista telematico:
http://forum.commercialistatelematico.com/iva-intrastat-spesometro-san-marino/73559-ddt-con-partita-iva.html

3) Terzo destinatario
Esiste, sempre più spesso, il caso dell'acquisto fatto dalla Azienda A, presso il venditore B, con destinazione il soggetto o l'indirizzo C. 
In questo caso, Cedente, Cessionario, e Destinatario sono tre figure diverse. Nell'attuale DDT il Cessionario deve coincidere obbligatoriamente con il destinatario.

Chiedo se sia possibile avere una modifica alla maschera di creazione del Ddt, ove oltre alla indicazione del partner “cessionario”, si possa anche indicare (se necessario) il partner “destinatario”

4) Numero DDT
Attualmente il numero DDT viene indicato dopo il testo “Note Spedizione”
Mi ha stupito; non capisco se è voluto. 
Chiedo e propongo : non sarebbe meglio anteporre il testo “Numero Documento:” ?

**Comment by gigidn** [comment]
@Giuliano69 grazie del contributo, vorrei pero' spostare leggermente l'attenzione sugli aspetti funzionali e non sul report. Il report presente nel modulo lo considero un semplice esempio di scarsa o nulla utilità in molti casi. Premesso questo, sperando di essere stato chiaro, saresti in grado di distinguere quali dei punti evidenziati riguardano esclusivamente il report e quali invece sono legati all'attuale struttura dati? la distinzione tra partner di fatturazione e partner di spedizione non è coerente con le definizioni di "Terzo Destinatario"?

Il punto (4) ad esempio è solo riferito al report ed IMHO lo vedo di poca utilità generale, su altre cose mi sfugge la linea di demarcazione tra report e dati.

Grazie per il contributo che vorrai dare.

**Comment by Giuliano69** [comment]
Ciao gigidn
Grazie per la risposta.

Divido la risposta, come sembra mi chiedi, tra parte normativa-report e struttura dati-view

ASPETTO “NORMATIVO FISCALE”
premetto che le segnalazioni riguardano principalmente la versione stampata del DDT, ma ad oggi l'obbligo per le merci viaggianti in Italia è di essere accompagnate da tale documento CARTACEO.
Se manca la possibilità di uscire su carta, il modulo DDT non può dirsi funzionante ai fini FISCALI

Per dare peso alle segnalazioni fatte, evidenzio che la materia è stata si fortemente depenalizzata, tuttavia le sanzioni vanno ancora da 300 a1200 euro per SINGOLO documento…. 
Alias un controllo a posteriori che evidenziasse le irregolarità formali dette, potrebbe facilmente fare (contestando i Ddt di un anno intero o più)  molte migliaia di euro di sanzione…  non sarebbero bruscolini...

Report e STAMPA PIVA
La partita della P IVA è un campo OBBLIGATORIO ma già presente nel modello dati di ogni partner, ed andrebbe semplicemente riportato nel documento report, per evitare le sanzioni sopra dette...
Analogamente dicasi per la dicitura testuale “Cedente” e “Cessionario”

STRUTTURA DATI DDT
I partner da riferire nella struttura dati sono TRE: cedente, cessionario, destinatario.
Allo tato attuale, se entro in Magazzion→ DDT, Trovo un UNICO partner da poter indicare, quindi i soggetti coinvolti nel DDT sono chiaramente DUE.
il CEDENTE, si da per implicito essere il partner azienda attiva; nella stampa :-) sapremo dove andare a prendere i dati che ci servono.

Come dicevo, il modello del DDT attuale considera che cessionario e destinatario siano la stessa persona (se non erro) . Ma è un caso particolare, non è il caso generale.
Il modello dovrebbe considerare che il DDT abbia un capo parnter_cessionario e un campo partner_destinatario.

FORM
La view dovrebbe avere un check-button che (di default) applichi al campo destinatario i riferimenti del cessionario, ovvero quando checkato faccia scegliere un partner destinatario diverso, riportando tale riferimento nella struttura dati del DDT

**Comment by eLBati** [comment]
Ciao @Giuliano69 , grazie del feedback.
Con @OpenCode abbiam fatto un grosso refactoring del DDT. Ora si basa sul modulo ``` stock_picking_package_preparation```
Le PR coinvolte sono:
 - https://github.com/OCA/l10n-italy/pull/138
 - https://github.com/OCA/stock-logistics-workflow/pull/159
 - https://github.com/OCA/stock-logistics-workflow/pull/160

In pratica, se vuoi testare, ti servono 3 moduli aggiuntivi:
 - ``` stock_picking_package_preparation``` scaricabile con ```git clone -b fix_stock_picking_package_preparation https://github.com/eLBati/stock-logistics-workflow.git```
 - ``` stock_picking_package_preparation_line``` scaricabile con ```git clone -b 8.0-add-stock_picking_package_preparation_line https://github.com/OpenCode/stock-logistics-workflow.git```
 - ``` l10n_it_ddt``` scaricabile con ```git clone -b 8.0-ddt-based-on-packaging-preparation_lb https://github.com/eLBati/l10n-italy.git```

**Comment by eLBati** [comment]
Visto che la PR 160 è stata mergiata, ora i moduli necessari sono scaricabili solo con
```
git clone -b 8.0-add-stock_picking_package_preparation_line https://github.com/OpenCode/stock-logistics-workflow.git
git clone -b 8.0-ddt-based-on-packaging-preparation_lb https://github.com/eLBati/l10n-italy.git
```

**Comment by gigidn** [comment]
Ciao @eLBati,

intanto grazie mille, come al solito, per il tuo contributo. Detto questo volevo sottoporre un'idea, durante la creazione della fattura a partire dal/dai DDT si potrebbe pensare di creare la "fattura differita" accorpando o meno le righe del DDT.

Cosa ne pensate? manca qualche altra specifica ... tipo uno stato iniziale che sostituisce 2binvoiced con qualcosa legato alla differita? conviene implementare qui questa logica oppure inserirla in modulo a parte?

**Comment by SGiuseppe** [comment]
Sto cercando di installarlo ma mi da questo errore.

File "/home/odoo/8.0/odoo/openerp/tools/convert.py", line 895, in convert_file
    convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
  File "/home/odoo/8.0/odoo/openerp/tools/convert.py", line 963, in convert_csv_import
    raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_it_ddt failed: file l10n_it_ddt/security/ir.model.access.csv could not be processed:
 Line 9 : Nessun record trovato per id esterno 'model_stock_ddt_type' nel campo 'Object'

**Comment by OpenCode** [comment]
@SGiuseppe ti chiedo gentilmente di aprire un'altra issue per poter risolvere il tuo problema

**Comment by eLBati** [comment]
Ciao @gigidn cosa intendi con ```accorpando o meno le righe del DDT``` ? Puoi fare un esempio?

**Comment by gigidn** [comment]
In presenza di molti DDT da riepilogare in fattura (fine mese) magari con molti prodotti per singolo DDT, alcuni per limitare le pagine della fattura stessa preferiscono esplicitare il solo riferimento al DDT e il suo valore in termini monetari.

In pratica in fattura avrei righe del tipo

Riga fattura 1: Nostro DDT  numero 1234 del 14/09/2015 - Imponibile: somma degli imponibili presenti nel ddt 1234.
Riga fattura 2: Nostro DDT  numero 45678 del 17/09/2015 - Imponibile: somma degli imponibili presenti nel ddt 45678.

In sostanza per ogni DDT riepilogato ho 1 riga in fattura, o meglio ho n righe per quante sono le aliquote iva distinte presenti in esso.

Essendo il DDT un formato abbastanza "aperto" non e' chiaro se esso debba o meno riportare prezzo ed aliquote iva ... io per i miei clienti nell'incertezza li riporto nella stampa.

Questa prassi è molto comune per chi fa spedizioni ricorrenti (tipicamente giornaliere).

Selezionando quindi n DDT, l'utente dovrebbe poter scegliere se generare la fattura differita con il dettaglio di tutti i prodotti o semplicemente l'ammontare diviso per aliquota iva del DDT stesso.

**Comment by OpenCode** [comment]
@gigidn Più che creare la fattura già raggruppata, io opterei per demandare la cosa in una fase di report piuttosto che di documento. Al massimo possiamo discutere di mantenere le relazioni tra ddt e dettagli fattura così che la cosa possa essere agevolmente gestita nella stampa ma non me la sentirei di creare fatture con dettagli raggruppati. Si perdono informazioni che secondo me è meglio mantenere.

**Comment by gigidn** [comment]
@OpenCode quella che ho scritto e' la richiesta che probabilmente ci troveremmo a dover far fronte dai clienti. Come raggiungere lo scopo nel miglior modo possibile spetta a noi deciderlo. Non posso che condividere il tuo punto di vista, inserendo in fattura elementi raggruppati si perde dettaglio. Di contro demandare il raggruppamento al report renderebbe la produzione dello stesso lenta ... situazione accettabile se stampi una singola fattura, inaccettabile e con rischio di timeout se vai a stampare un lotto di 200/300 se non oltre fatture (stiam parlando di fatturazione fine mese). Un compromesso, da analizzare bene perche' lo sto elaborando mentalmente solo in questo momento, potrebbe essere quello di inserire nella riga fattura il riferimento al DDT ed il suo valore aggregato come campo calcolato e storicizzato della somma di tutte le righe in cui e' presente quel DDT. In questo modo la produzione del report sarebbe facile visto che il calcolo sarebbe demandato al singolo oggetto in fase di salvataggio. Sicuramente bisogna ragionarci un po' meglio, quello che posso dirvi dalla mia esperienza e' che i valori raggruppati rappresentano un must in alcuni settori. Pensa ad una azienda di prodotti freschi che giornalmente consegna ad un cliente/distribuzione 20-30 prodotti differenti ... fatturare fine mese significherebbe avere una fattura con 400-600 righe oggettivamente poco gestibile, raggruppando i DDT avrei 30*(numero di aliquote differenti) righe sicuramente piu' facili da maneggiare fintanto che usiamo la carta come elemento per la trasmissione delle informazioni.

**Comment by dcorio** [comment]
per snellire la produzione del report penso sarebbe sufficiente avere la chiave di raggruppamento, ovvero il ddt, direttamente sulla riga della fattura.

non ho mai visto aggiungere informazioni come il totale per ddt. solo numero documento e data.
ma è comunque fattibile, anche se questo lo demanderei al report.

**Comment by eLBati** [comment]
Consiglierei a chiunque voglia proporre modifiche di fare una pull request,
così da capire meglio la modifica sia testandola che guardando il codice.

In prima battuta punterei a mergiare le PR aperte
https://github.com/OCA/stock-logistics-workflow/pull/159
https://github.com/OCA/l10n-italy/pull/138
con le loro funzionalità attuali, assicurandoci che funzionino.

Per quanto riguarda stock_picking_package_preparation_line, @OpenCode
riesci a sistemare le cose che diceva @tafaRU ?

Una volta mergiata la 159, la 138 potrà diventare verde e la si potrà anche
direttamente su runbot. Non appena i test saranno soddisfacenti, mergeremo
anche lei
