### ISSUE TITLE
[IMP] l10n_it_vat_registries: Stampare registri senza movimenti

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1330]
Può risultare utile stampare i registri IVA anche in periodi in cui la stampa sarebbe vuota, per tenere conto che la stampa è stata comunque fatta.
Altrimenti, potrebbe voler dire che è stata dimenticata.
 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1331
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1332

**Comment by eLBati** [comment]
Per v12: https://github.com/OCA/l10n-italy/pull/1332

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
