### ISSUE TITLE
Nuovo modulo per corretta fatturazione KIT da DDT

### ISSUE THREAD

**Issue by jackjack82** [OCA/l10n-italy#1335]
Versioni coinvolte:

* [ ]  v8: ?
* [x]  v10: #1337 , #1336  
* [ ]  v11: ?
* [x]  v12: https://github.com/OCA/l10n-italy/pull/3320

Passi per riprodurre:

Creo un SO con un prodotto che ha una distinta base e due componenti. Confermo l'ordine e valido il picking (che contiene due righe dei prodotti componenti, non il kit). Quando creo il DDT ho sempre due righe. Quando fatturo, però, voglio poter fatturare il prodotto KIT, non i componenti.

Comportamento osservato:

La fattura creata dal DDT contiene una riga per ogni componente del KIT (con descrizione sbagliata), sembrano molteplici KIT.

Comportamento atteso:

Viene creata correttamente la fattura con la riga del KIT.

Vedi anche https://github.com/OCA/l10n-italy/issues/1296 per una descrizione più dettagliata

**Comment by eLBati** [comment]
@jackjack82 @difra duplicata della https://github.com/OCA/l10n-italy/issues/1296 ?

**Comment by difra** [comment]
> @jackjack82 @difra duplicata della #1296 ?

Si, confermo.

**Comment by jackjack82** [comment]
si si, potete mergiarle. Tra l'altro il modulo funziona correttamente sulla
10, si potrebbe mergiare.
Giacomo

**Comment by eLBati** [comment]
> Tra l'altro il modulo funziona correttamente sulla 10, si potrebbe mergiare

Sulla https://github.com/OCA/l10n-italy/pull/1336 manca questo https://github.com/OCA/l10n-italy/pull/1336#pullrequestreview-271929823 
@jackjack82 se non riesci a farlo vediamo se lo può fare qualcun altro

**Comment by eLBati** [comment]
@difra puoi testare/revisionare la https://github.com/OCA/l10n-italy/pull/1336 ?

**Comment by primes2h** [comment]
C'è una spunta per la v10, ma manca il merge della #1336.

**Comment by OpenCode** [comment]
Le versioni supportate hanno tutte la PR mergiata. Chiudo.
