### ISSUE TITLE
Numero di pagina errato in footer di stampe con più pagine

### ISSUE THREAD

**Issue by jado95** [OCA/l10n-italy#1339]
Versioni Coinvolte
 - [x] v11:  [#1338](https://github.com/OCA/l10n-italy/pull/1338)
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1361

**Comment by eLBati** [comment]
@jado95 una revisione per 12.0 https://github.com/OCA/l10n-italy/pull/1361 ?

**Comment by eLBati** [comment]
@OCA/local-italy-developers le versioni prima della 11 non sono affette?

**Comment by primes2h** [comment]
Questo problema si verifica anche nella versione 10.0?

**Comment by jado95** [comment]
Mai capitato, quindi non credo che il problema si verifichi anche su versioni precedenti alla 11.

**Comment by primes2h** [comment]
> Mai capitato, quindi non credo che il problema si verifichi anche su versioni precedenti alla 11.

Ok, quindi la chiudo.
Grazie!
