### ISSUE TITLE
Registro IVA: Nota credito fornitore con riga negativa

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#1355]
Versioni coinvolte:

- 10.0 (non più supportata)
- [ ] 11.0: https://github.com/OCA/l10n-italy/pull/1356
- [X] 12.0: https://github.com/OCA/l10n-italy/pull/1717

Passi per riprodurre:

Creazione nota credito fornitore con una riga di 1000 iva al 22 e una riga di -500 con IVA al 10.

Comportamento osservato:
Nella stampa del registro iva, la riga di dettaglio delle imposta riporta 2 righe con entrambi i valori negativi

Comportamento atteso:
la riga di registro relativa alla riga di nota credito positiva dovrebbe avere imponibile e imposta positiva
Video/Screenshot (opzionale):
![image](https://user-images.githubusercontent.com/7657512/61174182-2a525c80-a59d-11e9-9265-5c322af23628.png)
![image](https://user-images.githubusercontent.com/7657512/61174185-36d6b500-a59d-11e9-9da2-06053bff837b.png)

**Comment by primes2h** [comment]
@alessandrocamilli 
Il problema si presenta anche con la 10.0 o la 12.0?

**Comment by eLBati** [comment]
Sulla 12 si verifica

**Comment by OpenCode** [comment]
@alessandrocamilli Ho aggiornato la descrizione per indicare che la 12.0 è merged e che la 10.0 non è più supportata.

**Comment by alessandrocamilli** [comment]
@OpenCode grazie!!
