### ISSUE TITLE
[10.0] l10n_it_fatturapa_in - Filtro ricerca IBAN

### ISSUE THREAD

**Issue by matteotrubini** [OCA/l10n-italy#1359]
Questo filtro di ricerca
https://github.com/OCA/l10n-italy/blob/eb1d21b465fb8794ae479d52bacf23ababc85adb/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L675-L684

non è coerente con questo;
https://github.com/odoo/odoo/blob/f7acbf6466a712dd086d13b14a69f415afe7dc13/odoo/addons/base/models/res_bank.py#L93-L95

Questo comporta errori di importazione, ad esempio, se l'iban di pagamento nell'XML:
- è quello della company (es: Modalità: MP20 (SEPA Direct Debit CORE) - in questo caso è indicato l'iban di addebito della company, non quello del fornitore)
- è condiviso fra più soggetti (es: Autostrade per L'Italia / Telepass, ovvero anche in caso di factoring)

Nel secondo caso c'è un problema ulteriore, ovvero la posizione di odoo sulla possibilità di condividere l'iban fra più partner:
https://github.com/odoo/odoo/issues/15636
https://github.com/odoo/odoo/pull/15638

Ultimamente è stata riproposta la questione anche in ambito OCA:
https://github.com/OCA/account-financial-tools/pull/787

Idee?

**Comment by eLBati** [comment]
@matteotrubini riesci a fornire un XML di esempio che riproduca l'errore? Così lo mettiamo nel test automatico.
Puoi prendere spunto da quelli esistenti se vuoi:
https://github.com/OCA/l10n-italy/tree/10.0/l10n_it_fatturapa_in/tests/data

**Comment by eLBati** [comment]
Questo problema verrebbe risolto da queste modifiche
https://github.com/OCA/l10n-italy/pull/1354
?

**Comment by matteotrubini** [comment]
> Questo problema verrebbe risolto da queste modifiche
> #1354
> ?
No, non sono questioni correlate.

**Comment by matteotrubini** [comment]
> > Questo problema verrebbe risolto da queste modifiche
> > #1354
> > ?
> 
> No, non sono questioni correlate.

**Comment by matteotrubini** [comment]
[tests.zip](https://github.com/OCA/l10n-italy/files/3407699/tests.zip) - la seconda importazione fallisce: `Account Number must be unique`

Verificato manualmente su http://3378975-10-0-e313e6.runbot2.odoo-community.org/

**Comment by eLBati** [comment]
@matteotrubini ottimo, grazie. Hai anche idea di come risolvere?

**Comment by matteotrubini** [comment]
Possibili soluzioni veloci:
1) https://github.com/wtaferner/odoo/commit/326727bbd7161f6c2af68009d3d9fc924772d665 (estensione del vincolo per renderlo meno restrittivo)
1) https://github.com/OCA/account-financial-tools/pull/787 (rimozione del vincolo)
1) ~~('partner_id', '=', partner_id)~~ `('company_id', '=', 'self.env.user.company_id')` e rispettare i vincoli di modello originali

Oltre a questo aggiungerei un campo "beneficiario" per importare il relativo nodo XML ed avere quantomeno il dato a video, per una successiva gestione manuale.

**Comment by eLBati** [comment]
@matteotrubini allora in prima battuta potremmo seguire la 3 (più  l'aggiunta del campo informativo).

Riesci a fare la PR, con test automatico?

**Comment by matteoopenf** [comment]
Buongiorno, @matteotrubini  per caso hai più fatto una pr rguardo il punto 3?

**Comment by matteotrubini** [comment]
@matteoopenf purtroppo no, per caso potresti occupartene te?

**Comment by matteoopenf** [comment]
sto avendo un problema simile su 11 attualmente subito non riesco
