### ISSUE TITLE
[l10n_it_fatturapa_in] Setta la data competenza delle fatture di acquisto

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1364]
- [ ] 8.0 ?
- [x] 10.0 #1363 
- [ ] 11.0 ?
- [x] 12.0 #1365 

Descrizione del problema o della funzionalità:

La data competenza di una fattura di acquisto elettronica dovrebbe essere quella al momento del prelievo dalla PEC

Comportamento attuale prima di questa PR:

Attualmente non viene gestita

Comportamento desiderato dopo questa PR:

Setta la data competenza della registrazione delle fattura di acquisto prendendo l'informazione dalla PEC inviata dallo SDI

**Comment by eLBati** [comment]
@robyf70 hai letto anche questa discussione https://github.com/OCA/l10n-italy/issues/1183 ?

**Comment by robyf70** [comment]
@eLBati Stavo cercando proprio quella discussione

**Comment by robyf70** [comment]
@eLBati Ho appena pushato la versione che imposta la data registrazione della fattura usando quella della PEC dello SDI

**Comment by eLBati** [comment]
@robyf70 In aggiunta a quanto fatto, darei anche la possibilità (opzionale?) di usare la `e_invoice_received_date` come "Data contabile" in fattura, visto che in generale,  se usi la data ricezione sia nei registri/libri che ai fini della liquidazione IVA, vai sul sicuro
cc @As400it

**Comment by As400it** [comment]
> @robyf70 In aggiunta a quanto fatto, darei anche la possibilità (opzionale?) di usare la `e_invoice_received_date` come "Data contabile" in fattura, visto che in generale, se usi la data ricezione sia nei registri/libri che ai fini della liquidazione IVA, vai sul sicuro
> cc @As400it

ok

**Comment by robyf70** [comment]
@eLBati Per me ok, ma non vorrei triggerare un'altra discussione infinita

**Comment by eLBati** [comment]
Io la propongo semplice: https://github.com/OCA/l10n-italy/pull/1595

**Comment by primes2h** [comment]
Le PR principali sono state completate, la posso chiudere?
(vedo che ci sono ancora alcuni commenti riguardo le date fattura)

**Comment by eLBati** [comment]
Sì, le modifiche specifiche di questa issue sono fatte
