### ISSUE TITLE
Opzionalmente escludere partner/fornitori dall'aggiornamento dei dati delle fatture di acquisto elettroniche

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1367]
- [ ] 8.0 ?
- [x] 10.0 #1366 
- [ ] 11.0 ?
- [x] 12.0 #1368 

Versioni coinvolte:

Tutte

Descrizione del problema:

Attualmente i dettagli del partner/fornitore vengono sempre e comunque aggiornati al momento dell'importazione di una fattura elettronica sovrascrivendo eventuali modifiche da parte dell'utente

Comportamento attuale prima di questa PR:

I dettagli del partner/fornitore vengono aggiornati sempre dalla fattura importata

Comportamento desiderato dopo questa PR:

Rendere opzionale l'aggiornamento di specifici partner/fornitori al momento dell'importazione delle fatture di acquisto

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
