### ISSUE TITLE
Supporto per la rilevazione degli arrotondamenti in fatture elettroniche d'acquisto

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1375]
- [ ] 8.0 ?
- [x] 10.0 #1374 #1391 
- [ ] 11.0 ?
- [x] 12.0 #1395 

Versioni coinvolte:

Tutte

Descrizione del problema o della funzionalità:

La procedura di importazione delle fatture elettroniche di acquisto non supporta la gestione degli arrotondamenti, pertanto la fattura che viene generata risulta errata e quindi da "sistemare" a mano

Comportamento attuale prima di questa PR:

Non c'è supporto degli arrotondamenti in fatture elettroniche d'acquisto

Comportamento desiderato dopo questa PR:

Supporto completo per la rilevazione degli arrotondamenti attivi e passivi

**Comment by eLBati** [comment]
Anche il porting a 12 di queste modifiche è bloccato da https://github.com/OCA/l10n-italy/pull/1305
@robyf70 @SimoRubi @primes2h merge?

**Comment by robyf70** [comment]
@eLBati Nel mentre faccio il porting alla 12 delle ultime modifiche

**Comment by eLBati** [comment]
@robyf70 otterrai conflitti perchè sulla 12 manca la #1305 
Per te OK per il merge?

**Comment by robyf70** [comment]
Questa PR è ancora da allineare, mi sono fermato perchè dovrò fare un'altra PR per la 10, c'è anche il caso che gli arrotondamenti finiscano su ``FatturaBody.DatiGenerali.DatiGeneraliDocumento.Arrotondamento`` e questo mi era sfuggito!

**Comment by robyf70** [comment]
@eLBati Il supporto completo l'abbiamo con la #1391

**Comment by eLBati** [comment]
@robyf70 @sergiocorato un dubbio su `arrotondamenti_tax_id`: l'imposta da usare in fattura per la riga di arrotondamento, più che essere prefissata in configurazione, non dovrebbe essere una di quelle già presenti in fattura?

**Comment by eLBati** [comment]
Inoltre, quando l'arrotondamento è in `DatiRiepilogo` dovrebbe essere usata l'imposta di quella riga di riepilogo

**Comment by eLBati** [comment]
Come non detto: è fuori campo IVA

**Comment by primes2h** [comment]
Merge effettuato per le PR delle principali versioni supportate. Chiudo.
