### ISSUE TITLE
make lint green

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1378]
Versioni coinvolte:

 - [x] 10: https://github.com/OCA/l10n-italy/pull/1351
 - [ ] 11
 - [x] 12: https://github.com/OCA/l10n-italy/pull/1349

**Comment by eLBati** [comment]
Per la 12 , modifiche incluse in https://github.com/OCA/l10n-italy/pull/1349 , la quale modificava già `bindings`

**Comment by SimoRubi** [comment]
Per v11 lint è già verde (https://travis-ci.org/OCA/l10n-italy/jobs/564788049) quindi direi che questo issue si può chiudere

**Comment by eLBati** [comment]
ok
