### ISSUE TITLE
l10n_it_fatturapa_* - Nome file univoco

### ISSUE THREAD

**Issue by matteotrubini** [OCA/l10n-italy#1382]
* [ ]  8.0 ?
* [x]  10.0 #1410
* [ ]  11.0 ?
* [x]  12.0 https://github.com/OCA/l10n-italy/pull/1465 + https://github.com/OCA/l10n-italy/pull/1480

Versioni coinvolte:
_Tutte_

Passi per riprodurre:
_Caricare in successione 2 volte lo stesso file o 2 file con lo stesso nome_

Comportamento osservato:
_Entrambi i file vengono caricati_

Comportamento atteso:
_Vincolo univocità su nome file_

> Ogni file inviato al Sistema di Interscambio deve avere un nome diverso da qualsiasi altro file inviato in precedenza
https://www.fatturapa.gov.it/export/fatturazione/sdi/Specifiche_tecniche_SdI_v1.6.pdf - pag. 10

**Comment by primes2h** [comment]
È stato fatto il merge per le PR delle principali versioni supportate. Chiudo.
