### ISSUE TITLE
l10n_it_fiscal_document_type: nome e codice obbligatori

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1386]
Versioni coinvolte:

 - [x] 8.0 https://github.com/OCA/l10n-italy/pull/1402
 - [x] 10.0 https://github.com/OCA/l10n-italy/pull/1401
 - [x] 11.0 https://github.com/OCA/l10n-italy/pull/1400
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/1387

Passi per riprodurre:

Creare un tipo documento fiscale senza codice
Crea una fattura attiva utilizzando tale tipo
Esportare la fattura elettronica

Comportamento osservato:

`TipoDocumentoType enumeration constraint violated by value False`

Comportamento atteso:

Il sistema costringe l'utente a inserire nome e codice per il tipo documento fiscale

**Comment by SimoRubi** [comment]
Per v11: #1400

**Comment by SimoRubi** [comment]
Per v10: https://github.com/OCA/l10n-italy/pull/1401

**Comment by SimoRubi** [comment]
Per v8: #1402
