### ISSUE TITLE
[12] l10n_it_withholding_tax does not work as expected: multiple invoices payment

### ISSUE THREAD

**Issue by batalhadematos** [OCA/l10n-italy#1399]
Versioni coinvolte: 

 - [ ] 12
 - [ ] 14

Passi per riprodurre:
- Defined the desired WT Tax: ie. 10%
- Created 2 invoices with WT included and validated them: 
	- Invoice 1: Total amount: 1.000,00 / WT Tax: 100,00 / Net to pay: 900,00
	- Invoice 2: Total amount: 1.000,00 / WT Tax: 100,00 / Net to pay: 900,00
- Under invoices list view, select the 2 invoices and ask to "register payment" under Action menu:
	- Since both invoices have a net to pay of 900,00, change the default proposed value (2.000,00) to 1.800,00 in order to pay both invoices and have the 200,00 retained.

Comportamento osservato:
The first invoice is correctly paid and the journal entries are correct.
For the second invoice it does not happens and customer stays with a value on credit and the invoice is not totally paid.
Besides this unexpected issue, the journal entries are somehow messed up.

Thank you all

**Comment by TheMule71** [comment]
This PR might be related (as a possible solution, I haven't tested it).
https://github.com/OCA/l10n-italy/pull/2818
