### ISSUE TITLE
fatturapa fiscal position readonly in configurazione

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1405]
Esportando una fattura elettronica, se il campo `res.company.fatturapa_fiscal_position_id` è vuoto, viene sollevato l'errore:
https://github.com/OCA/l10n-italy/blob/4c43e0efd55035f9f9880158e2e7416dda304e96/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L228

dove si dice di andarlo a cambiare in configurazione.
Il problema è che tale campo è definito come readonly in 
https://github.com/OCA/l10n-italy/blob/4c43e0efd55035f9f9880158e2e7416dda304e96/l10n_it_fatturapa/models/company.py#L41

e credo che sia stato fatto volontariamente perché in tutti gli altri campi è esplicitato `readonly=False`, quindi non è possibile modificarlo in configurazione.

Le due informazioni sono contrastanti quindi non so come correggere l'errore:

- **Se è giusto che il campo sia `readonly`**: Modifico il messaggio di errore dicendo di andare a modificare in Impostazioni > Utenti e aziende > ...
- **Altrimenti**: Aggiungo `readonly=False` a `res.config.settings.fatturapa_fiscal_position_id`

Mi dite le vostre opinioni?
In entrambi i casi la fix è banale ma non so se ci sono ragioni funzionali/contabili dietro.

Versioni affette:
 - [ ] v8: ?
 - [ ] v10: not affected
 - [x] v11: https://github.com/OCA/l10n-italy/pull/1421
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1407

**Comment by eLBati** [comment]
Non vedo problemi nel renderlo modificabile in configurazione

**Comment by eLBati** [comment]
Per le altre versioni serve o chiudiamo?

**Comment by Crisa221** [comment]
Testando la issue su versione 10 non viene riscontrato l'errore. Appena si cancella il campo e si salva l'impostazione, la platform notifica che il campo deve essere compilato (quindi obbligatorio). Allego immagine
![Schermata da 2019-08-26 15-46-22](https://user-images.githubusercontent.com/19572134/63695352-cddb9180-c818-11e9-810e-0052bbd9115a.png)

**Comment by Crisa221** [comment]
Verificato anche per versione 8. Si presenta la stessa cosa della versione 10 ovvero che il campo deve essere compilato (quindi obbligatorio). Allego immagine relativa a versione 8
![Schermata da 2019-08-27 15-14-11](https://user-images.githubusercontent.com/19572134/63774375-68050d80-c8dd-11e9-84f5-fa87678c95e7.png)

**Comment by SimoRubi** [comment]
Grazie delle verifiche @Crisa221.
@eLBati a quanto pare v8 e v10 non sono affette quindi direi che si può chiudere
