### ISSUE TITLE
Doppio allegato creato in caso di ri-esportazione della e-invoice

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1412]
Versioni coinvolte:

 - [x] v8: #874 
 - [ ] v10: ?
 - [ ] v11: ?
 - [x] v12: #1976 

Passi per riprodurre: esportare l'e-invoice, eliminarla, ri-esportarla

Comportamento osservato: negli allegati dell'e-invoice si moltiplica il report della fattura per ogni volta che viene eliminata e ri-esportata

Comportamento atteso: c'è un solo allegato con l'ultimo report

**Comment by andreinl** [comment]
Confermo che il problema si manifesta anche sulla v12

**Comment by eLBati** [comment]
@andreinl se hai voglia di portare la modifica su v12, puoi provare a fare cherry-pick del commit https://github.com/OCA/l10n-italy/pull/874/commits/c20a17a3ede39d426248407ee6a143dfe1670129

**Comment by andreinl** [comment]
Scusa, ho visto soltanto oggi la tua risposta. Ecco il PR:
https://github.com/OCA/l10n-italy/pull/1976 - [FIX] double attach in fatturapa out xml #1976

**Comment by tafaRU** [comment]
Su `14.0` la fix è già presente: https://github.com/OCA/l10n-italy/blob/64f053e18be21f504a8e12199fae7cee66b5f187/l10n_it_fatturapa_out/models/attachment.py#L144-L148
