### ISSUE TITLE
[8.0] URGENT: l10n_it_base both in repo root AND __unported__

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-italy#143]
Can you check this and remove or rename in `__unported__`.

cc/ @tafaRU @eLBati 

See https://odoo-community.org/groups/contributors-15/contributors-26518?mode=thread&date_begin=&date_end=, item 2 for more information.

**Comment by tafaRU** [comment]
@eLBati I noticed that ```l10n_it_fatturapa``` and ```l10n_it_rea``` still depends on ```l10n_it_base```.
We can remove these dependencies and remove ```l10n_it_base``` from repo root accordingly?

Let me know if I can prepare a PR to apply these changes.

**Comment by sbidoul** [comment]
If you confirm l10n_it_base is ported, you can just remove it from `__unported__`.

**Comment by tafaRU** [comment]
@sbidoul done.
Thanks!
