### ISSUE TITLE
Stampa Registro IVA: Autofatture con segno negativo su imponibile e imposta

### ISSUE THREAD

**Issue by Crisa221** [OCA/l10n-italy#1434]
Versioni coinvolte:
- [ ] v10:
- [ ] v11:
- [ ] v12:

Quando si stampa il registro iva le autofatture hanno importo negativo su imponibile e imposta

Passi da riprodurre:
selezionare un range di date dal 01/04/2019 al 30/06/2019. Selezionare nella tabella le voci "Sezionale vendite" e "Autofatture EX"

Comportamento osservato:

stampa imponibile ed imposta con segno negativo

Comportamento atteso:

stampa imponibile ed imposta con segno positivo

**Comment by eLBati** [comment]
Non lo riscontro, almeno sulla 10.
Quali sono i passi per riprodurre il problema?

**Comment by Crisa221** [comment]
@eLBati I passi da riprodurre sono selezionare un range di date dal 01/04/2019 al 30/06/2019 e selezionare nella tabella le voci "Sezionale vendite" e "Autofatture EX"

**Comment by eLBati** [comment]
`Autofatture EX` non esiste di default. È stato configurato per il modulo reverse charge? Come?

**Comment by Crisa221** [comment]
chiudo issue perché non sussite problema
