### ISSUE TITLE
FIX l10n_it_fatturapa_out: remove duplicate code

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1438]
Versioni coinvolte:

 - [x] 8.0: non affetta
 - [x] 10.0: non affetta
 - [ ] 11.0: https://github.com/OCA/l10n-italy/pull/1442
 - [ ] 12.0: https://github.com/OCA/l10n-italy/pull/1437

Metodo `_domain_ir_values` e campo `report_print_menu` duplicati

**Comment by SimoRubi** [comment]
v11: https://github.com/OCA/l10n-italy/pull/1442

**Comment by SimoRubi** [comment]
@OCA/local-italy-maintainers questa si può chiudere
