### ISSUE TITLE
DDT: errore fatturazione massiva

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1446]
Versioni coinvolte:

 - [x] 8.0 non affetta
 - [x] 10.0 non affetta
 - [x] 11.0 non affetta
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1445

Passi per riprodurre:

 - Creare un DDT da fatturare
 - Andare su Vendite > da fatturare > fatturazione DDT
 - Selezionare la data odierna
 - Nella finestra successiva cliccare "creare fattura"

Comportamento osservato:

Ottengo `AttributeError: 'str' object has no attribute 'strftime'`

Comportamento atteso:

La fattura viene creata

**Comment by eLBati** [comment]
Sulle versione prima della 12 non dovrebbe capitare, giusto?

**Comment by GSLabIt** [comment]
corretto, almeno per quel che mi risulta 😬

**Comment by alessandrocamilli** [comment]
Sulla 11 è ok
