### ISSUE TITLE
l10n_it_fatturapa_in wrong import of XML with 100% discount

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1447]
Versioni coinvolte:

 - [x] 8.0: https://github.com/OCA/l10n-italy/pull/1460
 - [x] 10.0: https://github.com/OCA/l10n-italy/pull/1457
 - [x] 11.0: https://github.com/OCA/l10n-italy/pull/1458
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1448

Passi per riprodurre:

Importare un file con una riga con
```
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>100.00</Percentuale>
        </ScontoMaggiorazione>
```

Comportamento osservato:

La riga fattura in odoo ha sconto 0

Comportamento atteso:

La riga fattura in odoo ha sconto 100

**Comment by tafaRU** [comment]
@OCA/local-italy-developers le PR sono presenti per tutte le versioni supportate, mancano poche review per mergiarle e chiudere così la issue collegata. Potete provvedere?

**Comment by sergiocorato** [comment]
@tafaRU fatto!

**Comment by sergiocorato** [comment]
manca per la 11.0 #1495

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v11, è stato fatto il merge della relativa PR.
Quindi si può anche chiudere perchè completa.

**Comment by OpenCode** [comment]
> Andrebbe messa la spunta sulla v11, è stato fatto il merge della relativa PR.
> Quindi si può anche chiudere perchè completa.

Fatto.

Chiuso la issue. Bel lavoro.
