### ISSUE TITLE
l10n_it_reverse_charge: write supplier invoice data in self invoice comments

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1450]
Versioni coinvolte:

 - [x] 8.0 https://github.com/OCA/l10n-italy/pull/1463
 - [x] 10.0 https://github.com/OCA/l10n-italy/pull/1462
 - [x] 11.0 https://github.com/OCA/l10n-italy/pull/1461
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1449

Passi per riprodurre:

Regsitrare una fattura intraUE applicando il reverse charge configurato in modalità autofattura

Comportamento osservato:

L'autofattura generata non riporta i riferimenti alla fattura passiva

Comportamento atteso:

L'autofattura li riporta

**Comment by tafaRU** [comment]
@OCA/local-italy-developers le PR sono presenti per tutte le versioni supportate, mancano poche review per mergiarle e chiudere così la issue collegata. Potete provvedere?
