### ISSUE TITLE
[11.0][12.0] quantità errate in caso di DDT con picking con shipping policy "Deliver each product when available"

### ISSUE THREAD

**Issue by difra** [OCA/l10n-italy#1451]
**Versioni coinvolte:** 
- [ ] 11.0 
- [ ] 12.0

**Passi per riprodurre:**

- Creo un ordine di vendita con un prodotto X "Storable" con una quantità di 200 pz. 
- Seleziono "Deliver each product when available" come "Shipping Policy" 
- Aggiorno la quantità in possesso del prodotto X a 160 Pz.
- Confermo l'ordine di vendita.
- Creo il DDT.
- Aggiungo la picking generata dall'ordine di vendita.
- Salvo e confermo il DDT
- Genero la fattura dal DDT

**Comportamento osservato:**
La quantità del prodotto X confermate e spedite nella picking sono 160, quelle vendute 200.

Nel dettaglio DDT mi ritrovo la quantità della riga dell'ordine (200 pz).
Nella fattura, invece di fatturare la merce effettivamente spedita (160 pz), viene fatturata tutta la quantità presente nella riga dell'ordine di vendita (200 pz).

**Comportamento atteso:**
La quantità del prodotto X confermate e spedite nella picking sono 160, quelle vendute 200.

Nel dettaglio DDT mi aspetterei di avere una quantità di 160 pz che sono le quantità effettivamente riservate o spedite (a seconda dello stato del DDT e quindi della Picking)

Nella fattura mi aspetto di fatturare 160 pz, cioè la merce effetteviamente spedita.

Screenshot:
![screenshot-difra-test3-app-l10n-it-ddt-586127 dev odoo com-2019 09 14-16_53_32](https://user-images.githubusercontent.com/3530485/64909798-d5ec6a00-d710-11e9-86cb-883b756a3faa.png)

![screenshot-difra-test3-app-l10n-it-ddt-586127 dev odoo com-2019 09 14-16_53_57](https://user-images.githubusercontent.com/3530485/64909797-d5ec6a00-d710-11e9-9b41-e7d6565a8813.png)

![screenshot-difra-test3-app-l10n-it-ddt-586127 dev odoo com-2019 09 14-16_54_38](https://user-images.githubusercontent.com/3530485/64909796-d5ec6a00-d710-11e9-8116-1d8545375a23.png)

![screenshot-difra-test3-app-l10n-it-ddt-586127 dev odoo com-2019 09 14-16_55_27](https://user-images.githubusercontent.com/3530485/64909795-d553d380-d710-11e9-8b94-ae4fd01b9959.png)

**Comment by difra** [comment]
il problema è dovuto al fatto che la qty viene presa dalla stock.move invece che dalla stock move line. https://github.com/OCA/stock-logistics-workflow/blob/12.0/stock_picking_package_preparation_line/models/stock_picking_package_preparation_line.py#L65

**Comment by eLBati** [comment]
Questa è duplicata della https://github.com/OCA/l10n-italy/issues/1256 o sono problemi diversi?

**Comment by difra** [comment]
> Questa è duplicata della #1256 o sono problemi diversi?

Sono problemi diversi.

**Comment by Zephyria77** [comment]
Nel mio caso succede più o meno la stessa cosa già a livello ddt:
 "Deliver each product when available" attivo 

Ordine di vendita con 10 articoli di produzione 
Dopo tre giorni sono pronti 2 articoli e li devo consegnare 
Run scheduler 
Picking dei 10 articoli: pronto 
Ddt da picking 
Il ddt contiene tutti e 10 gli articoli con relative quantità 
Metto nel pacco e pacco completato (sempre 10 articoli) 
Controllo picking 
Trovo picking completato con i due articoli effettivamente spediti e backorder con gli articoli rimanenti
Per ovviare il problema cancello nel ddt gli articoli non pronti
