### ISSUE TITLE
Tipo di documento fiscale errato con nota di credito da ordine

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1452]
**Versioni coinvolte**
 - [ ] v8: ?
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1453
 - [ ] v11: ?
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1470

**Passi per riprodurre**

1. Aprire un sale order avente un picking e stato fattura 'interamente fatturato'.
2. Aprire il picking e fare un rientro con il check 'to refund' in ogni riga.
3. Validare il picking di rientro creato.
4. Tornare nel sale order, cliccare sul pulsante 'crea nota di credito' e creare la nota.

**Comportamento osservato**
La nota di credito creata ha il campo 'tipo documento fiscale' = fattura

**Comportamento atteso**
La nota di credito creata ha il campo 'tipo documento fiscale' = nota di credito

**Comment by eLBati** [comment]
@SimoRubi per v12 https://github.com/OCA/l10n-italy/pull/1470

**Comment by eLBati** [comment]
Chiudo perchè 8 e 11 sono fuori dagli interessi principali.
Se qualcuno volesse fare le PR, riapriamo.

**Comment by primes2h** [comment]
> Chiudo perchè 8 e 11 sono fuori dagli interessi principali.
> Se qualcuno volesse fare le PR, riapriamo.

Qui però sorge un problema IMHO.
Se una persona riscontra questa problematica in una di quelle versioni, se la cerca tra le issue aperte non troverà nulla.
Il rischio è che per fare la PR riparta da zero.

**Comment by eLBati** [comment]
@primes2h normalmente io cerco le parole chiave in tutto il repository, quindi mi vengono eventualmente proposte anche le issue chiuse

**Comment by primes2h** [comment]
> @primes2h normalmente io cerco le parole chiave in tutto il repository, quindi mi vengono eventualmente proposte anche le issue chiuse

Ok, ma nelle chiuse trovi anche le issue con con merge effettuato per tutte le versioni. 
Non mi sembra ci sia modo di filtrare e distinguere queste due tipologie. (issue con merge per tutte le versioni e issue con merge solo per 10 e 12) 
O forse si?

**Comment by eLBati** [comment]
Direi di no. Ma se faccio una ricerca, trovo qualcosa di simile al mio problema, apro la issue e le relative PR, vedo che è il mio problema e vedo anche che per la mia versione magari non è stato risolto

**Comment by primes2h** [comment]
> Direi di no. Ma se faccio una ricerca, trovo qualcosa di simile al mio problema, apro la issue e le relative PR, vedo che è il mio problema e vedo anche che per la mia versione magari non è stato risolto

Capisco la necessità, ma proporrei di aggiungere almeno un'etichetta alla issue per tenerne traccia dopo la chiusura (almeno per la 11.0, la 8.0 non è più ufficialmente supportata). 
Agevolerebbe molto la ricerca per chi volesse eventualmente metterci le mani.

**Comment by eLBati** [comment]
@primes2h ok per me

**Comment by primes2h** [comment]
> @primes2h ok per me

Una proposta potrebbe essere questa:

Nelle issue di tracciabilità chiuse (o da chiudere) lasciamo l'etichetta "help wanted" e aggiungiamo quella per la versione mancante insieme a "needs fixing".

Parlando in generale, propongo di aggiungere l'etichetta "tracking" per identificare le issue (aperte e chiuse) di tracciabilità, renderebbe più semplice la loro ricerca.

Che ne dite @OCA/local-italy-developers ?
