### ISSUE TITLE
pip3 install odoo12-addon-l10n-it-fatturapa-out -> No matching distribution found for odoo<12.1dev,>=12.0a (from odoo12-addon-l10n-it-fatturapa-out)

### ISSUE THREAD

**Issue by trottomv** [OCA/l10n-italy#1454]
Versioni coinvolte: 12

Passi per riprodurre:
ho installato odoo12 community edition con docker
https://docs.docker.com/samples/library/odoo/

Comportamento osservato:
entrando nel container con il comando 
`docker exec -it odoo /bin/bash`
si prende controllo della shell bash del container docker

per installare il modulo della fatturazione elettronica, dalla shell in docker eseguendo il comando:
`pip3 install odoo12-addon-l10n-it-fatturapa-out`

l'installazione del modulo non va a buon fine e torna questo errore:
`Could not find a version that satisfies the requirement odoo<12.1dev,>=12.0a (from odoo12-addon-l10n-it-fatturapa-out) (from versions: )`
`No matching distribution found for odoo<12.1dev,>=12.0a (from odoo12-addon-l10n-it-fatturapa-out)
`

Comportamento atteso:
il modulo dovrebbe installarsi senza errori

Video/Screenshot (opzionale):
![Screenshot at 2019-09-18 15:11:16](https://user-images.githubusercontent.com/17194729/65151536-954d6300-da26-11e9-86e8-31a7b8958646.png)

**Comment by eLBati** [comment]
`odoo` deve essere installato con pip, quindi ad esempio con
`pip install http://nightly.odoo.com/12.0/nightly/src/odoo_12.0.latest.tar.gz`
o
`pip install -e git+https://github.com/odoo/odoo.git@12.0#egg=odoo`
