### ISSUE TITLE
Errore installazione modulo DDT

### ISSUE THREAD

**Issue by SGiuseppe** [OCA/l10n-italy#146]
Ho cercato di installare il modulo DDT ma ho riscontrato degli errori e non mi da la possibilita di provarlo. Di seguito l'errore:

File "/home/odoo/8.0/odoo/openerp/tools/convert.py", line 895, in convert_file
convert_csv_import(cr, module, pathname, fp.read(), idref, mode, noupdate)
File "/home/odoo/8.0/odoo/openerp/tools/convert.py", line 963, in convert_csv_import
raise Exception(_('Module loading %s failed: file %s could not be processed:\n %s') % (module, fname, warning_msg))
Exception: Module loading l10n_it_ddt failed: file l10n_it_ddt/security/ir.model.access.csv could not be processed:
Line 9 : Nessun record trovato per id esterno 'model_stock_ddt_type' nel campo 'Object'

Mi riferisco al modulo 
git clone -b 8.0-add-stock_picking_package_preparation_line https://github.com/OpenCode/stock-logistics-workflow.git
git clone -b 8.0-ddt-based-on-packaging-preparation_lb https://github.com/eLBati/l10n-italy.git

**Comment by eLBati** [comment]
Ciao @SGiuseppe sei sicuro di avere le ultime revisioni dei branch (compreso odoo) e di non avere un database compromesso?
Ho appena creato un nuovo DB e installato il modulo l10n_it_ddt senza problemi.
Puoi descrivere i passi per riprodurre il problema su un nuovo DB?
Grazie

**Comment by SGiuseppe** [comment]
Ok. Ho aggiornato il modulo da git.... e ho notato che ci sono stati dei cambiamenti. Ora si installa senza problemi. Farò un po di test per vedere la funzionalità.

Grazie.

**Comment by Mitconsulting** [comment]
ciao @SGiuseppe mi dici come hai risolto il problema...io sto avendo il tuo stesso problema quando provo ad installare il modulo l10n_it_ddt sulla versione 8

**Comment by OpenCode** [comment]
@Mitconsulting 

possibilmente evitiamo il cross tra issue diverse altrimenti iniziamo sessioni di domande/risposte divergenti e dispersive

https://github.com/OCA/l10n-italy/issues/176

**Comment by SGiuseppe** [comment]
Ho semplicemente aggiornato il repository con il comando
git pull

ho notato che vi erano dei cambiamenti nel sorgente. A quel punto ho semplicemente reinstallato il modulo. Senza il problema citato su. Devo dire che non ho riprovato a reinstallarlo su in altro database e non ho fatto altri aggiornamenti.
