### ISSUE TITLE
Fattura fornitore collegata ad acquisto in bozza

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1476]
@stevech091 @SimoRubi per il domain, penso che per l'utente possa essere meglio trovare troppi ordini, poi filtrabili, piuttosto che troppo pochi, con un domain che non ti permette  di espandere l'insieme.

In generale forse potrebbero esserci dei casi in cui la fattura arriva, prima che l'ordine sia stato confermato.

Eventualmente apriamo una issue o una PR a parte dove discuterne.

Per questa, se siete d'accordo, procederei con il merge

_Originally posted by @eLBati in https://github.com/OCA/l10n-italy/pull/1439#issuecomment-535808834_

**Comment by stevech091** [comment]
io sono per filtrare perche' un ordine di acquisto non confermato non ha senso che possa già collegarlo ad una fattura.
Prima lo devo confermare e poi lo vedo nella parte di fatture.

**Comment by eLBati** [comment]
Ci può stare in effetti
