### ISSUE TITLE
Manage WT for customer invoices

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1483]
Versioni coinvolte:

 - [ ] 10.0: https://github.com/OCA/l10n-italy/pull/1433
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/1488 (per `l10n_it_withholding_tax_payment` c'è https://github.com/OCA/l10n-italy/pull/1281)

**Comment by primes2h** [comment]
Andrebbe messa la spunta sulla v12, è stato fatto il merge delle relative PR.

**Comment by OpenCode** [comment]
> Andrebbe messa la spunta sulla v12, è stato fatto il merge delle relative PR.

Fatto
