### ISSUE TITLE
l10n_it_reverse_charge: Generare fattura e auto fattura, con aliquota IVA 0%

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1491]
### Versioni coinvolte:

 - [x] 10.0: https://github.com/OCA/l10n-italy/pull/1492
 - [ ] 11.0
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/1503

### Passi per riprodurre:

creare 2 codici iva (1 acquisti e 1 vendite) con % a 0

**acquisti**

![image](https://user-images.githubusercontent.com/1033131/66919989-b94e9500-f022-11e9-9238-4d0a08e3d366.png)

**vendite**

![image](https://user-images.githubusercontent.com/1033131/66920001-c075a300-f022-11e9-95c0-67e4cd231c68.png)

Crea la relativa configurazione sul reverse charge

![image](https://user-images.githubusercontent.com/1033131/66920014-c5d2ed80-f022-11e9-9dcd-248dc5dbeae5.png)

e posizione fiscale

![image](https://user-images.githubusercontent.com/1033131/66920021-ca97a180-f022-11e9-911f-8b532de80f8e.png)

poi vado a fare una fattura 

![image](https://user-images.githubusercontent.com/1033131/66920041-d1261900-f022-11e9-900f-12aaee9c8ed7.png)

### Comportamento osservato:

![image](https://user-images.githubusercontent.com/1033131/66920058-d7b49080-f022-11e9-8951-3de6eb0f5ad3.png)

### Comportamento atteso:

la validazione della fattura di reverse e creazione della relativa fattura di vendita

**Comment by primes2h** [comment]
Chiudo, è stato fatto il merge per le versioni principali supportate.
