### ISSUE TITLE
Travis: l10n_it_fatturapa - No module named asn1crypto 

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1495]
Versioni coinvolte:

 - [x] 8.0 https://github.com/OCA/l10n-italy/pull/1498
 - [x] 10.0: https://github.com/OCA/l10n-italy/pull/1496
 - [x] 11.0 https://github.com/OCA/l10n-italy/pull/1508
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1497

Da oggi travis fallisce con
`UserError: (u'Unable to install module "l10n_it_fatturapa" because an external dependency is not met: No module named asn1crypto', '')`

**Comment by GuzuGuzu** [comment]
> 
> 
> Versioni coinvolte:
> 
>     * [ ]  8.0 #1498
> 
>     * [x]  10.0: #1496
> 
>     * [ ]  11.0
> 
>     * [x]  12.0: #1497
> 
> 
> Da oggi travis fallisce con
> `UserError: (u'Unable to install module "l10n_it_fatturapa" because an external dependency is not met: No module named asn1crypto', '')`

pip3 install asn1crypto

**Comment by sergiocorato** [comment]
qualcuno interessato alla 11.0?

**Comment by OpenCode** [comment]
> qualcuno interessato alla 11.0?

La faccio io

**Comment by sergiocorato** [comment]
close :tada:
