### ISSUE TITLE
[10] Two distinct partners with VAT number ITxxxxxxxxxxx and Fiscal Code xxxxxxxxxxx already present in db.

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1526]
L'importazione di un file XML relativo ad un fornitore che è presente anche come cliente, genera l'errore in oggetto.

**Comment by OpenCode** [comment]
Ciao @protontrigg3r,

Ti dispiacerebbe allegare l'errore completo? Se hai acceso al server sarebbe davvero utile avere tutto il messaggio così da comprendere da chi viene sollevato.

Grazie mille :)

**Comment by protontrigg3r** [comment]
Ciao @OpenCode . Quello riportato in oggetto è il messaggio di errore completo. Ti riferisci forse ai log di Odoo?

**Comment by sergiocorato** [comment]
> L'importazione di un file XML relativo ad un fornitore che è presente anche come cliente, genera l'errore in oggetto.

Cioè non c'è un unico partner con flaggati 'cliente' e 'fornitore'? Questo non è una pratica prevista.

**Comment by OpenCode** [comment]
> Ciao @OpenCode . Quello riportato in oggetto è il messaggio di errore completo, visualizzato dall'interfaccia grafica di Odoo tentando di importare l'XML . Ti riferisci forse ai log di Odoo?

Sì, mi riferivo al log. Ti invito comunque a prendere un attimo in considerazione il suggerimento di @sergiocorato. Se il sistema ti dice che la partita IVA che stai importanto è già presente, allora dovresti recarti nell'anagrafica di quel partner e indicare che oltre che essere cliente e anche fornitore.

**Comment by protontrigg3r** [comment]
Hai ragione @sergiocorato , non avevo nemmeno preso in considerazione che potesse essere questo il problema ... Grazie!

**Comment by protontrigg3r** [comment]
Mi sto chiedendo: come mai il campo Partita IVA ammette duplicati?

**Comment by eLBati** [comment]
Perchè non hai installato questo modulo https://github.com/OCA/partner-contact/tree/10.0/partner_vat_unique

**Comment by protontrigg3r** [comment]
Grazie @eLBati ma in realtà mi stavo chiedendo perché non c'è un vincolo di unicità su quel campo. Come mai serve un modulo aggiuntivo? Ci sono forse alcuni contesti in cui in Odoo è plausibile avere partner con la stessa PI?

**Comment by eLBati** [comment]
Non saprei, dovresti chiedere su https://github.com/odoo/odoo
