### ISSUE TITLE
liquidazione IVA: calcolo credito anno precedente e impostazione del campo corretto in comunicazione

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1527]
Versioni coinvolte:

 - [ ] 10.0: per `account_vat_period_end_statement` incluso in https://github.com/OCA/l10n-italy/pull/1679, per `l10n_it_vat_statement_communication` in https://github.com/OCA/l10n-italy/pull/1196
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1482 + https://github.com/OCA/l10n-italy/pull/1772

Passi per riprodurre:

 - Creare una fattura passiva a dicembre
 - Creare la liquidazione IVA, che andrà a credito
 - Creare una fattura passiva a gennaio
 - Creare la liquidazione IVA per gennaio

Comportamento desiderato:

Il campo "crediti anno precedente" viene impostato.

**Comment by primes2h** [comment]
Andrebbe tolta la spunta sulla v12, non è ancora stato fatto il merge della relativa PR.

**Comment by OpenCode** [comment]
> Andrebbe tolta la spunta sulla v12, non è ancora stato fatto il merge della relativa PR.

Fatto

**Comment by primes2h** [comment]
> > Andrebbe tolta la spunta sulla v12, non è ancora stato fatto il merge della relativa PR.
> 
> Fatto

Attenzione che è sparita la casella.

**Comment by primes2h** [comment]
@OpenCode perfetto, grazie!
