### ISSUE TITLE
[RFC] Modalità e Termini di pagamento nei moduli OCA di contabilità italiana e fatturazione elettronica

### ISSUE THREAD

**Issue by vincenzoterzulli** [OCA/l10n-italy#1528]
**PROBLEMA:**

Il modulo `account` di Odoo introduce nei partner e nelle fatture il concetto del _**termine di pagamento**_ (ovvero il "quando"), tuttavia ignora del tutto il concetto di _**modalità di pagamento**_ (ovvero il "come").

Esiste il modulo OCA `account_payment_mode` da v10 in poi https://github.com/OCA/bank-payment/tree/10.0/account_payment_mode, `account_payment` per v8 (ufficiale OdooERP SA) che compensa questa mancanza introducendo correttamente la modalità di pagamento e permettendo così di distinguere i due concetti.

Tuttavia il modulo OCA di fatturazione elettronica `l10n_it_fatturapa_out` non contempla la modalità di pagamento **come concetto distinto** dal termine di pagamento, bensì come concetto unico **"modalità e termine di pagamento"**, portando così l'utente ad adottare una sovrapposizione di concetti in un unico campo. Nel wizard di esportazione infatti si fa riferimento al termine per ottenere invece la modalità:
https://github.com/OCA/l10n-italy/blob/360d4d2f1fbbca9b3f019dbb87d1bec8de70e0f8/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L772

Nei casi di test affrontati dal modulo `l10n_it_fatturapa_out` viene sempre specificato il termine di pagamento, e mai la modalità.
https://github.com/OCA/l10n-italy/blob/360d4d2f1fbbca9b3f019dbb87d1bec8de70e0f8/l10n_it_fatturapa_out/tests/test_fatturapa_xml_validation.py#L41

Nel modulo `l10n_it_fiscal_payment_term` (contrariamente a quanto ci si potrebbe aspettare dal suo nome) si introducono le seguenti "novità":
* nei termini di pagamento la correlazione con i termini di pagamento previsti dall'ADE (m2o verso `fatturapa.payment_term`)
* nei termini di pagamento la correlazione con le modalità di pagamento previsti dall'ADE (m2o verso `fatturapa.payment_method`)

E' evidente la forzatura: i termini di pagamento di odoo sono utilizzati per rappresentare due concetti differenti..
https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_fiscal_payment_term/models/account.py

A questo punto mi chiedo: come mai i moduli della fatturazione elettronica non contemplano la distinzione tra modalità di pagamento e termine di pagamento, nonostante in Italia questo concetto esiste ed è ben definito? 
Sta di fatto che non solo la fattura elettronica ne richiede la distinzione, ma anche l'operatività giornaliera delle aziende che operano con i due concetti in maniera ben distinta.

I moduli OCA non contemplano questa distinzione, quindi nemmeno i casi di test attuali ne fanno una corretta verifica, ed è questo il nodo cruciale della discussione. Secondo me si dovrebbe fare bene la distinzione tra i due concetti e quindi affrontare anche nei casi di test le dovute differenze, nell'esportazione verso la PA e nei report delle fatture.

**SOLUZIONE:**

Propongo quindi:
1. introdurre il modulo `l10n_it_fiscal_payment_mode` per aggiungere nelle modalità di pagamento la correlazione con le modalità di pagamento previste dall'ADE
https://github.com/elvenstudiotmp/l10n-italy/tree/8.0/l10n_it_fiscal_payment_mode
2. a cascata introdurre quindi dipendenza a `account_payment` (in `l10n_it_fiscal_payment_mode`) per introdurre il concetto di _modalità di pagamento_ su Odoo
https://github.com/elvenstudiotmp/l10n-italy/blob/e9be33d0b31b285d0aaacc411389e4659bf72d97/l10n_it_fiscal_payment_mode/__openerp__.py#L19
3. correggere il modulo `l10n_it_fiscal_payment_term` per operare solo sui termini di pagamento
https://github.com/elvenstudiotmp/l10n-italy/tree/8.0/l10n_it_fiscal_payment_term
4. nel modulo `l10n_it_fatturapa` aggiungere dipendenza a `l10n_it_fiscal_payment_mode` e contemplare correttamente le distinzioni esistenti in fase di esportazione
https://github.com/elvenstudiotmp/l10n-italy/blob/e9be33d0b31b285d0aaacc411389e4659bf72d97/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L718
5. correggere i casi di test di `l10n_it_fatturapa_out` 

I punti da 1 a 4 per Odoo v8 sono già fatti nel nostro repo https://github.com/elvenstudiotmp/l10n-italy e i moduli sono già in produzione (ovviamente non escludo che ci siano miglioramenti da fare in quanto queste correzioni sono state effettuate ad inizio anno in fretta e furia). Di sicuro mancano i test del punto 5 ed altri ed eventuali

Se siete d'accordo con questa idea mi occuperei io di fare la PR sul repo OCA per odoo v8, ma ovviamente vorrei prima capire cosa ne pensate.

**Comment by eLBati** [comment]
@vincenzoterzulli il tuo approccio secondo me è corretto, quindi la PR da parte mia è ben accetta. Certo l'ideale sarebbe averla almeno su 10.0.

In ogni caso attenzione che una modifica alla struttura dati necessita obbligatoriamente di script di migrazione dati, altrimenti chi si è configurato i propri termini di pagamento usando la versione attuale di `l10n_it_fiscal_payment_term` aggiornando perderebbe dei dati.

**Comment by vincenzoterzulli** [comment]
Avevo dimenticato che già tempo fa avevo sollevato la stessa questione. 
Riporto i link alla PR con la discussione che se ne fece allora per completezza. #827

**Comment by eLBati** [comment]
Quindi la https://github.com/OCA/l10n-italy/pull/827 implementa quanto descritto da questa issue?
