### ISSUE TITLE
l10n_it_fatturapa_in: nella scadenza della fattura usare la data più remota tra quelle presenti in DataScadenzaPagamento

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1536]
Versioni coinvolte:

 - [ ] 10.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1537

**Comment by vincenzoterzulli** [comment]
Perché la più recente? 
Il concetto di "scadenza fattura" è diverso dal concetto di "data della prima scadenza". Infatti in odoo si considera come data di scadenza di una fattura quella della sua **ultima scadenza**

**Comment by bitit-it** [comment]
ma c'è sempre la possibilità di editarla all'emissione della fattura?

**Comment by eLBati** [comment]
@vincenzoterzulli hai ragione, ho modificato la PR https://github.com/OCA/l10n-italy/pull/1537 : https://github.com/OCA/l10n-italy/compare/bf2db4eeca65042bab1282906d86365932c7df78..5eee1b0c276d2866fbc1bf1e76df4ca99188c4c2
Grazie

**Comment by eLBati** [comment]
@bitit-it certo

**Comment by bitit-it** [comment]
Mi sa che è tardi, ho provato a reinstallare odoo 10 
ma io dentro l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py 
quella porzione di codice non la trovo

**Comment by eLBati** [comment]
@bitit-it dalla descrizione di questa issue puoi vedere che la modifica è stata fatta solo per 12.0

**Comment by bitit-it** [comment]
Ok. la 12   sto cercando di installarla su una macchina, ma non ci sono ancora riuscito . 
quindi niente :(

**Comment by tafaRU** [comment]
Già portata in `14.0`: https://github.com/OCA/l10n-italy/blob/971c1780420806388f05b09a91e7a46ddd721010/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1427-L1433
