### ISSUE TITLE
Rigenerare il file XML delle fatture in errore senza rimetterle in bozza

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1540]
- [8.0]
- [10.0] #1539 
- [12.0]

Descrizione del problema o della funzionalità:

Quando una fattura elettronica non viene accettata dallo SDI si è obbligati a rimettere in stato di bozza l'account invoice per poi procedere alla correzione e rigenerazione del file xml da inviare perdendo allo stesso tempo lo storico delle operazioni con lo SDI. Spesso l'errore è dovuto a questioni di codice fiscale, partita iva, codici univoci etc etc non corretti

Comportamento attuale prima di questa PR:

Non c'è possibilità di rigenerare solo il file xml in caso di errore 

Comportamento desiderato dopo questa PR:

Dare la possibilità all'utente di poter rigenerare solo il file xml in caso di errore senza dover rimettere la fattura in bozza

--
Confermo di aver firmato il CLA https://odoo-community.org/page/cla e di aver letto le linee guida su https://odoo-community.org/page/contributing

**Comment by CiroBoxHub** [comment]
Buongiorno, se ho ben capito questa è la casistica in cui l'errore non è sulla fattura ma sull'anagrafica cliente ad esempio.
Questa possibilità che io sappia è già presente:

![export_xml_odoo_10_not_draft](https://user-images.githubusercontent.com/16084466/69420055-2ccc7c00-0d1e-11ea-932f-0e2b7d653f0a.gif)

Non è questa la casistica?

**Comment by robyf70** [comment]
Si esatto! Ma quello che hai fatto di fà perdere la history

**Comment by CiroBoxHub** [comment]
ok ok, adesso ho compreso. 
Praticamente la pr farà in modo di rigenerare il file senza dover cancellare il precedente, ma effettuando solo una sostituzione con il file nuovo generato, se ho ben capito.

**Comment by robyf70** [comment]
Si! Rigenera il file xml e lo sostituisce a quello corrente. Chiaramente se bisogna firmarlo con la chiave privata lo si farà come al solito

**Comment by CiroBoxHub** [comment]
:+1:

**Comment by eLBati** [comment]
@robyf70 chiudiamo in favore di https://github.com/OCA/l10n-italy/issues/1566 ?

**Comment by robyf70** [comment]
Si assolutamente!
