### ISSUE TITLE
[12.0] l10n_it_ddt: problemi creazione DDT con picking in stato bozza e mediante inserimento di prodotti

### ISSUE THREAD

**Issue by ellesalvo** [OCA/l10n-italy#1547]
Versioni coinvolte:
12
Passi per riprodurre:

Creo un picking con relativi movimenti e lo lascio in stato bozza.
Creo un DDT nuovo ed aggiungo il picking creato precedentemente.
Giustamente non posso impostare il ddt a completato perchè non tutti i prelievi si trovano nell stato completato e non posso neanche metterli nel pacco perchè è impossibile creare un collo senza dettagli.
Se successivamente valido il picking e ritorno sul mio ddt e lo imposto a completato nei dettagli non trovo alcuna informazione quindi devo cancellare il ddt, rifarne uno nuovo ed aggiungere il picking in stato completato oppure devo eliminare il picking ed inserirlo nuovamente.

Mi aspettavo che una volta completato il picking il relativo ddt si "popolava" dei prodotti inseriti nei vari movimenti del picking.

Altra cosa che non mi convince è che invece quando si crea un DDT inserendo i prodotti non è possibile specificare prodotto, ubicazione di partenza, quantità, eventuale seriale o lotto (ad esempio se nel ddt volessi inserire 2 hard disk che si trovano in una data ubicazione di partenza il sistema dovrebbe suggerire i seriali che si trovano in quella data ubicazione ed io sceglierne due)
Questo è un problema a mio parere generale relativo alla creazione dei movimento di un picking relativo ad un prodotto che ho in magazzino pronto per essere movimentato.
Addirittura è possibile specificare un prodotto con un dato seriale già venduto e quando si clicca su metti nel pacco il risultato è errore python

**Comment by OpenCode** [comment]
Ciao @ellesalvo 

ti dispiacerebbe inserire un titolo più significativo per la issue?

Grazie mille

**Comment by ellesalvo** [comment]
Ciao @OpenCode, lo faccio subito. Spero sia più significativo.Mi piacerebbe contribuire ma non ho molta esperienza nell'uso di github

**Comment by OpenCode** [comment]
Non preoccuparti. Tutti abbiamo iniziato almeno una volta :)

Se hai screenshot o video che mostrano in maniera completa il problema che hai rilevato non esitare ad allegarli. Più materiale e informazioni ci sono è maggiore è la possibilità di risolvere il problema.

Intanto grazie per la segnalazione :)

**Comment by ellesalvo** [comment]
Creato un DB pulito in Odoo 12.0 - Edizione comunitaria
Installato il solo modulo l10n_it_ddt
Nelle impostazioni generali per il magazzino abilito la tracciabilità
![tracciabilità](https://user-images.githubusercontent.com/38501359/70308269-24d70680-180b-11ea-9cff-7cb8f8ffc3b5.jpg)
Abilito per gli ordini di consegna il mostra operazioni dettagliate.
Primo problema
Creo un prodotto Hard Disk di tipo seriale e Aggiorno la quantità mediante un aggiustamento dell’inventario al fine di avere 3 Hard Disk in magazzino con seriali 000001,00002,00003.
![3_hd_in_magazzino](https://user-images.githubusercontent.com/38501359/70308734-3076fd00-180c-11ea-870c-d93256a028c8.jpg)
Creo un ordine di consegna inserendo l’hard disk con seriale 00001 e lo lascio in stato bozza e creo un DDT mediante DDT da consegne.
![ordine_in_stato_bozza_ddt_da_consegne](https://user-images.githubusercontent.com/38501359/70308833-6ddb8a80-180c-11ea-9def-631256f31132.jpg)
Imposto nel DDT le condizioni di trasporto, la descrizione dei beni, la casuale di trasporto ed il metodo di trasporto.
![ddt_creato](https://user-images.githubusercontent.com/38501359/70308901-8f3c7680-180c-11ea-98ce-f43c33456223.jpg)
Nel DDT creato Metti nel Pacco e Imposta a completato giustamente non producono alcun effetto perchè l’ordine di consegna è ancora in stato bozza.
Valido il mio ordine di consegna e vado a controllare il DDT in cui era stato inserito, nella sezione dettagli non compare nulla.
![ddt_con_ordine_completato](https://user-images.githubusercontent.com/38501359/70309331-9617b900-180d-11ea-86a1-a85b9f672f6f.jpg)
![ddt_senza_dettagli](https://user-images.githubusercontent.com/38501359/70309255-64065700-180d-11ea-9a5c-a2e5ecf5045e.jpg)
La validazione dell’ordine di consegna non ha popolato i dettagli del DDT pertanto dal DDT devo eliminare l’ordine di consegna e sempre dal DDT devo aggiungerlo nuovamente per avere il DDT completo con i dettagli presenti  ed  impostarlo a completato.
![ddt_completo](https://user-images.githubusercontent.com/38501359/70309379-b34c8780-180d-11ea-8fde-6f523d58336f.jpg)

Secondo problema continuando la simulazione
Creo un secondo DDT impostando il Cliente, l’indirizzo di spedizione e le condizioni di trasporto, la descrizione dei beni, la casuale di trasporto ed il metodo di trasporto ed aggiungo il prodotto Hard Disk in quantità 1 e noto che il form di inserimento del prodotto
![ddt_con_seleziona_prodotti](https://user-images.githubusercontent.com/38501359/70309608-2ce47580-180e-11ea-9930-167809c29fde.jpg)
 mi permette di inserire il numero seriale e mi propone anche il seriale 000001 che io diciamo ho già venduto.Se viene inserito per errore questo seriale nel DDT il Metti nel Pacco ti avvisa che non è possibile anche se il messaggio dice solo che non è disponibile la quantità ma non dice nulla sul seriale, l’imposta a completato mette il ddt a completato ma non viene creato alcun ordine di consegna quindi sarebbe opportuno non permettere il completamento in quanto inutile.
Per quanto riguarda il secondo problema credo che quando si vuole creare un DDT specificando i prodotti da inserire il form di inserimento dei prodotti che compare nel DDT dovrebbe permettere all'utente se vuole di inserire il prodotto e la quantità di tale prodotto e lavorando con prodotti a seriale unico, a lotto e non tracciabili tutte le informazioni (seriali, lotti ed ubicazioni di magazzino) utili per determinare in modo univoco quali prodotti si vogliono movimentare e da quali ubicazioni si vogliono movimentare.Nel caso in cui queste informazioni non vengono inserite sarà poi diciamo Odoo a scegliere i prodotti (seriali, lotti ed ubicazioni)  da inserire nei relativi picking cosa che viene fatta nell’implementazione attuale.

Quindi ha senso inserire picking non confermati in un DDT ??
Ha senso se si crea un DDT inserire in modo specifico prodotto quantità seriali ed ubicazioni o bisogna lasciare fare all’algoritmo di Odoo che stabilisce quale seriale/lotto movimentare e da quale ubicazione ??

**Comment by eLBati** [comment]
> Creo un ordine di consegna inserendo l’hard disk con seriale 00001 e lo lascio in stato bozza

Come fai a lasciarlo in stato bozza? I seriali si possono aggiungere dopo aver confermato

**Comment by ellesalvo** [comment]
Ciao,
non so se ti ho capito bene, ma abilitando per gli ordini di consegna il mostra operazioni dettagliate, quando si crea l'ordine di consegna come trasferimento immediato e si sceglie il prodotto di tipo seriale si deve scegliere il seriale e l'ordine lo si può lasciare in stato bozza per aggiungere ad esempio ulteriori prodotti successivamente
E' obbligatorio inserire il seriale prima di validare (confermare) l'ordine di consegna
 ![msg_warning](https://user-images.githubusercontent.com/38501359/70895513-5e6bf680-1fef-11ea-8725-18a76ec307d1.jpg)

**Comment by eLBati** [comment]
Ah ok mi ero perso il "mostra operazioni dettagliate".

Se hai in mente una soluzione potresti proporre la PR?

**Comment by ellesalvo** [comment]
Ciao,
si mi piacerebbe ed ho in mente come risolvere la prima parte del problema.
Ho analizzato il codice per fare le cose come si deve ed in realtà mi sono reso conto che la creazione delle linee del DDT a cui sono stati aggiunti gli ordini avviene attraverso una _prepare_lines_from_pickings che è implemetata nel modulo stock_picking_package_preparation_line che però considera solo solo le move_lines dello stock.picking e non le move_line_ids_without_package che invece vengono create nel picking quando l'opzione "mostra operazioni dettagliate" è abilitata. Una _prepare_lines_from_pickings è implementata anche nel modulo l10n_it_ddt ma solo per "Add values used for invoice creation" quindi si potrebbe modificarla per fare creare linee del DDT quando il picking ha  stock.move di tipo move_line_ids_without_package ma in realtà andrebbe sistemata la _prepare_lines_from_pickings del modulo stock_picking_package_preparation_line perchè è questa che non restituisce lines from pickings quando per i pickings "mostra operazioni dettagliate" è abilitato.
Mi puoi suggerire come operare correttamente in questa situazione ??
