### ISSUE TITLE
[10] Impossibile annullare fatture con importo totale 0

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1561]
Se l'importo totale di una fattura è 0, dopo la sua validazione viene posta nello stato di "paid" e resa quindi non più annullabile. Io ho bisogno di sistemarla per inviarla a SDI. Come fare?

**Comment by sergiocorato** [comment]
non riesci a togliere la riconciliazione?
Sergio Corato


Il giorno ven 13 dic 2019 alle ore 18:42 protontrigg3r <
notifications@github.com> ha scritto:

**Comment by protontrigg3r** [comment]
Ciao @sergiocorato . Mi potresti indicare i passaggi?

**Comment by protontrigg3r** [comment]
Non trovo niente in relazione ai pagamenti.
Tutto ciò che trovo sono la registrazione e i movimenti contabili relativi alle due righe della fattura (che compensandosi portano il totale a 0). Riesco ad annullare la Registrazione contabile e quindi eliminare i relativi Movimenti, ma la fattura resta collegata alla Registrazione (che quindi non riesco ad eliminare) e sopratutto rimane nello stato "paid", quindi non annullabile.

**Comment by protontrigg3r** [comment]
Ho anche provato ad installare il modulo "Cancel payment line" ma eseguendo "Free Invoices" sulla fattura in questione ottengo "No payment line found".

**Comment by OpenCode** [comment]
@protontrigg3r il comportamento da te indicato è il modo in cui Odoo si comporta nel caso di fatture con importo totale a 0. Non crea pagamenti ma cambia lo stato.

Ti invito a guardare il modulo:

https://apps.odoo.com/apps/modules/10.0/account_invoice_zero_cancel/

Dovrebbe fare al caso tuo.

**Comment by protontrigg3r** [comment]
Grazie @OpenCode Risolto
