### ISSUE TITLE
Riorganizzazione del metodo di generazione fatture elettroniche

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1566]
La PR riorganizza il codice di ```l10n_it_fatturapa_out``` e ```l10n_it_fatturapa_pec``` tenendo conto delle funzionalità presenti nelle PR #1539 #1563.

- [ ] 8.0 
- [x] 10.0 #1565 
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/1859

**Comment by mrcast** [comment]
@robyf70 facendo riferimento alla #1540 descrivo un caso d'uso che andrebbe coperto.
- Invio XML
- scarto da parte di SDI per errore sulla fattura: (descrizione prodotto troppo ampia, problema iva, etc)
- in questo caso è necessario riportare a bozza la fattura, ma andrebbe cancellato XML perdendo così lo storico

PROPOSTA

se l'XML è nello stato "Sender error" dare la possibilità di:
- riportare a bozza la fattura per la modifica necessaria
- validare la fattura 
- rigenerare l'XML (funzionalità già presente)

che ne pensi?

**Comment by robyf70** [comment]
@mrcast Si potrebbe chiaramente fare, ma magari prima mergiamo la funzionalità dato che è in attesa da 8mesi ;)?

**Comment by mrcast** [comment]
@robyf70 : mi sembra sensato. grazie
