### ISSUE TITLE
Descrizione Iva per cassa non corretta nella selezione della posizione fiscale della società

### ISSUE THREAD

**Issue by l-realdon** [OCA/l10n-italy#1572]
Versioni coinvolte:
ultima disponibile per odoo 12.0

 - [ ] 10.0:
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1582

Passi per riprodurre:
selezionare iva per cassa come posizione fiscale della società nella tab e-fattura.
il file da correggere credo sia il seguente "l10n_it_fatturapa/data/fatturapa_data.xml"

Comportamento osservato:
la descrizione "IVA per cassa soggetti con volume d’affari inferiore ad euro 200.000 (art. 7, D.L. 185/2008)" fa riferimento ad una vecchia normativa superata

Comportamento atteso:
la descrizione corretta dovrebbe corrispondere a quella che poi effettivamente compare nell'xml della fattura elettronica, cioè "IVA per cassa - art. 32-bis, D.L. 83/2012"

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
@l-arnold grazie, vedi https://github.com/OCA/l10n-italy/pull/1582
