### ISSUE TITLE
[11] indicazione codice fiscale nella stampa in inglese

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1577]
Versioni coinvolte: 11

Passi per riprodurre: Stampa fattura 

Comportamento osservato: nella riga codice fiscale viene scritto Fiscal Code

Comportamento atteso:  andrebbe tradotto in italiano , Codice Fiscale

Enrico

**Comment by eLBati** [comment]
È possibile tradurre tutti i moduli tramite https://translation.odoo-community.org
