### ISSUE TITLE
[11] stampa fatture fornitori mancano diciture emittente e ricevente

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1578]
Versioni coinvolte: odoo11

 apro le fatture dei fornitori faccio una stampa  dove non si capisce chi ha emesso la fattura e chi l'ha ricevuta, il layout è uguale a quello della stampa delle fatture clienti.

mi sembra strano manchi l'idicazione di chi emette la fattura e di chi la riceve.
Enrico

**Comment by eLBati** [comment]
Non penso sia un malfunzionamento (il PDF delle fatture passive e chi andrebbe inviato?), comunque si tratterebbe di un funzionamento di odoo standard, quindi da tracciare su https://github.com/odoo/odoo

**Comment by bitit-it** [comment]
La fattura elettronica assume lo stesso valore della fattura cartacea, ma non è che la fattura cartacea non vale niente; è necessario avere una corretta stampa, anche se non per motivi fiscali, ma per motivi amministrativi e legali. 
se vai in un contezioso  gli  puoi portare un documento dove non si capisce chi è chi lo emette e chi lo riceve?

**Comment by bitit-it** [comment]
Ok.  grazie
Enrico

**Comment by eLBati** [comment]
Se vai in un contenzioso porti il documento che hai ricevuto dal fornitore, non quello che hai generato tu dal tuo gestionale
