### ISSUE TITLE
Errore calcolo segno su gruppi di conti

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1583]
**Versioni coinvolte:**
- [x] 11.0 https://github.com/OCA/l10n-italy/pull/1584
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/1585 + https://github.com/OCA/l10n-italy/pull/1626

**Passi per riprodurre:**
- su v12.0: https://github.com/OCA/l10n-italy/pull/1264#issuecomment-506641019
- su v11.0: analogo

**Comportamento osservato:**
1. Non esiste controllo sul valore del segno, che quindi può essere diverso da  +1 o -1.
2. Il controllo di conformità sul segno dei tipi di conto viene fatto solo all'interno di un gruppo, ma non tra i conti di un gruppo ed i conti dei suoi eventuali parent o children; questo fa sì che un gruppo G possa avere sottogruppi SG1 e SG2 , il primo con segno +1 ed il secondo con segno -1; al momento della valutazione del segno di G, questo varrà randomicamente +1 o -1 a seconda di quale dei due sottogruppi viene valutato prima.
3. Il segno di un gruppo di conti viene preso analizzando solo il primo "ramo" dei possibili sottogruppi, senza analizzare gli altri rami né eventuali altri rami del suo stesso parent. Se il primo ramo non ha conti, al gruppo viene assegnato in automatico il segno +1, anche se altri rami o il suo parent potrebbero avere conti il cui tipo ha segno -1.

**Comportamento atteso:**
1. Il valore del segno può essere solo ±1.
2. Il controllo di conformità sul segno dei tipi di conto va fatto su parent e children per avere una coerenza del segno sull'intero albero gerarchico dei conti.
3. La valutazione del segno di un gruppo va fatta a cascata dal progenitore (gruppo con `parent_id` non valorizzato): il gruppo progenitore prende il segno dal primo conto disponibile al suo interno o nei suoi sottogruppi; i suoi sottogruppi prendono il segno dal progenitore.

NB: si aggiunge l'assenza di eventuali controlli sulla ricorsività dei gruppi di conti: il gruppo A può essere padre del gruppo B e contemporaneamente esserne figlio. Questo rende impossibile il calcolo del segno come sopra descritto.

**Comment by SilvioGregorini** [comment]
@eLBati cosa manca sulla v11.0? Così vedo di sistemare anche quella, se serve!

**Comment by eLBati** [comment]
@SilvioGregorini non saprei, a prima vista mi sembrano diverse le implementazioni di alcuni metodi

**Comment by SilvioGregorini** [comment]
@eLBati ho allineato la PR su 11.0 a quella su 12.0, aggiungendo anche il tuo commit con cherry-pick per evitare il blocco in fase di aggiornamento.

**Comment by SilvioGregorini** [comment]
@eLBati riguardo a questa issue: ho fatto un leggero bugfix, che trovi in #1626 per la v12 ed è già incluso in #1584 (con cherry pick) per la v11.
Manca altro in queste PR?

**Comment by primes2h** [comment]
Questo problema si presenta anche sulla v.10.0?

**Comment by marco-marchiori** [comment]
Dall'uso del modulo e da quanto leggo capisco che:
- viene assegnato un segno a ciascun account type
- viene assegnato un segno a ciascun gruppo.
Un conto con AT di segno negativo non può essere incluso in un G di segno positivo
e viceversa.

1) a quale caso d'uso risponde questa impostazione?
2) se l'utente ha bisogno di nettare in un gruppo valori/conto di segno diverso come potrebbe fare?

**Comment by marco-marchiori** [comment]
Scusate, non vedo risposte alla questione.
Perché e secondo quale caso d'uso questo cambiamento è stato fatto?
