### ISSUE TITLE
l10n_it_fatturapa_in: usa la data ricezione come data contabile (configurabile)

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1594]
Versioni coinvolte:

 - [x] 10.0: https://github.com/OCA/l10n-italy/pull/1634
- [ ] 11.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1613

Vedi https://github.com/OCA/l10n-italy/issues/1364#issuecomment-574674608

Nel caso "critico" di fattura con data 31 marzo ricevuta il 10 aprile, se contabilmente viene tutto registrato con data 10 aprile siamo sicuri di non sbagliare

**Comment by marco-marchiori** [comment]
Nel caso critico di fattura con data 31 marzo ricevuta il 10 aprile il contabile DECIDE, compatibilmente con altri presupposti, con che data registrare. Se indotto a registare poi quando puo' registrare prima l'azienda ritarda il diritto alla detrazione con danno finanziario. Questione abbondantemente trattata a LUGLIO. Perche' ritirata fuori ora?

**Comment by marco-marchiori** [comment]
Puo' avere un senso ancorche' opinabile, riportare la "received bill date" nel form fattura, in particolare per i noti casi di fine anno, che attualmente sono oggetto di contestazione a livello istituzionale.
Non va -in generale- bene riprendere quella data come data di registrazione, anche se una quota di clienti potrebbe gradirlo.

**Comment by eLBati** [comment]
Per la 10 dipendiamo da https://github.com/OCA/l10n-italy/pull/1363

@sergiocorato puoi aggiornare la tua review https://github.com/OCA/l10n-italy/pull/1363#pullrequestreview-265890705 ?

**Comment by eLBati** [comment]
Per v10: https://github.com/OCA/l10n-italy/pull/1634

**Comment by primes2h** [comment]
Chiudo perchè completato per la 10.0 e la 12.0.
