### ISSUE TITLE
Dichiarazione Intrastat: Arrotondamenti a 1 in caso di valore inferiore a zero (AMMONT. EURO, VALORE STATIST, MASSA NETTA, UNITA' SUPPL)

### ISSUE THREAD

**Issue by labaggio** [OCA/l10n-italy#1602]
Versioni coinvolte:
- [ ] 10.0
- [ ] 11.0
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/1611

Comportamento osservato:
La dichiarazione arrotonda il valore ad un numero intero, inserendo 0, dove il valore è <= 0.5

Comportamento atteso:
I valori di Euro, Massa e Unità devono essere arrotondato all'unità, ma mai con valore minore di 1

Fonte: https://www.adm.gov.it/portale/documents/20182/908833/AllegatoXI++DEF+18+2+15.pdf/34c12ee1-d810-4be5-bfcf-1ff2e0bfe9ab

> 4. Gli importi da indicare nelle colonne "AMMONTARE DELLE OPERAZIONI IN EURO" e "VALORE
> STATISTICO IN EURO" sono arrotondati all'euro. L'arrotondamento va effettuato per difetto, se la frazione è
> inferiore a 0,5 euro, e per eccesso se è uguale o superiore. Nel solo caso di importi inferiori a 0,5 euro l’importo
> da indicare dovrà essere sempre pari a 1 euro.
> 5. Le quantità da indicare nelle colonne "MASSA NETTA" e "UNITA' SUPPLEMENTARI" sono arrotondate
> all'unità. Nel solo caso di quantità di “MASSA NETTA” inferiori a 1 Kg si dovrà indicare 1
>

**Comment by OpenCode** [comment]
@labaggio Deduco che serva una PR correttiva. Creiamo la lista delle varie versioni così man mano linkiamo la relativa PR?

**Comment by labaggio** [comment]
> @labaggio Deduco che serva una PR correttiva. Creiamo la lista delle varie versioni così man mano linkiamo la relativa PR?

Esatto, a breve faccio quella della 12.0

**Comment by labaggio** [comment]
> Ho aggiunto la lista delle versioni al testo della issue

Fatta PR per la 12.0.
La versione 8.0 non c'è su l10n-italy, il modulo è stato inserito dalla 10.0 ;)
