### ISSUE TITLE
Stampa Registri IVA: mostrare totali giornalieri

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1609]
Versioni coinvolte:
- [ ] 10.0
- [x] 11.0 #1593
- [ ] 12.0 https://github.com/OCA/l10n-italy/pull/2397
- [ ] 14.0

Comportamento osservato:
L'attuale stampa dei registri IVA mostra i dati raggruppati per documento o solo totali. 

Comportamento atteso:
Implementare il raggruppamento IVA anche per singolo giorno.

**Comment by eLBati** [comment]
Da valutare quale tenere fra questa e la https://github.com/OCA/l10n-italy/issues/2702
