### ISSUE TITLE
[7.0] Runbot builds are yellow due to some warnings

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#161]
The PRs on branch 7.0 are yellow: https://runbot.odoo-community.org/runbot/repo/github-com-oca-l10n-italy-122

This is due to some warnings such as:
`openerp.addons.base.ir.ir_ui_view: Setting the `type` field is deprecated in the `ir.ui.view` model.`
See https://runbot2.odoo-community.org/runbot/static/build/3135366-7-0-314c68/logs/job_20_test_all.txt for further info.

**Comment by eLBati** [comment]
@tafaRU si può chiudere?
