### ISSUE TITLE
[11] problema recezione fatture a PEC

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#1612]
Buon giorno su odoo11 ho un problema che su 10 non si era manifestato;  quando mi arriva una fattura in pec, se  ho gia letto il messaggio prima che odoo verifiche se ci sono nuove fatture, odoo non scarica la fattura;  devo reimpostare il messaggio come da leggere  perchè  la fattura si posizioni in fatture elettroniche in ingresso

Enrico

**Comment by eLBati** [comment]
Questo è il comportamento previsto ed è lo stesso anche su v10

**Comment by bitit-it** [comment]
Se mi posso permettere, questo obbliga ad avere un indirizzo pec dedicato per la fattura elettronica, altrimenti, ogni volta, devo entrare in webmail e reimpostare i messaggi come non letti per caricarli on odoo.
In oltre se oddo non mi svutota periodicamente la cartella di posta dedicata, ad un certo punto c'è il rischio di saturazione, quindi di una manutenzione manuale della casella; se me la svuota e per qualche ragione mi crescha oddo e perdo gli archivi, non sarà così immediato recuperare i file se non  andare nell'archivio di conservazione remoto.

Sicuramente avevo qualcosa di sbagliato io ma con odoo10 in tutto il 2019  non ho avuto problemi di queto tipo.

**Comment by eLBati** [comment]
> questo obbliga ad avere un indirizzo pec dedicato per la fattura elettronica

Non è obbligatorio ma fortemente consigliato

> In oltre se oddo non mi svutota periodicamente la cartella di posta dedicata, ad un certo punto c'è il rischio di saturazione

Per questo potresti voler valutare (e portare a 11) il modulo https://github.com/OCA/social/tree/10.0/mail_check_mailbox_size

> Sicuramente avevo qualcosa di sbagliato io ma con odoo10 in tutto il 2019 non ho avuto problemi di queto tipo

Su v10 questo comportamento è identico
