### ISSUE TITLE
l10n_it_fatturapa_in: invoice lines with quantity 0

### ISSUE THREAD

**Issue by sherpya** [OCA/l10n-italy#1615]
- [ ] v8: ?
 - [x] v10: #1614
 - [ ] v11: #1630
 - [x] v12: #1618

**Descrizione del problema o della funzionalità:**
esistono delle fatture elettroniche con linea quantità a zero

**Comportamento attuale prima di questa PR:**
le linee vengono importate con quantità 1

**Comportamento desiderato dopo questa PR:**
le linee vengono importate con quantità 0

**Comment by sherpya** [comment]
ho sistemato anche il totale nella fattura di esempio

**Comment by eLBati** [comment]
Grazie @sherpya , prevedi di portarla anche a v12?

**Comment by sherpya** [comment]
> Grazie @sherpya , prevedi di portarla anche a v12?

dopo mergiata la v10 posso farlo (non vorrei riportare modifiche avanti e dietro), se non ho capito male è sufficiente applicare la stessa patch

**Comment by eLBati** [comment]
Ecco https://github.com/OCA/l10n-italy/pull/1614#issuecomment-580438185

> se non ho capito male è sufficiente applicare la stessa patch

Teoricamente sì

**Comment by sherpya** [comment]
@eLBati la fix si il test conflittava, ho messo nome specifico al test e all'xml, il checkbox va markato dopo il merge o già ora che ho aperto la PR?

**Comment by eLBati** [comment]
@sherpya grazie

> il checkbox va markato dopo il merge o già ora che ho aperto la PR?

Dopo il merge

**Comment by eLBati** [comment]
@primes2h mi ricordi la tua proposta relativa alla chiusura o meno delle issue risolte in v10 e v12?

Questa issue l'avrei chiusa, ma non ricordo cosa suggerivi.

Magari poi scriviamo la procedura da qualche parte, una volta decisa.

**Comment by primes2h** [comment]
> @primes2h mi ricordi la tua proposta relativa alla chiusura o meno delle issue risolte in v10 e v12?

La trovi qui https://github.com/OCA/l10n-italy/issues/1452#issuecomment-576845652
Un'etichetta (o due) aggiunte alla issue agevolerebbe molto la ricerca per chi volesse eventualmente metterci le mani in futuro.
Una cosa tipo "11.0 todo ( o missing)"

**Comment by sherpya** [comment]
aggiunto la 11, vediamo se i test vanno a buon fine, per la 13?

**Comment by eLBati** [comment]
Per la 13 il modulo l10n_it_fatturapa_in non esiste
