### ISSUE TITLE
[12.0] Errore cron fetchmail server

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1617]
Versioni coinvolte:

Passi per riprodurre: ~installare il modulo l10n_it_fatturapa_pec~ usare postgresql v. 11.5. Con postgresql 9.6 l'errore non compare

Comportamento osservato: nel log del postgres viene segnalato che il cron non riesce a bloccare la scrittura sulla tabella: `ERRORE:  lock di riga nella relazione "ir_cron" fallito`

Comportamento atteso: nessun errore

**Comment by sergiocorato** [comment]
Purtroppo ho visto dopo che l'errore mi si ripresenta comunque (il cron è configurato a 1). Se non succede ad altri, chiudo la issue.

**Comment by eLBati** [comment]
Se esegui il cron di fetchmail ogni minuto, c'è il forte rischio che il sistema cerchi di farne partire un altro prima che sia terminato il precedente, generando l'errore che vedi

**Comment by sergiocorato** [comment]
Ho scritto poco chiaramente, il cron viene chiamato ogni 5 minuti, l'1 è il `max_cron_threads = 1`.

**Comment by eLBati** [comment]
Ah, allora servirebbero più informazioni per riprodurre/identificare il problema

**Comment by sergiocorato** [comment]
Forse postgresql 11.5 potrebbe portare dei problemi con Odoo 12.0?

**Comment by sergiocorato** [comment]
Downgradando a 9.6 l'errore sparisce :O

**Comment by primes2h** [comment]
@sergiocorato 
Dato che non è (più) una issue di tracciabilità toglierei lo schema con le versioni coinvolte nella descrizione.
Dato che, se non ho capito male, capita con la v12.0, aggiungerei l'info direttamente nel titolo [12.0].

**Comment by sergiocorato** [comment]
:+1:

**Comment by eLBati** [comment]
Ma quindi c'è un bug riproducibile?
