### ISSUE TITLE
[10.0][12.0] Errore in fatturapa_out con fatture di accconto

### ISSUE THREAD

**Issue by elvise** [OCA/l10n-italy#1623]
**Versioni coinvolte:**
V10.0 e V12.0

**Passi per riprodurre:**
1 creato ordine di vendita per 1.000€
2 creato fattura di acconto per 200€
3 inviata FE
4 creato fattura al netto dell’acconto
5 invio fattura elettronica
6 errore: non ammessa qty -1

**Comportamento osservato:**
La qty -1 viene inserita da Odoo quando emette la fattura al netto delle precedenti di acconto.

**Comportamento atteso:**
Passare al file XML quantità positive

**Video/Screenshot (opzionale):**
![photo_2020-02-05 10 40 16](https://user-images.githubusercontent.com/5269577/73829886-fde58280-4803-11ea-904e-010f24bfc99e.jpeg)

**Comment by PatosMarco** [comment]
Mi permetto di aggiungere che la issue segnalata riguarda, oltre che la V12 anche la **V10**

**Comment by eLBati** [comment]
Questa la chiuderei in favore della https://github.com/OCA/l10n-italy/issues/2090
