### ISSUE TITLE
Liquidazione IVA: acconto (e metodo di calcolo) in VP13

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1646]
Versioni coinvolte:

 - [ ] 10.0:
 - [ ] 11.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1647 + https://github.com/OCA/l10n-italy/pull/1658

Passi per riprodurre:

Creare una liquidazione IVA e inserire l'acconto in "Crediti d'imposta" o "Altri crediti / debiti per IVA"

Comportamento osservato:

VP13 non viene valorizzato

Comportamento atteso:

VP13 viene valorizzato e VP14 calcolato di conseguenza

**Comment by mrcast** [comment]
@eLBati : se valorizzo solo "Altri crediti / debiti per IVA" quale campo VP deve essere valorizzato?

**Comment by eLBati** [comment]
@mrcast i crediti/debiti generici influiscono sul totale dell'IVA detratta/esigibile
