### ISSUE TITLE
VP14 non deve essere compilato dai contribuenti trimestrali di cui all’art. 7 del d.P.R. 14 ottobre 1999, n.542, relativamente al 4° trimestre

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1649]
Versioni coinvolte:

 - [ ] 10.0 Incluso in https://github.com/OCA/l10n-italy/pull/1196
 - [ ] 11.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1647 + https://github.com/OCA/l10n-italy/pull/1664

Passi per riprodurre:

Preparare comunicazione liquidazione IVA trimestrale per il 4° trimestre

Comportamento osservato:

Il campo relativo  a VP14 (`iva_da_versare` o `iva_a_credito`) viene valorizzato

Comportamento atteso:

Il campo non viene valorizzato
Vedi https://www.agenziaentrate.gov.it/portale/documents/20143/296732/Provvedimento+21032018+Iva+periodica_Modello_IVA+periodica.pdf/abf0de79-fd2f-93b1-b15f-71a8e942c78f

**Comment by mrcast** [comment]
@eLBati : non mi è chiaro qui se è sufficiente scegliere un date range trimestrale o se devo indicare altro in Odoo per ottenere il comportamento atteso

**Comment by alessandrocamilli** [comment]
@mrcast nel quadro VP, c'è il campo dove va indicato se si tratta di dichiarazione mensile o trimestrale. Quindi non dipende dal date range

**Comment by mrcast** [comment]
@alessandrocamilli : grazie!

**Comment by eLBati** [comment]
Sembra che però l'XML non passi i controlli se `ImportoDaVersare` o `ImportoACredito` non sono valorizzati...

**Comment by eLBati** [comment]
> Sembra che però l'XML non passi i controlli se `ImportoDaVersare` o `ImportoACredito` non sono valorizzati...

https://github.com/OCA/l10n-italy/pull/1664
