### ISSUE TITLE
[FIX] l10n_it_central_journal: Break long words in fields that can contain them

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1651]
**Versioni coinvolte**
Facendo stampe con molte righe (ho provato con 50 pagine) e parole molto lunghe (ad esempio un Riferimento `390eb05bc90694693be7b8ed91674f5d`), la funzionalità `smart-shrink` di `wkhtmltopdf` rimpicciolisce tutta la tabella e può arrivare a spostarla e tagliare le ultime colonne a destra.

Disabilitare `smart-shrink` non porta il risultato desiderato perché la tabella non sta nella pagina, quindi il mio suggerimento è di spezzare le parole troppo lunghe.

 - [x] v10: https://github.com/OCA/l10n-italy/pull/1652
 - [ ] v11: ?
 - [ ] v12: ?

**Passi per riprodurre**

1. Generare movimenti contabili per almeno 50 pagine del report in Contabilità > Report > Libro giornale.
2. Stampare il report.

**Comportamento osservato**
Le colonne `debit` e `credit` risultano tagliate:
![image](https://user-images.githubusercontent.com/32064796/75142590-b57aff80-56f3-11ea-93ed-35e477cc605b.png)

**Comportamento atteso**
Tutte le colonne sono visibili:
![image](https://user-images.githubusercontent.com/32064796/75142397-48676a00-56f3-11ea-900e-77d62b7c1fb8.png)

**Comment by SimoRubi** [comment]
@primes2h in fase di creazione non posso aggiungere etichette/labels alla issue come suggerisci in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo, mi sa che tocca farlo ai maintainers

**Comment by primes2h** [comment]
> @primes2h in fase di creazione non posso aggiungere etichette/labels alla issue come suggerisci in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo, mi sa che tocca farlo ai maintainers

Hai ragione, metto una nota.

**Comment by primes2h** [comment]
> > @primes2h in fase di creazione non posso aggiungere etichette/labels alla issue come suggerisci in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo, mi sa che tocca farlo ai maintainers
> 
> Hai ragione, metto una nota.

@SimoRubi 
Ho riorganizzato tutta la pagina, dimmi se va bene e ti sembra più chiaro così.
https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo

**Comment by SimoRubi** [comment]
Benissimo grazie :)
Dici che ha senso aggiornare anche il template per le nuove issue?
Attualmente è:
![image](https://user-images.githubusercontent.com/32064796/75146750-ff67e380-56fb-11ea-8d32-28788c51d349.png)
ad esempio si potrebbe aggiungere l'elenco delle versioni come suggerito in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo

**Comment by primes2h** [comment]
> Benissimo grazie :)
> Dici che ha senso aggiornare anche il template per le nuove issue?
> Attualmente è:
> ![image](https://user-images.githubusercontent.com/32064796/75146750-ff67e380-56fb-11ea-8d32-28788c51d349.png)
> ad esempio si potrebbe aggiungere l'elenco delle versioni come suggerito in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo

Intendi il template per tutte le nuove issue aperte?
Non saprei, considera che le issue di tracciabilità sono di tipo particolare. Vengono aperte quando è già pronta una PR per una specifica versione e servono per tenere allineate le altre versioni.

Vediamo cosa dicono anche gli altri @OCA/local-italy-developers

**Comment by SimoRubi** [comment]
ah pensavo si potessero aprire anche quando non c'è una PR..
Tipo quando trovo un problema in v10 e magari non so/posso correggerlo, apro la issue dicendo che la v10 è coinvolta ma senza aggiungere la PR perché non esiste.

**Comment by primes2h** [comment]
> ah pensavo si potessero aprire anche quando non c'è una PR..

Infatti è proprio così, uno può aprire anche una issue generica per quello che a suo parere è un bug, magari ha solo bisogno di un chiarimento o magari è una domanda. Ci sono diverse issue di questo tipo aperte.

> Tipo quando trovo un problema in v10 e magari non so/posso correggerlo, apro la issue dicendo che la v10 è coinvolta ma senza aggiungere la PR perché non esiste.

Esatto, non so se sia il caso di gestire questo tipo di issue generiche con il modello per le issue di tracking. Vediamo cosa dicono anche gli altri.

**Comment by eLBati** [comment]
> Esatto, non so se sia il caso di gestire questo tipo di issue generiche con il modello per le issue di tracking. Vediamo cosa dicono anche gli altri

Io direi di sì, perlomeno il template era nato generico.

> ad esempio si potrebbe aggiungere l'elenco delle versioni come suggerito in https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo

Personalmente lascerei il template così com'è: il modello che sta su https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo è pensato per le issue con PR
