### ISSUE TITLE
[10.0] l10n_it_fatturapa_out_wt

### ISSUE THREAD

**Issue by borgogelli** [OCA/l10n-italy#1656]
Le specifiche ci dicono che Il tag **TipoRitenuta** può essere compilato con i valori **RT01** (ritenuta persone fisiche) o **RT02** (ritenuta persone giuridiche).
Analizando il codice seguente
https://github.com/OCA/l10n-italy/blob/c66dfae6c864ce4acf8f4a74deac3617b39eb06c/l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py#L33
sembrerebbe che il modulo valorizzi il tag con riferimento al cessionario/committente .
Mentre in molti mi suggeriscono che andrebbe compilato con riferimento al cedente/prestatore.
Cosa ne pensate ?

**Comment by borgogelli** [comment]
@sergiocorato @eLBati @robyf70 si accettano suggerimenti

**Comment by sergiocorato** [comment]
`invoice.partner_id` è il cessionario

**Comment by borgogelli** [comment]
@sherpya si accettano suggerimenti

> `invoice.partner_id` è il cessionario

Appunto, in molti mi fanno notare che il dato dovrebbe essere riferito invece al cedente/prestatore

**Comment by borgogelli** [comment]
@sherpya si accettano suggerimenti

> `invoice.partner_id` è il cessionario

Appunto, in molti mi fanno notare che il dato dovrebbe essere riferito invece al cedente/prestatore

**Comment by sergiocorato** [comment]
> Mentre in molti mi suggeriscono che andrebbe compilato con riferimento al cessionario/committente.

Mi pare che qui sia scritto il contrario. In ogni caso direi che non è corretto come fa adesso, vuoi caricare una PR?

**Comment by borgogelli** [comment]
> > Mentre in molti mi suggeriscono che andrebbe compilato con riferimento al cessionario/committente.
> 
> Mi pare che qui sia scritto il contrario. In ogni caso direi che non è corretto come fa adesso, vuoi caricare una PR?

Hai ragione, ho corretto. Per la PR ci penso io, volevo però prima una conferma da qualcuno che la pensa come me in merito all'interpretazione delle specifiche.

**Comment by borgogelli** [comment]
Ho creato una PR associata al branch 12.0. @sergiocorato come posso riportarlo sul branch 10.0 ?

**Comment by sergiocorato** [comment]
con cherry-pick del singolo commit fatto sulla 12.0

**Comment by eLBati** [comment]
@borgogelli grazie della segnalazione.

Se vuoi fare la PR, dovrebbe essere sufficiente questa modifica:
```
diff --git a/l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py b/l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py
index a4e003f0b..7d591c602 100644
--- a/l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py
+++ b/l10n_it_fatturapa_out_wt/wizard/wizard_export_fatturapa.py
@@ -30,7 +30,7 @@ class WizardExportFatturapa(models.TransientModel):
                                 % wt_line.withholding_tax_id.name)
             body.DatiGenerali.DatiGeneraliDocumento.DatiRitenuta\
                 = DatiRitenutaType(
-                    TipoRitenuta="RT02" if invoice.partner_id.is_company
+                    TipoRitenuta="RT02" if invoice.company_id.partner_id.is_company
                     else "RT01",  # RT02 persona giuridica
                     ImportoRitenuta='%.2f' % float_round(wt_line.tax, 2),
                     AliquotaRitenuta='%.2f' % float_round(
```

Dopo averla creata, aggiungi il link alla PR nella descrizione di questa issue per favore
