### ISSUE TITLE
FE - trasmissione via PEC

### ISSUE THREAD

**Issue by gigidn** [OCA/l10n-italy#1662]
Scrivo qui come traccia di quanto detto su telegram.
Le mail ricevute da odoo vengono storate direttamente nella tabella mail.thread come messaggio row comprensivo dei suoi allegati.
Questo comportamento ha impatto sul modulo di ricezione della FE che sfrutta il sottosistema di ricezione delle mail. Sfortunatamente quello che doveva essere un file xml leggero nella pratica non lo e' vista la barbara prassi di molti che allegano allo stesso il pdf ed altra roba.
Essendo abbastanza complicato l'intervento sul core di odoo (dove il problema andrebbe risolto visto che non ha impatto solo sulla FE) e considerato che dopo l'interpretazione la FE viene conservata come attachment una possibile soluzione sarebbe la cancellazione del messaggio pec per evitare che la tabella mail_thread cresca a dismisura.
Cosa ne pensate?

**Comment by eLBati** [comment]
La tabella `mail_thread` non esiste, essendo un `AbstractModel`

**Comment by gigidn** [comment]
@eLBati ops ... grazie per la segnalazione, ho scritto mail.thread ma intendevo mail.message.

Per meglio chiarire la issue, questo e' quello che ho su un db v10 con installato il modulo di fatturazione ed invio via pec.

 mail_message                                              | 11 GB      | 4995 MB
 mail_tracking_value                                       | 3685 MB    | 950 MB
 account_move_line                                         | 2581 MB    | 1956 MB
 sale_order_line                                           | 1056 MB    | 169 MB

Valori ordinati per size ... e' evidente come la tabella mail_message sia fuori controllo.
Visto che il problema su questa tabella lo riscontro su questo db che a differenza di altri ha la gestione delle fatture in uscita via pec ipotizzavo che il problema fosse legato a quello.
Se non fosse quello il problema ci sta da qualche altra parte in odoo .. quella tabella e' troppo dissimile da tutte le altre e fa un casino in fase di ottimizzazione del carico su postgres.

**Comment by eLBati** [comment]
@gigidn ok, sì, potrebbe essere piena di fatture elettroniche. In tal caso i messaggi con fatture elettroniche penso si possano eliminare, essendo esse comunque salvate in `fatturapa.attachment.out` e `fatturapa.attachment.in`

**Comment by eLBati** [comment]
@gigidn https://github.com/OCA/server-tools/tree/12.0/autovacuum_message_attachment questo modulo potrebbe essere una soluzione
