### ISSUE TITLE
[IMP] account_vat_period_end_statement: permettere di poter scegliere l'anno che compare nel footer

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#1665]
La stampa della liquidazione iva non permette di poter scegliere l'anno che compare nel footer.

Versioni coinvolte:

 - [x] v10: https://github.com/OCA/l10n-italy/pull/1666
- ~~[ ] v11: ?~~
- ~~[ ] v12: ?~~

Passi per riprodurre:
provare a stampare una liquidazione iva

Comportamento osservato:
nel footer di ciascuna pagina della stampa compare la scritta `Pag: current_year / n_page` es:`Pag: 2020 / 1`.

Comportamento atteso:
poter scegliere nella liquidazione iva, tab `Print Options`, l'anno che si vuole far comparire nel footer come segue: `Pag: year_footer / n_page`.

**Comment by eLBati** [comment]
Mi pare che la 12 non ne soffra, giusto?

**Comment by tafaRU** [comment]
Giusto, anche la 11.

12.0: https://github.com/OCA/l10n-italy/blob/baaa1dfae957b7faaf4b2d9e7ca530727c92b708/account_vat_period_end_statement/views/account_view.xml#L128
11.0: https://github.com/OCA/l10n-italy/blob/18f1bbcdc17686f9827342b62a7c583f0009dce0/account_vat_period_end_statement/views/account_view.xml#L115
