### ISSUE TITLE
fatturapa_pec - Fatture PA firmate mandano in tilt server in ingresso

### ISSUE THREAD

**Issue by PatosMarco** [OCA/l10n-italy#1668]
**Versioni coinvolte:** 

-  [x] 10.0 #1683
-  [ ] 11.0 ?
-  [X] 12.0 https://github.com/OCA/l10n-italy/pull/1820

**Passi per riprodurre:**
1 creata fattura per cliente PA
2 generata la fattura elettronica
3 scaricata la fattura elettronica in locale
4 firmata la fattura elettronica
5 upload su Odoo della fattura elettronica firmata (estensione .p7m)
6 invio della fattura elettronica allo SDI
7 errore: nessun server PEC in ingresso trovato alle successive operazioni di invio 

**Comportamento osservato:**
Il modulo non riesce a leggere le prime mail di notifica, le consuete che si ricevono all'invio di un file XML. Non riuscendo a leggerle il modulo inizia ad accumulare errori che vengono registrati su fetchmail.pec.max.retry. Una volta raggiunto il numero massimo di errori, il server di posta in ingresso **torna nello stato non confermato** causando il blocco dei meccanismi di ricezione ed invio di tutte le fatture elettroniche.

**Nello specifico**

Aggiungendo alcuni log nella classe MailThread del modulo l10n_it_fatturapa_pec ho notato che il server in ingresso non gestisce i file XML firmati (estensione p7m). Nello specifico, abbiamo un messaggio di consegna con oggetto _CONSEGNA: IT06363391001_ynFj2.xml_ mentre su odoo il nome file è **IT06363391001_ynFj2.xml.p7m**

Non provenendo da @pec.fatturapa.it rientra nella funzione find_attachment_by_subject() che, però, non riesce a risalire all'attach in quanto subject e datas_fname sono differenti.

Questi sono i log:

> 2020-02-19 12:04:39,051 976 ERROR dev odoo.addons.l10n_it_fatturapa_pec.models.mail_thread: message_route() - reply:
> 2020-02-19 12:04:39,052 976 ERROR dev odoo.addons.l10n_it_fatturapa_pec.models.mail_thread: message_route() - from: Posta Certificata Sogei <posta-certificata@pcert.sogei.it>
> 2020-02-19 12:04:39,052 976 ERROR dev odoo.addons.l10n_it_fatturapa_pec.models.mail_thread: message_route() - path: <posta-certificata@pcert.sogei.it>
> 2020-02-19 12:04:39,052 976 ERROR dev odoo.addons.l10n_it_fatturapa_pec.models.mail_thread: find_attachment_by_subject() - SUBJECT: CONSEGNA: IT06363391001_ynFj2.xml
> 2020-02-19 12:04:39,052 976 ERROR dev odoo.addons.l10n_it_fatturapa_pec.models.mail_thread: find_attachment_by_subject() - att_name: IT06363391001_ynFj2.xml
> 2020-02-19 12:04:39,069 976 ERROR dev odoo.addons.l10n_it_fatturapa_pec.models.mail_thread: find_attachment_by_subject() - fatturapa_attachment_out: fatturapa.attachment.out()
> 2020-02-19 12:04:39,070 976 INFO dev odoo.addons.l10n_it_fatturapa_pec.models.fetchmail: Failure when fetching emails using imap server pec fatturazione in arrivo.
> Traceback (most recent call last):
>   File "/opt/odoo/buildout/parts/l10n-italy/l10n_it_fatturapa_pec/models/fetchmail.py", line 65, in fetch_mail
>     strip_attachments=(not server.attach)
>   File "/opt/odoo/buildout/parts/odoo/addons/mail/models/mail_thread.py", line 1283, in message_process
>     routes = self.message_route(msg_txt, msg, model, thread_id, custom_values)
>   File "/opt/odoo/buildout/parts/l10n-italy/l10n_it_fatturapa_pec/models/mail_thread.py", line 83, in message_route
>     fetchmail_server.user
> UserError: (u'<p>Il messaggio PEC con Message-Id <opec292.20200219103230.08786.8229.1.2472.12@pcert.sogei.it> \xe8 stato letto ma non elaborato, non \xe8 relativo a una e-fattura.</p><p>Controllare la casella PEC pec fatturazione in arrivo: server imaps.pec.aruba.it, utente fatturazione@pec.it</p>', '')

**Comportamento atteso:**
Fare in modo che il modulo riesca a leggere i messaggi di notifica così da evitare problemi al server PEC. I messaggi di notifica, non provenendo da @pec.fatturapa.it, rientrano nella funzione find_attachment_by_subject() che a questo punto dovrebbe ragionare in modo differente: **se non riesce a risalire all'attach in quanto subject e datas_fname sono differenti verifica se la fattura presenta scissione dei pagamenti e fa avvenire il matching con il campo name di fatturapa_attachment_out piuttosto che con datas_fname.**

**Video/Screenshot (opzionale):**
![Schermata 2020-02-19 alle 13 16 18](https://user-images.githubusercontent.com/60786718/75628043-a73a5100-5bd5-11ea-98f3-2dda0a941679.png)

**Comment by eLBati** [comment]
@PatosMarco grazie.

La modifica che proponi mi sembra corretta.
Hai voglia di fare una PR? (vedi https://www.odoo-italia.org/documentazione/12.0/sviluppo/come_contribuire.html se servisse)

**Comment by eLBati** [comment]
@frdmar riesci a fare la PR anche per v12?

Grazie

**Comment by eLBati** [comment]
Ecco per la 12 https://github.com/OCA/l10n-italy/pull/1820

**Comment by primes2h** [comment]
Chiudo come da [linee guida](https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#chiusura-issue).
Se qualcuno ha intenzione di fare la PR per la 11.0 la riapra pure.
