### ISSUE TITLE
fatturapa_pec non riconosce lo stato Accettato EC01 delle fatture PA

### ISSUE THREAD

**Issue by PatosMarco** [OCA/l10n-italy#1669]
**Versioni coinvolte:**

 - [X] 10.0 https://github.com/OCA/l10n-italy/pull/1680
 - [ ] 11.0
 - [X] 12.0 #1821

**Passi per riprodurre:**
1 creata fattura per cliente PA
2 generata la fattura elettronica
3 scaricata la fattura elettronica in locale
4 firmata la fattura elettronica
5 upload su Odoo della fattura elettronica firmata (estensione .p7m)
6 invio della fattura elettronica allo SDI
7 la fattura elettronica passa i controlli dello SDI
8 la fattura viene accettata definitivamente dalla PA

**Comportamento osservato:**
Nel momento in cui arriva la notifica che la fattura elettronica è stata accettata dall'ente pubblico, , il sistema riporta correttamente nel campo last_sdi_response il codice EC01 (utilizzato per notificare proprio che la PA ha accettato la fattura) solo che lo stato della fattura elettronica rimane su Consegnato.

**Comportamento atteso:**
Ogni qual volta una fattura elettronica presenta nel campo last_sdi_response il codice EC01, lo stato della fattura elettronica deve spostarsi su Accettato. Nello specifico, dovrebbe bastare intervenire sulla seguente porzione di codice:

> if esito is not None:
>                             if esito.text == 'EC01':
>                                 state = 'validated'
>                             elif esito.text == 'EC02':
>                                 state = 'rejected'

**Cambiando validated in accepted**

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
@PatosMarco grazie.
Anche per questa, hai voglia di fare una PR?

**Comment by frdmar** [comment]
Eccola #1680 

Grazie!

**Comment by PatosMarco** [comment]
> @PatosMarco grazie.
> Anche per questa, hai voglia di fare una PR?

Fatta quest'oggi insieme a @frdmar . Te l'ha linkata più sotto

**Comment by primes2h** [comment]
C'è qualcuno che ci sta lavorando per la v.12.0?
In caso contrario posso farla io.

**Comment by eLBati** [comment]
@primes2h io no. Secondo me puoi procedere

**Comment by primes2h** [comment]
> @primes2h io no. Secondo me puoi procedere

Ok, grazie. Aperta la #1821

**Comment by primes2h** [comment]
Chiudo come da [linee guida](https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#chiusura-issue).
Se qualcuno ha intenzione di fare la PR per la 11.0 la riapra pure.
