### ISSUE TITLE
[8.0] [l10n_it_ddt] emissione DDT tra varie stock location interne/magazzini 

### ISSUE THREAD

**Issue by As400it** [OCA/l10n-italy#167]
l'emissione di DDT dovrebbe essere consentita anche per trasferimenti interni alla società. 
Nello specifico se l'azienda ha più di un magazzino ubicato in siti diversi dovrei avere la possibilità di emettere ddt che accompagnano la merce, in modo particolare se si usano corrieri esterni all'azienda. 
Allo stato attuale se rendo visibile picking_type_id viene ignorato in fase di "put in pack" . 

Grazie 
Marco C.

**Comment by eLBati** [comment]
Se hai magazzini in siti diversi dovresti creare un warehouse per ognuno di essi.

Esempio
 - Creo un nuovo warehouse 'magazzino2' (con il suo indirizzo). Il sistema creerà le sue locations base
 - Faccio un ordine di consegna da 'stock' a 'magazzino2'
 - Creo il DDT senza problemi
