### ISSUE TITLE
Libro giornale: anno su footer

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#1672]
Versioni coinvolte:

- [x] 10.0 https://github.com/OCA/l10n-italy/pull/1673
- [ ] 11.0
- [ ] ~~12.0~~

Passi per riprodurre:
Eseguire la stampa del libro giornale
Comportamento osservato:
Nel footer, insieme al numero della pagina viene riportato l'anno in cui viene eseguita la stampa.

Comportamento atteso:
Se nel 2020 viene stampato il libro giornale dell'anno 2019, è bene riportare insieme al nr di pagina l'anno di competenza del libro giornale. In questo caso il 2019.

Video/Screenshot (opzionale):

**Comment by tafaRU** [comment]
@alessandrocamilli ho aggiunto il link alla tua PR per la 10.0.

**Comment by eLBati** [comment]
Sulla 12 la funzionalità c'è già

**Comment by primes2h** [comment]
Qualcuno ha intenzione di aprire la PR per la 11.0?
Altrimenti la chiudo con `needs fixing` e `11.0`.

**Comment by tafaRU** [comment]
@primes2h per quanto mi riguarda puoi procedere. Grazie!
