### ISSUE TITLE
Posizione fiscale ignorata sull'import fatture elettroniche

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1678]
**Versioni coinvolte:**
- [ ] 11.0
- [ ] 12.0

**Passi per riprodurre:**
1. si crea un prodotto con imposta 22%;
2. si crea una posizione fiscale che trasforma l'imposta 22% a 22%RC;
3. si imposta su un fornitore la posizione fiscale di cui al punto 2, e gli si imposta il prodotto di cui al punto 1 come prodotto di default per l'import delle FE.
4. si importa una fattura elettronica con livello di dettaglio massimo, relativa al fornitore di cui al punto 3, con posizione fiscale di cui al punto 1 e prodotto di cui al punto 2.

**Comportamento osservato:**
La posizione fiscale viene ignorata (nel caso in questione, l'imposta del prodotto viene impostata al 22% anziché 22%RC).

**Comportamento atteso:**
La posizione fiscale del partner viene coinvolta nel calcolo delle imposte (nel caso in questione, l'imposta del prodotto viene impostata al 22%RC).

**Comment by eLBati** [comment]
@SilvioGregorini stai usando https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_fatturapa_in_rc ?

**Comment by alessandrocamilli** [comment]
@eLBati si, usando il modulo in questione, la problematica viene riscontrata quando si va a specificare un prodotto nell'anagrafica del fornitore da usare nell'import dell'e-fattura.
