### ISSUE TITLE
Comunicazione dati iva: esterometro

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1685]
**Versioni coinvolte:**
- [x] 10.0
- [ ] 11.0 (manca il modulo  l10n_it_invoices_data_communication)
- [x] 12.0 #1677 

**Comportamento osservato:**
L’Esterometro prevede solo l'opzione per non includere le fatture elettroniche.
Nei casi di fornitori con regime forfettario o comunque non soggetti a fatturazione elettronica, occorre ricordarsi di impostare a true il relativo flag per evitare che tale fattura venga inclusa nell'esterometro.

**Comportamento atteso:**
Presenza di un'opzione che permetta di estrarre tutte le fatture estere (partner che non hanno nazionalità italiana impostata in anagrafica).

**Comment by primes2h** [comment]
Ho aggiunto la v.10 dato che il modulo è presente. 
Nella 11.0 invece manca, l'ho segnalato.

**Comment by eLBati** [comment]
Si può chiudere?
