### ISSUE TITLE
[l10n_it_account_stamp] Creazione righe registrazione contabile

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1694]
Versioni coinvolte:
- [ ] 10.0 (da verificare)
- [x] 11.0 #1687 
- [ ] 12.0 ~#1896~ #~1933~ #2319
- [ ] 14.0 (da verificare)

**Passi per riprodurre:**
Creare una fattura assoggetta ad imposta di bollo, senza applicare la rivalsa in fattura.

**Comportamento osservato:**
Alla validazione della fattura, Odoo scrive in dare e avere l'importo del bollo all'interno della registrazione collegata.

**Comportamento atteso:**
Permettere all'utente di decidere se tali righe debbano essere riportate nella registrazione.

**Comment by eLBati** [comment]
@sergiocorato che ne pensi?

**Comment by matteoopenf** [comment]
Buongiorno ho creato il porting anche alla versione 12 dove abbiamo rilevato il medesimo problema https://github.com/OCA/l10n-italy/pull/1896

**Comment by matteoopenf** [comment]
> Buongiorno ho creato il porting anche alla versione 12 dove abbiamo rilevato il medesimo problema #1896 chiusa in favore di #1933
Ho rifatto al pr per la 12 che essendo rimasta molto indietro aveva svariati conflitti

https://github.com/OCA/l10n-italy/pull/2319

**Comment by TheMule71** [comment]
Ho aggiunto il task per la 14.0 (da verificare)
