### ISSUE TITLE
[l10n_it_withholding_tax] Importo pagamento fattura con ritenuta d'acconto

### ISSUE THREAD

**Issue by SilvioGregorini** [OCA/l10n-italy#1695]
**Versioni coinvolte:**
- [ ] 10.0 da verificare
- [ ] 11.0 da verificare
- [ ] 12.0 #1671 
- [x] 14.0 #2572
- [x] 16.0 #3404

**Passi per riprodurre:**
Creare una fattura con una riga di ritenuta d'acconto, validarla e creare un pagamento dal pulsante "Registra pagamento" dalla testata della fattura.

**Comportamento osservato:**
L'importo da pagare preso di default è il totale della fattura.

**Comportamento atteso:**
L'importo da pagare preso di default è il totale netto della fattura.

**Video/Screenshot (opzionale):**
Esempio di comportamento attuale: fattura da 610€ con ritenuta d'acconto da 110€; l'importo di default del pagamento è di 610€ anziché 500€.
![image](https://user-images.githubusercontent.com/32639900/76872415-ad366000-686c-11ea-90d0-f6dfde383f15.png)

**Comment by SirTakobi** [comment]
@OCA/local-italy-maintainers che dite si può chiudere?
