### ISSUE TITLE
Dichiarazione Intrastat - acquisti: partner intra emette fatture in euro non viene calcolato "ammontare delle operazioni in valuta"

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/l10n-italy#1698]
Versioni coinvolte:
- [x] 11.0 da verificare (risolta per supporto terminato)
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/3278 (risolta per supporto terminato)
- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/3279
- [ ] 16.0

Passi per riprodurre:
se ricevo da un partner estero una fattura acquisti in euro in dichiarazione intrastat non viene valorizzato il campo ammontare delle operazioni in valuta che è obbligatorio per i paesi non euro es svezia. Se la fattura è in corone allora il calcolo viene fatto correttamente.  

Comportamento osservato:
nel codice non c'è nulla che provvede a fare questo calcolo . credo che una soluzione potrebbe essere che se la fattura ha currency id = a currency id della company reperire il tasso di cambio dalla nazione del partner (nazione già presente nelle righe intra) 

Comportamento atteso:

Video/Screenshot (opzionale):

**Comment by patrickt-oforce** [comment]
per la v 12.0 avevo aperto la PR #3278
