### ISSUE TITLE
[10.0] move python dependencies out of .travis.yml

### ISSUE THREAD

**Issue by sbidoul** [OCA/l10n-italy#1700]
Hi,

I noticed this project installs [python dependencies in `.travis.yml`](https://github.com/OCA/l10n-italy/blob/7bc03a13543eb0e77bd38d7d0bd30882ba8dda8b/.travis.yml#L28-L32).

I'd encourage you to move them to addon manifests.

When that is done, published wheels will be correct, and with `MQT_DEP=PIP` in `.travis.yml`, installation for test will be correct too.

When a constraint absolutely needs to be made on versions, it can be done in setup py ([as it is done for PyXB](https://github.com/OCA/l10n-italy/blob/7bc03a13543eb0e77bd38d7d0bd30882ba8dda8b/setup/l10n_it_fatturapa/setup.py#L8)). Also, please do avoid pinning dependencies when not strictly necessary (or pin a minimum version, or if nothing else works a maximum version). Strict pinning prevent your modules to work with the latest versions (including security updates) and makes it difficult to mix your modules in projects that may require more recent versions of the same dependencies.

- [x] 10.0: https://github.com/OCA/l10n-italy/pull/1702
- [ ] 11.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1701

**Comment by eLBati** [comment]
@sbidoul hi, fixing with https://github.com/OCA/l10n-italy/pull/1702 and https://github.com/OCA/l10n-italy/pull/1701
Thanks

About pyxb, we know the implications but the e-invoice modules  works with that version only.
We hope to get rid of pyxb in the future actually.
