### ISSUE TITLE
Partner per corrispettivi in ambiente multicompany

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#1712]
Versioni coinvolte:

- [ ] 11.0
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2523

Passi per riprodurre:
Creo una nuova company.
Creo un utente che può entrare solo in questa nuova company.
Con un utente abilitato alla fatturazione, vado a creare una nuova ricevuta, ricevo l'errore di sicurezza per accedere all'utente x.

Comportamento osservato:
Il problema è che viene sempre proposto come partner per il corrispettivo quello dell'utente pubblico, mentre come addetto alle vendite viene messo Odoobot che punta alla company principale(alla quale non può accedere l'utente che sta caricando la ricevuta).

Comportamento atteso:
Alla creazione di una nuova ricevuta, dovrebbe essere proposto il partner dove si è indicato "Usa per ricevute".
Video/Screenshot (opzionale):

**Comment by matteoopenf** [comment]
@alessandrocamilli  puoi aggiornare che il problema c'è anche per 11.0?

**Comment by matteoopenf** [comment]
@tafaRU  qui è stata aggiornata la issue. 
Dimmi pure se occorre altro.
Grazie ancora

**Comment by tobesmartcs** [comment]
Esiste il fix per la versione 12.0?

**Comment by eLBati** [comment]
@tobesmartcs c'è una proposta su https://github.com/OCA/l10n-italy/pull/1711 ma con punti non risolti

**Comment by TheMule71** [comment]
C'è anche nella 14.0?

**Comment by SimoRubi** [comment]
> C'è anche nella 14.0?

Il modulo `l10n_it_corrispettivi` non esiste in v14 e non mi pare ci sia nemmeno una PR di migrazione

**Comment by SimoRubi** [comment]
@alessandrocamilli ora che https://github.com/OCA/l10n-italy/pull/2523 è mergiata, questo problema dovrebbe essere risolto. Puoi verificare ed eventualmente chiudere questa problematica?
