### ISSUE TITLE
[RFC] Proposta nuovo modulo: gestione turni per associazioni di volontariato

### ISSUE THREAD

**Issue by mymage** [OCA/l10n-italy#1725]
Versioni coinvolte: 12

**Obiettivo**
Realizzare un’applicazione per la gestione dei turni di organizzazioni quali Protezione Civile, Croce Rossa, che necessitano di coprire attività come presidio (es. sala operativa), servizio (es. pulizie), trasporto (es. ambulanze) utilizzando persone e risorse, garantendo alcune regole come la disponibilità 24/7, evitare doppie assegnazioni, rispetto turni di riposo, blocco dei mezzi per manutenzione.

**Funzionalità**
- programmazione
  - calendari di disponibilità (persone e attrezzature)
  - gestione candidature e l’indisponibilità
  - rispetto normative turnistica
  - gestione dei ruoli (specializzazioni)
- consuntivazione
- facile interfaccia di gestione
- (versione mobile per alcune funzioni)

**Contatti**
Chi volesse prendere contatti scriva a odoo@pnlug.it

**Comment by salusutis** [comment]
Vorrei poter dare un contributo: 
- analisi dell E/R
- collaborazione nell'elaborazione delle viste
-----------------------------------
studio da due mesi il sistema con cui si sviluppa ma vorrei poter dare un contributo

**Comment by eLBati** [comment]
Forse il repository più adatto è
https://github.com/OCA/vertical-ngo

Era stato popolato principalmente da Camptocamp con moduli che avevamo fatto per la Croce Rossa se non sbaglio.
Al momento i moduli sono rimasti alla 8.

**Comment by sergiocorato** [comment]
Bella iniziativa! Si potrebbe provare a proporlo su https://github.com/OCA/hr, quello più dedicato sarebbe https://github.com/OCA/vertical-ngo che è abbandonato

**Comment by tbuonanno** [comment]
Oltre ad essere un appartenente alla famiglia Odoo sono anche un responsabile di una associazione appartenente alle Misericordie d'Italia. se posso essere di aiuto nella parte funzionale, ben volentieri. P.S. Da prendere in considerazione gli aspetti legati al covid molto assimilati al mondo HR aziendale (es. assegnazione dotazioni DPI,...)

**Comment by marcelofrare** [comment]
> Vorrei poter dare un contributo:
> 
>     * analisi dell E/R
> 
>     * collaborazione nell'elaborazione delle viste
> 
>     * o dei modelli
> 
> 
> studio da due mesi il sistema con cui si sviluppa ma vorrei poter dare un contributo

Ciao, visto che hai già avuto modo di studiare il caso, ti propongo di confrontare la tua analisi con la nostra in modo da elaborare una comprensiva dei vari casi.
Se sei d'accordo mandami una tua email a odoo@pnlug.it in modo che ti giro la ns. di analisi

**Comment by salusutis** [comment]
Ciao, il riferimento allo studio è sullo sviluppo di ODOO  non sul caso
specifico (ho approfittato di questi due mesi), ma ho una certa esperienza
sui database e lo sviluppo dei modelli e delle relazioni. Sul progetto
specifico dovrei poter iniziare a valutare le problematiche insieme a voi.

Il giorno lun 4 mag 2020 alle ore 09:51 Marcelo Frare <
notifications@github.com> ha scritto:

**Comment by SerM11** [comment]
Ciao a tutti, 
Mi piacerebbe contribuire alla parte funzionale, da anni sto cercando di informatizzare l'associazione per cui faccio servizio.

**Comment by mymage** [comment]
@SerM11 
> Ciao a tutti,
> Mi piacerebbe contribuire alla parte funzionale, da anni sto cercando di informatizzare l'associazione per cui faccio servizio.

Ciao, se non l'hai fatto manda un messaggio a odoo@pnlug.it così ti aggiorniamo su quanto fatto.
