### ISSUE TITLE
l10n_it_account_stamp: calcolo mancato di tax_stamp

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1727]
Versioni coinvolte:

 - [ ] 10.0
 - [ ] 11.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1728

Passi per riprodurre:

 - Creare un prodotto impostandolo "fuori campo IVA"
 - Configurare il prodotto "Imposta di bollo 2 euro" in modo che venga applicato a "fuori campo IVA"
 - Creare una fattura, aggiungere una riga selezionando il nuovo prodotto create e modificare il prezzo unitario impostando 100

Comportamento osservato:

Il bollo non viene applicato

Comportamento atteso:

Il bollo viene applicato

**Comment by protontrigg3r** [comment]
12.0 appena installato da sorgenti non mostra nemmeno il flag nella scheda "Altre informazioni" della fattura:

![Schermata da 2020-06-24 08-19-24](https://user-images.githubusercontent.com/38140509/85518480-912b2300-b600-11ea-9fab-e0478e14c4a2.png)
![Schermata da 2020-06-24 09-16-59](https://user-images.githubusercontent.com/38140509/85518494-94beaa00-b600-11ea-8734-d224e54bf82e.png)
![Schermata da 2020-06-24 09-17-18](https://user-images.githubusercontent.com/38140509/85518500-96886d80-b600-11ea-8c6a-57947e40d58b.png)

**Comment by eLBati** [comment]
@protontrigg3r infatti non è previsto che venga visualizzato.

Per abilitare la modalità manuale, vedi README

**Comment by protontrigg3r** [comment]
Ok. Negli screenshot in cui mi sono imbattuto era visibile e ho ipotizzato lo fosse sempre.

La documentazione parla anche di un _pulsante "Aggiungi riga bollo"_: anche questo non c'è?

**Comment by eLBati** [comment]
Compare se il bollo non c'è già e se la fattura è bozza:
https://github.com/OCA/l10n-italy/blob/f66a289f451d7bbb2a7f5c491479479fa9db33d0/l10n_it_account_stamp/views/invoice_view.xml#L28-L29

**Comment by protontrigg3r** [comment]
Grazie Lorenzo. Questo modulo sembra poter andar bene anche per  i “prodotti Covid-19” che sono esenti IVA art. 124 del DL n. 34/2020 fino al 31/12/2020.
