### ISSUE TITLE
Dichiarazione intrastat: Errore export sezione 4 - Rettifica servizi

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#1729]
Versioni coinvolte:

- [x] 10.0 #1722 
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/1731

Passi per riprodurre:
Creo una nota credito che ha un servizio intrastat, nella dichiarazione avrò una riga in corrispondenza della sezione Rettifica servizi - sezione 4.
All'interno vado a valorizzare, in quanto obbligatorio, il campo "Progressivo da rettificare".

Comportamento osservato:
Quando vado ad esportare il file ricevo l'errore:

>   File "/opt/odoo/community_addons/bundles/l10n-italy/l10n_it_intrastat_statement/models/intrastat_statement_sale_section.py", line 445, in _prepare_export_line
>     self.progressive_to_modify_id and
> AttributeError: 'account.intrastat.statement.sale.section4' object has no attribute 'progressive_to_modify_id'

Comportamento atteso:
Che non venga segnalato l'errore, che il campo progressive_to_modify_id vada a popolare correttamente il file da esportare
Video/Screenshot (opzionale):

**Comment by tafaRU** [comment]
Ho aggiunto anche la versione 10.0 tra le versioni coinvolte. Vedi https://github.com/OCA/l10n-italy/pull/1718
