### ISSUE TITLE
[FIX] l10n_it_fatturapa_pec: Rollback unwanted DB changes in case of exception

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1745]
**Versioni coinvolte**
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1732
 - [x] v11: ? (risolta per termine supporto)
 - [x] v12: (risolta per termine supporto)
 - [ ] v14:
 - [ ] v16 ?

Suppongo questo succeda in tutte le versioni perché il rollback della transazione viene tipicamente fatto quando l'eccezione è propagata mentre durante l'import delle mail noi blocchiamo la propagazione.

**Passi per riprodurre**
Durante l'import di una fattura elettronica con fetchmail, viene sollevata un'eccezione che compromette l'integrità del DB all'interno della transazione.

**Comportamento osservato**
Il DB rimane compromesso e non è più possibile fare UPDATE all'interno della transazione (ad esempio per salvare il messaggio di errore).

**Comportamento atteso**
Il DB è utilizzabile anche dopo l'errore

**Comment by SirTakobi** [comment]
La modifica non è presente in `12.0` né in `14.0`, @OCA/local-italy-maintainers qualcuno può riaprire la issue?
