### ISSUE TITLE
[10.0][12.0][Ricevute Bancarie] Registrazione incasso Ri.Ba. con conto sbagliato

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#1753]
Versioni coinvolte:
10.0 12.0

Comportamento osservato:
Leggendo il buon vecchio documento https://docs.google.com/document/d/1xCqeTcY6CF-Dgk_Avthhy7iwg_aG86WzNv3E_HHQkt4/edit si evince che la registrazione dell'incasso debba considerare come conti **"effetti SBF"** e **"Banca conto ricevute bancarie"**
Il primo dovrebbe essere **accreditation_account_id** ed il secondo **bank_account_id** entrambi presi dalla configurazione.
In realtà osservando una registrazione e leggendo il codice in riba.py (https://github.com/OCA/l10n-italy/blob/52392ebf40934b1dbe5682ada236201beeffdde4/l10n_it_ricevute_bancarie/models/riba.py#L377) la registrazione utilizza **acceptance_account_id** e **accreditation_account_id**

Altra cosa che mi porta dei dubbi è la presenza del wizard_accreditation.py che mi sembra non sia accessibile, forse ce lo portiamo dietro dal 2012, ma richiama la registrazione esattamente come dovrebbe essere (https://github.com/OCA/l10n-italy/blob/52392ebf40934b1dbe5682ada236201beeffdde4/l10n_it_ricevute_bancarie/wizard/wizard_accreditation.py#L95)

Chiedo riscontro e nel caso i miei dubbi fossero confermati, eliminerei il wizard_accreditation correggendo il metodo in riba.py

**Comment by eLBati** [comment]
> la registrazione utilizza acceptance_account_id e accreditation_account_id

è corretto: `acceptance_account_id` è `effetti SBF` e `accreditation_account_id` è `Banca conto ricevute bancarie`

> Altra cosa che mi porta dei dubbi è la presenza del wizard_accreditation.py che mi sembra non sia accessibile

Se non è accessibile forse è un errore di porting: dovrebbe ricomparire. Si dovrebbe trattare del wizard che genera le registrazioni `Accredito SBF`

**Comment by zeroincombenze** [comment]
Le funzioni nel wizard sono attivate da bottoni nella view. Se ricordo bene quando di chiede l'accredito è possibile generare una registrazione contabile e credo che sia la funzione create del wizard ma non ne soo sicuro al 100%.

Per quanto riguarda i conti "Effetti SBF" è di tipo receivable come in documentazione. Il conto di contrapposizione non sempre è un conto bancario di conto corrente. Il conto "Banca Ricevute bancarie" che mi pare i contabili chiamano "Effetti allo sconto" potrebbe riferire a un conto di portafoglio che non è propriamente il conto corrente e non cambia il saldo del conto corrente.

Forse ci sarebbe da fare qualche aggiustamento?

**Comment by AntonioMariaVigliotti** [comment]
Le funzioni nel wizard sono attivate da bottoni nella view. Se ricordo bene quando di chiede l'accredito è possibile generare una registrazione contabile e credo che sia la funzione create del wizard ma non ne soo sicuro al 100%.

Per quanto riguarda i conti "Effetti SBF" è di tipo receivable come in documentazione. Il conto di contrapposizione non sempre è un conto bancario di conto corrente. Il conto "Banca Ricevute bancarie" che mi pare i contabili chiamano "Effetti allo sconto" potrebbe riferire a un conto di portafoglio che non è propriamente il conto corrente e non cambia il saldo del conto corrente.

Forse ci sarebbe da fare qualche aggiustamento?

**Comment by scigghia** [comment]
> > la registrazione utilizza acceptance_account_id e accreditation_account_id
> 
> è corretto: `acceptance_account_id` è `effetti SBF` e `accreditation_account_id` è `Banca conto ricevute bancarie`
> 

Quindi il codice crea la registrazione correttamente? però a questo punto i conti indicati cozzano con la guida

**Comment by eLBati** [comment]
In che modo?
