### ISSUE TITLE
Errore installazione modulo l10n_it_ddt su odoo 8

### ISSUE THREAD

**Issue by Mitconsulting** [OCA/l10n-italy#176]
quando provo ad installare il modulo l10n_it_ddt esce questo errore...

"Exception: Module loading l10n_it_ddt failed: file l10n_it_ddt\security/ir.model.access.csv could not be processed:
 Line 9 : Nessun record trovato per id esterno 'model_stock_ddt_type' nel campo 'Object'"

come posso risolvere l'errore?

**Comment by OpenCode** [comment]
Ciao @Mitconsulting 

ho appena installato il modulo ddt e non mi ha dato il problema da te indicato? Dopo aver scaricato il repo hai eseguito un checkout sul branch giusto? Il db era nuovo o già avviato? Ti sei assicurato di non avere un altro modulo con lo stesso nome che ha priorità su questo?

**Comment by Mitconsulting** [comment]
ciao @OpenCode 
il db è nuovo e ho solo installato il modulo Magazzino...tieni presente che sto lavorando su una installazione di odoo 8 su windows

**Comment by SGiuseppe** [comment]
Scusate.... ma non ho ben capito se rispondere qui oppure di là. 
Per correttezza, visto che l'altro post è chiuso, continuo su questo e, ripeto anche la risposta scritta nell'altro post.

Ho semplicemente aggiornato il repository con il comando
git pull

ho notato che vi erano dei cambiamenti nel sorgente. A quel punto ho semplicemente reinstallato il modulo. Senza il problema citato su. Devo dire che non ho riprovato a reinstallarlo su un altro database e non ho fatto altri aggiornamenti.

**Comment by OpenCode** [comment]
@Mitconsulting come hai installao il modulo? Da dove lo hai preso? Il branch in cui ti trovi è 8.0? Non ho esperienze di installazioni di Odoo su Windows onestamente.

**Comment by Mitconsulting** [comment]
allora funziona il modulo che ho scaricato da https://www.odoo.com/apps/modules/8.0/l10n_it_ddt/
mentre mi ha dato quell'errore il modulo che ho scaricato da https://github.com/OCA/l10n-italy/tree/8.0

**Comment by SGiuseppe** [comment]
Per dovere di informazione:
```
giuseppe@opensuse-virtuale:~/Documenti/ddt/eLBarati/.git> cat config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/eLBati/l10n-italy.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "8.0-ddt-based-on-packaging-preparation_lb"]
	remote = origin
	merge = refs/heads/8.0-ddt-based-on-packaging-preparation_lb

```

Come si può notare ho usato il repository di eLBati.

**Comment by OpenCode** [comment]
@SGiuseppe Il modulo che hai indicato è ormai confluito in stock-picking-workflow di OCA mentre il modulo ddt è confluito in l10n-italy

**Comment by eLBati** [comment]
Si può chiudere?

**Comment by SGiuseppe** [comment]
Non ho provato ad reinstallare il modulo quindi non ho voce in capitolo. Penso che vada bene chiuderlo.
