### ISSUE TITLE
[IMP] Mostra Netto da Pagare su tree fatture fornitore

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#1762]
**Versioni coinvolte**

- [x] v10: https://github.com/OCA/l10n-italy/pull/1763
- [ ] v11: ?
- [x] v12: https://github.com/OCA/l10n-italy/pull/1776

**Comment by eLBati** [comment]
v12 https://github.com/OCA/l10n-italy/pull/1776

**Comment by tafaRU** [comment]
Chiudo come da [linee guida](https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#chiusura-issue).
Se qualcuno ha intenzione di fare la PR per la 11.0 la riapra pure.
