### ISSUE TITLE
Modulo l10n_it_website_portal_fiscalcode autoinstallante con solo portal e l10n_it_fiscalcode

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1764]
È una cosa voluta? Non ci vorrebbe almeno website?

https://github.com/OCA/l10n-italy/blob/c8ef48940781b634497deeb1354b3df28dbeece1/l10n_it_website_portal_fiscalcode/__manifest__.py#L15

**Comment by eLBati** [comment]
> Non ci vorrebbe almeno website?

Non mi risulta: sulla 12 le funzionalità portal non dipendono da website; puoi ad esempio far visualizzare preventivi online senza avere website

**Comment by sergiocorato** [comment]
Quindi il ...website... nel modulo è solo un residuo di una necessità precedente?

**Comment by eLBati** [comment]
@sergiocorato penso di sì, perchè nelle versioni precedenti non c'era distinzione tra `portal` e `website`, nel senso che le funzionalità portale dipendevano da `website` se non sbaglio.
Il nome  più corretto per il modulo sarebbe forse `l10n_it_fiscalcode_portal`. Varrebbe un po' per tutti i moduli `l10n_it_website_portal_*`

**Comment by sergiocorato** [comment]
@eLBati quindi si potrebbe modificarne il nome sulla v. 14.0, inserendo in Openupgrade la modifica

**Comment by eLBati** [comment]
Sì
