### ISSUE TITLE
Dipendenza su intrastat_base di l10n_it_invoices_data_communication

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1770]
Visto che intrastat è basato sui due moduli della localizzazione italiana, perchè c'è questa dipendenza? Si potrebbe dipendere dai moduli italiani?

https://github.com/OCA/l10n-italy/blob/23ec1fd7a62de27278e1e0e793f6f8543709901e/l10n_it_invoices_data_communication/__manifest__.py#L20

**Comment by eLBati** [comment]
Penso che la dipendenza serva per questo
https://github.com/OCA/l10n-italy/blob/23ec1fd7a62de27278e1e0e793f6f8543709901e/l10n_it_invoices_data_communication/models/communication.py#L369
