### ISSUE TITLE
[fiscal_epos_print] Stampa duplicato scontrino

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1779]
**Versioni coinvolte**
`12.0`

**Passi per riprodurre**

1. Nel POS, fare un acquisto e stampare lo scontrino
2. Cliccare sul carrello (in alto),
3. Cliccare sull'iconcina della stampante:
![image](https://user-images.githubusercontent.com/32064796/83858144-5417f300-a71c-11ea-9519-826c0e0f1f69.png)
per l'ordine appena creato

**Comportamento osservato**
Errore:
![image](https://user-images.githubusercontent.com/32064796/83858402-b8d34d80-a71c-11ea-93bc-8925188a047f.png)

**Comportamento atteso**
Stampare un duplicato dello scontrino

Ho visto che il messaggio di errore è voluto e il codice che lo solleva esplicitamente è:
https://github.com/OCA/l10n-italy/blob/4532c6ab43b3a4e603543ff8d5d9e80cce5b8715/fiscal_epos_print/static/src/js/pos_order_mgmt.js#L36-L41

Come posso fare per stampare il duplicato di uno scontrino?

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/1780#pullrequestreview-425250284
