### ISSUE TITLE
[fatturazione elettronica 1.6] modifica della enumeration di  Tipo Documento Type

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#1799]
Versioni coinvolte:
- [ ] 10.0
- [ ] 11.0
- [x] 12.0 ~#1792~ ~~#1864~~ 

Passi per riprodurre:

Comportamento osservato:

Comportamento atteso:

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/issues/1670#issuecomment-644082541
