### ISSUE TITLE
La form di checkout dell'eCommerce non evidenzia tutti i campi obbligatori

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1810]
Dopo aver aperto un ticket [qui](https://github.com/odoo/odoo/issues/51092) ritengo che il seguente problema sia collegato al modulo _l10n_it_website_sale_fatturapa_.

Se nella form di checkout si procede senza inserire alcun dato, viene segnalata l’obbligatorietà di: Email, Telefono, Indirizzo, Città e Nazione. Procedendo dopo averli inseriti, viene segnalato che "_Alcuni campi obbligatori sono vuoti_", ma nessun campo è evidenziato, né con un asterisco né con il bordo rosso. 

![Screenshot_2020-06-20 Address Management My Website](https://user-images.githubusercontent.com/38140509/85197598-641a0000-b2e2-11ea-9445-b7aae33a0916.png)

**Comment by eLBati** [comment]
Effettivamente non è chiarissimo, comunque si tratta di nome e cognome, che sono in grassetto

**Comment by protontrigg3r** [comment]
Per agevolare il visitatore dell'eCommerce, sarebbe bene uniformare il modo in cui vengono evidenziati i campi mancanti: puoi indicare dove si deve intervenire?

**Comment by eLBati** [comment]
Direi qui
https://github.com/OCA/l10n-italy/blob/5aa3b920c19bbd7a3222e9fa4e17c08a91704bec/l10n_it_website_sale_fatturapa/controllers/main.py#L60
Bisognerebbe aggiungere a `error` i campi che effettivamente stanno andando in errore

**Comment by protontrigg3r** [comment]
Mi riferivo al fatto di evidenziare i campi obbligatori (che tu mi facevi notare sono evidenziati in grassetto) anche affiancandoci un asterisco.

**Comment by eLBati** [comment]
Invece di evidenziarli nel modo standard e coerente con il resto dell'interfaccia previsto da odoo?

**Comment by protontrigg3r** [comment]
Esatto, per uniformarli al theme grafico, che (almeno nel mio caso) influenza solo i campi della form di checkout standard:

![Schermata da 2020-07-17 09-41-19](https://user-images.githubusercontent.com/38140509/87761501-de6e6f00-c811-11ea-81d6-f5df5b0eca58.png)

**Comment by eLBati** [comment]
Se è il tema ad aggiungere gli asterischi, allora la modifica va fatta nel tema o in un modulo che estende il tema

**Comment by protontrigg3r** [comment]
Ok. Non sono un esperto, ma dato che le classi CSS dei campi della form di chekout standard sembrano le stesse dei campi introdotti dalla personalizzazione italiana, trovo strano che le impostazioni CSS del tema non influenzino allo stesso modo l'estetica di tutti i campi. Quindi sto cercando di capirne un po' di più ....

**Comment by protontrigg3r** [comment]
Solo per completezza: ...il CSS in questione non interviene sulla classe dei campi ma sui singoli ID.

Campi form standard:

```
<div id="div_email" class="form-group  col-lg-6">
	<label class="col-form-label" for="email">E-mail</label>
	<input type="email" name="email" class="form-control ">
</div>
```

```
<div id="div_phone" class="form-group  col-lg-6">
	<label class="col-form-label" for="phone">Telefono</label>
	<input type="tel" name="phone" class="form-control ">
</div>
```

campi introdotti dalla personalizzazione italiana:

```
<div class="form-group  col-lg-6 div_firstname">
	<label class="col-form-label" for="name">Nome</label>
	<input type="text" name="firstname" class="form-control ">
</div>
```

CSS:

```
        .div_name,#div_email,#div_phone,.div_street,.div_city,.div_country,.div_state
        {
                >label:after
                {
                        content:'*';
                }
        }
```

**Comment by eLBati** [comment]
> .div_name,#div_email,#div_phone,.div_street,.div_city,.div_country,.div_state

Questo CSS non è introdotto dal tema?

**Comment by protontrigg3r** [comment]
Si, è introdotto dal tema. Ma pensavo potesse essere utile segnalare come funziona, visto che il ticket è aperto.

L'html dei campi obbligatori dovrebbe essere generato con una class CSS specifica, da usare poi per distinguerli esteticamente.
 
Invece, a quanto pare, è necessario inserire nel CSS in maniera esplicita l'id di ogni campo che si desidera evidenziare, a prescindere che questo sia realmente obbligatorio.
