### ISSUE TITLE
[12.0] partner_vat_unique: errore 500 se PI già esistente

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#1813]
Versioni coinvolte: 12.0

**Passi per riprodurre**: installare _eCommerce_ e _partner_vat_unique_ e inserire nella form di checkout una P.I. già esistente

**Comportamento osservato**: 500 Internal Server Error
```
... odoo.addons.website.models.ir_http: 500 Internal Server Error:

Traceback (most recent call last):
  File ".../odoo/addons/base/models/ir_http.py", line 203, in _dispatch
    result = request.dispatch()
8<
  File ".../odoo/models.py", line 1117, in _validate_fields
    check(self)
  File ".../addons-extra/OCA/partner-contact/partner_vat_unique/models/res_partner.py", line 31, in _check_vat_unique
    "partner.") % record.vat)
odoo.exceptions.ValidationError: ('La Partita Iva ITxxxxxxxxxxx è già assegnata ad un altro partner.', None)

```
**Comportamento atteso**: l'eccezione dovrebbe essere gestita segnalando all'utente l'impossibilità di accettare il dato inserito nel campo della P.I.

**Comment by tafaRU** [comment]
Ciao @protontrigg3r,

grazie della segnalazione, come vedi però il modulo in oggetto appartiene a https://github.com/OCA/partner-contact, pertanto conviene che utilizzi https://github.com/OCA/partner-contact/issues.

**Comment by protontrigg3r** [comment]
Sorry ...
