### ISSUE TITLE
[l10n_it_fatturapa_in] Cassa previdenziale

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#1828]
Versioni coinvolte:

- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2387
- [ ] 14.0: 

Passi per riprodurre: 
Nel mio caso ho un ambiente multicompany con 10 company, ho una fattura in ingesso dove ho all'interno un prodotto di tipo cassa previdenziale.

nella configurazione della contabilità ho correttamente indicato il prodotto da usare con il relativo  field del conto da usare riporto gli screen per completezza:
![image](https://user-images.githubusercontent.com/43987335/87404373-5a707900-c5be-11ea-8051-38b0b672727d.png)

![image](https://user-images.githubusercontent.com/43987335/87404593-9f94ab00-c5be-11ea-95f7-abf4b57106f0.png)

Il problema è relativo a questa parte di codice:
https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1306

Se si accede al campo  self.env.user.company_id.cassa_previdenziale_product_id e poi nel metodo sotto adjust_accounting_data e poi nel metodo https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L408 si va ad accede al campo product.product_tmpl_id.**property_account_expense_id** è vuoto quando in realtà come da screen sopra è valorizzato.

Se tuttavia prendo l'id del prodotto di cui sopra ne faccio la browse e vado a prendere il medesimo campo è valorizzato

Comportamento osservato:

Comportamento atteso:

Il comportamento che mi aspetto è che con questa operazione self.env.user.company_id.cassa_previdenziale_product_id io possa accedere a tutti i field del campo e non solo ad alcuni

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Immagino dipenda dall'utente, e quindi dalla company, con cui stai eseguendo l'importazione.
Hai impostato il campo `E-bill creator` in configurazione?

**Comment by matteoopenf** [comment]
> Immagino dipenda dall'utente, e quindi dalla company, con cui stai eseguendo l'importazione.
> Hai impostato il campo `E-bill creator` in configurazione?

@eLBati  innanzi tutto grazie per la risposta.

Ho provato a cercare il campo che accenni ma non l'ho trovato, dove è localizzato configurazione della contabilità o sulla company?

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_pec/models/company.py#L9-L13

**Comment by matteoopenf** [comment]
@eLBati  nel mio caso non utilizzo il modulo pec che introduce questo campo

**Comment by eLBati** [comment]
In ogni caso direi che dipende dall'utente che esegue l'importazione

**Comment by OpenCode** [comment]
@eLBati La possibilità che il problema sia dovuto dall'utente è stata esclusa provando con utenti diversi e accertandosi della company dell'utente.

L'anomalia sta nel fatto che interrogando `product.product_tmpl_id.property_account_expense_id` si ottiene un valore vuoto mentre il codice `self.env['product.template'].browse(product.product_tmpl_id.id).property_account_expense_id` restituisce lo stesso valore che è possibile trovare navigando il prodotto da interfaccia.

**Comment by eLBati** [comment]
Cosa c'è nell'`env` di `product`? Cosa ha di diverso da `self.env`?

**Comment by OpenCode** [comment]
A prima vista sembra niente

**Comment by SimoneVagile** [comment]
Sono incappato anche io nello stesso errore.

Ho debuggato un bel po', e ho capito che il problema viene fuori quando il cliente è multicompany.fattura 

Illustro il caso: importazione fattura xml con company diversa dalla default.

[https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1306](https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1306)

Qui `company_id` è la company corretta, ma se guardo il valore di `cassa_previdenziale_product.env.user.company_id` è a seconda company, quella sbagliata. Per questo `property_account_expense_id` è vuoto e restituisce `property_account_expense_categ_id` del `product.category`, ma anche questo della company sbagliata.

C'è una fix per la 14.0 [https://github.com/OCA/l10n-italy/pull/2352](https://github.com/OCA/l10n-italy/pull/2352) ma non ho trovato nulla per questa.

**Comment by matteoopenf** [comment]
> Sono incappato anche io nello stesso errore.
> 
> Ho debuggato un bel po', e ho capito che il problema viene fuori quando il cliente è multicompany.
> 
> Illustro il caso: importazione fattura xml con company diversa dalla default.
> 
> https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1306
> 
> Qui `company_id` è la company corretta, ma se guardo il valore di `cassa_previdenziale_product.env.user.company_id` è a seconda company, quella sbagliata. Per questo `property_account_expense_id` è vuoto e restituisce `property_account_expense_categ_id` del `product.category`, ma anche questo della company sbagliata.
> 
> C'è una fix per la 14.0 #2352 ma non ho trovato nulla per questa.

Ciao Simone, 

per 12 qui mi ero arenato sinceramente, perchè se facevo poi la browse del medesimo prodotto della cassa previdenziale, che è quello che poco prima non mi trova poi mi viene trovato.

**Comment by matteoopenf** [comment]
> Sono incappato anche io nello stesso errore.
> 
> Ho debuggato un bel po', e ho capito che il problema viene fuori quando il cliente è multicompany.
> 
> Illustro il caso: importazione fattura xml con company diversa dalla default.
> 
> https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1306
> 
> Qui `company_id` è la company corretta, ma se guardo il valore di `cassa_previdenziale_product.env.user.company_id` è a seconda company, quella sbagliata. Per questo `property_account_expense_id` è vuoto e restituisce `property_account_expense_categ_id` del `product.category`, ma anche questo della company sbagliata.
> 
> C'è una fix per la 14.0 #2352 ma non ho trovato nulla per questa.

Su 12.0 so che il comportamento per accedere alle company è diverso da 14.0.
Tu come vorresti cambiare self.env.user.company_id.cassa_previdenziale_product_id rispetto a come già  hai proposto su 14?

Fammi sapere che magari provo ad aprire una pr in proposito

**Comment by matteoopenf** [comment]
> > Sono incappato anche io nello stesso errore.
> > Ho debuggato un bel po', e ho capito che il problema viene fuori quando il cliente è multicompany.
> > Illustro il caso: importazione fattura xml con company diversa dalla default.
> > https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1306
> > 
> > Qui `company_id` è la company corretta, ma se guardo il valore di `cassa_previdenziale_product.env.user.company_id` è a seconda company, quella sbagliata. Per questo `property_account_expense_id` è vuoto e restituisce `property_account_expense_categ_id` del `product.category`, ma anche questo della company sbagliata.
> > C'è una fix per la 14.0 #2352 ma non ho trovato nulla per questa.
> 
> Su 12.0 so che il comportamento per accedere alle company è diverso da 14.0.
> Tu come vorresti cambiare self.env.user.company_id.cassa_previdenziale_product_id rispetto a come già hai proposto su 14?
> 
> Fammi sapere che magari provo ad aprire una pr in proposito

@SimoneVagile  mi scuso per le più risposte, ma credi che togliere user e passare diretto company  funzioni su 12?

**Comment by SimoneVagile** [comment]
>  mi scuso per le più risposte, ma credi che togliere user e passare diretto company funzioni su 12?

No, la property `company` dell'Environment viene usata a partire dalla versione 13: [https://github.com/odoo/odoo/blob/13.0/odoo/api.py#L525](https://github.com/odoo/odoo/blob/13.0/odoo/api.py#L525)

> per 12 qui mi ero arenato sinceramente, perchè se facevo poi la browse del medesimo prodotto della cassa previdenziale, che è quello che poco prima non mi trova poi mi viene trovato.

Quando arrivavi ai campi `property_account_*` avevi uno `user.company_id` diverso dal `company_id` dell'oggetto `account.account`, quindi non lo trovava con quell' `id`. Quello che non mi è chiaro il motivo dei due environment con `user.company_id` diversi, @eLBati forse può chiarire questo aspetto meglio di me.

> Tu come vorresti cambiare self.env.user.company_id.cassa_previdenziale_product_id rispetto a come già hai proposto su 14?

Ho creato un "workaround", a breve aprirò la PR: [https://github.com/SimoneVagile/l10n-italy/commit/cfbc2bcf3f3e06311b06bea8c2ea1356c4f6ba75](https://github.com/SimoneVagile/l10n-italy/commit/cfbc2bcf3f3e06311b06bea8c2ea1356c4f6ba75)
