### ISSUE TITLE
[12.0] l10n_it_dichiarazione_intento - cambio posizione fiscale non voluto

### ISSUE THREAD

**Issue by labaggio** [OCA/l10n-italy#1830]
Versioni coinvolte:

- [x] 10.0 Vedi https://github.com/OCA/l10n-italy/pull/1811#issuecomment-662481851
- [x]  12.0 https://github.com/OCA/l10n-italy/pull/1829

Passi per riprodurre:
Dopo aver installato il modulo, creare un cliente con una posizione fiscale (per esempio per le extra cee con cambio di imposta)
Non creare nessuna dichiarazione d'intento per il cliente.
Creare una fattura di vendita, inserire una riga di prodotto che (verrà creata con iva impostata nella posizione fiscale).
Selezionare la data della fattura.

Comportamento osservato:
la posizione fiscale verrà annullata e la riga di dettaglio modificherà l'imposta, inserendo quella originale del prodotto.

Comportamento atteso:
Nel caso in cui il cliente non abbia dichiarazioni d'intento, l'assegnazione della data non deve modificare la posizione fiscale e le righe della fattura.

Video/Screenshot (opzionale):

**Comment by labaggio** [comment]
Qualcuno può controllare e confermare che il link "Selezionare manualmente" funzioni correttamente? 
Forse è un problema solo mio, ma a me non appaiono le dichiarazioni del cliente selezionato.. :(

**Comment by eLBati** [comment]
Confermo entrambi i problemi

**Comment by labaggio** [comment]
bene, almeno non ho allucinazioni :D
la PR risolve già il primo, per il secondo accetto suggerimenti..
la riga incriminata è questa. 
https://github.com/OCA/l10n-italy/blob/09e579cc1162eed3b703fc3577edc688a82f9eca/l10n_it_dichiarazione_intento/wizard/manually_declarations.py#L19
id_invoice NON è l'id della fattura, di conseguenza non trova il partner e le sue dichiaraizoni
