### ISSUE TITLE
[l10n_it_fiscalcode] Cambiare metodo di validazione del codice fiscale

### ISSUE THREAD

**Issue by FrancoTampieri** [OCA/l10n-italy#1833]
Stavo valutando nel modulo per il codice fiscale, di completarlo con la libreria "stdnum", la trovo molto più completa per i check e più adatta per eventuali sviluppi per altre verifiche su codifiche ISO e altri standard internazionali.

- [ ] 14.0 
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/4511

**Comment by sergiocorato** [comment]
`python-stdnum` è già presente di default in quanto dipendenza di `vatnumber`, se ti interessa

**Comment by OpenCode** [comment]
> Stavo valutando nel modulo per il codice fiscale, di completarlo con la libreria "stdnum", la trovo molto più completa per i check e più adatta per eventuali sviluppi per altre verifiche su codifiche ISO e altri standard internazionali.

La tua proposta è di affiancare l'attuale libreria con stdnum o di fare un rimpiazzo completo?

**Comment by drdran** [comment]
@sergiocorato Interessante, non lo avevo valutato anche perchè vatnumber 1.2 è un pò obsoleto... il progetto non è più mantenuto e la release 1.2 risale al 2014
@OpenCode di base affiancare, poichè la generazione del codice non è presente in stdnum, tuttavia la validazione è presente e supporta anche altre validazioni che potrebbero essere utili, ovviamente è una proposta, mi sono ritrovato ad usare stdnum su un altro progetto e ho visto che sono supportate un sacco di codifiche standard, ovviamente se se lo porta com edipendenza vatnumber, questo decade, anche se vorrei capire se è fissato ad una release particolare vista l'obsolescenza della prima

Poi ovviamente correggetemi se sbaglio

**Comment by OpenCode** [comment]
L'idea di per sé non è malvagia visto che è già una dipendenza di sistema. Tuttavia il modulo del codice fiscale è così semplice che sarebbe un peccato infarcirlo di ulteriori librerie visto che comunque l'altra dobbiamo in ogni modo tenercela per fare la creazione del codice.

Appoggio idealmente l'idea ma forse sarebbe meglio mantenere lo status quo con solo l'attuale libreria e prevedere la migrazione a python-stdnum quando nascerà l'esigenza.

**Comment by drdran** [comment]
Da parte mia non vedo problemi, teniamola in considerazione per eventuali altre esigenze.

L'inico mio dubbio rimanse sempre su vatnumber che non è più sviluppata da tanto...

**Comment by patrickt-oforce** [comment]
Riguardo questa issue, ritenete possibile il cambio della libreria usata per validare il codice fiscale da `codicefiscale` a `python-codicefiscale`?
Quest'ultima supportebbe anche la validazione formali di CF con omocodia

**Comment by SirAionTech** [comment]
> Riguardo questa issue, ritenete possibile il cambio della libreria usata per validare il codice fiscale da `codicefiscale` a `python-codicefiscale`? Quest'ultima supportebbe anche la validazione formali di CF con omocodia

Sì certo che è possibile, ma non è quello di cui parlava questa issue; se vuoi proporlo penso sia meglio aprirne un'altra dedicata.

**Comment by patrickt-oforce** [comment]
> > Riguardo questa issue, ritenete possibile il cambio della libreria usata per validare il codice fiscale da `codicefiscale` a `python-codicefiscale`? Quest'ultima supportebbe anche la validazione formali di CF con omocodia
> 
> Sì certo che è possibile, ma non è quello di cui parlava questa issue; se vuoi proporlo penso sia meglio aprirne un'altra dedicata.

Grazie per il chiarimento, ma ho visto che @francesco-ooops ha linkato la mia PR a questa issue

**Comment by francesco-ooops** [comment]
@patrickt-oforce aprine un'altra e sposto i link

**Comment by SirAionTech** [comment]
> > > Riguardo questa issue, ritenete possibile il cambio della libreria usata per validare il codice fiscale da `codicefiscale` a `python-codicefiscale`? Quest'ultima supportebbe anche la validazione formali di CF con omocodia
> > 
> > 
> > Sì certo che è possibile, ma non è quello di cui parlava questa issue; se vuoi proporlo penso sia meglio aprirne un'altra dedicata.
> 
> Grazie per il chiarimento, ma ho visto che @francesco-ooops ha linkato la mia PR a questa issue

Visto che la PR non risolve il problema di questa issue le ho scollegate e ora la PR è https://github.com/OCA/l10n-italy/labels/missing%20issue: @patrickt-oforce come ha scritto @francesco-ooops quando aprirai la issue dedicata un maintainer potrà collegarla alla PR.
