### ISSUE TITLE
Aggiungere più campi da visualizzare nella treeview della liquidazione IVA

### ISSUE THREAD

**Issue by robyf70** [OCA/l10n-italy#1837]
Aggiungere più campi nella tree view della liquidazione iva per mostrare le informazioni essenziali delle singole liquidazioni

* [x] 10.0 #1835
* [ ]  11.0
* [x] 12.0 #1836

**Comment by primes2h** [comment]
Chiudo come da [linee guida](https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#chiusura-issue).
Se qualcuno ha intenzione di fare la PR per la 11.0 la riapra pure.
