### ISSUE TITLE
[IMP] l10n_it_ddt: show number of TDs linked to the sale order

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#1845]
Versioni coinvolte:

- [x] v10: https://github.com/OCA/l10n-italy/pull/1846
- [ ] v11:
- [ ] v12:

**Comment by OpenCode** [comment]
@tafaRU Sai se il problema è presente sulla 14.0?

**Comment by francesco-ooops** [comment]
@OpenCode non dovrebbe esserci questo modulo sulla 14 o sbaglio?

**Comment by OpenCode** [comment]
> @OpenCode non dovrebbe esserci questo modulo sulla 14 o sbaglio?

No no. Hai ragione. Giusto. Mi sono confuso con il modulo nuovo.

**Comment by francesco-ooops** [comment]
@tafaRU pensi si possa chiudere?
