### ISSUE TITLE
fiscal_epos_print: lotteria degli scontrini + RT XML 7

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#1857]
Versioni coinvolte:

 - [x] 10.0 (risolta per supporto terminato)
 - [x] 11.0 (risolta per supporto terminato)
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/1997
 - [ ] 14.0 ?
 - [ ] 16.0 ?

### Lotteria

Implementazione lotteria degli scontrini:
https://www.lotteriadegliscontrini.gov.it

Resi:

The Lottery ID CODE must be sent only if the original sales receipt was not found in the EJ of the
RT printer. If the Original Receipt is found in the EJ the RT add the Lottery Code available in the
original receipt.

Il codice lotteria è alternativo al codice fiscale

### XML 7

 - [ ] La ristampa dell'ultimo documento commerciale emesso (stampa da DGFE) richiede la "log in" ? (anche https://github.com/OCA/l10n-italy/pull/1780#issuecomment-717971124)
 - [x] Nuovi payment type e index
 - [ ] Voucher mono uso e multi uso (nel secondo caso non so a priori l'IVA: dipenderà da come verrà utilizzato)
 - [ ] La stampante arrotonderà ai 5 cents: `account.cash.rounding` da configurare?
 - [ ] Configurazione reparti:
   - beni o servizi (RT dovrà sapere i non riscossi, sui servizi si paga l'IVA al pagamento, sui beni alla consegna; il caso è quello dei ticket)
   - codici ATECO
 - [ ] Sconto a pagare
 - [ ] Sarà possibile fare resi basati su "altre evidenze" (ad es scontrino POS) con una sintassi apposita.
 - [ ] Nuova natura per la ventilazione IVA

**Comment by eLBati** [comment]
Se qualcuno è interessato all'argomento, vorrei creare un gruppo di lavoro per analizzare, progettare e sviluppare le funzionalità relative a questa issue.

Incontriamoci sul canale #pos su discord: https://discord.gg/W2TSbjQrxk

**Comment by OpenCode** [comment]
> Se qualcuno è interessato all'argomento, vorrei creare un gruppo di lavoro per analizzare, progettare e sviluppare le funzionalità relative a questa issue.
> 
> Incontriamoci sul canale #pos su discord: https://discord.gg/W2TSbjQrxk

@eLBati hai novità a riguardo?
