### ISSUE TITLE
[FIX] l10n_it_intrastat_statement: supply and payment method are mandatory

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1880]
**Versioni coinvolte**

- [x] 10: https://github.com/OCA/l10n-italy/pull/1881
- [x] 12: https://github.com/OCA/l10n-italy/pull/2142

**Passi per riprodurre**
1. Spostarsi in Contabilità > Operazioni contabili > Intrastat > Dichiarazioni intrastat
2. Creare una dichiarazione
3. Nel tab "Cessione servizi - sezione 3", click su "Aggiungi voce"
4. Compilando tutti i campi tranne *Numero fattura*, *Data fattura*, *Modalità di erogazione*, *Modalità di incasso*
5. Click su "Salva e chiudi"

**Comportamento osservato**
I campi *Numero fattura*, *Data fattura*, *Modalità di erogazione*, *Modalità di incasso* sono richiesti per salvare la riga.

**Comportamento atteso**
La riga viene salvata

Nota che i due campi sono facoltativi:
> Numero fattura (col. 5).
> Indicazione facoltativa [...]
>
> Data fattura (col. 6).
> Indicazione facoltativa [...]
>
> Modalità di erogazione (col. 8).
> Indicazione facoltativa [...]
>
> Modalità di incasso (col. 9).
> Indicazione facoltativa [...]

(Rif. https://www.adm.gov.it/portale/documents/20182/908833/AllegatoXI++DEF+18+2+15.pdf/34c12ee1-d810-4be5-bfcf-1ff2e0bfe9ab)

**Video/Screenshot (opzionale)**
![image](https://user-images.githubusercontent.com/32064796/93588821-3e1cfe00-f9ac-11ea-917c-dd45abc98863.png)

**Comment by eLBati** [comment]
Inclusa in https://github.com/OCA/l10n-italy/pull/2142
