### ISSUE TITLE
[12.0] Eccezione durante l'esecuzione dei test

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#1882]
**Versioni coinvolte**
- [ ] v10
- [x] v12: https://github.com/OCA/l10n-italy/pull/1883

Nel travis verde (/push) c'è però:
`lxml.etree.XMLSyntaxError: Namespace prefix ns1 on Fattura is not defined, line 1, column 13`

_Originally posted by @sergiocorato in https://github.com/OCA/l10n-italy/pull/1873#issuecomment-694834509_

**Comment by eLBati** [comment]
Nelle altre versioni non capita?

**Comment by SimoRubi** [comment]
> Nelle altre versioni non capita?

Sì, ad esempio in v10 c'è https://travis-ci.org/github/OCA/l10n-italy/jobs/728320569#L2046.
Ho modificato la issue aggiungendo v10
