### ISSUE TITLE
[fix] - fpdeptax field in fiscal_epos_print module should accept 2 digits

### ISSUE THREAD

**Issue by fredzamoabg** [OCA/l10n-italy#1884]
Versioni coinvolte:
12.0: https://github.com/OCA/l10n-italy/pull/1889
Passi per riprodurre:

- Entrare in Contabilità - configurazione -> Imposte
- selezionarne una
- passare al tab "Opzioni avanzate"
- Il campo Reparto stampante fiscale 1-99 accetta solo valori di una cifra
![screenshot](https://user-images.githubusercontent.com/70569899/93751880-17ee9c80-fbfe-11ea-9f1b-ee9612f1abad.png)

Comportamento osservato:
osservati 2 problemi:
- il campo accetta una sola cifra
- il campo accetta anche caratteri non numerici

Comportamento atteso:
- size del campo == 2
- il campo dovrebbe accettare solo valori numerici

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
@fredzamoabg grazie. Hai voglia di fare la PR?

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/1889#issuecomment-698245941
