### ISSUE TITLE
Aiuto installazione

### ISSUE THREAD

**Issue by tobesmartcs** [OCA/l10n-italy#1888]
Salve ragazzi. Sono nuovo della community di odoo. Ho visto il progetto ed ho scaricato il file, solo che l'ho caricato nella path degli addons del mio odoo 12 e tra le applicazioni installabili non lo vedo. 
Mi potreste dare una mano?

**Comment by matteoopenf** [comment]
Due cose:
Hai aggiornato la lista moduli?
Hai aggiunto il Path di questo repo agli addons path?

Sui Log infine hai errori?

Matteo Mircoli
Developer | matteomircoli@openforce.it 

> Il giorno 22 set 2020, alle ore 22:33, tobesmartcs <notifications@github.com> ha scritto:
> 
> ﻿
> Salve ragazzi. Sono nuovo della community di odoo. Ho visto il progetto ed ho scaricato il file, solo che l'ho caricato nella path degli addons del mio odoo 12 e tra le applicazioni installabili non lo vedo.
> Mi potreste dare una mano?
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by eLBati** [comment]
Ciao @tobesmartcs , le issue github vengono usate per tracciare i malfunzionamenti o gli sviluppi di nuove funzionalità.

Per le richieste di supporto vedi https://www.odoo-italia.org/forum/forum-1
