### ISSUE TITLE
Import XML: prezzo unitario erroneamente arrotondato a due decimali, totali non coerenti con l'XML

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#1901]
Versioni coinvolte: 12.0

Passi per riprodurre: Importare un XML con una riga riportante un costo unitario con più di 2 decimali.

Comportamento osservato: Il costo unitario viene arrotondato a 2 decimali, e vengono riportate discrepanze con la fattura elettronica, sull'imponibile, IVA e totale.

Comportamento atteso: La fattura dovrebbe essere importata correttamente, come ricevuta dal SdI.

Video/Screenshot (opzionale):
![Bug3-3](https://user-images.githubusercontent.com/915043/94709416-f8feb180-0345-11eb-9efd-c47b01aee084.png)
![Bug2-3](https://user-images.githubusercontent.com/915043/94709420-f9974800-0345-11eb-9129-621d26c0887e.png)
![Bug1-3](https://user-images.githubusercontent.com/915043/94709424-f9974800-0345-11eb-997c-c421c47d9269.png)

**Comment by TheMule71** [comment]
Ho provato ad aumentare i decimali in Funzioni Tecniche -> Struttura Database: Accuratezza Decimale. I default sono 2 per 'Product Price' e 5 per 'Product Price for XML e-invoices'. Li ho impostati entrambi a 6.
La situazione migliora nel senso che le differenze diminuiscono. Rimane però che adesso l'imponibile ha più decimali e non corrisponde all'XML dove è arrotondato a 2.

Per capirci, solo guardando l'XML, si vede come: 4,5455 * 33 = 150,0015 e non 150. Il problema (seppur minore) rimane e Odoo comunque segnala un warning di incongruenza tra la fattura generata e l'XML di importato da cui deriva. O si importano i due campi con due precisioni diverse, or il problema rimane anche con 100 decimali. L'incoerenza  (per quanto minima) è nell'XML.

In realtà il problema è filosofico: faccio un esempio. Se ho una tabella in un db con delle citazioni da personaggi storici, nel campo testo inserisco quello che hanno detto o scritto, anche se grammaticalmente scorretto. Lo sto riportando as-is, per me è un dato opaco che va accettato per quello che è: non sta a me validarlo, per cui non lo valido.

Analogamente, i dati dell'XML essendo da fonte esterna ed ufficialmente "validati" dallo SdI fanno fede. Provocatoriamente, direi fanno fede più della matematica. Se secondo lo SdI 4,5455 * 33 = 150,00, io riporto quello che dice lo SdI. O meglio, meno provocatoriamente, il dettaglio fattura dal punto di vista fiscale è una descrizione, un campo "opaco" che va preso com'è, e i dati nudi da importare (senza toccarli or ricalcolarli) sarebbero l'imponibile, l'aliquota, il totale e altre diciture relative al documento. In un certo senso non sta a me questionare come si arriva a quell'imponibile, lo hanno fatto altri (e ufficialmente), e a me sta solo di riportare la cosa così com'è.

**Comment by eLBati** [comment]
@TheMule71 potresti fornire un XML che riproduca il problema?

**Comment by TheMule71** [comment]
Dovrei renderlo anonimo. Tra gli screenshot vedi il preview della parte rilevante dello stesso. In ogni caso l'import avviene correttamente.

Il problema è in fase di creazione delle righe della fattura, dove il prezzo unitario viene arrotondato e i conti non tornano più.

Ok, ho provato e dovrebbe essere anonimo e caricabile (almeno io riesco a caricarlo):

[1.zip](https://github.com/OCA/l10n-italy/files/5318873/1.zip)

**Comment by TheMule71** [comment]
Ehm, file errato.
[2.zip](https://github.com/OCA/l10n-italy/files/5318902/2.zip)

**Comment by eLBati** [comment]
Con questo file SDI dà
`Errore nella parse del file (idSdi 22359047 ): XML document structures must start and end within the same entity. - File non conforme al formato`

**Comment by TheMule71** [comment]
Ho appena importato il file 2.xml (scaricato da qui) in una diversa istanza di odoo appena creata, senza errori.

l10n-italy è aggiornato al commit 9b5890bb15a1c9e31216885ed06a6ffa5778bb22

![Screenshot from 2020-10-13 18-57-16](https://user-images.githubusercontent.com/915043/95891971-1b50f000-0d86-11eb-9aa2-99124e627220.png)

**Comment by labaggio** [comment]
@eLBati questa problematica può rientrare nel discorso fatto dell'ultima call sull'import minimo, massimo degli xml?

Il problema segnalato in questa issue non è identico da quello riscontrato da noi, ma la soluzione può essere la stessa.
In generale è sempre un problema di decimali del prezzo del prodotto.

Alcune fatture di acquisto, per esempio carburante e bollette elettriche, indicano righe di dettaglio il cui  prezzo ha un numero elevato di decimali. 
Aumentare il numero dei decimali, solo per alcune fatture di acquisto, avrebbe un impatto non desiderato sulle fatture di vendita. 
Se la company ha prezzi a due decimali, si ritroverebbe tutte le stampe con una serie di zeri, non desiderati, negli ordini o nelle fattura.

Non aumentare i decimali però crea il problema di totali.
Se non uso tutti i decimali che mi vengono indicati nel xml di acquisto, i prezzi vengono arrotondati in fase di importazione e  i totali non tornano. 

Al momento il modulo di importazione della fattura elettronica da la possibilità di scegliere il "livello di dettaglio della e-fattura": 

* massimo: in cui ogni linea dell'xml viene indicata nella fattura di odoo
* minimo: in cui vengono riportate tutte le informazioni dell'xml, ma nessuna linea di dettaglio.

La proposta è aggiungere una nuova modalità (per altro presente, almeno come descrizione, ma commentata, nel modulo fatturapa_in) 
* Aliquota: l'idea è di creare una line di dettaglio della fattura,  per ogni riga presente nella sezione "DatiRiepilogo", quindi per ogni aliquota. 
price_unit:  sarà line.ImponibileImporto e quantity sempre 1. In questo modo il dato è già arrotondato.

Questa modalità farà perdere le descrizioni, che dovranno essere modificate una volta creata la fattura. 
Ho ipotizzato di aggiungere come default nella  descrizione del dettaglio riga "Riepologo Aliquota Iva xx%". 

La PR è praticamente già pronta, ho solo il dubbio sulla descrizione della riga di dettaglio. :)

**Comment by TheMule71** [comment]
Ho notato un'altra cosa, tra l'altro. Nell'xsd, nel dettaglio linee, gli importi, sia unitatio che totale, sono a 8 cifre (potenzialmente, la re matcha da 2 a 8 decimali). Solo il totale riepilogo è a 2 cifre.
Per cui chi ha generato la fattura ha deciso di arrotondare il totale di riga senza alcun motivo.

**Comment by eLBati** [comment]
Non lo so, io non ho ancora capito il problema, cioè non ho ancora visto un XML (valido per SDI) che lo riproduca

**Comment by eLBati** [comment]
Forse questo https://github.com/OCA/l10n-italy/issues/1924#issuecomment-716403065

**Comment by labaggio** [comment]
> Non lo so, io non ho ancora capito il problema, cioè non ho ancora visto un XML (valido per SDI) che lo riproduca
al file manca il tag di chiusura `</ns3:FatturaElettronica>`

> Forse questo [#1924 (comment)](https://github.com/OCA/l10n-italy/issues/1924#issuecomment-716403065)
questo non c'entra.  

Il problema qui nasce sul numero di decimali impostati in odoo.
Questa linea di dettaglio del xml
```
<Descrizione>DIESEL</Descrizione>
<Quantita>57.08000</Quantita>
<UnitaMisura>LT</UnitaMisura>
<PrezzoUnitario>1.048360</PrezzoUnitario>
<PrezzoTotale>59.84</PrezzoTotale>
<AliquotaIVA>22.00</AliquotaIVA>
```
Il prezzo ha 6 decimali, dalla schermata che ha allegato @TheMule71, la sua istanza di odoo ha impostato 2 decimali per i prezzi dei prodotti.
Al caricamento del file xml, odoo non può far altro che arrotondare il prezzo che trova a 1.05 e di fare i calcoli su quel valore.

@TheMule71 odoo, fa l'unica cosa che può fare, cioè convertire il prezzo a due decimali e fare il calcolo. 
Se vuoi che il prezzo venga salvato con tutti i decimali, devi modificare le impostazioni. a quel punto i tuoi totali torneranno.

Il mio commento e la PR che voglio implementare vuole "raggirare" l'obbligo di aumentare i decimali e cioè,
in casi come questo, creare una riga per riepilogo Iva (il cui valore sarà sempre con 2 soli decimali)
