### ISSUE TITLE
Importazione nota di credito elettronica con messaggio "Il codice REA deve essere univoco per azienda !"

### ISSUE THREAD

**Issue by pezcl67** [OCA/l10n-italy#1913]
Versioni coinvolte: 12

**Descrizione problema:**

Faccio una importazione di una nota di credito xml proveniente dalla fatturazione elettronica
Quando cerco di confermare l'importazione la procedura mi da sempre "Il codice REA deve essere univoco per azienda !"
La cosa è alquanto strana visto che il fornitore in anagrafica ha lo stesso codice REA presente nell'xml (ed esiste solo lui con quel codice REA).
Anche la partita iva è la stessa.
Sembra che la procedura voglia comunque creare il fornitore anche se esiste già.
Infatti provando a modificare manualmente il codice REA nell'xml il recupero viene fatto ma mi duplica il fornitore.

**Comportamento atteso:**

Dovrebbe riconoscere il fornitore ed agganciarlo senza duplicazioni

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Riesci a fornire i passi e l'XML per riprodurre il problema?

**Comment by pezcl67** [comment]
Certamente.
In anagrafica ho già presente il fornitore (di cui ho già inserito diverse fatture).
Ti allego le immagini con i suoi dati.
![Cattura](https://user-images.githubusercontent.com/61226707/95831871-e159fc80-0d39-11eb-9880-ed6d4f0d2f80.JPG)
![Cattura1](https://user-images.githubusercontent.com/61226707/95831895-eae36480-0d39-11eb-9485-adcb3b30c6cb.JPG)

Poi arriva un xml di una nota di credito (che allego).
Quindi vado in fatturazione - fornitori - file e-fattura in ingresso, ed inserisco il file xml.
Alla conferma mi da il famigerato errore...
[Probios 22683 - IT03230760583_018f6.zip](https://github.com/OCA/l10n-italy/files/5369793/Probios.22683.-.IT03230760583_018f6.zip)

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
