### ISSUE TITLE
[12.0] l10n_it_ricevute_bancarie: campo payment_term_id commentato

### ISSUE THREAD

**Issue by ilaria-franchini** [OCA/l10n-italy#1915]
Versioni coinvolte: 12.0

Passi per riprodurre: https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_ricevute_bancarie/views/account_view.xml#L54

Comportamento osservato: il campo payment_term_id è commentato nella versione 12.0, invece nella versione 10.0 no

Comportamento atteso: vorrei sapere il motivo per il quale è stato commentato e se è possibile decommentarlo

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
