### ISSUE TITLE
[12.0] Gestione Ritenute – Ritenute per cassa previdenziale

### ISSUE THREAD

**Issue by CiroBoxHub** [OCA/l10n-italy#1924]
Versioni coinvolte:

 - [ ] 10.0
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1940

Analisi problematica utilizzo ritenute modulo l10n_it_withhoding_tax per gestione ritenute per casse previdenziali ed esportazione dei dati cassa e della ritenuta ad essa legata nel file xml della fatturazione elettronica.
L’attuale gestione delle ritenute, in conformità a quanto richiesto dal nuovo formato di fatturazione elettronica, manca di alcune parti fondamentali, per tanto risulta incompleta sia la gestione nelle righe fattura che l’esportazione.

Allego il documento di analisi elaborato in merito alla problematica: 
https://docs.google.com/document/d/1mz_U_doNUPMZK6WQmF9didRb4DiCzNskQ9l6PqqfRUE/edit?usp=sharing
Moduli coinvolti:

https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_withholding_tax
https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_fatturapa_out_wt
https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_fatturapa_in

**Comment by eLBati** [comment]
Attendiamo quindi i casi d'uso: uno o più file XML da importare, o fatture odoo da esportare

**Comment by labaggio** [comment]
allego una fattura reale con cassa previdenziale sulla quale è applicata la ritenuta 

(ho dovuto aggiungere l'estensione txt, altrimenti non mi faceva allegare il file)

[IT06363391001_xxx.xml.txt](https://github.com/OCA/l10n-italy/files/5437726/IT06363391001_xxx.xml.txt)

**Comment by eLBati** [comment]
Importando il file rinominato in `IT06363391001_00015.xml` ottengo 
```
odoo12/parts/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1305, in set_welfares_fund
    if not wt_found:
UnboundLocalError: local variable 'wt_found' referenced before assignment
```
Anche voi?

**Comment by labaggio** [comment]
> Importando il file rinominato in `IT06363391001_00015.xml` ottengo
> 
> ```
> odoo12/parts/l10n-italy/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 1305, in set_welfares_fund
>     if not wt_found:
> UnboundLocalError: local variable 'wt_found' referenced before assignment
> ```
> 
> Anche voi?

Si, tutto questo giro è nato da questo errore. 
Mettendo mano per risolvere questo errore ci si è accorti che l'apporoccio era errato, da lì issue e call

**Comment by eLBati** [comment]
Ne parliamo su discord? https://discord.com/channels/753902328494424064/753903737197690991/770919650417573918 cc @CiroBoxHub @sergiocorato

**Comment by marco-marchiori** [comment]
Come dicevo e' il caso di fare una casistica, partiamo dai casi piu' frequenti:
1) avvocato cassa forense (parallelamente molte altri regimi, come commercialisti etc)
2) collaboratore gestione separata con rivalsa 4%
3) agente con ritenuta enasarco.

Quindi
1) rivalsa previdenziale soggetta ad IVA, ritenuta fiscale NON su rivalsa
2) rivalsa previdenziale soggetta ad IVA, ritenuta fiscale ANCHE su rivalsa
3) ritenuta previdenziale su imponibile (non influisce su IVA), ritenuta fiscale su imponibile.

Che relazione col tipo cassa? Il tipo cassa e' riconducibile al regime previdenziale (le regole), le ritenute si fanno in base alle regole. Avro' una corrispondenza (nella maggioranza dei casi) ma non necessariamente una causalita'.
Chi ha tempo approfondisca nelle specifiche se il tipo cassa e' obbligatorio, in alcuni casi l'ho omesso nell'XML ed e' passato lo stesso.
Qui sotto gli esempi.

**Comment by marco-marchiori** [comment]
Caso 1. Avvocato Mario Bianchi di Ferrara.
Imponibile di 100+15% spese.
Vedo che in runbot importa e calcola correttamente.

[ITBNCMRA80A01D548T_20001.xml.txt](https://github.com/OCA/l10n-italy/files/5455086/ITBNCMRA80A01D548T_20001.xml.txt)
[ITBNCMRA80A01D548T_20001.pdf](https://github.com/OCA/l10n-italy/files/5455087/ITBNCMRA80A01D548T_20001.pdf)



](url)

**Comment by marco-marchiori** [comment]
Caso 2. Dr Giuseppe Rossi di Corbetta
Imponibile 1.000
Vedo che il sistema da' l'errore segnalato da Lara.

[ITRSSGPP80A01C986Y_20002.xml.txt](https://github.com/OCA/l10n-italy/files/5455097/ITRSSGPP80A01C986Y_20002.xml.txt)
[ITRSSGPP80A01C986Y_20002.pdf](https://github.com/OCA/l10n-italy/files/5455098/ITRSSGPP80A01C986Y_20002.pdf)

**Comment by marco-marchiori** [comment]
Caso 3. Giacomo Neri, agente di commercio di Firenze.
Imponibile 10.
Mi pare che il sistema non rilevi la ritenuta fiscale (troppe due ritenute?)

[ITNREGCM80H30D612D_20003.xml.txt](https://github.com/OCA/l10n-italy/files/5455107/ITNREGCM80H30D612D_20003.xml.txt)
[ITNREGCM80H30D612D_20003.pdf](https://github.com/OCA/l10n-italy/files/5455108/ITNREGCM80H30D612D_20003.pdf)

**Comment by marco-marchiori** [comment]
Ho lavorato un po' in fretta, chi ha tempo cortesemente confronti con i propri casi, grazie.

**Comment by eLBati** [comment]
Riassumo la chiamata.

Caso `ITRSSGPP80A01C986Y_20002` (che è uguale al caso di @labaggio https://github.com/OCA/l10n-italy/issues/1924#issuecomment-716403065): in odoo dovrà essere tradotta in una fattura con 2 righe, entrambe soggette a ritenuta `RT01`

Caso `ITNREGCM80H30D612D_20003`: in odoo dovrà essere tradotta in una fattura con 1 riga con 2 ritenute (`RT01` e `RT04`)

@marco-marchiori prova a produrre un caso che coinvolga ad esempio la `RT03`

Tutti gli XML di questa issue andranno aggiunti ai test automatici di importazione.

**Comment by marco-marchiori** [comment]
Questo e' un po' un caso di scuola di amministratrice di societa', soggetto IVA per sua attivita', che oltrepassa il limite occasionale di eur 5.000 e subisce la ritenuta INPS dell'11,41% (1/3 di 34,23%).

Caso 4 Alessandra Verdi di Parma
imponibile 10.000.
Ritenuta previdenziale INPS 11,41% su imponibile
Ritenuta fiscale su (10.000 - ritenuta previdenziale).
Ho pero' finora trovato pochi esempi, forse ci sono casistiche piu' frequenti.
Se magari trovate qualche documento di amministratore di societa' con ritenuta inps mandatemelo anonimizzato che lo confrontiamo.

Il sistema ora non riesce a calcolarmi la ritenuta fiscale (l'imponibile non e' in riga), probabilmente l'operatore sarebbe costretto a spaccare gli imponibili.

[ITVRDLSN80C71G337E_20004.xml.txt](https://github.com/OCA/l10n-italy/files/5460722/ITVRDLSN80C71G337E_20004.xml.txt)
[ITVRDLSN80C71G337E_20004.pdf](https://github.com/OCA/l10n-italy/files/5460724/ITVRDLSN80C71G337E_20004.pdf)

**Comment by labaggio** [comment]
Riepilogo quanto da fare dopo la call di questa mattina con @eLBati e @marco-marchiori.

Modulo **l10n_it_fatturapa_in**:
* Creare una mappatura tra i codici ritenuta RT01, RT02, RTXX, ecc. e i wt_types presenti in l10n_it_withholding_tax.
* Cercare la ritenuta, oltre che per CausalePagamento e AliquotaRitenuta anche per TipoRitenuta (considerando il mapping sopra descritto)
* Eliminare la parte relativa alla Cassa Pevidenziale in caso di TC07 (Enasarco) che verrà gestita dal tag DatiRitenuta, fare in modo che non venga nulla in caso di questo tipo di cassa.
* Verificare e gestire il caso di CassaPrevidenziale con Ritenuta SI. `ITRSSGPP80A01C986Y_20002`: Aggiungere una riga di dettaglio con i dati della cassa e assegnare la ritenuta. 
* Aggiungere testa automatici per XML allegati da @marco-marchiori.

Nel caso del xml ITVRDLSN80C71G337E_20004 le due ritenute dovrebbero essere calcolate a cascata.
Si è deciso di non gestire il calcolo, ma di limitarsi ad assegnare le due ritenute sulla stessa riga. 
E' una casistica particolare e rara. Il valore della ritenuta sarà poi modificata a mano in fattura. 
TODO per il futuro: implementare il calcolo guardando come è gestito il calcolo nelle imposte a cascata.

Modulo **l10n_it_fattura_out_wt**:
* Togliere completamente il legame tra ritenuta e cassa. 
* Togliere la generazione del tag Cassa Previdenziale. 
Rimarrà solo l'implementazione del tag DatiRitenuta.

**Comment by eLBati** [comment]
Modifiche in https://github.com/OCA/l10n-italy/pull/1940

**Comment by vincenzoterzulli** [comment]
Per v8 #1970

**Comment by tafaRU** [comment]
Chiudo perché nella `14.0` è già incluso (Rif. https://github.com/OCA/l10n-italy/commit/b274c59b017f9d0f8002560ce756d42f3866fb6a).
