### ISSUE TITLE
Errore in importazione xml fattura fornitore se nei tag PECDestinatario ed Email ci sono spazi finali

### ISSUE THREAD

**Issue by jado95** [OCA/l10n-italy#1932]
Versioni coinvolte: 

 - [x]  8.0 #2008 
 - [ ]  10.0 
 - [X]  12.0 #1966 + #2001
 - [ ] 14.0

Comportamento osservato:
Va in errore sia l'import della fattura fornitore, sia il collegamento a fattura già esistente.

Comportamento atteso:
Import fattura fornitore ignorando gli spazi che precedono o che seguono la Pec.

**Comment by eLBati** [comment]
Puoi fornire un XML che riproduce l'errore?

Poi lo aggiungiamo anche ai test automatici

**Comment by jado95** [comment]
Allego l'xml da qualche parte o scrivo qui il contenuto del file?

**Comment by eLBati** [comment]
L'ideale sarebbe una PR con il test che riproduce l'errore

**Comment by primes2h** [comment]
Immagino di si, ma chiedo per conferma. 
Si verifica anche nella 10.0?

**Comment by jado95** [comment]
@primes2h No, ho appena fatto un paio di test in v10 e il problema non c'è.

**Comment by eLBati** [comment]
@jado95 molto strano. Ti sei fatto un'idea del motivo?

**Comment by jado95** [comment]
@eLBati in effetti è strano. Non so perchè sulla v10 non restituisce l'errore, dovrei controllare il codice.

**Comment by vincenzoterzulli** [comment]
per v8 #2008

**Comment by tafaRU** [comment]
Testato anche sulla `14.0`: il problema non si verifica-
