### ISSUE TITLE
[12.0] column ai.ftpa_withholding_amount does not exist

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#1936]
facendo un update all di un mio db, ottengo errore qui 
https://github.com/OCA/l10n-italy/blob/b063233bc7a6a7c01211f3f7f040e65cba6c36b8/l10n_it_fatturapa_in/migrations/12.0.1.19.0/post-migration.py#L22
 non ho trovato il modulo in cui questo campo è definito

**Comment by sergiocorato** [comment]
C'è https://github.com/OCA/l10n-italy/pull/1914 ma è bloccata per migliorie che sinceramente non ho il tempo di fare

**Comment by scigghia** [comment]
grazie @sergiocorato

**Comment by tafaRU** [comment]
Avevo iniziato ad implementare l'ottimizzazione richiesta su https://github.com/tafaRU/l10n-italy/tree/12.0-fix-l10n_it_fatturapa_in ma non sono più riuscito a trovare del tempo per portarla avanti.

**Comment by tafaRU** [comment]
@sergiocorato https://github.com/sergiocorato/l10n-italy/pull/1 Ho fatto un paio di test in locale, @scigghia hai modo di provarla anche tu?

**Comment by tafaRU** [comment]
@scigghia hai modo di testare la https://github.com/OCA/l10n-italy/pull/1914 aggiornata?

**Comment by tafaRU** [comment]
Chiudo visto che https://github.com/OCA/l10n-italy/pull/1914 è stata mergiata.
