### ISSUE TITLE
Importazione XML nuovo livello di dettaglio *Aliquota 

### ISSUE THREAD

**Issue by labaggio** [OCA/l10n-italy#1941]
Versioni coinvolte:

- [ ] 12.0: https://github.com/OCA/l10n-italy/pull/1944

**Problema riscontrato**
Alcune fatture di acquisto, per esempio carburante e bollette elettriche, indicano righe di dettaglio il cui prezzo ha un numero elevato di decimali.
Aumentare il numero dei decimali, solo per alcune fatture di acquisto, avrebbe un impatto non desiderato sulle fatture di vendita.
Se la company ha prezzi a due decimali, si ritroverebbe tutte le stampe con una serie di zeri, non desiderati, negli ordini o nelle fattura.

Non aumentare i decimali però crea il problema di totali.
Se non uso tutti i decimali che mi vengono indicati nel xml di acquisto, i prezzi vengono arrotondati in fase di importazione e i totali non tornano.

**Implementazione**
Al momento il modulo di importazione della fattura elettronica da la possibilità di scegliere il "livello di dettaglio della e-fattura":

Esistenti:
* massimo: in cui ogni linea dell'xml viene indicata nella fattura di odoo
* minimo: in cui vengono riportate tutte le informazioni dell'xml, ma nessuna linea di dettaglio.

La proposta è aggiungere una nuova modalità (per altro presente, almeno come descrizione, ma commentata, nel modulo fatturapa_in)

* Aliquota: creerà una line di dettaglio della fattura per ogni riga presente nella sezione "DatiRiepilogo", quindi per ogni aliquota.

price_unit: sarà `line.ImponibileImporto`e quantity sempre 1. Il valore è gia arrotondato a due decimali.

Questa modalità farà perdere le descrizioni, che dovranno essere modificate una volta creata la fattura.
Come default nella descrizione del dettaglio riga verrà inserita la scritta "Riepologo Aliquota Iva xx%".

**Comment by tafaRU** [comment]
Chiudo perché la fix è già inclusa nella `14.0`.
