### ISSUE TITLE
fatturazione elettronica nel file xml generato i campi numerici non hanno il formato corretto come da file xsd 

### ISSUE THREAD

**Issue by roccocesetti** [OCA/l10n-italy#1943]
Versioni coinvolte: 8.0-l10n_it_fatturapa-1.6

Passi per riprodurre: estrazione file xml fattura elettronica

Comportamento osservato:tutti i campi numerici non hanno il formato corretto come da file xsd 

Comportamento atteso:

Video/Screenshot (opzionale):
![Schermata del 2020-11-09 03-17-30](https://user-images.githubusercontent.com/4387127/98493224-36563900-223a-11eb-9f17-12eb8b41bf14.png)

**Comment by vincenzoterzulli** [comment]
Ciao @roccocesetti,
Ti chiedo scusa ma non avevo proprio notato questa issue.
Credo di aver già risolto questo problema. 
Potresti cortesemente verificare sul branch 8.0 ufficiale se il problema persiste ancora?
Grazie

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
