### ISSUE TITLE
[l10n_it_fatturapa_in] Problema import per partner con codice fiscale di tipo aziendale

### ISSUE THREAD

**Issue by fredzamoabg** [OCA/l10n-italy#1945]
Versioni coinvolte:
[12.0]
Passi per riprodurre:
fare un import da file che contenga il dato di codice fiscale di tipo aziendale (11 caratteri numerici) e porti alla creazione del partner
- riprodotto anche su runbot

Comportamento osservato:
viene visualizzato messaggio di errore "**Il codice fiscale non sembra corretto.**"
Comportamento atteso:
essendo un codice fiscale di tipo aziendale deve poter essere creato il partner
Video/Screenshot (opzionale):

**Comment by fredzamoabg** [comment]
da ulteriore analisi risulta che la scelta che porta ad avere un partner di tipo aziendale ricade nella valorizazione di campo "Denominazione" nel file xml (mancante nel file utilizzato)... chiudo la issue

**Comment by francesco-ooops** [comment]
@fredzamoabg come hai risolto? dove si trova questo campo denominazione?

**Comment by fredzamoabg** [comment]
@francesco-ooops in effetti più che "campo" è corretto dire "tag". 
al momento non ritrovo lo schema, ma il tag Denominazione lo trovi dentro anagrafica:

ie:

<DatiAnagrafici>
        <Anagrafica>
          <Denominazione>la denominazione dell'azienda</Denominazione>
        </Anagrafica>
</DatiAnagrafici>
