### ISSUE TITLE
Problema di importazione dei messaggi PEC di notifica di "AVVISO DI MANCATA CONSEGNA PER SUP. TEMPO MASSIMO" nell'aggiornamento dello stato di consegna della fattura elettronica

### ISSUE THREAD

**Issue by p-amoruso** [OCA/l10n-italy#1949]
Versioni coinvolte:

- [ ] [8.0] 
- [ ] [10.0] 
- [ ] [12.0]

Passi per riprodurre:

Comportamento osservato:

Il problema riguarda l'importazione dei messaggi PEC di notifica degli stati delle fatture elettroniche. 
Ci sono due messaggi di "AVVISO DI MANCATA CONSEGNA PER SUP. TEMPO MASSIMO" dopo le prime 12 ore dall'invio della fattura elettronica e dopo le 24 ore. 
Questi tipi di messaggi non sono gestiti nell'importazione che effettua il sistema, viene segnalato l'errore poichè si sta cercando di importare un messaggio che non corrisponde ad una fattura elettronica e la configurazione dell'email passa in stato di non confermato, bloccando l'importazione di nuovi messaggi finchè manualmente non si accede alla casella di posta e si impostano questi messaggi come letti.

Comportamento atteso:

Importazione dei messaggi di "AVVISO DI MANCATA CONSEGNA PER SUP. TEMPO MASSIMO" 

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
![photo_2020-11-12_11-32-59](https://user-images.githubusercontent.com/1033131/99052159-e5777500-2598-11eb-821f-5c1a3ccecc53.jpg)

**Comment by eLBati** [comment]
Se ho capito bene quindi questo è un messaggio di Aruba che dice che non è riuscita a consegnare il messaggio PEC a SDI, per problemi loro, giusto?

**Comment by p-amoruso** [comment]
Si, praticamente Aruba (il gestore del mittente in questo caso) notifica che non è stato possibile consegnare il messaggio o per problemi loro o per problemi sul canale SDI del destinatario che magari è risultato irraggiungibile per problemi tecnici.

Dopo 24 ore arriva un nuovo messaggio di "AVVISO DI MANCATA CONSEGNA PER SUP. TEMPO MASSIMO" di notifica in cui si "ritiene" che la spedizione non è andata a buon fine (allego esempio qui sotto).

![image](https://user-images.githubusercontent.com/16465298/99058994-3b9ae700-259e-11eb-94ca-bac2ea02bd08.png)

Successivamente arriva un messaggio di ricevuta di consegna o di notifica di mancata consegna, gestito dal sistema.

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
