### ISSUE TITLE
Liquidazioni IVA: campo debiti precedenti viene riportato senza detrarre i pagamenti

### ISSUE THREAD

**Issue by SimoneVagile** [OCA/l10n-italy#1952]
Versioni coinvolte:
 - [ ] 10.0 https://github.com/OCA/l10n-italy/pull/1946
 - [ ] ~~12.0~~

Passi per riprodurre:
Creare una liquidazione IVA avendo chiuso la precedente con un debito, ma con i movimenti di pagamento presenti sul conto.

Comportamento osservato:
Il campo riporta il debito per intero.

Comportamento atteso:
Il campo dovrebbe riportare il debito residuo (l'importo all'erario della liquidazione precedente - i pagamenti effettuati nel periodo successivo a saldo del precedente).

Video/Screenshot (opzionale):

**Comment by SimoneVagile** [comment]
[https://github.com/OCA/l10n-italy/pull/1946](https://github.com/OCA/l10n-italy/pull/1946)

**Comment by eLBati** [comment]
Sulla 12 non è riproducibile:

![IVA](https://user-images.githubusercontent.com/1033131/100055102-9bf21a00-2e23-11eb-8526-9f2c46d84983.gif)

**Comment by SimoneVagile** [comment]
> Sulla 12 non è riproducibile:
> 
> ![IVA](https://user-images.githubusercontent.com/1033131/100055102-9bf21a00-2e23-11eb-8526-9f2c46d84983.gif)

Nella seconda liquidazione non viene riportato il campo Importo Iva Erario ma il campo Importo a saldo che è a 0,00 [https://github.com/OCA/l10n-italy/blob/12.0/account_vat_period_end_statement/models/account.py#L535](https://github.com/OCA/l10n-italy/blob/12.0/account_vat_period_end_statement/models/account.py#L535)

**Comment by eLBati** [comment]
Infatti, comportamento corretto

**Comment by SimoneVagile** [comment]
No, è errato.

[https://github.com/OCA/l10n-italy/pull/1946#issue-518587978](https://github.com/OCA/l10n-italy/pull/1946#issue-518587978)

**Comment by eLBati** [comment]
Rinnovo la richiesta: potresti fornire un caso d'uso , possibilmente numerico, dove esplciti il comportamento osservato e il comportamento atteso?

Io ho riportato una gif animata dove mostro esattamente  il caso d'uso descritto in questa issue e dove non vedo nulla di sbagliato. Cosa ci vedi di sbagliato?

Se il caso d'uso è diverso, potresti come minimo fare lo stesso (gif animata o screenshots), se non riesci a descriverlo a parole.

Mandare questo commento https://github.com/OCA/l10n-italy/pull/1946#issue-518587978 non serve a nulla, perchè l'ho già letto e non è chiaro:
"un saldo a debito di € 4.000 nel periodo mensile di Maggio viene riportato come debito nel periodo di Giugno": questo ad esempio è falso e l'ho mostrato in https://github.com/OCA/l10n-italy/issues/1952#issuecomment-732675100

"anche se Maggio è partito con un credito verso l'Erario di 1.000": qui "è partito" non so cosa voglia dire.

**Comment by OpenCode** [comment]
> Rinnovo la richiesta: potresti fornire un caso d'uso , possibilmente numerico, dove esplciti il comportamento osservato e il comportamento atteso?
> 
> Io ho riportato una gif animata dove mostro esattamente il caso d'uso descritto in questa issue e dove non vedo nulla di sbagliato. Cosa ci vedi di sbagliato?
> 
> Se il caso d'uso è diverso, potresti come minimo fare lo stesso (gif animata o screenshots), se non riesci a descriverlo a parole.
> 
> Mandare questo commento [#1946 (comment)](https://github.com/OCA/l10n-italy/pull/1946#issue-518587978) non serve a nulla, perchè l'ho già letto e non è chiaro: "un saldo a debito di € 4.000 nel periodo mensile di Maggio viene riportato come debito nel periodo di Giugno": questo ad esempio è falso e l'ho mostrato in [#1952 (comment)](https://github.com/OCA/l10n-italy/issues/1952#issuecomment-732675100)
> 
> "anche se Maggio è partito con un credito verso l'Erario di 1.000": qui "è partito" non so cosa voglia dire.

In virtù della mancata risposta a questo commento, chiudo per inattività
