### ISSUE TITLE
Dichiarazione d'intento [12.0]: mancata registrazione fattura fornitore - superamento plafond errato

### ISSUE THREAD

**Issue by sdn66** [OCA/l10n-italy#1960]
Versioni coinvolte:

 - [ ] 12.0: https://github.com/OCA/l10n-italy/pull/2006

Passi per riprodurre: Inserire il limite azienda a 100.000€; inserire dichiarazione d'intento emessa per 10.000€ al fornitore X - inserire una fattura per il fornitore X di 1.200€. La validazione della fattura restituisce il messaggio "Plafond insufficiente. Valore in eccesso 1.200€

Comportamento osservato: alla validazione restituisce un messaggio anche se è la prima volta che si utilizza la lettera d'intento

Comportamento atteso: Validazione della fattura corretta e inserimento della stessa tra i documenti che consumano il plafond della lettera d'intento

Video/Screenshot (opzionale):

![image](https://user-images.githubusercontent.com/74873609/99913518-70264580-2cf8-11eb-920a-5c21bf29e4e5.png)
![image](https://user-images.githubusercontent.com/74873609/99913661-2722c100-2cf9-11eb-94de-7cf024706bb6.png)
![image](https://user-images.githubusercontent.com/74873609/99913574-b8456800-2cf8-11eb-8dfc-5a90acef818d.png)
![image](https://user-images.githubusercontent.com/74873609/99913585-c6938400-2cf8-11eb-9175-c95ee708391f.png)
![image](https://user-images.githubusercontent.com/74873609/99913540-8b915080-2cf8-11eb-887e-e747a9835348.png)

**Comment by sergiocorato** [comment]
non avevo visto il bug, cmq vedi #2006

**Comment by TheMule71** [comment]
#2006 risolve

**Comment by sdn66** [comment]
Ok. Grazie

**Comment by TheMule71** [comment]
@eLBati Posso chiudere?

**Comment by eLBati** [comment]
direi di sì
