### ISSUE TITLE
Server posta in arrivo marcato come "draft"

### ISSUE THREAD

**Issue by oirad** [OCA/l10n-italy#1972]
**Versioni coinvolte:**

- [ ] v12

**Passi per riprodurre:**

1. Creare un nuovo server posta in ingresso (IMAP) e mettere la spunta su pec
2. Inviare una mail non contenente fattura elettronica all'indirizzo pec in questione
3. Attendere che il cron giri 6 volte

**Comportamento osservato:**

La mail in questione viene letta multiple volte ma mai messa come letta, incrementando il counter `server.pec_error_count` fino a quando non è maggiore di 5 (default del parametro `fetchmail.pec.max.retry`) e il server di posta viene marcato come "draft".

Da quello che vedo nel codice, il cron ogni volta leggerà la mail non contenente la fattura ma non la marcherà come letta (non arriva a linea 71 di `fetchmail.py`):
https://github.com/OCA/l10n-italy/blob/3eb8b3c0fd9ad366ca2eaa0ef510ac7653e6df3d/l10n_it_fatturapa_pec/models/fetchmail.py#L50-L75

Quando il cron di fetchmail è girato 6 volte, il counter degli errori arriva a un numero maggiore di 5 e imposta il server a "draft":
https://github.com/OCA/l10n-italy/blob/3eb8b3c0fd9ad366ca2eaa0ef510ac7653e6df3d/l10n_it_fatturapa_pec/models/fetchmail.py#L119-L131

Inoltre quando si prova a inviare una fattura elettronica, se il server di ricezione è in "draft", le nuove fatture non possono essere inviate:
https://github.com/OCA/l10n-italy/blob/db2245ba766d84735d5fbd3a7c6b4e6f45ad8f4c/l10n_it_fatturapa_pec/models/fatturapa_attachment_out.py#L51-L63

**Comportamento atteso:**

Avere una configurazione che permetta di leggere comunque email che non contengono informazioni relative alla fatturazione elettronica così da non bloccare il processo ogni volta che una mail non relativa a fatture elettroniche viene ricevuta sulla casella pec.

**Comment by tafaRU** [comment]
Chiudo a fronte di https://github.com/OCA/l10n-italy/issues/2316#issuecomment-858707635
