### ISSUE TITLE
Withholding_tax - Dichiarazione ritenuta d'acconto non calcola importo RdA applicato

### ISSUE THREAD

**Issue by account-vr** [OCA/l10n-italy#1982]
Versioni coinvolte: 12

Passi per riprodurre: in una nuova installazione ho configurato il modulo RdA come da specifiche, ho inserito una fattura fornitore con ritenuta d'acconto

Comportamento osservato: il calcolo della RdA è corretto e anche l'importo dovuto e da pagare, mentre nella dichiarazione RdA nella colonna importo RdA applicato l'importo è 0

Comportamento atteso: nella dichiarazione RdA nella colonna importo RdA l'importo dovrebbe essere pari alla ritenuta d'acconto.

Video/Screenshot (opzionale):

**Comment by sergiocorato** [comment]
Hai fatto il pagamento? La RdA è da pagare dopo aver pagato il fornitore.

**Comment by account-vr** [comment]
No, non ancora in quanto il fornitore verrà pagato tra 60 giorni mentre la ritenuta prima.

**Comment by sergiocorato** [comment]
Perchè? https://www.agenziaentrate.gov.it/portale/Schede/Pagamenti/Versamento+modello+F24+ritenute+su+reddito+di+lavoro+autonomo+F24_RIT_RED_LAV_AUT/cosa+F24+RED_LAV_AUT/?page=schedepagamenti

**Comment by account-vr** [comment]
In effetti hai ragione la RdA si paga dopo aver effettuato il pagamento della prestazione.
Grazie Sergio sei stato molto gentile e professionale. Buon lavoro

**Comment by account-vr** [comment]
Ho provato a pagare la prestazione e funziona correttamente. Grazie ancora
