### ISSUE TITLE
[12.0] l10n_it_invoices_data_communication non compatibile con Odoo Enterprise

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#1993]
Il modulo in oggetto dipende dal modulo intrastat_base di OCA, che non è compatibile con il modulo account_intrastat di Odoo Enterprise, quindi su Odoo Enterprise l10n_it_invoices_data_communication non è installabile.

https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_invoices_data_communication/__manifest__.py#L20

Siccome questa dipendenza era nata esclusivamente per avere un campo booleano su res.country, propongo di rimuovere la dipendenza e di creare un campo dedicato, così da rendere disponibile tutta la localizzazione italiana anche ai clienti Enterprise.

 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/1995
 - [ ]  10.0

**Comment by alessandrocamilli** [comment]
@dcorio grazie, sono d'accordo e posso occuparmene io
