### ISSUE TITLE
PIP metapackage outdated; how to update

### ISSUE THREAD

**Issue by Byloth** [OCA/l10n-italy#1996]
Hi @sbidoul and @pedrobaeza.
May I ask you how to trigger the update for [`odoo12-addons-oca-l10n-italy`](https://github.com/OCA/l10n-italy/tree/12.0/setup/_metapackage)?

It hasn't been updated since July 2019: https://pypi.org/project/odoo12-addons-oca-l10n-italy/#history  
Isn't it an automated procedure? Are we missing something?

Thank you.

**Comment by sbidoul** [comment]
Indeed, it seems that the metapackage wheen generation feature has not made it to oca-github-bot.
I created https://github.com/OCA/oca-github-bot/issues/133 to track this, so I'm closing here.

In the meantime you can use `pip install git+https://github.com/OCA/l10n-italy#subdirectory=setup/_metapackage`
