### ISSUE TITLE
[8.0] l10n_it_fatturapa_in: withholding_tax_exclude non viene impostato

### ISSUE THREAD

**Issue by SGiuseppe** [OCA/l10n-italy#2007]
Versioni coinvolte:

- [ ] 8.0

Passi per riprodurre:

Installare il modulo  l10n_it_fatturapa_in ed importare una con ritenuta di acconto e con un prodotto, settato in configurazione->contabilità->prodotto per cassa previdenziale,  avente il campo  withholding_tax_exclude impostato a True 

Comportamento osservato:

Sulla riga della fattura ( relativa al modulo account.invoice.line) viene importato come campo impostato a false anche se nel prodotto è impostato a true.

Comportamento atteso:
Il campo in questione dovrebbe avere il valore True selezionato. Cosa che non avviene.

**Comment by SGiuseppe** [comment]
Un altro comportamento errato, non so se dovuto a questo campo, non viene ricalcolato il campo withhoding_tax_ammount se si imposta in modo differente il campo withholding_tax_exclude. In pratica il valore resta quello importato senza mai cambiare.
Facendo altre verifiche creando manualmente la fattura con fornitore avente impostato la posizione fiscale su 1040(per esempio) si ottengono comportamenti anomali su vari campi. 
1) se si imposta lo stesso prodotto che si è importato e quello di previdenza impostato di default e si preme il bottone "aggiornare" che si trova vicino all'imposta nello specchietto in basso per riassumere i totali, il campo withholding_tax si imposta a "false" sempre vanificando ogni modifica su di esso, con relative conseguenze nella fattura. Inoltre nello specchietto in basso delle ritenute non vengono calcolate in nessun modo, neanche premendo il pulsante "save" e settando withholding_tax a True.

**Comment by vincenzoterzulli** [comment]
> 1. se si imposta lo stesso prodotto che si è importato e quello di previdenza impostato di default e si preme il bottone "aggiornare" che si trova vicino all'imposta nello specchietto in basso per riassumere i totali, il campo withholding_tax si imposta a "false" sempre vanificando ogni modifica su di esso, con relative conseguenze nella fattura. Inoltre nello specchietto in basso delle ritenute non vengono calcolate in nessun modo, neanche premendo il pulsante "save" e settando withholding_tax a True.

Ciao @SGiuseppe questo problema è risolto dalla PR #2015 

Riguardo al problema indicato nella issue non ho ancora avuto modo di verificarlo. Avresti modo di riprovarlo con la PR sopra indicata?
Grazie

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
