### ISSUE TITLE
Fattura elettronica da SDI con spazi nei campi numerici (prezzi, quantità, imposta)

### ISSUE THREAD

**Issue by vincenzoterzulli** [OCA/l10n-italy#2020]
Versioni coinvolte:

- [x] 8.0 #2034 
- [x] 10.0 Non si presenta
- [x] 12.0 Non si presenta
- [x] 14.0

**Passi per riprodurre:**
Caricare una fattura elettronica dal file XML [IT02780790107_11008.xml.zip](https://github.com/OCA/l10n-italy/files/5757066/IT02780790107_11008.xml.zip), che risulta essere valido secondo ADE

![image](https://user-images.githubusercontent.com/16492632/103407123-9e9c0980-4b5d-11eb-8452-05d94d9ffc74.png)

**Comportamento osservato:**
il sistema si blocca

**Comportamento atteso:**
il sistema scarta la fattura elettronica o notifica le incompatibilità

**Comment by primes2h** [comment]
Ho appena provato a caricare l'xml sulla 12.0 da runbot.
Nessun problema, neanche quando viene generata la fattura fornitore.

**Comment by PatosMarco** [comment]
Ho appena provato a caricare l'xml sulla 10.0 e non si riscontrano anomalie.

**Comment by sergiocorato** [comment]
Probabilmente è dovuto all'approccio 'sbrigativo' usato sulla 8.0 [qui](https://github.com/OCA/l10n-italy/blob/9b942f7e4e8869d92c02c376552ec69bc88a4932/l10n_it_fatturapa/bindings/binding.py#L960). Sarebbe da riportare da string a decimal come nelle altre versioni.

**Comment by vincenzoterzulli** [comment]
> Probabilmente è dovuto all'approccio 'sbrigativo' usato sulla 8.0 [qui](https://github.com/OCA/l10n-italy/blob/9b942f7e4e8869d92c02c376552ec69bc88a4932/l10n_it_fatturapa/bindings/binding.py#L960). Sarebbe da riportare da string a decimal come nelle altre versioni.

Ciao @sergiocorato, adottai i tipi string per i campi decimal come soluzione al problema della rimozione della seconda cifra decimale per i campi dei pesi nella fattura elettronica, perché fallivano i test. Ricordi? (es: 10.00 != 10.0) Provai diverse strade ma non riuscii a trovare il modo corretto per ottenere sempre la seconda cifra decimale (anche se zero), quindi alla fine per superare i test, fui costretto a cambiare i tipi nel file XSD seguendo una soluzione proposta l'anno scorso per la v10. Certo non potevo sapere che questo avrebbe generato problemi in presenza di spazi nei campi decimali delle fatture elettroniche ricevute!!

Ad ogni modo, ho seguito il tuo suggerimento e ho fatto una PR. In locale i test vengono superati tutti con successo. Ho pure testato il file XML con spazi e viene importato correttamente. Attendiamo anche i risultati di Travis.

Grazie!

**Comment by vincenzoterzulli** [comment]
Problema risolto. Chiudo la issue
