### ISSUE TITLE
[8.0][12.0] fatture elettroniche in ingresso: campo totale fatture (invoices_total) non presente nella tree view

### ISSUE THREAD

**Issue by vincenzoterzulli** [OCA/l10n-italy#2028]
### Versioni coinvolte:

- [x] 8.0 #2029 
- [x] 10.0 Già presente
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2030
- [ ] 14.0 ?

### Passi per riprodurre:
aprire la tree view delle fatture elettroniche in ingresso

### Comportamento osservato:
manca il totale fatture nella tree, è difficile individuare il giusto file XML necessario non avendo a vista l'importo 

![image](https://user-images.githubusercontent.com/16492632/103555603-d1713500-4eb0-11eb-93b7-638dde7f5429.png)

### Comportamento atteso:
il totale è presente

![image](https://user-images.githubusercontent.com/16492632/103555547-bbfc0b00-4eb0-11eb-944e-5a6bb9e0293c.png)

**Comment by eLBati** [comment]
v12: https://github.com/OCA/l10n-italy/pull/2030
