### ISSUE TITLE
Conversione fattura, contenente riga ritenuta di acconto, in nota credito

### ISSUE THREAD

**Issue by account-vr** [OCA/l10n-italy#2032]
Versioni coinvolte: 12.0

Passi per riprodurre: convertire una fattura, contenente una riga con ritenuta di acconto, in nota credito

Comportamento osservato: la fattura viene convertita ma la colonna relativa la ritenuta di acconto, non viene trasferita e bisogna inserirla manualmente

Comportamento atteso: dovrebbe convertire tutto anche il campo della ritenuta di acconto

Non so se questo comportamento è normale, diciamo che inserirlo manualmente non è un grosso problema, la mia preoccupazione però è in un eventuale storno delle voci, ho l'impressione che le partite rimangano aperte.
Potete per favore verificare.
grazie mille
Vincenzo

**Comment by eLBati** [comment]
Sì probabilmente a quel punto la riconciliazioni sbaglierebbero.
@alessandrocamilli ti è già capitato?

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
