### ISSUE TITLE
Fattura XML con PECDestinatario contenente spazi

### ISSUE THREAD

**Issue by OmniaGit** [OCA/l10n-italy#2037]
Versioni coinvolte: 10.0

Passi per riprodurre:
Importare una fattura XML in cui la sezione seguente contiene degli spazi
<PECDestinatario>fatture@pec.abc.it                        </PECDestinatario>

Comportamento osservato:
All'importazione si ha un errore di email non valida
Comportamento atteso:
La procedura di importazione dovrebbe ignorare gli spazi e tenere in considerazione solo il valore puro
Video/Screenshot (opzionale):

**Comment by primes2h** [comment]
Ciao, è un problema noto e c'è già una issue di tracciamento aperta. #1932.

Chiudo questa issue e aggiorno l'altra la v.10.0.
