### ISSUE TITLE
[12.0] Correzione ereditarietà delle viste di l10n_it_fatturapa legate al partner

### ISSUE THREAD

**Issue by OpenCode** [OCA/l10n-italy#2045]
Versioni coinvolte:

- [X] 12.0 - https://github.com/OCA/l10n-italy/pull/2046 + https://github.com/OCA/l10n-italy/pull/2105
- [ ] 14.0

Passi per riprodurre:

Creare un ambiente in cui sono presenti diverse viste che ereditano quelle di base di res.partner ed eseguire un update all

Comportamento osservato:

Odoo restituisce un errore poiché [qui](https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa/views/partner_view.xml#L47) si fa riferimento al campo `parent.electronic_invoice_subjected` che però nalla vista di base non esiste ma esiste nella vista definita [poco sopra](https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa/views/partner_view.xml#L15).

Comportamento atteso:

Odoo che non si spacca!

**Comment by aleuffre** [comment]
Il problema è stato risolto diversamente (in maniera forse meno pulita ma comunque efficace) durante la migrazione alla v14

https://github.com/OCA/l10n-italy/pull/1984/files#diff-bfbdc26230c07dd7e317d8e72cd1f179a353a4fc0ad128d1e88821a91cf5a133R66-R67

Quindi secondo me si può chiudere

**Comment by tafaRU** [comment]
Grazie @aleuffre! Puoi verificare se la stessa modifica è anche presente sulla `16.0`?

**Comment by aleuffre** [comment]
Verificato! La 16 ha ereditato la fix applicata in fase di migrazione alla 14.

**Comment by tafaRU** [comment]
> Verificato! La 16 ha ereditato la fix applicata in fase di migrazione alla 14.

grazie @aleuffre, ottimo!
