### ISSUE TITLE
Delivery note: Eliminazione fattura in bozza, le righe rimangono nello stato di Invoiced

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2047]
Versioni coinvolte:

- [ ] 12.0

Passi per riprodurre:
- Creazione di un SO con prodotto stoccabile (fatturazione sul consegnato)
- Si valida il picking
- Si genera il DDT validandolo
- Dall'SO si clicca su CREA FATTURA
- La fattura mostra correttamente la riga di commento con i riferimenti al DDT insieme al prodotto consegnato
- Elimino la fattura (è ancora in bozza)
- Dall'SO genero nuovamente la fattura con "CREA FATTURA"

Comportamento osservato:
Nella nuova fattura generata non trovo più la riga con i riferimenti al DDT e nel database comunque non sono sicuro ci siano i collegamenti tra SO-DDT-Fattura
Comportamento atteso:
Se l'SO non viene modificato, quando si va a rigenerare la fattura dall'SO, dopo averla eliminata, la fattura deve essere identica a quella di prima.

Video/Screenshot (opzionale):

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
