### ISSUE TITLE
Delivery note: incompatibilità con modulo sale_invoice_group_method

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2048]
Versioni coinvolte:

- [ ] 12.0

Passi per riprodurre:
- Installare il modulo sale_invoice_group_method per gestire i raggruppamenti degli ordini in fattura
- Si genera un SO
- Si valida il picking
- Viene creato il DDT
- Dall'SO si genera la fattura
Comportamento osservato:
I riferimenti al DDT non appaiono in fattura, ma in generale il collegamento tra SO-DDT-Fattura viene ignorato
Comportamento atteso:
Nell fattura deve apparire la riga di tipo commento che riporti i riferimenti al DDT

Video/Screenshot (opzionale):

**Comment by francesco-ooops** [comment]
@alessandrocamilli che metodo hai impostato in sale_invoice_group_method? come l'hai impostato?

**Comment by andreampiovesana** [comment]
Yes

**Comment by alessandrocamilli** [comment]
@francesco-ooops ho definito un raggruppamento per indirizzo di fatturazione. Comunque a breve rilasceremo un modulo ponte che risolve il problema

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.

**Comment by francesco-ooops** [comment]
Ricordo un paio di giorni di panico per questa issue e mi piacerebbe trovare un modo per evitarli al prossimo

@alessandrocamilli per caso alla fine avevate fatto il modulo ponte?

forse una menzione dell'incompatibilità in known issues/roadmap può tornare utile

**Comment by tafaRU** [comment]
> forse una menzione dell'incompatibilità in known issues/roadmap può tornare utile

ok proponi pure una PR se ritieni opportuno. Grazie.
