### ISSUE TITLE
[12.0] Hide fields to not italy company

### ISSUE THREAD

**Issue by victoralmau** [OCA/l10n-italy#2053]
This is for hiding specific Italian fields when using these modules in a multi-localization DB and being logged in a non-Italian company.

Addon base OCA:

- [ ] `l10n_multi_country` https://github.com/OCA/server-ux/pull/262

It's related to some addons:

- [x] `l10n_it_account` https://github.com/OCA/l10n-italy/pull/2011
- [ ] `l10n_it_account_tax_kind` https://github.com/OCA/l10n-italy/pull/2016
- [ ] `l10n_it_esigibilita_iva` https://github.com/OCA/l10n-italy/pull/2014
- [ ] `l10n_it_fatturapa` https://github.com/OCA/l10n-italy/pull/2021
- [ ] `l10n_it_fatturapa_in` https://github.com/OCA/l10n-italy/pull/2055
- [ ] `l10n_it_fatturapa_out` https://github.com/OCA/l10n-italy/pull/2056
- [ ] `l10n_it_fiscal_document_type` https://github.com/OCA/l10n-italy/pull/2010
- [ ] `l10n_it_fiscal_payment_term` https://github.com/OCA/l10n-italy/pull/2013
- [ ] `l10n_it_fiscalcode` https://github.com/OCA/l10n-italy/pull/2018
- [ ] `l10n_it_ipa` https://github.com/OCA/l10n-italy/pull/2017
- [ ] `l10n_it_rea` https://github.com/OCA/l10n-italy/pull/2019
- [ ] `l10n_it_split_payment` https://github.com/OCA/l10n-italy/pull/2012
- [ ] `l10n_it_withholding_tax` https://github.com/OCA/l10n-italy/pull/2054

@Tecnativa TT27560

**Comment by eLBati** [comment]
I think we should establish the generic way to handle this https://github.com/OCA/l10n-italy/pull/2017#pullrequestreview-561539307 before opening other PRs based on `l10n_it_account.mixin` and similar
