### ISSUE TITLE
Gestione risposte PEC di CONSEGNA o ACCETTAZIONE fatture elettroniche.

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#2057]
Versioni coinvolte:
10.0

Passi per riprodurre:
Configurare due istanze di Odoo che devono utilizzare la stessa PEC per la gestione delle fatture elettroniche (caso reale: gestionale Odoo 10 on-premises e eCommerce Odoo 12 su datacenter) in modo che consultino ognuno una propria copia della casella PEC.

Comportamento osservato:
Il mail server in entrata smette di funzionare quando legge una ricevuta di consegna/accettazione relativa a una fattura sconosciuta (perché emessa dall'altra istanza di Odoo). Errore: "Il messaggio PEC con Message-Id <xxxxxxxxx@pcert.sogei.it> è stato letto ma non elaborato, non è relativo a una e-fattura". Si risolve entrando nella casella e segnando queste mail come lette.

Comportamento atteso:
Qualsiasi email non relativa a fatture elettroniche emesse, viene semplicemente ignorata (come succedeva prima di recenti aggiornamenti) senza provocare l'interruzione del funzionamento del server PEC in ingresso.

**Comment by eLBati** [comment]
Lo scenario descritto non è supportato è personalmente lo sconsiglio vivamente

**Comment by protontrigg3r** [comment]
Ok  (anch'io l'ho fortemente sconsigliato, ma chiaramente non è possibile costringere qualcuno a migrare il gestionale, né rifiutarsi di implementare l'eCommerce, quindi una soluzione la devo necessariamente trovare :\ )

Al netto del particolare scenario, il precedente comportamento, che semplicemente ignorava i messaggi "extra", sembra corretto, perché non si può essere certi che nella PEC non arrivino messaggi "extra" (considerando "extra" tutto ciò che non è relativo alle fatture emesse). Segnalare il problema senza bloccare lo scaricamento della casella, credo sia una soluzione corretta (M2C)

**Comment by rcerrillo2** [comment]
Sono d'accordo con questa issue. Nel nostro caso la banca invia notificazioni allo steso indirizzo del PEC e ogni volta che legge un email di questo tipo il server si sblocca.

Come dice @protontrigg3r e meglio ignorare questi messaggi non relativi alle fatture come se faceva prima.

**Comment by eLBati** [comment]
> meglio ignorare questi messaggi non relativi alle fatture come se faceva prima

Cioè se l'utente riceve una raccomandata, odoo la legge senza avvisarlo?

**Comment by rcerrillo2** [comment]
Avvisa delle email non relativi alle fatture emesse, con questo messaggio di "stato letto ma non elaborato, non è relativo a una e-fattura", però non dovrebbe disattivare il server di ingresso perché non c'e nessun errore

**Comment by sergiocorato** [comment]
Concordo, Odoo legge, avvisa e non disattiva il server.

**Comment by protontrigg3r** [comment]
Esatto, Odoo avvisa ma non disattiva il server.

Non so se siete d'accordo, ma credo sia improbabile che qualcuno usi la PEC dedicata alle fatture elettroniche anche per altri scopi. Di conseguenza la possibilità che arrivi una raccomandata ad un indirizzo PEC mai comunicato a nessuno dovrebbe essere a ridosso dello 0.

**Comment by eLBati** [comment]
> Odoo legge, avvisa e non disattiva il server

Ok per me

**Comment by eLBati** [comment]
> ma credo sia improbabile che qualcuno usi la PEC dedicata alle fatture elettroniche anche per altri scopi

Nonostante sia sconsigliato, molti lo fanno

**Comment by protontrigg3r** [comment]
> Nonostante sia sconsigliato, molti lo fanno

Eh ... immagino. Masochismo puro, dato che hanno già la PEC con cui sono registrati in Camera di Commercio

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
