### ISSUE TITLE
l10n_it_intrastat: campo Paese di pagamento errato

### ISSUE THREAD

**Issue by SimoneVagile** [OCA/l10n-italy#2058]
Versioni coinvolte:
- [ ] 10.0 #2060 
- [ ] 12.0 https://github.com/OCA/l10n-italy/pull/2100

Passi per riprodurre:
Creazione e validazione di una fattura cliente in Contabilità per beni o servizi

Comportamento osservato:
Il campo Paese di pagamento viene valorizzato con il paese del cliente.

Comportamento atteso:
Agenzia delle Entrate, circolare n. 36/E/2010, al punto n. 36:
"Con il termine Paese di pagamento si deve intendere il Paese in cui il corrispettivo entra nella disponibilità del beneficiario".
Il campo Paese di pagamento viene valorizzato con il paese del fornitore (o il paese dove ha sede il conto corrente bancario che viene coinvolto nella transazione oggetto di comunicazione).

**Comment by eLBati** [comment]
Per 12.0: https://github.com/OCA/l10n-italy/pull/2100 plis review
