### ISSUE TITLE
[8.0][l10n_it_ricevute_bancarie] esportazione file anche senza iban

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#206]
nel file di esportazione riba è sufficiente indicare abi e cab per ogni riga.
attualmente è possibile esportare solo in presenza di IBAN

**Comment by zeroincombenze** [comment]
:+1:

**Comment by alessandrocamilli** [comment]
:+1:

**Comment by andrea4ever** [comment]
Issue Fixed with PR #214
