### ISSUE TITLE
[12.0] l10n_it_reverse_charge - non valida fattura fornitore in rc con conto bancario

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2062]
Versioni coinvolte: 

- [ ] 12.0: https://github.com/OCA/l10n-italy/pull/2063
- [ ] 14.0: ?

Passi per riprodurre: Validare una fattura fornitore in rc con un conto bancario specificato.

Comportamento osservato: Odoo riporta un mismatch tra il commercial partner e il proprietario del conto.

Comportamento atteso: Dovrebbe validare la fattura e creare l'autofattura.

Il problema è che l'autofattura parte copiando i dati della fattura originaria, compresa il conto bancario. Nel momento in cui viene cambiato il partner (per mettere la company attuale) viene triggerato l'errore (a questo punto il proprietario del conto è il vecchio fornitore).

**Comment by tafaRU** [comment]
Chiudo perché nella `14.0` la fix è già presente. Rif. https://github.com/OCA/l10n-italy/blob/7f6d25b5e55637ebeb564445ac776a2502cf50bc/l10n_it_reverse_charge/models/account_move.py#L282
