### ISSUE TITLE
Creare DDT da PoS

### ISSUE THREAD

**Issue by c-amara** [OCA/l10n-italy#2066]
Passi per riprodurre: Nessuno 

Comportamento osservato: Impossibile creare DDT da POS

Comportamento atteso: Possibilità di creare DDT da POS

Video/Screenshot (opzionale):

Buongiorno, è possibile aggiungere un modulo per creare DDT da Punto Vendita oltre alla fattura?

**Comment by eLBati** [comment]
Se usi `l10n_it_ddt` puoi andare in
Panoramica magazzino > ordini POS > selezionarlo > azione > DDT da consegne

**Comment by c-amara** [comment]
Si questa procedura l'avevo vista, ma sarebbe molto più veloce creare un DDT allo stesso modo della fattura nel PoS. 
Anche perché così si può automatizzare anche la NON stampa dello scontrino fiscale in caso di DDT e la stampa cartacea del documento stesso.

**Comment by eLBati** [comment]
La stampa diretta da POS sarebbe da sviluppare

**Comment by c-amara** [comment]
È possibile automatizzare questa azione da python?

Panoramica magazzino > ordini POS > selezionarlo > azione > DDT da consegne

**Comment by eLBati** [comment]
```
wizard = self.env["ddt.from.pickings"].with_context(active_ids=PICKING_IDS).create({})
wizard.create_ddt()
```
dove `PICKING_IDS` è la lista di ID dei pickings di cui creare il DDT

**Comment by c-amara** [comment]
Provo e ti aggiorno.... una domanda ulteriore: 

c'è un modo per sapere quando l'ordine pos è stato inviato correttamente?
O da js o da python?
Per ora sto usando un timeout in js che non mi sembra la soluzione ideale.

**Comment by eLBati** [comment]
> c'è un modo per sapere quando l'ordine pos è stato inviato correttamente?

Non ho capito. Ma meglio se vieni su https://discord.gg/FeYcxprGdh , per non andare OT qui

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
