### ISSUE TITLE
[8.0] missing supplier_invoice_number set during invoice import.

### ISSUE THREAD

**Issue by fredzamoabg** [OCA/l10n-italy#2085]
Versioni coinvolte:
[8.0] https://github.com/OCA/l10n-italy/pull/2067

Passi per riprodurre:
importare una fattura elettronica contenente il dato di **FatturaBody.DatiGenerali.DatiGeneraliDocumento.Numero**

Comportamento osservato:
il campo **supplier_invoice_number** non viene valorizzato

Comportamento atteso:
valorizzare il campo **supplier_invoice_number**

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Se coinvolge solo la 8, si può chiudere

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
