### ISSUE TITLE
Fattura elettronica: errore nella gestione degli acconti

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2090]
Versioni coinvolte:

- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2797
- [ ] 14.0

Passi per riprodurre:
- Creo un prodotto ABC immagazzinabile fatturabile alla consegna
- Creo un SO con una riga con il prodotto ABC da 1.000 euro e lo confermo
- NON evado la spedizione
- Dall'SO clicco "CREA FATTURA". Odoo mi chiederà di fare la fattura di anticipo
- Scelgo un anticipo del 20% e valido la fattura di anticipo
- Valido la spedizione dell'SO
- Torno nell'ordine e clicco "CREA FATTURA" scegliendo "righe fatturabili con anticipo dedotto"
- Verrà generata una fattura con 2 righe, una con il totale e una con qta negativa a dedurre la fattura di anticipo
- Clicco su Export E-Fattura

Comportamento osservato:
L'xml generato viene scartato perchè all'interno ha una riga negativa

Comportamento atteso:
L'xml presenti la riga positiva e l'importo negativo

Video/Screenshot (opzionale):

**Comment by PatosMarco** [comment]
il problema si presenta anche sulla versione 10.0

**Comment by TheMule71** [comment]
La 14 non è menzionata perché non affetta o non è stata testata?

**Comment by francesco-ooops** [comment]
testato sulla v14, quantità positiva e importo negativo nell'xml come richiesto

non so valutare però se l'xml generato è corretto, qualcuno può dare un'occhiata? grazie!

**Comment by francescapenso** [comment]
Ho fatto una prova in 14 anche io , confrontando poi xml con alcuni validati sdi inviati da un cliente per servizi. L'xml prodotto con i prodotti stoccabili è come quello per i servizi con righe con quantità positive e importi negativi. Secondo me funziona correttamente. A questo punto però è da riaprire la #2465 che avevo aperto io perchè il bug segnalato era diverso.

**Comment by tafaRU** [comment]
> A questo punto però è da riaprire la #2465 che avevo aperto io perchè il bug segnalato era diverso.

@francescapenso riapri pure, dovresti poterlo fare, fammi sapere in caso contrario.
