### ISSUE TITLE
[12.0] Errore permessi su l10n_it_corrispettivi in multi azienda

### ISSUE THREAD

**Issue by tobesmartcs** [OCA/l10n-italy#2091]
Versioni coinvolte: Odoo 12.0

Passi per riprodurre: Creare più aziende, associare le aziende: azienda 1 (la prima azienda creata), azienda 2 ed azienda 3, associare tutte le aziende all'utente principale (admin), creare un record "Corrispettivo" su Azienda 2 o Azienda 3.

Comportamento osservato: Volendo creare un record "Corrispettivo" su una aziendada Fatturazione -> Clienti -> Corrispettivi, cliccando sul pulsante "Crea" ottengo questo errore:
L'operazione richiesta non può essere completata per questioni di di sicurezza. Si prega di contattare l'amministratore di sistema.

(Tipo documento: Users, Operazione: read) - (Record: [4], Utente: 2)

Comportamento atteso: Schermata di creazione corrispettivo così come avviene per Azienda 1

N.B. per tutte le aziende (Azienda 1, Azienda 2 e Azienda 3) riesco a creare normalmente un record Fattura Cliente senza ottenere errori

**Comment by tafaRU** [comment]
@tobesmartcs mi pare duplicata di https://github.com/OCA/l10n-italy/issues/1712 Puoi verificare e in caso affermativo chiudere questa?

**Comment by tobesmartcs** [comment]
Si sembra duplicata.
