### ISSUE TITLE
Campo INVCONT per fatture intracomunitarie emesse natura N2.1

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#2094]
Versioni coinvolte:
- [ ] 8.0
- [ ] 10.0
- [ ] 11.0
- [x] 12.0 #2096 
- [x] 14.0 #2503 

Passi per riprodurre: emettere una fattura elettronica con inversione contabile a cliente intracomunitario

Comportamento osservato: il campo INVCONT non è compilato

Comportamento atteso: il campo INVCONT è compilato

Video/Screenshot (opzionale): nota: 
```
N2.1 – Operazioni non soggette ad IVA ai sensi degli artt. da 7 a 7-septies del d.P.R. n.
633/72
Il codice N2.1 deve essere inserito, in luogo dell’imposta, per le operazioni non soggette ad imposta
per carenza del requisito di territorialità di cui agli artt. da 7 a 7-septies del d.P.R. n. 633/72 per le
quali è stata emessa la relativa fattura ai sensi dell’articolo 21, comma 6-bis, del medesimo decreto
IVA. Si tratta delle operazioni che confluiscono nel rigo VE34 della dichiarazione annuale IVA.
Relativamente alle operazioni di cui all’articolo 21 comma 6 bis lettera a), dovrà essere inserita la
dicitura “INVCONT” nel campo 2.2.1.16.1<TipoDato> del blocco 2.2.1.16 <AltriDatiGestionali>.
```
[Guida_compilazione-FE_18+12+20.pdf](https://www.agenziaentrate.gov.it/portale/documents/20143/451259/Guida_compilazione-FE_18+12+20.pdf)

**Comment by TheMule71** [comment]
#2503 mi sembra pronta per il merge, che ne dite?

**Comment by eLBati** [comment]
Chiudo quindi
