### ISSUE TITLE
Fatturazione  elettronica nuovo tracciato 1.6 errore per autofatture/reverse charge 

### ISSUE THREAD

**Issue by As400it** [OCA/l10n-italy#2098]
Versioni coinvolte:
12.0 14.0 le altre non so 

Passi per riprodurre:
registrare una fattura passiva per servizi da fornitore intra , generare con reverse charge la fattura attiva e inviarla allo SDI con tipo documento [TD17] integrazione/autofattura per acquisto servizi dall'estero
 
Comportamento osservato:
Scarto da parte dell'agenzia con il seguente errore :
[00473] Per il valore indicato nell'elemento 2.1.1.1 <TipoDocumento> non è ammesso il valore IT nell'elemento 1.2.1.1.1 <IdPaese> Se il TipoDocumento vale TD17 o TD18 o TD19, il soggetto cedente non può essere un soggetto italiano 

Comportamento atteso:
inversione dei partner ovvero l'azienda deve essere il destinatario e il fornitore il cessionario. allego documento dell'ade che a pagina 10 sezione TD17. "Campo cedente/prestatore: dati del prestatore estero con l’indicazione del paese di residenza dello stesso.  Campo cessionario/committente: dati del C/C che effettua l’integrazione o emette l’autofattura." 

[Guida_compilazione-FE_18 12 20.pdf](https://github.com/OCA/l10n-italy/files/5925922/Guida_compilazione-FE_18.12.20.pdf)

Propongo di aggiungere in fiscal.document.type un boolean per indicare che vanno invertiti i cedente cessionario. 

L'invio all'ade di questo tipo di fatture sarà obbligatorio nel 2022  .

**Comment by sergiocorato** [comment]
Hai installato il modulo `l10n_it_fatturapa_out_rc` e seguito le istruzioni?

**Comment by As400it** [comment]
> Hai installato il modulo `l10n_it_fatturapa_out_rc` e seguito le istruzioni?

no, mi mancava. lo testo e chiudo la issue
