### ISSUE TITLE
fattura con BIC indicato, errore "account number must be unique"

### ISSUE THREAD

**Issue by marco-marchiori** [OCA/l10n-italy#2102]
Versioni coinvolte: v12, v10 

Passi per riprodurre:

(testato in runbot v12)
Accounting > Vendors > Electronic Bill > Incoming E-bill files
Comandi Create > Upload
di un file XML con campo BIC valorizzato
(comportamento osservato con una fattura professionista tipo quella allegata)
salva correttamente
> Import

Comportamento osservato:

Segnalazione Account Number must be unique

Comportamento atteso:

importazione della fattura

Video/Screenshot (opzionale):

[ITRSSGPP80A01C986Y_200Y2.xml.txt](https://github.com/OCA/l10n-italy/files/5940121/ITRSSGPP80A01C986Y_200Y2.xml.txt)
![Screenshot from 2021-02-07 22-48-16](https://user-images.githubusercontent.com/31436410/107160857-2402ad00-6999-11eb-9240-3c6724e4d843.png)

**Comment by eLBati** [comment]
Ho provato a importare il file XML allegato, ma non ho ottenuto errori

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
