### ISSUE TITLE
Ritenuta d'acconto non gestibile su fattura cliente con linea vista form

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2104]
Versioni coinvolte:

- [x] 11.0 (risolta in quanto non più supportata)
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2103
- [x] 14.0 #3433 (ad una verifica il bug segnalato non sembra presente)
- [x] 16.0: no

Passi per riprodurre:
- Abilitare la vista form per le righe delle fatture clienti
- Aggiungi riga

Comportamento osservato:
Non è presente il campo per gestire la ritenuta d'acconto
Comportamento atteso:
Il campo della ritenuta d'acconto sia visibile

Video/Screenshot (opzionale):

**Comment by tafaRU** [comment]
> @OCA/local-italy-maintainers non credo debba andare in stale

allora aggiungi la label https://github.com/OCA/l10n-italy/labels/no%20stale :wink:

**Comment by SirAionTech** [comment]
In `16.0` il campo è visibile 
![image](https://github.com/OCA/l10n-italy/assets/143788994/ebedf1f2-2bf7-4a47-8fd6-a5a1f62653e3)
quindi non è coinvolta

**Comment by francesco-ooops** [comment]
@SirAionTech ti posso chiedere una rapida verifica se è necessario per v14?

**Comment by SirAionTech** [comment]
In `14.0` il campo è visibile
![image](https://github.com/OCA/l10n-italy/assets/143788994/43aa2f49-ce41-43f5-b32c-65a67ed69be5)
quindi non è coinvolta

**Comment by francesco-ooops** [comment]
Grazie mille!
