### ISSUE TITLE
[7.0][8.0][9.0] unidecode versio

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/l10n-italy#211]
Nel file .travis.yml è richiesto il package unidecode 0.4.17
Questo package è stato aggiornato alla 0.4.19 su PYPI
C'è un motivo per forzare questa specifica versione?
Io opterei per richiedere unidecode senza versione
PS Il package è usato anche nella repository 'bank-payment'

(en) In .travis.yml is required unidecode 0.4.17 package
The latest version now avaiable on PYPI is 0.4.19.
I would like to use latest version and decalre unidecode without version in .travis.yml
Notice: this package is called by 'bank-payment' too

**Comment by eLBati** [comment]
> C'è un motivo per forzare questa specifica versione?

Che io sappia no.
Se vuoi puoi fare una PR (su 8.0) modificandolo e vediamo subito se travis funziona comunque

**Comment by zeroincombenze** [comment]
Package che richiedono la specifica versione:
/opt/odoo/7.0/l10n-italy/.travis.yml:  - pip install unidecode==0.04.17
/opt/odoo/8.0/l10n-italy/.travis.yml:  - pip install unidecode==0.04.17
/opt/odoo/9.0/l10n-italy/.travis.yml:  - pip install unidecode==0.04.17
/opt/odoo/10.0/l10n-italy/.travis.yml:  - pip install unidecode==0.04.17

Package che non richiedono la specifica versione:
/opt/odoo/7.0/bank-payment/.travis.yml:  - pip install unidecode
/opt/odoo/7.0/account-payment/.travis.yml:  - pip install unidecode
/opt/odoo/8.0/bank-payment/.travis.yml:  - pip install unidecode
/opt/odoo/8.0/account-invoicing/.travis.yml:  - pip install unidecode
/opt/odoo/9.0/bank-payment/.travis.yml:  - pip install unidecode
/opt/odoo/9.0/server-tools/.travis.yml:  - pip install unidecode
/opt/odoo/9.0/account-invoicing/.travis.yml:  - pip install unidecode
/opt/odoo/10.0/bank-payment/.travis.yml:  - pip install unidecode
/opt/odoo/10.0/account-invoicing/.travis.yml:  - pip install unidecode

**Comment by zeroincombenze** [comment]
Ho provato 0.4.19 e passa i test di travis sulla 7.0
Provo con la 8.0, 9.0 e 10.0

**Comment by zeroincombenze** [comment]
Passa i test in tutte le versioni. A mio modesto parere sarebbe da cmabiare la dichiarazione di .travis.yml in l10n-italy
