### ISSUE TITLE
l10n_it_fatturapa - per la generazione dell'XML è necessario l'indirizzo. 

### ISSUE THREAD

**Issue by c-amara** [OCA/l10n-italy#2110]
Versioni coinvolte:
Odoo 12 CE
l10n_it_fatturapa 12.0.2.1.0

Passi per riprodurre:
Installare il modulo: base_address_extended.
Creare un nuovo contatto azienda, inserire tutti i campi necessari e, sempre durante la creazione, abilitare anche i campi fatturazione elettronica inserendo i dati necessari.

Al salvataggio si verifica l'errore!
Succede solo alla creazione; se si inserisce un nuovo contatto senza abilitare la fatturazione elettronica salva normalmente e lo stesso accade se i dati vengono inseriti durante la modifica del contatto.

Comportamento osservato:
Cliente taldeiTali: per la generazione dell'XML è necessario l'indirizzo. 

Comportamento atteso:
Validazione dei campi e salvataggio.

Video/Screenshot (opzionale):

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers teniamo aperto?
