### ISSUE TITLE
Fattura elettronica default TD24 (fattura differita) quando si crea Fattura da DDT

### ISSUE THREAD

**Issue by c-amara** [OCA/l10n-italy#2111]
Versioni coinvolte:

 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/2117

Passi per riprodurre:
Creare Fattura da DDT

Comportamento osservato:
La fattura viene creata con Tipo Fattura TD01

Comportamento atteso:
La fattura dovrebbe avere di default TD24

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
Hai già visto qua https://github.com/OCA/l10n-italy/issues/2072 ?

**Comment by c-amara** [comment]
Si appena visto, è inerente ma non la stessa issue. 
Quando si fatturano dei DDT il campo tipo "fiscal_document_type_id" nella bozza della fattura ora viene impostato di default a "TD01 Fattura" mentre dovrebbe essere impostato di default a "TD24 Fattura Differita", in quanto la fatturazione di DDT sono fatture di merce già consegnate e quindi differita.

**Comment by eLBati** [comment]
Hai fatto un registro per le fatture differite e associato il TD24?

**Comment by c-amara** [comment]
No ne vorrei usare uno unico per entrambe.... sia differite che immediate con la stessa numerazione e cambiare solo il tipo di documento nella fattura elettronica.

**Comment by eLBati** [comment]
Quindi al momento non è possibile.

Volendo implementarla, io procederei così: un nuovo modulo ponte, autoinstallante, dipendente da `l10n_it_ddt` e `l10n_it_fiscal_document_type` che fa override del metodo `action_invoice_create` di `stock.picking.package.preparation` solo per scrivere `TD24` nel campo della fattura `fiscal_document_type_id`

**Comment by c-amara** [comment]
Ciao Lorenzo, grazie per dritta ho scritto questo e sembra funzionare

from odoo import api, fields, models

class StockPickingPackagePreparation(models.Model):
    _inherit = 'stock.picking.package.preparation'
    
    @api.multi
    def action_invoice_create(self):
        invoice_sup = super().action_invoice_create()
        
        doc_type_obj = self.env['fiscal.document.type'].search([('code', '=', 'TD24')])
        invs_obj = self.env['account.invoice'].search([('id', 'in', invoice_sup)])
        
        for inv in invs_obj:
            inv.fiscal_document_type_id = doc_type_obj
        
        return invoice_sup

**Comment by c-amara** [comment]
Accetto consigli!

**Comment by CiroBoxHub** [comment]
Si portebbe implementare in l10n_it_fatturapa_out_ddt

**Comment by c-amara** [comment]
Credo che l'inserimento in un modulo esistente implichi anche lo sviluppo di un'impostazione dove l'utente può scegliere se avere questo comportamento alla creazione delle fatture o meno (nonostante io creda che sia il comportamento giusto da adottare).

**Comment by eLBati** [comment]
@c-amara mi sembra comunque una modifica giusta.
Hai voglia di proporre una PR?
https://www.odoo-italia.org/documentazione/12.0/sviluppo/come_contribuire.html

**Comment by c-amara** [comment]
Sono nuovo di GitHub.... Comunque provo.

**Comment by c-amara** [comment]
Ce l'ho fatta!.. Però c'è un piccolo errore nella guida "come contribuire" 

git clone git@github.com:OCA/l10n-italy.git 

dovrebbe essere 

git clone git@github.com:mio_remote/l10n-italy.git

Mi ha fatto perdere un po' di tempo e non capivo perché non riuscivo ad inviare le modifiche

**Comment by tafaRU** [comment]
> Però c'è un piccolo errore nella guida "come contribuire"

Mi pare di no: il remote del tuo fork viene fatto aggiungere [dopo](https://www.odoo-italia.org/documentazione/12.0/sviluppo/come_contribuire.html#creare-una-pr).

Per proporre correzioni a quella guida puoi fare una PR verso https://github.com/odoo-italia/documentazione/blob/12.0/sviluppo/come_contribuire.rst
