### ISSUE TITLE
[8.0] l10n_it_fatturapa: lo SDI scarta le fatture per campi non conformi alle specifiche

### ISSUE THREAD

**Issue by PatosMarco** [OCA/l10n-italy#2113]
**Versioni coinvolte:**

- [ ]  8.0

**Passi per riprodurre:**

Installare i moduli per la fatturazione elettronica e provare a generare una fattura elettronica.

**Comportamento osservato:**

Il file XML presenta i campi relativi al totale documento, quantità, aliquota iva, prezzo unitario ecc... con un solo decimale se il valore dei decimali è ".00". Questo in seguito al commit che vi riporto che ha agito sul binding.py di fatturapa per risolvere il problema di quelle fatture in ingresso, emesse da Passepartout e contenente degli spazi in quegli stessi campi nominati prima. 

https://github.com/OCA/l10n-italy/commit/ae79fb7e42a0260506b216ad4d94f9d05c9af3c5#diff-a79f5ccf2435903ea7470d49d7c05c77037b4daf8efe86edcfe6b308711701f0

Inserendo un solo decimale, ad esempio per l'aliquota o la quantità, lo SDI rifiuta le fatture.

**Comportamento atteso:**

Possibilità di emettere correttamente le fatture elettroniche di vendita e di poter importare quelle in ingresso anche se presenti degli spazi (vengono accettate dallo SDI).

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
