### ISSUE TITLE
[FIX] l10n_it_intrastat_statement: trasporto non obbligatorio, default per natura transazione

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2120]
**Versioni coinvolte**
- [x] 10: https://github.com/OCA/l10n-italy/pull/2121
- [x] 12: https://github.com/OCA/l10n-italy/pull/2142

**Passi per riprodurre**

0. Configurazione utente:
    In `10.0`: Essere nel gruppo _Accounting and Finance: Adviser_
    In `12.0`: Essere nel gruppo _Show full accounting features_
1. In Accounting > Accounting > Intrastat > Intrastat Statements, creare una dichiarazione
2. Aggiungere una riga nel tab Vendite, Sezione 1

**Comportamento osservato**
Il campo natura transazione è vuoto e obbligatorio.
Il campo trasporto è vuoto e obbligatorio.

**Comportamento atteso**
Il campo natura transazione è valorizzato con il default definito nell'azienda.
Il campo trasporto è vuoto ma non obbligatorio.

**Comment by eLBati** [comment]
@SimoRubi https://github.com/OCA/l10n-italy/pull/2142
