### ISSUE TITLE
[FIX] l10n_it_intrastat_statement: campi facoltativi per sezioni 3 e 4

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2123]
**Versioni coinvolte**
- [x] 10: https://github.com/OCA/l10n-italy/pull/2124 + https://github.com/OCA/l10n-italy/pull/2134/commits/a3e39cd49a8aa6a5f277189bfe51c67ea6a9c7c4
- [x] 12: https://github.com/OCA/l10n-italy/pull/2142

**Passi per riprodurre**

0. Configurazione utente:
    In `10.0`: Essere nel gruppo _Accounting and Finance: Adviser_
    In `12.0`: Essere nel gruppo _Show full accounting features_
1. In Accounting > Accounting > Intrastat > Intrastat Statements, creare una dichiarazione
2. Aggiungere una riga nel tab Cessioni, Sezione 4

**Comportamento osservato**
Il campo Paese di pagamento è obbligatorio

**Comportamento atteso**
Il campo Paese di pagamento è facoltativo.
Nota che il campo è obbligatorio invece per la sezione 3.

**Note**
Le specifiche sono in https://www.adm.gov.it/portale/dogane/operatore/modulistica/elenchi-scambi-intracomunitari-di-beni, allegati XI e XII.

**Comment by tafaRU** [comment]
@SimoRubi dall'elenco di campi che indichi in **Comportamento osservato** mi sembra che siano da eliminare:

Numero fattura
Data fattura
Modalità di erogazione
Modalità di incasso

perché già collegati a https://github.com/OCA/l10n-italy/issues/1880

**Comment by eLBati** [comment]
12.0: https://github.com/OCA/l10n-italy/pull/2142
