### ISSUE TITLE
[8.0] [9.0] [10.0] Annullamento DDT

### ISSUE THREAD

**Issue by OpenCode** [OCA/l10n-italy#213]
Da un'esigenza diretta nasce il bisogno di definire un workflow che permetta, partendo dal ddt, di annullare un ordine. Gli ordini con picking collegati non possono essere annullati. I picking completati non possono essere annullati. Alla luce di ciò ho effettuato delle prove trovando il seguente workflow che pare funzionare per lo scopo che vogliamo raggiungere
- Annullo il DDT (attualmente non è possibile farlo per un DDT done ed ho dovuto forzare)
- Inverto tutti i picking legati al DDT così da far quadrare la situazione del magazzino
- Mediante il procurement group definito sui picking, cerco gli ordini di vendita legati allo stesso procurement group
- Svuoto il campo procuremetn_group_id di sale order per slegare gli ordini di vendita dai procurement group
- Sempre mediante il procurement group cerco i procurement order. Nella tabelle procurement_order svuoto il campo sale_line_id di questi PO così da slegare anche i dettagli dell'ordine

A questo punto ho l'ordine completamente isolato dal flusso di magazzino. Le quantità dei prodotti sono nuovamente quadrati ed è possibile annullare l'ordine.

Potrebbe essere utile, anche in un modulo a sé stante, automatizzare il processo (ovviamente escluso l'annullamento dell'ordine) che dovrebbe essere eseguito manualmente dall'utente interessato.

Qualcuno trova buchi nel mio ragionamento? Avete idee migliori? Suggerimenti? Proposte? Contestazioni?

**Comment by OpenCode** [comment]
Ciao a tutti,

nessuno ha ancora incontrato casistiche che possono essere coperte da questa issue?

**Comment by eLBati** [comment]
Per quanto riguarda la possibilità di annullare l'ordine, farei un modulo a parte, generico, per sale-workflow, indipendentemente dal DDT. Poi il modulo del DDT (o un modulo che lo estende) potrà chiamare i suoi metodi.
Ho fatto una breve ricerca e ho trovato questo
https://github.com/akretion/sale-workflow/tree/8.0-sale-cancel-mrp/sale_cancel_picking
ma non so se funziona

**Comment by dcorio** [comment]
L'annullamento dei picking è stato discusso largamente nelle ml OCA e noi internamente abbiamo fatto tantissime prove.
La conclusione è che, dopo l'introduzione dei quanti, è impossibile cancellare un picking.
L'unica cosa fattibile è il suo revert. Hai clienti di sicuro non piacerà, ma penso sia l'unica strada percorribile.
Quindi, annullare un DDT è possibile, ma facendo il revert dei pickings associati.

**Comment by OpenCode** [comment]
@eLBati Il fine ultimo non è proprio annullare l'ordine ma annullare il DDT e slegarlo dall'ordine in modo che se ne possa emettere, eventualmente, un altro. Potrei essere d'accordo sul fare un modulo che annulla i ddt se ce ne fosse il motivo. ne possiamo discutere.

@dcorio Sì, infatti nella procedura che ho descritto non si parla di cancellare picking ma di invertirli per non vanificare la situazione di magazzino. Non sarà l'utente a farlo ma la procedura lanciata dal ddt.

**Comment by dcorio** [comment]
@OpenCode si, la procedura per me è ok (non ho verificato la parte sul procurement, ma siccome non c'è più workflow sugli ordini potrebbe essere necessario intervenire come dici tu). Mi riferivo ai vari moduli che sulla 7 cancellavano i picking. ciò che ho visto per la 8 non funzionava.

**Comment by OpenCode** [comment]
@dcorio Sì, ce ne eravamo accorti con il porting si stock_cancel :)

**Comment by sergiocorato** [comment]
chiudo per inattività
