### ISSUE TITLE
Descrizione Errata Prodotti quando si crea "DDT da consegne" in l10n_it_ddt da un ordine PoS

### ISSUE THREAD

**Issue by c-amara** [OCA/l10n-italy#2145]
Versioni coinvolte:  l10n_it_ddt 12.0.1.9.0

Passi per riprodurre:
Con Odoo 12 CE
Creare un DDT con:

Panoramica magazzino > ordini POS > selezionarlo > azione > DDT da consegne

Comportamento osservato:
Nella scheda "dettagli" del DDT creato dove sono elencati i Prodotti la descrizione di ognuno è sbagliata in quanto non è riportata la descrizione del prodotto bensì il riferimento all'ordine PoS. La stampa del DDT produce una serie di righe shop/xxxx

Comportamento atteso:
La descrizione dei prodotti deve essere o il titolo del prodotto o la sua descrizione nel template.

Video/Screenshot (opzionale):

**Comment by c-amara** [comment]
Buongiorno, allora il metodo `create_ddt` di `l10n_it_ddt` non ha tutti i torti: 

In effetti la colpevole è la funzione `create_picking` di `pos_order.py` nel modulo `point_of_sale` che inserisce il riferimento alla riga dell'ordine invece che la descrizione o nome del prodotto come avviene alla creazione manuale del prelievo di magazzino.

La riga 903 di `pos_order.py` andrebbe modificata cosi:

`'name': line.product_id.description if line.product_id.description else line.product_id.name,`

**Comment by c-amara** [comment]
[https://github.com/odoo/odoo/issues/67047#issue-819908731](url)

**Comment by c-amara** [comment]
https://github.com/odoo/odoo/issues/67047

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
