### ISSUE TITLE
Unificare i tab della fattura elettronica in fattura

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2165]
**Versioni coinvolte**
- [ ] 12.0

**Passi per riprodurre**
1. Configurare un cliente per la fatturazione elettronica:
    nel form del cliente, tab Fatturazione elettronica, abilitare 'Soggetto a fatturazione elettronica'
2. Creare una fattura per il cliente configurato

**Comportamento osservato**
Vengono mostrati due tab per i dati della fattura elettronica:
![image](https://user-images.githubusercontent.com/32064796/110923750-84cb2f80-8321-11eb-945a-689ea7b0fd51.png)

**Comportamento atteso**
Viene mostrato un solo tab per i dati della fattura elettronica

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers teniamo aperto?
