### ISSUE TITLE
Data registrazione per fatture passive ricevute da xml 

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/l10n-italy#2167]
Miglioramento proposto è di avere una terza opzione in configurazione delle fatturepa in ovvero : 

"**Imposta la data predefinita usata per registrare le fatture fornitore: data della fattura o data ricezione.** "
oltre ad **Data fatture** e **Data Ricezione** aggiungere **Data Fine Mese** .
questa nuova impostazione dovrebbe calcolare data fine mese a partire dalla data fattura. 

in questo modo le fatture verranno registrate tutte a fine mese e si evitano problemi di data e protocollo.  

propongo di farlo su 12.0 e poi le altre versioni

**Comment by marco-marchiori** [comment]
Si. Direi che la proposta di Marco è consentire una terza possibilità che si potrebbe descrivere come:
"ultimo giorno del mese data fattura".
Riflette un caso d'uso frequente: 
1- registro più fatture possibile nel mese che sto chiudendo
2- scelgo l'ultimo giorno del mese per non avere problemi di progressività (fattura registrata il 30 con numero successivo a quella registrata il 31).

Ovviamente nel rendere disponibile questa funzionalità bisognerà, come per le altre dare l'avvertenza che non può automaticamente risolvere tutti i problemi difficilmente catturabili:
- ad esempio usare la data fattura è un modo anche per l'agenzia di approssimare la fatidica "effettuazione
- ad esempio se ricevo dopo il 15 una fattura del mese precedente non la posso comunque registrare 
- il fine anno (lungamente discusso)
- le fatture con data anomala
etc etc

**Comment by eLBati** [comment]
Ok per me
