### ISSUE TITLE
[12] Imposta predefinita inserita in automatico quando si inserisce il prodotto

### ISSUE THREAD

**Issue by andgit71** [OCA/l10n-italy#2176]
Versioni coinvolte: 12

Passi per riprodurre: Fatturazione -> Fornitori -> Fatture -> modifica e poi conferma fattura in bozza

Comportamento osservato: con i moduli di fatturazione elettronica installati, dopo aver importato le fatture dei fornitori, se prima di confermare una fattura si specifica il prodotto di una riga, l'imposta di tale riga cambia prendendo quella di default. Ciò obbliga l'operatore ad annotarsi l'IVA presente nella fattura elettronica per reintrodurla prima di salvare e validare

Comportamento atteso: per le fatture importate, quando si specifica il prodotto di una riga di fattura il campo delle imposte non deve cambiare

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
