### ISSUE TITLE
Intrastat statement: la parte rettifica non viene intestata correttamente

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#2178]
Versioni coinvolte:
- [x] 10.0 #2282 
- [x] 12.0 #2177 
- [x] 14.0 #2599

Passi per riprodurre: esportare una dichiarazione intrastat con la sezione 2: rettifiche

Comportamento osservato: l'intestazione del file ha l'importo della rettifica

Comportamento atteso: l'intestazione del file ha il codice derivato dall'importo della rettifica

Video/Screenshot (opzionale):

**Comment by francesco-ooops** [comment]
@sergiocorato verificata su 14 e 16?

**Comment by francesco-ooops** [comment]
verificata presente nella migrazione 14, chiudo

**Comment by SirAionTech** [comment]
> verificata presente nella migrazione 14, chiudo

Hai linkato #2599 ma dovrebbe essere https://github.com/OCA/l10n-italy/pull/2259

**Comment by francesco-ooops** [comment]
grazie, corretto
