### ISSUE TITLE
[12.0] l10n_it_withholding_tax: WT not printed in pdf

### ISSUE THREAD

**Issue by aleuffre** [OCA/l10n-italy#2185]
Versioni coinvolte:

- [ ] 12.0
Non ho testato altre versioni

Passi per riprodurre: Stampare invoice con ritenute d'acconto in pdf

Comportamento osservato: Nella form della fattura viene correttamente visualizzato il prezzo totale, la ritenuta d'acconto, e il netto da pagare. Tuttavia, nella stampa pdf della fattura viene stampato il prezzo totale, senza ritenuta d'acconto e netto da pagare. Risulta fuorviante.

Comportamento atteso: Stampare anche nella fattura pdf, in maniera analoga alla form view, i campi "withholding_tax_amount" e "net_to_pay". Eventualmente si può aggiungere anche "net_to_pay_residual". Insomma, replicare queste righe:

https://github.com/OCA/l10n-italy/blob/21ec05b2f94dbf94bfce477306ad904b8945e842/l10n_it_withholding_tax/views/account.xml#L49-L58

Posso creare volentieri io una PR per aggiungere i due/tre campi nella fattura pdf. Non so se è meglio aggiungerlo al modulo l10n_it_wirthholding_tax, o creare un altro modulo a parte solo per questo.

**Comment by eLBati** [comment]
@aleuffre grazie della segnalazione. C'era già https://github.com/OCA/l10n-italy/issues/1504 quindi chiudo.
Se vuoi fare le modifiche per la 12, puoi prendere spunto da quella per la 11 https://github.com/OCA/l10n-italy/pull/1543

**Comment by aleuffre** [comment]
Scusami, avevo cercato per vedere se fosse già stato segnalato, ma non avevo trovato l'issue.

Grazie mille per i riferimenti!
