### ISSUE TITLE
Intrastat riflessione per il ricalcolo righe intrastat

### ISSUE THREAD

**Issue by As400it** [OCA/l10n-italy#2188]
il ricalcolo righe intrastat è attivo solo quando la fattura è in draft o send . solo che con l'introduzione della fattura elettronica se ho commesso un errore e la fattura non ha righe intrastat e le voglio ricalcolare però ho già inviato la fattura elettronica mi è quasi impossibile fare il ricalcolo. 

se siete d'accordo consentirei sempre il ricalcolo indipendentemente dallo stato della fattura. Eventualmente condizionarlo in funzione dello stato dichiarazione intrastat. 

versione coinvolta credo tutte .

**Comment by andreampiovesana** [comment]
approvo

**Comment by sergiocorato** [comment]
Concordo, un cliente mi ha chiesto di mettergli un'azione al volo per risolvere il problema.

**Comment by tafaRU** [comment]
Chiudo in favore di https://github.com/OCA/l10n-italy/issues/2731
