### ISSUE TITLE
l10n_it_cental_journal: errore stampa in multicompany

### ISSUE THREAD

**Issue by SimoneVagile** [OCA/l10n-italy#2206]
Versioni coinvolte:

- [x] 10.0 [https://github.com/OCA/l10n-italy/pull/2207](https://github.com/OCA/l10n-italy/pull/2207) (risolta per fine supporto)
- [x] 12.0 (presumo perché il codice è identico) (risolta per fine supporto)
- [ ] 14.0 da verificare
- [ ] 16.0 da verificare

Passi per riprodurre:
Cliente con multicompany.
Stampa libro giornale: Contabilità > Report > Giornale centralizzato
con utente diverso da admin.

Comportamento osservato:
Si ha l'errore:
```
Error to render compiling AST
AccessError: (u'The requested operation cannot be completed due to security restrictions. Please contact your system administrator.\n\n(Document type: account.move.line, Operation: read, Records: xxxxxx,xxxxxx,xxxxxx,xxxxxx,xxxxxx,xxxxxx, User: X)', None)
Template: 1048
Path: /templates/t/t/t[3]/div/table/tbody/t[1]/t[2]
Node: <t t-set="tot_credit" t-value="tot_credit + line.credit"/>

```

Comportamento atteso:
Stampa il report Giornale centralizzato inerente alla company dell'utente.

Video/Screenshot (opzionale):

**Comment by aleuffre** [comment]
Essendo che nessuna PR è stata mergiata a riguardo, credo il problema esista ancora, e dovrebbe esistere anche sulla 14.
