### ISSUE TITLE
Triplo sconto, Troppi caratteri --> fattura scartata dall'SDI

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2213]
Versioni coinvolte:

- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2216

Passi per riprodurre:
- Installare modulo l10n_it_fatturapa_out_triple_discount
- Creare una fattura usando 2 sconti. Il secondo sconto deve essere del 20%
- Esportare fattura elettronica
Comportamento osservato:
- L'SDI non ritiene valida la fattura in quanto il campo "percentuale" all'interno della sezione "ScontiMaggiorazioni" ha troppi caratteri

Comportamento atteso:
- Il campo percentuale dell'xml venga espresso con al massimo 6 caratteri

![image](https://user-images.githubusercontent.com/7657512/114298918-f6c99c80-9ab8-11eb-8d80-54872989d244.png)

Video/Screenshot (opzionale):

**Comment by alessandrocamilli** [comment]
@eLBati @sergiocorato a breve facciamo la PR

**Comment by tafaRU** [comment]
Chiudo perché sulla `14.0` non è ancora presente nessuna PR di migrazione del modulo.
