### ISSUE TITLE
Esportazione in XML fattura con IVA prodotti diversa da IVA al 22% e con note relative a righe di fattura

### ISSUE THREAD

**Issue by mpfoodex** [OCA/l10n-italy#2226]
Versioni coinvolte:

 - [x] 14.0 #2335
 - [x] 12.0 https://github.com/OCA/l10n-italy/issues/2226#issuecomment-883948121

Passi per riprodurre: creare una fattura con iva prodotti diversa da iva al 22% e  con note relative a righe di fattura

Comportamento osservato: viene creato oltre al computo corretto dell'aliquota IVA inserita anche un blocco tag xml di questo tipo <DatiRiepilogo><AliquotaIVA>22.00</AliquotaIVA><ImponibileImporto>0.00</ImponibileImporto><Imposta>0.00</Imposta></DatiRiepilogo> 
all'invio della fattura allo sdi la stessa viene scartata

Comportamento atteso: non deve essere creato il blocco in oggetto. Se si tolgono le linee relative alle note tutto si risolve.

Video/Screenshot (opzionale):

![image](https://user-images.githubusercontent.com/78920082/115293108-35b1bf00-a157-11eb-816f-f084827239c7.png)
![image (1)](https://user-images.githubusercontent.com/78920082/115293126-3b0f0980-a157-11eb-8845-0a5079d2dbc1.png)
![image (2)](https://user-images.githubusercontent.com/78920082/115293131-3e09fa00-a157-11eb-8191-3b7ff34f1e43.png)

**Comment by scigghia** [comment]
in pratica le note in fattura creano un blocco con aliquota iva, quando in realtà non dovrebbe esserci

**Comment by dcorio** [comment]
Il problema quindi è il blocco DatiRiepilogo che non deve essere aggiunto se l'importo è 0?
Il fatto che ci siano righe con importo 0 per le note direi che è ok, siccome è il trucco usato da tutti i software siccome il tracciato non prevede righe di tipo "nota"

**Comment by mpfoodex** [comment]
Si esatto il problema è quello. tanto più che nello specifico guardando il blocco della linea 3 quella appunto delle note l'aliquota sarebbe impostata al 10 non ha proprio senso il blocco datiriepilogo al 22%

**Comment by francescapenso** [comment]
qualche news in merito a questa issue?

**Comment by TheMule71** [comment]
La cosa è stata volutamente introdotta con 377d4c791.

In particolare, https://github.com/OCA/l10n-italy/commit/377d4c7912c9321a780f8cc202f3d499c72b41fb#diff-37f21000647675810006a4ce22da747f3c30d7ff5eb7948f92931e368d8e30d1R219-R226

Questo perché in presenza di note, senza un riepilogo iva corrispondente, lo SdI rifiutava il file.

Sembra che in alcuni casi le note vengano inserite con iva di default, in altri "ereditino" l'IVA dalla riga precedente (?)

Bisognerebbe scoprire le casistiche, prima di intervenire.

Nel frattempo potete disabilitare il comportamento con:
```
diff --git a/l10n_it_fatturapa_out/wizard/efattura.py b/l10n_it_fatturapa_out/wizard/efattura.py
index 7d30bd938..c96780db7 100644
--- a/l10n_it_fatturapa_out/wizard/efattura.py
+++ b/l10n_it_fatturapa_out/wizard/efattura.py
@@ -238,7 +238,7 @@ class EFatturaOut:
                         out[key]["ImponibileImporto"] += line.price_subtotal
                         out[key]["Imposta"] += 0.0
             out.update(out_computed)
-            if there_is_a_note:
+            if False:
                 new_key = "22.00_False"
                 if new_key not in out:
                     out[new_key] = {
```
però non è detto che non smettano di funzionare altre casistiche.

**Comment by francescapenso** [comment]
Ho provato a fare qualche ricerca tra XML di ft ingresso ricevuti per vedere come fanno gli altri. 

Es. 1
![image](https://user-images.githubusercontent.com/19937703/120239149-f601eb00-c25d-11eb-8ed8-9700b40375be.png)
uso di un tag specifico annidato.

Es. 2 mettono delle righe con aliquota iva a 0.0 (sono sicura che questi nell'immagine siano "note" della riga prodotto)
![image](https://user-images.githubusercontent.com/19937703/120239317-4ed18380-c25e-11eb-83fb-5f5f2d58bade.png)

**Comment by TheMule71** [comment]
Puoi controllare se poi nei DatiRiepilogo c'è una stanza relativa all'AliquotaIVA 0.00?


Comunque il problema è a monte. Non so perché le righe note dovrebbero avere le tasse specificate. Sembra sia previsto così:
https://github.com/odoo/odoo/blob/14.0/addons/account/views/account_move_views.xml#L976
notare come alcuni campi come debit e credit siano 'invisible' se la riga è una nota, ma le tasse sono read-only (come se fosse normale che una riga le abbia)


![image](https://user-images.githubusercontent.com/915043/120294275-53ca1d80-c2c6-11eb-8c4f-6c0af4ec32f3.png)

Notare come non erediti le tasse della riga precedente.

Da quello che vedo, le righe note/sezione NON settano exclude_from_invoice_tab=True (perché devono vedersi tra le righe fattura), ma questo interferisce con:

https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L3261

che assegna alla riga le tasse di default della company.

Deduco che tu abbia impostato il 10% come tassa di default invece del 22%.

Se mi confermate che lo SdI vuole una stanza nell'XML col riepilogo per l'aliquota 0.00 allora possiamo semplicemente "forzare" l'aliquota a 0.00 per le righe note/sezione nel produrre l'XML. Se non serve le ignoriamo e basta.

**Comment by francescapenso** [comment]
Ciao, 
si c'è la stanza relativa nell'esempio due 
![image](https://user-images.githubusercontent.com/19937703/120349073-11243780-c2fe-11eb-8e84-1e72ecdcdd6c.png)
Nel primo che invece usano il tag <AltriDatiGestionali> no 

Si io nelle mie invoice uscenti ho impostato 10% come default perchè il cliente tratta materia prima con iva al 10% per la maggiorparte

**Comment by TheMule71** [comment]
Ok, allora potremmo semplicemente ignorare le imposte delle righe note/sezione e fingere sia sempre a zero...

**Comment by francescapenso** [comment]
si direi che è un ottimo modo...cosi smetto di vedere invoice che mi tornano indeitro per errore dell'Ade

**Comment by TheMule71** [comment]
@francescapenso 
Hai modo di provare questo al volo, prima che faccia la PR?

```diff --git a/l10n_it_fatturapa_out/wizard/efattura.py b/l10n_it_fatturapa_out/wizard/efattura.py
index 7d30bd938..e74c9c593 100644
--- a/l10n_it_fatturapa_out/wizard/efattura.py
+++ b/l10n_it_fatturapa_out/wizard/efattura.py
@@ -192,7 +192,6 @@ class EFatturaOut:
         def get_all_taxes(record):
             out = {}
             out_computed = {}
-            there_is_a_note = False
             tax_ids = record.line_ids.filtered(lambda line: line.tax_line_id)
             for tax_id in tax_ids:
                 tax_line_id = tax_id.tax_line_id
@@ -211,11 +210,19 @@ class EFatturaOut:
                         tax_line_id.law_reference, 100
                     )
             for line in record.invoice_line_ids:
-                if (
-                    line.display_type in ("line_section", "line_note")
-                    and not there_is_a_note
-                ):
-                    there_is_a_note = True
+                if ( line.display_type in ("line_section", "line_note")):
+                    # notes and sections
+                    # we ignore line.tax_ids altogether,
+                    # (it is popolated with a default tax usually)
+                    # yet, SdI expects a summary, so we add one if needed
+                    new_key = "00.00_False"
+                    if new_key not in out:
+                        out[new_key] = {
+                            "AliquotaIVA": "00.00",
+                            "ImponibileImporto": 0.00,
+                            "Imposta": 0.00,
+                        }
+                    continue
                 for tax_id in line.tax_ids:
                     aliquota = format_numbers(tax_id.amount)
                     key = "{}_{}".format(aliquota, tax_id.kind_id.code)
@@ -238,14 +245,6 @@ class EFatturaOut:
                         out[key]["ImponibileImporto"] += line.price_subtotal
                         out[key]["Imposta"] += 0.0
             out.update(out_computed)
-            if there_is_a_note:
-                new_key = "22.00_False"
-                if new_key not in out:
-                    out[new_key] = {
-                        "AliquotaIVA": "22.00",
-                        "ImponibileImporto": 0.00,
-                        "Imposta": 0.00,
-                    }
             return list(out.values())
```

**Comment by TheMule71** [comment]
Prima di chiudere la issue, verificare se si applica anche alla 12.0.

**Comment by eLBati** [comment]
Ho provato sulla 12 con una fattura fatta così
![image](https://user-images.githubusercontent.com/1033131/126446524-5528dca3-8e22-44c4-b2b6-315751586d1d.png)
e l'XML generato è valido per SDI
