### ISSUE TITLE
UPD supermerge 14.0 

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2227]
Versioni coinvolte: 14.0 

Passi per riprodurre: avere installato una versione supermerge (nel mio caso. commit 53f0608) eseguire update di tutto il modulo con git pull

Comportamento osservato: alla build i test odoo.sh falliscono perchè i submoduli 10n_it_payment_causali è stato rinominato in 10n_it_payment_reason, e l10n_it_withholding_tax_causali in l10n_it_withholding_tax_reason
Provando prima di fare update a disinstallare questi due moduli, fare update e poi rebuild fallisce cmq tutto. 
Come ultimo tentativo ho provato anche partite da un repo in cui non avevo installato supermerge, installato quello nuovo, importato il db del client si generano cmq errori in fatturapa e non si riesce ad aprire il modulo accounting

**Comment by TheMule71** [comment]
Chiudo in quanto la versione "supermerge" non è OCA.

I moduli sono stati rinominati prima della loro inclusione nel branch 14.0, per cui non è mai esistito per es. l10n_it_causali_pagamento sulla 14.0. La migrazione e il cambio nome al modulo sono contemporanei e vengono supportati nel passaggio dalla 12.0 alla 14.0.

Per altro, anche in quel caso, non basta la semplice migrazione del DB e l'update dei moduli; per quei moduli che cambiano nome bisogna seguire una procedura manuale, illustrata per es. qui:

https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_payment_reason#readme

Siccome sei partita da una versione di sviluppo "vicina" a quella della 12.0 e col vecchio nome, puoi provare ad eseguire la stessa procedura. Stessa cosa per ogni altro modulo che nella passaggio 12.0 -> 14.0 ha cambiato nome.

Io farei così: eseguirei tutte le procedure shell insieme, ovviamente su una copia del db e coi vecchi sorgenti, per i moduli installati che cambiano nome. Poi copio il db in un'installazione "fresca" e faccio l'update dei moduli col -u.  Non escludo ci siano cose da sistemare a mano.
