### ISSUE TITLE
Aliquote, conti  e posizione fiscale per split payment

### ISSUE THREAD

**Issue by CiroBoxHub** [OCA/l10n-italy#2235]
Versioni coinvolte:
- [ ] 12.0
- [ ] 14.0

l10n_it_split_payment

Passi per riprodurre:

Comportamento osservato:
Attualmente le aliquote e i conti per l'uso dello split payment, cosi come la posizione fiscale, sono create manualmente dopo l'installazione del modulo.

Comportamento atteso:
Come discusso in call sviluppo, le aliquote SPL (22, 10, e 4), i conti per lo split e la posizione fiscale, sono aggiunte direttamente all'installazione del modulo.

Video/Screenshot (opzionale):

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
