### ISSUE TITLE
Apertura righe di fattura, mancato ricalcolo imponibile impossibile fatturare - l10n_it_fatturapa

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2237]
Versioni coinvolte: 14.0 - commit l10n_italy 14.0 supermerge c984b40

Passi per riprodurre: attivare l10n_it_fatturapa

Comportamento osservato: all'inserimento di una fattura quando si inseriscono righe di prodotto non è possibile inserirle inlinea ma si apre una finestra in cui scrivere. Quando si aggiornano i dati relativi a costo e quantità prodotto non viene aggiornato l'imponibile con relativo successivo errore di validazione da parte del sistema che non permette nemmeno di salvare. Tale comportamento è tanto più fastidioso quando si parte da un ordine e si vuole cambiare il quantitativo della merce da fatturare.  

Comportamento atteso: corretto calcolo di imponibile e ritorno alla compilazione in linea che è molto più comoda

Video/Screenshot (opzionale): https://drive.google.com/file/d/1NaVjSnePWfd6exwQW1HjbrzLviuMU_CT/view

**Comment by francescapenso** [comment]
risolto temporaneamente commentando le righe di codice che rendono apertura in finestra a parte 
righe da 24 a 30. e tutto funziona correttamente

commentate
<xpath
                    expr="//field[@name='invoice_line_ids']/form"
                    position="attributes"
                >
                    <attribute name="editable" />
                </xpath>

**Comment by eLBati** [comment]
@TheMule71 questa si può chiudere?

**Comment by TheMule71** [comment]
Chiudo in quanto dovrebbe essere risolta nell'attuale 14.0.
