### ISSUE TITLE
l10n_it_fatturapa_in: importazione XML con prezzi con tante cifre decimali

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2242]
**Versioni coinvolte**:

 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2243
 - [x] 14.0 36467a587

**Passi per riprodurre**:

Importare una fatture con righe del tipo
![image](https://user-images.githubusercontent.com/1033131/116104082-7443fe00-a6b0-11eb-809c-ec269a405f9f.png)

**Comportamento osservato**:

Errori del tipo
![image](https://user-images.githubusercontent.com/1033131/116104191-8aea5500-a6b0-11eb-8e1b-03b082505a5d.png)

**Comportamento atteso**:

Importazione senza errori

**Comment by TheMule71** [comment]
Aggiunto 36467a587

Dovrebbe essere chiudibile, no?

**Comment by eLBati** [comment]
sì
