### ISSUE TITLE
[14.0][withholding_tax] Fatture in uscita non calcola la ritenuta d'acconto

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2252]
Versioni coinvolte: #14.0# supermerge commit 2672ea9 

Passi per riprodurre: commentate righe come da PR https://github.com/TheMule71/l10n-italy/pull/6  che davano singleton error. 
Creare una fattura di vendita con WT

Comportamento osservato: Non viene calcolato WT e non viene nemmeno creato tag in e-invoice con ritenuta

Comportamento atteso: calcolo wt in invoice e creazione corretta XML 
Fatto test di importazione fattura di acquisto elettronica con ritenuta applicata e viene caricata e computata correttamente. 

Video/Screenshot (opzionale):
![image](https://user-images.githubusercontent.com/19937703/116512984-3110a780-a8c9-11eb-8fef-8074a79559e7.png)

fattura acquisto correttamente importata 
![image](https://user-images.githubusercontent.com/19937703/116513248-949ad500-a8c9-11eb-8cb9-37cad496eea1.png)

**Comment by francescapenso** [comment]
Fatto test funzionale in V14 con commit  9fabf18 di venerdi 30/04
Calcolo ritenute funziona. 
Mi sono accorta però che manca la parte di gestione di righe contabili e popolamento piano dei conti. 
Fatto test di confronto in V12 su runbot ed effettivamente in V12 vengono compilate le righe delle "dirichiarazioni rda"

**Comment by mpfoodex** [comment]
Ulteriore test funzionale in V14 con commit 9fabf18 di venerdi 30/04
Calcolo ritenute non va a finire in XML fattura elettronica e nemmeno in stampa PDF cortesia.

**Comment by francescapenso** [comment]
Ulteriore test funzionale in V14 con commit 9fabf18 di venerdi 30/04
Calcolo ritenute non va a finire in XML fattura elettronica e nemmeno in stampa PDF cortesia.

**Comment by CiroBoxHub** [comment]
> Ulteriore test funzionale in V14 con commit [9fabf18](https://github.com/OCA/l10n-italy/commit/9fabf182807753bf1652c5422e8b8cbcd2b1ef76) di venerdi 30/04
> Calcolo ritenute non va a finire in XML fattura elettronica e nemmeno in stampa PDF cortesia.

il modulo ponte per l'inserimento delle ritenute in xml è stato preso in carico per il porting. Non era in lista tra i moduli da lavorare.

**Comment by eLBati** [comment]
Per il PDF: https://github.com/OCA/l10n-italy/pull/2260 e https://github.com/OCA/l10n-italy/pull/2193

**Comment by francescapenso** [comment]
> Per il PDF: #2260 e #2193

Ma questo per la 12.0...giusto?

**Comment by francescapenso** [comment]
https://github.com/OCA/l10n-italy/pull/2386  c'è questa pr che è in work in progress
