### ISSUE TITLE
[l10n_it_rea] Unicità codice REA solo per partner attivi

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2256]
**Versioni coinvolte**
- [x] 10.0: https://github.com/OCA/l10n-italy/pull/2257
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2372
- [x] 14.0: #2370

**Passi per riprodurre**

1. Installare il modulo `l10n_it_rea`
2. Creare un partner **test** avente:
    - Codice REA = 123
    - Ufficio Provincia = Roma
3. Archiviare il partner **test**
4. Creare un secondo partner con gli stessi valori

**Comportamento osservato**
Errore: "Il codice REA deve essere unico per azienda!"

**Comportamento atteso**
Nessun errore

**Comment by TheMule71** [comment]
Aggiunto #2370
