### ISSUE TITLE
[12.0] l10n_it_account_balance_report js error

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#2261]
Versioni coinvolte:
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2399 (risolta per termine supporto)
- [ ] 14.0

Passi per riprodurre: visualizzare a video il report di bilancio

Comportamento osservato: vedi errore in video

Comportamento atteso: apre i movimenti contabili del conto

Video/Screenshot (opzionale): 
![errore-report-bilancio](https://user-images.githubusercontent.com/7657311/116805926-096c4a00-ab2a-11eb-8d56-df1b09ffcc50.gif)

**Comment by tafaRU** [comment]
Da verificare se è presente anche sulla `14.0`

**Comment by sergiocorato** [comment]
segnalo che ho difficoltà a replicarlo sempre (in remoto sì, in locale no), forse è collegato al sistema di installazione

**Comment by sergiocorato** [comment]
(però nel video sopra ero in runbot, quindi forse è il mio locale un caso particolare)
