### ISSUE TITLE
FIX l10n_it_fatturapa_in in multi company env where partners are shared between companies

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2264]
Versioni coinvolte:

 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2263
 - [ ] 14.0

Passi per riprodurre:

 - Create 2 companies, without de-selecting company_share_partner configuration field
 - Configure 2 different e-bills creators (e_invoice_user_id field)
 - Load 2 different invoices from the same supplier, 1 for the first company, 1 for the second one

Comportamento osservato:

fatturapa.attachment.in records are created, 2 different partners are created and invoice creation raises "Two distinct partners with VAT number %s or Fiscal Code %s already present in db"

Questo estende lo scenario descritto da @SilvioGregorini su https://github.com/OCA/l10n-italy/pull/1660#issuecomment-592559254 coprendo quindi il caso in cui i fornitori sono condivisi fra le aziende.

**Comment by aleuffre** [comment]
Il codice della MR v12 https://github.com/OCA/l10n-italy/pull/2263/files

è già presente sulla V14

https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L201-L214

https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L223-L231

e anche sulla V16

https://github.com/OCA/l10n-italy/blob/16.0/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L223-L253

Credo l'issue si possa chiudere.

**Comment by tafaRU** [comment]
Grazie 1K, @aleuffre!
