### ISSUE TITLE
l10n_it_account_stamp: Configurazione mancante in multi-company

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2265]
Versioni coinvolte:
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2266
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3442

**Passi per riprodurre**

1. In un DB vuoto installare contabilità italiana e `l10n_it_account_stamp`
2. In Contabilità > Configurazione > Impostazioni, verificare che c'è il prodotto bollo e ha modalità automatica
3. Completare la configurazione del prodotto assegnando l'imposta _IVA debito 22_ dei conti di income/expense
4. Creare un fattura per un prodotto da 100€ e validarla
5. Verificare che il movimento contabile ha delle registrazioni dovute al bollo
5. Abilitare multi-azienda
6. Spostarsi in una nuova azienda e installare piano dei conti ITA
7. Configurare lo stesso prodotto per il bollo, con l'imposta _IVA debito 22_ e altri conti
8. Creare una fattura
9. [opzionale] cliccare sul pulsante "Aggiungi riga bollo"
9. Validarla

**Comportamento osservato**
![image](https://user-images.githubusercontent.com/32064796/116889374-c34bdf00-ac2c-11eb-9456-1a81d4d7a592.png)
A seconda delle configurazioni, si può anche ricevere l'errore:
> È necessario impostare i conti di ricavo e di costo per il prodotto Imposta di bollo 2 euro

**Comportamento atteso**
Validazione della fattura anche nella seconda azienda

**Comment by SirAionTech** [comment]
Non riproduco il problema in `16.0`.
Penso che il problema sia stato corretto già in `14.0` dalla migrazione https://github.com/OCA/l10n-italy/commit/86e6cc744bece079243345dfc50fe75d71d0b1d6 perché nella rinomina del file **invoice.py** in **account_move.py** le righe https://github.com/OCA/l10n-italy/blob/dbc3e2bb4b7a6163d38a1e1f7ae8f19cec359e80/l10n_it_account_stamp/models/invoice.py#L17-L19
sono diventate https://github.com/OCA/l10n-italy/blob/86e6cc744bece079243345dfc50fe75d71d0b1d6/l10n_it_account_stamp/models/account_move.py#L19-L21

**Comment by tafaRU** [comment]
grazie dell'analisi @SirAionTech allora chiudo :+1:
