### ISSUE TITLE
[IMP] l10n_it_fatturapa_in: Errore parlante se manca configurazione del conto

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2267]
Versioni coinvolte:
- [x] 12.0: #2268
- [ ] 14.0

**Passi per riprodurre**
1. Installare `l10n_it_fatturapa_in` con la contabilità italiana
1. In Fatturazione / Configurazione / Impostazioni / Contabilità / Registri, rimuovere il "Conto di costo" dal registro "Fatture fornitore"
2. Importare una fattura elettronica, tipo https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa_in/tests/data/IT05979361218_005.xml

**Comportamento osservato**
![image](https://user-images.githubusercontent.com/32064796/117165800-1a38ec00-adc6-11eb-88fc-9fde7341081d.png)

**Comportamento atteso**
Un errore che indichi come risolvere il problema

**Comment by TheMule71** [comment]
Sulla 14.0:
6e75ad13fb7b83adac6fff370a69137d1ec8b797
3dbe4833e6704d3e4c22ed6de9bbb5010c2f1ebc

**Comment by matteoopenf** [comment]
C’è ancora il problema che viene riaperta?



Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 18 giu 2021, alle ore 16:38, Lorenzo Battistini ***@***.***> ha scritto:
> 
> ﻿
> Reopened #2267.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by eLBati** [comment]
Per la 14 risulta aperta

**Comment by TheMule71** [comment]
In realtà, i commit sono mergiati, per cui basterebbe verificare che il bug non ci sia più...

**Comment by eLBati** [comment]
Ah ok, se i commit sono su 14.0 per me si può anche chiudere

**Comment by aleuffre** [comment]
Dovrebbe essere possibile chiudere questa issue (i commit sono anche su v14 e su v16)
