### ISSUE TITLE
Migliorare la gestione dei documenti correlati

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2270]
Versioni coinvolte:

 - [ ] 12.0
 - [ ] 14.0

Comportamento osservato:
I documenti correlati si possono aggiungere alla fattura, ma non associare alle righe.
Anche abilitando l'editing delle singole righe fattura come form, va aggiunto il documento una riga alla volta, il che può essere scomodo se le righe sono molte.

Comportamento atteso:
Aggiungere il documento alla fattura, e poi tramite un dialog apposito, associarlo alle righe relative.

**Comment by SimoRubi** [comment]
👍🏻 nota che attualmente un documento correlato è associabile solo a una riga fattura:
https://github.com/OCA/l10n-italy/blob/06d991fde536fafd15e702b0cc6936bda026168d/l10n_it_fatturapa/models/account.py#L192
quindi c'è anche da cambiare il tipo di relazione tra i due

**Comment by TheMule71** [comment]
A livello di XML la relazione è dal doc alla linea. Non c'è (a livello di xsd) limititazione sul fatto che due diversi documenti (dello stesso tipo) facciano riferimento alla stessa riga, tuttavia bisognerebbe verificare che lo SdI accetti un siffatto XML.

**Comment by TheMule71** [comment]
La domanda era un po' più specifica, non mi sono spiegato bene.

Immagina documento A (ordine cliente) che fa riferimento alla riga di fattura 1.
Aggiungi documento B (sempre ordine cliente) che fa riferimento alla riga fattura 1.

Questa è una situazione potenzialmente ambigua (a quale documento la riga 1 va associata?) ma fattibile a livello di XML (senza violare lo schema). Mi chiedevo se allo SdI da fastidio la cosa oppure no.
