### ISSUE TITLE
l10n_it_fatturapa_in avoid to create existing IBAN

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2273]
Versioni coinvolte:

 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/2272
 - [ ] 14.0

Passi per riprodurre:

Vedi test di https://github.com/OCA/l10n-italy/pull/2272

**Comment by aleuffre** [comment]
FW alla 14.0 fatto https://github.com/OCA/l10n-italy/commit/ed126f98193d30475b0faab33284db0e84cf21f0

e portato anche sulla 16.0 https://github.com/OCA/l10n-italy/commit/b7ca39fc0a3a51c79df2e7bec1068efae6933a17

Si può chiudere.
