### ISSUE TITLE
[12.0] l10n_it_dichiarazione_intento una volta assegnata manualmente non si può rimuovere

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2275]
Versioni coinvolte:
 - [ ] 12.0
 - [ ] 14.0

Passi per riprodurre:
Assegnare manualmente una lettera d'intento ad una fattura.

Comportamento osservato:
Il campo è read-only, e non si può rimuovere la lettera d'intento. Seleziona manualmente permette solo di aggiungere.

Comportamento atteso:
Se per errore si sceglie una lettera sbagliata dovrebbe essere possibile rimuoverla.

Ho risolto (per prova) togliento il readonly da:
```
                    <field name="dichiarazione_intento_ids" widget="many2many_tags"
                           readonly="1" class="oe_inline oe_link"/>
```

in l10n_it_dichiarazione_intento/views/account_invoice_view.xml

Questo rende i tag eliminabili.  Non so però perché fosse readonly in origine.

**Comment by sdallanora** [comment]
Aggiungo Screenshot 
![image](https://user-images.githubusercontent.com/45040804/117577040-6fd40800-b0e8-11eb-835e-aa13b18a5604.png)

**Comment by TheMule71** [comment]
Chiudo in favore di #3310
