### ISSUE TITLE
FIX l10n_it_fatturapa_in when importing TIN with double "IT"

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2288]
Versioni coinvolte:

 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2287
 - [ ] 14.0

Passi per riprodurre:

Importare il file di test contenuto in https://github.com/OCA/l10n-italy/pull/2287

Comportamento osservato:

The VAT number [...] for partner [...] does not seem to be valid

Comportamento atteso:

Importazione non bloccata

**Comment by aleuffre** [comment]
Reimplementato indipendentemente per la v14 qui: https://github.com/OCA/l10n-italy/pull/3138

e presente anche sulla v16: https://github.com/OCA/l10n-italy/commit/541a46c6916c9c6cb8b772c62bb16cc24d75495f

Si può chiudere.
