### ISSUE TITLE
l10n_it_fatturapa_in better views for DettaglioPagamento in e-bill details

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2291]
Versioni coinvolte:

 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/2290 + https://github.com/OCA/l10n-italy/pull/2433
 - [x] 14.0: #2369

Passi per riprodurre:

Importare una fattura elettronica con dettagli di pagamento

Comportamento osservato:

L'interfaccia per leggerli è scomoda

Comportamento atteso:

L'interfaccia per leggerli è comoda

**Comment by TheMule71** [comment]
Aggiunto #2369
