### ISSUE TITLE
[14.0] l10n_it_fatturapa forward porting delle PR della 12.0

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2296]
(Più altre questioni aperte)
Promemoria (la lista non è esaustiva):

 - [x] #2000 e750558
 - [x] #2097 (impatta più moduli, forse conviene aspettare che siano tutti mergati)
 - [x] #2174 e6e5cf1
 - [x] #2264 794a0e0
 - [x] #2273 c8d6e58

- [x] #2193 riguarda l10n_it_withholding_tax ma la aggiungo qui comunque perché è una dipendenza di fatturapa_in

**Comment by TheMule71** [comment]
Avevo messo solo quelle di l10n_it_fatturapa_in, comunque ha senso anche raggruppare tutte quelle relative a l10n_it_fattura* in generale.

O forse avrebbe senso mettere la lista completa di tutte le issue/patch relative ai moduli portati 14.0, sulla falsa riga di #1905, per avere un'unica task list sulla quale lavorare. Una sorta di meta-issue in modo da non doversi spulciare ogni volta la list delle issue alla ricerca di quelle della 12 che si applicano anche alla 14.

**Comment by TheMule71** [comment]
Aggiungo anche #2287?

**Comment by tafaRU** [comment]
chiudo perché su trattava di una issue di riepilogo
