### ISSUE TITLE
l10n_it_fatturapa_out: prevent to export XML for vendor bills

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2301]
Versioni coinvolte:

 - [ ] 10.0:
 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/2300
 - [x] 14.0 https://github.com/OCA/l10n-italy/pull/2309

Passi per riprodurre:

 - Creare una fattura passiva
 - Cliccare su Azione > Esporta fattura elettronica

Comportamento osservato:

Viene creato l'oggetto `fatturapa.attachment.out` e l'utente rischia quindi poi di inviare a SDI qualcosa che non va inviato

Comportamento atteso:

L'oggetto `fatturapa.attachment.out` non viene creato

**Comment by PatosMarco** [comment]
Anche sulla 10.0
