### ISSUE TITLE
[14.0] l10n_it_fatturapa_out: lost functionality

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2312]
Il commit: https://github.com/OCA/l10n-italy/commit/c5138282dd1f499ac69f3bbea821b78fb4e23172 (poi squashato) ha rimosso la possibilità di raggruppare le fatture per l'invio tramite XML.

Però non sembra che successivamente sia stata reintrodotta.

Il commit originale che introduceva la funzionalità era il https://github.com/OCA/l10n-italy/commit/3f1588ad9425e2b530526b9e05e90e8965690088

**Comment by eLBati** [comment]
La funzionalità si sovrapponeva a una già sviluppata su 12.0 ed è stata portata su 14.0 con https://github.com/OCA/l10n-italy/commit/8dc7ba5876b3f0a3e42b253729330ce144770fb1

**Comment by TheMule71** [comment]
Si infatti c'era un commento per ricordarsi di integrarle. https://github.com/OCA/l10n-italy/commit/3f1588ad9425e2b530526b9e05e90e8965690088#diff-914565354eea6151b103fe044fbc59e9406e4df75dd4143da361a2873a4c246eR161-R162

La funzionalità della 14.0 era quella di raggruppare le fatture alla creazione dell'XML con un bottone apposito. Quella della 12.0 di @robyf70 le raggruppa automaticamente fino a un max preimpostato. Sono sovrapposte nel senso di collisione del codice, ma non sono identiche come funzionalità e una non sostituisce l'altra.

L'idea era combinare le due cose, permettendo la funzionalità di raggruppamento manuale con bottone, ma con chunk di dimensione che sia quella impostata, in modo da poter dire:
- queste 10 fatture mandale singolarmente (bottone di invio singolo); e odoo genera 10 xml;
- queste 115 fatture mandale raggruppate, ma l'impostazione (stile @robyf70) è 25 fatture per xml; odoo genera 5 xml, 4 con 25 fatture ciascuno (rispettando il limite impostato) e l'ultimo con le restanti 15.

Un pratica il codice orginario della 14 era già stato sviluppato con l'integrazione in mente, solo che
```chunk_size = 1000```
fisso invece di considerare partner.max_invoice_in_xml (vd. commento sopra). 
Per quando riguarda la generazione dell'XML, bastava commentare la 163 e scommentare la 162. Ovviamente poi andava aggiunto tutto il resto per la gestione (viste, campi ecc).
