### ISSUE TITLE
[FIX] l10n_it_fatturapa_pec: Segnare tutte le email nel server PEC come lette

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2316]
**Versioni coinvolte**
- [ ] 10.0: https://github.com/OCA/l10n-italy/pull/2317
- [ ] 12.0: ?
- [ ] 14.0: ?

**Passi per riprodurre**

1. Installare `l10n_it_fatturapa_pec`
2. Configurare e abilitare un server di posta per la PEC (flag "Server PEC e-fattura")
3. Indicare dei partner nel campo "Contatti da notificare"
2. Impostare il parametro di sistema 'fetchmail.pec.max.retry' = 10
3. Ricevere una email non relativa e fatture elettroniche nel server di posta configurato

**Comportamento osservato**
Vengono inviate 10 email ai contatti da notificare tutte che indicano l'email ricevuta come 'letta ma non processata'.
Viene anche inviata 1 email che notifica del reset del server di posta.
La mail nel server di posta non è segnata come letta.

**Comportamento atteso**
Viene inviata 1 email ai contatti da notificare che indica l'email ricevuta come 'letta ma non processata'.
Il server di posta è abilitato.
La mail nel server di posta è segnata come letta.

**Comment by eLBati** [comment]
Questo lo vedo molto pericoloso: mi aspetto che pochi leggano la notifica e la PEC si perda.

Il meccanismo attuale è pensato in modo che, chi riceve e legge le notifiche di "PEC letta ma non processata" vada sulla mailbox, la legga e faccia quello che vuole.
Se lo fa prima di "max.retry", il server non viene resettato.

Altrimenti, il server viene resettato e l'utente più sprovveduto se ne accorgerà al momento dell'invio di una fattura elettronica (oppure se un fornitore gli dice che ha inviato una fattura e lui non l'ha ricevuta).

Questo è anche un incentivo a non usare la casella PEC per messaggi che non siano fatture elettroniche, che è ovviamente la situazione ideale.

Non possiamo rischiare che qualcuno riceva una PEC importante e Odoo la legga senza provare in tutti i modi di farlo sapere al destinatario.
Si può anche rischiare che il destinatario chieda i danni.

**Comment by tafaRU** [comment]
Chiudo a fronte di https://github.com/OCA/l10n-italy/issues/2316#issuecomment-858707635
