### ISSUE TITLE
[14]  field Riferimento pagamento valorizzato in modo errato dall'XML 

### ISSUE THREAD

**Issue by AIR-sc** [OCA/l10n-italy#2321]
Versioni coinvolte:
14

Passi per riprodurre:
Importare file xml da fattura fornitori

Comportamento osservato:
Il campo "Numero documento" all'interno del file xml viene valorizzato all'interno del field payment_reference del modulo account.move anziché nel field ref (Ricevimento ricevuta)

Comportamento atteso:
La valorizzazione del field ref (Ricevimento ricevuta) con il valore di "Numero documento" del file xml importato 

Video/Screenshot (opzionale):
![Selection_119](https://user-images.githubusercontent.com/73834302/121375057-b82d5280-c940-11eb-8ee9-49471102fd81.png)

**Comment by SimoRubi** [comment]
Grazie della segnalazione!
Ho provato in runbot della versione 14 (http://3487018-14-0-2a1596.runbot1-2.odoo-community.org/) ma non c'è il menu per caricare le fatture fornitori:
![image](https://user-images.githubusercontent.com/32064796/121377460-a64caf00-c942-11eb-9e01-53c2e436039d.png)
Sicuro di aver installato i moduli mergiati in `14.0`?

Se stai provando il codice di qualche PR ancora aperta (ad esempio sospetto tu abbia il codice di https://github.com/OCA/l10n-italy/pull/1990), sarebbe meglio riportare lì il problema.

**Comment by TheMule71** [comment]
Confermo che l10n_it_fatturapa_in (https://github.com/OCA/l10n-italy/pull/1990) non è stato ancora mergiata qui in OCA. 

Chiudo e ti rispondo di là:
https://github.com/OCA/l10n-italy/pull/1990#issuecomment-857836235

**Comment by TheMule71** [comment]
Segnalo anche https://github.com/OCA/l10n-italy/pull/1990#issuecomment-859566773
