### ISSUE TITLE
[14] l10n_it_fatturapa installazione

### ISSUE THREAD

**Issue by progressify** [OCA/l10n-italy#2324]
# Versioni coinvolte:
odoo 14
l10n_it_fatturapa latest scaricato da questo git

# Passi per riprodurre:
## Comportamento osservato:
In fase di installazione ricevo questo errore:

```
I moduli "ITA - Fattura elettronica - Base" e "Italy - E-invoicing" non sono compatibili.
```

![image](https://user-images.githubusercontent.com/11472632/121556412-255de800-ca14-11eb-9025-39af2cbf8d56.png)

ovviamente il modulo citato nell'errore nella mia installazione non è presente

![image](https://user-images.githubusercontent.com/11472632/121556553-458da700-ca14-11eb-94a9-abc7c0305500.png)

## Comportamento atteso:
Il modulo installato correttamente 😂

**Comment by OpenCode** [comment]
Quello indicato non è un errore. Semplicemente i due moduli non sono compatibili e il sistema avvisa l'utente. In questo caso bisogna scegliere se usare uno OPPURE l'altro.

**Comment by progressify** [comment]
si, ma il secondo, quello che mi dice di non essere compatibile, non è installato.. quindi perchè mi segnala l'errore e non mi completa l'installazione?

**Comment by OpenCode** [comment]
La gestione delle dipendenze e delle (in)compatibilità è completamente gestita dal core di Odoo. Da parte nostra non possiamo farci molto. Ho appena provato in locale e l'errore non me lo dà. Potrebbe essere legato alla specifica build del core che stai usando. In ogni caso il bug va aperto a odoo.

**Comment by TheMule71** [comment]
Stai provando ad installare solo l10n_it_fatturapa o anche altri moduli?

Odoo tenta di installare automaticamente l10n_it_edi se viene richiesta (direttamente o tramite dipendenza) l'installazione di l10n_it. Quindi se contemporaneamente a l10n_it_fatturapa stai provando ad installare l10n_it o un modulo che dipende da quello, odoo inserisce nella lista da installare anche l10n_it_edi.

Se è questo il caso, installa separatamente l10n_it, e poi disinstalla l10n_it_edi. Procedi poi col resto dell'installazione.

**Comment by eLBati** [comment]
Io ho modificato il mio odoo così
```
diff --git a/addons/l10n_it_edi/__manifest__.py b/addons/l10n_it_edi/__manifest__.py
index 0eeaf86967c..b60e88e7e98 100644
--- a/addons/l10n_it_edi/__manifest__.py
+++ b/addons/l10n_it_edi/__manifest__.py
@@ -24,5 +24,5 @@ E-invoice implementation
     'demo': [
         'data/account_invoice_demo.xml',
     ],
-    'auto_install': True,
+    'auto_install': False,
 }
```

**Comment by SimoRubi** [comment]
Grazie della segnalazione!

Il problema esiste quindi lascerei aperta la issue, se ne è dibattuto non poco anche in https://github.com/odoo/odoo/pull/67185, che hanno chiuso ma penso ci sia qualche follow-up ancora aperto da qualche parte.

In locale ho riprodotto con i passi:

1. Creazione nuovo DB specificando:
    - nazione = Italy
    - lingua = Italiano (opzionale)
2. Installazione `l10n_it_fatturapa`

Così ottengo: 
![image](https://user-images.githubusercontent.com/32064796/122362124-28972d80-cf58-11eb-9401-90855e39bd03.png)
ma il modulo `l10n_it_edi` non risulta installato:
![image](https://user-images.githubusercontent.com/32064796/122362254-449acf00-cf58-11eb-86fa-86fecd0c91d3.png)


Per risolvere:

1. Installare `l10n_it`
2. Disinstallare `l10n_it_edi`
3. Installare `l10n_it_fatturapa`

Per poter considerare questa issue _chiusa_, aggiungerei come minimo qualche istruzione nel README di `l10n_it_fatturapa`: https://github.com/OCA/l10n-italy/pull/2332

**Comment by primes2h** [comment]
@SimoRubi 
Una soluzione più pulita potrebbe essere l'utilizzo di questo modulo OCA:

https://github.com/OCA/server-tools/tree/14.0/module_change_auto_install

Non serve neanche installarlo, basta renderlo disponibile in `addons_path` e aggiungere due righe al file di configurazione di Odoo.
Che ne pensi?

**Comment by primes2h** [comment]
Oppure, come dice Pedro (https://github.com/OCA/server-tools/pull/2091#issuecomment-847759123), usare OCB (*).

(*) previa apertura e merge di una apposita PR per `l10n_it_edi`

**Comment by SimoRubi** [comment]
> @SimoRubi
> Una soluzione più pulita potrebbe essere l'utilizzo di questo modulo OCA:
> 
> https://github.com/OCA/server-tools/tree/14.0/module_change_auto_install
> 
> Non serve neanche installarlo, basta renderlo disponibile in `addons_path` e aggiungere due righe al file di configurazione di Odoo.
> Che ne pensi?

Sì più pulita ma penso meno adatta all'utente finale che magari vede Odoo solo da interfaccia e vuole semplicemente installare il modulo senza _sporcarsi troppo le mani_.
Comunque va bene, per me puoi aggiungerla come soluzione alle modifiche di https://github.com/OCA/l10n-italy/pull/2332, una PR è gradita :)

> Oppure, come dice Pedro ([OCA/server-tools#2091 (comment)](https://github.com/OCA/server-tools/pull/2091#issuecomment-847759123)), usare OCB (*).
> 
> (*) previa apertura e merge di una apposita PR per `l10n_it_edi`

Anche questa potrebbe andare bene e la si potrà aggiungere alle istruzioni di https://github.com/OCA/l10n-italy/pull/2332 dopo che la modifica sarà in OCB.

**Comment by primes2h** [comment]
> Sì più pulita ma penso meno adatta all'utente finale che magari vede Odoo solo da interfaccia e vuole semplicemente installare il modulo senza _sporcarsi troppo le mani_.
> Comunque va bene, per me puoi aggiungerla come soluzione alle modifiche di #2332, una PR è gradita :)

Vedo se riesco a prepararla nei prossimi giorni.
 
> > Oppure, come dice Pedro ([OCA/server-tools#2091 (comment)](https://github.com/OCA/server-tools/pull/2091#issuecomment-847759123)), usare OCB (*).
> > (*) previa apertura e merge di una apposita PR per `l10n_it_edi`
> 
> Anche questa potrebbe andare bene e la si potrà aggiungere alle istruzioni di #2332 dopo che la modifica sarà in OCB.

:+1:
