### ISSUE TITLE
Rif dichiarazioni intento ripetute nelle note della fattura

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2328]
Versioni coinvolte:

- [x] 12 ~https://github.com/OCA/l10n-italy/pull/2333~ https://github.com/OCA/l10n-italy/pull/2740
- [x] 14 #3059

Passi per riprodurre:
Creare una fattura con dichiarazione intento collegata.
Validare la fattura, annullarla,riportarla in bozza e validarla nuovamente.

Comportamento osservato:
Nelle note della fattura i riferimenti alla dichiarazione d'intento risultano duplicati

Comportamento atteso:
I riferimenti alla dichiarazione d'intento siano mostrato una volta sola

Video/Screenshot (opzionale):
![image](https://user-images.githubusercontent.com/7657512/121692173-1cc6e980-cac8-11eb-9336-dbffdd9e38f6.png)

**Comment by kobalto** [comment]
Ho provato il modulo versione 12 e confermo lo stesso comportamento.
È prevista una soluzione?

**Comment by alessandrocamilli** [comment]
@kobalto è stata fatta questa PR https://github.com/OCA/l10n-italy/pull/2333

**Comment by alessandrocamilli** [comment]
Problema riscontrato anche sulla 14
