### ISSUE TITLE
[ADD] l10n_it_delivery_note_customer_code

### ISSUE THREAD

**Issue by SimoneVagile** [OCA/l10n-italy#2343]
Versioni coinvolte:
- [ ] 12.0
- [x]  14.0 [https://github.com/OCA/l10n-italy/pull/2344](https://github.com/OCA/l10n-italy/pull/2344)

Descrizione del problema o della funzionalità:
Stampa sulla riga del DDT il codice cliente abbinato al prodotto (vedi modulo `product_supplierinfo_for_customer_picking`)

Comportamento attuale prima di queste PR:
Stampa una colonna 'Product' con il codice prodotto.

Comportamento desiderato dopo queste PR:
Stampa una colonna 'Customer Code' con il codice cliente del prodotto se esiste, altrimenti stampa il codice prodotto di default.

PR modulo `product_supplierinfo_for_customer_picking` [https://github.com/OCA/stock-logistics-workflow/pull/855](https://github.com/OCA/stock-logistics-workflow/pull/855)

**Comment by primes2h** [comment]
@SimoneVagile sai se per caso è coinvolta anche la versione 12.0 ?

**Comment by SimoneVagile** [comment]
> @SimoneVagile sai se per caso è coinvolta anche la versione 12.0 ?

@primes2h è un modulo nuovo fatto per la 14.0, bisognerà fare backporting se lo si vuole nella 12.0

**Comment by primes2h** [comment]
> > @SimoneVagile sai se per caso è coinvolta anche la versione 12.0 ?
> 
> @primes2h è un modulo nuovo fatto per la 14.0, bisognerà fare backporting se lo si vuole nella 12.0

Allora lascio aperta la issue in modo da poter tracciare la cosa.
Grazie.

**Comment by francesco-ooops** [comment]
aggiunta a PR migrazione #2967
