### ISSUE TITLE
Riga di tipo nota in fattura con almeno un'aliquota a 0 produce lo scarto.

### ISSUE THREAD

**Issue by letyf1988** [OCA/l10n-italy#2365]
Versioni coinvolte:
14

Passi per riprodurre:
Emettere una fattura con righe di tipo "note" e altre di cui almeno una con aliquota a 0 

Comportamento osservato:
L'estrapolazione dell'xml inserisce la riga di tipo nota con aliquota a 0 che, non avendo normativa agganciata, produce lo scarto della fattura.
Comportamento atteso:
Le note devono avere sempre l'aliquota al 22 onde evitare la richiesta della normativa
Il metodo da cambiare è get_default_note_tax in efattura.py del modulo l10n_it_fatturapa_out.
Opterei per un'imposta settata da configurazione e non la prima della lista oppure zero.

**Comment by francescapenso** [comment]
anche se si mette l'aliquota al 22 viene prodotto uno scarto. 
Questo cambio di comportamento (aliquota a zero) era stato messo "imitando" il comportamento visto in altri XML prodotti da altri ERP ma evidentemente non va bene. 
Probabilmente bisogna creare delle stanze di "nota". Mi pareva di aver mandato un esempio. Lo ricerco nuovamente

**Comment by francescapenso** [comment]
issue https://github.com/OCA/l10n-italy/issues/2226

**Comment by francescapenso** [comment]
le strade sono due
1) si crea  una stanza dedicata alle note 
2) si aggiunge cosi come sta alla aliquota 0.0 delle note la natura IVA N.1 come nell'esempio messo in issue 2226

**Comment by letyf1988** [comment]
grazie @francescapenso 
Lo scarto con il 22 cosa dice?

**Comment by francescapenso** [comment]
lo vedi qui https://github.com/OCA/l10n-italy/issues/2226#issue-861772731  proprio all'inizio. In paerticolare questo avveniva con cliente che di default ha iva al 10%

**Comment by TheMule71** [comment]
A quale versione si riferisce la issue esattamente?

La stanza con aliquota a zero viene introdotta qui: https://github.com/OCA/l10n-italy/pull/2335/files#diff-37f21000647675810006a4ce22da747f3c30d7ff5eb7948f92931e368d8e30d1R213-R227

nella #2335.

La 14.0 dovrebbe produrre ancora la stanza con l'IVA al 22%. Vd. https://github.com/OCA/l10n-italy/blob/91eac51ddc9c3d93db94e4420899cd80c73083bc/l10n_it_fatturapa_out/wizard/efattura.py#L241-L248

Ho rimosso la get_default_note_tax() nella #2335, giustamente adesso deve sempre essere 0.00 per le note.

**Comment by alessandrocamilli** [comment]
@TheMule71 ho fatto una pr sul tuo branch per come reperire l'imposta per le righe di tipo note.

**Comment by TheMule71** [comment]
Mergiata. Come funzionasse prima, non lo so.
