### ISSUE TITLE
[8.0, 9.0] ddt and lots

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#237]
Looking at the code I understand that you aren't able to specify a lot/serial on the stock.move, since the picking has to be in "ready to transfer" state, but the lot assignation takes place only when you transfer the picking, via the dedicated wizard.

This way you can add "ready to transfer" pickings to the DdT, but you lose the possibility to run the Transfer wizard which was the only way to assign the lots.

Am i doing something wrong?

**Comment by eLBati** [comment]
@dcorio In this case, you should process the picking in the standard way (remember you can at any time create DDT from pickings or add pickings to existing DDT by the wizards 'DDT from pickings' and 'add pickings to DDT').
Then, manually 'set to done' the DDT (with specific button)

**Comment by paolovalier** [comment]
@eLBati that is working for me, thk

**Comment by dcorio** [comment]
@eLBati @paolovalier that was my expected behavior, but it looks like a cannot set a DDT to done if the pickings have been already processed

**Comment by eLBati** [comment]
@dcorio just tried on http://3150026-8-0-f460a2.runbot1.odoo-community.org (base DB): processed a picking, created a DDT from it and set DDT to done

**Comment by dcorio** [comment]
@eLBati my bad... this is probably just the case of v9 then

**Comment by gigidn** [comment]
@dcorio i tried on v9 ...
a) Create a picking whit 2 product and lot/serial
b) Create a DDT from the picking
c) edit the lot number inside the 2 picking
d) confirm the pack

ALL ok the transfer keep the lot number

other test
a) Create a picking whit the same product
b) Create a DDT from the picking
c) back to picking and confirm the transfer whit correct lot number
d) set DDT to done

Can u better explain the problem? tks

**Comment by sergiocorato** [comment]
chiudo per inattività
