### ISSUE TITLE
l10n_it_fatturapa_in valorizzazione del <NumeroCivico> in fase di importazione delle fatture e aggiornamento del Partner

### ISSUE THREAD

**Issue by mktsrl** [OCA/l10n-italy#2375]
Versioni coinvolte:

- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2382
- [x] 14.0: #2383

Passi per riprodurre: Il modulo coinvolto è l10n_it_fatturapa_in per l’importazione delle fatture passive in Odoo 12 CE. Importazione di una fattura con il numero civico impostato nell'apposito nodo dell'XML <NumeroCivico>NN</NumeroCivico>

Comportamento osservato: Il problema rilevato è che in caso la fatture elettroniche abbia l’indirizzo del fornitore (CedentePrestatore) con l’indirizzo suddiviso nei due appositi campi XML “sede.indirizzo” e “sede.numero_civico”, il numero civico non viene trattato ai fini dell’assegnamento all’anagrafica del partner creato in automatico da Odoo

Comportamento atteso: Visualizzazione del numero civico all'interno dell'indirizzo del partner. Concatenare il numero civico (presente nell'apposito nodo dell'XML) al campo Indirizzo in fase di assegnamento al partner Odoo, come nell'esempio di seguito proposto:
********************
addons/l10n_it_fatturapa_in/wizard/wizard_import_fattura.py
 
def getCedPrest(self, cedPrest):
        partner_model = self.env['res.partner']
        partner_id = self.getPartnerBase(cedPrest.DatiAnagrafici)
        no_contact_update = False
        if partner_id:
            no_contact_update = partner_model.browse(partner_id).\
                electronic_invoice_no_contact_update
        fiscalPosModel = self.env['fatturapa.fiscal_position']
        if partner_id and not no_contact_update:
            partner_company_id = partner_model.browse(partner_id).company_id.id
            vals = {
                **# BL, 19/07/2021 - MODIFICA: inserimento NumeroCivico
                # 'street': cedPrest.Sede.Indirizzo,
                'street': str(f"{cedPrest.Sede.Indirizzo} {str(cedPrest.Sede.NumeroCivico)}").strip(),
                # BL, 19/07/2021 - FINE MODIFICA: inserimento NumeroCivico**
                'zip': cedPrest.Sede.CAP,
                'city': cedPrest.Sede.Comune,
                'register': cedPrest.DatiAnagrafici.AlboProfessionale or ''
            }
    .... (omissis)...
************

Video/Screenshot (opzionale):

**Comment by eLBati** [comment]
@mktsrl grazie, vuoi proporre un PR?

**Comment by mktsrl** [comment]
Si, grazie @eLBati ! Dato che sarebbe il mio primo contributo chiedo conferma sulla procedura da seguire:

1. **fork** del repository: **mktsrl/l10n-italy** 
2. caricare le modifiche (che sono quelle che ho indicato nella issue) committandole su un nuovo branch **fix-issues-2375** (issue_id: #2375)
3. Da **mktsrl/l10n-italy**, creare una nuova PULL Request impostando: **base repository** di OCA sulla branch **12.0** e la **head repository** quella relativa al mio spazio su branch **fix-issues-2375**

**Comment by tafaRU** [comment]
@mktsrl quanto scrivi mi sembra sostanzialmente corretto. Puoi comunque fare riferimento a https://www.odoo-italia.org/documentazione/12.0/sviluppo/come_contribuire.html

**Comment by mktsrl** [comment]
Buongiorno @eLBati e @tafaRU,
confermo apertura della PR: https://github.com/OCA/l10n-italy/pull/2382/commits/0700cb7d2ffd090e582f7a00e07c4f7346aeaefe

**Comment by TheMule71** [comment]
#2382

**Comment by TheMule71** [comment]
#2383

**Comment by TheMule71** [comment]
Tasklist completata
