### ISSUE TITLE
Red Transifex

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#238]
See for example
https://travis-ci.org/OCA/l10n-italy/jobs/142348403

Transifex build is failing with

```
File "/home/travis/build/OCA/l10n-italy/account_invoice_sequential_dates/invoice.py", line 27, in action_number
    _('Cannot create invoice!'
ParseError: "Cannot create invoice! Post the invoice with a greater date" while parsing /home/travis/odoo-8.0/addons/sale/sale_demo.xml:427, near
<workflow action="invoice_open" model="account.invoice" ref="test_crm_sale_invoice_2"/>
```

This is because `sale` module, with its demo data, is installed **after** `account_invoice_sequential_dates`. Thus, sale demo data does respect `account_invoice_sequential_dates` constraint, and the error is raised.

**Comment by eLBati** [comment]
I see 2 solutions for the transifex build
 - Install dependencies **before** the modules of the current repo (just like for the tests builds: https://travis-ci.org/OCA/l10n-italy/jobs/142348404#L396)
 - Create a database without demo data

@OCA/core-maintainers what do you think?

**Comment by moylop260** [comment]
+1 `without-demo=all` for transifex builds

**Comment by moylop260** [comment]
Please, could you create a new issue in [MQT](https://github.com/OCA/maintainer-quality-tools/issues/new)

**Comment by yvaucher** [comment]
Agreed, we don't need demo data for translations.

**Comment by eLBati** [comment]
Recent  builds of
https://travis-ci.org/OCA/l10n-italy/branches
are green

@moylop260 is this already fixed?

**Comment by moylop260** [comment]
@eLBati 
The last change that I have created to MQT was https://github.com/OCA/maintainer-quality-tools/pull/340
But I think that is unrelated with this issue

Maybe other change from odoo was the real fix.

This issue is ToDo to me yet... Could you create a issue in MQT, please?

**Comment by eLBati** [comment]
@moylop260 here it is https://github.com/OCA/maintainer-quality-tools/issues/345

**Comment by eLBati** [comment]
Red again
https://travis-ci.org/OCA/l10n-italy/jobs/151819539

**Comment by gurneyalex** [comment]
@sbidoul is this related to the issue for which you recently mass-committed on the OCA repositories?

**Comment by sbidoul** [comment]
@gurneyalex my mass commit simply removed i18n/en.po and did not touch l10n-italy yet.
How could that be related to this particular issue?

**Comment by gurneyalex** [comment]
@sbidoul I was thinking maybe the mass commit (not yet done in l10n-italy) could be a solution (not a cause of the issue). But I think I read the description to fast.

**Comment by eLBati** [comment]
At the moment, transifex build is green
https://travis-ci.org/OCA/l10n-italy/branches
so I close
