### ISSUE TITLE
Bug in "l10n_it_delivery_note_base": modifica campi mittente e destinatario bloccati

### ISSUE THREAD

**Issue by AIR-Banzo** [OCA/l10n-italy#2394]
Versioni coinvolte: Odoo 14

Passi per riprodurre: Creare DDT da un qualunque trasferimento di magazzino

Comportamento osservato: abbiamo notato un bug nel modulo DDT  “l10n_it_delivery_note_base” in cui non è possibile modificare in modo distinto il campo “Mittente” e “Destinatario”, ovvero assegnare manualmente indirizzi diversi. 

Comportamento atteso: possibilità di modificare in modo distinto il campo “Mittente” e “Destinatario”, ovvero assegnare manualmente indirizzi diversi fino alla validazione. Questa possibilità è molto utile per esempio quando si deve emettere un DDT per movimentare merce tra magazzini diversi della stessa azienda.

Video/Screenshot (opzionale):

**Comment by DinamicheAziendali** [comment]
> Versioni coinvolte: Odoo 14
> 
> Passi per riprodurre: Creare DDT da un qualunque trasferimento di magazzino
> 
> Comportamento osservato: abbiamo notato un bug nel modulo DDT “l10n_it_delivery_note_base” in cui non è possibile modificare in modo distinto il campo “Mittente” e “Destinatario”, ovvero assegnare manualmente indirizzi diversi.
> 
> Comportamento atteso: possibilità di modificare in modo distinto il campo “Mittente” e “Destinatario”, ovvero assegnare manualmente indirizzi diversi fino alla validazione. Questa possibilità è molto utile per esempio quando si deve emettere un DDT per movimentare merce tra magazzini diversi della stessa azienda.
> 
> Video/Screenshot (opzionale):

Attenzione il trasferimento di magazzino ovvero picking di odoo base ha un location di partenza e una di destinazione che sono quelle del delivery note. 

adesso immagina dal mag A mando merce al mag B con il trasferimento e quindi movimento le qty e i relativi saldi. 
poi nel delivery note cambio mittente dicendo che è il mag C e destinatario mag zz. avrei un documento non coerente. 

sperando di aver capito la tua segnalazione.

**Comment by AIR-Banzo** [comment]
Grazie per la risposta, faccio un esempio pratico che abbiamo riscontrato.
Un nostro cliente ha la specifica esigenza di un percorso di magazzino in cui viene ordinata merce dal suo e-commerce per essere poi ritirata presso il suo store fisico. In questo caso la merce viene inviata dalla sede principale allo store fisico con creazione di DDT al momento dello scarico Sede e carico sul magazzino store fisico per poi essere ritirata dal cliente presso lo store fisico (vendita da store fisico->vendor location). In questo caso il DDT tra i due differenti magazzini di proprietà del cliente NON riporta dati di mittente e destinatario, ma solo i dati generali dell'azienda. Questo è dovuto dalla tipologia di documento (trasferimento interno) oppure dal fatto che l'azienda mittente e destinataria è la medesima (pur con indirizzi differenti) ? Se dovuto alla tipologia di documento rettifico il "Comportamento atteso" nell'avere la possibilità di avere un form DDT con indicazione mittente e destinatario anche nei casi di Trasferimento Interno tra due magazzini di proprietà. Se vi è un'altra metodologia per ottenere il medesimo output andrebbe comunque bene. La necessità è quella di mantere gli automatismi creati. Grazie ancora per l'attenzione

**Comment by AIR-Banzo** [comment]
Grazie mille per la risposta.

Assolutamente d'accordo con l'analisi, la possibilità di cambiare i campi di spedizione era emersa per gestire alcuni percorsi intricati di magazzino in cui vengono triggerati diversi trasferimenti di merce con necessità di rilasciare DDT nei diversi carichi e scarichi tra magazzini interni fino al  cliente finale. Abbiamo risolto operando sulle operazioni di magazzino, quindi questa ISSUE si può considerare risolta. Posso anche cancellarla nel caso in cui il mio quesito possa confondere la community. 
Grazie ancora per la disponibilità
