### ISSUE TITLE
Odoo12 : Migrate l10n_it_ddt to l10n_it_delivery_note

### ISSUE THREAD

**Issue by yleroux** [OCA/l10n-italy#2395]
Versioni coinvolte: Odoo 12 (prepare upgrade to Odoo 14)

Passi per riprodurre: I have follow the instruction to migrate data. But the command line ./odoo-bin migratel10nItddt –database <nome_database> […] is not possible (unknown command returned by odoo-bin) on odoo.sh.

Comportamento osservato: unknown command returned by odoo-bin

Comportamento atteso: migrate data from ddt to delivery note

Additionnals infos: I have also tried to run the script within odoo shell but I got an issue on PyPDF2.

Thanks for your help

**Comment by SimoRubi** [comment]
Hi, I don't have Odoo sh but managed to reproduce your issue locally and here's how I fixed it, so you can maybe give it a try:

1. Locate your Odoo configuration file, I believe that for Odoo sh it is in `/home/odoo/.config/odoo/odoo.conf`
2. Copy the value of `addons_path` in the configuration file and use it for executing the command
   ```
   ./odoo-bin --addons-path=<addons_path from config file> migratel10nItddt –database <database name> --config /home/odoo/.config/odoo/odoo.conf
   ```

**Comment by yleroux** [comment]
Hi

odoo.conf file is empty on odoo.sh.
Regarding what you suggest the only solution to migrate the data is to have a local system.

I will try it tomorrow.

Thanks

**Comment by tafaRU** [comment]
Reopening in order to improve the README file as discussed on Discord (ref. https://discord.com/channels/753902328494424064/806815905006223411/897022721349812235).
