### ISSUE TITLE
[14] fatturapa_in con allegati pdf

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2398]
Fatture elettroniche entranti con PDF. Il pdf viene preso in carico da odoo ma se si tenda di scaricarlo e aprirlo risulta illeggibile. 

video screen https://drive.google.com/file/d/1WjXFDsmqCo8X8UK2o-KVrMyYqmrngLwk/view non contiene dati personali

**Comment by francescapenso** [comment]
Testato e funzionante

**Comment by eLBati** [comment]
La 12 non mi risulta soffrirne
