### ISSUE TITLE
[IMP] l10n_it_withholding_tax: Istruzioni per il pagamento nel README

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2401]
**Versioni coinvolte**
- [x] : `12.0` (risolta per termine supporto)
- [x] : `14.0`: https://github.com/OCA/l10n-italy/pull/2402
- [x] : `16.0` https://github.com/OCA/l10n-italy/issues/2401#issuecomment-1870083584

Aggiungere al README le istruzioni per completare correttamente il pagamento di una fattura con ritenuta d'acconto.

**Comment by eLBati** [comment]
Per completezza, riporto la issue che migliorerebbe il funzionamento: https://github.com/OCA/l10n-italy/issues/1695

**Comment by SirAionTech** [comment]
Questa è già in `16.0` (https://github.com/OCA/l10n-italy/commit/dd6e8406fa3ed0be86008b00fac5433a6bf1e914) quindi si può chiudere
