### ISSUE TITLE
[7.0] Utilizzo modulo DDT_webkit

### ISSUE THREAD

**Issue by gbonline** [OCA/l10n-italy#241]
Salve
avevo la necessità di stampare un ddt ed ho installato il modulo I10n_it_DDT_webkit.
Questo modulo italiano ha tre dipendenze, che sono : 'report_webkit', 'l10n_it_sale', 'base_headers_webkit'
Il modulo 'base_headers_webkit' installa un header per i report: Base Reports Portrait Header
Che è quello di default nel report DDT.
in questo header Base .... si fa riferimento ad una funzione

`helper.embed_company_logo()`

che non esiste nel modulo report_webkit di Openerp v.7.0, ma è presente a partire dalla v8.0.

Per cui al primo tentativo di stampare un ddt si ha un clamoroso errore che tale metodo non esiste !

Per cui ho cercato a lungo di venirne a capo ed infine ho fatto in modo di usare un altro header nella stampa DDT.

Volevo segnalare questo inconveniente per chi come me si trova alle prime armi col sistema di stampa webkit
Ciao

**Comment by archetipo** [comment]
ciao @gbonline 
In:
**Configurazione  -> Loghi Webkit** , si deve creare un record con "nome_che_vuoi" con il logo che si vuole usare e quindi  associarlo alla company.

Nel caso in cui non si voglia associazre nessuna company al logo, si puo' usare il metodo:

helper.embed_logo_by_name('nome_record_logo')

**Comment by eLBati** [comment]
Chiudo. Se il problema fosse ancora aperto, riaprite. Grazie
