### ISSUE TITLE
l10n_it_dichiarazione_intento: duplicazione dichiarazione di intento di tipo in

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#2415]
Versioni coinvolte:
- [x] 12.0: #2413 
- [ ] 14.0: ~da includere nel porting in corso #2043~ (non è stata inclusa) https://github.com/OCA/l10n-italy/pull/3471
- [ ] 16.0: https://github.com/OCA/l10n-italy/pull/3472

Descrizione del problema o della funzionalità: in caso di duplicazione della dichiarazione d'intento, il valore del campo date_start è un datetime.date, per cui il valore preso come una stringa data risulta in un errore

Comportamento attuale prima di questa PR: la duplicazione non è possibile

Comportamento desiderato dopo questa PR: la duplicazione è possibile

Video/Screenshot (opzionale):

 Traceback (most recent call last):
 `   File "/home/tafaru/dev/envs/odoo12/l10n-italy/l10n_it_dichiarazione_intento/tests/test_dichiarazione_intento.py", line 264, in test_copy_dichiarazione_in
 `     dichiarazione_copy = self.dichiarazione4.copy()
 `   File "/home/tafaru/dev/envs/odoo12/odoo/odoo/models.py", line 4338, in copy
 `     new = self.with_context(lang=None).create(vals)
 `   File "<decorator-gen-201>", line 2, in create
 `   File "/home/tafaru/dev/envs/odoo12/odoo/odoo/api.py", line 440, in _model_create_single
 `     return create(self, arg)
 `   File "/home/tafaru/dev/envs/odoo12/l10n-italy/l10n_it_dichiarazione_intento/models/dichiarazione_intento.py", line 96, in create
 `     values['date_start'], '%Y-%m-%d').strftime('%Y')
 ` TypeError: strptime() argument 1 must be str, not datetime.date

**Comment by aleuffre** [comment]
Aperte PR per v14 e v16

**Comment by tafaRU** [comment]
> Aperte PR per v14 e v16

grazie, le ho aggiunte in descrizione.

**Comment by francesco-ooops** [comment]
@sergiocorato puoi verificare se #3471 risolve?

**Comment by HekkiMelody** [comment]
Sembra che l'errore non ci sia su v14 e v16. Ho chiuso le PR di Forward Porting.

**Comment by sergiocorato** [comment]
Ottimo, chiudo.
