### ISSUE TITLE
[14.0] Errore Stampa registro IVA: Field amount doesn't exist in account.move

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2426]
Versioni coinvolte:

- [ ] 14.0  https://github.com/OCA/l10n-italy/pull/2427

Passi per riprodurre:
Creo una nuova fattura, aggiungo una riga e salvo (senza validare).
Nella sezione journal items vado a cambiare il conto di debito/credito  con un conto di  attività-passività
Comportamento osservato:
Quando stampo il registro IVA che contiene quella fattura  ottengo il seguente messaggio di errore

![oca](https://user-images.githubusercontent.com/43987335/133790101-c86814cc-3a99-443d-8bae-afa189359720.png)

Comportamento atteso:

Generazione della stampa del registro iva senza errore

Video/Screenshot (opzionale):

**Comment by SimoRubi** [comment]
Si può chiudere?

**Comment by matteoopenf** [comment]
> Si può chiudere?
direi di si

**Comment by matteoopenf** [comment]
@SimoneVagile  unica cosa non so come si mette la spunta sull'apertura della PR

**Comment by matteoopenf** [comment]
@SimoneVagile  risolto
