### ISSUE TITLE
[14.0] Pagamento fattura con ritenuta: non viene proposto il netto

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2429]
Versioni coinvolte:

- [ ] 14.0

Passi per riprodurre:
- Creo una fattura con ritenuta:
tot doc 2.440
ritenuta 400
Netto a pagare 2.040
- Clicco su "Registra pagamento"

Comportamento osservato:
- Nel wizard l'importo da pagare proposto è : 2.440

Comportamento atteso:
- Nel wizard l'importo da pagare deve essere : 2.040

Video/Screenshot (opzionale):
![image](https://user-images.githubusercontent.com/7657512/133828836-d7d4fd43-e3f0-4385-a74d-d9551f1791e5.png)
![image](https://user-images.githubusercontent.com/7657512/133828929-34d5784e-187a-4320-a3ca-5cb39e3accab.png)

**Comment by eLBati** [comment]
Chiudo in favore di https://github.com/OCA/l10n-italy/issues/1695
