### ISSUE TITLE
[FIX] l10n_it_account: Correzione importo detraibile per imposte non detraibili

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2431]
**Versioni coinvolte**
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/2432

**Passi per riprodurre**
1. Installare `account_vat_period_end_statement`
2. Configurare un'imposta non detraibile, ad esempio:
    ![image](https://user-images.githubusercontent.com/32064796/134310274-8204f570-8392-4650-b501-ce133504d4b4.png)
3. Creare una fattura fornitore che contenga l'imposta creata e confermarla, ad esempio:
    ![image](https://user-images.githubusercontent.com/32064796/134310482-c0bbc772-4a77-45fe-81b4-5b279df801a3.png)
    i movimenti contabili saranno quindi:
    ![image](https://user-images.githubusercontent.com/32064796/134310600-b7bad45c-31a8-4e74-ad8b-694dbc7c220f.png)
4. In Fatturazione > Contabilità > Liquidazioni IVA, stampare la liquidazione per il periodo contenente la fattura creata

**Comportamento osservato**
Per l'imposta creata, l'importo detraibile e l'importo non detraibile corrispondono:
![image](https://user-images.githubusercontent.com/32064796/134311649-b55f7e5d-1f2a-44a8-aaa4-5d710d7a6e35.png)

**Comportamento atteso**
Per l'imposta creata, l'importo detraibile è 0:
![image](https://user-images.githubusercontent.com/32064796/134311247-d496904d-5eb0-4f7d-9498-44525bb1dd2b.png)

**Comment by eLBati** [comment]
@SimoRubi sai mica se la 12 ne soffre?

**Comment by SimoRubi** [comment]
> @SimoRubi sai mica se la 12 ne soffre?

Non lo so

**Comment by monen17** [comment]
> @SimoRubi sai mica se la 12 ne soffre?

Non ne soffre: la liquidazione risulta essere già corretta
![image](https://user-images.githubusercontent.com/46226165/145454259-b2ae8dad-4c47-4711-bb03-e34eb3263fd0.png)
