### ISSUE TITLE
[12.0] l10n_it_dichiarazione_intento: sforamento limite verso il basso

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2439]
Versioni coinvolte:
- [x]  12.0 (risolta per termine supporto)
- [ ] 14.0 (?)
- [ ] 16.0 (?)

Passi per riprodurre:
Importare da XML una nota di credito di un fornitore, relativa ad una fattura con riferimento ad una dichiarazione di intento.

Comportamento osservato:
Se manca la fattura originaria, e non c'è altro documento appoggiato sulla stessa dichiarazione (usato 0), viene visualizzato l'errore plafond insufficiente.   In realtà la n.c. va a cercare di aumentare il disponibile (che essendo l'usato 0, è uguale al limite), e questo supera il limite della dichiarazione. L'utente non ha modo di correggere la situazione e sbloccarla se non con procedura estremamente convoluta (bisogna creare una fattura passiva fittizia di importo superiore e appoggiarla alla stessa dichiarazione di intento, registrare successivamente la n.c., e poi aunnullare la fattura fittizia - da database si può fare un update su available_amount e ridurlo. Si può validare la n.c. e poi available_amount viene ricalcolato).

Comportamento atteso:
L'XML in questione viene dallo SdI. Indipendentemente dalla storia precedente, è un documento valido che va registrato. Non si può ignorarlo anche se il fornitore l'ha inviato per sbaglio o con dati sbagliati, essendo passato dallo SdI.
Quindi il sistema dovrebbe permettere la validazione.

In generale, tutto il flusso passivo, questo vale anche per fatture che sforano il limite della dichiarazione, dovrebbe essere importabile specie se passa dallo SdI. L'utente ci può fare poco se il fornitore ha commesso un errore, può solo segnalarlo, ma i documenti fiscali devono essere registrati come sono passati dallo SdI.

**Comment by sergiocorato** [comment]
Puoi allegare l'errore generato?

**Comment by TheMule71** [comment]
> Puoi allegare l'errore generato?

Posso fare di meglio, questo è il codice che lo genera:
https://github.com/OCA/l10n-italy/blob/3e47220d6ee4ef8acd74cd6324f650b82454e24f/l10n_it_dichiarazione_intento/models/account_invoice.py#L112-L118

In realtà anche questo controllo non dovrebbe essere bloccante per i documenti passivi: https://github.com/OCA/l10n-italy/blob/3e47220d6ee4ef8acd74cd6324f650b82454e24f/l10n_it_dichiarazione_intento/models/account_invoice.py#L103-L106

e anche:
https://github.com/OCA/l10n-italy/blob/3e47220d6ee4ef8acd74cd6324f650b82454e24f/l10n_it_dichiarazione_intento/models/dichiarazione_intento.py#L155-L163

Da un cliente ho dovuto bypassare i controlli per documenti in_*  e per le dichiarazioni di tipo "in", perchè alla fine impedivano la registrazione della fatture e note di credito passive, provenienti dallo SdI.

**Comment by sergiocorato** [comment]
Ho anch'io avuto qualche problema, si potrebbero togliere i `raise` e sostituirli con una indicazione di sforamento/incongruità dei valori nella dichiarazione di intento, o qualcosa di equivalente.

**Comment by TheMule71** [comment]
Qual è per te il modo più corretto per segnalare la cosa? Io ho semplicemente disabilitato i raise, ma così le cose passano silenziosamente e se il fornitore ha fatto un errore andrebbe segnalato un qualche modo.  Non mi va di indicare un problema nella fattura, perché la fattura che scatena il problema potrebbe non essere quella errata: es. il fornitore F manda fattura 1 (sbagliata) manda fattura 2 (corretta) si perde e non manda nota di credito per f.1, sforando così (con fattura 2) il limite della dichiarazione. Se segnalo un problema in fattura 2 è fuorviante (è la 1 che va corretta).

Idealmente ci vorrebbe un popup tipo "c'è questo problema vuoi continuare lo stesso? si/no".   Non ho idea di quanto sia complicato però intercettare la condizione in l'action_move_create() aprendo il popup e gestendo le due possibile risposte.
