### ISSUE TITLE
[14.0] l10n_it_fatturapa_export_zip: dipendenze

### ISSUE THREAD

**Issue by borgogelli** [OCA/l10n-italy#2444]
Il modulo in oggetto installa come dipendenza "ITA - Fattura elettronica - Ricezione"
Non è possibile utilizzarlo solo con il modulo "ITA - Fattura elettronica - Emissione" ?

**Comment by matteoopenf** [comment]
Guardando qui https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_export_zip/models/attachment.py 
permette di esportare entrambe in uno zip, quindi credo non sia possibile.
