### ISSUE TITLE
[14.0] [MIG] fiscal_epos_print

### ISSUE THREAD

**Issue by cippoco** [OCA/l10n-italy#2449]
Versioni coinvolte:12.0 14.0

Vorrei iniziare la migrazione verso la 14, molte funzionalità sono state integrate nel modulo core di Odoo V14 point_of_sale ed è stato introdotto sempre nel core V14  il modulo pos_epson_printer che si interfaccia alle stampanti Epson internazionali utilizzando la API epos-2.12.0.js. 
Procederei partendo dal modulo pos_epson_printer rifattorizzandolo per fare in modo che utilizzi la API Epson sviluppata per l'italia, in modo da utilizzare le funzionalità di point_of_sale come il modulo nativo, cosa ne pensate? 
pos_epson_printer utilizza javascript mentre in point_of_sale è stato implementato OWL...

**Comment by eLBati** [comment]
Venerdì abbiamo verificato che il modulo `pos_epson_printer` non serve quasi a nulla perchè si limita mandare alla stampante l'immagine grezza dello scontrino, non usa quindi i web services dei registratori telematici e anche a livello funzionale le funzionalità di `fiscal_epos_print` non sono coperte.

Quindi, la strada che suggerisco è portare alla 14 `fiscal_epos_print`.

`pos_epson_printer` potrà essere usato ad esempio per la stampa delle comande, ma non per gli scontrini fiscali.

**Comment by cippoco** [comment]
Ok, la mia idea era di integrare in `pos_epson_printer `i metodi di `fiscal_epos_print`, questo perchè, da quello che ho capito, in `point_of_sale` sono implementati metodi di 'fiscal_epos_print', tipo la ristampa dello scontrino non utilizza più `pos_order_mgmt ` perchè è stato implementato il ticket widget dove vedo gli scontrini stampati e posso rimandarli alla schermata di stampa... Partendo da zerom penso sarebbe stato leggermente più facile visto che non sono proprio così ferrato su js e le API Epson, se però riusciamo a coordinarci preferisco fare il porting, questo venerdì siete ancora su questo argomento? Vi collegate nella stanza vocale del pos?

**Comment by eLBati** [comment]
Ok allora non useremo più `pos_order_mgmt` e per i resi, le ristampe etc. ci baseremo sull'elenco ordini di `point_of_sale`.
Per il resto porteremo le funzionalità di `fiscal_epos_print`.

> Vi collegate nella stanza vocale del pos?

Direi di sì

**Comment by tafaRU** [comment]
Sposterei eventualmente la discussione su https://github.com/OCA/l10n-italy/pull/2761
