### ISSUE TITLE
l10n_it_intrastat_statement: sezione 4, non è possibile esportare una rettifica per cancellazione.

### ISSUE THREAD

**Issue by fredzamoabg** [OCA/l10n-italy#2456]
Versioni coinvolte:

- [x] 12.0
- [x] 14.0 aggiunta alla PR di migrazione https://github.com/OCA/l10n-italy/pull/2259

in base a https://www.adm.gov.it/portale/documents/20182/908833/AllegatoXI++DEF+18+2+15.pdf/34c12ee1-d810-4be5-bfcf-1ff2e0bfe9ab (rif pag 9 Sezione 4):
_3. In caso di cancellazione di una riga dettaglio dichiarata in precedenza nella sezione 3 occorre:
- indicare nelle colonne da 2 a 5 gli estremi che identificano la riga dettaglio da cancellare dichiarata in
precedenza;
- **non compilare le colonne da 6 a 15**._

Passi per riprodurre:
creare una riga in sessione 4 che riguardi una rettifica per cancellazione.

Comportamento osservato:
non è possibile da ottenere una rettifica per cancellazione inquanto i campi sono mandatori nel modello e non c'è alcun flag che escluda questi campi durante l'esportazione del file SCAMBI.CEE.

Comportamento atteso:
poter esportare una rettifica per cancellazione.

Video/Screenshot (opzionale):

**Comment by primes2h** [comment]
@fredzamoabg sai per caso se capita anche nelle altre versioni?

**Comment by fredzamoabg** [comment]
> @fredzamoabg sai per caso se capita anche nelle altre versioni?

Direi di sì,  si tratta di un implementazione mancante.

**Comment by primes2h** [comment]
> > @fredzamoabg sai per caso se capita anche nelle altre versioni?
> 
> Direi di sì, si tratta di un implementazione mancante.

Ok, grazie.

**Comment by SirAionTech** [comment]
Visto che `12.0` non è più supportata, questa si può chiudere
