### ISSUE TITLE
[IMP] l10n_it_delivery_note, spostare creazione DN al di fuori di action_done

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2461]
Versioni coinvolte:

- [x] 12.0 - https://github.com/OCA/l10n-italy/pull/2460
- [ ] 14.0
- [ ] 16.0

**Comment by PicchiSeba** [comment]
Per la `14.0` è stato introdotto in c2e67c1b77fcc6e6129785da19fe8d5a1761e47e
Nella `16.0` f0355e7e0fdb880c2c3caf2e64f6a73060c74dbe
