### ISSUE TITLE
[12.0] - Compatibilità DN e account_cancel

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#2470]
Versioni coinvolte: 

- [ ] 14.0
- [ ] 16.0

**Passi per riprodurre:**

Test con "base" DN ("advanced features" non attivato)

installare/verificare sia installato account_cancel

Creare SO > aggiungi prodotti immagazzinabili > conferma > valida picking > valida DN creato automaticamente > click "create invoice" > DN passa in stato "Invoiced"

Entrare nella fattura generata > Nelle righe fattura vedo il riferimento del DDT

annullare fattura

**Comportamento osservato:**

1) tornare nel picking > DN è ancora in stato "Invoiced"
2) Da SO, creare nuova fattura senza eliminare la precedente > nelle righe fattura NON vedo il riferimento del DDT

**Comportamento atteso:**

Questo comportamento è pericoloso perchè:

1) il DN è in stato "fatturato" quando effettivamente non lo è
2) se la fattura originaria resta annullata e non eliminata, creando altre fatture ci si perde il riferimento del DDT

Forse potrebbe essere sufficiente un popup all'annullamento di una fattura relazionata ad un DDT che informi l'utente "Attenzione: questa fattura è relazionata ad un DDT. Se si vuole mantenere il collegamento tra DDT e fattura, sarà necessario eliminare questa fattura e crearne una nuova" (con due bottoni: "Conferma annullamento fattura" o "torna indietro")?

Video/Screenshot (opzionale): https://recordit.co/kC6Q9Ih6K2

**Comment by tafaRU** [comment]
Puoi verificare che il bug è ancora presente?

**Comment by francesco-ooops** [comment]
gestita in https://github.com/OCA/l10n-italy/issues/4190
