### ISSUE TITLE
[14.0] Check development status failed

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#2472]
Versioni coinvolte:

- [x] 14.0: https://github.com/OCA/l10n-italy/pull/2473

Comportamento osservato:
lavorando a https://github.com/OCA/l10n-italy/pull/2468 mi sono imbattuto in questo problema: https://github.com/OCA/l10n-italy/pull/2468/checks?check_run_id=3960902278#step:6:13

```
Run manifestoo -d . check-dev-status --default-dev-status=Beta
l10n_it_account_tax_kind (Production/Stable) depends on l10n_it_account (Beta)
l10n_it_fatturapa_export_zip (Beta) depends on l10n_it_fatturapa_in (Alpha)
l10n_it_fatturapa_out (Beta) depends on l10n_it_fatturapa (Alpha)
l10n_it_fatturapa_sale (Beta) depends on l10n_it_fatturapa (Alpha)
l10n_it_invoices_data_communication_fatturapa (Beta) depends on l10n_it_fatturapa_in (Alpha)
l10n_it_payment_reason (Production/Stable) depends on l10n_it_account (Beta)
l10n_it_vat_registries (Production/Stable) depends on account_tax_balance (Beta)
l10n_it_vat_registries (Production/Stable) depends on l10n_it_account (Beta)
l10n_it_withholding_tax_payment (Beta) depends on l10n_it_withholding_tax (Alpha)
Error: Process completed with exit code 1.
```

Comportamento atteso:
I moduli attualmente presenti all'interno del branch `14.0` rispettino https://odoo-community.org/page/module-maturity-levels e che di conseguenza il check relativo al `development_status` dei moduli venga superato.

**Comment by primes2h** [comment]
@tafaRU sai per caso se il problema si presenta anche nella v. 12.0?

Altrimenti possiamo chiudere.

**Comment by tafaRU** [comment]
Si può chiudere perché GitHub Actions è attivo solo su `14.0`. (Rif. https://github.com/OCA/l10n-italy/pull/2468).
