### ISSUE TITLE
l10n_it_sdi_channel: spostamento codice per migliorare disaccoppiamento.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2477]
- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2810 + https://github.com/OCA/l10n-italy/pull/3206
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/2708 + https://github.com/OCA/l10n-italy/pull/3207
- [ ] 16.0 #3785 

Spostare da:

https://github.com/OCA/l10n-italy/blob/ccaced704b2e140f3f7831a46f33b637d338882f/l10n_it_sdi_channel/models/company.py#L31-L37

e 
https://github.com/OCA/l10n-italy/blob/d630333a924e1def898b92e7b2477c7c8a1849c0/l10n_it_sdi_channel/models/company.py#L35-L44

in https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa_pec/models/company.py

Questo permetterebbe di disaccoppiare meglio l10n_it_sdi_channel con l10n_it_fatturapa_pec ed altri future implementazioni.

**Comment by GSLabIt** [comment]
@Borruso review?

**Comment by SirTakobi** [comment]
Inizio il backporting a `12.0`

**Comment by eLBati** [comment]
La consideriamo completata?

**Comment by SirTakobi** [comment]
@OCA/local-italy-maintainers si può chiudere?

**Comment by OpenCode** [comment]
> @OCA/local-italy-maintainers si può chiudere?

Sì. Nel caso ci fosse bisogno la si riapre.

**Comment by primes2h** [comment]
Nella PR per la 12.0 vedo tutta una serie di commit aggiuntivi che non sono presenti in quella della 14.0, e che non c'entrano con lo scopo di questa issue di tracciamento.

https://github.com/OCA/l10n-italy/pull/2810/commits (12.0)
https://github.com/OCA/l10n-italy/pull/2708/commits (14.0)

@SirTakobi @GSLabIt 

Le varie modifiche (non presenti nella 14.0) sono state tracciate in altre issue?

Ad esempio https://github.com/OCA/l10n-italy/pull/2810/commits/b696b289f3867f464940bb41b0bc485ba6007f09 e https://github.com/OCA/l10n-italy/pull/2810/commits/5b0c48ebddda693749de9395d02d75dbe864a162 non sono stati portati alla 14.0 e compare quindi questo errore durante la migrazione da 12.0 a 14.0

2023-01-16 16:37:02,489 46557 INFO ez_14 odoo.modules.registry: module l10n_it_fatturapa_pec: creating or updating database tables
2023-01-16 16:37:02,738 46557 INFO ez_14 odoo.modules.loading: loading l10n_it_fatturapa_pec/security/ir.model.access.csv
2023-01-16 16:37:02,753 46557 INFO ez_14 odoo.modules.loading: loading l10n_it_fatturapa_pec/security/groups.xml
2023-01-16 16:37:02,756 46557 ERROR ez_14 odoo.sql_db: bad query: INSERT INTO "res_groups" ("id", "create_uid", "create_date", "write_uid", "write_date", "category_id", "name") VALUES (nextval('res_groups_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 3, 'Allow to force e-invoice export state') RETURNING id
ERROR: duplicate key value violates unique constraint "res_groups_name_uniq"
DETAIL:  Key (category_id, name)=(3, Allow to force e-invoice export state) already exists.

**Comment by SirTakobi** [comment]
> Nella PR per la 12.0 vedo tutta una serie di commit aggiuntivi che non sono presenti in quella della 14.0, e che non c'entrano con lo scopo di questa issue di tracciamento.
> 
> https://github.com/OCA/l10n-italy/pull/2810/commits (12.0) https://github.com/OCA/l10n-italy/pull/2708/commits (14.0)
> 
> @SirTakobi @GSLabIt
> 
> Le varie modifiche (non presenti nella 14.0) sono state tracciate in altre issue?

La PR https://github.com/OCA/l10n-italy/pull/2810 è nata inizialmente per implementare https://github.com/OCA/l10n-italy/issues/2809.
Incidentalmente risolveva anche questa issue perché disaccoppiava il codice presente in **l10n_it_sdi_channel** spostandolo in **l10n_it_fatturapa_pec** come richiesto in questa issue.

Quindi gli altri commit https://github.com/OCA/l10n-italy/pull/2810 sono tracciati dalla issue https://github.com/OCA/l10n-italy/issues/2809.

> Ad esempio [b696b28](https://github.com/OCA/l10n-italy/commit/b696b289f3867f464940bb41b0bc485ba6007f09) e [5b0c48e](https://github.com/OCA/l10n-italy/commit/5b0c48ebddda693749de9395d02d75dbe864a162) non sono stati portati alla 14.0 e compare quindi questo errore durante la migrazione da 12.0 a 14.0
> 
> 2023-01-16 16:37:02,489 46557 INFO ez_14 odoo.modules.registry: module l10n_it_fatturapa_pec: creating or updating database tables 2023-01-16 16:37:02,738 46557 INFO ez_14 odoo.modules.loading: loading l10n_it_fatturapa_pec/security/ir.model.access.csv 2023-01-16 16:37:02,753 46557 INFO ez_14 odoo.modules.loading: loading l10n_it_fatturapa_pec/security/groups.xml 2023-01-16 16:37:02,756 46557 ERROR ez_14 odoo.sql_db: bad query: INSERT INTO "res_groups" ("id", "create_uid", "create_date", "write_uid", "write_date", "category_id", "name") VALUES (nextval('res_groups_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 3, 'Allow to force e-invoice export state') RETURNING id ERROR: duplicate key value violates unique constraint "res_groups_name_uniq" DETAIL: Key (category_id, name)=(3, Allow to force e-invoice export state) already exists.

I commit https://github.com/OCA/l10n-italy/commit/b696b289f3867f464940bb41b0bc485ba6007f09 e https://github.com/OCA/l10n-italy/commit/5b0c48ebddda693749de9395d02d75dbe864a162 sono ancora in fase di porting a `14.0` e sono quindi ancora in una PR aperta (la https://github.com/OCA/l10n-italy/pull/3118), rispettivamente sono: https://github.com/OCA/l10n-italy/pull/3118/commits/c66d3ba4753a6b240e6e18c55b984787cf01535b e https://github.com/OCA/l10n-italy/pull/3118/commits/138a25a95170167a20e88ec66e0246352415cad7.

Se attualmente c'è un problema durante la migrazione da `12.0` a `14.0` penso debba andare in una nuova issue, che forse si risolverà al merge di https://github.com/OCA/l10n-italy/pull/3118, oppure con una fix puntale.

**Comment by primes2h** [comment]
> > Nella PR per la 12.0 vedo tutta una serie di commit aggiuntivi che non sono presenti in quella della 14.0, e che non c'entrano con lo scopo di questa issue di tracciamento.
> > https://github.com/OCA/l10n-italy/pull/2810/commits (12.0) https://github.com/OCA/l10n-italy/pull/2708/commits (14.0)
> > @SirTakobi @GSLabIt
> > Le varie modifiche (non presenti nella 14.0) sono state tracciate in altre issue?
> 
> La PR #2810 è nata inizialmente per implementare #2809. Incidentalmente risolveva anche questa issue perché disaccoppiava il codice presente in **l10n_it_sdi_channel** spostandolo in **l10n_it_fatturapa_pec** come richiesto in questa issue.
> 
> Quindi gli altri commit #2810 sono tracciati dalla issue #2809.

Ok, grazie mille per il chiarimento.


> 
> > Ad esempio [b696b28](https://github.com/OCA/l10n-italy/commit/b696b289f3867f464940bb41b0bc485ba6007f09) e [5b0c48e](https://github.com/OCA/l10n-italy/commit/5b0c48ebddda693749de9395d02d75dbe864a162) non sono stati portati alla 14.0 e compare quindi questo errore durante la migrazione da 12.0 a 14.0
> > 2023-01-16 16:37:02,489 46557 INFO ez_14 odoo.modules.registry: module l10n_it_fatturapa_pec: creating or updating database tables 2023-01-16 16:37:02,738 46557 INFO ez_14 odoo.modules.loading: loading l10n_it_fatturapa_pec/security/ir.model.access.csv 2023-01-16 16:37:02,753 46557 INFO ez_14 odoo.modules.loading: loading l10n_it_fatturapa_pec/security/groups.xml 2023-01-16 16:37:02,756 46557 ERROR ez_14 odoo.sql_db: bad query: INSERT INTO "res_groups" ("id", "create_uid", "create_date", "write_uid", "write_date", "category_id", "name") VALUES (nextval('res_groups_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 3, 'Allow to force e-invoice export state') RETURNING id ERROR: duplicate key value violates unique constraint "res_groups_name_uniq" DETAIL: Key (category_id, name)=(3, Allow to force e-invoice export state) already exists.
> 
> I commit [b696b28](https://github.com/OCA/l10n-italy/commit/b696b289f3867f464940bb41b0bc485ba6007f09) e [5b0c48e](https://github.com/OCA/l10n-italy/commit/5b0c48ebddda693749de9395d02d75dbe864a162) sono ancora in fase di porting a `14.0` e sono quindi ancora in una PR aperta (la #3118), rispettivamente sono: [c66d3ba](https://github.com/OCA/l10n-italy/commit/c66d3ba4753a6b240e6e18c55b984787cf01535b) e [138a25a](https://github.com/OCA/l10n-italy/commit/138a25a95170167a20e88ec66e0246352415cad7).
> 
> Se attualmente c'è un problema durante la migrazione da `12.0` a `14.0` penso debba andare in una nuova issue, che forse si risolverà al merge di #3118, oppure con una fix puntale.

Se ritieni  che quei due commit non siano strettamente legati al nuovo modulo introdotto dalla #3118 posso fare cherry-pick e aprire una PR a parte.

Tra l'altro mi sembra ci siano diverse sovrapposizioni tra i commit tra #3118, #3120, #3121, #3122, molti sono presenti in tutte le PR (tra cui i due oggetto della discussione).

**Comment by primes2h** [comment]
> > Se ritieni che quei due commit non siano strettamente legati alle funzionalità introdotte dalla #3118 e dal nuovo modulo nella #3122, posso fare cherry-pick e aprire una PR a parte.
> 
> Sì per me fai pure, anzi se così risolvi il problema della migrazione tanto meglio :)

Ok.

> 
> > Tra l'altro mi sembra ci siano diverse sovrapposizioni tra i commit tra #3118, #3120, #3121, #3122, molti sono presenti in tutte le PR (tra cui i due oggetto della discussione).
> 
> Sì questo è vero, l'ho segnalato nella descrizione di ogni PR che ne include un'altra; non ho trovato modi migliori per fare il porting di **l10n_it_fatturapa_sdicoop** (obiettivo di tutta la catena di PR) mantenendo il tracciamento con le singole issue e facendo comunque funzionare le CI di ogni PR. Non mi fido ad usare test-requirements in questo caso perché i moduli nel requirements sarebbero anche nel addons_path: non so quale dei due avrebbe la precedenza, e anche supponendo che mi andasse bene non voglio farci affidamento

Forse sarebbe meglio seguire l'approccio standard OCA e mantenere semplicemente la corrispondenza con le PR aperte a suo tempo per la 12.0.
Se ha funzionato nella 12.0 non vedo perché non possa funzionare anche nella 14.0.

Quindi, ad es. 
la #3120 con le modifiche della #2876 (merge già effettuato senza necessità di test-requirements)
la #3121 con le modifiche della #2884 (merge già effettuato senza necessità di test-requirements)
e così via.

Altrimenti tenere traccia di tutto diventa un problema enorme, per non parlare di chi vuole revisionare le PR. ;-)
Meno codice c'è in una PR più è facile che venga revisionata IMO.

**Comment by primes2h** [comment]
> > Se ritieni che quei due commit non siano strettamente legati alle funzionalità introdotte dalla #3118 e dal nuovo modulo nella #3122, posso fare cherry-pick e aprire una PR a parte.
> 
> Sì per me fai pure, anzi se così risolvi il problema della migrazione tanto meglio :)

Fatto in #3145

**Comment by SirTakobi** [comment]
> la https://github.com/OCA/l10n-italy/pull/3120 con le modifiche della https://github.com/OCA/l10n-italy/pull/2876 (merge già effettuato senza necessità di test-requirements)

Le modifiche fatte dalla #2876 sono fatte sul codice che già include la https://github.com/OCA/l10n-italy/pull/2810, quindi provando a fare il cherry-pick dei commit della #2876 sull'attuale `14.0` ci sono non pochi conflitti perché mancano tutte le modifiche fatte, lato `12.0`, dalla #2810.

Quindi per portare la #2876 ho dovuto prima portare la #2810: per questo ho fatto la #3118.

Stessa cosa per le PR successive: per fare un cherry-pick il più possibile pulito, ho dovuto portare le PR che erano state mergiate precedentemente.

> Altrimenti tenere traccia di tutto diventa un problema enorme, per non parlare di chi vuole revisionare le PR. ;-)
Meno codice c'è in una PR più è facile che venga revisionata IMO.

Lo ben so, però come scrivevo questo è il modo migliore che ho trovato per farlo per mantenere i commit il più possibile simili agli originali e le CI funzionanti; se qualcuno vuole revisionare la PR con meno codice può farlo con la #3118, se invece si vuole provare tutto il flusso si può fare nella https://github.com/OCA/l10n-italy/pull/3122.
Ovviamente se c'è gente interessata a tutto il flusso e arrivano abbastanza revisioni per la #3122 si mergia quella e tanto meglio, ci evitiamo le revisioni intermedie :)

Un'alternativa che avevo pensato era portare la https://github.com/OCA/l10n-italy/pull/2810 così com'è, senza estrarre **l10n_it_fatturapa_sdicoop**, includendo invece un commit di migrazione per quel modulo.
Al merge però ci saremmo trovati un **l10n_it_fatturapa_sdicoop** alla `14.0` che però non è l'equivalente dello stesso modulo nella `12.0` perché gli mancano ancora i porting delle varie #2876, #2884 ecc; secondo me così si sarebbe generata più confusione quindi ho optato per le PR come sono fatte adesso.
