### ISSUE TITLE
l10n_it_account_stamp: Descrizione righe fattura resettate quando viene aggiunto il bollo

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2498]
## Module
l10n_it_account_stamp

## Describe the bug
Aggiungendo il bollo alla fattura vengono resettate eventuali modifiche alla descrizione delle altre righe fattura.

## To Reproduce
**Affected versions**: 
- [x] v14: https://github.com/OCA/l10n-italy/pull/2499

1. Creare una fattura che sia soggetta a bollo
2. Modificare la descrizione di una riga
3. Salvare la fattura
3. Entrare in modifica e aggiungere il bollo tramite il pulsante "Aggiungi riga bollo"

**Expected behavior**
Viene aggiunta la riga del bollo e la descrizione della riga modificata rimane tale.

**Actual behavior**
Viene aggiunta la riga del bollo e la descrizione della riga modificata viene resettata alla descrizione del prodotto.

**Comment by eLBati** [comment]
La 12 non è affetta

**Comment by SimoRubi** [comment]
> La 12 non è affetta

grazie, allora chiudo
