### ISSUE TITLE
l10n_it_fiscal_document_type: Tipo documento impostato dall'utente non mantenuto

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2501]
## Module
l10n_it_fiscal_document_type, l10n_it_account_stamp

## Describe the bug
Se il tipo di documento fiscale viene impostato dall'utente, viene resettato all'aggiunta della riga bollo

## To Reproduce
**Affected versions**:
- [x] v14: https://github.com/OCA/l10n-italy/pull/2502

1. Creare una fattura in modo che il bollo sia applicabile
2. Modificare il tipo di documento fiscale (tab "Altre informazioni") e salvare
3. Entrare in modifica della fattura e cliccare su "Aggiungi riga bollo"

**Expected behavior**
Il tipo di documento fiscale viene mantenuto.

**Actual behavior**
Il tipo di documento fiscale viene modificato in 'fattura'.

**Comment by eLBati** [comment]
La 12 non è affetta
