### ISSUE TITLE
Spostare menu RiBa in modo da renderlo visibile anche nella versione Enterprise

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#2526]
## Module
- [x] 12.0 chiusa in quanto non supportata 
- [x] 14.0 #2623
- [x] 16.0 #3615 

Vedi #2139 e relativo commento qui sotto:

Riporto quanto detto stamattina in chiamata.
Questa PR non è mergiabile perché dipende dal modulo `account_accountant` che è enterprise, però il problema descritto va in qualche modo risolto.

In generale bisogna fare in modo che il modulo `account_accountant` sposti anche questo menu.
Visto che il modulo sposta i menu in modo _statico_ semplicemente cambiando il parent dei menu che conosce (https://github.com/odoo/enterprise/blob/693ea0e9f35738a09465f0b628f6678ca8f4e601/account_accountant/data/account_accountant_data.xml#L10-L28), secondo me l'unica soluzione è mettere il menu delle RiBa sotto uno dei menù esistenti e verrà così spostato automaticamente.

Può comunque valere la pena indagare se ci sono altre soluzioni.

_Originally posted by @SimoRubi in https://github.com/OCA/l10n-italy/pull/2139#pullrequestreview-816650426_

**Comment by primes2h** [comment]
Una possibile soluzione può essere https://github.com/OCA/l10n-italy/pull/2623#issuecomment-1047298073.

**Comment by francesco-ooops** [comment]
@odooNextev questa è da fare anche per la 16?

**Comment by francesco-ooops** [comment]
allora direi di sì che va aggiunta una checkbox per la 16 @tafaRU

**Comment by odooNextev** [comment]
A me comunque neanche quella della 14 funziona

**Comment by francesco-ooops** [comment]
@odooNextev perchè mi sembra ci siano diverse PR ancora aperte, vedi https://github.com/OCA/l10n-italy/pull/2623#issuecomment-1194147076

**Comment by SirAionTech** [comment]
Il commit f1f9e4c937308a24ebfe757a45aaf7beed805b48 di #2623 è stato portato alla `16.0` da https://github.com/OCA/l10n-italy/pull/3615 (ora è https://github.com/OCA/l10n-italy/commit/b028d5bc413639aae71bde233806e13f0ff21f24).

Per sicurezza ho anche verificato che la problematica in oggetto non succeda in `16.0`, quindi direi che si può chiudere.

**Comment by SirAionTech** [comment]
> > @odooNextev questa è da fare anche per la 16?
> 
> Il codice aggiunto dalla PR è già integrato nel modulo `l10n_it_riba`, ma non funziona

Scusa @odooNextev vedo ora questo commento, puoi riportare i passi che hai fatto?
Come scrivevo poco fa ho appena provato e mi sembra funzionare correttamente, i passi che ho fatto sono:

1. Creo nuovo DB in italiano
2. Installo **l10n_it_edi**
3. Disinstallo **l10n_it_edi** (perché incompatibile con **l10n_it_fatturapa**)
4. Installo **l10n_it_riba**
    -> Il menu delle RiBa è sotto Fatturazione
5. Installo **account_accountant**
    -> Il menu delle RiBa è sotto Contabilità

**Comment by SirAionTech** [comment]
> @SirAionTech se installi `account_accountant` prima di `l10n_it_riba` ti genera il menù **Accounting** arancione

Capito, quindi in pratica inverti 4. e 5. di https://github.com/OCA/l10n-italy/issues/2526#issuecomment-1862954868, io l'ho sempre provato come descritto in https://github.com/OCA/l10n-italy/issues/2526#issuecomment-1862954868 e non trovavo il problema.

La fix attuale fa in modo che il menu RiBa segua i suoi menu sibling quando vengono spostati, se però viene installato dopo non può farlo.
Per risolvere si potrebbe usare un post_init_hook per spostare il menu RiBa nel caso venga installato quando i menu sono già stati spostati da account_accountant.

**Comment by francesco-ooops** [comment]
risolta su tutte le versioni

**Comment by SirAionTech** [comment]
@francesco-ooops il commento https://github.com/OCA/l10n-italy/issues/2526#issuecomment-1863093444 è un problema aperto, quindi è da risolvere in una nuova issue?

**Comment by francesco-ooops** [comment]
@SirAionTech il problema riportato da @odooNextev è su entrambe le versioni?

se sì puoi aprire una nuova issue?

**Comment by SirAionTech** [comment]
> @SirAionTech il problema riportato da @odooNextev è su entrambe le versioni?

Penso di sì

> se sì puoi aprire una nuova issue?

https://github.com/OCA/l10n-italy/issues/3799
