### ISSUE TITLE
l10n_it_fatturapa_out: Esportazione fattura con natura esenzione

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2529]
## Module
l10n_it_fatturapa_out

## Describe the bug
Non è possibile esportare una fattura avente
- una riga avente imposta con natura esenzione
- una nota

## To Reproduce
**Affected versions**:
- [x] `14.0`: #2530 

1. Creare un'imposta che abbia natura esenzione
4. Creare una fattura
5. Aggiungere un prodotto con l'imposta creata
6. Aggiungere una riga di nota
8. Confermare
9. Esportare fattura elettronica

**Actual behavior**
Errore: 
```
[...]
  File "<template>", line 1, in template_l10n_it_fatturapa_out_account_invoice_line_it_FatturaPA_6585
KeyError: account.move(407,)

Error to render compiling AST
KeyError: account.move(407,)
Template: l10n_it_fatturapa_out.account_invoice_line_it_FatturaPA
Path: /t/DettaglioLinee/Natura[2]
Node: <Natura t-if="line.display_type in ('line_section', 'line_note') and list(all_taxes[line.move_id.id].values())[0].get('Natura')" t-esc="list(all_taxes[line.move_id].values())[0]['Natura']"/>
```

**Expected behavior**
Creazione della fattura elettronica

**Comment by TheMule71** [comment]
Credo debba essere:
```
diff --git a/l10n_it_fatturapa_out/data/invoice_it_template.xml b/l10n_it_fatturapa_out/data/invoice_it_template.xml
index 06ff324ca..da4ab806e 100644
--- a/l10n_it_fatturapa_out/data/invoice_it_template.xml
+++ b/l10n_it_fatturapa_out/data/invoice_it_template.xml
@@ -186,7 +186,7 @@ e 'line' per riga di fattura (a seconda del livello in cui sono chiamati)
                 />
                 <Natura
                     t-if="line.display_type in ('line_section', 'line_note') and list(all_taxes[line.move_id.id].values())[0].get('Natura')"
-                    t-esc="list(all_taxes[line.move_id].values())[0]['Natura']"
+                    t-esc="list(all_taxes[line.move_id.id].values())[0]['Natura']"
                 />
                 <RiferimentoAmministrazione
                     t-if="line.admin_ref"
```
Adesso però guardo se è il caso di coprire con un test la casistica.

**Comment by SimoRubi** [comment]
> Credo debba essere:
> 
> ```
> diff --git a/l10n_it_fatturapa_out/data/invoice_it_template.xml b/l10n_it_fatturapa_out/data/invoice_it_template.xml
> index 06ff324ca..da4ab806e 100644
> --- a/l10n_it_fatturapa_out/data/invoice_it_template.xml
> +++ b/l10n_it_fatturapa_out/data/invoice_it_template.xml
> @@ -186,7 +186,7 @@ e 'line' per riga di fattura (a seconda del livello in cui sono chiamati)
>                  />
>                  <Natura
>                      t-if="line.display_type in ('line_section', 'line_note') and list(all_taxes[line.move_id.id].values())[0].get('Natura')"
> -                    t-esc="list(all_taxes[line.move_id].values())[0]['Natura']"
> +                    t-esc="list(all_taxes[line.move_id.id].values())[0]['Natura']"
>                  />
>                  <RiferimentoAmministrazione
>                      t-if="line.admin_ref"
> ```
> 
> Adesso però guardo se è il caso di coprire con un test la casistica.

vedi https://github.com/OCA/l10n-italy/pull/2530

**Comment by matteoopenf** [comment]
avevo fatto anche io una pr in questo senso

**Comment by TheMule71** [comment]
Ah manco ho fatto a tempo a digitare che hai già fatto. :)

**Comment by TheMule71** [comment]
> avevo fatto anche io una pr in questo senso

Infatti la cosa mi era familiare.

**Comment by matteoopenf** [comment]
https://github.com/OCA/l10n-italy/pull/2491 non ho fatto in tempo a fare rebase

**Comment by SimoRubi** [comment]
> avevo fatto anche io una pr in questo senso

@matteoopenf ho cercato prima di aprire issue e PR ma non ho trovato nulla 

> #2491 non ho fatto in tempo a fare rebase

Probabile che non l'avevo trovata perché non parla della natura esenzione

**Comment by matteoopenf** [comment]
> > avevo fatto anche io una pr in questo senso
> 
> @matteoopenf ho cercato prima di aprire issue e PR ma non ho trovato nulla
> 
> > #2491 non ho fatto in tempo a fare rebase
> 
> Probabile che non l'avevo trovata perché non parla della natura esenzione

risolveva proprio il problema delle nature senza inserire tutta la logica inserita ora da te, perchè già parzialmente aveva risolto @TheMule71  e ho aggiunto li il pezzo mancante

**Comment by TheMule71** [comment]
Comunque la #2530 aggiunge un test e soprattutto rende il codice più leggibile.

**Comment by matteoopenf** [comment]
@SimoRubi  comunque ho visto che hai corretto come ho corretto io, quindi approvo e chiudiamo la mia poi
