### ISSUE TITLE
l10n_it_fatturapa_sale - Errore nella creazione della fattura da un ordine di vendita

### ISSUE THREAD

**Issue by mktsrl** [OCA/l10n-italy#2533]
Errore nel creare una fattura da un ordine di vendita

## Module
l10n_it_fatturapa_sale  ("version": "14.0.1.0.0")

## Describe the bug
Partendo da un'ordine di vendita, la funzione "Crea Fattura" scatena un errore.

## To Reproduce
**14.0**:

Steps per riprodurre il comportamento:
1. Dall'area ordini di vendita apro i dettagli di un qualsiasi ordine
2. clicco sul bottone "Crea Fattura"
2. seleziono "Fattura normale" nelle opzioni proposte dal wizard
3. clicco sul bottone "Crea Fatture" del wizard
4. si scatena il seguente errore:

`Errore:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/wizard/sale_make_invoice_advance.py", line 159, in create_invoices
    sale_orders._create_invoices(final=self.deduct_down_payments)
  File "/home/odoo-user/odoo-14/third-party-addons/l10n-italy/l10n_it_fatturapa_sale/models/sale_order.py", line 19, in _create_invoices
    moves = super()._create_invoices(grouped=grouped, final=final, date=date)
  File "/home/odoo-user/odoo-14/third-party-addons/l10n-italy/l10n_it_delivery_note/models/sale_order.py", line 116, in _create_invoices
    invoice_ids = super()._create_invoices(grouped=grouped, final=final, date=date)
  File "/usr/lib/python3/dist-packages/odoo/addons/sale/models/sale.py", line 716, in _create_invoices
    (0, 0, line._prepare_invoice_line(
  File "/home/odoo-user/odoo-14/third-party-addons/l10n-italy/l10n_it_fatturapa_sale/models/sale_order_line.py", line 25, in _prepare_invoice_line
    invoice_line_vals = super()._prepare_invoice_line(**optional_values)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: _prepare_invoice_line() got an unexpected keyword argument 'sequence'`

**Expected behavior**
Creazione della fattura

**Comment by SimoRubi** [comment]
Grazie della segnalazione!
Ho provato a riprodurre il problema in runbot e sono riuscito a creare una fattura con gli step che hai riportato: 

https://user-images.githubusercontent.com/32064796/144018816-d462cef4-d1b3-4fa8-a74e-fd5e4de50eab.mp4

Il link alla fattura creata è http://3517168-14-0-a63eb2.runbot2.odoo-community.org/web?debug=1#id=32&action=211&active_id=4&model=account.move&view_type=form&cids=&menu_id=251

Riesci a riprodurre il problema nell'ambiente linkato?

Se non riesci, allora potrebbe essere un problema dovuto alla tua particolare installazione, ad esempio moduli custom, versioni non aggiornate o altro.

**Comment by mktsrl** [comment]
Grazie Simone per la velocissima risposta!
Nell'ambiente segnalato non riscontro l'errore, così ho appena fatto un ulteriore verifica e ho capito che il problema è dovuto alla presenza, sulla mia istanza, del modulo OCA/commission/sale_commission (che uso per la gestione degli agenti di vendita)

Se disinstallo OCA/commission/sale_commission il comportamento si ripristina regolarmente come nell'ambiente che mi hai linkato.

Sembrerebbe che i due moduli:
- OCA/l10n-italy/l10n_it_fatturapa_sale
- OCA/commission/sale_commission
non possano esistere insieme.

Eventualmente mi puoi fornire qualche ulteriore indicazione in merito e confermare se devo segnalare questo comportamento anomalo anche sul repo OCA/commission ?

Grazie!
Luca

**Comment by SimoRubi** [comment]
Ho provato in un ambiente locale con i due moduli installati e non riscontro il problema:

https://user-images.githubusercontent.com/32064796/144029760-ba0994da-368a-4c25-ad89-c88b487db714.mp4

In ogni caso, per quanto ne so se c'è un'incompatibilità tra moduli va segnalata nel manifest di entrambi i moduli tramite la chiave `excludes`.
Non ho trovato documentazione per questa chiave in https://www.odoo.com/documentation/14.0/developer/reference/addons/module.html?#manifest ma abbiamo un esempio in 
https://github.com/OCA/l10n-italy/blob/a63eb2f0650f799863c496ec266890a2cdba8dc1/l10n_it_fatturapa/__manifest__.py#L16

**Comment by TheMule71** [comment]
Ho guardato il codice e non vedo incompatibilità. Per altro l'errore sempre legato alla definizione della funzione `_prepare_invoice_line()` ma sembra corretta in entrambi i moduli. 

Domanda banale per @mktsrl :  sei certo di avere fatto il checkout del branch 14.0 di sale_commission? Quale è la versione del modulo installato?

**Comment by mktsrl** [comment]
@TheMule71 la versione del modulo sale_commission è la 14.0.1.1.4

@TheMule71 e @SimoRubi , credo di aver finalmente individuato in che condizione si scatena esattamente l'errore:

1. Ho disinstallato tutti i moduli del pacchetto OCA/commission e il funzionamento risulta regolare (si creano tranquillamente le fatture)
2. Ho riattivato il modulo sale_commission (nella versione indicata) e anche in questo caso non riscontro il problema. (Nei test iniziali ero passato da una situazione di errore con i moduli del pacchetto commission installati e avevo verificato solamente che disinstallandoli non si verificasse più il problema, ma in questo modo non avevo un indicazione chiara del modulo coinvolto)
3. Ho iniziato a reinstallare puntualmente gli altri moduli del pacchetto commission partendo da sale_commission_salesman e subito ho verificato un comportamento anomalo, ovvero:

- Il modulo sale_commission_salesman permette di aggiungere sul contatto cliente specifici agenti di vendita. L'agente di vendita poi comparirà sulle line dell'ordine di vendita di quel cliente. 
- Se sulle linee dell'ordine di vendita non compare nessun agente (non lo specifico per il cliente), allora il comportamento risulta ancora regolare e la fattura si crea correttamente.
- Se, al contrario, per la linea d'ordine viene specificato un agente (perchè impostato sul contatto cliente) --> a quel punto creando la fattura si genera l'errore.

**Comment by SimoRubi** [comment]
> * sale_commission_salesman

Non mi pare che il modulo `sale_commission_salesman` sia presente per `14.0` (https://github.com/OCA/commission/tree/d64cfbddfc76620f6df361ed073ebd3a778bc493), da dove l'hai preso?

**Comment by mktsrl** [comment]
@SimoRubi hai ragione e non riesco a capire perchè nel mio pacchetto OCA/commission versione 14 compaia quel modulo nella versione 13.
Probabilmente ho fatto confusione con qualche aggiornamento del pacchetto.. non so.. Mi dispiace avervi fatto tribulare! :-(

**Comment by TheMule71** [comment]
La mia domanda non era casuale:
```
commit 359ab184f0ef0f0876143a74de9041fb7f751fcd
Author: Christoph Müllner <christoph.muellner@foerster.co.at>
Date:   Thu Dec 17 12:05:09 2020 +0100

    [MIG] sale_commission: Migration to 14.0

diff --git a/sale_commission/models/sale_order.py b/sale_commission/models/sale_order.py
index c1d2c30..0516336 100644
--- a/sale_commission/models/sale_order.py
+++ b/sale_commission/models/sale_order.py
@@ -40,8 +40,8 @@ class SaleOrderLine(models.Model):
                     record.order_id.partner_id
                 )
 
-    def _prepare_invoice_line(self):
-        vals = super()._prepare_invoice_line()
+    def _prepare_invoice_line(self, **optional_values):
+        vals = super()._prepare_invoice_line(**optional_values)
         vals["agent_ids"] = [
             (0, 0, {"agent_id": x.agent_id.id, "commission_id": x.commission_id.id})
             for x in self.agent_ids
```
questa è l'unica modifica a questo file fatta in fase di migrazione. La signature della funziona cambia, quella della 14.0 è corretta e soprattutto non può dare l'errore che tu hai riportato. Per dare quello specifico errore deve girare il codice della 13.0 o precedente.

Il modulo `sale_commission_salesman` non contiene modifiche a quella funzione, quindi non può essere il colpevole. È possibile che tu abbia installato il modulo `sale_commission` con il branch 14.0 attivo (in tal caso nel DB viene salvata la versione 14 del modulo) e poi abbia switchato al branch 13.0 per "vedere" il modulo `sale_commission_salesman`.  In questo modo se fai ripartire Odoo gira il codice 13.0 anche per il modulo `sale_commission`, la signature della funzione è quella vecchia (non compatibile con la 14.0), anche se da DB risulta ancora installato il modulo in versione 14.0.  Spero di essermi spiegato bene :)

**Comment by SimoRubi** [comment]
> @SimoRubi hai ragione e non riesco a capire perchè nel mio pacchetto OCA/commission versione 14 compaia quel modulo nella versione 13. Probabilmente ho fatto confusione con qualche aggiornamento del pacchetto.. non so.. Mi dispiace avervi fatto tribulare! :-(

Succede :)
Quando sei sicuro che il problema non sussiste, ricorda di chiudere la issue, grazie

**Comment by mktsrl** [comment]
Perfetto e grazie per le chiarissime indicazioni!!
Chiudo allora la issue e.... farò un po' più allenamento con i branch! :-)
