### ISSUE TITLE
EmailType pattern constraint violated by value test@pec

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2535]
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/2534
 - [x] 14.0 non affetta

Passi:

 - importare l'XML `l10n_it_fatturapa_in/tests/data/IT01234567890_FPR13.xml` contenuto nella PR https://github.com/OCA/l10n-italy/pull/2534

**Comment by TheMule71** [comment]
Ma è arrivato dallo SdI quel XML?

**Comment by TheMule71** [comment]
Comunque i pattern non mi tornano, dovrebbero essere:
```
  <xs:simpleType name="EmailType">
    <xs:restriction base="xs:token">
      <xs:maxLength value="256" />
      <xs:pattern value="([!#-'*+/-9=?A-Z^-~-]+(\.[!#-'*+/-9=?A-Z^-~-]+)*|&quot;(\[\]!#-[^-~ \t]|(\\[\t -~]))+&quot;)@([!#-'*+/-9=?A-Z^-~-]+(\.[!#-'*+/-9=?A-Z^-~-]+)*|\[[\t -Z^-~]*\])" />
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="EmailContattiType">
    <xs:restriction base="xs:string">
      <xs:minLength value="7" />
      <xs:maxLength value="256" />
      <xs:pattern value=".+@.+[.]+.+" />
    </xs:restriction>
  </xs:simpleType>
```

```
import re
p = r"([!#-'*+/-9=?A-Z^-~-]+(\.[!#-'*+/-9=?A-Z^-~-]+)*|&quot;(\[\]!#-[^-~ \t]|(\\[\t -~]))+&quot;)@([!#-'*+/-9=?A-Z^-~-]+(\.[!#-'*+/-9=?A-Z^-~-]+)*|\[[\t -Z^-~]*\])"
print(re.match(p, "test@pec"))
```
```
<_sre.SRE_Match object; span=(0, 8), match='test@pec'>
```

Col pattern giusto come da specifiche SdI funziona...

**Comment by eLBati** [comment]
> Ma è arrivato dallo SdI quel XML?

Sì https://github.com/OCA/l10n-italy/pull/2534#issuecomment-982528684

**Comment by TheMule71** [comment]
Si ma non capisco perché non usare l'xds corretto, che funziona, invece di modificare una nostra copia locale. La re da applicare è quella che ho testato qui sopra https://github.com/OCA/l10n-italy/issues/2535#issuecomment-982526265

**Comment by SimoRubi** [comment]
`14.0` non è affetta:
![image](https://user-images.githubusercontent.com/32064796/144037526-88f6d0c6-c0b7-4c05-b7a4-97b275b73097.png)
(da http://3517168-14-0-a63eb2.runbot2.odoo-community.org/web#id=33&active_id=2&model=account.move&view_type=form&cids=&menu_id=124)
