### ISSUE TITLE
[14.0][l10n_it_fatturapa_out] permessi per esportazione fattura elettronica

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#2537]
Il wizard di esportazione della fattura elettronica, ha un campo che mostra i report disponibili.
Quel campo è un M2O verso ir.actions.actions, ma stando a questa riga, solo gli amministratori possono vedere quel campo:

https://github.com/odoo/odoo/blob/14.0/odoo/addons/base/security/ir.model.access.csv#L80

Infatti un utente con i soli permessi contabili non può lanciare quel wizard.

Sulla 12.0 ir.actions.actions era accessibile in lettura a tutti gli utenti:

https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/security/ir.model.access.csv#L69

 - [x] 12.0 non affetta
 - [x] 14.0 ~https://github.com/OCA/l10n-italy/pull/2641~ vedi #3267 
 - [x] 16.0 vedi #3267

**Comment by TheMule71** [comment]
Vd. anche  https://github.com/odoo/odoo/pull/53335

**Comment by TheMule71** [comment]
Ho dato un'occhiata ma non trovo una soluzione semplice.

La relazione usa `comodel_name` direttamente, non possiamo usare `.sudo()`, almeno io non ho trovato come fare.

**Comment by SimoRubi** [comment]
@dcorio puoi verificare se https://github.com/OCA/l10n-italy/pull/2641 risolve?

**Comment by OpenCode** [comment]
> @dcorio puoi verificare se #2641 risolve?

@dcorio Hai feedback a riguardo?
