### ISSUE TITLE
[14.0] AttributeError: 'fiscal.document.type' object has no attribute 'refund_fiscal_document_type_id'

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#2540]
Questo campo non è definito in fiscal_document_type e genera errore in fase di update

https://github.com/OCA/l10n-italy/blob/a43b2543d677fd0f6eb2817299f1df938e997b27/l10n_it_fiscal_document_type/models/account_move.py#L68

**Comment by scigghia** [comment]
sulla V12 c'è questo https://github.com/OCA/l10n-italy/blob/500b3d27d6599173ec8610d5c79014876c81d77b/l10n_it_fiscal_document_type/models/fiscal_document_type.py#L24 come mai non è stato portato ?

**Comment by TheMule71** [comment]
> refund_fiscal_document_type_id



> come mai non è stato portato ?

Probabilmente perché il porting è cominciato prima che questa #2099 venisse mergiata.  Quando io ho fatto un primo screening delle pr sulla 12 all'indietro mi sono fermato a marzo.

**Comment by scigghia** [comment]
grazie @TheMule71 nel frattempo ho fatto una PR che magicamente ora ha tutti i check superati ;)
