### ISSUE TITLE
l10n_it_dichiarazione_intento: Validazione massiva di fatture

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2547]
## Module
l10n_it_dichiarazione_intento

## Describe the bug
Non è possibile validare diverse fatture contemporaneamente chiamando il metodo `action_invoice_open`
(https://github.com/odoo/odoo/blob/bb712ad7017db9c6477ceb40633e2460238b3317/addons/account/models/account_invoice.py#L581).

**Affected versions**:
- [x] `10.0`: #2548 
- [x] 12.0 (risolta per termine supporto)
- [x] 14.0 il problema non sussiste, vedi https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_declaration_of_intent/models/account_move.py#L89
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/4207 (solo test)

**Additional context**
Non ho trovato un modo di riprodurre il problema da interfaccia perché la validazione fatta dalla lista delle fatture viene propagata ad ogni singola fattura in https://github.com/odoo/odoo/blob/bc8d5dbf2c2ee19b337195bdb4bee8e6ba8508cf/addons/account/wizard/account_invoice_state.py#L22.

**Comment by eLBati** [comment]
Sulla 12 il codice è uguale quindi direi che non riguarda solo la 10

**Comment by sergiocorato** [comment]
Il bug non sussiste sulla 14.0, quindi chiudo la issue.
