### ISSUE TITLE
[14.0] l10n_it_fiscalcode traduzione "Calcolo CF"

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#2554]
Non sta funzionando la traduzione di questo bottone (screenshot da runbot)

![image](https://user-images.githubusercontent.com/55489873/145851418-bf331688-066d-43d4-88d3-f5a56c13575c.png)

**Comment by tafaRU** [comment]
Grazie della segnalazione!

Penso che il problema sia dovuto al fatto che nel file po si ha [Compute F.C.](https://github.com/OCA/l10n-italy/blob/db628eee76cf9cc547792a89c6b557d8cd953e29/l10n_it_fiscalcode/i18n/it.po#L55) mentre nel pot e nei termini sorgente si ha [Compute FC](https://github.com/OCA/l10n-italy/blob/db628eee76cf9cc547792a89c6b557d8cd953e29/l10n_it_fiscalcode/wizard/compute_fc_view.xml#L60).
@primes2h puoi verificare?

**Comment by primes2h** [comment]
@sbidoul 
It seems that .po files has not been updated in weblate.
E.g.
https://github.com/OCA/l10n-italy/blob/f1820b9d5293eee45cac565628b37bd9fcef8914/l10n_it_fiscalcode/i18n/l10n_it_fiscalcode.pot#L48
https://github.com/OCA/l10n-italy/blob/db628eee76cf9cc547792a89c6b557d8cd953e29/l10n_it_fiscalcode/i18n/it.po#L55

Could you check it please?

**Comment by sbidoul** [comment]
I clicked configure on the msgmerge addon in weblate for this component, and a commit went through.
We never understood completely what is happening. I'll try to do a weblate upgrade in the coming weeks and see if it improves.
