### ISSUE TITLE
account_vat_period_end_statement: il debito della liquidazione precedente non risulta pagato

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2558]
## Module
account_vat_period_end_statement

## Describe the bug
Nonostante il pagamento, il debito della liquidazione IVA del periodo precedente non risulta pagata e il debito viene riportato sulle liquidazioni successive.

## To Reproduce
**Affected versions**:
- [ ] `12.0`: sì
- [ ] `14.0`: da verificare

1. Configurazione:
    1. Installare `l10n_it` (Piano dei conti italiano).
    2. Abilitare modalità debug e abilitare il gruppo "Funzionalità contabili complete" per l'utente corrente.
    4. Configurare le imposte da 10 credito/debito con il conto per la liquidazione IVA credito/debito rispettivamente.
    5. In Fatturazione > Configurazione > Contabilità > Intervalli data Generazione intervalli data, creare i periodi per il 2022
6. Creare e confermare una fattura cliente da 100+10 a Gennaio
7. Creare la liquidazione IVA di Gennaio 2022 in data 31 Gennaio e creare il movimento
8. Creare e confermare una fattura cliente da 1000+100 a Febbraio
9. Creare e confermare una fattura fornitore da 500+50 a Febbraio
10. Creare la liquidazione IVA di Febbraio 2022 in data 28 Febbraio e creare il movimento
      Verificare che la liquidazione IVA riporta "Importo IVA Erario" = 60.
12. Creare un pagamento da 60 per la liquidazione IVA di Febbraio 2022 e riconciliare.
13. Creare una liquidazione IVA di Marzo 2022 in data 31 Marzo.

**Actual behavior**
La liquidazione di Febbraio non risulta pagata (tab conti, check "Pagata/Riconciliata").
La liquidazione IVA di Marzo 2022 riporta "Importo IVA Erario" = 10.

**Expected behavior**
La liquidazione di Febbraio risulta pagata (tab conti, check "Pagata/Riconciliata").
La liquidazione IVA di Marzo 2022 riporta "Importo IVA Erario" = 0.

**Additional context**
Codice dove il problema è riprodotto (ultimo commit di `12.0`): https://github.com/OCA/l10n-italy/tree/81e2162499d6d66ddc0f53a462359082e3c5996d
Dump dove il problema è riprodotto: [odoo12-16954_2021-12-15_15-02-40.zip](https://github.com/OCA/l10n-italy/files/7720491/odoo12-16954_2021-12-15_15-02-40.zip)

**Work-around**
Allo step 12, riconciliando le righe selezionate nell'immagine:
![image](https://user-images.githubusercontent.com/32064796/150943610-4d4ac10f-5c25-4f2f-b6a3-f87b4dc8bb80.png)
allora il comportamento è quello atteso.

**Comment by primes2h** [comment]
@SimoRubi per caso sai se il problema si presenta anche nella versione 14.0 ?

**Comment by SimoRubi** [comment]
> @SimoRubi per caso sai se il problema si presenta anche nella versione 14.0 ?

Non lo so

**Comment by primes2h** [comment]
> > @SimoRubi per caso sai se il problema si presenta anche nella versione 14.0 ?
> 
> Non lo so

Grazie, ho aggiunto la 14.0 come "da verificare".

**Comment by eLBati** [comment]
Il comportamento descritto mi pare quello atteso: se l'utente non chiude il debito aperto, perchè il sistema dovrebbe considerarlo pagato?

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
