### ISSUE TITLE
[14.0][l10n_it_fiscal_document_type] name_search not working

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#2561]
L'implementazione di name_search recentemente aggiunta al modulo pare avere problemi.
Se clicco sul campo tipo documento, per cambiare il tipo, ricevo

`Errore:Odoo Server ErrorTraceback (most recent call last):  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch    result = request.dispatch()  File "/home/odoo/src/odoo/odoo/http.py", line 684, in dispatch    result = self._call_function(self.params)  File "/home/odoo/src/odoo/odoo/http.py", line 360, in _call_function    return checked_call(self.db, *args, kwargs)  File "/home/odoo/src/odoo/odoo/service/model.py", line 94, in wrapper    return f(dbname, args, **kwargs)  File "/home/odoo/src/odoo/odoo/http.py", line 348, in checked_call    result = self.endpoint(a, kw)  File "/home/odoo/src/odoo/odoo/http.py", line 913, in call    return self.method(*args, kw)  File "/home/odoo/src/odoo/odoo/http.py", line 532, in response_wrap    response = f(*args, **kw)  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1389, in call_kw    return self._call_kw(model, method, args, kwargs)  File "/home/odoo/src/odoo/addons/web/controllers/main.py", line 1381, in _call_kw    return call_kw(request.env[model], method, args, kwargs)  File "/home/odoo/src/odoo/odoo/api.py", line 399, in call_kw    result = _call_kw_multi(method, model, args, kwargs)  File "/home/odoo/src/odoo/odoo/api.py", line 382, in _call_kw_multi    ids, args = args[0], args[1:]ExceptionThe above exception was the direct cause of the following exception:Traceback (most recent call last):  File "/home/odoo/src/odoo/odoo/http.py", line 640, in _handle_exception    return super(JsonRequest, self)._handle_exception(exception)  File "/home/odoo/src/odoo/odoo/http.py", line 316, in _handle_exception    raise exception.with_traceback(None) from new_causeIndexError: list index out of range`

Potrebbe dipendere dalla mancanza del decoratore sul metodo?

**Comment by eLBati** [comment]
Quindi questa si può chiudere?
