### ISSUE TITLE
ricevute bancarie migrazione Odoo 12 > 14.0

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#2568]
https://github.com/OCA/l10n-italy/blob/b559d0c22c38116cd5a452058d91731ee0160965/l10n_it_ricevute_bancarie/migrations/13.0.1.0.0/post-migration.py#L8

credo che qui si debba aggiungere prima un "alter table invoice_unsolved_line_rel rename invoice_id to move_id;"

**Comment by eLBati** [comment]
@scigghia Vuoi fare la PR?

**Comment by scigghia** [comment]
e voi ritenete affidabile una PR fatta da me a natale? 😂😂😂
vabbè si può fare

**Comment by SirAionTech** [comment]
A occhio questa issue è stata risolta da https://github.com/OCA/l10n-italy/pull/3361, @scigghia puoi verificare?
@sergiocorato che hai fatto https://github.com/OCA/l10n-italy/pull/3361 ne dici?

**Comment by francesco-ooops** [comment]
chiusa per https://github.com/OCA/l10n-italy/pull/2794#issuecomment-1873787198
