### ISSUE TITLE
Dichiarazioni d'intento supporto multicompany 

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2578]
Nel modulo dichiarazioni d'intento non mi pare ci sia modo per indicare da quale\per quale azienda interna a odoo è creata\destinata la dichiarazione d'intento.
Cambiando company le dichiarazioni d'intento sono visibili da tutte le aziende
iIl rischio di usare la dischiarazione di intento "sbagliata" potrebbe essere elevato se più company hanno gli stessi fornitori\clienti 

 - [x] 12.0 #2593 
 - [x] 14.0: https://github.com/OCA/l10n-italy/pull/2582

**Comment by As400it** [comment]
#2582 V14.0

**Comment by francescapenso** [comment]
testata e funzionante
