### ISSUE TITLE
[IMP] l10n_it_account_stamp: spostare impostazioni da tab "informazioni generali"

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#2580]
Per mantenere la pulizia della form del prodotto non si potrebbero spostare tutte queste impostazioni nel tab "contabilità"?

![immagine](https://user-images.githubusercontent.com/227940/150865329-ad50b8fe-28c7-4bc0-98d4-b38a8d420da5.png)

Grazie

- [x] 12.0 (risolta per termine supporto)
- [x] 14.0 #2613

**Comment by tafaRU** [comment]
Puoi proporre una PR se vuoi. Grazie.

**Comment by francesco-ooops** [comment]
> Puoi proporre una PR se vuoi. Grazie.

lo so bene, intanto apro la issue ;)

**Comment by OpenCode** [comment]
@francesco-ooops Potresti creare la PR per la 12.0?

**Comment by francesco-ooops** [comment]
> @francesco-ooops Potresti creare la PR per la 12.0?

@GSLabIt puoi riportare le stesse modifiche alla 12.0?

**Comment by SirAionTech** [comment]
Per `16.0` le modifiche di #2613 sono in https://github.com/OCA/l10n-italy/commit/3700a050a245c7db97155bf0d46581a7c145c82e (sono state portate dalla migrazione https://github.com/OCA/l10n-italy/pull/3021).
