### ISSUE TITLE
l10n_it_intrastat - novità 2022 Paese di origine preferenziale, semplificazioni, codice unico «99500000», 

### ISSUE THREAD

**Issue by marco-marchiori** [OCA/l10n-italy#2581]
A dicembre l'agenzia delle dogane  e l'agenzia delle entrate hanno introdotto una serie di modifiche nell'intrastat.
Allego determinazione ministeriale.

La modifica più urgente appare quella relativa al Paese di origine preferenziale, ci sono poi alcune semplificazioni, l'introduzione di un codice unico per cessioni ed acquisti sotto i 1.000 euro.

Non vedo ancora pubblicate le specifiche tecniche e le norme per la produzione del file.

Se ci fossero già degli aggiornamenti almeno sull'inserimento dell'origine preferenziale Vi prego di aggiornarmi qui.
[determinazione_prot_493869_ru.pdf](https://github.com/OCA/l10n-italy/files/7828393/determinazione_prot_493869_ru.pdf)

 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2686 + https://github.com/OCA/l10n-italy/pull/2719 + https://github.com/OCA/l10n-italy/pull/2782
 - [x] 14.0 https://github.com/OCA/l10n-italy/pull/2857

**Comment by dcorio** [comment]
@marco-marchiori Dove si reperiscono le specifiche dei cambiamenti da apportare? Con una semplice ricerca su Google non ci sono arrivato

**Comment by sergiocorato** [comment]
A questo link: https://www.adm.gov.it/portale/-/determinazione-n%C2%B0-493869-del-23-dicembre-2021-nuovi-modelli-degli-elenchi-riepilogativi-delle-cessioni-e-degli-acquisti-intracomunitari-di-beni-e-delle-prestazioni-di-servizio-rese-e-ricevute-in-ambito-comunitario-periodi-di-riferimento-decorrenti-da
ho trovato:
[Allegato 12 Specifiche tecniche e tracciati record degli elenchi riepilogativi.pdf](https://github.com/OCA/l10n-italy/files/8068535/Allegato.12.Specifiche.tecniche.e.tracciati.record.degli.elenchi.riepilogativi.pdf)
[Allegato 11 Istruzioni per l'uso e la compilazione degli elenchi riepilogativi.pdf](https://github.com/OCA/l10n-italy/files/8068548/Allegato.11.Istruzioni.per.l.uso.e.la.compilazione.degli.elenchi.riepilogativi.pdf)

**Comment by sergiocorato** [comment]
Da quanto leggo:
per la sezione 1 dell'Intra-2 (acquisti):
![Screenshot(176)](https://user-images.githubusercontent.com/7657311/154075861-a6e68245-ee88-4751-a58a-0282b30a52d4.png)

per la sezione 1 dell'Intra-1 (cessioni):
![Screenshot(177)](https://user-images.githubusercontent.com/7657311/154075886-2a9dd2d5-ec11-4c60-bf9d-cc63b43e5eb3.png)

per l'Intra-1 (cessioni):
![Screenshot(178)](https://user-images.githubusercontent.com/7657311/154075984-3839d307-1ef5-45c0-8c58-624432b11eeb.png)

**Comment by sergiocorato** [comment]
Quindi è da implementare la colonna B e i codici triangolazione di questa tabella:
[tabella B.pdf](https://github.com/OCA/l10n-italy/files/8070824/tabella.B.pdf)

**Comment by zeroincombenze** [comment]
Grazie Sergio. Gli do subito un'occhiata

**Comment by sergiocorato** [comment]
#2664

**Comment by sergiocorato** [comment]
Da quanto ho saputo, il sito delle dogane attualmente non può ricevere il nuovo formato e sono in attesa di aggiornamento dalla SOGEI.

**Comment by AliceCancedda** [comment]
Da questo pomeriggio è disponibile la procedura intraweb per la creazione e/o controllo dei file intrastat, completa dei nuovi codici di nomenclatura combinata. Sino a stamattina il link per il download non era attivo

**Comment by eLBati** [comment]
Riporto anche la sintesi delle modifiche in corso:

```
Intrastat: modifiche in corso
-----------------------------

* Nella tabella natura A (transport) aggiunto il campo codice triangolazione alfabetico
* Nuova tabella natura B che dipende da natura A (nature_parent_id)
* Righe intrastat delle vendite (sale)
    * Campo many2one verso natura B
    * Paese di origine, campo many2one verso res.country
    * Flag triangolazione

* Modifiche al tracciato
```

Rif https://discord.com/channels/753902328494424064/753902328494424070/945315764225851413

**Comment by zeroincombenze** [comment]
Riepilogo situazione:
Ho creato 2 nuove PR la [#2690](https://github.com/OCA/l10n-italy/pull/2690) e la [#2690](https://github.com/OCA/l10n-italy/pull/2691)

La #2690 (Odoo 12.0) è completa per il modulo l10n_it_intrastat ed incorpora le modifiche di Xergio #2686 / #2664 e quelle di eLBati
#2687 
Sto importando le modifiche per il modulo l10n_it_intrastat_statement

La #2691 è la prima versione per Odoo 14.0 solo modulo l10n_it_intrastat. Questa versione è sperimentale (non ho ancora sufficiente esperienza con la 14.0) e manca ancora dei test.
Sto anche importando le modifiche per il modulo l10n_it_intrastat_statement

Per la 14.0 non sono sicuro di completare entro la scadenza del 07/03/2022
