### ISSUE TITLE
[14.0] Fattura_pa_in errore visualizzazione

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2585]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1. importare una fattura
2. visualizzare la fattura fornitore
3. la data di fattura (solo il valore non l'etichetta del campo) vanno a finire sotto la data ricezione e fattura. In presenza di studio la cosa si può facilmente risolvere spostando i campi Protocollo, Trasmittente, Data ricezione e-fattura al di sotto della data 

![image](https://user-images.githubusercontent.com/19937703/148758748-ef672334-5558-4ce6-99c7-b9d81bf1c054.png)

**Comment by TheMule71** [comment]
@francescapenso puoi vedere se #2592 fixa?

**Comment by francescapenso** [comment]
Fixa per me è mergiabile
