### ISSUE TITLE
[14.0] l10n_it_withholding_tax: all'abbinamento pagamento alla fattura genera diverse righe di ritenuta

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#2591]
## Module
l10n_it_withholding_tax

## Describe the bug
All'abbinamento del pagamento genera diverse righe di ritenuta

## To Reproduce
14.0

1. creare fattura con fornitore che abbia come posizinoe fiscale ritenuta d'acconto
2. aggiungere prodotto e validare la fattura 
3. cliccare su registra pagemento e pagare l'intera fattura
4. riportare la fattura in bozza e abbinare il pagamento che prima avevo registrato
5. associato il pagamento genera diverse righe di ritenuta

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
