### ISSUE TITLE
[14.0] l10n_it_delivery_note : issue to open DN from invoice for non-admin users

### ISSUE THREAD

**Issue by mde-spring** [OCA/l10n-italy#2597]
Hi team,

We have identified an issue when we click on smart button Delivery Note from an invoice.

![image](https://user-images.githubusercontent.com/79934758/149995881-abae44af-d36b-43b9-90be-303982a5fea7.png)

A non-admin user (w/o the role 'Administration/Settings') can't open the DN linked to the invoice.

![image](https://user-images.githubusercontent.com/79934758/149995798-a051539c-d152-408b-8134-4d46fb05ef91.png)

Because the model ir_act_window can't be read without to be a superuser.

Works by adding a sudo() on this line of code:
https://github.com/OCA/l10n-italy/blob/6530fd2b0ac728ef08bd05f384e4c06c08a8f0a4/l10n_it_delivery_note/models/account_invoice.py#L34

or to replace by :
`action = self.env['ir.actions.act_window']._for_xml_id('l10n_it_delivery_note.stock_delivery_note_action')`

**Comment by mde-spring** [comment]
Same things on these lines:
https://github.com/OCA/l10n-italy/blob/6530fd2b0ac728ef08bd05f384e4c06c08a8f0a4/l10n_it_delivery_note/models/stock_delivery_note.py#L557

https://github.com/OCA/l10n-italy/blob/6530fd2b0ac728ef08bd05f384e4c06c08a8f0a4/l10n_it_delivery_note/models/sale_order.py#L125

**Comment by tafaRU** [comment]
@mde-spring could you please have a look if #3469 and #3470 fix it?

**Comment by mde-spring** [comment]
@tafaRU yes it's good for me
