### ISSUE TITLE
[12.0] [BUG] riba:calcolo iva spese incasso fattura duplicata

### ISSUE THREAD

**Issue by stefano-ooops** [OCA/l10n-italy#2600]
Versione verificata 12.0

passi per riprodurre:
1. creazione fattura con modalità pagamento RIBA (validazione con aggiunta automatica spese incasso)
2. duplicata fattura cambiando termine di pagamento (esempio:rim diretta) mantenendo inalterati i prodotti
3. validazione fattura 

comportamento osservato: 
il calcolo dell'iva nella fattura duplicata tiene conto ancora delle spese di incasso.

comportamento atteso:
dovrebbe calcolare l'iva basandosi sul nuovo imponibile.

[video](https://recordit.co/r4PYsF0F5y)

**Comment by stefano-ooops** [comment]
Testato nella V14 il problema non si presenta

**Comment by francesco-ooops** [comment]
Chiudo in quanto v12 non più supportata
