### ISSUE TITLE
[14.0] l10n_it_fatturapa_in, missing translation string in weblate.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2601]
Missing translation for module `l10n_it_fatturapa_in`, v 14.0

## Describe the bug

Per un qualche motivo alcune stringhe del modulo `l10n_it_fatturapa_in`  non sono presenti, in particolare:

https://github.com/OCA/l10n-italy/blob/6530fd2b0ac728ef08bd05f384e4c06c08a8f0a4/l10n_it_fatturapa_in/i18n/l10n_it_fatturapa_in.pot#L482-L498

**Comment by francesco-ooops** [comment]
@GSLabIt this looks solved now, you can close
