### ISSUE TITLE
[RFC][14.0] l10n_it_declaration_of_intent: dichiarazione di intenti in modelli vendita e acquisto 

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2603]
Sarebbe interessante arricchire il modulo l10n_it_declaration_of_intent in modo tale che quando viene creato un ordine di acquisto o di vendita fosse "evidente" in qualche modo se è presente una dichiarazione di intenti che ha ancora plafond disponibile.

**Comment by TheMule71** [comment]
È possibile creare uno smart button contenente il residuo delle LI aperte col partner?
Ovviamente deve cambiare al cambiare del medesimo.

**Comment by matteoopenf** [comment]
> È possibile creare uno smart button contenente il residuo delle LI aperte col partner? Ovviamente deve cambiare al cambiare del medesimo.

si l'ideale è se lo metti calcolato e storato in modo che è sempre aggiornato
