### ISSUE TITLE
Dati Ordine Acquisto - Sezione 2.1.2 della Fatturazione Elettronica

### ISSUE THREAD

**Issue by MirkosoftAssistenza** [OCA/l10n-italy#2611]
Salve a tutti, vorrei porre una richiesta, sarebbe possibile trovare questo campo in fattura?
Probabilmente non è gestito da Odoo, ma potrebbe essere interessante trovarlo nella fattura elettronica.
Per trovarlo andrebbe sia modificato il modulo "Fatturazione" che il vostro relativo alla "Fatturazione Elettronica"?
Potete suggerirmi qualcosa o attuare la modifica?

Grazie mille!

**Comment by TheMule71** [comment]
Al momento, io sono riuscito a create un ordine, con documento collegato di tipo Ordine
![image](https://user-images.githubusercontent.com/915043/151598982-a5bdaea9-0426-461f-bd20-be7fbb1c4ef0.png)

poi ho consegnato la merce, ho creato fattura, ho creato l'XML e in questo ho trovato:
![image](https://user-images.githubusercontent.com/915043/151599087-ff178783-2811-49a4-8bd1-fdb12e0e72b4.png)

In XML:
![image](https://user-images.githubusercontent.com/915043/151599221-4863ea3b-977d-421d-9884-06e9ff2a3dc4.png)

**Comment by MirkosoftAssistenza** [comment]
Provato anch'io ed è assolutamente funzionante, sarebbe sì da aggiungere la possibilità anche dall'Invoicing così da emettere fatture immediate legate ad ordini d'acquisto esterni

**Comment by TheMule71** [comment]
> Provato anch'io ed è assolutamente funzionante, sarebbe sì da aggiungere la possibilità anche dall'Invoicing così da emettere fatture immediate legate ad ordini d'acquisto esterni

Assolutamente d'accordo. Infatti c'è una issue aperta: #2270 
La gestione dei documenti correlati va rivista, se vogliamo rappresentare le varie combinazioni possibili a livello di XML.

**Comment by MirkosoftAssistenza** [comment]
Intanto ho aperto un'altra issue #2651 per il campo "lineRef" che non è editabile.

**Comment by OpenCode** [comment]
@MirkosoftAssistenza @TheMule71 Possiamo chiudere questa issue in visione del fatto che avete aperto le altre?
