### ISSUE TITLE
[14.0] Scarico fatture elettroniche fornitore su Odoo 

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#2615]
## Module
l10n_it_fatturapa_in

## Describe the bug
Quando si scaricano le fatture elettroniche ci potrebbe essere nel db più partner con stessa partita iva o codice fiscale.
In questo caso Odoo trovando il raise non ti scrive il record nella tabella fatturapa_in e il cliente può non accorgersene.

**Expected behavior**
Potremmo nella funzione `_compute_xml_data` aggiungre un `self.env.cr.commit()` così se va in errore, quando va a trovare il partner , almeno il record nella tabella lo inizia a scrivere e viene poi gestita successivamente la presenza della partita iva o codice fiscale

**Comment by matteoopenf** [comment]
ma non è simile al problema dei gruppi iva questo?

**Comment by Borruso** [comment]
> ma non è simile al problema dei gruppi iva questo?

Purtroppo non ti so dire poiché non mi è capitato

**Comment by matteoopenf** [comment]
> > ma non è simile al problema dei gruppi iva questo?
> 
> Purtroppo non ti so dire poiché non mi è capitato

I gruppi iva sono società che hanno stessa partita iva e diverso codice fiscale e che alla fine portano a un problema simile.

Forse alla creazione della Fe bisognerebbe vedere se oltre a esistere quel contatto esiste per quella company.
Non so ora come viene fatta la ricerca.

**Comment by SimoRubi** [comment]
Potresti scrivere gli step per ottenere il problema e il comportamento attuale/atteso per almeno uno degli errori che possono capitare? Ad esempio che errore viene sollevato nel caso di partner con stesso codice fiscale.
In chiamata parlavi di un import da Aruba ma non saprei come replicarlo.


Riporto poi quanto detto stamattina in chiamata:
Invece di inserire un `commit` durante il processamento delle fatture potrebbe essere più _safe_ aggiungere un `try..except` intorno alle operazioni più a rischio, a occhio sarebbero:
https://github.com/OCA/l10n-italy/blob/e3b0fa6d4251f1633b3e6e8e627cf6a7a9c456d8/l10n_it_fatturapa_in/models/attachment.py#L100-L102
se ci sono degli errori in questa fase si possono riportare in uno dei campi dell'allegato tipo `fatturapa.attachment.in.e_invoice_validation_error` (eventualmente facendo `rollback`) e poi andare avanti a leggere le altre fatture.

**Comment by fredzamoabg** [comment]
@Borruso vedi https://github.com/OCA/l10n-italy/pull/2750

**Comment by eLBati** [comment]
Secondo me si risolve con https://github.com/OCA/l10n-italy/pull/2748
