### ISSUE TITLE
l10n_it_withholding_tax: Prevenire "AttributeError: 'bool' object has no attribute 'id'"

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2616]
## Module
l10n_it_withholding_tax

## Describe the bug
In https://github.com/OCA/l10n-italy/blob/d4493d603579420a8eda0d83cee0408d69eeef58/l10n_it_withholding_tax/models/account.py#L132
la variabile `rec_line_statement` potrebbe avere valore `False`, quindi potrebbe essere sollevato l'errore
> AttributeError: 'bool' object has no attribute 'id'

## To Reproduce
**Affected versions**:
- [x] `12.0`: sì perché il codice è identico (risolta per fine supporto)
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/2617
- [x] 16.0: #2998

**Steps to reproduce the behavior**
L'errore è capitato a un nostro cliente, purtroppo non siamo riusciti ad estrapolare i passi per riprodurlo in runbot.

**Comment by francesco-ooops** [comment]
tutte le versioni risolte
