### ISSUE TITLE
New due date modules / Nuovo scadenzario evoluto

### ISSUE THREAD

**Issue by AntonioMariaVigliotti** [OCA/l10n-italy#2619]
Apro questa issue per concentrare tutta la documentazione ed i feedback del progetto di gestione scadenzario.

Questa issue fa riferimento alla https://github.com/OCA/l10n-italy/pull/2618 che contiene alcuni nuovi file:
* account_banking_common
* account_common_mixin
* account_duedates
* account_duedates_sale
* account_fiscal_year_plus
* account_invoice_13_more
* account_move_line_type
* account_move_plus
* account_payment_method
* account_payment_term_plus
* assigned_bank

Ciascun modulo è dotato di README con i dettagli.

Note di implementazione:
* Sviluppato per Odoo 12.0
* Permette di modificare le scadenza anche su fattura inviata a SdI
* Aggiunge una tab di scadenze in fattura
* Permette di modificare il metodo di pagamento di ogni singola scadenza (esempio per trasformare bonifico in RiBA o viceversa)
* Permette di riassagnere il conto bancario aziendale di una singola scadenza
* Nelle fatture e nelle righe fattura si possono dichiarare sia il conto aziendale che la banca di appoggio
* I due campi banche compilano il campo standard di Odoo "conto bancario" che è oscurato (secondo lo standard Odoo: conto bancario per documenti clienti, conto parnter per documento fornitore)
* Utilizza un unico flusso di gestione scadenze basato su payment.order di OCA (anche per Ricevute Bancarie) che in questa PR non è ancora caricato
* Per come è progettato semplifica anche la gestione della ricevute bancarie passive
* Molto altro ancora

Purtroppo il nostro software diverge molto dai moduli OCA, per cui è stato fatto un lavoro di standardizzazione e semplificazione, ai fini di ridurre al minimo le differenze. L'idea è quella di proporre successive PR di evoluzione, mano a mano che la Community analizza il codice proposto.
Temo che questa attività, che ha ritardato la pubblicazione della PR, abbia introdotto qualche piccolo bug, che ovviamente risolveremo il più rapidamente possibile.

Attendo fiducioso i Vostri feedback.

**Comment by matteoopenf** [comment]
Buonasera,

Ma le cose inviate a SDI non vanno modificate.
L'agenzia delle entrate non vede di buon occhio chi fa queste cose. Abbiamo già avuto un caso in cui a qualcuno delle fiamme gialle non è piaciuta la cosa.
Ti consiglio di rivedere quanto hai scritto.

**Comment by AntonioMariaVigliotti** [comment]
> Buonasera,
> 
> Ma le cose inviate a SDI non vanno modificate. L'agenzia delle entrate non vede di buon occhio chi fa queste cose. Abbiamo già avuto un caso in cui a qualcuno delle fiamme gialle non è piaciuta la cosa. Ti consiglio di rivedere quanto hai scritto.

Grazie Matteo per la tua segnalazione. In fattura sono modificabili solo le date e gli importi delle scadenze, niente altro. Questi dati non sono fiscali e sono, per legge, modificabili in accordo tra le parti anche dopo l'invio della fattura elettronica.

**Comment by AntonioMariaVigliotti** [comment]
Questa è la bozza del manuale per l'utilizzo del software.

[Manuale Odoo 12.pdf](https://github.com/OCA/l10n-italy/files/7953603/Manuale.Odoo.12.pdf)

**Comment by AntonioMariaVigliotti** [comment]
> Buonasera,
> 
> Ma le cose inviate a SDI non vanno modificate. L'agenzia delle entrate non vede di buon occhio chi fa queste cose. Abbiamo già avuto un caso in cui a qualcuno delle fiamme gialle non è piaciuta la cosa. Ti consiglio di rivedere quanto hai scritto.

Scusa sono stato frettoloso. Sai fornire qualche indicazione più precisa, magari i riferimenti legislativi?
Grazie
