### ISSUE TITLE
[14.0] Reimposta a bozza un pagamento - Errore causato dal modulo del reverse charge

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2620]
## Module
l10n_it_reverse_charge

## Describe the bug
Con il modulo l10n_it_reverse_charge installato, quando vado a reimpostare a bozza un pagamento ottengo l'errore
![image](https://user-images.githubusercontent.com/7657512/151541332-955d01c4-8099-46f9-b0b7-29312577810a.png)

## To Reproduce
**Affected versions**:

1. Installare modulo l10n_it_reverse_charge
2. Creare una fattura cliente
3. Registrare il pagamento
4. Entrare nel menu 
![image](https://user-images.githubusercontent.com/7657512/151541599-e56cb232-a969-4302-a629-5f6a2c52ed4e.png)
5. Entrare nel pagamento e cliccare su
![image](https://user-images.githubusercontent.com/7657512/151541768-54373a1a-0a5c-4b22-b70b-ff578dd69a91.png)

**Expected behavior**
Il pagamento deve essere riportato nello stato di bozza
![image](https://user-images.githubusercontent.com/7657512/151541891-6b54211a-7623-4eb4-bc21-bc48a4535260.png)

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by SimoRubi** [comment]
Grazie della segnalazione e della PR, esiste però già https://github.com/OCA/l10n-italy/pull/2595, puoi controllare se risolve questa problematica ed eventualmente lasciare lì una review?

**Comment by alessandrocamilli** [comment]
@SimoRubi si grazie, la pr esistente funziona, chiudo la PR

**Comment by eLBati** [comment]
Capita solo sulla 14?

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
