### ISSUE TITLE
[14] fattura_pa_in data predefinita registrazione fattura

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2626]
1. impostare nelle impostazioni "Data predefinita per la registrazione delle fatture fornitore" a "Data ricezione" 
2. importare una fattura elettronica questa prenderà correttamente come data contabile quella di arrivo della fattura. 
3. confermare la fattura --> in questo caso il numero della fattura dipenderà dalla data della fattura fornitore originale.

ES: Formato registro: numero-anno 
Fattura emessa dal fornitore il 31.12.2021 e inviata il 10.01.2022 
Ultimo numero ft 2021 registrate 201-2021 
Ultimo numero ft 2022 registrate 10-2022
La fattura avrà correttamente data contabile 10.01.2022 ma verrà confermata come 202-2021

**Comment by TheMule71** [comment]
Interessante. Se la fattura è relativa al 2021, non va bene che finisca nel registro 2021?

**Comment by francescapenso** [comment]
Dipende se vuoi prendere la data di ricezione o la data di fattura.
Io ho un cliente che registra in base alla data di ricezione e uno che
registra sulla base della data di fatturazione originale.
In ogni caso a corredo di questo bisognerebbe che la data scadenza fattura
venisse calcolata sulla data della fattura e non sulla registrazione (che
può per altro modificata a piacimento)

Il giorno ven 4 feb 2022 alle ore 13:59 Marco Colombo <
***@***.***> ha scritto:

**Comment by eLBati** [comment]
Per completezza: https://github.com/OCA/l10n-italy/issues/1183

**Comment by TheMule71** [comment]
Comunque, è strano:
https://github.com/odoo/odoo/blob/d5f012f61dd877ef04fd1023b22a761d3dcd76ab/addons/account/models/sequence_mixin.py#L24
https://github.com/odoo/odoo/blob/d5f012f61dd877ef04fd1023b22a761d3dcd76ab/addons/account/models/account_move.py#L1271
Il campo usato per la parte data delle sequenze delle fattura è `date` del modello. Nel tuo caso @francescapenso mi aspetterei `date` nel 2022.

**Comment by TheMule71** [comment]
Ah sulla seconda parte ho dei dubbi. Credo che la fattura si consideri emessa nel momento la si manda allo SdI. Infatti esiste:
1) l'obbligo di indicare la data di esecuzione delle prestazioni - se diversa dalla data di emissione (quindi possono essere diverse)
2) l'obbligo di "emettere" la fattura entro 12 giorni dalla data di esecuzione della prestazione. 
Questo per le fatture immediate (non differite).

Se viene rifiutata dallo SdI, si considera "non emessa".

Però anche l'AdE spesso fa confusione e chiama la data del documento "data di emissione" e contemporaneamente "data dell'esecuzione" come se fossero sempre la stessa cosa, e chiama "data di trasmissione" quella dell'invio allo SdI.

In ogni caso la "data scadenza" della fattura da cosa è determinata e cosa determina?

**Comment by francescapenso** [comment]
> Comunque, è strano: https://github.com/odoo/odoo/blob/d5f012f61dd877ef04fd1023b22a761d3dcd76ab/addons/account/models/sequence_mixin.py#L24 https://github.com/odoo/odoo/blob/d5f012f61dd877ef04fd1023b22a761d3dcd76ab/addons/account/models/account_move.py#L1271 Il campo usato per la parte data delle sequenze delle fattura è `date` del modello. Nel tuo caso @francescapenso mi aspetterei `date` nel 2022.

Devo fare delle prove in più perchè temo che questo bug sia frutto di un modulo che c'è per gestire le sequenze in odoo 14 come venivano gestite in 12

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
