### ISSUE TITLE
Netto a pagare in fattura

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/l10n-italy#2629]
**Is your feature request related to a problem?**
Le normative degli ultimi anni determinano sempre più che il totale fattura ed il totale da pagare siano diversi (esempio split-payment e reverse-charge).
Il campo netto a pagare è disponibile nel modulo della ritenute d'acconto l10n_it_withholding_tax

**Describe the solution you'd like**
Propongo di spostare il campo netto a pagare amount_net_pay dal modulo l10n_it_withholding_tax in un modulo comune, esempio l10n_it_account 

**Additional context**
Questa modifica potrebbe aiutare a rivolvere i problemi di stampa fattura, dove ci sono molti calcoli.

**Comment by eLBati** [comment]
Mi sembra una buona idea
