### ISSUE TITLE
l10n_it_fatturapa_in_rc: back porting fixes 

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2630]
https://github.com/OCA/l10n-italy/blob/c7158bc6d4cfb9c13a7f57e9fed33d034f9e9f7a/l10n_it_fatturapa_in_rc/wizard/wizard_import_fatturapa.py#L10

Va aggiunta N2.1
Vd.
https://github.com/OCA/l10n-italy/pull/2149/commits/ee135bd296019375eb787da5bf06b8326778b5ad

Versioni (le altre da verificare)

- [x] 12.0 #2822
- [x] 14.0 #2149

**Comment by tafaRU** [comment]
Mentre ci siamo potremmo aggiungere `float_compare`.
