### ISSUE TITLE
14.0 l10n_it_fatturapa_out_rc

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2631]
https://github.com/OCA/l10n-italy/blob/d0b067f0b3834d0b6ac4ac225147f412636096f0/l10n_it_fatturapa_out_rc/models/account_move.py#L81

A questo punto servirebbe una:
```
if invoices_without_rc:
    return
```
I controlli dalla riga 81 in poi si devono applicare solo alle fattura con RC, altrimenti fanno fallire la generazione dell'XML le fatture normali (per capirci, `partner`, preso da `rc_suppliers` è sempre vuoto per le fatture normali, e gli ultimi controlli falliscono per forza).

**Comment by Borruso** [comment]
Questi sono i test che falliscono:

https://github.com/OCA/l10n-italy/runs/5064122206?check_suite_focus=true

**Comment by eLBati** [comment]
Riapro per valutare 12.0

**Comment by tafaRU** [comment]
@eLBati la `12.0` non è affetta perché qui i controlli vengono eseguiti solo se è verificata la condizione `self.env.context.get("rc_supplier")`.
