### ISSUE TITLE
IMP: back porting: invia XML via PEC anche da lista

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2633]
Dovrebbe essere applicabile anche alle versioni precedenti:

Vd. https://github.com/OCA/l10n-italy/pull/2198#discussion_r794441394

**Comment by tafaRU** [comment]
Ho verificato: sia sulla `10.0` che sulla `12.0` è già possibile eseguire una selezione multipla di `fatturapa.attachment.out` ed inviarli allo SDI tramite PEC.
