### ISSUE TITLE
l10n_it_fatturapa_out_di: Aggiunta riga a 0 con altra natura

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2634]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Creando una Fattura Elettronica da una fattura collegata a una dichiarazione d'intento, nella FE non devono esserci righe ulteriori con nature diverse e importo a 0 rispetto alle righe della fattura.

**Describe alternatives you've considered**
Le righe ulteriori derivano dalle righe note, quindi una possibilità è uniformare la natura delle righe note alla natura delle altre righe fattura esistenti.

**Additional context**
La FE contenente la riga a 0 è accettata da SDI quindi la problematica è puramente estetica e non è un bug.
La questione è stata sollevata nella issue di integrazione tra FE e dichiarazione d'intento (vedi https://github.com/OCA/l10n-italy/issues/2516#issuecomment-1015303373) e contestualmente all'aggiunta del modulo **l10n_it_fatturapa_out_di** in v10 (vedi discussione da https://github.com/OCA/l10n-italy/pull/2596#issuecomment-1026318012).

**Versioni affette**
- [x] `10.0`: sì (risolta per termine supporto)
- [x] `12.0`: sì (risolta per termine supporto)
- [ ] `14.0`: sì
- [ ] `16.0`: sì

**Comment by TheMule71** [comment]
Altri gestionali aggiungono una riga note con campi vari. Spesso le aliquote sono "inventate", prendendole dalla riga precedente o - se non c'è - dalla successiva. Ecco un es. di due righe note:
![screen1](https://user-images.githubusercontent.com/915043/152550133-dbe02f97-6795-49f5-89b4-99ff51767775.png)
![screen2](https://user-images.githubusercontent.com/915043/152550151-b28a19b8-0374-4002-9326-322f9bb66e8a.png)
dalla stessa fattura. Notare come la prima riga, che rappresenta un DDT, essendo la riga n.1, prenda in prestito l'aliquota dalla successiva, anche se ovviamente non c'entra con la dichiarazione d'intento.
L'ulitma, invece, eredita N1 dalla precedente (il bollo) pur non c'entrando nulla, anzi riportanto (formato assosoftware) i dati della lettera d'intento.

Ovviamente, prendere in prestito un'aliquota esistente ha il vantaggio di non introdurre riepiloghi inattesi. Noi lo facciamo già per le altre righe note.

Per cui, la riga note aggiunta per le lettere d'intento potrebbe effettivamente avere N3.5.


L'altro approccio, di cui vorrei discutere, è eliminare la riga note, e duplicare AltriDatiGestionali per ciacuna riga. L'algoritmo sarebbe quindi:
1) prendi le dichiarazioni collegate (in testata o in dettaglio)
2) prendi quelle collegate alle righe (forzate)
3) fai la differenze insiemistica, e ottienie le dichiarazioni di sola testata
4) (a) per ogni riga, aggiungi, sotto forma di AltriDatiGestionali, le dichiarazioni forzate + quelle di testata
4) (b) per ogni riga, aggiungi, sotto forma di AltriDatiGestionali, le dichiarazioni forzare. Se non ci sono, metti quelle di testata.

Da scegliere tra l'opzione 4a) e la 4b).

**Comment by francesco-ooops** [comment]
@SirAionTech che tu sappia questa è stata risolta per qualche via laterale?

**Comment by SirAionTech** [comment]
> @SirAionTech che tu sappia questa è stata risolta per qualche via laterale?

No
