### ISSUE TITLE
doppie scritture per le fatture in regime di ritenuta d’acconto dopo doppia conferma

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#2637]
## Describe the bug

- [x] 12.0:? (chiusa per fine supporto)
- [ ] 14.0: https://github.com/OCA/l10n-italy/pull/2673
- [x] 16.0: https://github.com/OCA/l10n-italy/pull/3707

Riportando in bozza una fattura in regime di ritenuta d’acconto precedentemente già confermata, Odoo crea doppie righe nel prospetto Dichiarazione ritenuta d’acconto:
![fattura ritenuta d'acconto](https://user-images.githubusercontent.com/53826275/152544928-741c0719-7824-4925-b6d2-c2ab12276131.png)

Alla prima conferma:
![alla 1° conferma](https://user-images.githubusercontent.com/53826275/152545369-e5e46310-b583-4747-b0fb-9bc18fac78de.png)

Dopo aver riportato in bozza la fattura ed averla riconfermata:
![alla 2° conferma](https://user-images.githubusercontent.com/53826275/152545404-6bbed9c4-28f4-4820-ac3f-55dd48f5fc3c.png)

**Comment by Borruso** [comment]
Possibile soluzione #2673
Che ne pensate?

**Comment by eLBati** [comment]
Ma quindi questa è duplicata della https://github.com/OCA/l10n-italy/issues/3288 ?
