### ISSUE TITLE
Intestazione DDT ripetuta nelle righe della fattura

### ISSUE THREAD

**Issue by vincenzoriggi** [OCA/l10n-italy#2642]
## Module
l10n_it_delivery_note

## Describe the bug
Intestazione DDT ripetuta nelle righe della fattura

## To Reproduce
**Affected versions: 14.0**:

1. Creo un ordine cliente con più di due righe e lo confermo;
2. Consegno i prodotti;
3. Creo un nuovo DDT;
4. Dall'ordine creo la fattura di vendita
5. Nella fattura di vendita mi ritrovo l'intestazione dell DDT (DdT "2019/011" del 11/12/2019) ripetuta per ogni riga
--

**Expected behavior**
Avere una sola intestazione del DDT per tutte le righe

**Comment by MirkosoftAssistenza** [comment]
Confermo questo comportamento!

**Comment by SirTakobi** [comment]
In `12.0` questo viene gestito da https://github.com/OCA/l10n-italy/tree/6ef2e59847a0cc305b4789f4c017aaf51b70673e/account_invoice_report_ddt_group, ma ha a che fare con il _vecchio_ modo di generare i DdT (il modulo **l10n_it_ddt**) quindi non è immediato portarlo a `14.0`, dove invece viene usato un _nuovo_ modo di generare i DdT (il modulo **l10n_it_delivery_note**).
Chiedo ai maintainer di **l10n_it_delivery_note** @As400it e @Byloth, sapevate che questa funzionalità è sparita? Avete mica in programma di ripristinarla o sapete se ci sono discorsi aperti a riguardo?

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.

**Comment by SirTakobi** [comment]
È stato risolto da https://github.com/OCA/l10n-italy/pull/2346
