### ISSUE TITLE
l10n_it_vat_registries: Errore in stampa "Registro IVA fatture"

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2643]
## Module
l10n_it_vat_registries

## Describe the bug
Stampando il report "Registro IVA fatture" si ottiene l'errore:
```
[...]
  File "/home/odoo/build/OCA/l10n-italy/setup/l10n_it_vat_registries/odoo/addons/l10n_it_vat_registries/models/vat_registry.py", line 19, in _get_report_values
    date_format = data["form"]["date_format"]
KeyError: 'form'
```

## To Reproduce
**Affected versions**:
 - [x] 12.0 : "Registro IVA fatture" non c'è
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/2644

1. Aprire il form di una fattura
2. Nel menu contestuale, selezionare Stampa > "Registro IVA fatture"

**Expected behavior**
La stampa dalla fattura non ha senso perché il report è fatto per essere stampato da un wizard: la stampa deve essere rimossa

**Comment by eLBati** [comment]
> "Registro IVA fatture" non c'è

Come sarebbe?

**Comment by tafaRU** [comment]
@SirTakobi puoi verificare https://github.com/OCA/l10n-italy/issues/2643#issuecomment-1073179606?

**Comment by SirTakobi** [comment]
> @SirTakobi puoi verificare [#2643 (comment)](https://github.com/OCA/l10n-italy/issues/2643#issuecomment-1073179606)?

Riporto il commento:
> > "Registro IVA fatture" non c'è
>
> Come sarebbe?
> _Originally posted by @eLBati in https://github.com/OCA/l10n-italy/issues/2643#issuecomment-1073179606_

Ho provato in runboat gli step descritti nella issue:
> 1. Aprire il form di una fattura
> 2. Nel menu contestuale, selezionare Stampa > "Registro IVA fatture"

e confermo che
> "Registro IVA fatture" non c'è

screenshot:
![image](https://user-images.githubusercontent.com/101628000/168538025-f6bf63e2-3a57-40c6-a838-4420171cd244.png)

**Comment by tafaRU** [comment]
@SirTakobi @eLBati possiamo chiudere?
