### ISSUE TITLE
Import fattura pa modifica accuratezza decimale generale

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#2649]
Questa riga di codice compromette le impostazioni dei decimali ad ogni importazione di fattura elettronica,
si dovrebbe evitare questo comportamento ed optare per l'aggiornamento legato al partner della fattura in questione

https://github.com/OCA/l10n-italy/blob/6d2f62f94f44f7302bcd03c39f20f0aa2df50db2/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L1680

**Comment by TheMule71** [comment]
Per la cronaca, la issue originale di riferimento è la #2242, la PR la #2243. Quindi lo stesso codice è presente anche sulla 12.0 (la PR #1900 di migrazione di fatturapa_in è precedente ma è stata allineata prima del merge con 36467a5873daeb73b7d7776b1f90e722fabfac4c)

**Comment by scigghia** [comment]
grazie @TheMule71 
purtroppo il comportamento che riscontriamo è che a seguito di importazione i decimali restano modificati e non vengono ripristinati, provo a fare debug per capire se c'è qualcosa in più che posso aggiungere.
Vediamo intanto se lo riscontra qualcun altro

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
