### ISSUE TITLE
l10n_it_delivery_note | Stampa Report - Prodotto usa solo Riferimento Interno

### ISSUE THREAD

**Issue by MirkosoftAssistenza** [OCA/l10n-italy#2650]
## Module
l10n_it_delivery_note

- [ ] 14.0: https://github.com/OCA/l10n-italy/pull/3473
- [ ] 16.0: 

## Describe the bug
Buongiorno, nel modulo relativo ai DDT, quando vengono stampati i report nella colonna "Prodotto" non viene utilizzato il nome del Prodotto ma esclusivamente il Riferimento Interno. Il nome del Prodotto viene portato nella colonna "Descrizione".

## To Reproduce

Creare degli articoli senza riferimento interno, nella stampa non verrà popolato il campo "Prodotto" ma solamente quello di "Descrizione"

**Expected behavior**

Far stampare il nome dei prodotto insieme ai riferimenti interni nella colonna "Prodotto" oppure far scegliere il comportamento:
- Stampa il nome dei Prodotti e Riferimenti Interni
- Stampa solo il nome dei Prodotti

**Additional context**
Odoo 14.0 Versione Community - Latest Release and OCA Italy Latest Release

**Comment by aleuffre** [comment]
Fatta PR #3473 , da portare su v16 dopo approvazione

**Comment by tafaRU** [comment]
@MirkosoftAssistenza potete testare la https://github.com/OCA/l10n-italy/pull/3473?
