### ISSUE TITLE
Campo lineRef in l10n_it_fatturapa e l10n_it_fatturapa_out scrivibile

### ISSUE THREAD

**Issue by MirkosoftAssistenza** [OCA/l10n-italy#2651]
Quando all'interno di un ordine vado ad inserire nella scheda "Fattura Elettronica" un documento collegato di tipo "Ordine" posso scrivere una data ma non una riga di riferimento. Questo campo è impostato in sola lettura, forse perché è stato pensato per la lettura delle fatture elettroniche in ricezione.

Ho già provato a togliere il "read only" dalla Vista XML e funziona correttamente.
Esportando la fattura compare già il campo "RiferimentoNumeroLinea" all'interno di "DatiOrdineAcquisto" correttamente.

È possibile rimuovere il Read Only al campo "lineRef" e controllare sia tutto okay il resto?

Grazie mille!

**Comment by TheMule71** [comment]
Ho tracciato la storia, se ti riferisci a questo campo:
https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa/views/related_document_type_views.xml#L15
https://github.com/OCA/l10n-italy/blob/dbb00ab7988485a39428e8166a63ebe37d6e42dc/l10n_it_fatturapa/views/related_document_type_views.xml#L15
come vedi è qualcosa che viene dalla 12.0, e non è un bug introdotto in fase di porting.

Il problema esiste anche sulla 12.0 oppure lì c'è qualcos'altro altrove che sistema? mi pare di ricordare vagamente qualcosa visto all'epoca del porting, ma non riesco a trovarlo.

**Comment by MirkosoftAssistenza** [comment]
Mi riferisco proprio a quel campo lì, togliendo il "readonly" diventa scrivibile e le fatture vengono esportate correttamente.
Alla fine credevo mi servisse, ma pare sia facoltativo e basti la dichiarazione dell'ordine com'è già impostato adesso.

Grazie mille!
