### ISSUE TITLE
IMP spostare l'xsd dello schema di fatturapa in un modulo più generale (ad es. l10n_it_account)

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2654]
Issue nata da questa discussione:

https://github.com/OCA/l10n-italy/pull/2606#issuecomment-1034906436

Riassumo brevemente. Ci sono dei moduli (fuori da fatturapa) che codificano modelli con campi che vengono usati poi come valori nella generazione dell'XML. Ad es.:
`l10n_it_fiscal_document_type`
`l10n_it_fiscal_payment_term`
`l10n_it_rea`
(e potenzialmente altri)

Questi moduli caricano tabelle di istanze, coi codici predefiniti. Tuttavia, non impongono particolari controlli sui valori, consentendo all'utente di inserire valori non validi per lo SdI. Per capirci:
https://github.com/OCA/l10n-italy/blob/4fdb84b1da8885a4c4b18011d4bda4e44da3b58c/l10n_it_fiscal_document_type/models/fiscal_document_type.py#L8
è il codice da mettere nell'XML e non serve ad altro, ma rimane un campo libero (di 5 caratteri), e se vuole l'utente ci può mettere "pippo".

Spostando l'xsd in un modulo superiore, permetterebbe a questi moduli, volendo, di fare veriche e segnalare valori non validi (da scegliere se come errore, impedendo all'utente di proseguire, o come avvertimento e basta).

Consentirebbe anche di sviluppare test che verifichino che le tabelle caricate da questi moduli contangano valori validi e che non ne manchino.

Ho esplorato il modo (documentato) di estrarre i valori possibili di un tipo direttamente da xsd, e anche un modo (meno documentato) per estrarre le voci descrittive corrispondenti. Ciò ci permetterebbe di generare i dati precaricati con una funzione partendo da quelli validi dell'xsd, con tanto di label (ufficiali) (vd. https://github.com/OCA/l10n-italy/pull/2606#issuecomment-1036236499)

**Comment by TheMule71** [comment]
Per fiscal_document_type:
- si può implementare un controllo a livello di test
- va resa non modificabile la tabella

**Comment by SirTakobi** [comment]
> Per fiscal_document_type, si può implementare un controllo a livello di test e va resa non modificabile la tabella:
> 
> * [ ]  12.0 [[12.0] l10n_it_fiscal_document_type non deve essere possibile creare o modificare i tipi #2819](https://github.com/OCA/l10n-italy/pull/2819)
> * [ ]  12.0 (controllo test)
> * [ ]  14.0 [[14.0] [IMP] move FPA Schema xsd to l10n_it_account #2820](https://github.com/OCA/l10n-italy/pull/2820)
> * [ ]  14.0


Le modifiche nella PR #2819 non hanno nulla in comune con quelle fatte in #2820 quindi non credo sia corretto considerarle entrambe un'implementazione di questa problematica.

Separerei quindi le problematiche in:

- questa per tracciare quanto fatto in #2820
- https://github.com/OCA/l10n-italy/issues/3532 per tracciare la non modificabilità dei tipi di documento fiscale

**Comment by primes2h** [comment]
> > Per fiscal_document_type, si può implementare un controllo a livello di test e va resa non modificabile la tabella:
> > 
> > * [ ]   12.0 [[12.0] l10n_it_fiscal_document_type non deve essere possibile creare o modificare i tipi #2819](https://github.com/OCA/l10n-italy/pull/2819)
> > * [ ]   12.0 (controllo test)
> > * [ ]   14.0 [[14.0] [IMP] move FPA Schema xsd to l10n_it_account #2820](https://github.com/OCA/l10n-italy/pull/2820)
> > * [ ]   14.0
> 
> Le modifiche nella PR #2819 non hanno nulla in comune con quelle fatte in #2820 quindi non credo sia corretto considerarle entrambe un'implementazione di questa problematica.
> 

Concordo.

> Separerei quindi le problematiche in:
> 
>     * questa per tracciare quanto fatto in [[14.0] [IMP] move FPA Schema xsd to l10n_it_account #2820](https://github.com/OCA/l10n-italy/pull/2820)

Ho aggiunto la PR corretta per la 12.0 https://github.com/OCA/l10n-italy/issues/2654#issuecomment-1139428400

>     * [Non deve essere possibile creare o modificare i tipi di documento fiscale #3532](https://github.com/OCA/l10n-italy/issues/3532) per tracciare la non modificabilità dei tipi di documento fiscale

Ho aggiunto i riferimenti alle varie PR chiuse in precedenza, in modo da mantenere la cronologia delle operazioni.

**Comment by francesco-ooops** [comment]
@primes2h per 14/16 c'è qualcosa da fare relativo a questa issue?

**Comment by primes2h** [comment]
> @primes2h per 14/16 c'è qualcosa da fare relativo a questa issue?

La migrazione alla 16.0 mi pare sia iniziata dopo il merge della PR per la 14.0 quindi in teoria dovrebbe essere ok.

Però la problematica di #3532 è parte di questa issue, come indicato in fondo alla descrizione https://github.com/OCA/l10n-italy/issues/3532#issue-1861350807.
