### ISSUE TITLE
l10n_it_ddt: Errore all'aggiornamento

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2667]
## Module
`l10n_it_ddt`

## Describe the bug
Aggiornando il modulo in oggetto viene sollevato l'errore:
```
2022-02-17 00:00:00,000 97568 ERROR db_name odoo.modules.registry: Failed to load registry 
[...]
ValueError: Il campo `show_price` non esiste
```

## To Reproduce
**Affected versions**:

1. Installare `l10n_it_ddt` con versione precedente a `12.0.1.7.1`
2. Creare una vista che eredita da `l10n_it_ddt.ddt_stock_picking_package_preparation_form`
2. Aggiornare il modulo `l10n_it_ddt` con una versione successiva a `12.0.1.7.1`

**Expected behavior**
L'aggiornamento del modulo

**Additional context**
Durante l'esecuzione della migrazione https://github.com/OCA/l10n-italy/blob/ff2efb0c7a2ee7a954b034734253d261ce6a4df1/l10n_it_ddt/migrations/12.0.1.7.1/pre-migrate.py#L20 la vista non viene eliminata a causa di:
```
2022-02-17 00:00:00,000 97568 ERROR db_name odoo.sql_db: bad query: DELETE FROM ir_ui_view WHERE id IN (1332)
ERROR: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
DETAIL:  Key (id)=(1332) is still referenced from table "ir_ui_view".
```

**Work-around**
Eliminare la vista creata prima dell'aggiornamento del modulo `l10n_it_ddt`.

**Comment by SirAionTech** [comment]
Chiudo perché l'unica versione affetta non è più supportata
