### ISSUE TITLE
Invio e-fatture OSS: va impostata la natura dell'IVA

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#2668]
## Module
l10n_it_fatturapa_out

## Describe the bug
Le e-fatture vengono generate senza natura dell'imposta

## To Reproduce
**Affected versions**:
 - [x] 12.0 https://github.com/OCA/l10n-italy/pull/2688
 - [ ] 14.0
 - [ ] 16.0

1. emettere una fattura in regime OSS (vendita a privato intracee)
2. esportare l'xml per l'invio tramite SdI

**Expected behavior**
La e-fattura dovrebbe avere il codice natura dell'imposta N3.2

**Comment by sergiocorato** [comment]
[CS-22102021-OSS-IOSS.pdf](https://github.com/OCA/l10n-italy/files/8154832/CS-22102021-OSS-IOSS.pdf)

**Comment by francesco-ooops** [comment]
Chiudo perchè da gestire nelle issue di migrazione
