### ISSUE TITLE
l10n_it_reverse_charge: Estendere documentazione

### ISSUE THREAD

**Issue by SimoRubi** [OCA/l10n-italy#2670]
**Is your feature request related to a problem?**
no

**Describe the solution you'd like**
Una documentazione che descriva il funzionamento del modulo in oggetto tramite la descrizione di come gestire i casi d'uso più frequenti.

**Describe alternatives you've considered**
Si potrebbe migliorare il README attuale, oppure creare un documento esterno da linkare nel README.

**Comment by marco-marchiori** [comment]
Ok, dobbiamo descrivere il modulo attuale: ma nella prospettiva di utilizzarlo o per discutere il refactoring proposto nell'altro thread (evidenziando cioè le limitazioni ed i problemi)?

**Comment by SimoRubi** [comment]
> Ok, dobbiamo descrivere il modulo attuale: ma nella prospettiva di utilizzarlo o per discutere il refactoring proposto nell'altro thread (evidenziando cioè le limitazioni ed i problemi)?

Partirei descrivendo il funzionamento del modulo per com'è adesso; se poi verranno fatti nuovi sviluppi, la documentazione andrebbe aggiornata di conseguenza.
Stamattina in chiamata @stevech091 diceva che forse esiste già qualcosa per le versioni vecchie ma non ho trovato nulla.

Per facilitare l'allineamento tra il codice e la documentazione e problemi di link che scadono o simili, preferirei avere tutto nel README.

**Comment by zeroincombenze** [comment]
Ho inserito i primi appunti qui
https://docs.google.com/document/d/1C7LB2d1jOd7jJc9UA84h07EBjDFWJGjB-kYmRKEJUXw/edit#

**Comment by eLBati** [comment]
Abbiamo scritto qui
https://docs.google.com/document/d/1C7LB2d1jOd7jJc9UA84h07EBjDFWJGjB-kYmRKEJUXw/edit#heading=h.q7xrlcclcowg
l'implementazione di cui avevamo parlato nelle chiamate

Il punto 4 non richiede modifiche, giusto @sergiocorato ?

Resterebbe da implementare solo il punto 6, giusto @TheMule71 ?

**Comment by TheMule71** [comment]
> Resterebbe da implementare solo il punto 6, giusto @TheMule71 ?

Esatto.

**Comment by vincenzoterzulli** [comment]
**Aggiungo una nota riguardo liquidazione IVA e RC** 
Nei casi di configurazione di acquisti INTRA ed EXTRA CEE, bisogna anche configurare opportunamente le imposte da utilizzare nelle fatture fornitore, impostando che il relativo CONTO IMPONIBILE (campo m2o base_code_id) deve essere **ESCLUSO DAL REGISTRO IVA**. Se non viene fatto, tale imposta viene riportata anche nel report della liquidazione IVA, e sembra che il valore della merce/servizi acquistata da INTRA ed EXTRA si raddoppia....
**La soluzione è attualmente al vaglio, potrebbero esserci altre alternative percorribili.**

Se ne è parlato anche nel gruppo Sviluppo qui https://discord.com/channels/753902328494424064/753902328494424070/1006871240478306344

Esempio:
![image](https://user-images.githubusercontent.com/16492632/184114429-77e438c3-1799-4b1c-a0ef-1a21e6894d82.png)
