### ISSUE TITLE
l10n_it_split_payment the line disappear and the line_ids are unbalanced

### ISSUE THREAD

**Issue by micheledic** [OCA/l10n-italy#2672]
## Module
l10n_it_split_payment

- [ ] 12.0: ?
- [ ] 14.0: https://github.com/OCA/l10n-italy/pull/2515

## Describe the bug
If you fully configure split_payment module, if you try to create a customer invoice using a partner with a fiscal position "split payment" the line on the first tab goes away and the lines in "Journal items" are not balanced. I have already tried to merge the PR #2515  but the issue is still there.
I tried to debug the code , if in file l10n_it_split_payment/models on line  131 i try to put the line "self.set_receivable_line_ids()" after "            if self.amount_sp:
                self.line_ids = [(0, 0, write_off_line_vals)]" , the line on first tab doesn't disappear , the values are correct on joirnal items but when i save , it generated two different lines with "is_split_payment = True" and appears the error that lines are not balanced.

## To Reproduce

1. install l10n_it_split_payment
2. configure
3. try to create an invoice of partner with split payment fiscal position

**Expected behavior**
the line on first tab should be there and the journal items balanced

**Comment by matteoopenf** [comment]
qualcuno ci sta lavorando? anche io ho un errore su una fattura PA, non identico tuttavia credo sia correlato

**Comment by letyf1988** [comment]
Ciao,
ho provato anche io la PR e mi continua con le scritture non bilanciate. Tuttavia ho fatto delle piccole modifiche, sto testando ma sembra funzionare. 
Ho modificato come segue i due metodi:


  
 
    def _build_debit_line(self):
        if not self.company_id.sp_account_id:
            raise UserError(
                _(
                    "Please set 'Split Payment Write-off Account' field in"
                    " accounting configuration"
                )
            )
        vals = {
            "name": _("Split Payment Write Off"),
            "partner_id": self.partner_id.id,
            "account_id": self.company_id.sp_account_id.id,
            "journal_id": self.journal_id.id,
            "date": self.invoice_date,
            "price_unit": -self.amount_sp,
            "amount_currency": self.amount_sp,
            "debit": self.amount_sp,
            "credit": 0.0,
            "exclude_from_invoice_tab": True,
            "is_split_payment": True,
        }
        if self.move_type == "out_refund":
            vals["amount_currency"] = -self.amount_sp
            vals["debit"] = 0.0
            vals["credit"] = self.amount_sp
        return vals

    
    def set_receivable_line_ids(self):
        """Recompute all account move lines by _recompute_dynamic_lines()
        and set correct receivable lines
        """
        self._recompute_dynamic_lines()
        line_client_ids = self.line_ids.filtered(
            lambda l: l.account_id.id
            == self.partner_id.property_account_receivable_id.id
        )
        if self.move_type == "out_invoice":
            for line_client in line_client_ids:
                inv_total = self.amount_sp + self.amount_total
                if inv_total:
                    receivable_line_amount = (self.amount_total * line_client.debit) / inv_total
                else:
                    receivable_line_amount = 0.0
                line_client.with_context(check_move_validity=False).update(
                    {
                     "debit": receivable_line_amount,
                     "amount_currency":receivable_line_amount,
                     "price_unit":-receivable_line_amount,
                      
                    }
                )
        elif self.move_type == "out_refund":
            for line_client in line_client_ids:
                inv_total = self.amount_sp + self.amount_total
                if inv_total:
                    receivable_line_amount = (
                        self.amount_total * line_client.credit
                    ) / inv_total
                else:
                    receivable_line_amount = 0.0
                line_client.with_context(check_move_validity=False).update(
                    {
                      "credit": receivable_line_amount,
                      "amount_currency":-receivable_line_amount,
                      "price_unit":receivable_line_amount,
                    }
                )


    def _compute_split_payments(self):
        write_off_line_vals = self._build_debit_line()
        line_sp = self.line_ids.filtered(lambda l: l.is_split_payment or l.name == _("Split Payment Write Off"))
        if line_sp:
            if self.move_type == "out_invoice" and float_compare(
                line_sp[0].debit,
                write_off_line_vals["debit"],
                precision_rounding=self.currency_id.rounding,
            ):
                line_sp[0].with_context(check_move_validity=False).update(
                    {
                        #"price_unit": 0.0,
                        "amount_currency": 0.0,
                        "debit": 0.0,
                       # "credit": 0.0,
                    }
                )
                self.set_receivable_line_ids()
                line_sp[0].debit = write_off_line_vals["debit"]
            elif self.move_type == "out_refund" and float_compare(
                line_sp[0].credit,
                write_off_line_vals["credit"],
                precision_rounding=self.currency_id.rounding,
            ):
                line_sp[0].with_context(check_move_validity=False).update( {
                       
                        "credit": 0.0,
                    }
                )
                self.set_receivable_line_ids()
                line_sp[0].credit = write_off_line_vals["credit"]
        else:
            self.set_receivable_line_ids()
            if self.amount_sp:
                self.line_ids = [(0, 0, write_off_line_vals)]

**Comment by rbellanova** [comment]
Anche io ho riscontrato lo stesso errore... DB pulito.. Configurazione effettuata come da guida e quando si aggiungere una riga d'ordine "sparisce" e i movimenti contabili non sono bilanciate

**Comment by TheMule71** [comment]
Probabilmente legata alla #2753 

Si tratta di una modifica introdotta recentemente in core. Vd. descrizione della patch.

La PR non sistema il problema, rende solo mergiabili eventuali altre PR, perché adesso hanno tutte i test rossi.

Nella PR è indicato il commit che crea il problema.

**Comment by TheMule71** [comment]
Sono stato un po' criptico, quello che intendevo dire è che in odoo stanno evidentemente toccando quella parte del codice, anche a costo di spaccare altre cose.

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.

**Comment by SirTakobi** [comment]
@tafaRU abbiamo riscontrato questo problema durante formazione Venerdì.
Esiste https://github.com/OCA/l10n-italy/pull/2515 per correggere, ma sembra avere ancora problemi.
cc @Borruso

**Comment by tafaRU** [comment]
@TheMule71 ho già aggiornato https://docs.google.com/spreadsheets/d/1wLAzwlB8kP1n9kPGaCINVPoH1XJQJ-stIbjuqEUPt-k

**Comment by SirAionTech** [comment]
Ho provato in runboat e il problema non esiste in `16.0`: 

https://github.com/OCA/l10n-italy/assets/143788994/c768655f-9798-4f23-959d-3a76c7ec4f76



@micheledic puoi verificare anche tu o anche solo vedere se ho fatto tutto correttamente?
