### ISSUE TITLE
Timeout nella generazione dei registri IVA quando ci sono molte righe

### ISSUE THREAD

**Issue by parsifino** [OCA/l10n-italy#2676]
## Module
[l10n_it_vat_registries](https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_vat_registries)

## Describe the bug
La generazione dei registri iva va in timeout quando ci sono molte righe (pur dimensionando bene il server)

## To Reproduce
**Affected versions**:
Tutte

1. Rendicontazione -> registri IVA
2. Inserire date (range ampio, es. 01/01 a 31/12
3. Stampa

**Expected behavior**
Generazione del registro IVA. Si ottiene invece un timeout. Dovrebbe essere possibile processare il report in background

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
ti conviene generare per mese, whtmltopdf genera delle query grandi, non so se altri hanno suggerimenti, passa magari alla versione Excel che sicuramente non è affetta dal problema

**Comment by parsifino** [comment]
@matteoopenf grazie mille, gentilissimo. Il modulo attualmente permette solo la stampa in PDF (Odoo 12.0 e l10n_it_vat_registries versione 12.0.1.2.4). 
Che intendi per "passare alla versione excel"? 

Inoltre, non c'è un modo per generare i report in background in modo asincrono e poi scaricarli in seguito?

Nel caso, se può avere senso, potrei contribuire a svilupparlo: mi sembra necessario per aziende con molte transazioni (ad es. ecommerce internazionali con carrello medio 10-50$)

Grazie ancora!

**Comment by matteoopenf** [comment]
> @matteoopenf grazie mille, gentilissimo. Il modulo attualmente permette solo la stampa in PDF (Odoo 12.0 e l10n_it_vat_registries versione 12.0.1.2.4). Che intendi per "passare alla versione excel"?
> 
> Inoltre, non c'è un modo per generare i report in background in modo asincrono e poi scaricarli in seguito?
> 
> Nel caso, se può avere senso, potrei contribuire a svilupparlo: mi sembra necessario per aziende con molte transazioni (ad es. ecommerce internazionali con carrello medio 10-50$)
> 
> Grazie ancora!

Ciao, ho confuso con un altro export.
SI è possibile farlo, facendo qualche cambiamento al metodo che genera il pdf e usando queue
https://github.com/OCA/queue/tree/12.0

**Comment by parsifino** [comment]
Verifico subito, grazie mille, sono in debito! 🙏

**Comment by matteoopenf** [comment]
> Verifico subito, grazie mille, sono in debito! pray

Di Nulla Buon Lavoro

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
