### ISSUE TITLE
Import Fattura elettronica: Partner duplicati per partita iva estera che inizia con lo ZERO

### ISSUE THREAD

**Issue by alessandrocamilli** [OCA/l10n-italy#2679]
## Module

- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/2682
- [ ] 16.0

## Describe the bug
Quando uno dei partner di riferimento della fattura elettronica (fornitore, terzo intermediario) ha una partita iva nel formato:
SM03473
dove dopo l'id del paese c'è uno zero, quando viene creato in Odoo la partita iva diventa SM3473.
Questo comporta poi che alla successiva reimportazione il partner non venga trovato e creato nuovamente.

## To Reproduce
**Affected versions**:

1. Creare un partner con la seguente partita IVA: SM03473
2. Generare 2 fattura cliente e reimportarle in un altro ambiente come fattura fornitore.
3. Dopo averle importate entrambe, tra i contatti il partner con la partita iva SM3473 sarà duplicato

**Comment by TheMule71** [comment]
Vd. https://github.com/OCA/l10n-italy/pull/2682#issuecomment-1048198987

**Comment by TheMule71** [comment]
Aggiungo questo: https://github.com/OCA/l10n-italy/pull/984#discussion_r255481856

In sostanza, lo SdI controlla in alcuni casi e non in altri. In particolare, il TerzoIntermediario. Il fatto è che probabilmente creare un contatto per il TerzoIntermediario è un po' overkill.
