### ISSUE TITLE
[14.0] l10n_it_fatturapa_sale: "e_invoice" group visibility on sale order line

### ISSUE THREAD

**Issue by rbellanova** [OCA/l10n-italy#2689]
I would like to suggest an improvement to the "_l10n_it_fatturapa_sale_" module, specifically in this group: 
[https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_sale/views/sale_order_views.xml#L19](https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_sale/views/sale_order_views.xml#L19) , 
to add a `attrs = "{'invisible': [('display_type', '! =', False)]}"` so that when you go to add a section or a note in the order lines you do not see the electronic invoicing section, which should only appear when adding a product.

**Comment by tafaRU** [comment]
Ciao @rbellanova, feel free to open a PR, thanks!

**Comment by rbellanova** [comment]
Ok Alex, thank you for the answer
