### ISSUE TITLE
Creazione DDT da trasferimento senza documento origine

### ISSUE THREAD

**Issue by CiroBoxHub** [OCA/l10n-italy#2711]
Versioni coinvolte:

- [x] 14.0 - https://github.com/OCA/l10n-italy/pull/2569
- [ ] 12.0 ???

Comportamento atteso:
La creazione di un ddt deve essere possibile anche da un trasferimento (picking) anche se questo non deriva necessariamente da un ordine di vendita

Comportamento attuale:

il sistema va in errore alla riga linkata in quanto, se sale_order_id è False la funzione non può essere richiamata

https://github.com/OCA/l10n-italy/blob/48e78c00b31eca8ab114d10777c6169d7715d6a1/l10n_it_delivery_note/wizard/delivery_note_create.py#L103

```
File "/opt/odoo/odoo14/repos/l10n-italy/l10n_it_delivery_note/wizard/delivery_note_create.py", line 103, in confirm
    sale_order_id._assign_delivery_notes_invoices(sale_order_id.invoice_ids)
Exception
AttributeError: 'bool' object has no attribute '_assign_delivery_notes_invoices'
```

Risoluzione proposta:
Temporaneamente sull'istanza ho risolto aggiungendo un 
```
if sale_order_id:
``` 
prima della riga 103 in modo da far eseguire la funzione sole se il dato richiesto è presente.

**Comment by CiroBoxHub** [comment]
@fredzamoabg volevo segnalarti questa issue. Il commit che inserisce la riga sopra citata è questo:
https://github.com/OCA/l10n-italy/commit/fd61d041a6c040b4bd7778defd8c0a0e75d3e5e9

**Comment by fredzamoabg** [comment]
> @fredzamoabg volevo segnalarti questa issue. Il commit che inserisce la riga sopra citata è questo: [fd61d04](https://github.com/OCA/l10n-italy/commit/fd61d041a6c040b4bd7778defd8c0a0e75d3e5e9)

ciao @CiroBoxHub, direi che hai proprio ragione anche in base a questo:
https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_delivery_note/wizard/delivery_note_create.py#L73

Credo tu possa proporre una PR con la modifica (quella che hai indicato come proposta dovrebbe andare più che bene)
grazie.

**Comment by TheMule71** [comment]
Nel frattempo io avevo iniziato a lavorare a questo: #2710

L'attuale modulo per il DDT si tira dietro account e sale. In realtà, sarebbe possibile creare un DDT da picking direttamente, senza avere un ordine di vendita e senza avere una fattura.

La mia idea era rendere `l10n_it_delivery_note` indipendente da `sale` e `account` e poi fare un modulo `l10n_it_delivery_note_account` con l'integrazione degli altri due moduli... se non ricordo male ho visto anche la necessità di creare una fattura senza passare dall'SO (non ricordo se è stata integrata o è ancora una PR).

Probabilmente ha senso fare due moduli, `l10n_it_delivery_note_account` e `l10n_it_delivery_note_sale`.

**Comment by As400it** [comment]
Ciao a tutti 
https://github.com/OCA/l10n-italy/pull/2569/files 

questa pr mergiata fresca fresca dovrebbe risolvere il problema. 

se si chiudi  la issue . 

a presto Marco

**Comment by CiroBoxHub** [comment]
> Ciao a tutti https://github.com/OCA/l10n-italy/pull/2569/files
> 
> questa pr mergiata fresca fresca dovrebbe risolvere il problema.
> 
> se si chiudi la issue .
> 
> a presto Marco

Ciao Marco, si credo proprio che questa risolva lo stesso problema sulla 14.0
C'e da fare la stessa correzione per la versione 12.0

provvedi tu dato che hai già i repo impostati?

**Comment by Borruso** [comment]
> @Borruso puoi provvedere tu dato che hai già i repo impostati?

sulla versione 12.0 non dovrebbe esserci il problema dato che la PR #2497 non è stata fatta per la 12.0

**Comment by CiroBoxHub** [comment]
ok perfetto @Borruso grazie mille! Per me la issue si può chiudere

**Comment by As400it** [comment]
@CiroBoxHub  credo che la issue la dovresti chiudere tu. 
a me non lo fa fare.
