### ISSUE TITLE
<l10n_it_dichiarazione_intento> Funzione "Dichiarazione d'Intento"  non visibile da menù

### ISSUE THREAD

**Issue by rcaboni** [OCA/l10n-italy#2713]
l10n_it_dichiarazione_intento

Buongiorno,
  qualcuno ha idea del perché non vedo nella sezione Contabilità l'opzione "Dichiarazione d'Intento" ?
  
  Il modulo sembra installato:
  
(odoo12) odoo@ubuntu18:~/odoo12$ pip list | grep odoo
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
odoo (12.0.post20190504)
odoo12-addon-account-fiscal-year (12.0.1.0.0.99.dev18)
odoo12-addon-account-payment-term-extension (12.0.1.2.1)
odoo12-addon-account-tax-balance (12.0.1.1.1)
odoo12-addon-date-range (12.0.1.0.0.99.dev19)
odoo12-addon-l10n-it-account (12.0.1.4.3)
odoo12-addon-l10n-it-account-tax-kind (12.0.2.0.0)
odoo12-addon-l10n-it-causali-pagamento (12.0.2.0.0)
odoo12-addon-l10n-it-ddt (12.0.1.9.0)
odoo12-addon-l10n-it-dichiarazione-intento (12.0.0.2.0)
odoo12-addon-l10n-it-esigibilita-iva (12.0.2.0.0)
odoo12-addon-l10n-it-fatturapa (12.0.2.0.2)
odoo12-addon-l10n-it-fatturapa-in (12.0.2.1.4)
odoo12-addon-l10n-it-fatturapa-out (12.0.2.1.1)
odoo12-addon-l10n-it-fatturapa-out-ddt (12.0.1.1.4)
odoo12-addon-l10n-it-fatturapa-out-di (12.0.1.0.0.99.dev5)
odoo12-addon-l10n-it-fatturapa-pec (12.0.1.8.0)
odoo12-addon-l10n-it-fiscal-document-type (12.0.2.0.1)
odoo12-addon-l10n-it-fiscal-payment-term (12.0.2.0.0)
odoo12-addon-l10n-it-fiscalcode (12.0.1.1.3)
odoo12-addon-l10n-it-ipa (12.0.1.0.2)
odoo12-addon-l10n-it-rea (12.0.1.0.3)
odoo12-addon-l10n-it-sdi-channel (12.0.1.3.3)
odoo12-addon-l10n-it-split-payment (12.0.1.0.1)
odoo12-addon-l10n-it-withholding-tax (12.0.2.0.0)
odoo12-addon-l10n-it-withholding-tax-causali (12.0.2.0.0)
odoo12-addon-partner-firstname (12.0.1.1.0)
odoo12-addon-stock-picking-package-preparation (12.0.1.0.0.99.dev13)
odoo12-addon-stock-picking-package-preparation-line (12.0.1.0.1.99.dev7)
(odoo12) odoo@ubuntu18:~/odoo12$

![contabilita](https://user-images.githubusercontent.com/2706481/159448051-e987789e-400a-4599-8686-e2e661af60a9.jpg)

**Comment by eLBati** [comment]
![image](https://user-images.githubusercontent.com/1033131/161477987-cc118c62-b7df-4487-b24c-2829be4a4329.png)

Non rilevo problemi

**Comment by rcaboni** [comment]
Non avevo dubbi che su altre installazioni il pacchetto Dichiarazioni di Intento funzionasse. 
Chiedevo aiuto sulla mia installazione, forse ho dimenticato qualcosa da configurare.
Mi sembra di avere installato tutti i moduli necessari.

**Comment by eLBati** [comment]
Qui si lavora su bachi e nuove funzionalità.

Se hai bisogno di supporto puoi provare a chiedere su https://discord.gg/pYtJvc97Hz
