### ISSUE TITLE
14.0 Fattura verso PA splitpayment

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2714]
## Module
l10n_it_fatturapa_out

## Describe the bug
Creare una fattura verso la pubblica amministrazione, validarla e fare l'esportazione e si otterrà due volte il tag:
ImportoTotaleDocumento

## To Reproduce
Creare una fattura verso la pubblica amministrazione, validarla e fare l'esportazione e si otterrà due volte il tag:
ImportoTotaleDocumento

**Affected versions**:

- [ 14.0]  https://github.com/OCA/l10n-italy/pull/2717

1. prendere un partner che è una PA
2. creare una fattura a suo nome
3. tentare l'esportazione

**Expected behavior**
un solo tag per ImportoTotaleDocumento

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
attualmente se esporto ho questo:
  <DatiGeneraliDocumento xmlns:ns1="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2"><TipoDocumento>TD01</TipoDocumento><Divisa>EUR</Divisa><Data>2022-03-16</Data><Numero>FV1/2022/0313</Numero><ImportoTotaleDocumento>286.65</ImportoTotaleDocumento><ImportoTotaleDocumento>349.71</ImportoTotaleDocumento></DatiGeneraliDocumento>

**Comment by matteoopenf** [comment]
> Per cortesia controlla se #2563 risolve.

ma questa parla della conversione euro e in valuta, ora guardo comunque

**Comment by TheMule71** [comment]
Il problema è sempre quello. Si va a modificare ImportoTotale a seconda di condizione esterne.

Vale anche per la conversione in euro, visto che ad un certo punto è stata chiesta la possibilità di convertire tutto (che la PR faceva già), oppure tutto **tranne** l'ImportoTotale, e la cosa viene decisa da un flag.

Al quel punto, ci sarebbero stati fpa_out, fpa_out_rc, fpa_out_sp  tutte e tre i moduli che mettevano degli `<t if="">` nel template nello stesso punto, e la cosa diventava complicata da gestire a livello qweb (vanno gestite tutte le combinazioni). Oppure vanno messe dipendenze artificiali, in modo che l'ultimo modulo faccia tutte le permutazioni possibili.

Come approccio migliore, ho creato un metodo all'interno del wizard, che i veri moduli possono estendere a piacere, modificando il valore che viene riportato nell'XML.

**Comment by TheMule71** [comment]
> Pensi verrà mergiata a breve?

Magari.

Anche io ho una PR con la stessa modifica (fattura in valuta) per la 12, la tenevo bloccata in attesa che approvassero quella per la 14, e poi avrei backportato tutte le funzionalità.

**Comment by matteoopenf** [comment]
> > Pensi verrà mergiata a breve?
> 
> Magari.
> 
> Anche io ho una PR con la stessa modifica (fattura in valuta) per la 12, la tenevo bloccata in attesa che approvassero quella per la 14, e poi avrei backportato tutte le funzionalità.

l'ho approvata dimmi se posso aiutarti in altro modo così portiamo a termine la cosa

**Comment by TheMule71** [comment]
Per me è pronta, vediamo che dice @eLBati .

**Comment by matteoopenf** [comment]
> Per me è pronta, vediamo che dice @eLBati .

ok. Grazie Mille!

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
