### ISSUE TITLE
determinazione della posizione fiscale nell'import della fattura passiva

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#2715]
**Is your feature request related to a problem?**
attualmente in fatturapa_in la posizione fiscale e' letta direttamente dall'anagrafica del fornitore. Suggerirei invece di determinare la posizione fiscale utilzzando la function standard

**Describe the solution you'd like**
determinazione della posizione utilizzando la function standard
fiscal_position_id = self.env['account.fiscal.position'].get_fiscal_position(partner_id) 

**Describe alternatives you've considered**

**Additional context**
Add any other context about the feature request here.

- [x] 12.0 da fare (risolta per termine supporto)
- [x] 14.0 #2730 
- [x] 16.0 #3000

**Comment by TheMule71** [comment]
Ciao, grazie per la segnalazione.
Potresti spiegare meglio l'impatto pratico del problema? Ossia in quali casi fa differenza e perché usare `.get_fiscal_position()` dà un risultato migliore?

**Comment by ccandito** [comment]
e' lo standard Odoo. In questo modo non sei obbligato a specificare la posizione fiscale nell'anagrafica del fornitore ma vieen invece derivata.
prova a inserire una fattura passiva manualmente per un fornitore senza posizione fiscale e vedi che il sistema di valorizza la posizione fiscale in fattura derivandola dalla country code in anagrafica del fornitore.

**Comment by TheMule71** [comment]
Ok, ma quella che descrivi è la parte che funziona.

Non mi è chiaro quale è la parte che NON funziona.  In altre parole perché in fase di importazione di una fattura dovrebbe ignorare la posizione fiscale presente nell'anagrafica fornitori?

**Comment by TheMule71** [comment]
Task list:
- [ ] 12.0 - da fare
- [ ] 14.0 - #2730

**Comment by ccandito** [comment]
grazie

**Comment by vincenzoterzulli** [comment]
In Italia come sappiamo esistono diverse posizioni fiscali (generica, con ritenuta 1040, ritenuta 1038, enasarco, ecc).
Il metodo `get_fiscal_position` però restituisce semplicemente la prima che trova nello stato di pertinenza e questo potrebbe creare problemi in caso di importazioni di fatture con ritenute ad esempio.
Siamo sicuri che sia la cosa giusta da fare?

**Comment by TheMule71** [comment]
Beh, prende quella impostata nel partner.

https://github.com/OCA/OCB/blob/694cea7f9314a6e36c0c84503c3d1d2970901ac6/addons/account/models/partner.py#L184-L186

Se manca, allora va a prenderne una in base a stato/provincia. 

Se non ho capito male, stai suggerendo di creare un'euristica per determinare sulla base della tipologia della fattura (per dire, con/senza ritenuta) un criterio di ricerca delle posizioni fiscali, per scegliere quella che si adatta meglio?
