### ISSUE TITLE
[IMP] l10n_it_fatturapa_out, add transmitter partner for the company

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2721]
Aggiunge il trasmittente come partner configurabile per company, modifica del template xml in modo che venga inserito alla creazione dello stesso; come `default` viene utilizzato il partner della company.

- [x] 12.0 #2984 (risolta per termine supporto)
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/2720 
- [x] 16.0 #2996

**Comment by OpenCode** [comment]
La 12.0 è affetta dallo stesso problema?

**Comment by eLBati** [comment]
Più che un problema è una nuova funzionalità, comunque sì

**Comment by SirAionTech** [comment]
Si può chiudere perché #2720 è stata portata a `16.0` con la migrazione https://github.com/OCA/l10n-italy/pull/2996: il commit di #2720 è https://github.com/OCA/l10n-italy/pull/2720/commits/1a5a91c8ea7a0df8651a17c4256f43e75a9f1cf1, in `16.0` è https://github.com/OCA/l10n-italy/pull/2996/commits/deab0563d79141e19931656575fa58d629a8db36.
