### ISSUE TITLE
[RFC] refactoring l10n_it_corrispettivi, integrazione con ricevute Odoo

### ISSUE THREAD

**Issue by primes2h** [OCA/l10n-italy#2722]
**Versioni coinvolte**

- [ ] 14.0 https://github.com/OCA/account-invoicing/pull/1260 + https://github.com/OCA/account-invoicing/pull/1267
Funzionalità non ancora migrate:
https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_portal_corrispettivi
https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_sale_corrispettivi

**Descrizione**

Dalla versione 13.0 di Odoo le ricevute sono state integrate nel modulo `account` diventando una `move_type` alla pari di fatture e note di credito:

https://github.com/odoo/odoo/blob/5b099bf6135b2ff517078d1839b513da7830f718/addons/account/models/account_move.py#L154-L163

Per visualizzarle basta solo abilitarle nelle impostazioni dell'utente (caselle `Ricevute di vendita` e `Ricevute di acquisto`).

Alla luce di questo sarebbe importante valutare l'opportunità di utilizzare le funzionalità native messe a disposizione da Odoo che coprono gran parte di quelle presenti in `l10n_it_corrispettivi`.

### Modulo `l10n_it_corrispettivi`
Da una prima analisi le viste (riportate anche qui sotto) sono già presenti nel modulo `account`:

https://github.com/OCA/l10n-italy/blob/0709ef90a161a0e70740409a0d5a7496a075a360/l10n_it_corrispettivi/views/account_view.xml#L7-L76

La parte di stampa, con relativo report sarebbe già coperta da questa PR:

https://github.com/OCA/account-invoicing/pull/849

Alla luce di ciò sarebbe sufficiente un piccolo modulo base che aggiunge i campi di l10n_it_corrispettivi nel journal, nel partner e nella fiscal position e poco altro. (non sarebbe neanche strettamente necessario che tale modulo stia in `l10n_it_italy`).

L'integrazione delle funzionalità consentirebbe anche il riutilizzo di tali campi in altri moduli (vedi ad es. la PR https://github.com/OCA/vertical-association/pull/103 previa opportuna modifica). 
P.S.: per completezza segnalo anche quest'altra PR https://github.com/OCA/account-invoicing/pull/873

In questo modo verrebbe semplificata la gestione del codice evitando inutili doppioni tra le ricevute native e quelle introdotte da `l10n_it_corrispettivi`.

Che ne pensate?

**Comment by SirTakobi** [comment]
Giusto per coordinarsi, la migrazione del modulo è in corso:
>sto lavorando alla migrazione di `l10n_it_corrispettivi`
>
>_Originally posted by @tafaRU in https://github.com/OCA/l10n-italy/issues/1905#issuecomment-1076513601_

**Comment by primes2h** [comment]
> Giusto per coordinarsi, la migrazione del modulo è in corso:
> 
> > sto lavorando alla migrazione di `l10n_it_corrispettivi`
> > _Originally posted by @tafaRU in [#1905 (comment)](https://github.com/OCA/l10n-italy/issues/1905#issuecomment-1076513601)_

Hai ragione,mi sono scordato di scriverlo. Ho già parlato con lui della proposta. :-)

**Comment by stevech091** [comment]
L'idea di @primes2h la condivido.

**Comment by TheMule71** [comment]
@primes2h
ti ho fatto una PR

**Comment by tafaRU** [comment]
Parlandone con @primes2h si è deciso che il modulo relativo ai *corrispettivi* sulla `14.0` non ha più ragione di esistere in questo repository. Andrò pertanto a proporre su https://github.com/OCA/account-invoicing l'aggiunta del modulo`account_receipt` (con funzionalità equivalenti a quelle di `l10n_it_corrispettivi`). 

Task list:

- [ ]  rilascio di `account_receipt_report` tramite https://github.com/OCA/account-invoicing/pull/849
- [ ] rilascio di `account_portal_receipt` tramite https://github.com/OCA/account-invoicing/pull/873
- [ ] creazione modulo `account_receipt` che dipende dai due precedenti

**Comment by SirTakobi** [comment]
> Parlandone con @primes2h siamo giunti alla conclusione che il modulo relativo ai _corrispettivi_ sulla `14.0` non ha più ragione di esistere in questo repository. Andrò pertanto a proporre su https://github.com/OCA/account-invoicing l'aggiunta del modulo`account_receipt` (con funzionalità equivalenti a quelle di `l10n_it_corrispettivi`).
> 
> Task list:
> 
> * [x]   rilascio di `account_receipt_print` tramite [[14.0] [ADD] new module account_receipt_print account-invoicing#849](https://github.com/OCA/account-invoicing/pull/849)
> * [ ]  rilascio di `account_portal_receipt` tramite [[14.0] [ADD] new module account_portal_receipt account-invoicing#873](https://github.com/OCA/account-invoicing/pull/873)
> * [ ]  creazione modulo `account_receipt` che dipende dai due precedenti

Quindi sarebbe `account_receipt` a contenere la migrazione dei dati di [`l10n_it_corrispettivi`](https://github.com/OCA/l10n-italy/tree/81e2162499d6d66ddc0f53a462359082e3c5996d/l10n_it_corrispettivi)?
Giusto per capire se è il _piccolo modulo base_ di cui scriveva @primes2h nella sua analisi:

> Alla luce di ciò sarebbe sufficiente un piccolo modulo base che aggiunge i campi di l10n_it_corrispettivi nel journal, nel partner e nella fiscal position e poco altro. (non sarebbe neanche strettamente necessario che tale modulo stia in `l10n_it_italy`).

**Comment by stevech091** [comment]
@SirTakobi ho solo un dubbio sul "rintracciarlo" quel modulo.
Mi spiego: se entro in l10_it V14 come faccio a sapere che è stato fatto un modulo utilizzabile per l'Italia che copre quella funzionalità?

**Comment by SirTakobi** [comment]
> @SirTakobi ho solo un dubbio sul "rintracciarlo" quel modulo. Mi spiego: se entro in l10_it V14 come faccio a sapere che è stato fatto un modulo utilizzabile per l'Italia che copre quella funzionalità?

Penso che questo sia più un problema di documentazione, comunque da chiarire, ma dovresti chiedere a chi si occupa di questo sviluppo.
cc @tafaRU e @primes2h

In https://github.com/OCA/l10n-italy/issues/2722#issuecomment-1188737171 ho chiesto invece un chiarimento per quanto riguarda la migrazione dei dati.

**Comment by SirTakobi** [comment]
> > Quindi sarebbe `account_receipt` a contenere la migrazione dei dati di [`l10n_it_corrispettivi`](https://github.com/OCA/l10n-italy/tree/81e2162499d6d66ddc0f53a462359082e3c5996d/l10n_it_corrispettivi)?
> 
> Dal momento che il modulo atterrerebbe su https://github.com/OCA/account-invoicing non è pensabile farlo dipendere da un modulo della localizzazione italiana. Quello che possiamo fare è aggiungere le indicazioni di come effettuare la migrazione nel README del modulo stesso.

Grazie, mi interessava solo capire se la migrazione dei dati sarà responsabilità di `account_receipt`; per i dettagli della migrazione via script o README vedremo poi nella PR

**Comment by SirTakobi** [comment]
> > > @SirTakobi ho solo un dubbio sul "rintracciarlo" quel modulo. Mi spiego: se entro in l10_it V14 come faccio a sapere che è stato fatto un modulo utilizzabile per l'Italia che copre quella funzionalità?
> > 
> > 
> > Penso che questo sia più un problema di documentazione, comunque da chiarire, ma dovresti chiedere a chi si occupa di questo sviluppo. cc @tafaRU e @primes2h
> 
> Si esatto, quello è principalmente un problema di documentazione da discutere a tempo debito.
> 
> Per quanto riguarda la migrazione dei dati, uno spunto potrebbe essere quello che è stato fatto tra ddt e delivery_note.
> 
> https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_delivery_note#migrazione-dei-dati-da-l10n-it-ddt

Quella procedura serviva per rendere la migrazione opzionale, ed era per migrare i dati all'interno della stessa versione; nel nostro caso invece non si avrà scelta (la migrazione, se necessaria, deve essere eseguita) e la migrazione sarà tra due versioni di Odoo diverse.
Quindi penso sia meglio avere uno script di migrazione o qualcosa che si esegua in automatico, se possibile.

Per buttare lì un'altra idea: in questo caso non vedrei problemi ad inserire nel modulo `account_receipt` uno script di pre/post_init che faccia qualcosa tipo https://github.com/OCA/l10n-italy/blob/0f6d2480597b555066598ee84d1906cf4decdc81/l10n_it_fatturapa_pec/migrations/12.0.1.10.0/pre-migration.py per quanto riguarda i dati del modulo `l10n_it_corrispettivi`.
Per uno script del genere non credo serva nessuna dipendenza, ma forse mi sono perso qualche pezzo quindi per andare avanti con l'analisi penso sia meglio avere almeno una bozza di codice davanti, per questo ho scritto
> per i dettagli della migrazione via script o README vedremo poi nella PR

**Comment by primes2h** [comment]
> > > > @SirTakobi ho solo un dubbio sul "rintracciarlo" quel modulo. Mi spiego: se entro in l10_it V14 come faccio a sapere che è stato fatto un modulo utilizzabile per l'Italia che copre quella funzionalità?
> > > 
> > > 
> > > Penso che questo sia più un problema di documentazione, comunque da chiarire, ma dovresti chiedere a chi si occupa di questo sviluppo. cc @tafaRU e @primes2h
> > 
> > 
> > Si esatto, quello è principalmente un problema di documentazione da discutere a tempo debito.
> > Per quanto riguarda la migrazione dei dati, uno spunto potrebbe essere quello che è stato fatto tra ddt e delivery_note.
> > https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_delivery_note#migrazione-dei-dati-da-l10n-it-ddt
> 
> Quella procedura serviva per rendere la migrazione opzionale, ed era per migrare i dati all'interno della stessa versione; nel nostro caso invece non si avrà scelta (la migrazione, se necessaria, deve essere eseguita) e la migrazione sarà tra due versioni di Odoo diverse. Quindi penso sia meglio avere uno script di migrazione o qualcosa che si esegua in automatico, se possibile.

Certamente, esplicito un po' meglio l'idea. 
Perché non pensare ad alcuni moduli "dummy" che avrebbero l'unica funzione di installare il corrispondente modulo nuovo e lanciare automaticamente lo script di migrazione dei dati?

Es. modulo dummy `l10n_it_corrispettivi` per la v. 14.0, che avrebbe come dipendenza account_receipt (che contiene la nuova struttura/modelli).
Questo modulo si occuperebbe solo di lanciare lo script per la migrazione dei dati, tipo quello tra `ddt` e `delivery note`, ma in modo automatico.
Inoltre il suo README conterrebbe tutte le istruzioni sullo scopo del modulo e su come utilizzarlo.
Oltre a risolvere il problema della documentazione, un altro grosso vantaggio è che permetterebbe di automatizzare la migrazione del modulo tra la 12.0 e la 14.0. Una volta terminata la migrazione il modulo dummy può essere disinstallato.

Quindi, ad es.:
Modulo dummy `l10n_corrispettivi` v.14.0 → avrebbe come dipendenza `account_receipt`
Modulo dummy `l10n_corrispettivi_sale` v.14.0 → avrebbe come dipendenza `account_receipt_sale` (vedi https://github.com/OCA/l10n-italy/issues/2862#issuecomment-1184587146)
ecc..

Sarebbe una soluzione un po' atipica in Odoo ma, se fattibile, risolverebbe in modo elegante il problema. [1]

[1] metodologia utilizzata anche in altri ambiti software (es. https://serverfault.com/questions/610028/what-is-a-dummy-package)

**Comment by eLBati** [comment]
> aggiunta del moduloaccount_receipt (con funzionalità equivalenti a quelle di l10n_it_corrispettivi).

Provo a riassumere le funzionalità attualmente mancanti su v14 in merito alle ricevute:

- Identificare i registri di tipo Receipts
- Creare un Receipts Journal
- Impostare automaticamente nella ricevuta un Receipts Journal

La gestione dei campi `Receipts` su posizione fiscale e partner diventa superflua, in quanto la scelta se fare o meno una ricevuta viene fatta prima, dall'utente, facendo click sul menù Receipts, o da altri moduli, impostando `move_type` (o `default_move_type`) a `out_receipt`.

In pratica, tramite lo stesso form non può essere possibile decidere se fare una fattura o una ricevuta in base al cliente e alla posizione fiscale, come avviene adesso con `l10n_it_corrispettivi`.

>  creazione modulo account_receipt che dipende dai due precedenti

Considerate le funzionalità elencate sopra, non credo debba dipendere dagli altri 2 moduli e credo si possa chiamare `account_receipt_journal`.

Per quanto riguarda gli script di upgrade, appoggio l'idea del modulo dummy l10n_it_corrispettivi

@tafaRU @primes2h se non ci state lavorando, posso iniziare io.

**Comment by tafaRU** [comment]
> @tafaRU @primes2h se non ci state lavorando, posso iniziare io.

al momento non ci sto lavorando, procedi pure, grazie :+1:

**Comment by eLBati** [comment]
https://github.com/OCA/account-invoicing/pull/1260

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/2972#issuecomment-1281901222

**Comment by primes2h** [comment]
> Parlandone con @primes2h siamo giunti alla conclusione che il modulo relativo ai _corrispettivi_ sulla `14.0` non ha più ragione di esistere in questo repository. Andrò pertanto a proporre su https://github.com/OCA/account-invoicing l'aggiunta del modulo`account_receipt` (con funzionalità equivalenti a quelle di `l10n_it_corrispettivi`).
> 
> Task list:
> 
>     * [x]   rilascio di `account_receipt_print` tramite [[14.0] [ADD] new module account_receipt_print account-invoicing#849](https://github.com/OCA/account-invoicing/pull/849)
> 
>     * [ ]  rilascio di `account_portal_receipt` tramite [[14.0] [ADD] new module account_portal_receipt account-invoicing#873](https://github.com/OCA/account-invoicing/pull/873)
> 
>     * [ ]  creazione modulo `account_receipt` che dipende dai due precedenti

Mi sono accorto ora che c'è un errore. Non è` dipende dai due precedenti` ma `è dipendenza dei due precedenti`.
Alla luce di questo, è il caso che vengano rivalutati i successivi commenti.

Se poi il modulo è superfluo  e le sue funzionalità (campi "Receipts" per posizione fiscale e partner) non servono come indicato [qui](https://github.com/OCA/l10n-italy/issues/2722#issuecomment-1272490383) da @eLBati allora nessun problema.

Vedi anche https://github.com/OCA/account-invoicing/pull/1267

**Comment by eLBati** [comment]
I moduli per le ricevute su v14 sono sostanzialmente 2:

1. [account_receipt_journal](https://github.com/OCA/account-invoicing/pull/1260)
2. [account_receipt_sale](https://github.com/OCA/account-invoicing/pull/1267)

In più c'è [l10n_it_corrispettivi_fatturapa_out](https://github.com/OCA/l10n-italy/pull/2979) che si occupa di nascondere, per le ricevute, le parti di interfaccia relative alle fatture elettroniche, tipo il pulsante `Export E-invoice`

**Comment by primes2h** [comment]
> I moduli per le ricevute su v14 sono sostanzialmente 2:
> 
>     1. [account_receipt_journal](https://github.com/OCA/account-invoicing/pull/1260)
>     2. [account_receipt_sale](https://github.com/OCA/account-invoicing/pull/1267)

Avere due soli moduli comporta il seguente problema.

`account_receipt_journal` è generico. Aggiunge due `journal`, quindi supporta sia le ricevute di vendita che quelle di acquisto.

La gestione dei campi `Receipts` su posizione fiscale e partner è stata spostata invece in `account_receipt_sale`, quindi attualmente è legata solo alla parte vendite.
Ciò significa che se in un qualsiasi altro modulo volessi utilizzare quei campi (es. quello in partner) per gestire le ricevute di acquisto sarei obbligato a installare anche la parte di vendita.
La cosa potrebbe essere gestita da un altro modulo, (es. `account_receipt_purchase`) ma a quel punto avremmo due campi `Receipts`nel partner che fanno sostanzialmente la stessa cosa.

È per questo motivo che [qui](https://github.com/OCA/l10n-italy/issues/2722#issuecomment-1184583067) si parlava della necessità di avere il modulo generico `account_receipt` contenente la parte di gestione dei campi `Receipts` per partner e posizione fiscale. (sostituto di `l10n_it_corrispettivi`), non legato a vendite o acquisti. 

Tra l'altro il modulo `account_receipt_sale`, dato che `consente di creare ricevute da ordini di vendita`, dovrebbe dipendere da `sale_management` e non da `sale`.

> 
> In più c'è [l10n_it_corrispettivi_fatturapa_out](https://github.com/OCA/l10n-italy/pull/2979) che si occupa di nascondere, per le ricevute, le parti di interfaccia relative alle fatture elettroniche, tipo il pulsante `Export E-invoice`

:+1: 
P.S: per coerenza con il resto dovrebbe però cambiare nome in `l10n_it_receipt_fatturapa_out`.

**Comment by primes2h** [comment]
Ho aperto questa PR per visualizzare le ricevute nel portale

https://github.com/OCA/account-invoicing/pull/1685

**Comment by primes2h** [comment]
Ho aperto questa PR per che consente di pagare le ricevute di vendita dal portale.

https://github.com/OCA/account-payment/pull/719

**Comment by SirAionTech** [comment]
@primes2h grazie, ma sono funzionalità che erano in **l10n_it_corrispettivi** o sono cose nuove?

Se le funzionalità di **l10n_it_corrispettivi** sono coperte (le PR che le implementano sono mergiate) chiuderei questa issue: le PR in descrizione sono tutte mergiate quindi forse si può chiudere?
Altrimenti, potresti aggiornare la descrizione per elencare cosa manca per chiudere la issue?

**Comment by primes2h** [comment]
> @primes2h grazie, ma sono funzionalità che erano in **l10n_it_corrispettivi** o sono cose nuove?

Sono funzionalità nuove.

> 
> Se le funzionalità di **l10n_it_corrispettivi** sono coperte (le PR che le implementano sono mergiate) chiuderei questa issue: le PR in descrizione sono tutte mergiate quindi forse si può chiudere? Altrimenti, potresti aggiornare la descrizione per elencare cosa manca per chiudere la issue?

Le funzionalità principali ci sono tutte, mancano quelle relative a:
https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_portal_corrispettivi
https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_sale_corrispettivi

Ho aggiornato la descrizione.

**Comment by SirAionTech** [comment]
> > Se le funzionalità di **l10n_it_corrispettivi** sono coperte (le PR che le implementano sono mergiate) chiuderei questa issue: le PR in descrizione sono tutte mergiate quindi forse si può chiudere? Altrimenti, potresti aggiornare la descrizione per elencare cosa manca per chiudere la issue?
> 
> Le funzionalità principali ci sono tutte, mancano quelle relative a: https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_portal_corrispettivi https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_website_sale_corrispettivi
> 
> Ho aggiornato la descrizione.

Capito grazie, quindi le due PR https://github.com/OCA/account-invoicing/pull/1685 e https://github.com/OCA/account-payment/pull/719 che hai linkato in https://github.com/OCA/l10n-italy/issues/2722#issuecomment-1999164309 e https://github.com/OCA/l10n-italy/issues/2722#issuecomment-2000145480 sono _extra_, mentre per chiudere la issue manca solo la migrazione di questi ultimi due moduli.
