### ISSUE TITLE
Coerenza importi account.move/account.invoice e visualizzazione/stampa/XML fatturapa

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2727]
Issue di promemoria. Poi magari la espando un po'.

Ci sono casi nei quali nell'XML vengono modificati gli importi, in particolare `.amount_total`. Al momento "aggiriamo" la cosa in vari modi in `l10n_it_fatturapa_out*".

Tali modifiche vengono inserite da moduli che implementano delle funzionalità. Prendo come esempio split payment.

Il realtà il problema non è relativo all'XML, ma anche a stampe e visualizzazioni. 

Io la vedo al contrario, con `.amount_total` che rappresenta qualcosa di diverso dal reale, fatto così per comodità interna di Odoo (fosse per riconciliazioni, scadenziario pagamenti, ecc. non sto ad approfondire in questo momento).

Come proposte ci sono:

- aggiungere un campo "totale da visualizzare", che stampe, viste, generazione XML usano al posto di `.amount_total`

- creare una funzione che data una `account.move`/`account.invoice` genera un dizionario coi dati da usare per l'XML (ma a questo punto per stampe ecc.) permettento ai vari moduli di fare gli aggiustamenti che servono prima della stampa/generazione XML.  Da vedere il discorso viste. Potrebbe essere overkill se poi l'unica cosa a cambiare è l'importo totale.

Da fare: elencare le casistiche in cui l'ImportoTotale della fattura e `.amount_total` sono diversi per varie ragioni. Sempre usando come esempio SP, in fattura XML ImportoTotale = `.amount_total` + `.amount_sp` (si riaccorpa l'IVA).
Capire se si riesce a risolvere "a monte" ossia a far si che `.amount_total` corrisponda all'importo totale, senza sballare le funzionalità ovviamente. Va cercato nel codice come e dove viene usato `.amount_total` e (dico una stupidata) valutare se cambiarlo con `.amount_total - .amount_sp`.  Non è così banale, ovviamente.

Avere i dati in un dizionario e generare l'XML fattura da quello non serve solo per questa casistica.  Ci permetterebbe di creare allegati XML per lo SdI senza dover per forza creare una `account.move`. Ad es. nei casi di reverse charge (senza autofattura) si potrebbe avere una sola `account.move` e generare il documento integrativo semplicemente preparando il dizionario coi dati corretti.

**Comment by zeroincombenze** [comment]
Io proporrei di utilizzare il campo "Importo a pagare" già usato nelle fatture fornitore con Ritenuta d'acconto.
Si potrebbe fare così:
1. Il modulo l10n_it_account definisce il campo amount_net_pay attualemente definito in l10n_it_withholding_tax; il campo DEVE essere definito esattamente come nel modulo di RA
2. I moduli come lo split-payment utilizzano il campo per visualizzare il netto a pagare; il modulo l10n_it_account è una dipendenza di quasi tutti i moduli delle localizzazione
3. Tra un po' di tempo si elimina il campo dal modulo l10n_it_withholding_tax; i dati clienti restano salvati perchè c'è la doppia deifnizione

Questa soluzione è semplice e utilizza codice e soluzione già sperimentate.

**Comment by francescapenso** [comment]
Non sono sicura che sia pertinente, magari ne parliamo, ma ho notato che se si apre un report fatture per un cliente che ha note di credito, l'importo da pagare non è corretto. Non viene sottratto ma lasciato con il segno positivo.
![image](https://user-images.githubusercontent.com/19937703/231988749-3f2f8aec-5c7b-480c-9c71-a16f40ddf390.png)
