### ISSUE TITLE
[14.0] l10n_it_intrastat - lingering v12 migration script

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2728]
https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_intrastat/migrations/12.0.1.0.0

shouldn't have been removed during the migration 12.0 -> 14.0?

**Comment by eLBati** [comment]
sì

**Comment by OpenCode** [comment]
@tafaRU Qui serve muovere la cartella di migrazione 12.0.1.0.0 dal branch 12.0 al 14.0
