### ISSUE TITLE
11.0 l10n_it_reverse_charge

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2747]
## Module
l10n_it_reverse_charge

## Describe the bug
non viene riportata in bozza la fattura cliente, se il cliente ha come posizione fiscale una posizione fiscale in reverse charge

## To Reproduce
Version

- [ ] 11.0 https://github.com/OCA/l10n-italy/pull/2746

1. Creare una fattura fornitore verso un cliente con reverse charge
2. Validarla, annullarla e riportarla a bozza
3. la fattura cliente rimane su annullata e non viene riportata a bozza insieme a quella fornitore

**Expected behavior**
mi aspetto che la fattura fornitore e la fattura cliente insieme tornino a bozza

**Comment by eLBati** [comment]
Capita solo sulla 11?

**Comment by matteoopenf** [comment]
> Capita solo sulla 11?

si perchè su 12 già c'è quel pezzo di codice che metto

**Comment by SirAionTech** [comment]
Chiudo perché l'unica versione affetta non è più supportata
