### ISSUE TITLE
FIX l10n_it_fatturapa_pec when e-invoice sent file name is in wrong format

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#2749]
## l10n_it_fatturapa_pec

SDI response can't be linked to original file, as RESPONSE_MAIL_REGEX does not match

 - [x] 12.0: https://github.com/OCA/l10n-italy/pull/2696
 - [x] 14.0: https://github.com/OCA/l10n-italy/pull/2792

**Comment by SirTakobi** [comment]
che si chiuda
