### ISSUE TITLE
[l10n_it_ricevute_bancarie] il footer viene stampo alla fine, mancata intestazione e manca il totale

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2755]
## Module
[l10n_it_ricevute_bancarie](https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_ricevute_bancarie)

## Describe the bug
nella stampa del pdf della riba il footer viene stampato all'inizio anzichè alla fine e non c'è l'intestazione e manca il totale

## To Reproduce
**Affected versions**:

- [x] 12.0 #2932
- [x] 14.0 funziona

1. installare il modulo delle riba
2. emettere una riba
3. provare a stamparòa

**Expected behavior**
il footer è in basse, l'header è in alto e il totale compare correttamente

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)
![image](https://user-images.githubusercontent.com/43987335/162781410-1311e872-df2d-43ab-a3a4-9ec497ae525b.png)
![image](https://user-images.githubusercontent.com/43987335/162781448-9f07f5f6-803e-4a82-b2dc-1da74b51d373.png)

![image](https://user-images.githubusercontent.com/43987335/162781494-2125db30-c403-465c-bca9-792f43074618.png)

Anche la versione html è bacata:
![image](https://user-images.githubusercontent.com/43987335/162781618-a1b1743b-1ec3-4136-9d1e-196477906f80.png)

**Comment by primes2h** [comment]
Grazie della segnalazione. 
Potresti aggiungere una descrizione al titolo per cortesia?

**Comment by matteoopenf** [comment]
> Grazie della segnalazione. Potresti aggiungere una descrizione al titolo per cortesia?

fatto

**Comment by patrickt-oforce** [comment]
PR per questa issue, #2932

**Comment by SirAionTech** [comment]
In `16.0` la stampa mi pare ok 
[Stampa distinta.pdf](https://github.com/user-attachments/files/15884241/Stampa.distinta.pdf)

Chiudo perché l'unica versione affetta non è più supportata
