### ISSUE TITLE
[14.0] fatturapa_out con ritenuta d'acconto

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#2762]
## Module
The name of the module that has a bug.

## To Reproduce
**Affected versions**:

1. creare una fattura con ritenuta d'acconto e confermarla
2. cercare di esportare la fattura 
3. errore:
4. 
![image](https://user-images.githubusercontent.com/19937703/163532860-c1ce6d03-021c-4cb1-8308-8b0a730ab227.png)

**Comment by TheMule71** [comment]
La funzione non è presente nell'attuale repo OCA/l10n-italy. Non è che per caso su questo DB è stata attivata la pull #2386 che definisce la funzione:

https://github.com/OCA/l10n-italy/pull/2386/files#diff-2d7e783ca364fe25262a183b7f549537a66774ea8ac1c69116f0445f65315182R22-R30

e per qualche motivo ti è rimasto in giro nel DB il template XML?

**Comment by francescapenso** [comment]
Sicuramente è presente perchè il modulo in questa versione qui 
https://github.com/odoo-italia/l10n-italy/tree/14.0-supermerge/l10n_it_fatturapa_out_wt

La cosa "strana" è che fino a metà marzo sicuramente ha funzionato senza dare errori.

**Comment by francescapenso** [comment]
Con @TheMule71 avevamo fatto una piccola analisi e pare l'errore di export xml con wt dipenda da qualche altro modulo che è stato modificato. Ad ogni modo con questo bug è impossibile esportare fatture con ritenute d'acconto.

**Comment by MaurizioConte** [comment]
Nella generazione dell'XML ci sono anche degli errori formali e, pur passando il file allo sdi resta il fatto che i dati non sono indicati correttamente nei tag previsti dalla normativa.
Nel file generato da odoo il tag relativo a ritenuta inizia con RT02 e non con RT01 mentre il tag della cassa TC22 non viene generato.
Di seguito ci sono i dati dei 2 file xml con il corpo di fatture/parcelle di professionisti uno con i tag corretti e l'altro, generato da odoo, con i tag non corretti. Nei documenti in uno c'è TD06 mentre nell'altro c'è TD01 ma nella composizione del file da inviare allo sdi non cambia nulla per i tag RT e TC.
Inoltre in quello formalmente corretto si evincono sia il totale fattura che il netto a pagare.

di seguito E-Invoice non generata da ODOO - Parcella Professionista con tag corretti
`<FatturaElettronicaBody>
	<DatiGenerali>
<DatiGeneraliDocumento>
	<TipoDocumento>TD06</TipoDocumento>
	<Divisa>EUR</Divisa>
	<Data>2022-05-04</Data>
	<Numero>2022/0005</Numero>
	<DatiRitenuta>
		<TipoRitenuta>RT01</TipoRitenuta>
		<ImportoRitenuta>377.52</ImportoRitenuta>
		<AliquotaRitenuta>20.00</AliquotaRitenuta>
		<CausalePagamento>A</CausalePagamento>
	</DatiRitenuta>
	<DatiCassaPrevidenziale>
		<TipoCassa>TC22</TipoCassa>
		<AlCassa>4.00</AlCassa>
		<ImportoContributoCassa>72.60</ImportoContributoCassa>
		<AliquotaIVA>22.00</AliquotaIVA>
	</DatiCassaPrevidenziale>
	<ImportoTotaleDocumento>2307.87</ImportoTotaleDocumento>
</DatiGeneraliDocumento></DatiGenerali>
<DatiBeniServizi>
	<DettaglioLinee>
		<NumeroLinea>1</NumeroLinea>
		<Descrizione>Attività di docenza</Descrizione>
		<Quantita>1.00</Quantita>
		<PrezzoUnitario>1815.00</PrezzoUnitario>
		<PrezzoTotale>1815.00</PrezzoTotale>
		<AliquotaIVA>22.00</AliquotaIVA>
	</DettaglioLinee>
	<DatiRiepilogo>
		<AliquotaIVA>22.00</AliquotaIVA>
		<ImponibileImporto>1887.60</ImponibileImporto>
		<Imposta>415.27</Imposta>
	</DatiRiepilogo>
</DatiBeniServizi>
<DatiPagamento>
	<CondizioniPagamento>TP02</CondizioniPagamento>
	<DettaglioPagamento>
		<ModalitaPagamento>MP05</ModalitaPagamento>
		<DataRiferimentoTerminiPagamento>2022-05-04</DataRiferimentoTerminiPagamento>
		<ImportoPagamento>1925.35</ImportoPagamento>
	</DettaglioPagamento>
	</DatiPagamento>
</FatturaElettronicaBody>
`

di seguito E-Invoice generata da ODOO  Fattura Professionista con tag non corretti
`<FatturaElettronicaBody>
	<DatiGenerali>
<DatiGeneraliDocumento>
	<TipoDocumento>TD01</TipoDocumento>
	<Divisa>EUR</Divisa>
	<Data>2022-05-03</Data>
	<Numero>2022/0005</Numero>
	<DatiRitenuta>
		<TipoRitenuta>RT02</TipoRitenuta>
		<ImportoRitenuta>600.00</ImportoRitenuta>
		<AliquotaRitenuta>20.00</AliquotaRitenuta>
		<CausalePagamento>A</CausalePagamento>
	</DatiRitenuta>
	<ImportoTotaleDocumento>3660.00</ImportoTotaleDocumento>
</DatiGeneraliDocumento>
</DatiGenerali>
<DatiBeniServizi>
	<DettaglioLinee>
		<NumeroLinea>1</NumeroLinea>
		<Descrizione>Compensi Professionali</Descrizione>
		<Quantita>1.000</Quantita>
		<UnitaMisura>Unita</UnitaMisura>
		<PrezzoUnitario>2884.62000</PrezzoUnitario>
		<PrezzoTotale>2884.62</PrezzoTotale>
		<AliquotaIVA>22.00</AliquotaIVA>
		<Ritenuta>SI</Ritenuta>
	</DettaglioLinee>
	<DettaglioLinee>
		<NumeroLinea>2</NumeroLinea>
		<Descrizione>Contributi previdenziali 4%(circ.INPS n.112 25/05/1996)</Descrizione>
		<Quantita>1.000</Quantita>
		<UnitaMisura>Unita</UnitaMisura>
		<PrezzoUnitario>115.38000</PrezzoUnitario>
		<PrezzoTotale>115.38</PrezzoTotale>
		<AliquotaIVA>22.00</AliquotaIVA>
		<Ritenuta>SI</Ritenuta>
	</DettaglioLinee>
	<DatiRiepilogo>
		<AliquotaIVA>22.00</AliquotaIVA>
		<ImponibileImporto>3000.00</ImponibileImporto>
		<Imposta>660.00</Imposta>
	</DatiRiepilogo>
</DatiBeniServizi>
</FatturaElettronicaBody>`

**Comment by MaurizioConte** [comment]
Per capire meglio allego immagine dei 2 file xml

E-Invoice non generata da ODOO - Parcella Professionista con tag corretti
![image](https://user-images.githubusercontent.com/83764823/167813823-b86d81cf-c77b-4473-a53d-62ebe1efc1e4.png)

E-Invoice generata da ODOO Fattura Professionista con tag non corretti
![image](https://user-images.githubusercontent.com/83764823/167813914-298fc6d6-d210-42c9-a7a2-13fcc04a0f13.png)

**Comment by francescapenso** [comment]
Il fatto che si tratti di RT01 o RT02 dipende dal fatto che si tratti di persona fisica o giuridica. Pertanto non è errato che sia RT02, ma semmai va aggiunto un cotrollo sul fatto che la company odoo emittente sia persona fisica o giuridica credo 
![image](https://user-images.githubusercontent.com/19937703/167844739-7ffb757b-e86e-4bff-bd2a-70ce005953fe.png)

**Comment by MaurizioConte** [comment]
Si è così in più, va gestita la discrimiinante per Fisica/Giuridica e va gestito il TC22 per chi ha la cassa.
E infine i dati relativi al totale fattura e netto a pagare

**Comment by francescapenso** [comment]
@CiroBoxHub qualche news in merito?

**Comment by tafaRU** [comment]
Meglio spostare la discussione su https://github.com/OCA/l10n-italy/pull/2386
Grazie.
