### ISSUE TITLE
[fatturapa] Gestione dati cassa previdenziale

### ISSUE THREAD

**Issue by mmaridev** [OCA/l10n-italy#2766]
In parte collegato a #1924 , apro questa feature request nella speranza possa essere vagliata durante i prossimi Sprint Days.

Allo stato delle cose manca, nell'emissione di fattue elettroniche, la possibilità di inserire la cassa di previdenza con la relativa ritenuta. Nel mio caso, ad esempio, di libero professionista (ma non artigiano) in regime forfettario dovrei poter aggiungere

- cassa di previdenza: INPS
- aliquota cassa: 4%
- importo contributo cassa: 4% * totale righe prodotti (esclusa ad es. la riga del bollo)
- aliquota IVA: 0%
- natura: non soggette - altri casi
- (opzionale ma i più puntigliosi lo chiedono) riferimento normativo: art.1, c.54-89, L. 190/2014

Edit: il riferimento normativo va in realtà nei dati IVA, non credo serva nella cassa previdenziale ma per il momento lo lascio per ulteriori verifiche

 - [ ] 12.0: https://github.com/OCA/l10n-italy/pull/2908
 - [ ] 14.0:

**Comment by francesco-ooops** [comment]
Il modulo sviluppato per la v12 è aggiunto in entrambe le Issue di migrazione a 14 e 16, pertanto chiudo
