### ISSUE TITLE
[fatturapa] Field "Data riferimento termini di pagamento" not present in XML

### ISSUE THREAD

**Issue by mmaridev** [OCA/l10n-italy#2774]
## Module
FatturaPA export

## Describe the bug
When importing an Odoo-generated XML in the "Agenzia delle Entrate" wizard, the field "Data riferimento termini di pagamento" is marked as missing and compulsory.

## To Reproduce
**Affected versions**: 

- [x] 12.0 (risolta per termine supporto)
- [ ] 14.0
- [ ] 16.0 #3892 

1. Create a new invoice
2. Export XML
3. Import XML in AE's tool

**Expected behavior**
Field is valorized with a meaningful date, e.g. today or the invoice date.

**Additional context**
Possibly related to #1594 #1364

**Comment by TheMule71** [comment]
Hello, we need more details, can you upload the XML that causes the problem, please? Maybe anonymized. TY

**Comment by mmaridev** [comment]
Hi,
I realize I have never provided an anonymized XML but the issue is still there. I tested from another instance running 14.0 and the generation of the XML still does not compile the 2.4.2.3 field ("DataRiferimentoTerminiPagamento") still won't get any value.
You can just generate any invoice from Odoo and export the XML. You'll notice there is no such attribute inside the "DettaglioPagamento" node and if you try to import it in the generation wizard by AdE and go back to step 3, the field will be marked red and warned it needs completion.

**Comment by SirAionTech** [comment]
Thanks for reporting this, I have done a little research and node **DataRiferimentoTerminiPagamento** does not seem to be compulsory according to the XSD schema https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.2/Schema_del_file_xml_FatturaPA_v1.2.2.xsd and to the other specifications in https://www.fatturapa.gov.it/it/norme-e-regole/documentazione-fattura-elettronica/formato-fatturapa/.
For instance, in https://www.fatturapa.gov.it/export/documenti/fatturapa/v1.2.2/RappresentazioneTabellareFattOrdinariav123.pdf it says:
> **2.4.2.3 \<DataRiferimentoTerminiPagamento>** | ... | **<0.1>**

where **<0.1>** means not compulsory and only 1 occurrence allowed (extracted from the header of the table in the link).

Do you have any more details on why is the field **DataRiferimentoTerminiPagamento** shown as compulsory?

I agree that this can be implemented, here I am just trying to understand whether this is an urgent fix (we are creating electronic invoices that are not compliant) or not (we are creating electronic invoices without an optional node).

**Comment by mmaridev** [comment]
Hi @SirAionTech ,

> Do you have any more details on why is the field **DataRiferimentoTerminiPagamento** shown as compulsory?

it's probably just the tool by AdE that has been implemented not following the specifications.
Anyway, if you import the generated XML in the generation wizard by AdE, the field will be marked red and the export of the XML prevented until it's valorized.

Yes, at the end of the day is just setting to the same value as the invoice date...

**Comment by mmaridev** [comment]
PR per 16.0 in attesa di review e merge
