### ISSUE TITLE
[12.0][fatturapa] Caption "copia di cortesia" on PDF print of invoices

### ISSUE THREAD

**Issue by mmaridev** [OCA/l10n-italy#2779]
**Is your feature request related to a problem?**
Yes, on the PDF print of an invoice there should be the caption "Copia di cortesia del documento elettronico trasmesso all'Agenzia delle Entrate ai sensi dell’art. 21 Dpr 633/72. Non valido per fini fiscali."

**Describe the solution you'd like**
Odoo automatically adds the necessary text when generating the PDF copy.

**Describe alternatives you've considered**
I'm currently using the "terms&conditions" field to print that but, as a downside, it also gets converted into the XML file which does not make any real sense.

**Additional context**
Since from July also for "forfettari" the electronic invoicing will be compulsory, I think a switch to disable this feature is not needed.

**Comment by mmaridev** [comment]
inficiato da #3883 e #3887

**Comment by mmaridev** [comment]
@francesco-ooops in realtà i due ticket summenzionati, se mergiati, evitano che la dicitura venga esportata nella fattura elettronica e quindi non sarebbe più un problema inserire nel campo termini e condizioni la dicitura standard, anche come default, volendo.

**Comment by francesco-ooops** [comment]
ah ok, dunque per "inficiato" intendi "risolto" :)

**Comment by mmaridev** [comment]
non la soluzione che avevo immaginato ma comunque una soluzione :-)

**Comment by primes2h** [comment]
@mmaridev 
Proprio per evitare quel tipo di problema nella 12.0 abbiamo sempre utilizzato il campo "Reference/Description", che non va nell'xml.

![immagine](https://github.com/OCA/l10n-italy/assets/227940/4614e535-768f-4755-a02c-4cc563083903)

**Comment by mmaridev** [comment]
@primes2h 

Si ma viene stampato nel campo descrizione nel PDF

![immagine](https://github.com/OCA/l10n-italy/assets/18599077/b8f44f72-4c8e-400b-a8d7-17c9f43858ad)

in questo senso mi pare migliore il risultato quando lo inserisce in termini e condizioni

![immagine](https://github.com/OCA/l10n-italy/assets/18599077/6d57e0b7-029a-4bbe-a573-1972748cebf4)
