### ISSUE TITLE
[IMP] l10n_it_split_payment: Limitarsi a rimuovere il totale delle imposte

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2781]
## Module
l10n_it_split_payment

## Describe the bug
Quando un altro modulo (ad esempio **account_global_discount**) ricalcola il totale in base a campi diversi da `amount_untaxed` e `amount_tax`, il risultato viene sovrascritto da **l10n_it_split_payment**.

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/2780
- [x] `14.0`: ?

1. Installare **account_global_discount** (rif. https://github.com/OCA/account-invoicing/tree/6b8221aca16d965f2f6e6e6420cd34fc466f216e/account_global_discount)
2. Installare **l10n_it_split_payment**
3. Creare uno sconto globale da 50%
4. Creare una fattura da 100 + 22
5. Applicare lo sconto globale creato alla fattura

**Actual behavior**
Il totale della fattura è 122

**Expected behavior**
Il totale della fattura è 61

**Additional context**
Non posso aggiungere un test perché non posso installare il modulo di un altro repository per riprodurre l'errore.
Succederebbe anche con qualsiasi altro modulo che modifichi il totale della fattura in modo che non sia più semplicemente
```
self.amount_total = self.amount_untaxed + self.amount_tax
```

**Comment by valeriobelcastro** [comment]
Test effettuato localmente con versione 14.0 riproducendo gli step descritti. Il totale della fattura corrisponde con il risultato atteso
![image](https://user-images.githubusercontent.com/47102619/168322031-a1e44f2c-8d35-4a15-b18e-b76296cdd85a.png)
