### ISSUE TITLE
[10.0] RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#279]
See
https://travis-ci.org/OCA/l10n-italy/jobs/172384561

It may depend on ```l10n_it_pec``` or ```l10n_it_ateco``` (more probably)

@CiroBoxHub @OpenCode could you have a look?

**Comment by OpenCode** [comment]
Travis restarted. We are waiting to see what happens.

**Comment by OpenCode** [comment]
@eLBati https://github.com/OCA/l10n-italy/pull/280

**Comment by eLBati** [comment]
Continuing on https://github.com/OCA/l10n-italy/pull/280
