### ISSUE TITLE
l10n_it_delivery_note Selezione di una DN esistente in bozza viene esposta come False

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#2802]
## Module
l10n_it_delivery_note

## Describe the bug
La selezione di una Delivery Note esistente a cui aggiungere il trasferimento mostra dei record False.

## To Reproduce
**Affected versions**:
- [x] 12.0: #2803 
- [x] 14.0: no
- [x] 16.0: ?

1. attivare le funzionalità Delivery Note avanzate
2. creare due trasferimenti per lo stesso partner
3. validare un trasferimento e creare una Delivery Note lasciandolo in bozza
4. validare l'altro trasferimento e tentare di selezionare il Delivery Note in bozza già creato

**Expected behavior**
Dovrebbe vedersi il nome del Delivery Note anche se non validato (per cui non ha un numero)

**Additional context**
![Screenshot(325)](https://user-images.githubusercontent.com/7657311/168823705-cf2b6bd1-bd6d-4914-b29c-3f51d77a96a6.png)

![Screenshot(326)](https://user-images.githubusercontent.com/7657311/168823734-5d15b18f-b1ca-4563-8e50-2598d8e6abca.png)

**Comment by SirTakobi** [comment]
Confermo il problema in `12.0`, puoi però mettere in descrizione che parli di Delivery note e non di DDT? Ho fatto un giro a vuoto perché creavo un DDT

**Comment by OpenCode** [comment]
@sergiocorato Hai modo di controllare anche la 14.0?

**Comment by tafaRU** [comment]
Segnalo che sulla `14.0` il campo `display_name` non è presente sul model [stock.delivery.note](https://github.com/OCA/l10n-italy/blob/ba549596fbd6dea566f031546e4645c9c52c91ac/l10n_it_delivery_note/models/stock_delivery_note.py#L42).

**Comment by SirTakobi** [comment]
> Segnalo che sulla `14.0` il campo `display_name` non è presente sul model [stock.delivery.note](https://github.com/OCA/l10n-italy/blob/ba549596fbd6dea566f031546e4645c9c52c91ac/l10n_it_delivery_note/models/stock_delivery_note.py#L42).

Credo che `display_name` sia sempre presente nei model perché è un campo _magico_ aggiunto in https://github.com/odoo/odoo/blob/95358dd00ec8a0a308bedda2f6bce6563eefb6e6/odoo/models.py#L452-L453

Il suo valore è calcolato in base al risultato di `name_get` in https://github.com/odoo/odoo/blob/95358dd00ec8a0a308bedda2f6bce6563eefb6e6/odoo/models.py#L1728-L1730

E `name_get` ha anche un override in `stock.delivery.note`: https://github.com/OCA/l10n-italy/blob/fb484bf5653e9aa3fba6f181a11bb967e3dc5061/l10n_it_delivery_note/models/stock_delivery_note.py#L268

**Comment by tafaRU** [comment]
> Credo che `display_name` sia sempre presente nei model perché è un campo _magico_ aggiunto in https://github.com/odoo/odoo/blob/95358dd00ec8a0a308bedda2f6bce6563eefb6e6/odoo/models.py#L452-L453

Grazie della condivisione allora forse sarebbe da rimuovere [qui](https://github.com/OCA/l10n-italy/blob/f3d717a4aa94a1adc354ba6c46c93cfa40e3e77f/l10n_it_delivery_note/models/stock_delivery_note.py#L84-L85) perché ridondante, anche se noto che, rispetto a quello che viene aggiunto dall'ORM, sono presenti in aggiunta: `index=True, copy=False`. Cosa ne pensi?

**Comment by SirTakobi** [comment]
> > Credo che `display_name` sia sempre presente nei model perché è un campo _magico_ aggiunto in https://github.com/odoo/odoo/blob/95358dd00ec8a0a308bedda2f6bce6563eefb6e6/odoo/models.py#L452-L453
> 
> Grazie della condivisione allora forse sarebbe da rimuovere [qui](https://github.com/OCA/l10n-italy/blob/f3d717a4aa94a1adc354ba6c46c93cfa40e3e77f/l10n_it_delivery_note/models/stock_delivery_note.py#L84-L85) perché ridondante, anche se noto che, rispetto a quello che viene aggiunto dall'ORM, sono presenti in aggiunta: `index=True, copy=False`. Cosa ne pensi?

C'è anche `store=True`; credo che l'override sia stato fatto proprio per salvarlo a DB (con `store`) e poterlo recuperare più velocemente (con `index`), che potrebbe essere più efficiente rispetto al ricalcolo che avverrebbe ogni volta se non fosse stato ridefinito in questo modo.
Non ho idea dell'utilità che può avere `copy=False` su un campo calcolato, perché penso che comunque il valore verrebbe ricalcolato sul record creato dalla copia.

È stato anche ridefinito il metodo `_compute_display_name` che non chiama `super`: in generale secondo me non è bene interrompere l'ereditarietà dei metodi, ma immagino che chi l'ha fatto avrà i suoi motivi.. Forse l'ha dovuto fare per poter aggiungere tutti questi campi https://github.com/OCA/l10n-italy/blob/31eb0c8b1431abb06944a86230c6365b6da540b6/l10n_it_delivery_note/models/stock_delivery_note.py#L222-L223
nel `api.depends`.

Quindi, forse si potrebbe migliorare qualcosa ma non credo che la nuova definizione del campo che hai linkato sia ridondante.

**Comment by tafaRU** [comment]
> Quindi, forse si potrebbe migliorare qualcosa ma non credo che la nuova definizione del campo che hai linkato sia ridondante.

Ok grazie dell'analisi, rimane comunque il fatto che le due versioni sono disallineate. Ciò però non preclude il completamento di questa issue.

**Comment by francesco-ooops** [comment]
@sergiocorato si può chiudere dunque?

**Comment by francesco-ooops** [comment]
Dato che la migrazione alla v16 è stata fatta successivamente a https://github.com/OCA/l10n-italy/issues/2802#issuecomment-1178709420, chiudo
