### ISSUE TITLE
l10n_it_intrastat, il campo intrastat non viene aggiornato se si fattura da sale order.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2807]
## Module
`l10n_it_intrastat`

## Describe the bug
Il campo `intrastat` non viene aggiornato se si fattura da sale order.

## To Reproduce
**Affected versions**:

- [x] 12.0 https://github.com/OCA/l10n-italy/pull/2362
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/2808

1. Creare una fattura da sale order, con una posizione fiscale soggetta ad intrastat.
2. Nell fattura creata, il campo `intrastat` non è valorizzato. 

**Expected behavior**
Il campo `intrastat`deve essere valorizzato a `True`.

**Comment by OpenCode** [comment]
@GSLabIt La 12.0 ha lo stesso problema?

**Comment by GSLabIt** [comment]
> @GSLabIt La 12.0 ha lo stesso problema?

No, sembrerebbe funzionare correttamente

**Comment by tafaRU** [comment]
@GSLabIt

> No, sembrerebbe funzionare correttamente

Confermo.
Infatti verificando nel codice mi sono accorto che tali modifiche erano state aggiunte da me sulla `12.0` con https://github.com/OCA/l10n-italy/pull/2362
_Best practice_: dal momento che le tue modifiche sono **identiche** a quelle che avevo fatto io sarebbe stato più corretto fare `cherry-pick` del mio commit ottenendo così un duplice risultato:

- riuscire ad applicare le modifiche più velocemente
- preservare la autorship del commit originale :exclamation:

**Comment by GSLabIt** [comment]
> @GSLabIt
> 
> > No, sembrerebbe funzionare correttamente
> 
> Confermo.
> Infatti verificando nel codice mi sono accorto che tali modifiche erano state aggiunte da me sulla `12.0` con https://github.com/OCA/l10n-italy/pull/2362
> _Best practice_: dal momento che le tue modifiche sono **identiche** a quelle che avevo fatto io sarebbe stato più corretto fare `cherry-pick` del mio commit ottenendo così un duplice risultato:
> 
> - riuscire ad applicare le modifiche più velocemente
> - preservare la autorship del commit originale :exclamation: 

Mi dai indicazioni per una prossima volta? Grazie

**Comment by tafaRU** [comment]
> Mi dai indicazioni per una prossima volta?

Queste indicazioni sono sempre valide.

**Comment by GSLabIt** [comment]
> > Mi dai indicazioni per una prossima volta?
> 
> Queste indicazioni sono sempre valide.

Certo, ma ora è fatto. Me le segno per una prossima volta mi dovesse capitare la stessa problematica. Grazie

**Comment by GSLabIt** [comment]
> > > @GSLabIt
> > > > No, sembrerebbe funzionare correttamente
> > > 
> > > 
> > > Confermo.
> > > Infatti verificando nel codice mi sono accorto che tali modifiche erano state aggiunte da me sulla `12.0` con #2362
> > > _Best practice_: dal momento che le tue modifiche sono **identiche** a quelle che avevo fatto io sarebbe stato più corretto fare `cherry-pick` del mio commit ottenendo così un duplice risultato:
> > > 
> > > * riuscire ad applicare le modifiche più velocemente
> > > * preservare la autorship del commit originale exclamation
> > 
> > Mi dai indicazioni per una prossima volta? Grazie
> 
> Crei un nuovo branch di sviluppo
> 
> `git checkout -b dev-esempio`
> 
> nel nuovo branch usi cherry-pick per portarti dentro uno o più commit presi da altri branch
> 
> `git cherry-pick <altro-commit-hash>`
> 
> A quel punto nella tua history troverai applicate le modifiche prese dall'altro commit e il commit porterà con sé le informazioni anche dell'autore originale.

Grazie
