### ISSUE TITLE
l10n_it_reverse_charge, flag rc su order line non viene aggiornato correttamente.

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#2812]
## Module
`l10n_it_reverse_charge`

## Describe the bug
`rc` flag non viene aggiornato

## To Reproduce
**Affected versions**:

- [ ] 14.0 - https://github.com/OCA/l10n-italy/pull/2813

1. Creare un ordine di acquisto
2. Aggiornare posizione fiscale che prevede RC
3. Validare l'ordine e creare fattura d'acquisto. 
4. Il flag `rc` non viene aggiornato in base alla posizione fiscale.

**Expected behavior**
il flag `rc` deve essere aggiornato.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by OpenCode** [comment]
Ho aggiunto il collegamento alla PR nel corpo del messaggio accanto alla versione.
La 12.0 non ne è affetta?

**Comment by GSLabIt** [comment]
> Ho aggiunto il collegamento alla PR nel corpo del messaggio accanto alla versione.
> La 12.0 non ne è affetta?

No, sembrerebbe funzionare correttamente.

**Comment by OpenCode** [comment]
> > Ho aggiunto il collegamento alla PR nel corpo del messaggio accanto alla versione.
> > La 12.0 non ne è affetta?
> 
> No, sembrerebbe funzionare correttamente.

Grazie mille per il feedback. Allora chiudo :)

**Comment by SirAionTech** [comment]
La fix #2813 mergiata per `14.0` è stata portata a `16.0` nella migrazione https://github.com/OCA/l10n-italy/pull/3566
