### ISSUE TITLE
l10n_it_fatturapa_pec: Campo 'is_fatturapa_pec' mancante nella vista

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2817]
## Module
**l10n_it_fatturapa_pec**

## Describe the bug
All'aggiornamento del modulo in oggetto, viene sollevato l'errore:
> Campo is_fatturapa_pec usato negli attributi mancante, è obbligatorio nella vista:
> [...]

## To Reproduce
**Affected versions**:
- [x] `12.0`: viene corretto come effetto collaterale di https://github.com/OCA/l10n-italy/pull/2810
- [x] `14.0`: viene corretto come effetto collaterale di https://github.com/OCA/l10n-italy/pull/2708
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/3189

**Steps to reproduce the behavior**:
Non ho trovato passi per riprodurre l'errore in un un nuovo DB.

**Additional context**
Il problema è che nella vista `fetchmail.view_email_server_form` ereditata da https://github.com/OCA/l10n-italy/blob/3586e01a0b201f2c8ef42eb54508f5839bb626f5/l10n_it_fatturapa_pec/views/fetchmail_view.xml#L4
non esiste il campo `is_fatturapa_pec`: il campo è definito in `l10n_it_sdi_channel.view_email_server_fatturapa_out_pec_form`.

Quindi la vista `l10n_it_fatturapa_pec.view_email_server_form_e_invoice` riesce ad essere applicata con successo solo se viene prima applicata la vista `l10n_it_sdi_channel.view_email_server_fatturapa_out_pec_form`, questo ordine però può cambiare ad esempio modificando la priorità delle viste.

Per non dipendere dalla priorità delle viste, si potrebbe modificare https://github.com/OCA/l10n-italy/blob/3586e01a0b201f2c8ef42eb54508f5839bb626f5/l10n_it_fatturapa_pec/views/fetchmail_view.xml#L7
in 
```
<field name="inherit_id" ref="l10n_it_sdi_channel.view_email_server_fatturapa_out_pec_form"/>
```

**Comment by francesco-ooops** [comment]
risolta in tutte le versioni
