### ISSUE TITLE
l10n_it_fatturapa_in: Mappare Codici Articolo Prodotti con Codice Articolo Fornitori

### ISSUE THREAD

**Issue by Foodentyco** [OCA/l10n-italy#2825]
I nostri fornitori utilizzano codici prodotto differenti dalla nostra codifica interna.

In fase di importazione dobbiamo mappare ogni prodotto interno con il prodotto presente in e-fattura.

Il modulo consente già di mappare il codice interno aziendale con il codice esterno fornitore? Se così non fosse, è stato già previsto il rilascio di una funzionalità che possa risolvere questa manualità o invece è una customizzazione da dover richiedere ad un consulente esterno?

Grazie mille

**Comment by eLBati** [comment]
Vedi

https://github.com/OCA/l10n-italy/blob/ed806c931ca42ce3fb2beeeb1f19175ad9480571/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L445-L470

Per le richieste di supporto, in generale: https://discord.gg/pYtJvc97Hz
