### ISSUE TITLE
Il resoconto dello stato patrimoniale non tiene conto degli anni precedenti

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2831]
## Module
l10n_it_account_balance_report

## Describe the bug
Il resoconto dello stato patrimoniale non tiene conto degli anni precedenti.

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/2832

1. Registrare una fattura cliente (senza pagamento) da 1€ + 0.22€ (IVA) per l'anno 2020
2. Chiudere l'anno 2020 (utilizzando il modulo **account_fiscal_year_closing**)
1. Registrare una fattura cliente (senza pagamento) da 1€ + 0.22€ (IVA) per l'anno 2021
2. Chiudere l'anno 2021 (utilizzando il modulo **account_fiscal_year_closing**)
4. Aprire il menu Fatturazione > Rendicontazione > Rendiconti contabili OCA > Stampa Bilancio Contabile, nel popup selezionare:
    - **Tipo di rendiconto**: stato patrimoniale
    - **Intervallo date**: 2021 (un intervallo data che copre tutto il 2021)
    - **Registro**: tutti i registri tranne il registro contenente le registrazioni di apertura/chiusura dell'anno fiscale
5. Cliccare su Visualizza

**Actual behavior**
Il resoconto dello stato patrimoniale mostra un attivo di 1,22€ e un passivo di 0,22€:
![image](https://user-images.githubusercontent.com/101628000/172852153-2e272d15-e74a-4015-82af-606b2b37418d.png)

**Expected behavior**
Il resoconto dello stato patrimoniale mostra un attivo di 2,44€ e un passivo di 1,44€:
![image](https://user-images.githubusercontent.com/101628000/178524376-ad6060fa-a391-42ba-a9d0-5ca410381ac5.png)

Questo risultato coinciderebbe così con i saldi finali calcolati dal report **Bilancio di verifica** (modulo **account_financial_report**):
![image](https://user-images.githubusercontent.com/101628000/178524535-8ed6e937-8297-4f38-98ef-96b3ea53cec4.png)
ottenuti impostando gli stessi filtri **Intervallo date**, **Registro** e **Gerarchia su** = Conti figli (valore utilizzato implicitamente da **l10n_it_account_balance_report** in https://github.com/OCA/l10n-italy/blob/e401162213cf42efe1d10cfb2a2fd8edde63a323/l10n_it_account_balance_report/wizard/wizard_account_balance_report.xml#L125 )

**Comment by francesco-ooops** [comment]
Integrata in successive migrazioni
