### ISSUE TITLE
Errore importazione fattura elettronica tramite PEC

### ISSUE THREAD

**Issue by esafocus** [OCA/l10n-italy#2837]
Ho un problema da alcuni giorni, quando il server email PEC prova a fare il download delle fatture elettroniche, arriva una fetchmail con questo messaggio
"Accesso ai record "E-bill import file" ([fatturapa.attachment.in](http://fatturapa.attachment.in/)) non consentito. L'operazione è consentita per i seguenti gruppi: - Invoicing/Billing Se necessario, contattare l'amministratore per richiedere l'accesso."
E naturalmente le fatture non vengono scaricate su Odoo.
Qualcuno sa come mai succede questo è come posso risolvere?

**Comment by dcorio** [comment]
Ciao @esafocus ,
è possibile che l'utente che hai impostato nel campo "creatore e-fattura" nella configurazione della contabilità non appartenga a quello specifico gruppo?

**Comment by francesco-ooops** [comment]
Chiudo per mancanza di informazioni, riapri pure se si dovesse ripresentare.
