### ISSUE TITLE
l10n_it_fatturapa_out | Stato Fatture Elettroniche

### ISSUE THREAD

**Issue by MirkosoftAssistenza** [OCA/l10n-italy#2840]
**Is your feature request related to a problem?**
Non è possibile forzare lo stato delle fatture elettroniche, ad esempio segnandole come "Spedite".
Si è costretti a spedirle correttamente con una PEC perché cambino stato.

**Describe the solution you'd like**
Inserire nel menù "Azione" la possibilità di cambiare lo stato delle Fatture in Inviate/Consegnate/Pronte alla Spedizione.

**Describe alternatives you've considered**
Installare un modulo di integrazione con altri servizi terzi (vedi Aruba) che permettano l'aggiornamento dello stato delle fatture.

**Additional context**
Modulo: l10n_it_fatturapa_out
Versione: 14.0

**Comment by PatosMarco** [comment]
Non ha molto senso, almeno in termini di procedere a mano. Ma che voi sappiate, integrazioni con sistemi di invio che facciano anche la firma?

**Comment by matteoopenf** [comment]
C’è Aruba che invia e firma direttamente quando gli passi il file xml 

Matteo Mircoli
Developer | ***@***.*** 

> Il giorno 21 giu 2022, alle ore 13:25, Patos ***@***.***> ha scritto:
> 
> ﻿
> Non ha molto senso, almeno in termini di procedere a mano. Ma che voi sappiate, integrazioni con sistemi di invio che facciano anche la firma?
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.

-- 

_
Openforce Srls Unipersonale *| www.openforce.it 
<http://www.openforce.it/> |*__ 02 21119472 | Via Tiziano,32 20145 Milano_

**Comment by PatosMarco** [comment]
Si questo sì, ma conoscere qualche servizio, anche Aruba, già integrato con Odoo perché magari mette a disposizione delle API?

**Comment by MirkosoftAssistenza** [comment]
> Se non ho capito male il flusso sarebbe:
> 
> * le fatture vengono create in Odoo;
> * gli XML vengono generati da Odoo;
> * esportati e inviati tramite altro software a mano senza connettore;
> * viene tenuta traccia in Odoo dello stato della spedizione (copiandolo a mano dall'altro software).
> 
> Direi che riguarda anche la 12.

Sì, tutto giusto, riguarda anche la 12.
L'utilità sta proprio nell'avere un'idea, senza dover controllare nel servizio terzo utilizzato, di quali FE siano state inviate.
Lavorando in Team è una situazione che può capitare.
