### ISSUE TITLE
[14.0] l10n_it_sdi_channel - Test connection success don't revert email

### ISSUE THREAD

**Issue by mde-spring** [OCA/l10n-italy#2849]
Hello,

I'm facing to an issue when I launch a connection test with is_fatturapa_pec ticked
If result is OK, the email address is not reverted.

https://github.com/OCA/l10n-italy/blob/d71d34c3c29219d3b1f03175b139abad1d751ddc/l10n_it_sdi_channel/models/ir_mail_server.py#L18

Since v14, odoo created new function to manage the user email and can be used to fix it
https://github.com/odoo/odoo/blob/ecff2d13dc7739dc089e5851e5b424acf93f8852/odoo/addons/base/models/ir_mail_server.py#L105

Thanks

**Comment by tafaRU** [comment]
Hello,

thanks for reporting that issue. 
Could you please re-open it by using https://github.com/OCA/l10n-italy/issues/new/choose ?

**Comment by mde-spring** [comment]
Done in #2861

**Comment by tafaRU** [comment]
> Done in #2861

thanks!
