### ISSUE TITLE
Xml 'NoneType' object has no attribute 'iter'

### ISSUE THREAD

**Issue by Foodentyco** [OCA/l10n-italy#2854]
In ricezione, al fetch della Pec, ricevo questo messaggio di errore:

Xml 'NoneType' object has no attribute 'iter' non valido.

Potreste aiutarmi nella risoluzione del problema?

grazie mille

**Comment by Foodentyco** [comment]
2022-07-04 15:25:58,630 1 INFO Foodentyco odoo.addons.l10n_it_fatturapa_pec.models.fetchmail: Failure when fetching emails using imap server pec_FATT_IN.
Traceback (most recent call last):
  File "/mnt/extra-addons/l10n_it_fatturapa/models/ir_attachment.py", line 100, in get_xml_string
    return self.cleanup_xml(data)
  File "/mnt/extra-addons/l10n_it_fatturapa/models/ir_attachment.py", line 70, in cleanup_xml
    xml_string = self.remove_xades_sign(xml_string)
  File "/mnt/extra-addons/l10n_it_fatturapa/models/ir_attachment.py", line 53, in remove_xades_sign
    for elem in root.iter("*"):
AttributeError: 'NoneType' object has no attribute 'iter'

During handling of the above exception, another exception occurred:

**Comment by Foodentyco** [comment]
L'intestazione della fattura elettronica che non viene parsata correttamente è la seguente:

<?xml version="1.0" encoding="UTF-8"?>
<b:FatturaElettronica xmlns:b="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" versione="FPR12">

La stessa fattura caricata nell'APP di fatturazione ed importata da wizard viene caricata correttamente.

C'è qualche differenza tra i due processi che può aver causato l'errore di parsing?

**Comment by vincenzoterzulli** [comment]
Ciao @Foodentyco,
Potresti allegare il file XML anonimizzato con cui poter fare dei test? Grazie

**Comment by Foodentyco** [comment]
Ciao @vincenzoterzulli, @TheMule71,

non riesco a venirne a capo! Ho fatto un test complessivo su tutte le fatture elettroniche. Il processo adesso non carica piû nulla, a prescindere dal file XML.

**Il processo acquisisce correttamente la mail, esegue correttamente message_process, quindi message_route, per restituire un primo messaggio di errore solo a (imap server):**

self._cr.commit()

INFO Foodentyco odoo.addons.l10n_it_fatturapa_pec.models.fetchmail: Failure when fetching emails using imap server pec_FATT_IN. 

**E poi il secondo classico errore sul parsing XML.

Ho anche notato che extract_cades(data) va sempre in except.**

File "/mnt/extra-addons/l10n_it_fatturapa/models/ir_attachment.py", line 100, in get_xml_string
  return self.cleanup_xml(data)
File "/mnt/extra-addons/l10n_it_fatturapa/models/ir_attachment.py", line 70, in cleanup_xml
  xml_string = self.remove_xades_sign(xml_string)
File "/mnt/extra-addons/l10n_it_fatturapa/models/ir_attachment.py", line 53, in remove_xades_sign
  for elem in root.iter("*"):
AttributeError: 'NoneType' object has no attribute 'iter'

**Sono le uniche informazioni che al momento sono riuscito a raccogliere.

Potreste darmi qualche diritta...please!**

**Comment by Foodentyco** [comment]
@TheMule71 @vincenzoterzulli volevo chiedervi se per caso avevate avuto modo di vedere il file xml e se potevate darmi una dritta. 

Lato funzionale conosco abbastanza bene Odoo, sto iniziando ad imparare anche la parte di coding e quindi, in questo caso, ad impostare il debug. Nel frattempo, perô una vostra indicazione sarebbe utilissima per me. Grazie mille
