### ISSUE TITLE
[14.0] Gestione move_type per ricevute legate agli ordini

### ISSUE THREAD

**Issue by FrancescoBallerini** [OCA/l10n-italy#2862]
Buongiorno, ho provato a creare una ricevuta prendendo i dati dall'ordine, per evitare di dover inserire tutto manualmente, quindi ho premuto il bottone 'crea fattura' dopo aver validato il picking e aver creato i registri e registri iva necessari per la gestione della sequenza e del sezionale, come consigliato in questo post:

https://www.odoo-italia.org/forum/forum-1/question/creazione-ricevuta-da-un-ordine-2956

Il problema è che così facendo, il move_type resta di tipo 'out_invoice'/'in_invoice', non permettendo alle ricevute di venire visualizzate nella vista apposita (menu Fatturazione/Fornitore (o clienti)/Ricevute) dato che queste viste vengono filtrate su dominio move_type 'out_receipt'/'in_receipt':

https://github.com/odoo/odoo/blob/5b099bf6135b2ff517078d1839b513da7830f718/addons/account/views/account_move_views.xml#L1410

Il comportamento voluto dunque sarebbe creare una ricevuta di acquisto/vendita senza dover reinserire i dati manualmente, cioè prendendoli dall'ordine associato al picking, e che allo stesso tempo il move_type risulti di tipo ricevuta piuttosto che di tipo fattura. 

Questa necessità è gestita e non sono riuscito a trovarla, oppure sarebbe una cosa da integrare? 

PS: Ho creato questa issue ma se ci fosse la necessità si potrebbe coordinare con https://github.com/OCA/l10n-italy/issues/2722

**Comment by tafaRU** [comment]
> oppure sarebbe una cosa da integrare?

occorre migrare https://github.com/OCA/l10n-italy/tree/12.0/l10n_it_corrispettivi_sale ma prima di farlo occorre portare avanti https://github.com/OCA/l10n-italy/issues/2722

**Comment by tafaRU** [comment]
Prima di partire con lo sviluppo occorrerà ovviamente attendere il completamento di https://github.com/OCA/l10n-italy/issues/2722.

**Comment by FrancescoBallerini** [comment]
@tafaRU Perfetto tutto chiaro. Se volete ditemi qualcosa quando sarà completato account_receipt, posso provare a contribuire per la gestione del move_type per le ricevute se vi torna comodo quando sarà il momento.
