### ISSUE TITLE
[14.0] l10n_it_split_payment - Problema inserimento riga fattura

### ISSUE THREAD

**Issue by CiroBoxHub** [OCA/l10n-italy#2863]
Problema con l'inserimento delle righe quando si crea una fattura con posizione fiscale soggetta a scissione pagamenti

## Module
l10n_it_split_payment

## Describe the bug
Alla creazione della fattura, se il campo posizione fiscale è valorizzato con una posizione fiscale soggetta a scissione pagamenti, non appena viene inserita una riga, questa sparisce. Le righe di movimenti contabili vengono comunque scritte, ma risultano squadrate. A questo punto non è possibile salvare la fattura o aggiungere altre righe

## To Reproduce

**Affected versions**:

- [ ] 14.0

1. Fatture Clienti - Crea
2. Selezionare cliente con posizione fiscale Scissione Pagamenti
3. Aggiungere una riga alla fattura

Comportamento atteso:
La riga non sparisce all'inserimento, e le scritture contabili non risultano squadrate
(test eseguito su runbot http://oca-l10n-italy-14-0-09d3587d96f0.runboat.odoo-community.org)

https://user-images.githubusercontent.com/16084466/178225621-22762499-d096-4c86-a57f-93a99ae6b9bc.mp4

**Comment by matteoopenf** [comment]
anche noi lo riscontriamo per un cliente ho risolto, mettendo prima un'altra posizione fiscale e poi questa dello split e poi è andata.
Però un effetti è un problema

**Comment by francescapenso** [comment]
Successo anche a me. Ma non ero riuscita ad individuare l esatta sequenza di passi pee riprodurre errore. In effetti creando fattura partendo da un ordine non avviene

**Comment by SirTakobi** [comment]
Mi pare sia duplicata di https://github.com/OCA/l10n-italy/issues/2672.
Esiste https://github.com/OCA/l10n-italy/pull/2515 per correggere: potete verificare se risolve?

**Comment by CiroBoxHub** [comment]
Questa issue è risolta. Grazie
