### ISSUE TITLE
[IMP] l10n_it_reverse_charge: preimpostare il campo 'rc' in 'account.invoice.line' durante create

### ISSUE THREAD

**Issue by vincenzoterzulli** [OCA/l10n-italy#2870]
## Module
l10n_it_reverse_charge

## Describe the bug
Nella model `account.invoice.line` il campo `rc` viene impostato dal metodo `onchange_invoice_line_tax_id` con riferimento al tipo di posizione fiscale. Il metodo onchange viene eseguito solo durante la creazione della fattura da backend, e quindi si pone il problema che il campo `rc` non viene preimpostato durante la creazione di fatture via codice.

Esempio su v12 qui https://github.com/OCA/l10n-italy/blob/4bae5b8d06b033c931686e1de870177bfb94011e/l10n_it_reverse_charge/models/account_invoice.py#L11-L30

Infatti il metodo `onchange_invoice_line_tax_id` viene poi richiamato esplicitamente anche nei test, si veda linea 29
https://github.com/OCA/l10n-italy/blob/4bae5b8d06b033c931686e1de870177bfb94011e/l10n_it_reverse_charge/tests/test_rc.py#L14-L31

**Expected behavior**
Il campo `rc` sia preimpostato correttamente anche durante la creazione di fatture via codice, quindi anche nei test.

**Affected versions**:
- [8.0] proposta soluzione nel commit https://github.com/OCA/l10n-italy/pull/2855/commits/313359c5dc279cb2e90a9643d54c977703f6b102 nella PR #2855  
- [10.0]
- [12.0]
- [14.0]

**Comment by francesco-ooops** [comment]
duplicata di #2812 ?

**Comment by SirAionTech** [comment]
> duplicata di #2812 ?

Non proprio, però la PR https://github.com/OCA/l10n-italy/pull/2813 mergiata per risolvere https://github.com/OCA/l10n-italy/issues/2812 a occhio risolve anche questa issue.

**Comment by francesco-ooops** [comment]
Ok, allora chiudo, se dovesse ripresentarsi si può riaprire.
