### ISSUE TITLE
[14.0] riconciliazione bancaria e reverse charge

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/l10n-italy#2894]
## Module
The name of the module that has a bug.
l10n_it_reverse_charge
## Describe the bug
quando registro un fattura passiva la fattura stessa non compare nell'elenco fatture riconciliabili da estratto conto .

se registro una fattura fornitore senza reverse charge , poi creo riga in estratto conto bancario e successivamente passo alla riconciliazione nell' elenco "Abbinamenti cliente/fornitore" ho la fattura e se la seleziono mi chiude il pagamento generando le varie scritture contabili.

se la fattura è in reverse charge invece non c'è nell'elenco "Abbinamenti cliente/fornitore" , se poi pago la fattura tramite button della fattura stessa allora nella riconciliazione appare il pagamento della fattura reverse charge e quindi posso riconciliare. 

1. registrare fattura fornitore con RC 
2. creare ec bancario con l'importo del pagamento
3. riconcliare movimenti.
4. la fattura non è in elenco 
5. ripetere la stessa operazione per fattura non rc e la fattura appare in elenco. 

ho provato sia con pagamenti totali che parziali 

**Expected behavior**
che la fattura in RC appaia nell elenco "Abbinamenti cliente/fornitore"

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by As400it** [comment]
Il campo che non fa selezionare la fattura come riconciliabile è payment_id. se impostato a null il comportamento è quello atteso .

**Comment by As400it** [comment]
@SimoRubi questo comportamento è solo alla 14.0

**Comment by SirTakobi** [comment]
> @SimoRubi questo comportamento è solo alla 14.0

Grazie mille della verifica
