### ISSUE TITLE
[14.0] [l10n_it_declaration_of_intent] Cambio company dopo update all

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2897]
## Module
[l10n_it_declaration_of_intent](https://github.com/OCA/l10n-italy/tree/14.0/l10n_it_declaration_of_intent)

## Describe the bug
Ci è successo da un cliente, che ha un ambiente multi company, che dopo un update all le dichiarazioni di intento hanno cambiato company, attualmente però è l'unico caso che abbiamo.
Qualcuno ha riscontrato un caso simile?

## To Reproduce

- [ ] 14.0
- [ ] 16.0

1. avere un ambiente multi company
2. aver installato e configurato la dichiarazione d'intento, creare una o più dichiarazioni di intento
3. fare un update all 
4. vengono trovate le dichirazioni di intento spostate su un'altra company (Nel nostro caso è stata la prima company).

**Expected behavior**
le dichirazione di intento  rimangono nella company settata inizialmente

**Additional context**

**Comment by SirTakobi** [comment]
Se nell'aggiornamento hai applicato le modifiche di https://github.com/OCA/l10n-italy/pull/2582, può essere che le dichiarazioni esistenti siano state assegnate a una company.
Se è così, si potrebbe correggere creando uno script di migrazione per la versione che introduce la modifica linkata, in modo da non assegnare una company alle dichiarazioni esistenti.

**Comment by matteoopenf** [comment]
> Se nell'aggiornamento hai applicato le modifiche di #2582, può essere che le dichiarazioni esistenti siano state assegnate a una company. Se è così, si potrebbe correggere creando uno script di migrazione per la versione che introduce la modifica linkata, in modo da non assegnare una company alle dichiarazioni esistenti.

Grazie Mille del pronto riscontro.
Si l'ambiente non veniva aggiornato da moltissimo tempo e quindi ha preso questo fix del multi company

**Comment by TheMule71** [comment]
Beh la #2582 non fa cambiare company, prima le dichiarazioni valevano per tutte le company. Vd. https://github.com/OCA/l10n-italy/issues/2578

Quindi non vengono "spostate" perché non erano in una company, ma in tutte.



> Se è così, si potrebbe correggere creando uno script di migrazione per la versione che introduce la modifica linkata, in modo da non assegnare una company alle dichiarazioni esistenti.

Non so, forse è possibile in fase di migrazione assegnare già la company corretta, andando a guardare `line_ids.invoice_id.company_id`:

https://github.com/OCA/l10n-italy/blob/de99fae6022defbdbb6fa4fc0616c90851d63e02/l10n_it_declaration_of_intent/models/declaration.py#L275

Ovviamente funzionerebbe solo per le dichiarazioni già "usate" e andrebbe fatto un controllo tipo:
```
if len(self.mapped("line_ids.invoice_id.company_id")) > 1:
   # ci sono righe nella stessa dichiarazione che riguardano company diverse, allarme rosso
```

Anzi, forse lo si potrebbe mettere nella stessa default, se line_ids è popolato si usa quella logica, altrimenti diventa self.env.company

**Comment by matteoopenf** [comment]
> Beh la #2582 non fa cambiare company, prima le dichiarazioni valevano per tutte le company. Vd. #2578
> 
> Quindi non vengono "spostate" perché non erano in una company, ma in tutte.
> 
> > Se è così, si potrebbe correggere creando uno script di migrazione per la versione che introduce la modifica linkata, in modo da non assegnare una company alle dichiarazioni esistenti.
> 
> Non so, forse è possibile in fase di migrazione assegnare già la company corretta, andando a guardare `line_ids.invoice_id.company_id`:
> 
> https://github.com/OCA/l10n-italy/blob/de99fae6022defbdbb6fa4fc0616c90851d63e02/l10n_it_declaration_of_intent/models/declaration.py#L275
> 
> Ovviamente funzionerebbe solo per le dichiarazioni già "usate" e andrebbe fatto un controllo tipo:
> 
> ```
> if len(self.mapped("line_ids.invoice_id.company_id")) > 1:
>    # ci sono righe nella stessa dichiarazione che riguardano company diverse, allarme rosso
> ```
> 
> Anzi, forse lo si potrebbe mettere nella stessa default, se line_ids è popolato si usa quella logica, altrimenti diventa self.env.company

si credo che l'unica sia quello, noi abbiamo ragionato con il cliente e deciso per un mass editing.
Se però hanno utilizzato una dichiarazione in più company essendo che prima non era previsto credo potrebbe essere un problema perchè non è ne dell'una, ne dell'altra

**Comment by SirTakobi** [comment]
> Beh la https://github.com/OCA/l10n-italy/pull/2582 non fa cambiare company, prima le dichiarazioni valevano per tutte le company. Vd. https://github.com/OCA/l10n-italy/issues/2578
>
> Quindi non vengono "spostate" perché non erano in una company, ma in tutte.

Secondo me restringerle a una company quando prima erano in tutte, equivale a spostarle; per non farlo, come scrivevo basterebbe uno script di migrazione che imposti il nuovo campo `company_id` a `False`.

Se va bene spostarle, allora sì concordo abbia senso guardare le fatture collegate come hai scritto.

> Anzi, forse lo si potrebbe mettere nella stessa default, se line_ids è popolato si usa quella logica, altrimenti diventa self.env.company

I default dei campi non possono tenere conto dei valori degli altri campi del record.
Durante la creazione di un record, viene chiamato https://github.com/odoo/odoo/blob/e54d87b703106c1222f713538601e64e85856466/odoo/models.py#L1170 mentre all'aggiunta della colonna viene chiamato https://github.com/odoo/odoo/blob/e54d87b703106c1222f713538601e64e85856466/odoo/models.py#L2368: entrambi sono in metodo `api.model(_cr_context)`.

Per avere una logica del genere, il nuovo campo dovrebbe essere calcolato.

**Comment by TheMule71** [comment]
Lo considero un bug, avere una dichiarazione da usare su due company diverse, riguarda una sola delle due per forza.  Rischi di usare la stessa dichiarazione per due fatture di due company diverse.

Probabilmente la cosa migliore è lasciare il lavoro allo script di migrazione. Bisogna decidere però dove mettere quelle che non hanno fatture collegate.

**Comment by matteoopenf** [comment]
> Lo considero un bug, avere una dichiarazione da usare su due company diverse, riguarda una sola delle due per forza. Rischi di usare la stessa dichiarazione per due fatture di due company diverse.
> 
> Probabilmente la cosa migliore è lasciare il lavoro allo script di migrazione. Bisogna decidere però dove mettere quelle che non hanno fatture collegate.


Per quelle che non hanno fatture, secondo me, non va assegnata e messo come required il campo, così alla prima volta utile l'utente la assegna alla company esatta. Sentiamo anche altri, ma credo potrebbe essere una via
