### ISSUE TITLE
Importazione fattura elettronica fornitore Semplificata [TD07]

### ISSUE THREAD

**Issue by stevech091** [OCA/l10n-italy#2901]
Importare la fattura fornitore semplificata [TD07]

In allegato un esempio di file xml zippato da importar
[IT002780790107_00001.zip](https://github.com/OCA/l10n-italy/files/9315511/IT002780790107_00001.zip)

- [x] 14.0 #2907
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/4028

**Comment by TheMule71** [comment]
Ci sto guardando, la struttura è diversa. Per es,:

```
  <xs:complexType name="DatiBeniServiziType">
    <xs:annotation>
      <xs:documentation>Blocco relativo ai dati di Beni Servizi della Fattura   Elettronica</xs:documentation>
    </xs:annotation>
    <xs:sequence>
      <xs:element name="Descrizione" type="String1000LatinType" />
      <xs:element name="Importo" type="Amount2DecimalType" />
      <xs:element name="DatiIVA" type="DatiIVAType" />
      <xs:element name="Natura" type="NaturaType" minOccurs="0" />
      <xs:element name="RiferimentoNormativo" type="String100LatinType" minOccurs="0" />
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="DatiIVAType">
    <xs:sequence>
      <xs:element name="Imposta" type="Amount2DecimalType" minOccurs="0" />
          <xs:element name="Aliquota" type="RateType" minOccurs="0"/>
        </xs:sequence>
  </xs:complexType>

```

**Comment by TheMule71** [comment]
Ho incluso un supporto primordiale in #2820.  @stevech091 il tuo file viene importato correttamente. Vd. test n.52 aggiunto a fatturapa_in.

**Comment by TheMule71** [comment]
@stevech091 a proposito se te ne capita una con l'IVA non a zero sarebbe da testare anche quella.

**Comment by francesco-ooops** [comment]
@TheMule71 che tu sappia questa è ancora da risolvere per la 16 corretto?

**Comment by CiroBoxHub** [comment]
Buonasera, sapete dirmi se nella versione 16.0 è stata risolta? non trovo riferimenti.
Sembra che le fatture semplificate siano diventate molto di più in ricezione e non siano più cosi sporadiche
Grazie mille

**Comment by francesco-ooops** [comment]
@CiroBoxHub neanche io ho visto PR per la 16, se vuoi fare fw-porting sei benvenuto!
