### ISSUE TITLE
Ricevere fatture elettroniche in base64 via PEC

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2915]
## Module
l10n_it_fatturapa_pec

## Describe the bug
La fattura elettronica viene creata e presenta l'errore
> Xml 'NoneType' object has no attribute 'iter' non valido.

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/2916
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/3500
- [ ] `16.0`: #4420 

(per la 16 si attendeva il merge di #3785 )

1. Nella PEC, ricevere un'email contenente un file codificato in base64

**Expected behavior**
La fattura elettronica viene creata senza errori

**Additional context**
~Non credo che https://github.com/OCA/l10n-italy/issues/2854 sia collegata perché la fattura allegata non è codificata~
Leggendo meglio la https://github.com/OCA/l10n-italy/issues/2854 si parla di
> Le fatture elettroniche firmate digitalmente, con il allegato il file criptato p7m NON vengono parsate!

quindi potrebbe essere collegata.

**Comment by francesco-ooops** [comment]
@SirTakobi @OCA/local-italy-maintainers una questione riguardante tutte le issues: quando in "affected versions" c'è solo una versione segnalata e non l'altra (considerando 12 e 14 come quelle mantenute da Italy), molto spesso ci sono dei commenti che chiedono se il bug non è presente nell'altra versione o se non è stato verificato se è presente o meno

sarebbe possibile includere sempre entrambi i checkbox per la 12 e la 14 sotto "affected versions"? 
Poi le opzioni possibili per popolarli sarebbero: 

- Non verificata la presenza del bug
- Bug presente
- Bug non presente
- PR (quando viene aperta)

Credo questo aiuterebbe a far chiarezza sullo status delle altre versioni, che ne pensate?

**Comment by SirTakobi** [comment]
Per le versioni che non sono scritte, io di solito suppongo che non sia stato verificato (in questo caso è così).

Se è stato fatto qualcosa nelle altre versioni (verifica o meno del bug, PR o altro), penso sia normale scriverlo nell'apposita casellina.

Per non lasciare nulla di sottinteso si potrebbe modificare il template impostando le versioni supportate a
> Non verificata la presenza del bug

**Comment by francesco-ooops** [comment]
sì mi pare ottimo

**Comment by francesco-ooops** [comment]
> Per le versioni che non sono scritte, io di solito suppongo che non sia stato verificato (in questo caso è così).
> 
> Se è stato fatto qualcosa nelle altre versioni (verifica o meno del bug, PR o altro), penso sia normale scriverlo nell'apposita casellina.
> 
> Per non lasciare nulla di sottinteso si potrebbe modificare il template impostando le versioni supportate a
> 
> > Non verificata la presenza del bug
> 
> EDIT: O anche un più semplice
> 
> > Non verificato
> 
> visto che il titoletto **Affected versions** già suppone si stia parlando del bug in questione

anche solo così è più che chiaro: 

![image](https://user-images.githubusercontent.com/55489873/186856144-249b04f7-deb9-4194-aec9-d6da26613261.png)

potete aggiornare il template?

**Comment by odooNextev** [comment]
@SirTakobi si verifica anche nella v14
https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_pec/models/mail_thread.py#L223

**Comment by odooNextev** [comment]
@SirTakobi ho aperto una PR copiando ed incollando esattamente quanto avevi fatto: https://github.com/OCA/l10n-italy/pull/3500

**Comment by micheledic** [comment]
Novità su questa issue ?

**Comment by matteoopenf** [comment]
> Novità su questa issue ?

le pr sono state mergiate hai ancora il problema con l'ultima versione??

**Comment by micheledic** [comment]
> > Novità su questa issue ?
> 
> le pr sono state mergiate hai ancora il problema con l'ultima versione??

https://github.com/OCA/l10n-italy/blob/080f9b472a4a6ec8442f22fa16ee56ef944572bc/l10n_it_fatturapa_pec/models/mail_thread.py#L225 sulla 16.0 non c'è ancora il b64decode , bisognerebbe fare un fwport della patch

**Comment by matteoopenf** [comment]
> > > Novità su questa issue ?
> > 
> > 
> > le pr sono state mergiate hai ancora il problema con l'ultima versione??
> 
> https://github.com/OCA/l10n-italy/blob/080f9b472a4a6ec8442f22fa16ee56ef944572bc/l10n_it_fatturapa_pec/models/mail_thread.py#L225
> 
> sulla 16.0 non c'è ancora il b64decode , bisognerebbe fare un fwport della patch

puoi fare una pr in proposito?

**Comment by micheledic** [comment]
> > > > Novità su questa issue ?
> > > 
> > > 
> > > le pr sono state mergiate hai ancora il problema con l'ultima versione??
> > 
> > 
> > https://github.com/OCA/l10n-italy/blob/080f9b472a4a6ec8442f22fa16ee56ef944572bc/l10n_it_fatturapa_pec/models/mail_thread.py#L225
> > 
> > sulla 16.0 non c'è ancora il b64decode , bisognerebbe fare un fwport della patch
> 
> puoi fare una pr in proposito?

https://github.com/OCA/l10n-italy/pull/4420 ho cherry-pickato la patch
