### ISSUE TITLE
[14.0][l10n_it_split_payment] impossibile registrare fatture fornitori se posizione fiscale è SP

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#2917]
## Module
l10n_it_split_payment

- [x] 14.0: https://github.com/OCA/l10n-italy/pull/2918

## Describe the bug
Nel caso in cui il partner è sia cliente che fornitore e la posizione fiscale è di tipo Split Payment, il modulo non permette di inserire fatture fornitori

## To Reproduce
Creare un partner e associare una posizione fiscale di tipo split payment, senza mappare imposte di acquisto.
Creare una fattura fornitore e provare a selezionare quel partner.

**Expected behavior**
Odoo non permette di selezionare posizioni fiscali differenti, quindi dobbiamo dare la possibilità agli utenti di creare comunque una fattura fornitore e di modificare manualmente la posizione fiscale che viene erroneamente attributa da Odoo.

**Comment by SirTakobi** [comment]
Si può chiudere?
