### ISSUE TITLE
Aggiornamento template per nuove issue

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2923]
@SirTakobi @OCA/local-italy-maintainers una questione riguardante tutte le issues: quando in "affected versions" c'è solo una versione segnalata e non l'altra (considerando 12 e 14 come quelle mantenute da Italy), molto spesso ci sono dei commenti che chiedono se il bug non è presente nell'altra versione o se non è stato verificato se è presente o meno

sarebbe possibile includere sempre entrambi i checkbox per la 12 e la 14 sotto "affected versions"? 
Poi le opzioni possibili per popolarli sarebbero: 

- Non verificata la presenza del bug
- Bug presente
- Bug non presente
- PR (quando viene aperta)

Credo questo aiuterebbe a far chiarezza sullo status delle altre versioni, che ne pensate?

_Originally posted by @francesco-ooops in https://github.com/OCA/l10n-italy/issues/2915#issuecomment-1227081796_

Un'altra proposta è:
> - [ ] `14.0`: ?

(rif. https://github.com/OCA/l10n-italy/issues/2915#issuecomment-1228197707)

Si potrebbe anche valutare di tradurle in italiano?

**Comment by TheMule71** [comment]
Le issue per me dovrebbero essere abbastanza libere, mettere una checklist con 12 e 14 sembra suggerire che abbia senso aprirle solo per 12 e 14. Poi per me è abbastanza ovvio che se qualcuno non nomina una versione vuol dire che non l'ha provata.

Dobbiamo anche ricordarci che a volte le issue sono il primo punto di ingresso per persone che non sanno nulla di come funziona la nostra comunity, per cui lascerei un abbastanza generico "affected versions" a formato libero.

I commenti che chiedono se il bug/issue è presente in un altra versione li trovo normali, si chiede se qualcuno ha avuto esperienze al riguardo prima di mettersi a testare direttamente.

Anche qui, non tutti sono sviluppatori e hanno l'infrastruttura per fare un test al volo su varie versioni, per cui trovo normale che chiedano. Pure io (che ho vari ambienti 12 e 14 a portata di un cd) chiedo a volte, se non sono al PC o se sto lavorando ad altro e non posso mettermi a fare i test direttamente, o se è qualcosa che funzionalmente conosco poco.

**Comment by francesco-ooops** [comment]
Sinceramente mi sembra una modifica minima che permette di avere da subito sotto controllo la situazione (le issue avranno sempre due task, non si rischia di chiuderle una volta mergiato il fix di una delle due per checkbox non presente) 

Inoltre inviterebbe chi apre la issue a fare un controllo anche in altre versioni, e/o chi aprendo la issue trova una versione non verificata a verificare

Il flusso sarebbe: apri la issue, trovi i due bottoni 12 e 14 con le opzioni già compilate 
("Non ho verificato / Ho verificato, si applica a questa versione / Ho verificato, non si applica a questa versione"), 
rimuovi le opzioni che non si applicano > la community ha già il tracciamento pronto

Non penso che fermerà chi vuole aprire una issue per la 10 dall'aprirla
