### ISSUE TITLE
Le dichiarazioni intrastat non possono essere modificate senza valorizzare il campo "transaction nature B"

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#2935]
## Module
l10n_it_intrastat_statement

## Describe the bug
Riporto qui letteralmente la regola sulla "natura" contenuta nel decreto che è entrato in vigore quest'anno (Det n. 493869 del 23 dicembre 2021 art2)

Negli elenchi riepilogativi relativi alle cessioni ed agli acquisti intracomunitari di beni, i dati
relativi alla natura della transazione sono forniti conformemente alla disaggregazione di cui alle
colonne A e B della Tabella ‹‹Natura della transazione›› di cui all’Allegato XI.

I soggetti di cui all’articolo 6, comma 4 del Decreto ministeriale 22 febbraio 2010, vale a dire i
soggetti che hanno realizzato nell’anno precedente, o in caso di inizio dell’attività di scambi
intracomunitari, presumono di realizzare, nell’anno in corso, un valore delle spedizioni o degli
arrivi superiore a euro 20.000.000, indicano i dati relativi alla natura della transazione
conformemente alla disaggregazione a 2 cifre [colonne A e B] di cui alla Tabella indicata al
comma precedente.

I soggetti diversi da quelli di cui al comma 2 possono indicare i dati relativi alla natura della
transazione conformemente alla disaggregazione a 1 cifra [colonna A] o alla disaggregazione a 2
cifre [colonne A e B] di cui alla Tabella citata al comma 1.

>> conseguenze per noi:
- avremo la maggioranza degli utenti che rientrerà fra i "soggetti diversi" (=spedizioni o ricezioni per meno di 20 mln euro annui) e che dovranno semplicemente valorizzare la colonna/natura A
- potremmo avere alcuni utenti (non si sa mai, guardando alla localizzazione) che devono valorizzare la colonna/natura B
- di conseguenza la scelta più ragionevole appare lasciare facoltativo il campo "B".

## To Reproduce
**Affected versions**:
- [ ] 12.0:
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/2936

1. entro in una dichiarazione INTRA già prodota da contabilità / registrazioni sezionale/ dichiarazioni intrastat
2.premo il bottone edit e vado a modificare una delle righe in "Vendita merci sezione 1"
3.batto sul bottone "salva" 

il sistema colora in rosso il campo "transaction nature B" impedendo di salvare la modifica

**Expected behavior**
il sistema consente di salvare la registrazione, essendo il campo natura transazione B facoltativo sotto un certo livello di valore delle spedizioni

Allegati: 
[Allegato 11 Istruzioni per l'uso e la compilazione degli elenchi riepilogativi.pdf](https://github.com/OCA/l10n-italy/files/9567490/Allegato.11.Istruzioni.per.l.uso.e.la.compilazione.degli.elenchi.riepilogativi.pdf)
[Allegato 12 Specifiche tecniche e tracciati record degli elenchi riepilogativi.pdf](https://github.com/OCA/l10n-italy/files/9567491/Allegato.12.Specifiche.tecniche.e.tracciati.record.degli.elenchi.riepilogativi.pdf)

**Comment by SirAionTech** [comment]
La modifica di #2936 è stata portata a `16.0` dalla migrazione #3327 (ora è https://github.com/OCA/l10n-italy/commit/20fa39cc35201fd1ce26a5ac01b6f6d47fda50a2) quindi si può chiudere.
