### ISSUE TITLE
[14.0][l10n_it_fatturapa_in]

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/l10n-italy#2937]
[IT04194640639_01259.xml.txt](https://github.com/OCA/l10n-italy/files/9582365/IT04194640639_01259.xml.txt)
l10n_it_fatturapa_in 

quando si riceve un file xml con fattura passiva il cui fornitore ha il carattere "&"  nella ragione sociale scritto nella forma &amp;
viene creato il partner senza name con tutti gli altri campi correttamente popolati. 
Non viene segnalato all'utente nessun errore o warning. 

allego un file xml di esempio 

- [ ] 12.0:
- [ ] 14.0:

**Comment by TheMule71** [comment]
Ho provato in runboat 12.0 e 14.0 e pare creare il partner correttamente.

**Comment by francesco-ooops** [comment]
Chiudo, riapri pure se si dovesse ripresentare.
