### ISSUE TITLE
Pagamenti ritenuta d'acconto duplicati

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2938]
## Module
**l10n_it_withholding_tax**

## Describe the bug
Ci sono diversi pagamenti per la ritenuta d'acconto

## To Reproduce
**Affected versions**:
- [x] `12.0`: #2939
- [x] `14.0`: sì
- [x] 16.0: https://github.com/OCA/l10n-italy/pull/4014

1. Creare una fattura fornitore da 10 + 2.2 contenente una ritenuta d'acconto da 10%
2. Confermare e pagare l'importo dovuto della fattura (11.2)
3. Riportare in bozza, confermare e collegare il pagamento esistente della fattura
4. Riportare in bozza, confermare

**Expected behavior**
Esiste un solo pagamento in sospeso per la ritenuta d'acconto

**Comment by TheMule71** [comment]
Ciao, ho modificato il testo, avevi linkato #2938 e non #2939

**Comment by eLBati** [comment]
@SirTakobi non è un duplicato di https://github.com/OCA/l10n-italy/issues/2637 ?

**Comment by SirTakobi** [comment]
> @SirTakobi non è un duplicato di #2637 ?

Non credo: in #2637 il problema è che vengono create diverse "Dichiarazioni ritenuta d'acconto", mentre qui il problema è che vengono creati diversi pagamenti per la ritenuta d'acconto nella fattura.

**Comment by SirAionTech** [comment]
In runbot `16.0` non riproduco il problema descritto:

[Screencast from 07-03-2024 10:38:39.webm](https://github.com/OCA/l10n-italy/assets/143788994/96e5df99-876d-43cc-a7ef-203af3cbd747)

**Comment by sergiocorato** [comment]
Sulla 14.0 non mi risulta ci sia questo problema, per cui la toglierei dalle versioni da sistemare (ce c'è uno affine ma diverso, apro una issue separata, vedi sotto).

![Screenshot(24)](https://github.com/OCA/l10n-italy/assets/7657311/97aeeae7-e986-4e45-939f-60aa1fc43da8)
