### ISSUE TITLE
Selezione liquidazione IVA precedente

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#2941]
## Module
**account_vat_period_end_statement**
## Describe the bug
L'importo della liquidazione IVA precedente non corrisponde alla liquidazione avente lo stesso conto.

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/2942
- [ ] `14.0`: #2943
- [x] `16.0`: https://github.com/OCA/l10n-italy/pull/3468

1. Creare una fattura fornitore da 10 + 2.2 in data 2/2/2022 e confermarla,
    l'imposta nella fattura ha il conto per la liquidazione IVA impostato a **conto1**
2. Creare una liquidazione IVA che comprenda la fattura creata, selezionando il conto **conto1**
3. Creare un'altra fattura fornitore da 20 + 4.4 in data 2/2/2022 e confermarla,
l'imposta nella fattura ha il conto per la liquidazione IVA impostato a **conto2**
4. Creare una liquidazione IVA che comprenda la fattura creata, selezionando il conto **conto2**
5. Creare una liquidazione IVA con data successiva alle precedenti per il conto **conto1**
6. Creare una liquidazione IVA con data successiva alle precedenti per il conto **conto2**

**Expected behavior**
La liquidazione IVA per il conto **conto1** ha **IVA debiti precedenti** 2.2.
La liquidazione IVA per il conto **conto2** ha **IVA debiti precedenti** 4.4.

**Additional context**
Questo è un problema perché attualmente le liquidazioni IVA riportano **IVA debiti precedenti** delle liquidazioni IVA OSS e viceversa.

**Comment by francesco-ooops** [comment]
@tafaRU puoi aggiungere #3468 al corpo della issue?

**Comment by tafaRU** [comment]
> @tafaRU puoi aggiungere #3468 al corpo della issue?

done
