### ISSUE TITLE
Autofattura elettronica reverse charge extra UE

### ISSUE THREAD

**Issue by vincenzoriggi** [OCA/l10n-italy#2946]
## Module
l10n_it_fatturapa_out_rc

## Describe the bug
Quando provo ad esportare un auto fattura elettronica reverse charge extra UE mi comare questo errore:

Traceback (most recent call last):
  File "/opt/odoo14/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo14/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
ValueError: Country code does not exist or it is not mapped in countries: 24

## To Reproduce
**14**:

1. Creare una fattura acquisto fornitore estero (India) e salvarla;
2. Il sistema genera un auto fattura;
3. Convertire i valori da USD in EURO;
4. Esportare il documento.

**Expected behavior**
Il sistema dovrebbe generare il file da inviare allo SDI

**Comment by TheMule71** [comment]
Hai modo di provare se #2602 risolve?

**Comment by vincenzoriggi** [comment]
Si, con #2602 ho risolto.
Grazie
