### ISSUE TITLE
[14.0] [l10n_it_fatturapa_export_zip]

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#2955]
## Module
l10n_it_fatturapa_export_zip

## Describe the bug
Se si tenta l'esportazione dello zip di alcuni xml, tramite l'apposita funzione del modulo si ottiene un errore

## To Reproduce

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/2954

1. Creare una fattura
2. esportare la fattura e quindi creare il file xml
3. tentare di esportare lo zip da azione
4. errore che si ottiene:
  File "/opt/odoo/odoo/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 1394, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo/odoo/addons/web/controllers/main.py", line 1382, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 399, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/odoo/odoo/odoo/api.py", line 386, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/parts/OCA/l10n-italy/l10n_it_fatturapa_export_zip/wizard/export_fatturapa.py", line 47, in export_zip
    "datas": base64.encodestring(data),
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: module 'base64' has no attribute 'encodestring'

**Expected behavior**
Il file zip viene creato con successo

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by TheMule71** [comment]
Il problema esiste solo con python 3.9 credo. La 14 è stata rilasciata con il 3.6. Comunque la funzione in questione è stata deprecata fin dalla 3.1, per cui ha senso considerarlo un bug.

**Comment by matteoopenf** [comment]
> Il problema esiste solo con python 3.9 credo. La 14 è stata rilasciata con il 3.6. Comunque la funzione in questione è stata deprecata fin dalla 3.1, per cui ha senso considerarlo un bug.

si esatto secondo ma ha senso considerarlo un bug, perchè doveva già dare errore in teoria.
Noi ce ne siamo accorti testandolo su python 3.9, ma immagino desse errore anche prima

**Comment by TheMule71** [comment]
> Noi ce ne siamo accorti testandolo su python 3.9, ma immagino desse errore anche prima

No, nella 3.6 (quella usata per fare i test) non dava errore, non sarebbe stata mergiata altrimenti.
Vd. https://github.com/python/cpython/issues/83532#issuecomment-1093851153

**Comment by matteoopenf** [comment]
> > Noi ce ne siamo accorti testandolo su python 3.9, ma immagino desse errore anche prima
> 
> No, nella 3.6 (quella usata per fare i test) non dava errore, non sarebbe stata mergiata altrimenti. Vd. [python/cpython#83532 (comment)](https://github.com/python/cpython/issues/83532#issuecomment-1093851153)

Grazie mille della precisazione
