### ISSUE TITLE
[14.0] Implementa "Conto utilizzato per la liquidazione IVA"

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#2956]
Porting alla 14 della #2385.

- [x] 14.0 #2957
- [x] 16.0 #3468

**Comment by Borruso** [comment]
16.0 #3468

**Comment by SirAionTech** [comment]
Questa è un https://github.com/OCA/l10n-italy/labels/enhancement o una https://github.com/OCA/l10n-italy/labels/hotfix?
Si può aggiungere in descrizione qualche dettaglio in più su qual è il miglioramento introdotto/problema risolto?

**Comment by sergiocorato** [comment]
> Questa è un [ enhancement](https://github.com/OCA/l10n-italy/labels/enhancement) o una [ hotfix](https://github.com/OCA/l10n-italy/labels/hotfix) ? Si può aggiungere in descrizione qualche dettaglio in più su qual è il miglioramento introdotto/problema risolto?

vedi https://github.com/OCA/l10n-italy/pull/2385#issuecomment-892353471

**Comment by SirAionTech** [comment]
> > Questa è un [ enhancement](https://github.com/OCA/l10n-italy/labels/enhancement) o una [ hotfix](https://github.com/OCA/l10n-italy/labels/hotfix) ? Si può aggiungere in descrizione qualche dettaglio in più su qual è il miglioramento introdotto/problema risolto?
> 
> vedi [#2385 (comment)](https://github.com/OCA/l10n-italy/pull/2385#issuecomment-892353471)

E https://github.com/OCA/l10n-italy/pull/2385#issuecomment-894220918?
C'è un po' di discussione nella PR, per questo ho pensato sarebbe meglio riassumere il significato in questa issue
