### ISSUE TITLE
Delivery Note does not update stock.delivery.note.line quantity if you update stock.picking line quantity value

### ISSUE THREAD

**Issue by OmniaGit** [OCA/l10n-italy#2970]
## Module
delivery_note

## Describe the bug
Delivery Note does not update stock.delivery.note.line quantity if you update stock.picking line quantity value

## To Reproduce
**Affected versions**:

1.Create a stock.picking adding a line and validate it
2.Create a delivery note with the above picking
3.Go to the picking unlock the picking and change the quantity
4.the quantity changed is not reflected in the delivery note

**Expected behavior**
the quantity on the delivery note must reflect the stock picking quantity

**Comment by TheMule71** [comment]
Hi, is this for version 12 or 14, or both?
