### ISSUE TITLE
La massa netta nell'intrastat statement deve essere opzionale

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#2980]
## Module
l10n_it_intrastat_statement

## Describe the bug
L'indicazione della massa netta nell'intra cessioni non è sempre obbligatoria, le specifiche indicano questa regola:
"
Per le sottovoci della nomenclatura combinata che prevedono anche l’unità supplementare, la colonna deve essere compilata esclusivamente dai soggetti di cui all’art. 6, comma 4, del decreto del Ministro dell’Economia e delle Finanze 22 febbraio 2010.
"

La totale implementazione della regola (che fa riferimento al fatturato annuale) appare eccessivamente onerosa, si lascia quindi all'utente la scelta se indicare la massa netta oppure no, indicandolo nella sezione intra della fattura.

Il funzionamento attuale del sistema, però, nel calcolare i dati per il modello intra riporta una massa di kg 1 (la regola di esposizione per masse <= 1) anche nel caso in cui l'utente voglia omettere l'indicazione della massa indicando 0 nella sezione intra della fattura.

La soluzione più ragionevole e meno ambigua è quindi quella di mettere un flag nella sezione intra, attraverso il quale l'utente escluda l'indicazione della massa netta.

## To Reproduce
- [x] 12.0: ? (risolta per termine supporto)
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/2981
- [x] 16.0: la modifica è già stata integrata, vedi https://github.com/OCA/l10n-italy/blob/16.0/l10n_it_intrastat/models/account.py#L606

**Expected behavior**
Poter omettere la massa netta nello statement
L'omissione consiste nel inserire il valore 0

**Comment by francesco-ooops** [comment]
@michelerusti puoi fare il porting alla 16? grazie!

**Comment by sergiocorato** [comment]
Chiudo in quanto sulla 16.0 la modifica c'è già.

**Comment by sergiocorato** [comment]
(v. commit https://github.com/OCA/l10n-italy/commit/3dcfe3910160662e193e4f7c4ad0c2d36b538ae2
e https://github.com/OCA/l10n-italy/commit/6187f39740e8e2f21b054aa9fb87c91eae4535ea )
