### ISSUE TITLE
fatturapa_out_di impossibile esportare documenti xml con utente in italiano

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3006]
Utente con lingua italiana
Creare una fattura con lettera d'intento 
Tentare esportazione xml si genera un errore relativo agli importi
 
 Il motivo è una traduzione che non doveva essere fatta e che imposta 0.00 a 0,00 
 Va quindi eliminata 
Link il commit della traduzione
 
https://github.com/OCA/l10n-italy/commit/72fc53306bd9d5db00e2a4667e49e63bd704e0f4

- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/3008
- [ ] 16.0 #3715

**Comment by francescapenso** [comment]
@primes2h avanzo una birra

**Comment by TheMule71** [comment]
Il modulo consiste  (test a parte) in un singolo file che estende il template della fattura el., non ci dovrebbero essere traduzioni.

@primes2h pure io avanzo...

**Comment by primes2h** [comment]
> Il modulo consiste (test a parte) in un singolo file che estende il template della fattura el., non ci dovrebbero essere traduzioni.


> 
> @primes2h pure io avanzo...



> Utente con lingua italiana Creare una fattura con lettera d'intento Tentare esportazione xml si genera un errore relativo agli importi
> 
> Il motivo è una traduzione che non doveva essere fatta e che imposta 0.00 a 0,00 Va quindi eliminata Link il commit della traduzione
> 
> [72fc533](https://github.com/OCA/l10n-italy/commit/72fc53306bd9d5db00e2a4667e49e63bd704e0f4)

> Il modulo consiste (test a parte) in un singolo file che estende il template della fattura el., non ci dovrebbero essere traduzioni.

Di per sè la traduzione è corretta perché porta il valore numerico da notazione inglese (punto) a una italiana (virgola).

Come dici tu, il problema sta nel fatto che quelle stringhe non dovevano neanche comparire nel .po, andava messo `t-translation="off"` nel relativo blocco del template. (vedi https://www.odoo.com/documentation/14.0/developer/howtos/translations.html#implicit-exports).

> @primes2h pure io avanzo...

Mi sa che sei tu che devi una birra a @francescapenso e a me. :wink: 

https://github.com/OCA/l10n-italy/commit/fc7a4b79e3347de0f7b3873a149e77d322a23433


@francescapenso 
Per ora come workaround ho cambiato la stringa tradotta.

https://github.com/OCA/l10n-italy/commit/8aed19049614982eed9ce1465dc85e19a9159cbc

Più tardi apro una PR con un fix per il template.

**Comment by TheMule71** [comment]
Tipo per dire
https://github.com/OCA/l10n-italy/blob/8989405086f6f8f2572568074ef9a34f4f210d94/l10n_it_fatturapa_out/data/invoice_it_template.xml#L149
non sia mai che preso dal sacro fuoco della traduzione qualcuno traduca 'EAN' in 'NAE'... :)

**Comment by primes2h** [comment]
> In tal caso vanno guardati tutti i template, compreso il template principale in fatturapa_out.

In teoria dovrebbe essere sufficiente aggiornare il template principale dato che gli altri poi lo ereditano, ma non ne sono sicuro al 100%.

**Comment by primes2h** [comment]
> Tipo per dire
> 
> https://github.com/OCA/l10n-italy/blob/8989405086f6f8f2572568074ef9a34f4f210d94/l10n_it_fatturapa_out/data/invoice_it_template.xml#L149
> 
> non sia mai che preso dal sacro fuoco della traduzione qualcuno traduca 'EAN' in 'NAE'... :)

In quel caso vuol dire che non ha letto bene le linee guida. ;-)

**Comment by primes2h** [comment]
> > In tal caso vanno guardati tutti i template, compreso il template principale in fatturapa_out.
> 
> In teoria dovrebbe essere sufficiente aggiornare il template principale dato che gli altri poi lo ereditano, ma non ne sono sicuro al 100%.

Ho appena provato.

Es. [questa modifica](https://github.com/OCA/l10n-italy/pull/3008/files#diff-11dc48afbaae626667c7075d54bb69cb88a77b2a679a3eb4affdb6eeef377c5cR16-R18) non è sufficiente ad evitare che [questa](https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_out_stamp/i18n/l10n_it_fatturapa_out_stamp.pot#L18) stringa venga aggiunta al .pot   (a causa di [questo](https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_out_stamp/views/account_invoice_it_dati_bollo.xml#L8) `replace`).
Provo a modificare la PR.

**Comment by TheMule71** [comment]
Mi sa che va fatto in ogni template.

**Comment by primes2h** [comment]
> In tal caso vanno guardati tutti i template, compreso il template principale in fatturapa_out.

Per dire.
https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_out_wt/i18n/l10n_it_fatturapa_out_wt.pot#L18

Qui è andata bene, solo perché ogni tanto weblate si incricca e non rigenera i .po aggiornati di qualche modulo.

**Comment by TheMule71** [comment]
E questo può dare problemi? https://github.com/odoo/odoo/blob/ec41980851fb98da25a06de3ef79cfcb152ab5dd/addons/l10n_it_edi/data/invoice_it_template.xml#L139
a parte che originariamente è in Italiano, ma viene comunque messo nel db come stringa traducibile (inglese), no?

**Comment by primes2h** [comment]
> Mi sa che va fatto in ogni template.

Infatti ho provato con `inside`ma non funziona.

**Comment by primes2h** [comment]
> E questo può dare problemi? https://github.com/odoo/odoo/blob/ec41980851fb98da25a06de3ef79cfcb152ab5dd/addons/l10n_it_edi/data/invoice_it_template.xml#L139 a parte che originariamente è in Italiano, ma viene comunque messo nel db come stringa traducibile (inglese), no?

Problemi non penso, ma in ogni caso non deve stare lì.

**Comment by TheMule71** [comment]
Abbiamo un alternativa + semplice forse.
Invce di `<xxx>Valore</xxx>` mettere `<xxx t-out="'Valore'" />`
quello senza `_()` non lo mette come valore traducibile.

**Comment by primes2h** [comment]
> Abbiamo un alternativa + semplice forse. Invce di `<xxx>Valore</xxx>` mettere `<xxx t-out="'Valore'" />` quello senza `_()` non lo mette come valore traducibile.

Se funziona potrebbe essere un'alternativa. 
Mi sembra però più complicata da gestire perché il lavoro deve essere fatto per ciascuna stringa.

Agendo a livello di template si fa una volta sola per tutte le stringhe contenute, a meno che non ci siano casi in cui sia effettivamente necessario avere le stringhe traducibili.

**Comment by primes2h** [comment]
> > Più tardi apro una PR con un fix per il template.
> 
> @francescapenso @TheMule71
> 
> Ho aperto la #3007, ora il .pot risulta vuoto.

La nuova PR, che tiene conto di tutti i template, è la https://github.com/OCA/l10n-italy/pull/3008

**Comment by primes2h** [comment]
> > > Più tardi apro una PR con un fix per il template.
> > 
> > 
> > @francescapenso @TheMule71
> > Ho aperto la #3007, ora il .pot risulta vuoto.
> 
> La nuova PR, che tiene conto di tutti i template, è la #3008

Segnalatemi se ne mancano per cortesia.
