### ISSUE TITLE
Il fondo ammortizzato nell'anno precedente non considera tutti gli anni precedenti

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3009]
## Module
assets_management

## Describe the bug
Il totale **Fondo amm.to anno prec.** nel registro dei beni ammortizzabili non considera tutti gli anni precedenti.

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/3010
- [x] `14.0`: #3544 
- [ ] 16.0: #3776 

1. Creare un cespite acquistato nel 2019 per 1000€
2. Creare degli ammortamenti per il cespite in modo che sia completamente ammortizzato nel 2020
3. Generare il registro dei beni ammortizzabili per il 2022

**Expected behavior**
Il totale **Fondo amm.to anno prec.** riporta 1000€

**Actual behavior**
Il totale **Fondo amm.to anno prec.** riporta 0€

**Comment by francesco-ooops** [comment]
@SirTakobi o @sergiocorato giusto per controllare, per caso sapete se questa issue è ancora valida per la v14?

**Comment by sergiocorato** [comment]
> @SirTakobi o @sergiocorato giusto per controllare, per caso sapete se questa issue è ancora valida per la v14?

Secondo oca-port il commit non risulta portato, verifico.

**Comment by SirAionTech** [comment]
Ho incluso la fix per questa problematica nella migrazione a `16.0` https://github.com/OCA/l10n-italy/pull/3776.

**Comment by francesco-ooops** [comment]
@SirAionTech linkata
