### ISSUE TITLE
Caricando le fatture come file.xml vengono perse le righe della fattura

### ISSUE THREAD

**Issue by mktsrl** [OCA/l10n-italy#3012]
## Module
account, l10n_it_fatturapa_in

## Describe the bug
Attualmente importando un file.xml come quello che allego di esempio per una fattura fornitore, non vengono caricate le linee della fattura.
Sembrerebbe che sia stato modificato il comportamento del bottone che importa il file xml della fattura, oltre che la sua posizione (prima appariva nella form di creazione di una nuova fattura) e penso che si sia conseguentemente perso il comportamento esteso da l10n_it_fatturapa_in
Lo stesso problema lo riscontro anche sulle fatture cliente

Allego un file di esempio di fattura che risente di questo problema: [IT01234567897_D2U9F.zip](https://github.com/OCA/l10n-italy/files/9653547/IT01234567897_D2U9F.zip)

## To Reproduce
**14.0**:

1. App Fatturazione > Fornitori > Fatture fornitore > (bottone) Carica > seleziono il file [IT01234567897_D2U9F.zip](https://github.com/OCA/l10n-italy/files/9653547/IT01234567897_D2U9F.zip) > non carica le righe
2. App Fatturazione > dashboard > (bottone) Carica > seleziono il file [IT01234567897_D2U9F.zip](https://github.com/OCA/l10n-italy/files/9653547/IT01234567897_D2U9F.zip) > non carica le righe

(stessa cosa per fattura cliente)

**Expected behavior**
Caricando il file xml devono essere caricate anche le linee

**Additional context**
Ubuntu 20.4 - Python 3.8 - (OCA/Italy aggiornato all'ultima versione)

**Comment by tafaRU** [comment]
Una volta creato `fatturapa.attachment.in` è necessario selezionare il menu Import Electronic Bill:

![image](https://user-images.githubusercontent.com/3512779/200860577-81953005-68c0-414b-86d7-dba6b85df4ad.png)

Ho appena provato su runboat e la fattura viene caricata coretttamente: http://oca-l10n-italy-14-0-8dee28fe07df.runboat.odoo-community.org/web#id=1&action=515&model=fatturapa.attachment.in

**Comment by mktsrl** [comment]
Grazie,
chiudo la issue
