### ISSUE TITLE
l10n_it_delivery_note & l10n_it_delivery_note_batch

### ISSUE THREAD

**Issue by jado95** [OCA/l10n-italy#3030]
## Module
l10n_it_delivery_note, l10n_it_delivery_note_batch

## Describe the bug
Error in validation batch picking.

## To Reproduce
**14.0**:

1.Don't enable 'Use Advanced DN Features' in settings.
In batch picking, if are selected more pickings with different partner, in validation of batch, Odoo raise Error:
"You have just called this method on an heterogeneous set of pickings.
All pickings should have the same 'partner_id' field value."

**Comment by tafaRU** [comment]
@jado95 potresti chiarire meglio la problematica?

**Comment by jado95** [comment]
> @jado95 potresti chiarire meglio la problematica?

@tafaRU Adesso vado a memoria, ma senza abilitare le funzionalità avanzate del DN, da un batch picking che contiene diversi picking con partner diversi, in fase di validazione del batch picking, viene fuori quell'errore.
