### ISSUE TITLE
[14.0][l10n_it_fatturapa_in]

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3037]
## Module
l10n_it_fatturapa_in

## Describe the bug
Attualmente quando si crea una autofattura e si manda allo SDI viene messo id codice con il codice  della nazione e Id paese con la vat in fase di esportazione.
Questa fattura poi lo SDI a sua volta recapita nuovamente all'azienda.
Quando Odoo poi la va a leggere per calcolare che è il fornitore, segnatamente qui:
https://github.com/OCA/l10n-italy/blob/c514a5c71c80ff37ee564437a71ea8aa350be99d/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L200
ci si trova che nel campo vat  finisce la concatenazione della stringa IDnazione+IDCODICE se tuttavia su IDCODICE c'è anche compreso il codice nazione  avremo per esempio FRFR12345678

## To Reproduce
**Affected versions**:

- [ ] 12.0
- [ ] 14.0: https://github.com/OCA/l10n-italy/pull/3138 ?

1. Creare una autofattura di un partner che ha la vat impostata
2. Inviarla allo SDI e attendere il ritorno
3. alla ricezione non sarà possibile calcolare il fornitore

**Expected behavior**
Il fornitore viene calcolato correttamente

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by TheMule71** [comment]
Va fatto solo per IT e ovviamente solo se non c'è già.
La 12 ha del codice più recente, ma ha comunque il problema di questa issue.

**Comment by matteoopenf** [comment]
> https://github.com/OCA/l10n-italy/blob/33510f2544701119fd5aa95a91b3e96439e1d02e/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L195-L202
> 
> La piva di altri stati non inizia necessariamente col loro ~IdCodice~ IdPaese

Allora è ancora più complesso ci ragiono su come aprire una eventuale pr

**Comment by matteoopenf** [comment]
però in fondo le fatture in arrivo dall'estero sono in sostanza, quelle in reverse charge e le autofatture che sono quelle che noi generiamo su Odoo, ci sono altre possibilità?
Per esempio non mi sembra possa attualmente accadere che l'azienda x dalla francia mi manda una fattura, giusto?

**Comment by tafaRU** [comment]
Ci sarebbe eventualmente da fare il back-porting di https://github.com/OCA/l10n-italy/pull/3138
