### ISSUE TITLE
[8.0][DDT] gestione dei prodotti di tipo servizio

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#304]
Utilizzando in produzione questo modulo mi rendo conto di quanto sia necessario aggiungere ulteriori funzionalità.

intanto qui https://github.com/OCA/stock-logistics-workflow/pull/301/ ho creato due moduli che tornano utili al fine di visualizzare l'importo del documento

ora, secondo i casi d'uso che sto affrontando, si rende necessario gestire la fatturazione dei prodotti di tipo servizio (es. trasporto o verniciatura o altri) perchè allo stato attuale, questi prodotti presenti negli ordini di vendita restano non fatturati perchè nel ddt (stock.pricking.package.preparation) non vengono portati.
sarebbe opportuno portarli nel ddt per poi averli in fase di fatturazione e non perdere righe da fatturare.

cosa ne pensate?

**Comment by sergiocorato** [comment]
Ciao,
sicuramente è una cosa necessaria, finora non me l'hanno chiesto ma a breve capiterà. Nella concorrenza si possono fatturare prodotti di qualsiasi tipo, inoltre si può decidere se vanno o no in fattura.

**Comment by gigidn** [comment]
"Fiscalmente" a sensazione dovrebbe essere sbagliato, il DDT serve a far viaggiare la merce (fisica) in assenza di fattura ed i servizi non sono merci.

A memoria la logica di fatturazione sulla 8 dovrebbe gia' riportare i servizi inizialmente esclusi, quindi quando si va a fatturare un picking la corrispondente fattura dovrebbe gia' riportare i servizi presenti nell'ordine.

Tempo fa lessi qualcosa sulla possibilità di creare una fattura differita dei servizi ma non ricordo nulla, nella prassi comune comunque la fattura per i servizi (a meno di non essere parte integrante del prodotto ed in quel caso sarebbe meglio usare la produzione) andrebbe fatta contestualmente alla loro consegna.

Tutto questo per dire che inserire i servizi nel DDT non mi sembra una bella cosa, se poi i limiti della v8 (il problema non si pone per v9 e v10) son tali da costringere ad un tale approccio amen ma prima valuterei bene tutte le strade possibili di configurazione e gestione.

**Comment by scigghia** [comment]
@gigidn la proposta nasce proprio dal fatto che i prodotti di tipo servizio, non finiscono nel DDT e rischiano di rimanere "non fatturati"

**Comment by sergiocorato** [comment]
i servizi non andrebbero stampati tramite un filtro sul report del ddt (non
ha senso stampare un servizio in un ddt), si sta parlando solo di metterli
visibili all'utente in odoo e poi invece in fattura andrebbero avanti
normalmente (direi)

Sergio Corato
cel. wsp +39 348 6622 725
skype     sergiocorato

2017-03-01 11:41 GMT+01:00 Andrea Cometa <notifications@github.com>:

**Comment by gigidn** [comment]
Mi sono espresso male evidentemente .... a mia memoria:

1) Creo un Sale.Order con 3 staccabili e 2 servizi
2) Odoo crea la spedizione per i 3 stoccabili 
3) Spedisco i 3 prodotti
4) Creo la fattura dalla spedizione
5) Odoo mette i prodotti spediti e tutte le linee servizio non ancora fatturati che erano presenti nell'odine originale in fattura.

Il rischio che i prodotti rimangano "non fatturati" è pressoché nullo. E' vero che il workflow di un ordine misto sulla v8 è un macello ed alcune cose son tenute con gli spilli ma questo purtroppo è un limite della v8. Oltretutto andrebbe verificato che non si abbia doppia fatturazione per i servizi per effetto del workflow di cui sopra.

Poiché vado a memoria non ho i mezzi per valutare bene il tutto, vi ho semplicemente esposto il mio punto di vista ed alcuni punti sui ci far attenzione.

**Comment by sergiocorato** [comment]
A dire la verità non ho verificato però spesso l'ordine non definisce tutti
i valori e dettagli che potrebbero cambiare in seguito per cui uno si
aspetta di poterli cambiare in una fase successiva e chiaramente che
vengano fatturati
Questa fase di solito è il DDT

Sergio Corato

Il 01 mar 2017 12:52 PM, "Luigi Di Naro" <notifications@github.com> ha
scritto:

**Comment by dcorio** [comment]
Ci sono alcuni regimi fiscali in cui il ddt viene usato come documento di vendita al quale segue fatturazione differita mensile, sopratutto in campo agricolo.

La normativa non dice come e per cosa deve essere usato un ddt, ma pone dei requisiti minimi e dei vicoli.
Ne consegue che in Italia il ddt è diventato un documento multi-uso, sul quale compaiono non solo i beni effettivamente spediti, ma anche annotazioni, servizi di imballaggio e pure i prezzi dei beni venduti.

Che sia corretto o meno, è una prassi che purtroppo dobbiamo tenere in considerazione.

**Comment by gigidn** [comment]
Discussione interessante che andrebbe affrontata in maniera più' generale del semplice aspetto implementativo su una specifica versione. Sperando di far cosa gradita mi son permesso di aprire una discussione apposita:

https://odoo-italia.org/index.php/kunena/24-generale/13888-la-funzione-del-ddt

**Comment by sergiocorato** [comment]
@scigghia Facendo una verifica sulla fatturazione degli ordini (con tipo di fatturazione da ordine di consegna), i servizi vengono sempre fatturati (anche le note), anche se non presenti nel ddt.
Ci sono delle possibilità di errore nell'utilizzo, ma la mancanza di funzionalità non esiste, o non ho capito bene come fatturi.

**Comment by gigidn** [comment]
@sergiocorato il "bug" virgolettato perché non è detto che lo sia si ha quando inserisci direttamente un servizio sul DDT senza che questo sia presente nell'ordine. La possibilità di inserire direttamente "prodotti" sul DDT porta con se diversi bug funzionali come descritti sul thread nel forum ed i servizi non fatturati son uno dei tanti. Se invece segui il processo canonico, senza pasticciare le linee (che a quel punto non servono) tutto funziona come hai evidenziato.

**Comment by scigghia** [comment]
@sergiocorato mi sono spiegato male, e @gigidn ha riassunto meglio quello che intendo.
il punto è che capita di trovare utenti abituati a gestire il ddt come un ordine o come una fattura, inserendo/eliminando manualmente righe di prodotti

**Comment by sergiocorato** [comment]
Si, scusa non ho più avuto tempo per guardare, devo togliere dei moduli
aggiuntivi che avevo fatto per evitare il problema presumo, visto che non
riesco a riprodurlo

Sergio Corato

Il 19 apr 2017 14:58, "Andrea Cometa" <notifications@github.com> ha scritto:

@sergiocorato <https://github.com/sergiocorato> mi sono spiegato male, e
@gigidn <https://github.com/gigidn> ha riassunto meglio quello che intendo.
il punto è che capita di trovare utenti abituati a gestire il ddt come un
ordine o come una fattura, inserendo/eliminando manualmente righe di
prodotti

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OCA/l10n-italy/issues/304#issuecomment-295260616>, or mute
the thread

**Comment by sergiocorato** [comment]
chiudo per inattività
