### ISSUE TITLE
l10n_it_fiscalcode - Controllo su codice fiscale per partner non Italiani

### ISSUE THREAD

**Issue by jado95** [OCA/l10n-italy#3054]
Nel modulo in oggetto,  sull' `@api.constrains("fiscalcode")` , metodo check_fiscalcode, perchè non far scaturire i vari controlli di validità CF solo nel caso in cui i partner siano Italiani? C'è un motivo specifico?

**Comment by TheMule71** [comment]
Gli stranieri possono avere codice fiscale italiano, credo, basta che lo chiedano. Non devi essere cittadino italiano. Non credo tu debba nemmeno essere residente in Italia.

**Comment by primes2h** [comment]
> Gli stranieri possono avere codice fiscale italiano, credo, basta che lo chiedano. Non devi essere cittadino italiano. Non credo tu debba nemmeno essere residente in Italia.

Esatto, non devi essere cittadino italiano e neanche residente per averlo.
Nel campo "Nato a" viene messo lo stato estero di nascita e come codice provincia viene messo EE.

**Comment by jado95** [comment]
Ok Grazie.
Ho chiesto semplicemente perchè se viene inserito qualcosa nel campo codice fiscale che non sia il codice fiscale italiano, questo va in errore (parlo di persone non italiane ovviamente).
Ma va bene, chiuso la issue.

**Comment by patrickt-oforce** [comment]
@jado95 ti riferisci a codici fiscali soggetti a omocodia?
