### ISSUE TITLE
[14.0][FIX] - l10n_it_ricevute_bancarie- La data del movimento di una distinta insoluta deve avere come data la scadenza della riga nella distinta, non "oggi"

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3068]
## Module
l10n_it_ricevute_bancarie

- [ ] 12.0: ?
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3067

1.Contabilità  > riba > distinte
2.Prendo una qualsiasi distinta aperta
3.Clicco su "segna come insoluta" di una riga qualsiasi

**Current behavior**
Il sistema registra l'insoluto con data contabile "ora", cioè dipende dal momento in cui registro l'insoluto

**Expected behavior**
il sistema registra l'insoluto alla data di scadenza, predetermina cioè la data di registrazione contabile nel giorno in cui il cliente avrebbe dovuto adempiere.

**Comment by tafaRU** [comment]
Già inclusa nella PR di migrazione alla `16.0`: https://github.com/OCA/l10n-italy/pull/3131
