### ISSUE TITLE
tax witholding doesn't work for multi currency

### ISSUE THREAD

**Issue by arakattack** [OCA/l10n-italy#307]
![screen shot 2017-02-12 at 19 57 40](https://cloud.githubusercontent.com/assets/12294296/22861886/9a65c854-f15e-11e6-82b5-ef48b677c2cd.png)

Tax witholding doesn't work for multi currency.
I tried on runbot with multi currency. it doesn't calculate forex transaction. It passed debit & credit directly and ignoring amount_currency.

**Comment by eLBati** [comment]
@alessandrocamilli could you have a look?

**Comment by sergiocorato** [comment]
chiudo per inattività
