### ISSUE TITLE
ValueError: Il campo `withholding_tax_in_print` non esiste

### ISSUE THREAD

**Issue by wowstore87** [OCA/l10n-italy#3075]
![image](https://user-images.githubusercontent.com/102078482/204398153-c3c76499-c30a-434b-b0ac-3fd3dd5736f3.png)

Mi trovo in questa situazione e quando clicco su fatturazione ricevo l'errore in oggetto, 

ValueError: Il campo `withholding_tax_in_print` non esiste

se scarico gli aggiornamenti dei componenti aggiuntivi, riavvio odoo senza eseguire l'aggiornamento e ricevo questo errore, ( lo estrapolo dal file log ) 

Error to render compiling AST
ProgrammingError: column res_company.xml_divisa_value does not exist
LINE 1: ...ding_state" as "account_invoice_onboarding_state","res_compa...
                                                             ^

Template: website.layout
Path: /templates/t/t/t[1]
Node: <t t-set="html_data" t-value="{             'lang': lang and lang.replace('_', '-'),             'data-website-id': website.id if website else None,             'data-editable': '1' if editable else None,             'data-translatable': '1' if translatable else None,             'data-edit_translations': '1' if edit_translations else None,             'data-view-xmlid': xmlid if editable or translatable else None,             'data-viewid': viewid if editable or translatable else None,             'data-main-object': repr(main_object) if editable or translatable else None,             'data-oe-company-name': res_company.name         }"/> - - -

se poi carico i componenti da aggiornare cosi: 

![image](https://user-images.githubusercontent.com/102078482/204398537-8a4dc956-0d9e-4a6c-bed1-09a8e1f91401.png)

Provo ad aggiornare manualmente l10n_it_fatturapa e ricevo questo errore: 

Modello non trovato: fatturapa.attachment

provo ad aggiornare l10n_it_fatturapa_out e ricevo questo errore:

Il campo `xml_divisa_value` non esiste

provo ad aggiornare l10n_it_fatturapa_in e ricevo questo errore:

Il campo `e_invoice_parsing_error` non esiste

provo ad aggiornare l10n_it_fatturapa_pec e ricevo: 

L'elemento '<page name="history">' non può esser localizzato nella vista genitore

Contesto errore:
Vista `fatturapa.attachment.out.form`

provo ad aggiornare l10n_it_sdi_channel   e ricevo come errore: 

Il campo `withholding_tax_in_print` non esiste

Provo ad aggiornare l10n_it_fiscal_document_type  e ricevo come errore: 

Modello non trovato: fatturapa.attachment

ho provato come suggerito di fare update all da terminale, ma passano 30 minuti e non succede niente.

Cosa potrei fare?

Grazie

**Comment by SirTakobi** [comment]
Ciao! Capisco che tu le abbia provate già tutte, ma ti do qualche consiglio:
> ValueError: Il campo withholding_tax_in_print non esiste

Per risolvere questo, senza scaricare nessun aggiornamento, potresti provare ad aggiornare il modulo **l10n_it_withholding_tax** perché lì è definito il campo: https://github.com/OCA/l10n-italy/blob/1aa46cf47daa6f2fb5e8f467b07eccda59e02ab8/l10n_it_withholding_tax/models/account.py#L396
In caso di errori, bisogna indagare da dove provengono.

Riguardo
> se scarico gli aggiornamenti dei componenti aggiuntivi, riavvio odoo senza eseguire l'aggiornamento

Quando cambi il codice dei moduli, come prima cosa devi aggiornarli; se non lo fai, è normale che ci siano errori.

Riguardo
> ho provato come suggerito di fare update all da terminale, ma passano 30 minuti e non succede niente.

concordo che un _update all_ normalmente risolve la maggior parte dei problemi.
Bisogna capire come mai dopo 30 minuti non succede nulla: il log cosa dice?
Se puoi, ti suggerisco di stoppare il processo principale in modo che non interferisca con l'aggiornamento che stai lanciando da terminale; quindi lanciare l'aggiornamento da terminale con le opzioni:

- `--update all`: per aggiornare tutti i moduli
- `--stop-after-init`: per spegnersi dopo che ha finito l'aggiornamento: magari ha finito di aggiornare ma senza questa opzione il processo rimane acceso e potresti pensare che non abbia ancora finito

In generale, quando ci sono errori del tipo _il campo XX non esiste_, ti consiglio di:

1. Cercare il modulo in cui è definito quel campo,
2. Verificare che nel tuo codice il campo sia definito in quel modulo, se non lo è allora dovresti scaricare il codice aggiornato
3. Aggiornare quel modulo

**Comment by wowstore87** [comment]
mi sono fatto aiutare da uno specialista, ha risolto lui per me.

grazie
