### ISSUE TITLE
id_paese is duplicated in id_fiscale field

### ISSUE THREAD

**Issue by patrickt-oforce** [OCA/l10n-italy#3083]
On e-Invoice export, if partner that receive the e-invoice isn't italian, its country is duplicated in id_fiscale field

## Module
l10n_it_fatturapa_out

## Describe the bug
When export e-invoice, for non italian partner country code is duplicated on id_fiscale field

## To Reproduce
**Affected versions**:
- [ ] 14.0

1. Export e-invoice for non italian partner
2. Show exported e-invoice

**Expected behavior**
id_paese must be present only once in id_fiscale

**Additional context**
PR for this issue, #3082

**Comment by TheMule71** [comment]
Per me è WAI. Vd. commenti nella PR.

**Comment by patrickt-oforce** [comment]
Chiudo in quanto non necessaria, avevo ricevuto una segnalazione errata riguardo la partita iva del cliente estero
