### ISSUE TITLE
[14.0] [RFC] - l10n_it_fatturapa_out - implementazione ScontoMaggiorazione in DatiGeneraliDocumento

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3088]
Ciao, vorremmo procedere ad implementare la funzionalità dello sconto documento in fatturapa_out ( tag commentato in https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_out/data/invoice_it_template.xml#L548 )

@OCA/local-italy-maintainers Ci sono impedimenti da tenere a mente o abbiamo il supporto per procedere? 

Grazie!

cc @elvise @GSLabIt

**Comment by eLBati** [comment]
Ciao @francesco-ooops , non mi risultano impedimenti su questo

**Comment by tafaRU** [comment]
@francesco-ooops questa issue ha senso ancora tenerla aperta?

**Comment by francesco-ooops** [comment]
Chiudiamo pure, se qualcuno ha input da aggiungere può sempre farlo
