### ISSUE TITLE
[16.0] l10n_it_account: i sottomenù di Intervali date non vengono mostrati

### ISSUE THREAD

**Issue by tafaRU** [OCA/l10n-italy#3090]
## Module
l10n_it_account

## Describe the bug
Provando 

## To Reproduce
**Affected versions**:
`16.0`:  https://github.com/OCA/l10n-italy/pull/3091

**Expected behavior**
Sotto il menù  Intervalli date dovrebbero essere presenti ulteriori sottomenù utili alla loro gestione
![image](https://user-images.githubusercontent.com/3512779/208087026-e4eae086-989c-4fa0-b029-0f4ac3ae4e72.png)

**Additional context**
I sottomenù che non vengono mostrati sono: https://github.com/OCA/l10n-italy/blob/ded6be38651e2a464c11e806253b3d9dbd5f0665/l10n_it_account/views/account_menuitem.xml#L15-L26
Questo si verifica a causa di https://github.com/odoo/odoo/issues/105609

**Comment by eLBati** [comment]
Da chiudere?
