### ISSUE TITLE
l10n_it_ddt - DdT "action_invoice_create" dovrebbe creare Fatture da SaleOrder.action_invoice_create se l'origine è un ordine di vendita

### ISSUE THREAD

**Issue by c-amara** [OCA/l10n-italy#3095]
**Is your feature request related to a problem?**
[action_invoice_create](https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_ddt/models/stock_picking_package_preparation.py#L416) della classe `StockPickingPackagePreparation` dovrebbe avere lo stesso comportamento di [action_invoice_create](https://github.com/odoo/odoo/blob/12.0/addons/sale/models/sale.py#L579) di `SaleOrder` se la consegna legata al DdT è stata creata da un ordine di vendita.
Fatturando un DdT con il pulsante "Crea Fattura da DdT", se nell'ordine di vendita sono stati inserite righe "servizi" queste non vengono riportate in fattura generando un totale fattura inferiore al preventivo di vendita. 

**Describe the solution you'd like**
Si dovrebbe avere invece lo stesso comportamento ottenuto dalla fatturazione dell'ordine di vendita con pulsante "Crea Fattura" da SaleOrder

**Comment by matteoopenf** [comment]
sulla 12.0?

**Comment by c-amara** [comment]
Si intendevo sulla 12.0... Ma anche sulle successive se il comportamento è lo stesso.

**Comment by matteoopenf** [comment]
> Si intendevo sulla 12.0... Ma anche sulle successive se il comportamento è lo stesso.

Sulle successive non è possibile il modulo su 14 cambia

**Comment by c-amara** [comment]
Ok

**Comment by matteoopenf** [comment]
credo che non sia un bug, ma sia voluto, tu fatturi il ddt

**Comment by matteoopenf** [comment]
puoi fare l'override per prendere le righe mancanti

**Comment by c-amara** [comment]
> credo che non sia un bug, ma sia voluto, tu fatturi il ddt

No ma infatti avevo selezionato "feature request" non bug. Però è anche vero che il ddt non include le righe servizi dell'ordine di vendita perché ovviamente non sono trasportabili. 
Ma alla fatturazione dei ddt devono essere inclusi in fattura

**Comment by tafaRU** [comment]
Il modulo `l10n_it_ddt` non è più supportato.
