### ISSUE TITLE
[14.0][l10n_it_fatturapa_out] problema currency  in caso di fattura con valuta diverso da euro

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3097]
## Module
l10n_it_fatturapa_out

## To Reproduce

- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/3739
- [ ]  16.0

1. Creare una fattura fornitore con reverserge e con registro con una valuta diversa da euro
![image](https://user-images.githubusercontent.com/43987335/209155051-05eb3883-fed6-405e-b3cf-5e5dd9c96519.png)

2. Validare la fattura 
3. andare nella fattura cliente e esportare l'xml
4. inviarlo allo SDI
5. si ottiene il seguente errore:

![image](https://user-images.githubusercontent.com/43987335/209155315-5ac13200-2bae-44a8-ad8f-a679cb793a1e.png)

Dopo varie prove, sul fatto che fallivano i test e vari ragionamenti ho scoperto testando il file del test che a sua volta esso e' sbagliato.
Riguardo gli errori del file 15 li metto di seguito
![image](https://github.com/OCA/l10n-italy/assets/43987335/4933b662-aa31-4e9a-bace-14e0af05e330)

![image](https://github.com/OCA/l10n-italy/assets/43987335/92d5557d-5f2d-40db-aef5-66840c4a4d7e)

Quindi c'e' un problema che a monte si testa un file sbagliato 

**Expected behavior**
una volta esportata la fattura e inviata venga inviata correttamente allo SDI senza errori

**Additional context**
CI siamo accorti dopo varie prove che il problema è causato da questi due fattori:
imponobileImporto quando viene usato all'interno dell'xml è già  convertito nella valuta che occorre e invece l'imposta no.
![image](https://user-images.githubusercontent.com/43987335/209171864-7f92d59f-883e-4f11-9f7c-61c0a4159db2.png)

anche qui oltre che sul modulo del reverse charge imponibile importo è già in valuta.
![image](https://user-images.githubusercontent.com/43987335/209172337-b48a5ca5-de1d-4717-b3c2-07e7db8fb67c.png)

Mi sembra strano anche a me che sià già convertito, ma fatte varie prove, togliendo il metodo che fa la conversione sostanzialmente  sono riuscito qui https://www.fatturacheck.it/ a farmela validare la fattura .

**Comment by matteoopenf** [comment]
tra poco integro con un paio di dettagli e aggiorno sopra

**Comment by TheMule71** [comment]
occhio che https://www.fatturacheck.it/ non credo faccia quei controlli SdI (quelli che generano errori semantici), fa solo controlli sintattici che noi già facciamo.

Sarebbe il caso di vedere l'XML generato, magari anonimizzato.

**Comment by matteoopenf** [comment]
> occhio che https://www.fatturacheck.it/ non credo faccia quei controlli SdI (quelli che generano errori semantici), fa solo controlli sintattici che noi già facciamo.
> 
> 
> 
> Sarebbe il caso di vedere l'XML generato, magari anonimizzato.

Come riprendo a lavoro lo anonimizzo e metto.
Ma prima di sistemarlo mi dava errore anche qua quindi non è che passa per via di un controllo semantico, quando i valori erano errati mi dava errore proprio su i due campi che ho corretto con la pr.

**Comment by matteoopenf** [comment]
altri come noi hanno questo problema?

**Comment by francesco-ooops** [comment]
@matteoopenf anche sulla 16?

**Comment by matteoopenf** [comment]
> @matteoopenf anche sulla 16?

presumo di si essendo che la 16 e' quasi identica alla 14 sotto questo punto di vista

**Comment by matteoopenf** [comment]
@TheMule71  dopo varie prove e giri ho capito dove era l'inghippo, tolto che il file del test 15 ha il tipo documento errato, ho trovato dove era l'inghippo per far funzionare i test
