### ISSUE TITLE
programma del forum community

### ISSUE THREAD

**Issue by OpenValueConsulting** [OCA/l10n-italy#3104]
mi scuso per aver utilizzato questo canale
mi indichereste il nome del programma del forum della community per installarlo ed iniziare a collaborare
graie

**Comment by matteoopenf** [comment]
le pr e il resto si fa tutto su github, spesso discussioni e altro su discord qui https://discord.gg/ArBN8tJB tolto che comunque tutto si dovrebbe discutere in una issue per tenere traccia di tutto

**Comment by tafaRU** [comment]
@OpenValueConsulting facci sapere se hai bisogno di ulteriori info, nel frattempo chiudo la tua issue.
