### ISSUE TITLE
Base Location Provinces Import uninstallable

### ISSUE THREAD

**Issue by ginomazzoni** [OCA/l10n-italy#311]
Io ho installato tutte le dipendenze necessarie, vedo la app ma senza il bottone per la installazione e cliccandoci sopra nelle informazioni tecniche mi dice uninstallable. Dove sbaglio? Grazie

**Comment by OpenCode** [comment]
Di quale versione stiamo parlando?

**Comment by ginomazzoni** [comment]
Odoo 10 ultima nightly builds. Grazie

**Comment by OpenCode** [comment]
Il modulo è settato come "Non installabile" perché non è ancora stato fatto il porting completo

**Comment by OpenCode** [comment]
Le PR inerenti l'import dei dati geonames sono state tutte chiuse. Se installi Odoo dai sorgenti troverai questi moduli abilitati. La versione nightly builds è sempre un po' più vecchia dei sorgenti.
