### ISSUE TITLE
Nei test, c'è un conflitto di sequenze fattura

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3113]
## Module
l10n_it_fatturapa_out_welfare

## Describe the bug
L'esecuzione dei test automatici restituisce errore, ad esempio https://github.com/OCA/l10n-italy/actions/runs/3821494241/jobs/6500697922#step:8:1654

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/3114
- [ ] `14.0`: n/a (il modulo non c'è)
- [ ] `16.0`: n/a (il modulo non c'è)

1. Eseguire i test automatici

**Expected behavior**
I test passano.

**Comment by eLBati** [comment]
Questa si può chiudere quindi?
