### ISSUE TITLE
[14.0] l10n_it_fatturapa_out_rc  - doppia sigla nazione in partita iva

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3136]
Creando un'autofattura esteran per un fornitore con PIVA con codice nazione valorizzato il codice nazione viene ripetuto due volte. 
Es. 
In res partenr il fornitroe è salvato con piva 
BE0477472701

nell'xml dell'auto fattura trovo 
BEBE0477472701 
la conseguenza è che mi viene generato un doppio contatto in Odoo

**Comment by TheMule71** [comment]
Nell'attuale 14 non dovrebbe esserci codice che concatena il country code alla piva.  In quale caso viene creato il partner? Quando reimporti l'XML che torna dallo SdI?

**Comment by TheMule71** [comment]
Come non detto:
https://github.com/OCA/l10n-italy/blob/c514a5c71c80ff37ee564437a71ea8aa350be99d/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py#L200-L203

qui andrebbe importata la vat così com'è, senza concatenare l'IdPaese, perché abbiamo visto che non sempre c'è quel prefisso e non sempre corrisponde al contry code.

**Comment by TheMule71** [comment]
@francescapenso 
hai modo di provare #3138?

**Comment by francescapenso** [comment]
Ma secondo me è un problema di paout è nell'autofattura che genero che trovo il doppio codice nazione BEBE per dire....ad ogni modo provo

**Comment by TheMule71** [comment]
Quello è l'unico punto nel codice in cui viene concatenato IdPaese con IdCodice, almeno che ho trovato (e va corretto comunque).

In out ho cercato e non l'ho trovato. Lo faceva in passato, sei sicura di avere l'ultima versione aggiornata di fatturapa_out?

**Comment by matteoopenf** [comment]
> Creando un'autofattura esteran per un fornitore con PIVA con codice nazione valorizzato il codice nazione viene ripetuto due volte. Es. In res partenr il fornitroe è salvato con piva BE0477472701
> 
> nell'xml dell'auto fattura trovo BEBE0477472701 la conseguenza è che mi viene generato un doppio contatto in Odoo

anche io avevo aperto una issue simile dipende dal fatto che qui https://github.com/OCA/l10n-italy/blob/29fd1c16555a66e2da88dc58ec1a4404d7269552/l10n_it_fatturapa_out/wizard/efattura.py#L116

si prende tutta la VAT senza escludere la sigla iniziale.
Quindi poi c'è il problema in fase di ricezione di trovare l'xml così

**Comment by francescapenso** [comment]
Chiudo visto che c'è la PR #3138

**Comment by robyf70** [comment]
@francescapenso Per le fatture in uscita l'XML su clienti esteri e ovviamente nella preview, riporta il doppio prefisso della nazione. La issue andrebbe riaperta

**Comment by robyf70** [comment]
Ho fatto la PR #3147 per risolvere il problema
