### ISSUE TITLE
Aggiungere un commento in fattura di cortesia

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3150]
**Is your feature request related to a problem?**
No.

**Describe the solution you'd like**
In una fattura, poter inserire un commento che venga riportato nella stampa PDF ma non nella fattura elettronica.
Il commento potrebbe anche essere definito nel partner e riportato nelle sue fatture.

**Describe alternatives you've considered**
https://github.com/OCA/account-invoice-reporting/pull/262

**Comment by TheMule71** [comment]
In realtà, anche visto il fatto che nella 16.0 il campo è diventato un HTML, si potrebbe valutare di introdurre un campo causale per l'XML, lasciando `narration` per le stampe. C'è da cambiare un po' di moduli nostri che usano `narration` (non dovrebbero essere tanti).

**Comment by SirTakobi** [comment]
> In realtà, anche visto il fatto che nella 16.0 il campo è diventato un HTML, si potrebbe valutare di introdurre un campo causale per l'XML, lasciando `narration` per le stampe. C'è da cambiare un po' di moduli nostri che usano `narration` (non dovrebbero essere tanti).

L'alternativa che ho già implementato:

-  aggiunge un nuovo campo solo per la stampa,
-  utilizza il campo esistente per stampe e XML (come viene già fatto)

Ho scelto questa implementazione perché da utente mi aspetterei che il commento sulla fattura venga anche riportato nel XML perché il file XML è 'una copia' della fattura che mando a SdI.
Se c'è qualcosa nella fattura che non viene messo nel XML mi aspetto ci sia scritto chiaramente che non finirà nel XML.
Detto ciò, io non sono utente di questi sviluppi (non li uso) quindi l'utente medio potrebbe aspettarsi qualcosa di diverso.

Se vuoi puoi provare a fare un'implementazione alternativa e vedere come verrebbe, poi si vedrà anche con il codice sottomano cosa risulta più usabile

**Comment by TheMule71** [comment]
Io parto dal presupposto che sarà impossibile riportare l'annotation nell'XML in quanto non è più un testo.  In questo momento `l10n_it_fatturapa_out` fa buon viso a cattivo gioco e "converte" l'HTML in testo a forza, ma di fatto questo comporta possibili problemi.  In pratica l'annotation non è più compatibile con l'XML per come è strutturato.

Inoltre usare l'annotation come causale era anche prima una mappatura non precisa al 100% (Odoo ci mette varie note). C'è un discreto grado di vaghezza nelle indicazioni su cosa mettere nell'elemento Causale per cui era abbastanza ragionevole copiarci il commento, ma non è escluso che potrebbe essere meglio avere un campo "Causale" nel model account.move, in modo che sia chiaro cosa finisce nell'XML (e dove).
