### ISSUE TITLE
Problems related to the module setting :  14.0/l10n_it_reverse_charge

### ISSUE THREAD

**Issue by tgd1973** [OCA/l10n-italy#3151]
Good morning. 
  I can not solve the problem of the initial setting of reverse charge! Consulting various tutorials, I assert that each one suggests a different model which in turn seems different from the Odoo 12 to 14 version and then also different over time, 2 years ago the setting was different now. I would be very happy to find a definitive guide for v14 (for v16 I think it doesn't exist yet).
 
  Can anyone tell why even if setting according to the tutorials and info also displayed on the module 14.0/l10n_it_reverse_charge , when I try to insert an invoice I get the following message:
"Please define a payment method on your payment."

![Invoicing-error](https://user-images.githubusercontent.com/15127860/214620797-bfbf9b82-3a72-41e1-a109-cdd25f3db900.png)

Thanks for any response!

**Comment by SirTakobi** [comment]
I just tried following the README for version `14.0` and got stuck :sweat:.
The screenshots in the English side are still in italian, the accounts used in the taxes sometimes do not exist, the journal Autofatture is shown in the RC Type but has not been defined before.

I agree that the documentation should be improved.

**Comment by tgd1973** [comment]
However, I am stuck at this point, and I hope that someone will intervening to explain the reason for the message:

`"Please define a payment method on your payment."`

 ... I don't know what (the message) is due to, because the system does not go ahead for the validation of the invoice as it does with those simple ...

**Comment by sergiocorato** [comment]
> However, I am stuck at this point, and I hope that someone will intervening to explain the reason for the message:
> 
> `"Please define a payment method on your payment."`
> 
> ... I don't know what (the message) is due to, because the system does not go ahead for the validation of the invoice as it does with those simple ...

Hi @tgd1973 , this warning is resolved setting a payment method in the payment journal used in reverse charge configuration.

**Comment by tgd1973** [comment]
> > However, I am stuck at this point, and I hope that someone will intervening to explain the reason for the message:
> > `"Please define a payment method on your payment."`
> > ... I don't know what (the message) is due to, because the system does not go ahead for the validation of the invoice as it does with those simple ...
> 
> Hi @ , this warning is resolved setting a payment method in the payment journal used in reverse charge configuration.

Good morning and sorry for my request, but it could be more detailed in the answer (since the documentation is out-dated) can you say exactly or maybe put a screenshot from where (which menu) you have to intervene to correct? I ask because this thing is not spelled out anywhere in any explanatory document.
Thank you.

**Comment by sergiocorato** [comment]
This request is not related to this module, as it is a generic configuration.
See screenshot below:

![Screenshot(201)](https://user-images.githubusercontent.com/7657311/215427887-25c112c1-ce1d-43d8-8ebd-0733c7807c1d.png)

![Screenshot(200)](https://user-images.githubusercontent.com/7657311/215427939-e2627e12-2b9d-4cff-812a-3524e792c02c.png)
