### ISSUE TITLE
Modulo importazione cespiti

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3153]
**Is your feature request related to a problem?**
Modulo per importazione cespiti

**Describe the solution you'd like**
il modulo permetterà l'importazione dei cespiti

- [x] 12.0 https://github.com/OCA/l10n-italy/pull/3155
- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/3261
- [ ] 16.0: 

**Additional context**
Add any other context about the feature request here.

**Comment by francesco-ooops** [comment]
aggiunta a #2967 , chiudo
