### ISSUE TITLE
Il modello INTRA 2-bis stampa valori errati

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3157]
## Module
l10n_it_intrastat_statement

## Describe the bug

Il sitema elabora i dati  delle dichiarazioni intrastat consentendo nella sezione Contabilità/ Dichiarazioni intrastat la stampa dei modelli in formato ministeriale attraverso la funzione "Stampa".

Il sistema consente la correzione manuale dei dati sia accedendo alla sezione intrastat della fattura riportandola in bozza, sia alle "righe intrastat", sia direttamente nelle righe di dichiarazione.

Una volta elaborata la dichiarazione e fatte delle correzioni (ad esempio la modifica del paese di origine per una riga) il sistema, pur tenendo conto della correzione nell'elaborazione del file di trasmissione, non la riproduce nella stampa pdf dei modelli ministeriali.

**Expected behavior**
Una volta elaborata la dichiarazione e fatte delle correzioni (ad esempio la modifica del paese di origine per una riga) il sistema, tenendo conto della correzione nell'elaborazione del file di trasmissione, la riproduce la correzione nella stampa pdf dei modelli ministeriali.

## To Reproduce
- [x] 12.0: https://github.com/OCA/l10n-italy/pull/3156
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3159
- [ ] 16.0 #4320

**Comment by SirAionTech** [comment]
Direi https://github.com/OCA/l10n-italy/labels/good%20first%20issue
