### ISSUE TITLE
l10n_it_withholding_tax errore su template QWeb ordine di vendita (account.document_tax_totals)

### ISSUE THREAD

**Issue by webcircles-davide** [OCA/l10n-italy#3160]
## Module
l10n_it_withholding_tax

## Describe the bug
Installando il modulo viene generato un errore all'apertura dell'anteprima cliente per gli ordini di vendita

## To Reproduce
**Affected versions**: 16.0

1. installare il modulo
2. aprire l'anteprima cliente di un ordine di vendita
[errore.pdf](https://github.com/OCA/l10n-italy/files/10569815/errore.pdf)

**Comment by SirTakobi** [comment]
Grazie della segnalazione!
Riprodotto in runboat

**Comment by andreampiovesana** [comment]
qualcuno ha verificato?
la correzione è urgente ...

**Comment by tafaRU** [comment]
@andreampiovesana @ser-tec potete verificare se #3221 risolve?
