### ISSUE TITLE
[14.0] [l10n_it_fatturapa_in] assegnazione partner fattura elettronica

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3163]
## Module
l10n_it_fatturapa_in

## Describe the bug
Se un contatto, ha anche dei sotto contatti, in fase di importazione della fattura elettronica ottengo
![image](https://user-images.githubusercontent.com/43987335/216573388-c54d823b-bfc9-48ae-97d6-0b883fd32bbe.png)

## To Reproduce
**Affected versions**:

- [ ] 14.0
- [ ] 16.0 ?

1. Creare un contatto  assegnare ad esso una partita iva italiana
2. Creare 1 o più sotto contatti
3. ricevere una fattura elettronica e si ottiene il massaggio dello screen sopra

**Expected behavior**
La fattura viene associata al contatto padre e non esce l'errore.

**Additional context**

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Ho provato in `14.0` e non ottengo il problema.
I contatti sono ![image](https://github.com/user-attachments/assets/556d24c8-0125-4006-b8c9-3f67f33094c9)
e importo la fattura https://github.com/OCA/l10n-italy/blob/1dfb4ee2d11598669573b5f3c38d0efd31943f7d/l10n_it_fatturapa_in/tests/data/IT01234567890_FPR03.xml ma non ottengo nessun errore durante lìimportazione: 
![image](https://github.com/user-attachments/assets/23d3b516-245c-4d42-9333-df7c2037216b)

Ho fatto le prove in http://oca-l10n-italy-14-0-e86cae72893e.runboat.odoo-community.org/web#id=1&action=650&model=fatturapa.attachment.in&view_type=form&cids=1&menu_id=134

Forse il problema si è risolto nel frattempo, oppure mi manca qualche passaggio? Potresti verificare?

**Comment by TheMule71** [comment]
Abbiamo provato a riprodurre il problema, non sembra ci sia - oppure è scatenato da condizioni particolari.

**Comment by matteoopenf** [comment]
> Abbiamo provato a riprodurre il problema, non sembra ci sia - oppure è scatenato da condizioni particolari.

ok
