### ISSUE TITLE
Problemi di accesso al menu Fatturazione / Clienti / "File e-fattura esportati"

### ISSUE THREAD

**Issue by mktsrl** [OCA/l10n-italy#3164]
## Module
base

## Describe the bug
Con l'ultimo aggiornamento del repository i nostri utenti responsabili della contabilità non riescono più ad accedere all'area delle fatture elettroniche esportate: si tratta di utenti interni (non admin) responsabili/amministratori/manager di tutte le aree attivate.
Dagli approfondimenti fatti risulta che il problema non è dovuto a incongruenze sui permessi/autorizzazione, ma bensi ad un controllo localizzato nel modulo modulo "base" e in particolare nel sorgente "base/model/ir_attachment.py".
Nel sorgente è presente il controllo
 ```
 if not self.env.is_system() and (res_field or (not res_id and create_uid != self.env.uid)):
                    raise AccessError(_("Sorry, you are not allowed to access this document."))
```
che in sostanza verifica che i campi res_field e res_id del model ir_attachment (che supporta la memorizzazione dei file delle fatture elettroniche) non sono compilati o non contengono informazioni coerenti.
Ipotizziamo che il wizard del modulo l10n_it_fatturepa_out che salva il file XML della fattura elettronica non valorizzi il campo "res_id" ed infatti controllando a database tale campo risulta a NULL.

> Riferimento al post che ha generato questa issue: https://www.odoo-italia.org/forum/forum-1/question/autorizzazioni-file-e-fattura-in-ingresso-3526

## To Reproduce
**14.0**:

1. Accedere all'area Fatturazione con un utente che abbia permessi completi di visualizzazione della contabilità, ma che non sia un Admin  (user interno con "diritti di accesso" e non "impostazioni")
2. Cliccare sul menu Fatturazione /clienti / File e-fatture esportate
3. compare il pop-up: "Nessuna autorizzazione per accedere al documento"

**Expected behavior**
Apertura della lista delle fatture esportate

**Additional context**
Ubuntu 20.4, python 3.8, Repository OCA/ODOO aggiornati all'ultima versione il 01/02/23

**Comment by matteoopenf** [comment]
mi sembra che si ricolleghi a un problema già visto su discord, dovuto a un commit di Odoo

**Comment by matteoopenf** [comment]
Segnatamente credo che il tuo problema sia simile a quanto descritto qua https://discord.com/channels/753902328494424064/806815905006223411/1069654826088140850

**Comment by mktsrl** [comment]
Giusto, il problema è mooooolto simile.
E' possibile sanare il pregresso con una UPDATE ma rimane che deve essere fatturapa_out ad inserire correttamente i dati dell'attachment compreso il campo  ir_attachment.res_id

**Comment by matteoopenf** [comment]
> Giusto, il problema è mooooolto simile. E' possibile sanare il pregresso con una UPDATE ma rimane che deve essere fatturapa_out ad inserire correttamente i dati dell'attachment compreso il campo ir_attachment.res_id

che ne dici di una pr?

**Comment by mktsrl** [comment]
Aggiungo che fatturapa_in compila correttamente sia il campo **res_model** che **res_id** (entrambi a NULL sulle e-fattura esportate).

**Comment by mktsrl** [comment]
Matteo,
non ci sentiamo pronti per una PR su **fatturapa_out** in quanto è un modulo piuttosto complesso su cui non abbiamo abbastanza esperienza. A mio avviso sarebbe preferibile che la PR venisse predisposta da chi ci ha già lavorato e sa se esistono altri pezzi di codice che trattano gli attachments.
Per contribuire ti risporto qui di seguito la patch che abbiamo predisposto per i nostri clienti facendo l'override del metodo "saveAttachment" del sorgente  "l10n_it_fatturapa_out > wizard > **wizard_export_fatturapa.py**"

**metodo originale:**
 
def saveAttachment(self, fatturapa, number):
        attach_obj = self.env["fatturapa.attachment.out"]
        vat = attach_obj.get_file_vat()
 
        attach_str = fatturapa.to_xml(self.env)
        attach_vals = {
            "name": "{}_{}.xml".format(vat, number),
            "datas": base64.encodebytes(attach_str),
        }
        return attach_obj.create(attach_vals)

**metodo modificato:**
 
class WizardExportFatturapa(models.TransientModel):
    _inherit = "wizard.export.fatturapa"
 
    def saveAttachment(self, fatturapa, number):
        attach_obj = self.env["fatturapa.attachment.out"]
        vat = attach_obj.get_file_vat()
        attach_str = fatturapa.to_xml(self.env)
        attach_vals = {
            "name": "{}_{}.xml".format(vat, number),
            "datas": base64.encodebytes(attach_str),
            "res_model": "fatturapa.attachment.out",              #  <<<----  AGGIUNTA
        }
        ret = attach_obj.create(attach_vals)                          #  <<<----  AGGIUNTA
        ret.ir_attachment_id.res_id = ret.id                           #  <<<----  AGGIUNTA
        return ret

**Comment by tafaRU** [comment]
Chiudo a favore di https://github.com/OCA/l10n-italy/issues/3336
