### ISSUE TITLE
16. Errore nella stampa ...di un ordine di vendita

### ISSUE THREAD

**Issue by OpenValueConsulting** [OCA/l10n-italy#3172]
<KeyError: 'o'
Template: account.document_tax_totals
Path: /t/t[2]/tr[1]/td[2]/span
Node: <span t-field="o.withholding_tax_amount"/>

disinstallando il modulo del withholding tax funziona.
grazie
Claudio Candito

**Comment by OpenValueConsulting** [comment]
KeyError: 'o'
Template: account.document_tax_totals
Path: /t/t[2]/tr[1]/td[2]/span
Node: <span t-field="o.withholding_tax_amount"/>

**Comment by OpenValueConsulting** [comment]
KeyError: 'o'
Template: account.document_tax_totals
Path: /t/t[2]/tr[1]/td[2]/span
Node: 
<span t-field="o.withholding_tax_amount"/>

**Comment by OpenValueConsulting** [comment]
Node: <span t-field="o.withholding_tax_amount"/>

**Comment by francesco-ooops** [comment]
@OpenValueConsulting l'errore è riproducibile sul runboat l10n-italy?

**Comment by tafaRU** [comment]
Chiuso con https://github.com/OCA/l10n-italy/pull/3221
