### ISSUE TITLE
[16.0] account_vat_period_end_statement form non formatta bene i conti

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/l10n-italy#3192]
## Module
account_vat_period_end_statement

## Describe the bug
Formattazione errata della form

## To Reproduce
16

1. aprire liquidazione iva e il foglio conti
2. righe conti di credito e righe conti di debito sono visualizzati male

**Expected behavior**
Corretta visualizzazione

**Additional context**
esempio di errata visualizzazione
![immagine](https://user-images.githubusercontent.com/13952131/221543880-23197642-d7a4-4509-b79f-015d23e7e445.png)

**Comment by andreampiovesana** [comment]
dovrebbe essere:
![image](https://user-images.githubusercontent.com/13952131/221630210-02e7eb7a-2f81-4f14-a0a1-b6a07c1f6094.png)

**Comment by tafaRU** [comment]
Chiuso con https://github.com/OCA/l10n-italy/pull/3380
