### ISSUE TITLE
[14.0] l10n_it_declaration_of_intent fatture fornitore con superamento plafond errore salvataggio

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3193]
Caso: Dichiarazione di intento emessa dall'azienda verso un fornitore.
La fattura del fornitore tutta in dichiarazione d'intento super il plafond.
Il fornitore dovrà emettere una nota di debito per l'iva eccedente la dichiarazione

Comportamento riscontrato:
quando si conferma la fattura compare un errore utente che avvisa lo sforamento di Plafon e non permette di proseguir

Comportamento attesa:
warning di avviso ma non impedimento di salvare la fattura. 
Emettere fatture corrette con dichiarazione di intento è onere del fornitore 

- [ ] 14.0
- [ ] 16.0 ?

**Comment by SirAionTech** [comment]
@francescapenso potresti mettere un titolo più specifico?
