### ISSUE TITLE
SEPA - SCT ed SDD

### ISSUE THREAD

**Issue by caiuka** [OCA/l10n-italy#3203]
**Is your feature request related to a problem?**
No

**Describe the solution you'd like**
Implementare la gestione dei pagamenti SEPA utilizzando i moduli di bank-payment [account_banking_sepa_credit_transfer](https://github.com/OCA/bank-payment/tree/14.0/account_banking_sepa_credit_transfer) ed [account_banking_sepa_direct_debit](https://github.com/OCA/bank-payment/tree/14.0/account_banking_sepa_direct_debit), accompagnati dalla libreria [Fintech](https://www.joonis.de/en/fintech/).

Questo permette una più agevole e veloce manutenzione e migrazione del modulo.

**Describe alternatives you've considered**
In alternativa bisognerebbe migrare il modulo [l10n_it_sepa_bonifici](https://github.com/OCA/l10n-italy/tree/8.0/l10n_it_sepa_bonifici), fermo alla v8 proprio per la difficoltà di implementare l'algoritmo CBI.
La documentazione è di difficile reperimento, ed è lunga e complessa.

Inoltre, sarebbe comunque da utilizzare come base i moduli bank-payment, per una maggiore uniformità e coerenza di utilizzo.

**Additional context**
Add any other context about the feature request here.

Possibile implementazione:

- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/4367
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/4189

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers apriremo una PR il prima possibile per questo, utilizzare la libreria indicata vi sembra una soluzione adeguata?

**Comment by dcorio** [comment]
@francesco-ooops più per diletto che esigenza immediata, avevamo fatto una prova con quella libreria per far uscire degli XML SEPA compatibili con le banche italiane direttamente dai moduli standard di Odoo e siamo riusciti ad importarli sull'homebanking

**Comment by Lazza** [comment]
> You may not use this Software in a way other than allowed in this license. You may not:
> 
> - modify or adapt the Software or merge it into another program,
> - reverse engineer, disassemble, decompile or make any attempt to discover the source code of the Software,
> - sublicense, rent, lease or lend any portion of the Software,
> - publish or distribute the associated license keycode.

**Comment by dcorio** [comment]
Ciao, questa issue la consideriamo ancora buona?
E' un'esigenza sempre più sentita e il 19 Novembre ci sarà il roll-out delle nuove specifiche CBI.

Vedi: https://discord.com/channels/753902328494424064/753902328494424070/1163408801001639946

**Comment by francesco-ooops** [comment]
Sì credo anche io che serva uno sforzo di odoo Italia per sviluppare e mantenere un modulo con questa finalità
