### ISSUE TITLE
[12.0][14.0][assets_management] report previsionale e prorata

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#3205]
Ciao,
vedo che nel codice del report viene forzato il prorata:
https://github.com/OCA/l10n-italy/blob/14.0/assets_management/report/asset_previsional.py#L738

Non dovrebbe essere forzato solo nel caso in cui è effettivamente da applicare?

**Comment by dcorio** [comment]
Aggiungo che alcuni contabili mi dicono che è corretto usare sempre il prorata per il previsionale e altro mi dicono di no...

**Comment by silverf0x0** [comment]
Nella pratica, credo che solo coloro che effettuano solo operazioni esenti
IVA rientrino nella casistica in cui non andrebbe applicato.

Il giorno lun 13 mar 2023 alle ore 09:52 Davide Corio <
***@***.***> ha scritto:
