### ISSUE TITLE
Stampa registro IVA tagliata

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3217]
## Module
l10n_it_account.

## Describe the bug
Il periodo di stampa non risulta tagliato: ![image](https://user-images.githubusercontent.com/101628000/225881607-913615f5-b92d-440a-a942-506874af245b.png)

## To Reproduce
**Affected versions**:
- [x] `12.0`: no: ![image](https://user-images.githubusercontent.com/101628000/225881320-11ab7222-241a-4bdb-a2fd-d01e8b58c0f1.png)
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/3218
- [x] `16.0`: non verificata

1. Modificare l'azienda impostando il nome: "Your Company longer name and much much much longer"
2. Stampare il registro IVA

**Expected behavior**
Il periodo di stampa non risulta tagliato

**Additional context**
Problema sollevato in Discord  [^1].
Ho fatto qualche ricerca e il problema sembra essere noto per `wkhtmltopdf` [^2].

[^1]: Il messaggio https://discord.com/channels/753902328494424064/806815905006223411/1085503391129669662 in breve riporta la stampa problematica [Registro_IVA_fatture2.pdf](https://github.com/OCA/l10n-italy/files/11000496/Registro_IVA_fatture2.pdf)
[^2]: https://stackoverflow.com/a/11517290/18559110

**Comment by SirTakobi** [comment]
> Non si sa però perchè sulla 12 non si presenta?

No

**Comment by francesco-ooops** [comment]
@SirAionTech sapresti confermarmi se è presente anche sulla 16?

**Comment by SirAionTech** [comment]
> @SirAionTech sapresti confermarmi se è presente anche sulla 16?

Non riproduco l'errore nel runboat della `16.0`: 
![image](https://github.com/OCA/l10n-italy/assets/143788994/5237cd40-1b07-4001-85c0-85ee444ea245)
quindi direi che si può chiudere
