### ISSUE TITLE
fatturapa_out "N. max fatture nell'XML"

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3223]
Se si setta il paramentro "N. max fatture nell'XML" con un valore diverso da 0 (es. 1) fa in ogni caso un file xml unico con tutte le fatture 

- [ ] 14.0
- [ ] 16.0

**Comment by SirAionTech** [comment]
Duplicata di https://github.com/OCA/l10n-italy/issues/2544.

**Comment by francesco-ooops** [comment]
Chiudo dunque
