### ISSUE TITLE
[16.0][account_vat_period_end_statement] nel report allineare gli importi a destra per migliore visualizzazione

### ISSUE THREAD

**Issue by andreampiovesana** [OCA/l10n-italy#3232]
## Module
account_vat_period_end_statement

## Describe the bug
miglioramento grafico - importi allineati a dx

## To Reproduce

- [ ] 14.0 sì
- [x] 16.0 #3233 

![immagine](https://user-images.githubusercontent.com/13952131/227476787-16a00765-0bdf-4051-b0a9-3809afdec95e.png)

**Comment by tafaRU** [comment]
@andreampiovesana puoi verificare se si verifica anche su `12.0` e `14.0`?

**Comment by andreampiovesana** [comment]
nella 14 gli importi sono corretti, le stringhe sono allineate a dx
