### ISSUE TITLE
[BUG] l10n_it_delivery_note - create Delivery Note Types for all companies

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3257]
## Describe the bug
Come si vede dal runboat l10n-italy, in contesto multicompany l'azienda "My Company (Chicago)" non ha i DN types creati automaticamente, il che costringe la creazione manuale di questi record e delle relative sequenze

![image](https://user-images.githubusercontent.com/55489873/230147048-0d414ac6-0e28-4713-bcdc-11e3edff44e7.png)

**Affected versions**:

- [ ] 12.0 
- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/3308
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/3664

**Expected behavior**

All'installazione del modulo e alla creazione di nuove company, dovrebbero venir create sequenze per ogni company con prefissi progressivi (eg: DIN/C2/ per azienda con ID = 2, DIN/C3/ per azienda con ID = 3) e relativi tipi di ddt per ogni company

**Comment by SirAionTech** [comment]
Ricordavo di averne già parlato ma non trovavo dove, ora ho trovato che se ne parlò anche nei commenti da https://github.com/OCA/l10n-italy/pull/3308#issuecomment-1554753093
