### ISSUE TITLE
16.0 l10n_it_withholding_tax - Errata etichetta

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#3263]
## Describe the bug
L'etichetta relativa alla registrazione della ritenuta è errata.
Attualmente scrive **Pagato il dd/mm/yyyy**, dove in realtà non è pagata ma solo registrata

## To Reproduce

1. Creo la ritenuta d'acconto
2. Imposto il'informazione fiscale sul partner
3. Creo una fattura fornitore
4. La valido
5. La pago

![image](https://user-images.githubusercontent.com/25057933/230583530-8ddb9a87-f68f-496a-a0a8-2ef344c02e9f.png)

**Affected versions**:
16.0

**Expected behavior**
Dovrebbe usare l'etichetta **RdA registrata il dd/mm/yyyy** come succede sulla 14.0

![image](https://user-images.githubusercontent.com/25057933/230583157-8bdc15f2-9251-4e68-b165-daf2cb1778f3.png)

**Comment by primes2h** [comment]
@marcelofrare non dovrebbe essere un problema di stringa, ma di riga xml che non viene ereditata correttamente. 
A differenza della 14.0, nella 16.0 la classe `o_field_widget` compare due volte [qui](https://github.com/odoo/odoo/blob/b7382925b1ac37ff1e00eaa472ea30cea20f61d0/addons/account/static/src/xml/legacy_account_payment.xml#L41) e [qui](https://github.com/odoo/odoo/blob/b7382925b1ac37ff1e00eaa472ea30cea20f61d0/addons/account/static/src/xml/legacy_account_payment.xml#L44).

Prova a vedere se #3265 risolve.

**Comment by primes2h** [comment]
Tra l'altro vedo che il sistema di inherit utilizzato nella 14.0 adesso è superato.
https://www.odoo.com/documentation/16.0/developer/reference/frontend/qweb.html#old-inheritance-mechanism-deprecated.

**Comment by marcelofrare** [comment]
grazie @primes2h. Ho provato su runboat della #3265 ma il risultato non cambia:

BILL/2023/04/0003

![immagine](https://user-images.githubusercontent.com/25057933/230707945-368e4a1a-53c8-4c20-9b91-ba706320bed2.png)

**Comment by andreampiovesana** [comment]
news?

**Comment by primes2h** [comment]
> grazie @primes2h. Ho provato su runboat della #3265 ma il risultato non cambia:
> 
> BILL/2023/04/0003
> 
> ![immagine](https://user-images.githubusercontent.com/25057933/230707945-368e4a1a-53c8-4c20-9b91-ba706320bed2.png)

Il problema qui era più complesso di quello che sembrava.
Oltre al diverso meccanismo di inherit e altre modifiche dovute al passaggio a OWL, nella 16.0 sono presenti anche cambiamenti sostanziali nel core.

@marcelofrare @andreampiovesana con le ultime correzioni viste insieme a @TheMule71 dovrebbe funzionare.
