### ISSUE TITLE
[16.0] [14.0] [l10n_it_fatturapa_out] - Esportazione fattura elettronica senza accesso alle impostazioni

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3267]
## Module
l10n_it_fatturapa_out

## Describe the bug
Per un utente senza accesso alle impostazioni non è impossibile esportare la fattura elettronica

## To Reproduce
**Affected versions**:
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3317 --> https://github.com/OCA/l10n-italy/pull/3335
- [x] 16.0: https://github.com/OCA/l10n-italy/pull/3266

## To Reproduce

1. configurare un utente con nessun gruppo "impostazioni" 
2. provare ad esportare una fattura elettronica
3. esce messaggio di errore --> "impossibile accedere a ir.actions.actions"

**Expected behavior**
Stampare fattura elettronica

**Comment by TheMule71** [comment]
Vd anche https://github.com/OCA/l10n-italy/pull/3335
