### ISSUE TITLE
[12] Problema con imponibile negativo a causa contributo statale

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#3268]
## Module
l10n_it_fatturapa_in (suppongo)

## Describe the bug
fattura  tiscali
- imponibile                                59,90
- iva                                              13,18  
- contributo statale                   -61,00
- imponibile calcolato               -  1,10
- totale                                          12,08

non me la valida

errore L'imponibile (-1.1) non corrisponde con l'imponibile della fattura elettronica (-1.1).

## To Reproduce
**Affected versions**:

- [x] 12.0 l10n_it_fatturapa_in 12.0.3.1.5 (risolta per termine supporto)
- [ ] 14.0 ?
- [ ] 16.0 ?

1. ricevo la fattura 
2. importo la fattura
3. in fase di validazione mi da l'errore sopra riportato, non avvetta un valore negativo per l'imponibile, credo.
4. forzando la validazione  nel contibuto statale non identifica la tassazione che dovrebbe essere esente iva art.15

**Expected behavior**
Validazione fattura con registrazione di un credito pari a €.1,1

**Additional context**
debian 10, python 3.7

prima di aprire la segnalazione ho discusso il problema sul forum di odoo italia con Sergio Corato
https://www.odoo-italia.org/forum/forum-1/question/12-fattura-adsl-con-contributo-statale-non-accettata-3599

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Puoi allegare un file XML con cui riprodurre l'errore?
Vedo che l'hai già messo in https://www.odoo-italia.org/forum/forum-1/question/12-fattura-adsl-con-contributo-statale-non-accettata-3599 ma la formattazione lì è terribile
