### ISSUE TITLE
Utilizzo Indirizzo di Fatturazione nell'inversione contabile o nel Prestatore

### ISSUE THREAD

**Issue by maurobraggio** [OCA/l10n-italy#3273]
## Module
l10n_it_fatturapa_out

## Describe the bug
Nell'esportazione XML se si utilizza un indirizzo di fatturazione associato al Prestatore, questo non viene considerato 

## To Reproduce
**Affected versions**:
 14.0
E' errato anche nell'inversione contabile ( integrativa iva)

1. Creare un fattura con una company con indirizzo di fatturazione diverso dal principale
2. Esportare la fattura elettronica

**Expected behavior**
Il file xml dovrebbe utilizzare l'indirizzo di fatturazione, qualora venisse selezionato

**Comment by maurobraggio** [comment]
@francesco-ooops ci sono problemi con la fix?

**Comment by francesco-ooops** [comment]
@maurobraggio non saprei, se la issue è ancora valida riesci a riprodurre l'errore su runbot e magari allegare un video del comportamento corrent rispetto al comportamento atteso?

**Comment by SirAionTech** [comment]
@maurobraggio grazie della segnalazione!

> @maurobraggio non saprei, se la issue è ancora valida riesci a riprodurre l'errore su runbot e magari allegare un video del comportamento corrent rispetto al comportamento atteso?

Ho provato in `14.0` e con una company definita così 
![image](https://github.com/OCA/l10n-italy/assets/143788994/b4f07c50-dec9-496a-b659-6e6e0cd38ff1), la fattura elettronica esportata è 
![image](https://github.com/OCA/l10n-italy/assets/143788994/a819c9aa-a189-4f4c-a128-c55cba20c9be) (http://oca-l10n-italy-14-0-873d0cdbd170.runboat.odoo-community.org/web#id=2&active_id=4&model=fatturapa.attachment.out&view_type=form&cids=&menu_id=134)
quindi ho riprodotto il comportamento descritto.

**Comment by SirAionTech** [comment]
Non saprei però dire se è un problema o meno, per questo ci vuole qualcuno di più funzionale: @francesco-ooops tu cosa ne dici?
C'è anche già una PR per correggere

**Comment by francesco-ooops** [comment]
@SirAionTech cerco di fare una review con @stefano-ooops al più presto

**Comment by SirAionTech** [comment]
> @SirAionTech cerco di fare una review con @stefano-ooops al più presto

@francesco-ooops giusto per info, nel frattempo la fix https://github.com/OCA/l10n-italy/pull/3275 è marcita.

@maurobraggio come mai hai chiuso la issue?
