### ISSUE TITLE
[14.0][l10n_it_fatturapa_in] Importo amount tax negativo in fatturapa_in

### ISSUE THREAD

**Issue by odooNextev** [OCA/l10n-italy#3274]
Nell'importazione di una reso con importi negativi, viene modificato il price_unit da negativo in positivo, ma le tasse rimangono comunque di importo negativo. Amount total è quindi di importo errato.

![image](https://user-images.githubusercontent.com/93990941/231990769-745fcc9b-427c-4fb6-b75b-b8a90bb24c7f.png)

**Comment by odooNextev** [comment]
https://github.com/OCA/l10n-italy/pull/3269
Forse è questo il motivo per cui falliscono i test in questa pr

**Comment by SirTakobi** [comment]
La versione nel titolo della issue dovrebbe essere 14.0?

**Comment by odooNextev** [comment]
Importando il file che va in errore nei test della pr il totale riportato è corretto, mentre nei test ritorna 15.6
![image](https://user-images.githubusercontent.com/93990941/232001225-142693de-f62f-4c56-875c-3384781948fc.png)

**Comment by francesco-ooops** [comment]
@odooNextev dunque questa sarebbe risolta da https://github.com/OCA/account-invoicing/pull/1442 ?

**Comment by SirAionTech** [comment]
@odooNextev questa si può chiudere?
