### ISSUE TITLE
[16.0][BUG][l10n_it_delivery_note] Migrazione dati l10n_it_ddt

### ISSUE THREAD

**Issue by dariodelzozzo** [OCA/l10n-italy#3285]
## Module
l10n_it_delivery_note

## Describe the bug
In Odoo 16.0 ho lanciato il comando di migrazione dati come riportato nelle istruzioni:
[https://github.com/OCA/l10n-italy/tree/16.0/l10n_it_delivery_note#migrazione-dei-dati-da-l10n_it_ddt](url)

Ho provato i suggerimenti di questa Issue:
[https://github.com/OCA/l10n-italy/issues/2395](url)

Ma ottengo comunque l'errore:

> Unknown command 'migratel10nitddt'

Ho provato ad eseguire ./odoo-bin help ma tra i vari comandi non è presente `migratel10nitddt`.

## To Reproduce
**Affected versions**: Odoo 16.0

- [ ] https://github.com/OCA/l10n-italy/pull/3824

**Comment by TheMule71** [comment]
Mi sa che lo devi eseguire nella 14.
Ogni volta che si fa una migrazione, li script delle migrazioni precedenti vengono cancellati.

**Comment by dariodelzozzo** [comment]
> Mi sa che lo devi eseguire nella 14. Ogni volta che si fa una migrazione, li script delle migrazioni precedenti vengono cancellati.

Resta comunque il problema che si riceve Unknown Command (anche se poi i dati non sono corretti oppure ritornano un errore).
Sembra proprio non funzionare il comando `migratel10nitddt` sulla 16.0

**Comment by francesco-ooops** [comment]
@dariodelzozzo secondo te c'è qualcosa da fixare o si può chiudere?
