### ISSUE TITLE
Pagamenti in sospeso per fatture in inversione contabile

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3286]
## Module
l10n_it_reverse_charge.

## Describe the bug
Dopo aver validato una fattura fornitore in reverse charge, ci sono pagamenti in sospeso.
Nell'esempio riportato qui sotto, sono i due movimenti sui conti Outstanding Payments/Receipts.

## To Reproduce
**Affected versions**:
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/3287
- [x] `16.0`: https://github.com/OCA/l10n-italy/pull/3566

1. Configurare il modulo l10n_it_reverse_charge
2. Creare una fattura con reverse charge e confermarla:
    La fattura confermata è **BILL/2023/04/0001**, i movimenti contabili creati sono: 
![image](https://user-images.githubusercontent.com/101628000/233974024-f90ea5ed-8002-4ca7-b110-3488f4539b32.png)

**Expected behavior**
Non ci devono essere pagamenti in sospeso (outstanding payments e outstanding receipts) dopo aver confermato la fattura in reverse charge.

**Additional context**
Il comportamento attuale crea un nuovo pagamento ogni volta che c'è da riconciliare una delle registrazioni generate, questo comportamento è stato introdotto dalla migrazione del modulo in https://github.com/OCA/l10n-italy/commit/5e65a06924d1dbb41ac172ae12d9d2283b9553ad.
Nella PR di migrazione https://github.com/OCA/l10n-italy/pull/2310 non ho trovato motivazioni per questo cambio di comportamento, può essere che sia passato inosservato.

Prima della migrazione, le registrazioni venivano riconciliate tra loro con l'ausilio di una registrazione aggiuntiva _pagamento_.

**Comment by TheMule71** [comment]
Riapro, da portare dopo migrazione, perché il test del commit 
https://github.com/OCA/l10n-italy/pull/3300/commits/f309def6744854bb263da29fbb79b5a067e9dff3
sono rossi.

**Comment by SirTakobi** [comment]
> Riapro, da portare dopo migrazione, perché il test del commit [f309def](https://github.com/OCA/l10n-italy/commit/f309def6744854bb263da29fbb79b5a067e9dff3) sono rossi e non è immediata la fix.

Non sarebbero da correggere nella migrazione?

**Comment by TheMule71** [comment]
Certo, se la cosa fosse semplice.

**Comment by SirTakobi** [comment]
> Certo, se la cosa fosse semplice.

Fosse una nuova funzionalità sarei più d'accordo, ma questo è un errore: non portarlo vuol dire causare una regressione nel modulo alla versione 16.
A quanto ho capito dai funzionali tra l'altro non è nemmeno così un errore da poco.

Ma forse avere subito un modulo bacato è meglio che avere un modulo funzionante settimana prossima?
Uovo oggi o gallina domani?

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/3300#issuecomment-1625357061

**Comment by MarcoCalcagni** [comment]
@eLBati  

nel fare i test sul nostro db ho :
<img width="1428" alt="image" src="https://github.com/OCA/l10n-italy/assets/11019886/c5f5519b-23a8-43af-b0dd-58ea8a386089">

posizione fiscale
<img width="1228" alt="image" src="https://github.com/OCA/l10n-italy/assets/11019886/1a876083-6ca1-43bf-af3e-6772203df9e9">

inversione contabile :
<img width="1395" alt="image" src="https://github.com/OCA/l10n-italy/assets/11019886/1ccb0434-ee38-4f7f-985a-a60a2fa4e795">



registro :
<img width="1145" alt="image" src="https://github.com/OCA/l10n-italy/assets/11019886/d34e0676-b043-4144-a1a7-5348a7686e2c">

<img width="1338" alt="image" src="https://github.com/OCA/l10n-italy/assets/11019886/bc2cf471-c059-4065-8d67-c17d45b48cc0">

**Comment by SirAionTech** [comment]
Questa si può chiudere perché alla fine è stata inclusa nella migrazione del modulo (https://github.com/OCA/l10n-italy/pull/3566).
