### ISSUE TITLE
Dichiarazioni di ritenuta d'acconto duplicate

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3288]
## Module
l10n_it_withholding_tax.

## Describe the bug
Ogni volta che viene riconfermata una fattura, viene creata una nuova dichiarazione di ritenuta d'acconto.

## To Reproduce
**Affected versions**:
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/3289
- [ ] `16.0`: https://github.com/OCA/l10n-italy/pull/3978 oppure https://github.com/OCA/l10n-italy/pull/3978

1. Creare una fattura fornitore con ritenuta d'acconto
2. Confermare la fattura: viene creata una dichiarazione
3. Riportare la fattura in bozza
4. Riconfermare la fattura

**Expected behavior**
Esiste solo una dichiarazioni di ritenuta d'acconto collegata alla fattura.

**Additional context**
Nella `12.0` il comportamento era quello atteso grazie all'attributo `ondelete='cascade'` del campo `withholding.tax.statement.move_id`:
https://github.com/OCA/l10n-italy/blob/ef639f820ef3505740eaaefce13aba24b9543ae9/l10n_it_withholding_tax/models/withholding_tax.py#L202-L203

**Comment by andreampiovesana** [comment]
per 16.0 ?

**Comment by SirAionTech** [comment]
> per 16.0 ?

Ho provato ora in runboat e il problema è presente anche in `16.0`.

**Comment by eLBati** [comment]
https://github.com/OCA/l10n-italy/pull/3705#issuecomment-1956718055

**Comment by eLBati** [comment]
Duplicata della https://github.com/OCA/l10n-italy/issues/2637

**Comment by eLBati** [comment]
> @eLBati intendi di #2938 ?

Uhm no

**Comment by francesco-ooops** [comment]
@eLBati se sono duplicate, perchè sono risolte da due PR diverse? (v14)

**Comment by eLBati** [comment]
Probabilmente perchè sono state portate avanti in parallelo, senza controllare se nel frattempo il problema fosse già risolto
