### ISSUE TITLE
Balance EU and XBRL

### ISSUE THREAD

**Issue by TennyMkt** [OCA/l10n-italy#3297]
**Is your feature request related to a problem?**
In Odoo non attualmente è complesso creare il Bilancio con la tassonomia UE e impossibile creare il relativo file XBRL
 
**Describe the solution you'd like**
 
#3064 
 
il modulo permette di:
- associare ai conti del Piano dei Conti le voci del Bilancio UE (con preassociazione automatica in fase di installazione del modulo)
- elaborare le registrazioni contabili di un dato periodo (per esempio l’anno precedente) al fine di ottenere il bilancio contabile in formato UE, facendo gli opportuni controlli di congruenza,  associazione di tutti i conti movimentati nel periodo e quadratura del bilancio). Nei report viene riportato anche il dettaglio dei conti associati ad una certa voce del bilancio UE
- generare il report di anteprima del Bilancio UE
- generare la stampa PDF del Bilancio UE
- generare i file XLSX e XBRL del bilancio (utili per successive rielaborazioni e per trasferimento del bilancio UE al Commercialista)
 
Novità versione 14.0.1.0.5 (21-04-2023)
- aggiunta scelta “Intervallo Date” nel wizard
- aggiunta check-box “Ignora registrazioni di chiusura” nel wizard (per poter fare il bilancio di annualità già chiuse)
- nuovo controllo su coerenza tra il valore del conto “Utile d’Esercizio” e somma dei Conti Economici
- aggiunta voce “Ignora” alle voci del Bilancio UE in modo da poter escludere dei conti del Piano dei Conti dai controlli 
- aggiunta la visualizzazione di tutti i conti associati, anche se non movimentati nel periodo, quando non è selezionata la “Nascondere conti a 0”
- correzione di altri bug minori
- presenza dei test unitari

**Comment by SirAionTech** [comment]
Ora che https://github.com/OCA/l10n-italy/pull/3064 è mergiata, si può chiudere questa issue?
