### ISSUE TITLE
Fiscal code

### ISSUE THREAD

**Issue by franksl** [OCA/l10n-italy#33]
Hi,
Are there any specifications for the 8.0 port of fiscal code module?
To my understanding I think it can be ported as is with just the new api enhancements. 
As I need to install it I could start to work on it if nobody already did.
Thanks,
Frank

**Comment by dcorio** [comment]
if the "codicefiscale" python module isn't installed you get a "ImportError: No module named codicefiscale" just by trying to start odoo.

the presence of that module should be checked (try/except?)

**Comment by eLBati** [comment]
Shouldn't check be done by
```
    'external_dependencies': {
        'python': ['codicefiscale'],
    },
```
?

**Comment by dcorio** [comment]
that blocks the installation if the module isn't installed.
but if it's not and you import it you get an exception by python while odoo is starting

**Comment by scigghia** [comment]
mybe a 
try:
    import codicefiscale
except ImportError:
  raise...

could solve this problem
imho

**Comment by dcorio** [comment]
if you raise an exception odoo won't start as well

**Comment by franksl** [comment]
The codicefiscale module does really simple checks and part of the logic of those checks is already implemented in this odoo module. My opinion is that the dependency could be removed and replaced by internal code.

**Comment by eLBati** [comment]
Just tried to reproduce the same error with ```base_report_to_printer``` after having removed ```cups```
I'm getting
```
  File "/home/elbati/workspace/odoo/buildout_cfg-odoo-8/parts/report-print-send/base_report_to_printer/__init__.py", line 24, in <module>
    from . import printing
  File "/home/elbati/workspace/odoo/buildout_cfg-odoo-8/parts/report-print-send/base_report_to_printer/printing.py", line 27, in <module>
    import cups
ImportError: No module named cups
```

Also, tried removing ```ldap``` python module but odoo module ```auth_ldap``` does not raise exception while starting odoo.
It does not even load ```users_ldap.py``` at start time, so, when trying to install ```auth_ldap```, the system correctly says
```Unable to install module "auth_ldap" because an external dependency is not met: No module named ldap```

So, there are differences between ```auth_ldap``` and ```l10n_it_codicefiscale``` about how they are loaded. But I can't find such differences at the moment

**Comment by eLBati** [comment]
Solved with
https://github.com/OCA/l10n-italy/blob/8.0/l10n_it_fiscalcode/wizard/compute_fc.py#L29-L35
