### ISSUE TITLE
[12.0] Scorretta richiesta Codice Fiscale

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#3306]
In anagrafica cliente, scheda "Contatti e indirizzi", in fase di aggiunta di un indirizzo di spedizione si verifica l'errore "[Italian partner %s must have VAT Number or Fiscal Code.](https://github.com/OCA/l10n-italy/blob/f66a289f451d7bbb2a7f5c491479479fa9db33d0/l10n_it_fatturapa/models/partner.py#L132)".

In questo contesto il C.F. non dovrebbe essere richiesto (infatti la form non prevede il campo per inserirlo).

**Comment by francesco-ooops** [comment]
@protontrigg3r ciao, riesci a riprodurre sul runbot della 12 ed allegare un video?

grazie!

**Comment by protontrigg3r** [comment]
ciao @francesco-ooops puoi linkarmi delle istruzioni su come usare runbot?

**Comment by francesco-ooops** [comment]
Ciao, da https://github.com/OCA/l10n-italy prima selezioni il branch che ti interessa:

![image](https://github.com/OCA/l10n-italy/assets/55489873/98cd05db-912f-46a8-a313-679a90e1f053)

poi scorri in fondo alla lista dei moduli e il runboat con tutti i moduli l10n-italy installati è accessibile da qui

![image](https://github.com/OCA/l10n-italy/assets/55489873/ffd96754-d16f-44df-bf13-333b03355f38)

**Comment by protontrigg3r** [comment]
Grazie @francesco-ooops su runboat l'errore non si presenta (ache se la versione su cui sto operando non è tra quelle elencate). Ho pensato che si trattasse di un bug dopo che un post nel forum è rimasto senza risposta per una settimana.

In merito a runboat aggiungo un paio di informazioni nel caso tornassero utili a qualcun altro: dopo aver cliccato si "Start" in una delle istanze di Odoo è necessario attendere che compaia il link "**_live_**" che permette di accedere alla schermata di login (user: **admin** e password: **admin**):

![Screenshot from 2023-05-17 08-58-14](https://github.com/OCA/l10n-italy/assets/38140509/67ef16a5-f026-4277-aba8-bcf1e2e47942)
