### ISSUE TITLE
Errore nel salvataggio del dato “force_desclaration_of_intent_id” (Forzare dichiarazione d'intento)

### ISSUE THREAD

**Issue by mktsrl** [OCA/l10n-italy#3309]
## Module
l10n_it_declaration_of_intent
 
## Describe the bug
In presenza del modulo l10n_it_declaration_of_intent, nella “Fattura Cliente / Righe fattura”, compare un nuovo campo “Forzare dichiarazione di intento” che consente di selezionare tramite una tendina una delle dichiarazione di intento associate con il cliente.
La selezione e compilazione del campo funziona correttamente.
Quando dopo aver compilato il campo si effettua il salvataggio della fattura “"(pulsante “Salva”) il dato viene vuotato.
Il comportamento non cambia se si seleziona la stessa dichiarazione già selezionata in testata (o associata al cliente tramite Posizione Fiscale) o una dichiarazione diversa.
 
## To Reproduce
**Affected versions**: 14.0

- [x] 14.0: #3312 

1. installare e attivare il modulo l10n_it_declaration_of_intent
2. Inserire una Dichiarazione di Intento valida su un cliente
3. Creare una nuova fattura per lo stesso cliente 
4. Inserire una riga fattura e selezionare una dichiarazione di intento nel campo “Forzare dichiarazione di intento” (quella creata al pto. 2)
6. Salvare la fattura (il dato “Forzare dichiarazione di intento” è ancora visibile sulla riga prima del salvataggio)
7. il dato “Forzare dichiarazione di intento” scompare col salvataggio.
 
**Expected behavior**
Il comportamento corretto deve prevedere che il dato “Forzare dichiarazione di intento” persista anche dopo il salvataggio della fattura

**Comment by matteoopenf** [comment]
stiamo riscontrando anche noi il problema e sto indagando per capire se riesco a capire il motivo

**Comment by SirTakobi** [comment]
Probabile che sia un problema analogo a https://github.com/OCA/l10n-italy/pull/2393, puoi vedere come è stato risolto lì: long story short, nella vista devi aggiungere il campo anche alla tree delle `line_ids`

**Comment by matteoopenf** [comment]
> Probabile che sia un problema analogo a #2393, puoi vedere come è stato risolto lì: long story short, nella vista devi aggiungere il campo anche alla tree delle `line_ids`

vedo subito grazie mille

**Comment by matteoopenf** [comment]
> Probabile che sia un problema analogo a #2393, puoi vedere come è stato risolto lì: long story short, nella vista devi aggiungere il campo anche alla tree delle `line_ids`

confermo risolve e apro la pr tra poco

**Comment by matteoopenf** [comment]
Eccola https://github.com/OCA/l10n-italy/pull/3312 @mktsrl  puoi metterla nella descrizione della issue perfavore?
Grazie Mille

**Comment by TheMule71** [comment]
L'ho aggiunta io.

**Comment by francesco-ooops** [comment]
@TheMule71 puoi verificare se la PR linkata per la 16 risolve questa issue, e in caso riaprire?

**Comment by SirAionTech** [comment]
> @TheMule71 puoi verificare se la PR linkata per la 16 risolve questa issue, e in caso riaprire?

La PR linkata per la `16.0` è #3513 ed è verso `14.0`, ne volevi linkare un'altra?

**Comment by francesco-ooops** [comment]
Grazie @SirAionTech , per caso vedi una qualche PR che risolve per 16 o è da fare?

**Comment by SirAionTech** [comment]
> Grazie @SirAionTech , per caso vedi una qualche PR che risolve per 16 o è da fare?

https://github.com/OCA/l10n-italy/pull/3312 risolve come era stato suggerito in https://github.com/OCA/l10n-italy/issues/3309#issuecomment-1550996520 e a quanto ne so quel tipo di problemi non esiste più in `16.0`, quindi non credo il problema esista in `16.0`.
