### ISSUE TITLE
[14] l10n_it_ricevute_bancarie - possibilità di emettere una RiBa senza avere il permesso "Amministratore = Impostazioni"

### ISSUE THREAD

**Issue by SicurSam** [OCA/l10n-italy#3313]
Un utente Senza il permesso "Amministrazione = Impostazioni" non è in grado di emettere una RiBa:
https://recordit.co/NsfTQfdtlk

La desiderata sarebbe trovare un modo per Emettere una RiBa senza avere il permesso "Amministratore = Impostazioni"

- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3352

**Comment by francesco-ooops** [comment]
@SicurSam il problema è presente anche in v16?

**Comment by matteoopenf** [comment]
> @SicurSam il problema è presente anche in v16 / v12?

sicuramente questo cambiamento interessa da 14 in poi prima su 12 era diverso

**Comment by francesco-ooops** [comment]
@matteoopenf vedo che la 16 è in fase di migrazione ed è stata segnalata la PR

@tafaRU possiamo chiudere
