### ISSUE TITLE
[14.0][16.0][FIX] - Stesso numero DN per due documenti 

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#3314]
È possibile assegnare lo stesso numero di DDT a due documenti distinti
l10n_it_delivery_note

**Descrizione**
Forzando il numeratore del DDT a un numero esistente il sistema non riconosce l'errore assegnando lo stesso numero a 2 DDT 

Versioni con il problema:
- [x] 14.0: https://github.com/OCA/l10n-italy/pull/3374
- [x] 16.0: https://github.com/OCA/l10n-italy/pull/3388

**Per riprodurre**
1. creo e valido un DDT, viene assegnato il numero DDT/00001
2. creo e valido un secondo DDT, viene assegnato il numero DDT/00002
3. annullo, porto in bozza e modifico il numero da DDT/00002 a DDT/00001
4. valido

![immagine](https://github.com/OCA/l10n-italy/assets/25057933/7c36e11a-36f1-4c7d-a84f-c59d11cc611f)

**Comportamento atteso**
Non consentire la validazione di numeri uguali

**Comment by andreampiovesana** [comment]
@As400it cosa dici?

**Comment by As400it** [comment]
facciamo una pr

**Comment by As400it** [comment]
@andreampiovesana @marcelofrare  un Approve pls

**Comment by marcelofrare** [comment]
solved with #3374
Tnx!

**Comment by marcelofrare** [comment]
@tafaRU hai dedotto bene... ora che è stata fatta anche sulla 16.0, la richudo
