### ISSUE TITLE
Calcolo di ammortamenti su cespiti completamente ammortizzati con incremento valore successivo

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3318]
## Module
assets_management

## Describe the bug
Nel caso in cui venga effettuato un acquisto successivo per un cespite completamente ammortizzato, è possibile calcolare ammortamenti per anni in cui il cespite aveva un valore residuo da ammortizzare a zero.
Inoltre il report previsionale calcola ammortamenti anche nei periodi in cui il cespite aveva valore residuo da ammortizzare a zero.

## To Reproduce
**Affected versions**:
- [x] 12.0 (risolta per termine supporto)
- [x] 14.0 #3316 
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/3776

1. creare un cespite da zero o con un acquisto
2. ammortizzare il cespite completamente
3. creare un acquisto successivo di almeno un anno posteriore al completamento dell'ammortamento totale del cespite (tipo cespite ammortizzato completamente nel 2021, acquisto di incremento valore nel 2023)
4. ammortizzare il cespite: permette di farlo anche per l'anno in cui era completamente deprezzato (es. 2022)

**Expected behavior**
L'ammortamento non dovrebbe essere calcolato quando il cespite è completamente ammortizzato.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by francesco-ooops** [comment]
@SirAionTech ok aggiunto anche in descrizione migrazione
