### ISSUE TITLE
[l10n_delivery_note_base] - rimuovere vincolo fornitore per vettore

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3325]
## Describe the bug

E' possibile impostare come vettore nel DdT solo un fornitore, ma questo non è ideale se non è stato fatto alcun acquisto, dato che dalla 14 in poi non si può impostare manualmente il flag "è un fornitore" se non utilizzando altri moduli oca

![image](https://github.com/OCA/l10n-italy/assets/55489873/cb4bfbb1-1ec2-4156-bd1b-5e55dba523f9)

## To Reproduce
**Affected versions**:

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/3367
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/3633

**Expected behavior**

Possibili soluzioni: 

- rimuovere il vincolo
- mettere un flag "vettore" nel contatto, anche perché non ha granché senso trovarsi il salumiere tra i vettori

**Comment by andreampiovesana** [comment]
concordo
