### ISSUE TITLE
Reverse charge per fatture fornitore in valuta estera

### ISSUE THREAD

**Issue by MarcoCalcagni** [OCA/l10n-italy#3331]
quando si registra una fattura fornitore in valuta il reverse charge emette una fattura clienti in valuta che ha gli importi contabili non corretti. 

## Module
l10n_it_reverse_charge

## Describe the bug
i valori in euro sono diversi tra fattura passiva e attiva 

## To Reproduce

- [ ] 14.0 no (?)
- [ ] 16.0 sì

1. registra una fattura in dollari es 1000$ iva 220% 22$ di iva (iva è aggiunta per le regole del reverse) con data fattura 1 maggio data contabile 25 maggio. 
la registrazione contabile sarà  USD 1000,00	Eur 911,61 per le merci e iva USD 22,00	EUR 200,55  
è stato applicato correttamente il cambio del 1 maggio  
2. conferma la fattura e verrà creata la fattura cliente automaticamente 
3. la fattura cliente avrà data documento 25 maggio data contabile 25 maggio 
importi della fattura  USD 1000,00  EUR  911,29  Iva  USD 22,00 EUR 200,62 il cambio usato del 25 maggio. 

gli importi contabili sono diversi. 

**Expected behavior**
gli importi contabili devono essere gli stessi in entrambe le fatture. 
Le date è corretto che siano come quelle attuali.

la mia proposta è di creare la fattura attiva non più in valuta ma direttamente in euro. questo dovrebbe risolvere il problema e secondo il mio commercialista non dovrebbe essere un problema il fatto che fattura passiva è in USD e attiva in Eur in quanto ciò che conta sono gli importi in eur che devono essere uguali. 

@marco-marchiori che ne pensi ? se sei d'accordo sforniamo una PR fresca fresca :-)

**Comment by matteoopenf** [comment]
c'e' anche su 14 il problema e lo avevo segnalato e aperto una pr.
Riprendo il tutto asp

**Comment by matteoopenf** [comment]
https://github.com/OCA/l10n-italy/pull/3096 avevo anche aperto la ISSUE https://github.com/OCA/l10n-italy/issues/3097

**Comment by As400it** [comment]
il problema che hai segnalato è che converte più volte nel xml gli importi e Borruso ha fatto una pr che corregge il problema. (se hai iva =0 valore era corretto xml se iva  != 0 convertiva due volte) ma questo nella creazione xml. 
L'issue di sopra è che hai proprio valori diversi di iva . perchè un cambio è al 1 maggio e l'altro al 25 maggio .

**Comment by matteoopenf** [comment]
> il problema che hai segnalato è che converte più volte nel xml gli importi e Borruso ha fatto una pr che corregge il problema. (se hai iva =0 valore era corretto xml se iva  != 0 convertiva due volte) ma questo nella creazione xml. 
> 
> L'issue di sopra è che hai proprio valori diversi di iva . perchè un cambio è al 1 maggio e l'altro al 25 maggio . 
> 
>  

Hai ragione

**Comment by sergiocorato** [comment]
Non mi risulta che sulla 14.0 il cambio utilizzato sia quello della data fattura.
Il cambio utilizzato mi risulta sia sempre quello della data contabile, quindi il problema non esiste.
