### ISSUE TITLE
Stale github action processa poche PR/issues a ogni run

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3334]
Da: https://github.com/OCA/l10n-italy/pull/2202#issuecomment-1564011290

Le PR/issue che non sono state aggiornate da oltre 4 mesi non vengono marcate con l'etichetta "stale"

E' possibile ripristinare la funzionalità?

**Comment by SirTakobi** [comment]
Riporto il messaggio che ho scritto poco fa in Discord (https://discord.com/channels/753902328494424064/753902328494424070/1112669401725026376):

>La action è https://github.com/actions/stale, qui puoi trovare maggiori dettagli sul suo funzionamento.
Viene usata solo la configurazione che è sul branch di default, nel nostro caso quella di 14.0: https://github.com/OCA/l10n-italy/blob/c0ce8b454fb962f5270a4d43039e6353a5dcb60f/.github/workflows/stale.yml.
Di default non vengono processate tutte le issue/PR ma solo le prime 30 che trova, vedi https://github.com/actions/stale#operations-per-run.
C'è un warning che fa riferimento a questa impostazione anche nella run stessa: 
![image](https://github.com/OCA/l10n-italy/assets/101628000/29a8c3b9-4ee2-46fa-88bf-84b7d88a6fac)
> >If you think that not enough issues were processed you could try to increase the quantity related to the operations-per-run (​https://github.com/actions/stale#operations-per-run%E2%80%8B) option which is currently set to 30
>
>(da https://github.com/OCA/l10n-italy/actions/runs/5037626416)

**Comment by TheMule71** [comment]
È comunque strano, dovrebbe processare ad ogni giro le 30 più vecchie, e marcarle stale... al giro successivo dovrebbe saltarle, a logica.

**Comment by SirTakobi** [comment]
> È comunque strano, dovrebbe processare ad ogni giro le 30 più vecchie, e marcarle stale... al giro successivo dovrebbe saltarle, a logica.

Anche solo guardarle penso venga contata come _operazione_ perché conta nei limiti delle chiamate API.
Tutte le operazioni sono comunque elencate nella run dove viene riportato quelle che ha guardato e cosa ha fatto per ognuna, c'è anche un mini-report alla fine del job dedicato:
>Statistics:
Processed items: 16
├── Processed issues: 13
└── Processed PRs   : 3
New stale issues: 2
Closed items: 3
├── Closed issues: 2
└── Closed PRs   : 1
Added issues labels: 2
Added issues comments: 2
Fetched items: 100
Fetched items events: 11
Fetched items comments: 11
Operations performed: 30

(da https://github.com/OCA/l10n-italy/actions/runs/5037626416/jobs/9034591723#step:2:440)

**Comment by TheMule71** [comment]
Ok, allora a vederlo così, consuma operazioni anche per le PR/issue che sono già stale.   Ne processa meno di venti al giro.

Ne abbiamo 9 stale, in pratica avanzerà quando ne chiude una.  Tenendo conto che siamo alla #1712, tutte le successive non vengono guardate.
Ci vorrà un po' per arrivare alla #2202.  A meno che non ci mettiamo a chiudere a mano le stale per farlo avanzare più velocemente.

**Comment by TheMule71** [comment]
Le ho guardate, per la maggior parte sono issue risolte per la 12 con PR mergiata, lasciate aperte (senza PR) per 10 e 11.

Io dico che le issue risolte per la 12 senza PR per le altre precedenti versioni si possono anche chiudere senza aspettare i 30 giorni.

**Comment by francesco-ooops** [comment]
@SirTakobi @TheMule71 

Quanto costa / cosa comporta aumentare il numero di operazioni della action? 

Credo che se si aumentassero per qualche settimana o mese sarebbe in grado di smaltire il backlog, e il numero di operazioni necessarie si ri-abbasserebbe nel tempo

Penso che l'etichetta "stale" sia un buon sistema per richiamare l'attenzione a task lasciate indietro e sollecitare una verifica sulle funzionalità che sono veramente necessarie

**Comment by francesco-ooops** [comment]
> @SirTakobi @TheMule71
> 
> Quanto costa / cosa comporta aumentare il numero di operazioni della action?
> 
> Credo che se si aumentassero per qualche settimana o mese sarebbe in grado di smaltire il backlog, e il numero di operazioni necessarie si ri-abbasserebbe nel tempo
> 
> Penso che l'etichetta "stale" sia un buon sistema per richiamare l'attenzione a task lasciate indietro e sollecitare una verifica sulle funzionalità che sono veramente necessarie

@tafaRU che ne dici?

**Comment by francesco-ooops** [comment]
Ottimo @SirAionTech, non so se per il futuro vada ripristinato il valore (un item o è da processare o non lo è), per cui chiudo 👍

**Comment by SirAionTech** [comment]
> Ottimo @SirAionTech, non so se per il futuro vada ripristinato il valore (un item o è da processare o non lo è), per cui chiudo 👍

Si potrà ripristinare quando ce ne saranno meno, per il momento secondo me si può aumentare ancora.
Attualmente sta mettendo a _stale_ circa una decina di issue a settimana che sono meno di quelle che vengono aperte.
