### ISSUE TITLE
La lista delle fatture elettroniche non è sempre visibile agli utenti non amministratori

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#3336]
## Module
l10n_it_fatturapa_out

## Describe the bug
A causa del modo in cui creiamo gli allegati XML, e del modo in cui odoo gestisce gli allegati non correttamente collegati con un'istanza di un modello, un utente normale vede solo i propri allegati. Se prova a visualiizare una lista contenente un record non suo, ottiene un errore.

Si veda anche https://github.com/OCA/l10n-italy/issues/3164

## To Reproduce
**Affected versions**:

- [x] 12.0 da verificare (risolta per termine supporto)
- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/4194
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/4107

1. Creare un XML con utente 1
2. Cercare di aprire da menu la lista delle f.e. con utente 2 privo di permessi di settings (qualsiasi)

**Expected behavior**
O la lista è visibile, o almeno il sistema dovrebbe visualizzare una lista limitata ai record visibili

**Additional context**
Vd. https://github.com/odoo/odoo/blob/e8834cb00b82e0bee7f6338aef940037a3e49471/odoo/addons/base/models/ir_attachment.py#L427-L438

Non vengono applicati i normali permessi. O `.is_system()` è True  (equivale ad avere il gruppo `base.group_system`) oppure deve essere i creatore. Questo se `res_id` è vuoto.

Noi creiamo gli allegati senza `res_model` e senza `res_id`.

**Comment by michelerusti** [comment]
#3371 per la 16.0

**Comment by SirTakobi** [comment]
> Vd. https://github.com/odoo/odoo/blob/e8834cb00b82e0bee7f6338aef940037a3e49471/odoo/addons/base/models/ir_attachment.py#L427-L438

Quindi l'errore sollevato è `"Sorry, you are not allowed to access this document."`?
Mi pare strano che in un metodo `api.model` ci sia `self`, dal commento sembra una parte di codice dedicata solo al test `test_01_portal_attachment`; hai mica recuperato da dove viene fatta la chiamata (il passo prima dello stacktrace)?

**Comment by SirTakobi** [comment]
@tafaRU hai aggiunto in descrizione un link a questa stessa issue, forse doveva essere un'altra? Magari 3164?

**Comment by tafaRU** [comment]
@SirTakobi grazie, corretto.

**Comment by FrancescoBallerini** [comment]
Vi segnalo anche questa https://github.com/odoo/odoo/pull/82111. 
Qui hanno gestito il problema in mass mailing, non ho trovato la PR aggiornata ma hanno spostato quel pezzo di codice in questo mini metodo https://github.com/odoo/odoo/blob/a8c82e6e4e47d951601364f1714a4150fa63f62a/addons/mail/models/mail_template.py#L70C9-L73, mi chiedevo se fosse già stato valutato questo approccio, che coprirebbe anche l'esigenza espressa nella review di @SirTakobi https://github.com/OCA/l10n-italy/pull/3337#discussion_r1226308474 .

Sempre in merito a https://github.com/OCA/l10n-italy/pull/3337#discussion_r1226308474 volevo aggiungere: 

a prescindere dalla soluzione che verrà adottata per gli attachment scaricati, resta il fatto che quelli creati pre-PR hanno il `res_id` e il `res_model` nulli. 

1) domanda generica: come soluzione rapida, per garantire quantomeno l'accesso ai records, che cosa comporta avere i `res_id` impostati al valore dummy -1? 

2) domanda specifica: a tal proposito stavo provando in qualche modo ad associare gli ir.attachment con attachment in/out, in parte ci sono riuscito con questo script da shell ed ho notato due cose

```
# Eseguito da Odoo shell:

model_name = 'fatturapa.attachment.out'
records_to_update = self.env[model_name].search([])
for rec in records_to_update:
    irattachment_res = self.env['ir.attachment'].search([('name', '=', rec.name)])
    for att in irattachment_res:
        att.res_id = att.id
        att.res_model = model_name
self.env.cr.commit()
```

La prima è che ovviamente non matcha tutti i files, ma solo quelli degli allegati xml, grazie al nome. 
In effetti mi chiedo se sia possibile trovare un riferimento che ri-associ correttamente tutti gli altri attachments per le fatture importate.

La seconda cosa è strana, gli attachment che riesco a matchare e a ri-associare **non consentono l'apertura del record se cliccati, salvo ripristinare il res_id.** Non ho ancora trovato spiegazioni in merito.

**Comment by eLBati** [comment]
Propongo questa soluzione: https://github.com/OCA/l10n-italy/pull/3827
