### ISSUE TITLE
Refactoring cespiti per correzioni vari bug (assets_management)

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3351]
## Module
assets_management

## Describe the bug
Riassumo in questa issue le varie problematiche risolte in varie PR:
- bottone 'Vedi' su report cespiti e report cespiti previsionale non funzionante:
  - [x] 14.0: #3348 
  - [x] 16.0: integrata in #3776
- rimozione dalle stampe dei cespiti venduti, con opzione per includerli:
  - [x] 14.0: #3330 
  - [x] 16.0: integrata in #3776 
- dismissione di un cespite (distruzione) senza vendita:
  - [x] 14.0: #3239 
  - [x] 16.0: integrata in #3776 
- rimozione diretta delle righe contabili collegate a fatture senza dover risalire alla fattura:
  - [x] 14.0: #3238 
  - [x] 16.0: integrata in #3776
- corretta funzione di verifica data dismissione: 
  - [x] 14.0: #3346 (issue #3170)
  - [x] 16.0: https://github.com/OCA/l10n-italy/pull/3776/
- corretta funzione di generazione ammortamenti in data:
  - [x] 14.0: #3316 (issue #3318)
  - [x] 16.0: integrata in #3776
- rimossa la creazione di righe ammortamento a 0:
  - [x] 14.0: #3125 
  - [x] 16.0: https://github.com/OCA/l10n-italy/pull/3776/
- corretta funzione di conversione valuta:
  - [x] 14.0: #3349
  - [x] 16.0: integrata in #3776 
- aggiunte funzioni di estrazione movimenti in e out:
  - [x] 14.0: #3350  non so l'utilità di queste funzioni, da riprendere in mano se servisse
  - [x] 16.0: non so l'utilità di queste funzioni, da riprendere in mano se servisse
- correct permission management:
  - [x] 14.0: #3281 
  - [x] 16.0: integrata in #3776
- includere nella stampa cespiti non ancora ammortizzati:
  - [x] 14.0: #3393 
  - [x] 16.0: https://github.com/OCA/l10n-italy/pull/3776/

## To Reproduce
**Affected versions**:
- 16.0: #3776

**Expected behavior**

**Additional context**
~Ho caricato anche una PR stile 'SUPERMERGE' per facilitare i test qui: https://github.com/OCA/l10n-italy/pull/3345~

**Comment by aleuffre** [comment]
Posso aggiungere questa tra le problematiche? I model sono aperti a tutti senza permessi di sicurezza

https://github.com/OCA/l10n-italy/pull/3281

**Comment by matteoopenf** [comment]
@sergiocorato  per caso per quelle approvate si potrebbe procedere al merge?

**Comment by odooNextev** [comment]
@sergiocorato puoi linkare la PR nella casella della 16: https://github.com/OCA/l10n-italy/pull/3271
Ho già integrato le modifiche della https://github.com/OCA/l10n-italy/pull/3348 e https://github.com/OCA/l10n-italy/pull/3349

**Comment by sergiocorato** [comment]
> Posso aggiungere questa tra le problematiche? I model sono aperti a tutti senza permessi di sicurezza
> 
> #3281

Fatto, grazie.

**Comment by sergiocorato** [comment]
> @sergiocorato puoi linkare la PR nella casella della 16: #3271 Ho già integrato le modifiche della #3348 e #3349

Fatto (compreso la #3330 ), grazie.

**Comment by stenext** [comment]
Ho integrato nella migrazione alla 16 anche https://github.com/OCA/l10n-italy/pull/3238

**Comment by stenext** [comment]
Ho integrato nella migrazione alla 16 anche #3316
Ora faccio un test dello script di migrazione del DB e poi pubblico questi commit

**Comment by francesco-ooops** [comment]
@sergiocorato se ci sono nuovi comportamenti importanti introdotti da queste PR, potresti aggiungerle alla descrizione del modulo? giusto per non lasciare al buio i funzionali. Grazie!

**Comment by odooNextev** [comment]
Ho integrato nella migrazione alla 16 anche questa https://github.com/OCA/l10n-italy/pull/3239

**Comment by odooNextev** [comment]
@sergiocorato vuoi aggiungere qui il tracciamento di questo fix a `.format(line_type.name)` o devo creare una nuova issue?
https://github.com/OCA/l10n-italy/pull/3271#discussion_r1342780030

**Comment by odooNextev** [comment]
Ho integrato nella migrazione anche https://github.com/OCA/l10n-italy/pull/3281

**Comment by francesco-ooops** [comment]
@sergiocorato #3393 dovrebbe essere aggiunta a questa lista?

**Comment by sergiocorato** [comment]
> @sergiocorato #3393 dovrebbe essere aggiunta a questa lista?

giusto

**Comment by sergiocorato** [comment]
probabilmente si possono rimuovere i link alla v. 12.0

**Comment by francesco-ooops** [comment]
> probabilmente si possono rimuovere i link alla v. 12.0

fatto! 

@SirAionTech confermi che tutte le PR mergiate per la 14 sono presenti nella tua PR di migrazione alla 16?
o anche alcune non mergiate?

**Comment by SirAionTech** [comment]
> > probabilmente si possono rimuovere i link alla v. 12.0
> 
> fatto!
> 
> @SirAionTech confermi che tutte le PR mergiate per la 14 sono presenti nella tua PR di migrazione alla 16?

Tutto ciò che è mergiato in `14.0` è anche nella migrazione alla `16.0` https://github.com/OCA/l10n-italy/pull/3776.

>  o anche alcune non mergiate?

Nella migrazione ci sono anche le fix per #3009 e #3775 (che non sono in questa issue).

**Comment by SirAionTech** [comment]
Incluse anche #3346 #3393 #3125 in #3776
