### ISSUE TITLE
Il pulsante "Crea fattura" da  DdT in ingresso non funziona

### ISSUE THREAD

**Issue by cstevanatonehos** [OCA/l10n-italy#3357]
## Module
l10n_it_delivery_note

## Describe the bug
Cliccando sul pulsante "Crea fattura" da DdT in ingresso ricevo il seguente errore "DIN/2023/00001 non ha un ordine di vendita"

## To Reproduce
**Affected versions**:

- [ ] 14.0
- [ ] 16.0

1. Creare ordine di acquisto e confermarlo per creare dei trasferimenti
2. Dai trasferimenti creare un DdT
3. Dal DdT cliccare sul pulsante

**Expected behavior**
Dovrebbe creare la fattura a prescindere senza bloccare l'esecuzione del programma perchè non ci sono ordini di vendita, in quanto ci sono ordini d'acquisto.

**Comment by TheMule71** [comment]
Credo che andrebbe tolto il button dai DDT in ingresso.   Al momento 'Crea fattura' è previsto solo per il flusso attivo.

https://github.com/OCA/l10n-italy/blob/1d32f64759584eec320a90301d4b692dfe06246f/l10n_it_delivery_note/models/stock_delivery_note.py#L469-L474

<details>
<summary>Opinione personale</summary>
Fosse per me, io nasconderei completamente la gestione dei DDT in ingresso dietro ad un flag esplicito, fa solo confusione e genera errori. Si prende il PDF/scansione del vero DDT e lo si allega al picking in ingresso, e tanto basta per archiviarlo.  Staccare un numero di sequenza apposito (tipo "DIN/2023/00001") per i DDT ricevuti potrebbe rappresentare al massimo il numero di protocollo, ma per protocollare basterebbe un modello molto semplice, sempre ammesso che abbia senso usare Odoo come registro di protocollo.
</details>
