### ISSUE TITLE
[14.0] [l10n_it_fatturapa_in] – Importazione fattura elettronica con totale negativo in modalità “Livello di dettaglio: Aliquota fiscale” 

### ISSUE THREAD

**Issue by danall59** [OCA/l10n-italy#3358]
## Module 
l10n_it_fatturapa_in
 
## Describe the bug
Importando una fattura con totale negativo in modalità “raggruppamento: per aliquota” la fattura elettronica XML viene creata una fattura con il dettaglio positivo invece che negativo come dovrebbe essere.
Usare il file XML di esempio riportato qui in allegato (fattura con totale negativo).

## To Reproduce
**Affected versions**:  ODOO CE versione 14
 
1. Da “Fatturazione / Fornitori / File e-fatture in ingresso” caricare il file XML in allegato con “CREA” + “SALVA”
2. Selezionare il file “e-fattura” e fare azione “Importa fattura elettronica”. Nella maschera del wizard selezionare “Livello di dettaglio e-fatture: Aliquota fiscale” 
3. Aprire la fattura creata e verificare che il dettaglio è stato creato con importo positivo e il totale documento è positivo.
 
**Expected behavior**
Il comportamento atteso è che venga creato un dettaglio con importo negativo e quindi una fattura (TD01) con totale negativo.
 
**Additional context**
Il file TXT allegato è in realtà un file XML con l'estensione modificata: IT02663950984_6lsDM.XML
[IT02663950984_6lsDM.txt](https://github.com/OCA/l10n-italy/files/11627273/IT02663950984_6lsDM.txt)

**Comment by danall59** [comment]
E' probabile che questo comportamento anomalo dell'importazione fattura elettronica passiva sia collegato con l'altro BUG che avevamo segnalato con la ISSUE #2959 e che è ancora pending.
Nella #2959 avevamo individuato il problema nella funzione _prepareInvoiceLineAliquota di l10n_it_fatturapa_in e avevamo proposto una modifica da apportare sul codice.
Questa modica era stata da noi provata con successo, ma poi avevamo dovuto caricare delle versioni aggiornate di l10n_it_fatturapa_in e quindi avevamo perso la patch (che era stata fatta come una modifica estemporanea direttamente al sorgente di l10n_it_fatturapa_in)

**Comment by tafaRU** [comment]
Annullo perché duplicata di https://github.com/OCA/l10n-italy/issues/2959
