### ISSUE TITLE
Esportare solo il numero di telefono dedicato alla fattura elettronica

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3364]
## Module
l10n_it_fatturapa_out

## Describe the bug
Durante l'esportazione della fattura elettronica, viene utilizzato il campo **Telefono** (`res.company.phone`) dell'azienda.

## To Reproduce
**Affected versions**:
- [x] `12.0`: https://github.com/OCA/l10n-italy/pull/3365
- [ ] `14.0`: ?
- [ ] `16.0`: ?

1. Nell'azienda, impostare i campi:
    - **Telefono** = 1 234 5
    - **Telefono per fattura elettronica** = 678910
3. Esportare una fattura elettronica

**Expected behavior**
Solo il **Telefono per fattura elettronica** (`res.company.phone_electronic_invoice`) è presente nella fattura elettronica esportata.

**Comment by SirAionTech** [comment]
In `12.0` il campo **Telefono per fattura elettronica** (`res.company.phone_electronic_invoice`) era stato aggiunto da https://github.com/OCA/l10n-italy/pull/1934 che implementa https://github.com/OCA/l10n-italy/issues/2405.

Per `16.0` la soluzione a #2405 è https://github.com/OCA/l10n-italy/pull/3477 (ancora aperta): il campo non viene aggiunto, suppongo sia perché in `16.0` esiste il trasmittente già dalla migrazione https://github.com/OCA/l10n-italy/pull/2996.
In `16.0` quindi il campo non esisterà, quindi secondo me la issue si può considerare risolta.

Per `14.0` il ragionamento è lo stesso: https://github.com/OCA/l10n-italy/pull/3451 (ancora aperta) non aggiunge il campo, quindi secondo me la issue si può considerare risolta.

@matteoopenf visto che aggiungesti tu il campo **Telefono per fattura elettronica** (`res.company.phone_electronic_invoice`) in https://github.com/OCA/l10n-italy/pull/1934, cosa ne pensi? Serve ancora nelle versioni successive?
