### ISSUE TITLE
Il package odoo16-addon-l10n-it-fatturapa non è disponibile

### ISSUE THREAD

**Issue by borgogelli** [OCA/l10n-italy#3368]
Il seguente comando restituisce errore:

`pip3 install --pre odoo16-addon-l10n-it-fatturapa`

```
ERROR: Could not find a version that satisfies the requirement odoo16-addon-l10n-it-fatturapa (from versions: none)
ERROR: No matching distribution found for odoo16-addon-l10n-it-fatturapa
```

**Comment by SirTakobi** [comment]
Dalla versione 15 non è più necessario specificare la versione di Odoo nel nome del pacchetto, quindi quello che vorresti installare è https://pypi.org/project/odoo-addon-l10n-it-fatturapa.
Per installarlo puoi eseguire:
```
pip3 install --pre odoo-addon-l10n-it-fatturapa
```
Il cambiamento è descritto più in dettaglio in https://github.com/acsone/setuptools-odoo/issues/58

**Comment by borgogelli** [comment]
Grazie mille

**Comment by borgogelli** [comment]
@SirTakobi  ora l'errore è cambiato

`(odoo16-venv) odoo@odoo16:~$ pip3 install --pre odoo16-addon-l10n-it-fatturapa`


```
ERROR: Cannot install odoo-addon-l10n-it-fatturapa==16.0.1.0.0.3, odoo-addon-l10n-it-fatturapa==16.0.1.0.0.4, odoo-addon-l10n-it-fatturapa==16.0.1.0.0.5, odoo-addon-l10n-it-fatturapa==16.0.1.0.1 and odoo-addon-l10n-it-fatturapa==16.0.1.0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    odoo-addon-l10n-it-fatturapa 16.0.1.0.1.1 depends on odoo<16.1dev and >=16.0a
    odoo-addon-l10n-it-fatturapa 16.0.1.0.1 depends on odoo<16.1dev and >=16.0a
    odoo-addon-l10n-it-fatturapa 16.0.1.0.0.5 depends on odoo<16.1dev and >=16.0a
    odoo-addon-l10n-it-fatturapa 16.0.1.0.0.4 depends on odoo<16.1dev and >=16.0a
    odoo-addon-l10n-it-fatturapa 16.0.1.0.0.3 depends on odoo<16.1dev and >=16.0a

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

```

**Comment by SirTakobi** [comment]
> @SirTakobi ora l'errore è cambiato
> 
> `(odoo16-venv) odoo@odoo16:~$ pip3 install --pre odoo-addon-l10n-it-fatturapa`
> 
> ```
> ERROR: Cannot install odoo-addon-l10n-it-fatturapa==16.0.1.0.0.3, odoo-addon-l10n-it-fatturapa==16.0.1.0.0.4, odoo-addon-l10n-it-fatturapa==16.0.1.0.0.5, odoo-addon-l10n-it-fatturapa==16.0.1.0.1 and odoo-addon-l10n-it-fatturapa==16.0.1.0.1.1 because these package versions have conflicting dependencies.
> 
> The conflict is caused by:
>     odoo-addon-l10n-it-fatturapa 16.0.1.0.1.1 depends on odoo<16.1dev and >=16.0a
>     odoo-addon-l10n-it-fatturapa 16.0.1.0.1 depends on odoo<16.1dev and >=16.0a
>     odoo-addon-l10n-it-fatturapa 16.0.1.0.0.5 depends on odoo<16.1dev and >=16.0a
>     odoo-addon-l10n-it-fatturapa 16.0.1.0.0.4 depends on odoo<16.1dev and >=16.0a
>     odoo-addon-l10n-it-fatturapa 16.0.1.0.0.3 depends on odoo<16.1dev and >=16.0a
> 
> To fix this you could try to:
> 1. loosen the range of package versions you've specified
> 2. remove package versions to allow pip attempt to solve the dependency conflict
> 
> ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
> ```

Ho appena provato su un nuovo virtualenv ed effettivamente ho riprodotto il tuo errore, il problema credo sia che non c'è un pacchetto `odoo` in PyPI (esiste https://pypi.org/project/odoo ma mi sembra fake).
Ho risolto installando `odoo` nel virtualenv dal repository che avevo in locale, e poi installando il modulo in oggetto:
```
pip install -e /path/to/odoo  # oppure da https://github.com/odoo/odoo
pip3 install --pre odoo-addon-l10n-it-fatturapa
```
