### ISSUE TITLE
Odoo 16.0:  registrazione di riconciliazione autofattura con conto contabile non corretto

### ISSUE THREAD

**Issue by DA-amministrazione** [OCA/l10n-italy#3373]
## Module
ODOO V.16

## Describe the bug
Il registro della riconciliazione Reverse Charge è correttamente codificato (vedi documento allegato) ma quando viene generata la corrispondente auto-fattura la registrazione di riconciliazione prende un conto contabile indicato in impostazioni contabili nella sezione “Conti Predefiniti” nel campo “conto pagamenti in sospeso”.
Il problema sta nella quadratura del conto contabile “Transitorio auto-fatturazione” perché viene utilizzato solo nelle registrazioni contabili dell' auto-fattura (fattura attiva) mentre nelle altre registrazioni di riconciliazione non viene utilizzato ma prende quello indicato nella suddetta sezione “Conti Predefiniti” delle impostazioni generali della contabilità.

## To Reproduce
Affected versions:
16.0

1. Creare una fattura con fornitore soggetto a reverse charge
2. Validare il documento passivo, il sistema emette l'autofattura attiva e scrive in contabilità le registrazioni di riconciliazione dell'imposta passiva e del totale dell' autofattura.
3. Nel conto "Transitorio Autofatturazione" esiste solo la registrazione dell'imponibile dell'autofattura. Le registrazioni di riconciliazione contengono il conto "sospeso" configurato nella sezione "Conti predefiniti" delle impostazioni generali della contabilità 

**Expected behavior**
Le registrazionii di riconciliazione devono utilizzare il conto "transitorio autofatturazione" configurato nel registro di tipo banca "Riconciliazione Rc", che viene utilizzato nella configurazione dei "Tipi di inversione contabile"

[Anomalia_registrazioni_contabili_modulo_reverse_charge_in_ambiente.pdf](https://github.com/OCA/l10n-italy/files/11690300/Anomalia_registrazioni_contabili_modulo_reverse_charge_in_ambiente.pdf)

**Comment by marco-marchiori** [comment]
@DA-amministrazione 
Il registro con il quale storni l'importo dell'iva acquisti ed il saldo cliente è un registro bancario fittizio
è sufficiente impostare tutti i conti "outstanding" (nei tab pagamenti in entrata ed in uscita) con lo stesso conto che utilizzi come banca fittizia.
Prova e dovresti avere il conto che chiami "transitorio autofatturazione" pareggiato.

**Comment by DA-amministrazione** [comment]
Ciao Marco,
abbiamo seguito le tue indicazioni di configurazione dei registri di tipo banca, la questione è risolta. Purtroppo non vedevamo il campo "conto ricevute in sospeso" nella scheda dei pagamenti in entrata e in uscita, infatti andava abilitato tramite il bottone.
Grazie.
