### ISSUE TITLE
Odoo 16: modulo account_vat_period_end_statement errore di visualizzazione nella scheda conti

### ISSUE THREAD

**Issue by maxgrassi** [OCA/l10n-italy#3375]
Odoo 16
Modulo: account_vat_period_end_statement 
Problema: bug di visualizzazione nella scheda conti

Segnalo problema di visualizzazione nella scheda conti del modulo account_vat_period_end_statement di Odoo 16.

Testato su: https://runboat.odoo-community.org/webui/builds.html?repo=OCA/l10n-italy&target_branch=16.0

Riprodurre la problematica: Generare una liquidazione iva e spostarsi sulla scheda conti, compare una striscia bianca verticale in RIGHE CONTI DI CREDITO tra conto e imposta.

<img width="1241" alt="errore-di-visualizzazione" src="https://github.com/OCA/l10n-italy/assets/18476727/7fc82b23-0443-4a5e-95a3-bd19c34b878b">

**Comment by tafaRU** [comment]
Grazie della segnalazione :+1: 
Nota: è sufficiente aprire la issue senza riportare lo stesso commento su https://github.com/OCA/l10n-italy/issues/2967#issuecomment-1586246946

**Comment by marco-marchiori** [comment]
Sulla "contrapposizione" debito o credito non ci sono ovviamente prescrizioni di tipo grafico su come dev'essere una liquidazione.
Nel nostro caso esiste un aspetto di comodità di vedere ad esempio nelle RC la stessa IVA da una parte e da un'altra.
