### ISSUE TITLE
Prima riga Libro giornale non corretta per stampe suddivise

### ISSUE THREAD

**Issue by patrickt-oforce** [OCA/l10n-italy#3378]
## Module
l10n_it_central_journal

## Describe the bug
Quando si effettua una stampa del libro giornale suddivisa un più parti, impostando la riga iniziale nel wizard nella stampa la prima riga ha il numero successivo al valore impostato

## To Reproduce
**Affected versions**:
- [x] 14.0 #3379 
- [ ] 16.0

1. Effetture una stampa del libro giornale
2. Scegliere un periodo di tempo
3. Scegliere stampa definitiva
4. Una volta scaricato il PDF, selezionare un periodo successivo
5. Aggiornare i valori per pagina iniziale e riga di inizio
6. Ristampare il resoconto con stampa definitiva

Impostazione riga d'inizio
![L10N_ITALY__CENTRAL_JOURNAL_NO_FIX](https://github.com/OCA/l10n-italy/assets/93334962/7f49de59-6c0a-4081-b69b-e494f7b4a53d)

PDF ottenuto senza fix
![L10N_ITALY__CENTRAL_JOURNAL_PDF_NO_FIX](https://github.com/OCA/l10n-italy/assets/93334962/9f10b344-e219-4767-8814-2f020e4e0331)

PDF ottenuto con il fix
![L10N_ITALY__CENTRAL_JOURNAL_PDF_FIX](https://github.com/OCA/l10n-italy/assets/93334962/2b631a48-11db-4bb2-83b5-4393ea5a14f3)

**Expected behavior**
Alla stampa, la prima riga deve avere il valore impostato nel wizard

**Comment by SirAionTech** [comment]
Potrebbe essere https://github.com/OCA/l10n-italy/labels/good%20first%20issue?
