### ISSUE TITLE
[16.0] l10n_it_delivery_note riferimento DDT replicato in fattura

### ISSUE THREAD

**Issue by esafocus** [OCA/l10n-italy#3381]
## Module
l10n_it_delivery_note

## Describe the bug
In Odoo 16 il riferimento DDT nelle fattura e replicato per ogni riga

**Expected behavior**
Un solo riferimento al DDT posizionato all'inizio della fattura

**Comment by francesco-ooops** [comment]
Ciao @esafocus , riusciresti a fornire un video dell'errore sul runboat o i passi dettagliati per riprodurre?

Grazie!
