### ISSUE TITLE
l10n_it_fatturapa_out_rc: tipo di documento fiscale diverso da quello visibile a video se modificato dall'utente

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3382]
L'utente potrebbe aver modificato il tipo di documento fiscale, ma la fattura esportata risulterà sempre con il tipo impostato nella posizione fiscale della fattura di acquisto.

Si potrebbe quindi o impostare il campo in sola lettura, in questo caso, o prelevare il tipo di documento fiscale dalla fattura.

https://github.com/OCA/l10n-italy/blob/4aa0479ccea8daf3622907fdb24e38cbf5dcfe92/l10n_it_fatturapa_out_rc/views/invoice_it_template.xml#L36

**Comment by francesco-ooops** [comment]
@sergiocorato 14 e 16 giusto?
