### ISSUE TITLE
Se non è configurata la nazione nel partner l'esportazione non va a buon fine

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3397]
Qui viene dato per scontata la presenza della nazione, che però in caso di rappresentante legale (almeno) non viene controllato che sia stata impostata:

https://github.com/OCA/l10n-italy/blob/e59aec468d79ec66079ac0604d370324ce43bb93/l10n_it_fatturapa_out/wizard/efattura.py#L111

L'errore non è chiaro, vedasi questo thread sul forum: https://www.odoo-italia.org/forum/forum-1/question/reason-unexpected-child-with-tag-importototaledocumento-at-position-6-3310

Si potrebbe aggiungere un messaggio più esplicito.

- [ ] 14.0:
- [ ] 16.0: ?

**Comment by TheMule71** [comment]
magari in `preventive_checks()`
