### ISSUE TITLE
Importo resettato quando si cambia il sezionale nel wizard per la registrazione del pagamento 

### ISSUE THREAD

**Issue by mlk994** [OCA/l10n-italy#3401]
## Module
l10n_it_withholding_tax

## Describe the bug
Quando si vuole registrare un pagamento parziale per un importo diverso dall'importo della fattura e si cambia il sezionale l'importo del pagamento viene rimesso come il totale della fattura

## To Reproduce
**Affected versions**:
- [ ] 14.0 - #3400 
- [ ] 16.0

1. Aprire una fattura fornitore, confermarla se non lo è
2. Aprire il wizard per registrare il pagamento e cambiarne l'importo
3. Cambiare il valore del metodo di pagamento

**Expected behavior**
Quando si cambia il metodo di pagamento del wizard l'importo deve rimanere quello impostato

**Comment by mlk994** [comment]
PR per questa issue: #3400

**Comment by SirTakobi** [comment]
Il problema non è collegato al modulo delle ritenute **l10n_it_withholding_tax** ma è in Odoo: ho provato e si verifica anche in `16.0`

https://github.com/OCA/l10n-italy/assets/101628000/5c504592-d5f2-4835-acbf-115e452d17a5

Il link alla fattura prodotta è https://49264894-16-0-all.runbot162.odoo.com/web#cids=1&menu_id=321&action=479&model=account.move&view_type=form&id=31

**Comment by eLBati** [comment]
Secondo me il comportamento atteso di questa issue deve diventare "Quando si cambia il metodo di pagamento del wizard l'importo deve essere impostato con il Netto a pagare"

**Comment by eLBati** [comment]
Quindi chiuderei questa in favore della https://github.com/OCA/l10n-italy/issues/3533
