### ISSUE TITLE
account_vat_period_end_statement - unused CSS classes

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3403]
Nel file [l10n_it_vat_registries.css](https://github.com/OCA/l10n-italy/blob/e1cd1fb6596d7080152d6406111c5d2f716c348c/account_vat_period_end_statement/static/src/css/l10n_it_vat_registries.css)

Sono presenti una serie di classi CSS che non vengono utilizzate e non venivano importante fino alla PR: #3380 

Propongo di toglierli per evitare che vadano ad impattare da qualche altra parte. Inoltre, non venivano importati fino a poco fa e non mi pare aggiungano nulla a prescindere

Apro: 
- [x] https://github.com/OCA/l10n-italy/pull/3402 per la 16.0
- [ ] https://github.com/OCA/l10n-italy/pull/3733 per 14.0

**Comment by tafaRU** [comment]
Il nome del file non coerente con quello del modulo supporta la tesi che sia stato aggiunto per errore.

Inoltre, nel modulo di pertinenza, quel file `css` era presente in https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_vat_registries/static/src/css/l10n_it_vat_registries.css per poi essere stato eliminato nella migrazione alla `12.0` con https://github.com/OCA/l10n-italy/commit/8f618c6b7f7bc61a44b49157fd411a378cc79465#diff-8d11e66c11683c2f32e32676bec49718c322c1534733189b52f496b04f32a126

**Comment by michelerusti** [comment]
> @michelerusti vedo che lo stesso file è presente anche sulla `14.0`: https://github.com/OCA/l10n-italy/blob/69aafe8a6a2badea719250d9f9dd995f4a198789/account_vat_period_end_statement/static/src/css/l10n_it_vat_registries.css Puoi verificare se anche in questo caso le classi non vengono usate e pertanto il file può essere eliminato?
hai ragione, ho controllato e non vengono usati, ho aprerto #3733
