### ISSUE TITLE
[14.0] l10n_it_ricevute_bancarie: molte PR v12 non portate alla v14

### ISSUE THREAD

**Issue by aleuffre** [OCA/l10n-italy#3444]
Come da commento: https://github.com/OCA/l10n-italy/pull/2138#issuecomment-932013424

- [ ] https://github.com/OCA/l10n-italy/pull/2025
  - PR v14: https://github.com/OCA/l10n-italy/pull/3437
- [ ] https://github.com/OCA/l10n-italy/pull/2445
  - PR V14: in attesa di merge di PR v12

Inoltre le seguenti issue avevano il proprio issue originale
- [ ] https://github.com/OCA/l10n-italy/pull/2035
  - Issue di tracciamento originale: #2036 
- [ ] https://github.com/OCA/l10n-italy/pull/2119
  - Issue di tracciamento originale: #2118 

Una volta portate, assicurarsi che siano incluse anche nella migrazione a v16: https://github.com/OCA/l10n-italy/pull/3131

**Comment by aleuffre** [comment]
Rimosso alcune PR dal messaggio originale che in effetti erano state portate.

**Comment by francesco-ooops** [comment]
Chiudo perchè ogni PR ha la sua issue relativa
