### ISSUE TITLE
[14.0] l10n_it_account_stamp: mergiata PR #3442 con errori nei test

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#3456]
## Module
l10n_it_account_stamp

## Describe the bug
#3442
ha introdotto dei test che usano la classe `AccountingTestCase` che non esiste più.
Il test sono verdi nonostante l'errore di `import`.

## To Reproduce
**Affected versions**:
- [x] 14.0: #3455

**Comment by francesco-ooops** [comment]
@TheMule71 da risolvere per la 16? il test sembr
