### ISSUE TITLE
l10n_it_fatturapa_in: fare refactoring della parte relativa agli arrotondamenti

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#3461]
Il codice attuale interviene in più punti creando righe di arrotondamento che vengono ignorate da `_compute_amount()` che poi viene corretta a parte. Parte del codice è duplicato.

**Comment by patrickt-oforce** [comment]
@TheMule71 Riguardo 14.0 il metodo [_compute_amount](https://github.com/odoo/odoo/blob/14.0/addons/account/models/account_move.py#L1430) quando calcola i vari totali non tiene conto del tipo di riga come su 16.0, secondo me converrebbe a questo punto impostare a `True` il valore del flag per escludere la/e riga/he per gli arrotondamenti dalla vista delle righe fattura

**Comment by SirAionTech** [comment]
@TheMule71 riguardo gli arrotondamenti ho fatto https://github.com/OCA/l10n-italy/pull/3826, pensi ci sia altro da fare per questa issue?

**Comment by francesco-ooops** [comment]
@SirAionTech dunque questa sarebbe duplicata di https://github.com/OCA/l10n-italy/issues/3797 e https://github.com/OCA/l10n-italy/issues/3825 ?

**Comment by SirAionTech** [comment]
> @SirAionTech dunque questa sarebbe duplicata di #3797 e #3825 ?

non direi: questa issue è per migliorare alcune cose nella gestione degli arrotondamenti senza però cambiare il comportamento (refactoring), le altre issue linkate sono per correggere comportamenti specifici (bug).

In https://github.com/OCA/l10n-italy/pull/3826 ho modificato la gestione degli arrotondamenti correggendo gli errori descritti in https://github.com/OCA/l10n-italy/issues/3797 e https://github.com/OCA/l10n-italy/issues/3825; non so però se le modifiche della PR si possono considerare come i miglioramenti richiesti da questa issue, per questo ho chiesto all'autore della issue.
