### ISSUE TITLE
[RIBA][8.0] creazione insoluto

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#347]
capita con il wizard di creazione insoluto che venga fuori il seguente messaggio:

Journal Item '[numero fattura]' id: [xxxxx], Move '[numero registrazione]' is already reconciled!

il numero registrazione fa riferimento ad account_move relativo alla registrazione della distinta, ed è ovvio che sia riconciliato.

**Comment by scigghia** [comment]
commentando reconcile_partial alla riga 218 e 219 riesco a creare l'insoluto. 
In ogni caso la registrazione non mi sembra formalmente corretta, abbiamo un riferimento ?

**Comment by eLBati** [comment]
Ciao @scigghia puoi descrivere i passi per generare il problema su un nuovo DB, il risultato osservato ed il risultato atteso?

**Comment by scigghia** [comment]
Creo una distinta -> accredito distinta -> scelgo una scadenza ed attivo il wizard insoluto -> compilo gli importi e le spese e confermo la creazione della registrazione.
A questo punto compare l'errore ed è legato alla creazione della riconciliazione movimento appena creato.
Sostanzialmente si dovrebbe semplicemente creare la scrittura dell'insoluto senza fare la riconciliazione.

**Comment by scigghia** [comment]
Rivedendo le registrazioni che vengono create da wizard_unsolved.py, credo ci sia un errore di fondo perchè la view dovrebbe mostrare solo i conti relativi all'insoluto, mentre attualmente viene mostrato tutto quello che è presente nella configurazione riba. Capita quindi che il cliente conferma la registrazione trovandosi due volte l'importo in dare e due volte l'importo in avere, creando di fatto una registrazione non corretta, che dovrebbe essere "DARE effetti insoluti, AVERE cliente" (al netto delle spese)

**Comment by sergiocorato** [comment]
chiudo per inattività
