### ISSUE TITLE
[BUG] No scaricamento da server PEC a causa di XML problematico

### ISSUE THREAD

**Issue by filipposaviori** [OCA/l10n-italy#3481]
module: l10n_it_fatturapa_in
version: 14.0

**Steps to reproduce**
- Abbiamo un server PEC dedicato per il cliente con legalmail, ogni tanto (molto spesso) l'azione di caricamento PEC dal server si inceppa a causa di una mail PEC contenente un file XML.P7M che non riesce ad essere scaricato sul database Odoo, impedendo l'azione di ricezione di file e-fatture in ingresso.
- importando poi a mano la PEC bacata il sistema si sblocca e mi scarica nuovamente senza problemi tutte le restanti PEC in Odoo

**Expected behavior**
- Siccome per le altre PEC non ci son problemi, mi aspetto che vengano scaricate tutte allo stesso modo. 
- non è la prima volta che succede questo problema.

**Comment by matteoopenf** [comment]
vuoi proporre una pr?

**Comment by filipposaviori** [comment]
si va bene

**Comment by filipposaviori** [comment]
Mi serve indicazione di come fare però

**Comment by filipposaviori** [comment]
Ciao @francesco-ooops ,

ho provato a seguire le linee guida ma non sono riuscito a trovare l'iter per far diventare una Issue una Pull Request.

Ho letto che si dovrebbe creare in precedenza una branch dove sviluppare la PR, solo che da questa schermata:
![image](https://github.com/OCA/l10n-italy/assets/107557432/79405954-3f75-4b44-97f7-996ed98402d5)

non riesco a capire come andare avanti per avere quel bottone "create pull request" cliccabile.

Grazie mille per l'aiuto,
FS

**Comment by francesco-ooops** [comment]
> Se hai bisogno di assistenza puoi unirti al server discord qui: https://discord.gg/bcwxJafkXf

mi spiace ma non ho le competenze tecniche per risponderti, prova a scrivere sul canale #supporto

**Comment by tafaRU** [comment]
@filipposaviori hai provato a leggere https://www.odoo-italia.org/documentazione/14.0/sviluppo/come_contribuire.html?

**Comment by filipposaviori** [comment]
@tafaRU Grazied mille, provo a guardare allora questa guida.

se non riesco ancora, mi metterò in contatto su Discord.

Grazie mille,
FS

**Comment by filipposaviori** [comment]
La PR è stata creata correttamente con riferimento #3542.

Ci sono altre attività che posso svolgere oppure devo attendere che qualcuno controlli la PR e ne identifichi le cause?

Grazie,
FS
