### ISSUE TITLE
Duplicazione ritenute d'acconto se viene annullata la riconciliazione del pagamento

### ISSUE THREAD

**Issue by webcircles-davide** [OCA/l10n-italy#3489]
## Module
l10n_it_withholding_tax

## Describe the bug
In caso venga annullata la riconciliazione del pagamento su una fattura con ritenuta d'acconto e successivamente riassegnata, il modulo crea un nuovo account move (con le due linee di debito e credito) per la ritenuta d'acconto (per vedere l'elenco duplicato vanno annullate le riconciliazioni una seconda volta).
![Screenshot 2023-07-12 alle 10 36 28](https://github.com/OCA/l10n-italy/assets/9135478/5f0507d6-e840-4223-bf5d-5639d8baa1b3)
![Screenshot 2023-07-12 alle 10 36 41](https://github.com/OCA/l10n-italy/assets/9135478/309860f4-2b16-4b71-9bd7-880bd60efa6e)
![Screenshot 2023-07-12 alle 10 37 07](https://github.com/OCA/l10n-italy/assets/9135478/f9abaf10-ea6a-42d8-9835-09c77c0f4d28)
A seconda che venga anche annullata la riconciliazione della rda o meno, il comportamento è leggermente differente ma in ogni caso viene duplicata la parte di ritenuta d'acconto.
![Screenshot 2023-07-12 alle 10 43 24](https://github.com/OCA/l10n-italy/assets/9135478/e4ac04b9-b18c-4dfd-864d-b1825bfddc7a)
L'operazione può essere ripetuta più volte con conseguente creazione di nuovi duplicati per la parte di ritenuta d'acconto.

## To Reproduce
**Affected versions**:
14

1. creare fattura con voce di ritenuta d'acconto
2. confermare la fattura
3. registrare un pagamento
4. annullare la riconciliazione del pagamento (non voce rda)
5. associare nuovamente il pagamento visibile nel footer della fattura
6. ripetere l'operazione creerà ulteriori voci di rda

**Expected behavior**
Una volta generato l'account move per il pagamento della rda non deve essere duplicato

**Comment by webcircles-davide** [comment]
> Grazie della segnalazione! Potrebbe essere lo stesso problema descritto in #2938 ?

Si, sembra lo stesso problema generato riprodotto con un differente flusso

**Comment by SirTakobi** [comment]
> > Grazie della segnalazione! Potrebbe essere lo stesso problema descritto in #2938 ?
> 
> Si, sembra lo stesso problema riprodotto con un differente flusso

Hai modo di verificare se la soluzione #2939 proposta per #2938 risolve anche questo problema?

**Comment by francesco-ooops** [comment]
Chiudo in quanto duplicata di #2938
