### ISSUE TITLE
Fattura elettronica TD01 con totale negativo

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#3523]
## Module

l10n_it_fatturapa_in

## Describe the bug

In caso di ricezione di una fattura elettronica con "Tipologia documento: TD01" e "Totale imponibile/importo" negativo, viene creata una fattura passiva da pagare

## To Reproduce
**Affected versions**:

 - [ ] 14.0 : https://github.com/OCA/l10n-italy/pull/3751
 - [ ] 16.0 : https://github.com/OCA/l10n-italy/pull/4026

Steps to reproduce the behavior (v14):
1. Creare un Incoming E-bill Files con questo file https://gist.github.com/eLBati/e9aa39f32657a4a33a11ad1b638e6a75
2. Importare

Si ottiene
> L'importo espresso nella valuta secondaria deve essere positivo quando il conto è in addebito e negativo quando è in accredito. Se la valuta corrisponde a quella dell'azienda, questo importo deve essere rigorosamente uguale al saldo

**Expected behavior**

Nota di credito

**Note aggiuntive**

Su v12 la validazione viene bloccata con "Impossibile validare una fattura con un importo totale negativo. Creare invece una nota di credito"

**Comment by eLBati** [comment]
https://discord.com/channels/753902328494424064/753902328494424070/1146375041781612655

**Comment by eLBati** [comment]
Per la 14 al momento ho solo questa soluzione:

```
diff --git a/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py b/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
index 771141812..9b03fa35b 100644
--- a/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
+++ b/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py
@@ -1189,8 +1189,6 @@ class WizardImportFatturapa(models.TransientModel):
 
         self.set_vendor_bill_data(FatturaBody, invoice)
 
-        # this can happen with refunds with negative amounts
-        invoice.process_negative_lines()
         return invoice
 
     def set_vendor_bill_data(self, FatturaBody, invoice):
```

`+`

```
diff --git a/addons/account/models/account_move.py b/addons/account/models/account_move.py
index 498dc36a1193..5368c29d1d51 100644
--- a/addons/account/models/account_move.py
+++ b/addons/account/models/account_move.py
@@ -2728,9 +2728,6 @@ class AccountMove(models.Model):
                 elif move.is_purchase_document():
                     raise UserError(_("The field 'Vendor' is required, please complete it to validate the Vendor Bill."))
 
-            if move.is_invoice(include_receipts=True) and float_compare(move.amount_total, 0.0, precision_rounding=move.currency_id.rounding) < 0:
-                raise UserError(_("You cannot validate an invoice with a negative total amount. You should create a credit note instead. Use the action menu to transform it into a credit note or refund."))
-
             if move.line_ids.account_id.filtered(lambda account: account.deprecated):
                 raise UserError(_("A line of this move is using a deprecated account, you cannot post it."))
```

dove il secondo diff riguarda il modulo `account` e la possibilità di registrare fatture negative.

A questo vale la pena valutare un modulo OCA per permettere la registrazione di fatture negative?
Qualcuno ha già valutato le implicazioni?

**Comment by francesco-ooops** [comment]
@eLBati puoi aggiungere la PR https://github.com/OCA/l10n-italy/pull/3680 alla issue e rimuovere la casella per la 12 dato che non è più supportata?

**Comment by eLBati** [comment]
Rimuovo la https://github.com/OCA/l10n-italy/pull/3680 perchè questo problema si verifica anche senza installare `l10n_it_intrastat`

**Comment by eLBati** [comment]
Abbiamo aggiunto la fix per questo in https://github.com/OCA/l10n-italy/pull/3751 , visto che toccano le stesse cose
