### ISSUE TITLE
Non deve essere possibile creare o modificare i tipi di documento fiscale

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3532]
## Module
l10n_it_fiscal_document_type

## Describe the bug
I tipi di documento fiscale modificati dall'utente, poi non vengono più riconosciuti dalle fatture elettroniche in entrata/uscita.

## To Reproduce
**Affected versions**:
- [x] `12.0`: ~#2819~ 
              ~#3535~
              #3640
- [ ] `14.0`: sì
- [ ] `16.0`: sì

1. Creare un nuovo tipo di documento fiscale
2. Esportare una fattura elettronica contenente il nuovo tipo

**Expected behavior**
La fattura elettronica generata rispetta il suo XSD.

**Additional context**
Questa problematica è parte di https://github.com/OCA/l10n-italy/issues/2654.

**Comment by francesco-ooops** [comment]
@tafaRU puoi sostituire la PR per la 12 con https://github.com/OCA/l10n-italy/pull/3640 ?

**Comment by tafaRU** [comment]
> @tafaRU puoi sostituire la PR per la 12 con #3640 ?

done
