### ISSUE TITLE
Nelle fatture con ritenuta, resettare l'importo da pagare al netto da pagare residuo

### ISSUE THREAD

**Issue by SirTakobi** [OCA/l10n-italy#3533]
## Module
l10n_it_withholding_tax

## Describe the bug
Quando viene cambiato il registro, l'importo da pagare è il totale residuo della fattura (122).

## To Reproduce
**Affected versions**:
- [x] `14.0`: https://github.com/OCA/l10n-italy/pull/3534
- [ ] `16.0`: https://github.com/OCA/l10n-italy/pull/3986

1. Creare una fattura da 122 con ritenuta 20: il netto da pagare è 102
2. Iniziare la procedura di pagamento: propone 102
3. Modificare l'importo da pagare in 20
4. Modificare il registro di pagamento

**Expected behavior**
L'importo da pagare deve tornare ad essere il Netto da pagare (102).

**Additional context**
Normalmente ogni volta che viene cambiato il registro nella procedura di pagamento, l'importo da pagare viene resettato al totale da pagare per la fattura (per mantenere l'importo impostato vedi https://github.com/OCA/account-payment/pull/665).
Questo comportamento è da mantenere, ma nel caso delle fatture con ritenuta l'importo è diverso da quanto calcolato da Odoo.

Questa problematica è simile a https://github.com/OCA/l10n-italy/issues/3401, ma non è la stessa cosa perché in quel caso si vuole sempre mantenere l'importo impostato.

**Comment by francesco-ooops** [comment]
Chiudo a favore di https://github.com/OCA/l10n-italy/pull/3986
