### ISSUE TITLE
[l10n_it_split_payment] unbalanced lines when change fiscal position

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3546]
## Module
l10n_it_split_payment

## Describe the bug
CI siamo accorti che se una volta creata la fattura se si cambia la posizione fiscale, con una di tipo split payment le linee si sbilanciano come avveniva qui  https://github.com/OCA/l10n-italy/pull/2515
## To Reproduce
**Affected versions**:

- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/3548
- [ ] 16.0 ?

1. Creare una fattura con una posizione fiscale diversa da splitpyament
2. cambiare la posizione fiscale in split payment
3. Si ottiene lo sbilanciamento delle linee

**Expected behavior**
Le linee devono essere bilanciate

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Ho provato nel runboat di `14.0` e non riproduco il problema: 

https://github.com/OCA/l10n-italy/assets/143788994/f6012d9f-f6c7-4d77-a8c8-e3e7589864fa

Puoi verificare? Magari mi sono perso qualche passaggio?

La fattura generata nel video è http://oca-l10n-italy-14-0-24074c3762c5.runboat.odoo-community.org/web?#id=17&action=227&model=account.move&view_type=form&cids=1&menu_id=134.

**Comment by matteoopenf** [comment]
> Grazie della segnalazione! Ho provato nel runboat di `14.0` e non riproduco il problema:
> 
>  Accounting.Dashboard.-.Odoo.1.mp4 
> Puoi verificare? Magari mi sono perso qualche passaggio?
> 
> La fattura generata nel video è http://oca-l10n-italy-14-0-24074c3762c5.runboat.odoo-community.org/web?#id=17&action=227&model=account.move&view_type=form&cids=1&menu_id=134.

Ciao, a noi continua ad accadere senza la patch fatta.
Ora essendo passato tempo dal fix non ricordo, comunque non chiudete la issue cortesemente

**Comment by matteoopenf** [comment]
ci accadeva inoltre su piu' clienti, quindi non era un problema di moduli non aggiornati o simile

**Comment by francesco-ooops** [comment]
@matteoopenf ok, però quando potete cercate di riprodurla sul runboat così capiamo come procedere

**Comment by matteoopenf** [comment]
> @matteoopenf ok, però quando potete cercate di riprodurla sul runboat così capiamo come procedere

Noi l'errore lo abbiamo come posso arrivo su runboat.
Ora non vedo tutta questa fretta fin'ora nessuno ha dedicato tempo. C'è anche una vecchia issue simile che io ricordi, quindi non è così isolato il problema.
Comunque come posso ci torno sopra e vedo se c'è ancora o altro.

**Comment by theandryx** [comment]
Nella versione 16 crea la stessa problematica.
Al primo salvataggio bilancia correttamente.
Dopo aver salvato la fattura con split payment e provando ad aggiungere una nuova riga ( o toglierne una già esistente ) al salvataggio non riesce più a bilanciarla causando l'impossibilità di editare le fatture.

Controllando i commit sembrerebbe quasi che i fix applicati alla v14 non siano stati poi riportati nella v16

**Comment by matteoopenf** [comment]
sto riottenendo l'errore su 16 partendo dall'ordine di vendita, ora testo meglio, ma sembra che se si parte da un ordine con posizione fiscal split payment si crea una fattura con scritture sbilanciate e ti blocca
