### ISSUE TITLE
[l10n_it_central_journal_reportlab] - Migliorative al README

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3562]
A seguito della PR 
https://github.com/OCA/l10n-italy/pull/3002

come è stato fatto notare in [questo commento](https://github.com/OCA/l10n-italy/pull/3002#issuecomment-1709885254):

Nota a margine:

> il readme è piuttosto limitato.
Sarebbe da aggiungere l'indicazione che il file PDF generato dal modulo lo si trova in fondo alla form.
Inoltre, servirebbe spiegare la differenza tra STAMPA e STAMPA DEFINITIVA

- [ ]  v14: 
- [ ]  v16:

**Comment by francesco-ooops** [comment]
@marcelofrare @michelerusti è qualcosa su cui potreste proporre una PR? :)

**Comment by SirAionTech** [comment]
Come mai https://github.com/OCA/l10n-italy/labels/hotfix? Pensavo fosse solo per i bug

**Comment by tafaRU** [comment]
Viene usato anche per gli enhancement vedi: https://github.com/OCA/l10n-italy/issues?q=is%3Aopen+label%3Aenhancement+label%3Ahotfix

**Comment by SirAionTech** [comment]
> Viene usato anche per gli enhancement vedi: https://github.com/OCA/l10n-italy/issues?q=is%3Aopen+label%3Aenhancement+label%3Ahotfix

Grazie, pensavo avesse a che fare con i bug per
> A hotfix or quick-fix engineering update (QFE update) is a single, cumulative package that includes information (often in the form of one or more files) that is used to address a problem in a [software](https://en.wikipedia.org/wiki/Computer_software) product (i.e., a [software bug](https://en.wikipedia.org/wiki/Software_bug)).

(da https://en.wikipedia.org/wiki/Hotfix)

Allora cosa significa quando una issue è taggata con https://github.com/OCA/l10n-italy/labels/hotfix?

**Comment by francesco-ooops** [comment]
Sono d'accordo che si può chiarire, altrimenti finisce che perde di significato

**Comment by tafaRU** [comment]
> Non la userei ad esempio per una issue sulla documentazione

In questo caso avevo pensato di dare maggiore priorità alla issue a fronte di quanto indicato nel commento https://github.com/OCA/l10n-italy/pull/3002#issuecomment-1709885254.

L'accezione che avevamo pensato di dare alla label di https://github.com/OCA/l10n-italy/labels/hotfix è proprio questa: dare maggiore priorità alla risoluzione della issue a cui viene assegnata sia che si tratti di bug o di enhancement. Va da se che un bug è di solito più urgente di un enhancement.
