### ISSUE TITLE
errore calcolo product_qty di delivery_note su odoo 16 community

### ISSUE THREAD

**Issue by ventre** [OCA/l10n-italy#3570]
Ho notato che se gli ordini di vendita generano dei backorder il calcolo di product_qty in questa funzione del modello stock_delivery_note_line sul modulo
l10n_it_delivery_note versione 16.0.1.0.3  :

@api.model
    **def _prepare_detail_lines(self, moves):**
        lines = []
        for move in moves:

            name = move.product_id.name
            if move.product_id.description_sale:
                name += "\n" + move.product_id.description_sale

            line = {
                "move_id": move.id,
                "name": name,
                "product_id": move.product_id.id,
                **"product_qty": move.product_uom_qty,**
                "product_uom_id": move.product_uom.id,
            }

            if move.sale_line_id:
                order_line = move.sale_line_id
                order = order_line.order_id

                line["price_unit"] = order_line.price_unit
                line["currency_id"] = order.currency_id.id
                line["discount"] = order_line.discount
                line["tax_ids"] = [(6, False, order_line.tax_id.ids)]
                line["invoice_status"] = DOMAIN_INVOICE_STATUSES[1]

            lines.append(line)

        return lines
 
Non ne tiene conto e secondo me 

**product_qty dovrebbe essere uguale a move.quantity_done**

infatit stampando un ddt le quantità non sono quelle di **move.quantity_done** ma dell'ordine originario ossia **move.product_uom_qty**

- [x] 14.0 #3862 
- [x] 16.0 #3845

**Comment by francesco-ooops** [comment]
Ciao @ventre , grazie della segnalazione!

Potresti aprire una PR per verificare come risolvere?

**Comment by francescapenso** [comment]
Solo per completezza lo stesso errore si verifica anche in enterprise 16

**Comment by francescapenso** [comment]
io ho provato e funziona qui il file che ho modificato alla riga 125 
https://github.com/francescapenso/l10n-italy/blob/16.0/l10n_it_delivery_note/models/stock_delivery_note_line.py

**Comment by andreampiovesana** [comment]
per odoo 14?

**Comment by francesco-ooops** [comment]
@andreampiovesana sì, quando si linka la PR alla issue si chiude automaticamente al merge (anche se ci sono altre task aperte), non ho capito bene come gestirla se non standoci dietro

stiamo facendo il backporting cmq

**Comment by SirAionTech** [comment]
> non ho capito bene come gestirla

Che io sappia non è gestito chiudere una issue quando **tutte** le PR collegate vengono mergiate: se una PR è collegata e viene mergiata allora chiude tutte le issues collegate.

O le colleghi e riapri la issue se c'è ancora qualcosa da fare,
o non le colleghi e chiudi la issue a mano quando tutte le PR elencate sono mergiate.

Una buona soluzione ibrida potrebbe essere che le colleghi solo quando è rimasta solo una PR aperta nella issue.

**Comment by francesco-ooops** [comment]
Il problema è che la maggior parte delle volte prima di aprire la PR per l'altra versione dobbiamo mergiare quella esistente, per ora credo che cerco di starci dietro io
