### ISSUE TITLE
Migrazione con OpenUpgrade di moduli presenti in apriori non funzionante

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3574]
Questo codice viene richiamato sempre da OpenUpgrade per eseguire la migrazione:

https://github.com/OCA/l10n-italy/blob/8a18ee5c3aaa3d23146012918c55f3f010f1616e/l10n_it_appointment_code/migrations/14.0.1.0.0/pre-migrate.py#L11

per cui nel caso in cui il modulo sia già stato rinominato tramite l'inserimento nel file `apriori.py` in 

https://github.com/OCA/OpenUpgrade/blob/11000ece9ea3254deea8f20aaf526b94ed95d439/openupgrade_scripts/apriori.py#L66

non viene più eseguita la funzione

https://github.com/OCA/l10n-italy/blob/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_appointment_code/hooks.py#L9 

in quanto non risulta più installato.

Per utilizzare `apriori.py` serve quindi bypassare il controllo sullo stato di installazione del modulo e poi evitare eventualmente di eseguire la rinomina del modulo, già fatta.

Affected versions:
- [x] 14.0

Moduli da correggere:
- [x] l10n_it_payment_reason #3604 
- [x] l10n_it_appointment_code #3598 
- [x] l10n_it_withholding_tax_reason https://github.com/OCA/l10n-italy/pull/3495

**Comment by SirAionTech** [comment]
Puoi seguire la struttura di https://github.com/OCA/l10n-italy/tree/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_financial_statements_report: il metodo che esegue la migrazione è `migrate_old_module`.
Nel hook di installazione c'è rinomina + migrazione, se il vecchio modulo è installato:
https://github.com/OCA/l10n-italy/blob/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_financial_statements_report/hooks.py#L123-L132
mentre nella migrazione c'è la chiamata diretta al metodo perché il modulo è stato rinominato da https://github.com/OCA/OpenUpgrade/blob/11000ece9ea3254deea8f20aaf526b94ed95d439/openupgrade_scripts/apriori.py#L64C19-L64C19: https://github.com/OCA/l10n-italy/blob/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_financial_statements_report/migrations/14.0.1.0.0/pre-migrate.py#L7-L9

**Comment by sergiocorato** [comment]
> Puoi seguire la struttura di https://github.com/OCA/l10n-italy/tree/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_financial_statements_report: il metodo che esegue la migrazione è `migrate_old_module`. Nel hook di installazione c'è rinomina + migrazione, se il vecchio modulo è installato:
> 
> https://github.com/OCA/l10n-italy/blob/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_financial_statements_report/hooks.py#L123-L132
> 
> mentre nella migrazione c'è la chiamata diretta al metodo perché il modulo è stato rinominato da https://github.com/OCA/OpenUpgrade/blob/11000ece9ea3254deea8f20aaf526b94ed95d439/openupgrade_scripts/apriori.py#L64C19-L64C19:
> 
> https://github.com/OCA/l10n-italy/blob/2d6bbe27311c876c290d83adf15c8c46bcecd21c/l10n_it_financial_statements_report/migrations/14.0.1.0.0/pre-migrate.py#L7-L9

Ottimo, faccio così allora.

**Comment by sergiocorato** [comment]
> Ottimo, faccio così allora.

Grazie.

**Comment by SirAionTech** [comment]
Ho riportato la struttura descritta in https://github.com/OCA/l10n-italy/issues/3574#issuecomment-1719725803 su https://github.com/OCA/l10n-italy/wiki/Migrazione-con-rinomina-modulo,-compatibile-con-OpenUpgrade-e-Odoo-SA.

**Comment by francesco-ooops** [comment]
@sergiocorato @SirAionTech c'è altro da fare in questa issue o chiudiamo?

**Comment by SirAionTech** [comment]
> @sergiocorato @SirAionTech c'è altro da fare in questa issue o chiudiamo?

Non lo so, io ho solo suggerito un modo per risolvere.
@sergiocorato ho trovato https://github.com/OCA/l10n-italy/pull/3598 che forse è per risolvere questa issue, ce ne sono altre?

**Comment by sergiocorato** [comment]
> > @sergiocorato @SirAionTech c'è altro da fare in questa issue o chiudiamo?
> 
> Non lo so, io ho solo suggerito un modo per risolvere. @sergiocorato ho trovato #3598 che forse è per risolvere questa issue, ce ne sono altre?

Si può chiudere, ho aggiornato la descrizione.
