### ISSUE TITLE
Rinomina xmlids in migrazione 14.0 l10n_it_financial_statements_report

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3575]
Qui non ci va `OLD_MODULE_NAME`?

https://github.com/OCA/l10n-italy/blob/1194fb209a8f97410cbe780251de72637dde7d0d/l10n_it_financial_statements_report/hooks.py#L112

**Comment by SirAionTech** [comment]
Sì, vedi https://github.com/OCA/l10n-italy/pull/3576.

**Comment by sergiocorato** [comment]
> ~Sì, vedi #3576.~
> 
> Sembrava troppo semplice.. Quando si accede a questo metodo, il modulo è già stato rinominato quindi il nome è già quello nuovo. Quindi no.

Quindi se non ho capito male, con la funzione https://github.com/OCA/openupgradelib/blob/d0aee908031876a95dc36c7a9a2c847186155aa2/openupgradelib/openupgrade.py#L1718 (richiamata da `pre_absorb_old_module` o da  `apriori.py`):
1. viene fatta la rinomina del modulo
2. vengono rinominati gli xmlids da `nome_vecchio_modulo.nome_vecchio_xmlid` a `nome_nuovo_modulo.nome_vecchio_xmlid` > serve quindi eseguire la rinomina al `nome_nuovo_modulo.nome_nuovo_xmlid` se è cambiato
3. vengono rinominate le tabelle e i campi > serve rinominare i campi se cambiati 
4. vengono rinominate le traduzioni

**Comment by SirAionTech** [comment]
Non conosco nel dettaglio tutto quello che fa `update_module_names`, ma mi aspetto che ogni riferimento a `nome_vecchio_modulo` venga sostituito con `nome_nuovo_modulo`.

Quindi se `nome_vecchio_xmlid` è diverso da `nome_nuovo_xmlid`, allora sì serve eseguire la rinomina da `nome_nuovo_modulo.nome_vecchio_xmlid` a `nome_nuovo_modulo.nome_nuovo_xmlid`.

**Comment by sergiocorato** [comment]
Ok, mi pare logico, anche se non scontato.

**Comment by SirAionTech** [comment]
> Ok, mi pare logico, anche se non scontato.

Puoi aggiungere un commento per chiarire.

**Comment by sergiocorato** [comment]
Si certo, chiudo.
