### ISSUE TITLE
l10n_it_fatturapa_in controllo su e-fatture ricevute per campo riferimento di pagamento ..

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3578]
..uguale a numero fattura fornitore. È necessario che sia per forza uguale o si può rimuovere questo avviso?

https://github.com/OCA/l10n-italy/blob/a48f4133ffccb989a49a3a716aa5ea3078c943dd/l10n_it_fatturapa_in/models/account.py#L219..L232

Affected versions:
- [x] 12.0: n.a.
- [ ] 14.0: #3579 
- [ ] 16.0:

**Comment by matteoopenf** [comment]
io direi di lasciare il messaggio, essendo che quando mettono gli arrotondamenti poi e' difficile che porta e  pero' va notata la cosa da parte del cliente, perche' a volte saranno centesimi in piu' a volte in meno

**Comment by sergiocorato** [comment]
> io direi di lasciare il messaggio, essendo che quando mettono gli arrotondamenti poi e' difficile che porta e pero' va notata la cosa da parte del cliente, perche' a volte saranno centesimi in piu' a volte in meno

Mmm, mi riferisco all'avviso per cui il riferimento fattura fornitore non corrisponde al numero fattura fornitore, non a campi numerici.

**Comment by sergiocorato** [comment]
> io direi di lasciare il messaggio, essendo che quando mettono gli arrotondamenti poi e' difficile che porta e pero' va notata la cosa da parte del cliente, perche' a volte saranno centesimi in piu' a volte in meno

Così per capirci: #3579

**Comment by matteoopenf** [comment]
> > io direi di lasciare il messaggio, essendo che quando mettono gli arrotondamenti poi e' difficile che porta e pero' va notata la cosa da parte del cliente, perche' a volte saranno centesimi in piu' a volte in meno
> 
> Così per capirci: #3579

Ciao @sergiocorato  scusa non mi 'e chiaro.
Ma cosi non scompare l'alert?
L'utente cosi se non fa un check anche lui dell'xml non si accorge della differenza o sbaglio a intuire lo scopo della tua modifica?
