### ISSUE TITLE
[l10n_it_reverse_charge] movimento contabile errato in caso di abbuoni

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3581]
## Module
l10n_it_reverse_charge

## Describe the bug
abbiamo riscontrato che ll modulo l10n_it_reverse_charge in caso che su una fattura ci siano abbuoni il movimento contabile risulta errato, abbiamo inoltre visto che appare da dopo il merge di questa PR https://github.com/OCA/l10n-italy/pull/3287

## To Reproduce
**Affected versions**:

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/3582
- [x] 16.0 #3906 

1. Creare una fattura  che sia soggetta ad Intra extra UE
2. Aggiungere una riga di Abbuono 
3. il movimento risultera' errato

il problema avviene quando viene creato il giroconto.
Questo deve avere 2 righe per stornare l'IVA aggiunta alla fattura fornitore e 2 righe per stornare l'autofattura.
I valori da mettere nelle seconde 2 righe per stornare l'autofattura prendono il valore dalla prima riga che ha il movimento in DARE, senza controllare la natura del conto presente in quella riga. Ovvero se è di tipo credito.

Ora se nella fattura fornitore è presente una riga con valore negativo, come ad esempio un abbuono attivo, questo verrà riportato nell'autofattura con il valore in dare.

La versione attuale del modulo, nel reperire il valore dell'autofattura da mettere nel giroconto prende erroneamente il valore dell'abbuono anzichè quello del credito provocando la mancata chiusura del conto transitorio usato per l'inversione contabile.

**Expected behavior**
il movimento deve essere esatto, piu' segnatamente il giro conto

**Additional context**
[Add any other context about the problem here. (e.g. OS, Python version, ...)](https://github.com/OCA/l10n-italy/issues/3581#issuecomment-1749325559)

**Comment by eLBati** [comment]
> il movimento deve essere esatto

Puoi scrivere come dovrebbe essere fatto il movimento contabile?

"il movimento deve essere esatto" nel comportamento atteso mi suona come "il comportmento deve essere quello atteso" :smiley:

**Comment by matteoopenf** [comment]
Buonasera,Domani vedo di migliorare la spiegazione 🙃Matteo ***@***.*** Il giorno 4 ott 2023, alle ore 19:54, Lorenzo Battistini ***@***.***> ha scritto:﻿

il movimento deve essere esatto

Puoi scrivere come dovrebbe essere fatto il movimento contabile?
"il movimento deve essere esatto" nel comportamento atteso mi suona come "il comportmento deve essere quello atteso" 😃

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano

**Comment by alessandrocamilli** [comment]
Buonasera @eLBati ,
il problema avviene quando viene creato il giroconto.
Questo deve avere 2 righe per stornare l'IVA aggiunta alla fattura fornitore e 2 righe per stornare l'autofattura.
I valori da mettere nelle seconde 2 righe per stornare l'autofattura prendono il valore dalla prima riga che ha il movimento in DARE, senza controllare la natura del conto presente in quella riga. Ovvero se è di tipo credito.

Ora se nella fattura fornitore è presente una riga con valore negativo, come ad esempio un abbuono attivo, questo verrà riportato nell'autofattura con il valore in dare.

La versione attuale del modulo, nel reperire il valore dell'autofattura da mettere nel giroconto prende erroneamente il valore dell'abbuono anzichè quello del credito provocando la mancata chiusura del conto transitorio usato per l'inversione contabile.

Spero sia tutto chiaro

@matteoopenf puoi integrarlo nella issue? grazie mille

**Comment by matteoopenf** [comment]
@eLBati  aggiornata la issue

**Comment by matteoopenf** [comment]
@eLBati ci siamo ora?

**Comment by matteoopenf** [comment]
@eLBati  ci siamo?

**Comment by andreampiovesana** [comment]
@matteoopenf puoi fare PR anche per la 16?
