### ISSUE TITLE
[l10n_it_declaration_of_intent] Impossibile registrare pagamento fattura con dichiarazione d'intento

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#3586]
## Module
l10n_it_declaration_of_intent

## Describe the bug
Impostando una fattura con DI, quando cerco di registrare il pagamento viene generato il seguente errore:

![image](https://github.com/OCA/l10n-italy/assets/25057933/bd4cda3f-06f6-4163-a279-44e5dc4a3463)

## To Reproduce
**Affected versions**:
- [ ] 16.0 #3603
- [ ] 14.0 #3605

1. impostare una lettera d'intento
2. validare una fattura che utilizza la DI
3. registrare il pagamento

**Expected behavior**
Dovrebbe concludere il pagamento regolarmente come avviene nelle versioni precedenti

**Comment by matteoopenf** [comment]
Sia fattura cliente che fornitore? O solo cliente?

**Comment by marcelofrare** [comment]
> Sia fattura cliente che fornitore? O solo cliente?

al momento ho provato solo con fatture clienti, appena posso faccio anche con le fatture fornitori

**Comment by andreampiovesana** [comment]
Perchè quando pago nella v 16 esce il messaggio?

**Comment by TheMule71** [comment]
Da capire perché non arriva al continue a riga 100.

**Comment by TheMule71** [comment]
@marcelofrare @andreampiovesana avete modo di provare se le PR risolvono?

**Comment by marcelofrare** [comment]
> @marcelofrare @andreampiovesana avete modo di provare se le PR risolvono?

confermo che funziona sia su 14 che 16
Grazie Marco!
