### ISSUE TITLE
[14.0] l10n_it_website_sale_fiscalcode: missing check_fiscalcode() call

### ISSUE THREAD

**Issue by FrancescoBallerini** [OCA/l10n-italy#3588]
## Affected version

- [x] 14.0 #3592 
- [x] 16.0 da gestire in eventuale migrazione

## Steps to reproduce  

- registrare un contatto sul website 
- impostare il company_type a company e/o il company_name
- aggiungere un prodotto al carrello
- nella fase di checkout inserire un fiscalcode che abbia un numero di cifre diverso da 16

## Current Behaviour:

Si riceve il messaggio "Il codice fiscale non risulta corretto"

## Expected Behaviour:

L'errore dovrebbe tenere conto del `company_name` e del `company_type`, possibilmente chiamando il metodo specifico [check_fiscalcode](https://github.com/OCA/l10n-italy/14.0/l10n_it_fiscalcode/model/res_partner.py#L11) e non visualizzare l'errore in questo caso.

NB: la chiamata a `check_fiscalcode` dev'essere valutata tramite try/except. Se valutato tramite valore ritornato (come accade in [v12](https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_website_sale_fiscalcode/controllers/main.py#L28)) nella v14.0 avviene un redirect che porta l'utente fuori dal form (vedi issue description).

## Issue description

Da [#3209 ](https://github.com/OCA/l10n-italy/pull/3209/files) a [#3214 ](https://github.com/OCA/l10n-italy/pull/3214/files) è stato modificato il check sul fiscalcode rimuovendo la call al constrains [check_fiscalcode](https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fiscalcode/model/res_partner.py#L10-L27) .

Intuisco sia stato fatto perché portando il codice della 12 sulla 14, invece che ricevere il warning in alto nel form, si riceve un redirect all'errore dato dal constrains come da screenshot:

![image](https://github.com/OCA/l10n-italy/assets/103839892/4e4b1c68-209c-46fb-b086-59b281f32fca)

Chiedo conferma di questo anche a @baba75, intuisco inoltre che lo stesso inconveniente dev'essersi verificato quando fu migrato `l10n_it_website_sale_portal` dalla 12 alla 14, perché sulla 14 il check viene fatto valutando l'eccezione invece del boolean.

https://github.com/OCA/l10n-italy/blob/13c7bb35aa3a61e6a80ffcaba35c2c21351b8ddd/l10n_it_website_portal_fiscalcode/controllers/main.py#L37-L41

Ciò ripristina il comportamento corretto mantenendo il riferimento al constrains
Propongo quindi di portare lo stesso sistema anche su `l10n_it_website_sale_fiscalcode` .

**Comment by baba75** [comment]
@FrancescoBallerini confermo era proprio quello il problema.

**Comment by FrancescoBallerini** [comment]
@baba75 Ho proposto una PR ma penso ci sia la parte dei test da coprire, su cui al momento non sono pratico, posso fare un tentativo nei prossimi giorni .. intanto ti ringrazio per il feedback !

**Comment by eLBati** [comment]
@FrancescoBallerini quali sono i passi per riprodurre il problema?

**Comment by FrancescoBallerini** [comment]
> @FrancescoBallerini quali sono i passi per riprodurre il problema?

In teoria lo "steps to reproduce" sarebbe:

- registrare un contatto sul website (dev'essere un type="person" senza "company_name" altrimenti questo [ValidationError](https://github.com/OCA/l10n-italy/blob/13c7bb35aa3a61e6a80ffcaba35c2c21351b8ddd/l10n_it_fiscalcode/model/res_partner.py#L26) non scatta)

- dalla pagina indirizzo di fatturazione del checkout, inserire un fiscalcode che abbia un numero di cifre diverso da 16

Ma non riuscirai a riprodurlo su runbot in quanto lato GUI non si notano problemi a meno di sapere cosa fa il check: attualmente nel Controller viene eseguito un check statico per valutare che `fiscalcode != 16` bypassando la call al metodo completo, che controlla anche il type e il company_name. 

Ho proposto di chiamare il metodo MA è importante valutare l'errore con il try/except (invece che valutare il valore ritornato dal metodo come viene fatto nella [versione 12](https://github.com/OCA/l10n-italy/blob/8dd3107eb13cc549662b67dc6705ad3adccc348e/l10n_it_website_sale_fiscalcode/controllers/main.py#L28)).

Questa cosa infatti pare non dia problemi sulla v12, ma sulla v14 causa un redirect che ti manda fuori dal form (vedi screenshot) invece che mostrare l'errore nel form stesso.

Il problema dunque lo otterresti eseguendo i passi descritti ma soltanto dopo aver eseguito il controllo come nella v12, cioè senza try/except.

**Comment by FrancescoBallerini** [comment]
@eLBati Ora che ci penso uno steps to reproduce potrebbe essere:

- registrare un contatto sul website 
- impostare il company_type a company e/o il company_name
- nella fase di checkout inserire un fiscalcode che abbia un numero di cifre diverso da 16

Current Behaviour:

Si riceve il messaggio "Il codice fiscale non risulta corretto"

Expected Behaviour:

L'errore dovrebbe tenere conto del "company_name" e del "company_type" chiamando quindi il metodo check fiscalcode.

Lo aggiungo alla descrizione.
