### ISSUE TITLE
Missing name in pages in account_view.xml (but also maybe in other views)

### ISSUE THREAD

**Issue by cstevanatonehos** [OCA/l10n-italy#3608]
**Is your feature request related to a problem?**
If I want to override the content inside the notebook's pages here
https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_out/views/account_view.xml
I can't because I am missing the name property

**Describe the solution you'd like**
I would like to have a name attribute for these pages, and maybe a check should be done on other modules/views too.

**Describe alternatives you've considered**
Using index, but it does not work since there are also hidden pages that are not precise as name is.

**Comment by SirAionTech** [comment]
Other (in my opinion, better) alternatives than using index:

- Using **ancestor**, see how in https://www.w3schools.com/xml/xpath_axes.asp, in your case it would be something like
  ```
  <xpath expr="//field[@name='fatturapa_attachment_out_id']/ancestor::page" position=...
  ```
- Using **..**, see how in https://www.w3schools.com/xml/xpath_syntax.asp, in your case it would be something like
  ```
  <xpath expr="//field[@name='fatturapa_attachment_out_id']/../.." position=...
  ```

This said, I agree that having `name` in the pages would be better
