### ISSUE TITLE
[l10n_it_fatturapa_in] gestione scadenze multiple fattura fornitore

### ISSUE THREAD

**Issue by marcelofrare** [OCA/l10n-italy#3618]
**Scadenze multiple sulla stessa fattura**
Importando una fattura elettronica fornitore contente più scadenze di pagamento, viene generato solo una scadenza con l'ultima data di scadenza

**Desiderato**
Sarebbe corretto creare più scadenze, con data e importo come indicato sulla FE

![image](https://github.com/OCA/l10n-italy/assets/25057933/24a7b1e3-c154-4d9e-b3e6-05328589fbd3)

**Allegato**
esempio file xml con scadenze multipli
[IT04980380267_00KL8.xml.zip](https://github.com/OCA/l10n-italy/files/12764034/IT04980380267_00KL8.xml.zip)

**Comment by danall59** [comment]
Marcelo,
hai avuto qualche riscontro per questa tua issue?
Non abbiamo lo stesso problema (un cliente Odoo14 si sta lamentando molto) e al momento l'unico modo per ovviare è assegnare a mano un "Termine di pagamento" alla fattura passiva.
Erano state fatte delle supposizioni su come migliorare il codice ?

**Comment by danall59** [comment]
Ho visto ora che c'è una PR aperta che si avvicina a questo problema: https://github.com/OCA/l10n-italy/pull/2759
