### ISSUE TITLE
l10n_it_fatturapa_in: serve l'appartenenza al gruppo amministratore/impostazioni per leggere i file xml(attachment)

### ISSUE THREAD

**Issue by ventre** [OCA/l10n-italy#3623]
## Module
l10n_it_fatturapa_in

## Describe the bug
serve l'appartenenza al gruppo amministratore/impostazioni per leggere i file xml(attachment)
altrimenti all'apertura della vista ad albero dei file xml importati ottengo il seguente errore:
Sorry, you are not allowed to access this document.

facendo debug succede perchè ir_attachment riga 456 ci sta questo controllo :

  if not self.env.is_system() and (res_field or (not res_id and create_uid != self.env.uid)):
                    raise AccessError(_("Sorry, you are not allowed to access this document."))

- [ ] 14.0: https://github.com/OCA/l10n-italy/pull/4194
- [ ] 16.0: https://github.com/OCA/l10n-italy/pull/4107

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Aggiungo che è un problema analogo a https://github.com/OCA/l10n-italy/issues/3336, ma per **l10n_it_fatturapa_in**.

**Comment by eLBati** [comment]
Propongo questa soluzione: https://github.com/OCA/l10n-italy/pull/3827
