### ISSUE TITLE
Filtraggio picking e pulsate `Crea DdT` in modulo `l10n_it_delivery_note_batch`

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#3639]
Nella funzione `create_delivery_notes` sostituire la search dei picking 
```
pickings = rec.mapped("picking_ids").search(
    [("delivery_note_id", "=", False), ("batch_id", "=", rec.id)]
)
```

con

```
pickings = rec.picking_ids.filtered(lambda p: not p.delivery_note_id)
```

----------------------------------------------------

Pulsante `Crea DdT` in batch dovrebbe essere nasconto se tutti i picking hanno un DdT abbianato oppure inserire un `raise UserError` dopo aver popolato la variabile `pickings` nella funzione `create_delivery_notes` per segnalare che tutti i picking hanno già un proprio DdT allegato

- [ ] v14: #3821 
- [ ] v16: https://github.com/OCA/l10n-italy/pull/3980

**Comment by aleuffre** [comment]
È un po' fuorviante avere per la v 16.0 il link a #3636 , considerato che non risolve il problema, ma è solo la PR di migrazione del modulo a v16.

**Comment by francesco-ooops** [comment]
@aleuffre intendi che il problema è ancora presente in v16?

**Comment by aleuffre** [comment]
Non l'ho provato, ma quanto meno guardando il codice, la modifica proposta da @Borruso non c'è su V16

**Comment by francesco-ooops** [comment]
ok per ora la rimuovo, @Borruso quando puoi verifichi? (avevi linkato te la PR di migrazione)

**Comment by Borruso** [comment]
l'avevo proposta in v16 ma in fare di migrazione non è stata fatta ma creata questa issue per farla dopo migrazione
