### ISSUE TITLE
aggiungere totale fatture in tree e-fattura fornitore

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#3645]
- [x] v16: #3602
- [x] v14: https://github.com/OCA/l10n-italy/pull/3740
- [ ] v12:

**Comment by SirAionTech** [comment]
@OCA/local-italy-maintainers qui manca solo il porting a `14.0`, direi che è una buona https://github.com/OCA/l10n-italy/labels/good%20first%20issue

**Comment by francesco-ooops** [comment]
@SirAionTech penso sia https://github.com/OCA/l10n-italy/pull/3740

e che questa issue sia stata duplicata in https://github.com/OCA/l10n-italy/issues/3741

Questa situazione si crea perchè si fa la PR prima della issue, e poi c'è qualcuno che deve fare il triage per rimettere insieme PR e issue e porting vari... non mi pare ideale

penso possiamo migliorare nel fare le cose più ordinatamente, dato che qualsiasi PR qui dentro è da fare in doppia versione, la issue dovrebbe essere obbligatoria e non opzionale a mio parere

**Comment by SirAionTech** [comment]
> @SirAionTech penso sia #3740
> 
> e che questa issue sia stata duplicata in #3741

Giusto, peccato poteva essere una modifica semplice per qualche newbie.

@Borruso puoi aggiungere in descrizione che per `16.0` c'è https://github.com/OCA/l10n-italy/pull/3740 e chiudere?

> Questa situazione si crea perchè si fa la PR prima della issue, e poi c'è qualcuno che deve fare il triage per rimettere insieme PR e issue e porting vari... non mi pare ideale
> 
> penso possiamo migliorare nel fare le cose più ordinatamente, dato che qualsiasi PR qui dentro è da fare in doppia versione, la issue dovrebbe essere obbligatoria e non opzionale a mio parere

Eh questo è tutto un altro discorso :smile:
