### ISSUE TITLE
16.0: correggere x2m fields problematici con tag group

### ISSUE THREAD

**Issue by FrancescoBallerini** [OCA/l10n-italy#3646]
Pare che sulla v16 I campi one2many (many2many non verificato) a cui si aggiunge l'attributo `nolabel="1"` vadano posizionati fuori da un `<group>`  altrimenti si rompe la width mostrando il campo come da screenshot.

![267708993-fe2eef4e-a61c-48db-ba59-0af111faa8ef](https://github.com/OCA/l10n-italy/assets/103839892/797e6af4-1ca8-432e-ab47-97ed4d9011d9)

Apro questa issue di tracciamento sulla base di https://github.com/OCA/l10n-italy/issues/3573 , infatti durante il controllo sono stati rilevati campi problematici presenti su più viste oltre a quella indicata (vedi https://github.com/OCA/l10n-italy/issues/3573#issuecomment-1729651189).

ToDo list per i campi da correggere

- [x] 16.0: https://github.com/OCA/l10n-italy/pull/3647
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/3653
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/3654

**Comment by FrancescoBallerini** [comment]
Fatto, `related_documents` e `fatturapa_doc_attachments` forse potevano andare nella stessa PR poiché fanno parte della stessa view, nel dubbio li ho splittati in due PR.

**Comment by OpenCode** [comment]
@FrancescoBallerini Quanto detto qui https://github.com/OCA/l10n-italy/issues/3573 è già coperto o va aggiunto un ulteriore punto?

**Comment by FrancescoBallerini** [comment]
> @FrancescoBallerini Quanto detto qui #3573 è già coperto o va aggiunto un ulteriore punto?

Tutto coperto: oltre al one2many per cui era stata aperta la issue ne avevo identificati altri 2. Sono stati corretti tutti e 3 (una PR per ognuno, vedi todo list) e al momento non mi risulta ce ne siano altri da correggere.

**Comment by OpenCode** [comment]
> > @FrancescoBallerini Quanto detto qui #3573 è già coperto o va aggiunto un ulteriore punto?
> 
> Tutto coperto: oltre al one2many per cui era stata aperta la issue ne avevo identificati altri 2. Sono stati corretti tutti e 3 (una PR per ognuno, vedi todo list) e al momento non mi risulta ce ne siano altri da correggere.

Perfetto. Allora chiudo la issue poiché è risolta. Se nasceranno nuove esigenze la possiamo riaprire.
Grazie mille.
