### ISSUE TITLE
[l10n_fatturapa_out] | Errore aggiornamento causato da un constraint

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3649]
## Module
l10n_fatturapa_out

## Describe the bug
Durante l'aggiornamento di _l10n_fatturapa_out_ viene generato l'errore:

`psycopg2.errors.DatatypeMismatch: foreign key constraint "wizard_export_fatturapa_report_print_menu_fkey" cannot be implemented`
`DETAIL:  Key columns "report_print_menu" and "id" are of incompatible types: character varying and integer.`

Questo avviene per via di [questo commit](https://github.com/OCA/l10n-italy/commit/0315ba5e5a601765552bee38fce4d70a3fd78dcc) in cui il campo `report_print_menu` cambia da:
`report_print_menu = fields.`**Many2one**()
a:
`report_print_menu = fields.`**Selection**()

Dimenticandosi però di eliminare constraint nel database che va in conflitto con il nuovo tipo di campo. Va aggiunto uno script di migrazione per sistemare

## Note aggiuntive
Mentre nella 14.0 è corretto aggiungere lo script per la versione `14.0.3.4.2`, la 16.0 ha invece un comportamento diverso.

Lato GitHub la modifica avviene prima del [bump 16.0.1.0.7](https://github.com/OCA/l10n-italy/commit/758fd9ea2d3acbc74fe5a9a962d4d719611ab132) ma nelle wheel appare solo alla **16.0.1.0.9**. Di conseguenza lo script di migrazione va puntato verso quella versione

## Affected versions
- [ ] 14.0 
- [ ] 16.0 : https://github.com/OCA/l10n-italy/pull/3652

**Comment by francesco-ooops** [comment]
@michelerusti l'errore è presente anche sulla 14?

**Comment by SirAionTech** [comment]
@michelerusti da riaprire perché dalla descrizione direi che per `14.0` c'è ancora qualcosa da fare
