### ISSUE TITLE
Quando importo fatture fornitori la data contabile in fattura non è corretta

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#3655]
## Module
l10n_it_fatturapa_in

## Describe the bug
La data contabile nella fattura impostata non corrisponde alla data ricezione dell'xml.

## To Reproduce
- [x] v14: chiudo come da commento: https://github.com/OCA/l10n-italy/pull/3326#issuecomment-1750282419
- [x] v16: #3326

- Impostare il campo `Data predefinita per la registrazione delle fatture fornitore` come `Data ricezione`.
- La data contabile nella fattura impostata non corrisponde alla data ricezione dell'xml.

**Comment by SirAionTech** [comment]
Puoi riportare i passi per riprodurre l'errore e le altre informazioni richieste nel template https://github.com/OCA/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md?
