### ISSUE TITLE
[l10n_it_ricevute_bancarie] non c'è il numero fattura nelle righe generate da Ri.Ba

### ISSUE THREAD

**Issue by odooNextev** [OCA/l10n-italy#3657]
## Module
l10n_it_ricevute_bancarie

**Is your feature request related to a problem?**
Nella descrizione delle `account.move.line` generate da Ri.ba c'è solamente il riferimento della distinta senza il numero della fattura relativa.
Questo dato è utile nei seguenti casi:
- quando è presente l'insoluto
- quando una riba è presentata ed ancora non scaduta

**Describe the solution you'd like**
Aggiungere il numero delle fatture al riferimento distinta nella descrizione delle `account.move.line` generate da Ri.ba.

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/3624
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/3658

**Comment by francesco-ooops** [comment]
chiusa manualmente in quanto non riesco a linkare le issues
