### ISSUE TITLE
[l10n_it_delivery_note] No longer able to validate a stock.picking

### ISSUE THREAD

**Issue by mmaridev** [OCA/l10n-italy#3665]
Since the last update of all modules and Odoo 14.0 core, when I try to validate a stock picking the following error is raised:
```
odoo.sql_db: bad query: INSERT INTO "stock_delivery_note" ("id", "create_uid", "create_date", "write_uid", "write_date", "active", "company_id", "date", "delivery_method_id", "goods_appearance_id", "gross_weight_uom_id", "invoice_status", "net_weight_uom_id", "partner_id", "partner_sender_id", "partner_shipping_id", "state", "transport_condition_id", "transport_method_id", "transport_reason_id", "type_id", "volume_uom_id") VALUES (nextval('stock_delivery_note_id_seq'), 6, (now() at time zone 'UTC'), 6, (now() at time zone 'UTC'), true, 1, NULL, NULL, NULL, 3, 'no', 3, NULL, 32, 688, 'draft', NULL, NULL, NULL, 2, 11) RETURNING id
ERROR: null value in column "partner_id" of relation "stock_delivery_note" violates not-null constraint
DETTAGLI: Failing row contains (3, t, null, null, draft, 32, null, 688, null, null, null, 2, null, null, null, null, 11, null, 3, null, 3, null, null, null, null, null, no, null, null, null, 1, null, null, 6, 2023-10-13 21:22:15.714048, 6, 2023-10-13 21:22:15.714048, null).
```

## Module
`l10n_it_delivery_note`

## Describe the bug
Either some unsuccessful db schema change or missing declaration.

## To Reproduce
**Affected versions**: 14.0

1. create a new stock picking
2. try to validare

**Expected behavior**
Stock picking validated and DDT draft generated.

**Additional context**
If the `l10n_it_delivery_note` is uninstalled, the validation succeeds.

**Comment by FrancescoBallerini** [comment]
@mmaridev 

I wasn't able to reproduce it on l10n-italy runbot, are you able to achieve it on runbot?
Also is this already the full log? If not, could you please provide the full log ?

**Comment by FrancescoBallerini** [comment]
From provided log it's clear that it fails to validate because `partner_id` is not set on stock_delivery_note for some reason.
I think this is still not reproducible on runbot though

**Comment by mmaridev** [comment]
Hi @FrancescoBallerini ,
yes, I can confirm it's not reproducible also in another instance of Odoo 14.
I already tried removing the `l10n_it_delivery_note` module and reinstalling it but the behaviour doesn't change.
I guess it's something that happened through an update but can't figure out what went wrong.

**Comment by francesco-ooops** [comment]
@mmaridev can this be closed for now?

**Comment by mmaridev** [comment]
@francesco-ooops I guess so... even if I'd love to hear from other people running upgrades to their instances... I don't have any weird configuration on my end so wondering what could have gone wrong.

**Comment by FrancescoBallerini** [comment]
> @francesco-ooops I guess so... even if I'd love to hear from other people running upgrades to their instances... I don't have any weird configuration on my end so wondering what could have gone wrong.

Hi @mmaridev I've tried to update both l10n-italy repository and odoo source code on today's date, but I have no issues on DDT validation. Few questions:

1 - in your environment, when a DDT is generated from stock transfer, `partner_id` field should be set on DDT. I guess it doesn't set the field in your environment is it right?

2 - if I am right about point 1, have you already tried to debug the workflow locally to check why `partner_id` field is not set ? 

I confirm it seems a local issue of your environment, it's hard to guess precisely from here but a few guesses:

- `partner_id` field has multi-company domain: 
 https://github.com/OCA/l10n-italy/blob/3eb7867aab2aa87991a23c3e3f9ab3aeaa92e7b9/l10n_it_delivery_note/models/stock_delivery_note.py#L125
 
 if you manage a multi-company environment it might be an issue related to multi-company / company ID

- are you managing any PR for this module (maybe an old PR that might mess up module behaviour) ?

**Comment by mmaridev** [comment]
Hi @francesco-ooops ,
the field was indeed correctly populated on DDT generation. Not managing any PR nor having multi company setup.
Anyway, ran another update yesterday and the problem disappeared therefore I'm closing the issue.
Thank you for your support!
