### ISSUE TITLE
Errore nel riconciliare fatture multiple che hanno ritenuta di acconto

### ISSUE THREAD

**Issue by ventre** [OCA/l10n-italy#3669]
Registrando un pagamento che riconcilia fattura multiple con ritenuta di acconto, nel mio caso due fatture, viene riconciliata solo la prima fattura con importo pari al movimento bancario e il campo amount_net_pay_residual rimane con segno negativo pari al amount_net_pay_residual della seconda fattura.

Per la riconciliazione seguo le istruzioni del readme del modulo

- [ ] 14.0: ?
- [ ] 16.0: sì

**Comment by matteoopenf** [comment]
In quale versione?

**Comment by ventre** [comment]
Si.scusate la 16

Il Mar 17 Ott 2023, 08:31 Matteo Mircoli ***@***.***> ha
scritto:
