### ISSUE TITLE
Errore registrazione contabile split payment in caso di modifica fattura

### ISSUE THREAD

**Issue by DA-amministrazione** [OCA/l10n-italy#3679]
## Module
Split payment Odoo v.16

## Describe the bug
Quando si riporta a bozza una fattura attiva precedentemente confermata, modificando la quantità o solo l'importo imponibile il documento perde le registrazioni automatiche dello storno dell'imposta scissione pagamenti.
## To Reproduce
**Affected versions**:

1. Inserire una fattura clienti con posizione fiscale e relative imposte riferite a split payment (scissione pagamenti)
2. Dopo aver confermato le fattura riportarla a bozza
3.Nella riga della fattura modificare la quantità o solo l'importo imponibile e confermare
4.Visualizzando la fattura neil tab movimenti contabili scompare lo storno scissione pagamenti

**Expected behavior**
Dopo la modifica dell'importo nelle righe della fattura i movimenti contabili devono contenere il giroconto dell'imposta sul conto IVA split payment

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by MaurizioConte** [comment]
@TheMule71 @tafaRU : Ciao Marco e Alex, potreste revisionare questa issue. Grazie

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Ho provato in `16.0` e il comportamento mi sembra essere quello atteso: 

https://github.com/OCA/l10n-italy/assets/143788994/eb9c6102-e7b2-4002-b350-a76371d62374

puoi verificare? Forse mi sono perso qualche passaggio?

La fattura generata è http://oca-l10n-italy-16-0-cc5e6d0e71d5.runboat.odoo-community.org/web#cids=2&menu_id=139&action=250&model=account.move&view_type=form&id=51.

**Comment by CiroBoxHub** [comment]
Buon pomeriggio. Ci sono novità per questa issue?

**Comment by francesco-ooops** [comment]
sì che ora è stale 😂

**Comment by francesco-ooops** [comment]
> Grazie della segnalazione! Ho provato in `16.0` e il comportamento mi sembra essere quello atteso:
> 
>  Odoo.-.Bacheca.della.contabilita.mp4 
> puoi verificare? Forse mi sono perso qualche passaggio?
> 
> La fattura generata è http://oca-l10n-italy-16-0-cc5e6d0e71d5.runboat.odoo-community.org/web#cids=2&menu_id=139&action=250&model=account.move&view_type=form&id=51.

scherzi a parte: @CiroBoxHub sei riuscito a riprodurla sul runboat?
