### ISSUE TITLE
[14.0] fatturapa_out con più aliquote iva comprese nel prezzo

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3688]
Configurazione delle tasse incluse nel prezzo
Diverse categorie prodotto con la stessa aliquota iva.
In fase di esportazione XML non viene fatta la somma per aliquota iva ma viene considerata sola l'ultima riga di iva 
![image](https://github.com/OCA/l10n-italy/assets/19937703/36b84ab2-eed1-426a-9725-f7c7423e8e84)
![image](https://github.com/OCA/l10n-italy/assets/19937703/0e6283f8-cb0f-4262-b91c-9117fb32deb6)

- [ ] 14.0: sì
- [ ] 16.0: ?

**Comment by francescapenso** [comment]
Any update?

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers mi sembra da controllare questa

**Comment by francescapenso** [comment]
Sto cercando di riprodurlo ma non riesco. Non so se si è risolto con altri fix, ho cmq chiesto al cliente dettagli
