### ISSUE TITLE
Gestire i `position="replace"` nei vari moduli

### ISSUE THREAD

**Issue by aleuffre** [OCA/l10n-italy#3689]
## Modules
- `l10n_it_account`
- `l10n_it_fatturapa_out`
- `l10n_it_fatturapa_out_stamp`
- `l10n_it_fatturapa_out_wt`

## Describe the bug
Il nuovo linter OCA https://github.com/OCA/odoo-pre-commit-hooks consiglia fortemente di evitare i `position="replace"`, e di usarli solo come ultima risorsa.

In https://github.com/OCA/l10n-italy/pull/3687 ho inserito 

`<!-- oca-hooks:disable=xml-dangerous-qweb-replace-low-priority -->`

per disattivare il controllo su quel file. Questa però non è una soluzione ideale.

Soluzione consigliata qui https://github.com/OCA/sale-workflow/pull/2754#issuecomment-1785622763 da Pedro Baeza è di lasciare il check ma inserire `priority="999"` sulle view affette. Altre soluzioni ovviamente possono essere un refactor volto a eliminare completamente il `position="replace"`

## To Reproduce
**Affected versions**:
- [ ] 14.0 (disabilitato check in https://github.com/OCA/l10n-italy/pull/3687 )
- [ ] 16.0 (~~ancora tutto da gestire, per ora fermi qui: https://github.com/OCA/l10n-italy/pull/3686~~ risolto in https://github.com/OCA/l10n-italy/pull/3767 )

**Comment by SirAionTech** [comment]
In https://github.com/OCA/l10n-italy/pull/3767 viene usato il nuovo linter e non ci sono problemi con `position="replace"` perché ovunque venga usato ha priorità 100, ad esempio in https://github.com/OCA/l10n-italy/blob/2f6d1837f05258e7af7d6dc4d8a2a393083303f2/l10n_it_fatturapa_out_wt/views/account_invoice_it_dati_ritenuta.xml#L66.
Questa issue quindi si può considerare risolta per `16.0` o sarà risolta solo quando i `position="replace"` saranno rimossi?

**Comment by aleuffre** [comment]
Da indicazioni di Pedro Baeza, la priorità > 99 è una soluzione sufficiente. Marco la chiusura per 16.0

**Comment by tafaRU** [comment]
@aleuffre non sarebbe più corretto 
![image](https://github.com/OCA/l10n-italy/assets/3512779/e043875b-65d7-45c0-b216-8e06053d2c97)
attendere che #3767 venga *mergiata* prima di spuntare il flag?

**Comment by SirAionTech** [comment]
> @aleuffre non sarebbe più corretto ![image](https://private-user-images.githubusercontent.com/3512779/290227426-e043875b-65d7-45c0-b216-8e06053d2c97.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NzkyMzQsIm5iZiI6MTcwMjQ3ODkzNCwicGF0aCI6Ii8zNTEyNzc5LzI5MDIyNzQyNi1lMDQzODc1Yi02NWQ3LTQ1YzAtYjIxNi04ZTA2MDUzZDJjOTcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTNUMTQ0ODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGUyZWM3YzdkZmI0YThmYTI5NzY4M2FjNTdhZjViZTRjZjUxZWFjMmU5Y2IxMDk5Mjc4MTdlZDk4ZWVhNzI2YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.8cPbOlfDIsMYgtQQaBwdJZdvfR_PDmjsP3RrsmXEO90) attendere che #3767 venga _mergiata_ prima di spuntare il flag?

:pray: Colpa mia che in https://github.com/OCA/l10n-italy/issues/3689#issuecomment-1853908431 ho scritto che poteva essere considerata risolta per `16.0`.

Invece parlando di flag, se ho ben capito per `14.0` c'è ancora da rimuovere i vari `<!-- oca-hooks:disable=xml-dangerous-qweb-replace-low-priority -->` quindi il flag non ci andrebbe, che ne pensi @aleuffre?

**Comment by aleuffre** [comment]
> Invece parlando di flag, se ho ben capito per `14.0` c'è ancora da rimuovere i vari `<!-- oca-hooks:disable=xml-dangerous-qweb-replace-low-priority -->` quindi il flag non ci andrebbe, che ne pensi @aleuffre?

Io non l'ho cliccato quel flag... (cioè evidentemente l'ho cliccato io, probabilmente accidentalmente con il touchpad, ma...)

**Comment by tafaRU** [comment]
> Io non l'ho cliccato quel flag.

su `14.0`  l'avevo cliccato io pensando che fosse risolto :smiley:
