### ISSUE TITLE
Gli enchi puntati nel campo "termini e condizioni" delle fatture attive generano un file xml con errore

### ISSUE THREAD

**Issue by DA-amministrazione** [OCA/l10n-italy#3695]
## Module
Fattura cliente Odoo v.16

## Describe the bug
Quando si crea una fattura cliente, inserendo nel campo “termini e condizioni” un testo contenente un elenco puntato, il file xml generato risulta errato.

## To Reproduce
**Affected versions**:V.016 Crea una fattura cliente, inserisci un testo contenente un elenco puntato nel campo "termini e condizioni", genera il file xml. Il controllo del file xml restituisce errore. 

1.crea una fattura clienet
2.inserisci un testo con elenco puntato nel campo "termini e condizioni"
3.esporta il file xml
4.controlla il file xml generato

**Expected behavior**
Il controllo del file generato non deve restituire errore

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
> ## Module
> Fattura cliente Odoo v.16
> 
> ## Describe the bug
> Quando si crea una fattura cliente, inserendo nel campo “termini e condizioni” un testo contenente un elenco puntato, il file xml generato risulta errato.
> 
> ## To Reproduce
> **Affected versions**:V.016 Crea una fattura cliente, inserisci un testo contenente un elenco puntato nel campo "termini e condizioni", genera il file xml. Il controllo del file xml restituisce errore.
> 
> Steps to reproduce the behavior: 1.crea una fattura clienet 2.inserisci un testo con elenco puntato nel campo "termini e condizioni" 3.esporta il file xml 4.controlla il file xml generato
> 
> **Expected behavior** Il controllo del file generato non deve restituire errore
> 
> **Additional context** Add any other context about the problem here. (e.g. OS, Python version, ...)

che errore restituisce?
