### ISSUE TITLE
[IMP] l10n_it_fatturapa_pec: aggiungere le fatture in coda invece che inviarle subito

### ISSUE THREAD

**Issue by odooNextev** [OCA/l10n-italy#3717]
**Is your feature request related to a problem?**
Attualmente l'azione "Send Via PEC" manda le fatture senza passare dalla coda predefinita di Odoo, rischiando di raggiungere il limite di invio di mail contemporaneo imposto dal provider o dal certificatore.

**Describe the solution you'd like**
Bisognerebbe evitare di usare il metodo `send` nella funzione `send_via_pec` del modulo `l10n_it_fatturapa_pec` e creare solamente gli oggetti `mail.message` e `mail.mail`.
In questo caso però bisogna capire come intercettare l'invio effettivo della fattura per impostare "sent" sull'oggetto `fatturapa.attachment.out`, la data di invio e l'autore dell'invio.
In caso di errore ci sarebbe da memorizzare lo stato "sender_error" ed il messaggio ritornato.

Si potrebbe usare il metodo `_postprocess_sent_message` di `mail.mail` e recuperare l'id di `fatturapa.attachment.out` da `mail_message_id.res_id`.

**Describe alternatives you've considered**
Mettere in coda i `fatturapa.attachment.out` da elaborare con `send_via_pec` invece che le mail da inviare.

**Affected versions:**
- [x] 10.0 (chiuso in quanto non supportate)
- [x] 12.0 (chiuso in quanto non supportate)
- [ ] 14.0
- [ ] 16.0

**Comment by mmaridev** [comment]
+1 e aggiungo: quando si fa un invio massivo (inteso come selezione multipla di file FPA da inviare) sarebbe sufficiente inviare una sola PEC con tutti gli XML allegati, sempre fatto salvo il superamento dei limiti imposti dal provider (magari da configurare via settings?)

**Comment by odooNextev** [comment]
@mmaridev grazie per il supporto.
Per ora però questa issue è in stallo perché stiamo lavorando per integrare i moduli di `l10n-italy` in `l10n_it_edi` di Odoo SA per la prossima versione, 18.0.
A questo punto l'invio e la ricezione delle fatture verrebbe fatto tramite SDI che non ha questi problemi (ed è gratis).
Puoi trovare più informazioni qui: https://github.com/OCA/l10n-italy/issues/3787

**Comment by mmaridev** [comment]
è gratis nel senso che SdI non chiede un contributo ma non è gratis in termini di onerosità interna di gestione. La PEC è verificabile e storicizzata dal provider mentre usando lo SdI channel SOAP ciò che è nel DB di Odoo è autoritativo.
Per non dire che serve fare il processo di accreditamento e collaudo passando da SOGEI...

**Comment by odooNextev** [comment]
> Per non dire che serve fare il processo di accreditamento e collaudo passando da SOGEI...

Non so se ho capito bene, ma Odoo è già accreditato ed ha un proprio codice, basta inserirlo in configurazione, comunicarlo all'AdE e le fatture vengono inviate e ricevute correttamente: https://www.odoo.com/documentation/17.0/applications/finance/fiscal_localizations/italy.html#e-invoicing

Forse però intendi qualcos'altro

**Comment by mmaridev** [comment]
Non credo possa essere davvero questo che hai linkato, almeno non per quelli che non sono SaaS. Significherebbe che tutte le fatture transitano per un server centralizzato di Odoo che poi te le invia alla tua istanza e non credo che vogliano fare questo lavoro gratis. In più, si aggiungerebbe un contesto moderatamente complesso dal punto di vista RGPD da gestire.
Penso invece lo integreranno in maniera tale che parli direttamente con lo SdI via SOAP, per cui serve però un accredito specifico.

**Comment by odooNextev** [comment]
> Non credo possa essere davvero questo che hai linkato, almeno non per quelli che non sono SaaS.

Lo sto usando personalmente e funziona su Odoo Online, ma non ci sono riferimenti ad un diverso trattamento per i clienti On Premise.

Poi per il futuro non saprei, meglio chiedere a [@lordkrandel
](https://github.com/lordkrandel)
