### ISSUE TITLE
"Info registrazione contabile" shows standard Odoo description and the "Promemoria" account is wrong (IVA account taken)

### ISSUE THREAD

**Issue by federicocandiago** [OCA/l10n-italy#3726]
## Module
l10n_it_withholding_tax_payment

## Describe the bug
While registering the payment recounciliation of a supplier_invoice with the ritenuta d'acconto managed by this plugin, Odoo apparently crashed and the sequence
counter (withholding.tax.move.payment) didn't increase from WTMP/0003 to WTMP/0004. We tried to solve by increasing the number_next_actual variable of the sequence by 1 but now, for every supplier invoice with the withholding_tax selected, if we try to recouncile it with the incoming payment:
- The account ("promemoria") indicated in the "Info registrazione contabile" sum-up of the recounciliation record is indicated with the "Liquidazione IVA" account, and not with the expected "VARIE/2023/00XX" account corresponding to the analytic account of the invoice.
- The [account.move].ref "riferimento" field is not showing the correct description "WT 0012 - PURCHASE/2023/1234" reference (containing the progressive number of the WT and the purchase invoice reference) but just "Collaborazione occasionale del 01/02/2023" (which I assume is the standard Odoo diciture)

We tried to uninstall and reinstall the plugin, update it, delete and recreate all the rows in the witholding.tax model (Contabilità > Impostazioni > Ritenuta d'acconto), but unfortunately the IVA\VAT account is always taken, and the description is wrong.

Could anyone help us?
Thanks in advance
 
## To Reproduce
Odoo 16.0
Modules installed: 
- l10n_it_edi_withholding
- l10n_it_withholding_tax
- l10n_it_withholding_tax_payment

1. Have the recounciliation process of a payment for a supplier invoice with the tax_withholding crash, i assume
2. Recouncile a supplier invoice with its payment
3. Verify that the resulting [account.move].ref and the "promemoria" account are wrong (an IVA\VAT account is taken)

**Expected behavior**
The correct analytic account should be taken at recounciliation
The .ref field should correctly be populated as before (e.g. "WT 0012 - PURCHASE/2023/1234")

**Additional context**
Odoo.sh is being used for the modules to be hosted.
System info:
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers credo non sia prevista al momento la compatibilità tra questi moduli, confermate?

l10n_it_edi_withholding
l10n_it_withholding_tax
l10n_it_withholding_tax_payment

**Comment by tafaRU** [comment]
> @OCA/local-italy-maintainers credo non sia prevista al momento la compatibilità tra questi moduli, confermate?

@francesco-ooops confermo :+1:

**Comment by francesco-ooops** [comment]
penso sia sufficiente per chiudere la issue, @federicocandiago se hai altre domande riapri pure
