### ISSUE TITLE
Versioni supportate nelle issues

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3728]
Ciao, prendo ad esempio questa issue: https://github.com/OCA/l10n-italy/issues/3257

Per la 14 e la 16 il problema è stato risolto, il fatto che non sia risolto sulla 12 e precedenti è motivo per tenere la issue aperta?

A mia opinione no, però potrebbe essere utile mantenere uno storico se qualcuno affrontasse questo bug per un cliente fermo ad una versione non supportata.

Potrebbe essere una soluzione usare un tag specifico, es "Unresolved in 12.0" e poi chiudere?
Oppure sono solo pippe mentali e chiudiamo tutte le issue non risolte in 14 e 16?

**Comment by OpenCode** [comment]
IMHO si può chiudere. Lo stesso principio si potrebbe applicare alle versioni ancora più vecchie.
Fu presa la decisione si supportare le ultime due versioni pari. Se iniziano le eccezioni va a finire che nessuna issue sarà mai chiudibile finchè c'è la vaga possibilità che il problema esista su una delle qualsiasi versioni vecchie.

**Comment by SirAionTech** [comment]
+1 per tenere chiudere le issue quando il problema è risolto su tutte le versioni supportate.

Peraltro, dovrebbe essere già così :)
> La issue verrà chiusa quando tutte le versioni supportate saranno aggiornate.

da https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#chiusura-issue.

Fosse per me rimuoverei anche le parti
> La issue può essere chiusa quando: [...] non sono presenti PR aperte per le versioni dispari
> Contestualmente alla chiusura, per tenere traccia del problema o della funzionalità per le versioni ancora scoperte, aggiungere le label `needs fixing` e quella con il relativo numero di versione (es. `13.0`).

Non aggiungerei quindi tag particolari a quelle che sono ancora da risolvere su versioni non supportate (pari o dispari che siano).

**Comment by francesco-ooops** [comment]
ok dunque se ho capito bene la issue #3257 andrebbe chiusa con tag "needs fixing" "12.0" corretto?

**Comment by tafaRU** [comment]
> Per la 14 e la 16 il problema è stato risolto, il fatto che non sia risolto sulla 12 e precedenti è motivo per tenere la issue aperta?

no, così come evidenziato in https://github.com/OCA/l10n-italy/issues/3728#issuecomment-1820435542

La issue che _linki_ è stata aperta quando ancora il default branch era su `14.0` da qui l'opportunità di tracciare anche la versione `12.0`.

**Comment by tafaRU** [comment]
> Inoltre quello che c'è scritto nel wiki andrebbe un po' aggiornato perché nel frattempo abbiamo introdotto dei nuovi tag per gestire meglio il triage delle issue.

me lo segno tra le cose da fare :wink:

**Comment by francesco-ooops** [comment]
Ok, il passo successivo però dovrebbe essere di fare un giro delle issues aperte: 

- aggiungere v16 se non è presente il checkbox + tag
- volendo, chiudere issues risolte o non presenti in v14 e v16

mi metto a disposizione per fare questo lavoro se volete.

**Comment by tafaRU** [comment]
> Ok, il passo successivo però dovrebbe essere di fare un giro delle issues aperte:
> 
>     * aggiungere v16 (ed eventualmente v14) se non è presente il checkbox + tag
> 
>     * volendo, chiudere issues risolte o non presenti in v14 e v16

Era un lavoro che avevamo iniziato ad intraprendere con @TheMule71 e che sarebbe da riprendere.

> mi metto a disposizione per fare questo lavoro se volete.

Grazie mille :pray: Così come avevamo iniziato a fare, potremmo fissare un appuntamento mensile il venerdì pomeriggio in cui dedicarci a questo tipo di attività. Cosa ne pensi?

**Comment by francesco-ooops** [comment]
Dato che non posso entrare nello specifico tecnico delle questioni, potrei fare un lavoro su un foglio google facendo un suggerimento di quanto da fare a mia opinione per dare una "sgrossata", e poi magari verificate più in dettaglio. 

Potrebbe funzionare così? :)

**Comment by tafaRU** [comment]
> Dato che non posso entrare nello specifico tecnico delle questioni

la call a cui mi riferivo mirava semplicemente al triage delle issue pertanto le tue competenze _funzionali_ possono tornare molto utili :)

> poi sono disponibile a lavorarci in call, no problem

meglio se ci organizziamo almeno la prima volta in call.
