### ISSUE TITLE
[l10n_it_ricevute_bancarie] -  Presentazione RiBa basata su importo predefinito

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3737]
## Module
l10n_it_ricevute_bancarie

## Describe the bug
Aggiungere funzionalità per presentazione RiBa basata su importo predefinito

## To Reproduce
**Affected versions**:

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/3411 e https://github.com/OCA/l10n-italy/pull/3701
- [ ] 16.0

**Comment by SirAionTech** [comment]
Non direi https://github.com/OCA/l10n-italy/labels/bug ma https://github.com/OCA/l10n-italy/labels/enhancement
