### ISSUE TITLE
[14.0] Commit mancante in l10n_it_fatturapa_in

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3741]
Descrizione:
Il campo `invoices_total` presente nella 12.0 non è stato portato nella migrazione.

Module:
l10n_it_fatturapa_in

Versioni:
- [ ] 14.0: #3740 
- [ ] 16.0:

**Comment by francesco-ooops** [comment]
@sergiocorato dato che è una riga, riesci a fare la v16 così chiudiamo? Grazie!

**Comment by SirAionTech** [comment]
Come spiegato in https://github.com/OCA/l10n-italy/issues/3645#issuecomment-1853993153 è duplicata di https://github.com/OCA/l10n-italy/issues/3645 quindi si può chiudere @sergiocorato.

**Comment by tafaRU** [comment]
Chiudo perché duplicata di https://github.com/OCA/l10n-italy/issues/3645
