### ISSUE TITLE
Autofattura per fattura extra ue con partita IVA italiana "leggera" nel modulo l10n_it_fatturapa_out

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3745]
Credo l'intenzione di questo codice sia bypassata quando le fatture arrivano con una partita IVA italiana "leggera", non valida quindi come una partita IVA normale.

- [ ] 12.0: (inoltre qui viene esportata nell'xml la partita IVA indicata escluso il codice nazione) https://github.com/OCA/l10n-italy/blob/13995d0997fe9bd5c383c528d14752277ee5babb/l10n_it_fatturapa_out_rc/wizard/wizard_export_e_invoice.py#L108
- [ ] 14.0:  (inoltre qui viene esportata nell'xml la partita IVA indicata incluso il codice nazione) https://github.com/OCA/l10n-italy/blob/e59aec468d79ec66079ac0604d370324ce43bb93/l10n_it_fatturapa_out/wizard/efattura.py#L112
- [ ] 16.0: come 14.0

Modulo:
l10n_it_fatturapa_out (e l10n_it_fatturapa_out_rc in v. 12.0)

Il campo partita IVA viene ignorato se il codice nazione è diverso da IT, e compilato con codice nazione + 99999999999 se non indicato, forse dovrebbe esserlo sempre quando la nazione non è IT?
In ogni caso c'è una differenza tra 2 versioni stabili, che non pare il caso.

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Non sapevo esistessero delle partite IVA che non sono delle partite IVA valide.

Puoi proporre delle modifiche in modo da capire meglio quale sarebbe la soluzione giusta secondo te?

Aggiungi per favore che `16.0` è come `14.0`?

@TheMule71 cosa ne pensi?
