### ISSUE TITLE
[14.0] [l10n_it_fatturapa_out] problema nei test bug?

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#3747]
## Module
l10n_it_fatturapa_out

## Describe the bug
Facendo dei test per un altra' pr ho notato che il file di test 15 e' errato Ossia Cedente e Cessionario sono la stessa PIVA e cosi non puo' essere secondo le specifiche

Ulteriore cosa il file viene usato nel test 15 della fattura in valuta
https://github.com/OCA/l10n-italy/blob/14.0/l10n_it_fatturapa_out/tests/data/IT06363391001_00015.xml

## To Reproduce
**Affected versions**:

- [ ] 14
- [ ] 16

**Expected behavior**
le due partite iva dei test devono essere diverse

**Comment by francesco-ooops** [comment]
@matteoopenf vuoi proporre una modifica al test?

**Comment by SirAionTech** [comment]
Qual è l'errore restituito quando si prova a trasmettere una fattura con stesso cedente e cessionario?

**Comment by matteoopenf** [comment]
> @matteoopenf vuoi proporre una modifica al test?

ci sarebbe da farla ma sono poco pratico con i test

**Comment by matteoopenf** [comment]
> Qual è l'errore restituito quando si prova a trasmettere una fattura con stesso cedente e cessionario?
> 
> Ho cercato nelle specifiche in https://www.agenziaentrate.gov.it/portale/documents/20143/451259/Allegato+A+-+Specifiche+tecniche+vers+1.7.1.pdf/5c3de81a-7ad5-34a7-54b0-735b1456972c ma non l'ho trovato

io ho testato e non va e' sbagliato il tipo di documento

**Comment by matteoopenf** [comment]
> Qual è l'errore restituito quando si prova a trasmettere una fattura con stesso cedente e cessionario?
> 
> Ho cercato nelle specifiche in https://www.agenziaentrate.gov.it/portale/documents/20143/451259/Allegato+A+-+Specifiche+tecniche+vers+1.7.1.pdf/5c3de81a-7ad5-34a7-54b0-735b1456972c ma non l'ho trovato

piu' in particolare per i tipi di documento messi in quel file xml non e' possibile che siano identici
