### ISSUE TITLE
Stampa Libro Giornale: Intestazione Azienda errata su Multi-Company

### ISSUE THREAD

**Issue by MaurizioConte** [OCA/l10n-italy#3757]
## Module
The name of the module that has a bug.
Odoo V16
Nome del Modulo: ITA - Libro giornale - Reportlab
Nome Tecnico:        l10n_it_central_journal_reportlab 

## Describe the bug
NOTA: Problema si Verifica su Ambiente Multi-Company
I dati di intestazione della stampa del libro giornale non sono corretti.

## To Reproduce
- Lavorare su un ambiente Multi-Company

**Affected versions**:
- [x] V16: #3758 
- [x] V14: #3761 

1.Per riprodurre l'errore basta avere un ambiente con 2 company es Azienda A ed Azienda B
2.Impostare sul profilo utente l'Azienda A come Azienda predefinita.
3.Effettuare il login.
4.Portarsi sull'azienda B assicurandosi di lavorare solo con la spunta per l'azienda B.
5.Effettuare la Stampa del libro Giornale
6.Controllare il report

**Expected behavior**
Ci si aspetta che i dati da riportare nell'intestazione del report vengano recuperati utilizzando l'azienda a cui si è collegati e non l'azienda predefinita indicata nel profilo dell'utente.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by francesco-ooops** [comment]
Ciao @MaurizioConte , grazie della issue!

Sai se il problema si presenta anche in v14?

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Ho dato un'occhiata rapida al codice e mi pare plausibile perché in https://github.com/OCA/l10n-italy/blob/f3c7476dacf8baeeca0b9ad9ac15a4692cd1cd4b/l10n_it_central_journal_reportlab/wizard/print_giornale.py#L204C25-L204C25 (e le altre 10 occorrenze sotto) viene usato `env.user.company_id` invece di `env.company`.

**Comment by MaurizioConte** [comment]
Ciao, non l'ho testato sulla 14 quindi non saprei.

**Comment by MaurizioConte** [comment]
Se il modulo è stato migrato dalla 14.0 ha una buona percentuale che anche quello non funziona

**Comment by MaurizioConte** [comment]
#3758

**Comment by francesco-ooops** [comment]
@MaurizioConte @OCA/local-italy-maintainers questa si può chiudere come completata

Domanda: perchè alcune PR mergiate si chiudono con lo status merged e altre con lo status closed?

**Comment by SirAionTech** [comment]
> Domanda: perchè alcune PR mergiate si chiudono con lo status merged e altre con lo status closed?

Strano, forse perché c'è stata la modifica https://github.com/OCA/l10n-italy/pull/3761#event-11171007886 tra il comando di merge  https://github.com/OCA/l10n-italy/pull/3761#issuecomment-1843268140 e il merge effettivo https://github.com/OCA/l10n-italy/pull/3761#issuecomment-1843289071
