### ISSUE TITLE
Stampa liquidazione IVA ignora l'azienda nel multicompany

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3766]
## Module
account_vat_period_end_statement

## Describe the bug
Le imposte non vengono visualizzate nel report.

## To Reproduce
**Affected versions**:
- [x] 14.0: #3762 
- [ ] 16.0: #3765

1. impostare l'utente con l'azienda principale A
2. impostare l'interfaccia con l'azienda B
3. stampare una liquidazione IVA dell'azienda B

**Expected behavior**
Le imposte vengono visualizzate nel report.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by francesco-ooops** [comment]
@tafaRU perchè completed?

**Comment by francesco-ooops** [comment]
Chiusa perchè non risulta presente in v16 https://github.com/OCA/l10n-italy/pull/3765#pullrequestreview-1801685221
