### ISSUE TITLE
l10n_it_ricevute_bancarie esporta file senza rimuovere i caratteri non accettati

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3777]
## Module
l10n_it_ricevute_bancarie

## Describe the bug
Alcuni caratteri speciali non sono ammessi ~, vedi: https://online-smallbusiness.unicredit.it/nb/it/doc/Errori_frequenti_RiBa~
vedi istruzioni generiche per file CBI: [fdocumenti.com_cbi-std-001608.pdf](https://github.com/OCA/l10n-italy/files/13683835/fdocumenti.com_cbi-std-001608.pdf)
e specifiche per riba: [CBI-RIBA.pdf](https://github.com/OCA/l10n-italy/files/13683847/CBI-RIBA.pdf)

## To Reproduce
**Affected versions**:
- [x] 14.0: #3782 
- [ ] 16.0: https://github.com/OCA/l10n-italy/pull/4328

1. creare un cliente con indirizzo contenente una `è`
2. emettere una riba verso quel cliente
3. la riba viene rifiutata per riga troppo lunga

**Expected behavior**
La riba viene accettata.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by eLBati** [comment]
È un vincolo solo di alcune banche o del CBI in generale?

**Comment by sergiocorato** [comment]
> È un vincolo solo di alcune banche o del CBI in generale?

Ho allegato il file di specifiche del CBI, è una regola generale. Non specificano comunque un formato, ma solo i caratteri "ammessi", che poi dicono "consigliati", ma che è meglio rispettare per evitare errori.
