### ISSUE TITLE
l10n_it_withholding_tax_payment: aggiunta di un campo descrizione

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#3792]
Aggiunta di un nuovo campo descrizione sulla tabella di collegamento tra le fatture e pagamenti in ritenuta

Version:

- [ ] 14.0
- [ ] 16.0: #3698

**Comment by SirAionTech** [comment]
@Borruso ho letto https://github.com/OCA/l10n-italy/pull/3698#issuecomment-1863155070 ma non ho capito se per `14.0` serve fare qualcosa, nel caso riapri
