### ISSUE TITLE
Poter aprire una distinta RiBa quando la fattura collegata è stata eliminata

### ISSUE THREAD

**Issue by SirAionTech** [OCA/l10n-italy#3814]
## Module
**l10n_it_riba**

## Describe the bug
Provando ad aprire la distinta RiBa si ottiene:
```
  ...
  File "/mnt/data/odoo-addons-dir/l10n_it_riba/models/riba.py", line 225, in _compute_line_values
      ).strftime("%d/%m/%Y")
  AttributeError: 'NoneType' object has no attribute 'strftime'
```

## To Reproduce
**Affected versions**:
- [x] `14.0`: #4493
- [x] `16.0`: https://github.com/OCA/l10n-italy/pull/3813

1. Creare una fattura con RiBa
2. Confermare la fattura
3. Emettere la RiBa
4. Riportare in bozza la fattura
5. Eliminare la fattura
6. Aprire la RiBa

**Expected behavior**
Nessun errore

**Comment by toita86** [comment]
Ciao @SirAionTech, nel runboat della 14.0 non riesco a riprodurre i passi che hai descritto.

> Steps to reproduce the behavior:
>
> Creare una fattura con RiBa
> Confermare la fattura
>  Emettere la RiBa
>  Riportare in bozza la fattura
>  Eliminare la fattura

il mio punto di blocco è qui 
![image](https://github.com/user-attachments/assets/0fdc03ef-b50c-4524-af79-2ff1dde59579)

sto cercando di portare questa PR https://github.com/OCA/l10n-italy/pull/3813 alla 14 ma il test introdotto qui https://github.com/OCA/l10n-italy/commit/f2dc4c6659f3733ed0d36c8da306626c465fd383#diff-429c4f56afd08397de9cdd8888c36bf998bfe1bff27c020e7339ab36973955d7R619 si blocca esattamente alla parte in cui si cerca di eliminare la fattura. 

da traceback:
```
2024-12-09 10:48:23,448 20 ERROR devel odoo.addons.l10n_it_ricevute_bancarie.tests.test_riba: ERROR: TestInvoiceDueCost.test_riba_line_date_no_move
Traceback (most recent call last):
  File "/opt/odoo/auto/addons/l10n_it_ricevute_bancarie/tests/test_riba.py", line 643, in test_riba_line_date_no_move
    self.invoice.unlink()
  File "/opt/odoo/auto/addons/l10n_it_fatturapa_sale/models/account_move.py", line 12, in unlink
    res = super().unlink()
  File "/opt/odoo/auto/addons/sale/models/account_invoice.py", line 40, in unlink
    res = super(AccountMove, self).unlink()
  File "/opt/odoo/auto/addons/account/models/account_move.py", line 2144, in unlink
    raise UserError(_("You cannot delete an entry which has been posted once."))
odoo.exceptions.UserError: You cannot delete an entry which has been posted once.
```

Se si cercasse di annullare la registrazione appare il warning nello screenshot precedente rendendo cosi impossibile cancellare la fattura.

**Comment by SirAionTech** [comment]
> Ciao @SirAionTech, nel runboat della 14.0 non riesco a riprodurre i passi che hai descritto.
> 
> > Steps to reproduce the behavior:
> > Creare una fattura con RiBa
> > Confermare la fattura
> > Emettere la RiBa
> > Riportare in bozza la fattura
> > Eliminare la fattura
> 
> il mio punto di blocco è qui ![image](https://private-user-images.githubusercontent.com/36401195/393814932-0fdc03ef-b50c-4524-af79-2ff1dde59579.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM3NDQ0NzQsIm5iZiI6MTczMzc0NDE3NCwicGF0aCI6Ii8zNjQwMTE5NS8zOTM4MTQ5MzItMGZkYzAzZWYtYjUwYy00NTI0LWFmNzktMmZmMWRkZTU5NTc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA5VDExMzYxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZGQ1N2M3OWNjZTYzNDFmZGVmOTkyYTk3ZjQxMGEwNmE2ZTgyNmMzZWE2YzQ5MTI0YTQ4MzNlNzExMmIzNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VjWVnqXk0SEhEDwMYnzz5cDfpz6ElQhfW3PDfhXS-SI)
> 
> sto cercando di portare questa PR #3813 alla 14 ma il test introdotto qui [f2dc4c6#diff-429c4f56afd08397de9cdd8888c36bf998bfe1bff27c020e7339ab36973955d7R619](https://github.com/OCA/l10n-italy/commit/f2dc4c6659f3733ed0d36c8da306626c465fd383#diff-429c4f56afd08397de9cdd8888c36bf998bfe1bff27c020e7339ab36973955d7R619) si blocca esattamente alla parte in cui si cerca di eliminare la fattura.
> 
> da traceback:
> 
> ```
> 2024-12-09 10:48:23,448 20 ERROR devel odoo.addons.l10n_it_ricevute_bancarie.tests.test_riba: ERROR: TestInvoiceDueCost.test_riba_line_date_no_move
> Traceback (most recent call last):
>   File "/opt/odoo/auto/addons/l10n_it_ricevute_bancarie/tests/test_riba.py", line 643, in test_riba_line_date_no_move
>     self.invoice.unlink()
>   File "/opt/odoo/auto/addons/l10n_it_fatturapa_sale/models/account_move.py", line 12, in unlink
>     res = super().unlink()
>   File "/opt/odoo/auto/addons/sale/models/account_invoice.py", line 40, in unlink
>     res = super(AccountMove, self).unlink()
>   File "/opt/odoo/auto/addons/account/models/account_move.py", line 2144, in unlink
>     raise UserError(_("You cannot delete an entry which has been posted once."))
> odoo.exceptions.UserError: You cannot delete an entry which has been posted once.
> ```
> 
> Se si cercasse di annullare la registrazione appare il warning nello screenshot precedente rendendo cosi impossibile cancellare la fattura.

:wave: la fattura va eliminata, non annullata.

Per risolvere l'errore nel test, va bypassato il controllo di `14.0` https://github.com/odoo/odoo/blob/f33e80dc4a98d0234d531d5f6a3950de124510bc/addons/account/models/account_move.py#L2143-L2144:
```
            if move.posted_before and not self._context.get('force_delete'):
                raise UserError(_("You cannot delete an entry which has been posted once."))
```
e si può fare mettendo nel contesto `force_delete`; da interfaccia si potrebbe creare un'azione server che aggiunge quel contesto ed elimina.

Comunque se gli stessi passi non si possono replicare in `14.0` magari vuol dire che il problema non esiste in questa versione.

**Comment by toita86** [comment]
@SirAionTech esaustivo come al solito, grazie mille per la spiegazione.
