### ISSUE TITLE
[10.0][FIX] l10n_it_vat_registries - somma errata nell'imponibile dei registri iva quando ci sono valori negativi nella nota credito 

### ISSUE THREAD

**Issue by michelerusti** [OCA/l10n-italy#3840]
## Module
l10n_it_vat_registries

## Describe the bug
Nota di credito fornitori ( )
![image](https://github.com/OCA/l10n-italy/assets/102949020/c6fe96ac-4af2-44b7-b521-6b0a4ce9ff50)

che ha questi valori  - un importo in positivo ed uno negativo
![image](https://github.com/OCA/l10n-italy/assets/102949020/cb049d12-172e-4721-886d-8436fe0cb3b7)

quando stampo il registro iva (vat statement) viene conteggiata in questo modo
![image](https://github.com/OCA/l10n-italy/assets/102949020/683e28d2-b03b-4299-9b49-1f84238a9c08)

a livello di riga nella colonna imponibile appare la somma del valori (4300) che è errata
ma a livello di totali imponibile è corretto
la stampa dell'iva è corretta

## To Reproduce
**Affected versions**:
- [ ] 10.0 https://github.com/OCA/l10n-italy/pull/3841
- [x] 14.0 non si presenta
- [x] 16.0 non si presenta

**Comment by francesco-ooops** [comment]
@michelerusti puoi verificare se è applicabile anche alle versioni 14 e 16? grazie!

**Comment by michelerusti** [comment]
> @michelerusti puoi verificare se è applicabile anche alle versioni 14 e 16? grazie!

ho fatto una veloce verifica sui runboat, 14 e 16 non sembrano presentare questo problema!

**Comment by SirAionTech** [comment]
> > Potrebbe essere duplicata di #1355? Se è così esiste già #3129 per `10.0`, e spiegherebbe come mai il problema è già risolto nelle altre versioni
> 
> @SirAionTech Si effettivamente il problema sembra lo stesso, ma la soluzione della PR che menzionato. Il calcolo viene sistemato ma crea un'incongruenza di segni tra l'imponibile ed il totale
> 
> L'imponibile dovrebbe essere negativo (come il totale):
> 
> ![Screenshot from 2024-01-30 15-40-20](https://private-user-images.githubusercontent.com/102949020/300849796-6fbdda7e-0614-4e8f-813f-ff4f810bd0f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MjYxMjgsIm5iZiI6MTcwNjYyNTgyOCwicGF0aCI6Ii8xMDI5NDkwMjAvMzAwODQ5Nzk2LTZmYmRkYTdlLTA2MTQtNGU4Zi04MTNmLWZmNGY4MTBiZDBmMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEzMFQxNDQzNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjRlMDllNWQ2M2MxYTUwMjM3Yzk1MDIwNDIwZmZjZjUzZGU1OWMwZDZkYjFjMmQ0NTJmYjVjYzgwNTBhMWExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pi8pwDSmw-Tt-m3tYLPvD4nR_9XRl6S45nAGFTzmc40)
> 
> Che ne pensi?

Penso che se c'è un problema con https://github.com/OCA/l10n-italy/pull/3129 sarebbe da segnalare lì facendo una revisione, oppure proponendo una correzione, oppure scrivendo che vuoi sostituirla con https://github.com/OCA/l10n-italy/pull/3841.

Non ho seguito molto quale sia il problema nello specifico o come sia stato corretto, sto solo cercando di organizzare le PR e le issues coinvolte per non duplicare il lavoro.

Se la issue/PR è duplicata sarebbe meglio chiuderne una e proseguire il lavoro in una sola issue/PR.

**Comment by SirAionTech** [comment]
Chiudo perché l'unica versione che ha ancora il problema non è più supportata
