### ISSUE TITLE
[14.0] l10n_it_withholding_tax non aggiunge ritenuta se parto da ordine di vendita

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3856]
Creare una posizione fiscale con ritenuta d'acconto.
Creare un ordine di vendita per un cliente con la posizione fislcae appena create.
Creare la fattura a partiure dall'ordine di vendita, la stessa non contiene la ritenuta d'acconto.

Diversamente se parto dalla fattura e richiamo il lciente, la ritenuta viene correttamente applicata.

Il problema impatta ordini di vendita e abbonamenti in EE

https://app.screencastify.com/v3/watch/SbAr0kQlU7sPhoxLqojb

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Purtroppo il video è tagliato e non si vede nulla di utile

**Comment by francescapenso** [comment]
Domattina riedito il video, sorry

**Comment by francescapenso** [comment]
https://app.screencastify.com/v3/watch/SbAr0kQlU7sPhoxLqojb

**Comment by francescapenso** [comment]
vi viene in mente qualche workaround per gestire la situazione?

**Comment by francescapenso** [comment]
aggiornamento. Lo stesso problema si verifica in caso di Split Payment.

**Comment by SirAionTech** [comment]
> @SirAionTech dopo il video rifatto è più chiaro?

Sì grazie, lo puoi sostituire al video tagliato nella descrizione della issue?

**Comment by francescapenso** [comment]
Simone video sistemato nella descrizione
