### ISSUE TITLE
l10n_it_instrastat modifica il funzionamento di action_post bloccando account_financial_risk

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#3858]
## Module
l10n_it_instrastat

## Describe the bug
Il popup esteso di account_financial_risk non appare quando dovrebbe

## To Reproduce
**Affected versions**:
- [x] 14.0: #3857 
- [ ] 16.0: #4311

1. impostare il blocco per il rischio finanziario sulle fatture di un partner con un massimale
2. creare una fattura per il partner con un importo che supera il massimale
3. validare la fattura

**Expected behavior**
Appare l'avviso di blocco esteso con i dettagli:
![Screenshot(218)](https://github.com/OCA/l10n-italy/assets/7657311/37ea9376-64f7-4857-b233-709afb6018db)

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by SirAionTech** [comment]
@sergiocorato potrebbe essere https://github.com/OCA/l10n-italy/labels/good%20first%20issue, che ne dici?
