### ISSUE TITLE
[l10n_it_delivery_note] Creazione DDT da ordini di consegna con source location_id differenti 

### ISSUE THREAD

**Issue by Rohzen** [OCA/l10n-italy#3868]
Il modulo l10n_it_delivery_note controlla che l'ubicazione di origine di due trasferimenti, dei quali voglio fare il ddt, sia identica.
Potrei voler fare un ddt prelevando da due magazzini differenti.

**Comment by francesco-ooops** [comment]
Ciao @Rohzen , proponi pure una PR con la modifica richiesta
