### ISSUE TITLE
[16.0] | Partita IVA extra UE non riconosciuta.

### ISSUE THREAD

**Issue by mlopesbjj** [OCA/l10n-italy#3878]
Buongiorno,

Ho provato ad aggiungere un cliente extra UE nella anagrafica contatti, mettendo anche la partita IVA extra UE, necessaria per la fatturazione elettronica, ma il sistema non riconosce il cod OO99999999999, poichè segnala che il formato deve essere diverso (9 digits).

![2024-01-22 16_04_01-Posta](https://github.com/OCA/l10n-italy/assets/48922995/07b3486c-4c49-4abc-a80d-804981188d31)
Come devo procedere?

**Comment by tafaRU** [comment]
Riapri pure nel caso il problema dovesse riproporsi.
