### ISSUE TITLE
[RFC] Codice fiscale in odoo/odoo

### ISSUE THREAD

**Issue by odooNextev** [OCA/l10n-italy#3912]
**Is your feature request related to a problem?**
Attualmente `OCA/l10n-italy` e `odoo/odoo` aggiungono entrambi un campo per il codice fiscale con nome diverso e soprattutto `odoo/odoo` lo aggiunge solo se si installa la fatturazione elettronica tramite il modulo `l10n_it_edi`.

**Describe the solution you'd like**

- [x] ~~Spostare il campo `l10n_it_codice_fiscale` nel modulo base `l10n_it`~~: non è nelle priorità di Odoo SA e di fatto anche noi della comunità ci agganceremo a `l10n_it_edi`
- [x] Verificare che `l10n_it_codice_fiscale` faccia gli stessi controlli sulla validità del campo che attualmente fa `l10n_it_fiscalcode`
Rifiuta "AAAAAA00A00A000A"

**Comment by odooNextev** [comment]
@lordkrandel non è mai stata presa in considerazione l'idea di spostare il campo `l10n_it_codice_fiscale` nel modulo base `l10n_it` invece che tenerlo in `l10n_it_edi`?
Ne avevamo già parlato, ma non so se anche con te, però il codice fiscale è un'informazione di anagrafica che può servire anche senza fatturazione elettronica.

**Comment by lordkrandel** [comment]
Sì, certo, se n'è parlato...

Non so quanto sia prioritario internamente visto che `l10n_it_edi` si installa da solo.

Molti dei dati di `l10n_it_edi` in realtà andrebbero in `l10n_it`.
Ad esempio non è che il calcolo della ritenuta sia proprio proprio legato all'invio all'Agenzia delle entrate, no?
