### ISSUE TITLE
[16.0] fatturapa_out crasha durante update

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#3914]
durante l'update del database ottengo

```
    if env.cr.fetchall()[0]:
IndexError: list index out of range
```

la query precedente eseguita nel mio database, restituisce 0 righe
credo che il codice sia da adattare in questo modo

```
    result = env.cr.fetchall()

    if result and result[0]:
```

https://github.com/OCA/l10n-italy/blob/e8ff59760fba263a48352783d7ca6e53f056c205/l10n_it_fatturapa_out/migrations/16.0.1.0.9/pre-migrate.py#L23

**Comment by francesco-ooops** [comment]
Risolta da https://github.com/OCA/l10n-italy/pull/3696
