### ISSUE TITLE
l10n_it_central_journal_reportlab: esclude linee con account name o code non valorizzato

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#3922]
Come da descrizione

**Affected versions**:

- [x] 14.0 #3250 
- [ ] 16.0

**Comment by SirAionTech** [comment]
La correzione per `16.0` è https://github.com/OCA/l10n-italy/pull/4290.
Sono approcci diversi, ma entrambi risolvono praticamente lo stesso problema.
