### ISSUE TITLE
l10n-italy /l10n_it_intrastat_statement

### ISSUE THREAD

**Issue by mlopesbjj** [OCA/l10n-italy#3948]
Nella versione 16.0 in SH la stampa dei modelli non stampano corretamente.
invio degli esempi.

![image](https://github.com/OCA/l10n-italy/assets/48922995/d9457391-870a-4077-9123-36e681a5da73)

![image](https://github.com/OCA/l10n-italy/assets/48922995/15b80e8c-d780-42ff-a153-7fca608073d5)

- [ ] 14; no (verificato da @francesco-ooops )
- [ ] 16: https://github.com/OCA/l10n-italy/pull/4030

**Comment by francesco-ooops** [comment]
@mlopesbjj il problema è solo su odoo.sh o è riproducibile anche su runboat OCA?

**Comment by mlopesbjj** [comment]
Non ho provato su runboat OCA.

**Comment by francesco-ooops** [comment]
@mlopesbjj puoi provare? :)

**Comment by mlopesbjj** [comment]
Siccome non ho mai usato runboat non so neanche come farlo.

**Comment by francesco-ooops** [comment]
No problem! Runboat è l'istanza di testing OCA di tutti i moduli presenti in una determinata repo, qui un video su come accedere: http://recordit.co/QChmhz9XbE

riprodurre l'errore con passi chiari in un'istanza "pulita" e condivisa aiuta molto ad avvicinarsi alla risoluzione

**Comment by mlopesbjj** [comment]
Ciao, grazie per la risposta, ma non ho trovato l'opzione nel menu su RUNBOAT.
il problema è proprio nella stampa. Modello INTRA 1 BIS - MODELLO INTRA 2 BIS



[12.zip](https://github.com/OCA/l10n-italy/files/14246755/12.zip)

**Comment by francesco-ooops** [comment]
@mlopesbjj segui le istruzioni del modulo: https://github.com/OCA/l10n-italy/blob/16.0/l10n_it_intrastat_statement/readme/USAGE.rst

> N.B.: il menù "Contabilità" è visibile solo se vengono abilitate le funzionalità contabili complete.

Devi andare in impostazioni > gruppi > aggiungere Mitchell Admin al gruppo "Show full accounting features" (sarebbe bello se il runboat lo facesse in automatico)

da lì stampi il modello ed effettivamente si riproduce l'errore: 

![image](https://github.com/OCA/l10n-italy/assets/55489873/69561d78-514b-4879-8123-c209cc5817ae)

**Comment by mlopesbjj** [comment]
Grazie per aver insegnato come utilizzare runbot e per la pazienza.

**Comment by francesco-ooops** [comment]
Di nulla! :)
