### ISSUE TITLE
|16.0| account_vat_period_end_statement

### ISSUE THREAD

**Issue by fedecarraro** [OCA/l10n-italy#3961]
Buongiorno,
nella descrizione del modulo viene indicato quanto segue:
A seguito dell’introduzione della normativa OSS, per chi fa vendite online su diversi paesi, deve necessariamente escludere dalla liquidazione iva ciò che farà parte della liquidazione OSS. E’ stato introdotto un nuovo campo per filtrare le imposte da elaborare, quindi va indicato il conto configurato nelle imposte “Conto utilizzato per la liquidazione IVA”.

Però nella finestra non ho trovato nessuna opzione per fare questa operazione. Dove o come posso trovare questo campo?

![image](https://github.com/OCA/l10n-italy/assets/160120296/d5c73f6f-6552-4cfc-bb69-ef8fa263c4e3)

Grazie per la disponibilità
Federica

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Quella parte del README è stata aggiunta in https://github.com/OCA/l10n-italy/pull/3468 quindi forse lì puoi trovare qualche informazione in più.
A prima vista direi che il campo cui ci si riferisce è nelle imposte e va configurato come indicato in https://github.com/OCA/l10n-italy/tree/feebc9e28273c24aa994ac9e592b3c02f52303c0/account_vat_period_end_statement#configuration:
> 1. aprire l'imposta da Fatturazione > Configurazione > Contabilità > Imposte,
> 2. nella scheda 'Opzioni avanzate' selezionare il conto corretto (ad esempio IVA debito) per il campo 'Conto utilizzato per la liquidazione IVA'. Se si è soggetti a liquidazione OSS indicare un conto dedicato (ad esempio IVA debito OSS Francia)

Se pensi che la descrizione si possa migliorare, puoi proporre la modifica a uno dei file in https://github.com/OCA/l10n-italy/tree/feebc9e28273c24aa994ac9e592b3c02f52303c0/account_vat_period_end_statement/readme.

**Comment by fedecarraro** [comment]
Buongiorno,
a me non sembra chiara questa parte:
"A seguito dell’introduzione della normativa OSS, per chi fa vendite online
su diversi paesi, deve necessariamente escludere dalla liquidazione iva ciò
che farà parte della liquidazione OSS. E’ stato introdotto un nuovo campo
per filtrare le imposte da elaborare, quindi va indicato il conto
configurato nelle imposte “Conto utilizzato per la liquidazione IVA”.
Quindi selezionare il conto IVA debito per elaborare liquidazione iva su
tutte le imposte che hanno in configurazione il conto IVA debito. Per la
liquidazione OSS invece selezionare conto dedicato ad esempio IVA debito
OSS Francia. E’ necessario creare un periodo di dichiarazione IVA dedicato
all’OSS . Per caricare invece tutte le imposte che hanno un conto per la
liquidazione IVA, è sufficiente lasciare vuoto il filtro per conti".

come faccio escludere ad esempio l'iva OSS dalla dichiarazione se non trovo
il campo per  campo per filtrare le imposte da elaborare?

Attendo vostre,

Grazie
Federica


*Dott.ssa Federica Carraro*

*Tel:* 0444 021675

*Cell: *320 7587700

*Email: ***@***.***

*Website:* www.khps.it

*KH Project&Solutions Srl - *Galleria Crispi, 41 - 36100 Vicenza

Registro Imp. e PI: 03753460249 - Cap. Soc: 30.000 €

*Nota di riservatezza:* il presente messaggio e ogni suo allegato
contengono informazioni strettamente riservate. Unico soggetto legittimato
ad usarlo, copiarlo e, sotto la propria responsabilità, diffonderlo è
esclusivamente il destinatario sopra indicato. Chiunque ricevesse questo
messaggio per errore è informato che trattenerlo, copiarlo, diffonderlo a
persone diverse dal destinatario è severamente proibito, ed è pregato di
rinviarlo immediatamente al mittente distruggendone l'originale.



Il giorno gio 15 feb 2024 alle ore 12:08 Simone Rubino <
***@***.***> ha scritto:

**Comment by SirAionTech** [comment]
Capito, ho trovato https://github.com/OCA/l10n-italy/issues/3872 che mi sembra si occupi proprio di quello che chiedi, al momento è già stato fatto qualcosa per `12.0` (https://github.com/OCA/l10n-italy/pull/2385) e c'è una proposta per `14.0` (https://github.com/OCA/l10n-italy/pull/2536).

Direi che si può continuare lì.
