### ISSUE TITLE
[16.0] fatturapa_out TD01 con iva negativa non viene esportata correttamente e viene scartata da ADE

### ISSUE THREAD

**Issue by francescapenso** [OCA/l10n-italy#3976]
Creare una fattura con 2 righe
1) prodotto con iva a 0 (es. ristrutturazioni N6.7) 
2) storno di un acconto con iva al 22%

Allego immagini e codice di scarto ADE 

I conti sono corretti ma in xml l'iva non è con il segno negativo, la ft viene scartata da ADE
![image](https://github.com/OCA/l10n-italy/assets/19937703/9670e818-9074-4e9a-b57d-7bd96b157f59)
![image](https://github.com/OCA/l10n-italy/assets/19937703/53c12c76-fce8-4279-bcc2-15b089f21de9)

![image](https://github.com/OCA/l10n-italy/assets/19937703/03706233-1733-4496-b5b4-e1dc9696a8f2)
![image](https://github.com/OCA/l10n-italy/assets/19937703/8b54e350-6fcd-4dce-8484-b47dfa0609f9)

**Comment by francescapenso** [comment]
no update?

**Comment by SirAionTech** [comment]
Forse è duplicata di https://github.com/OCA/l10n-italy/issues/3670?

**Comment by francescapenso** [comment]
@SirAionTech sto leggendo ma mi pare di si

**Comment by francesco-ooops** [comment]
Chiudo perchè duplicata
