### ISSUE TITLE
[16.0] porting  l10n_it_fatturapa_out_welfare

### ISSUE THREAD

**Issue by DigitalAutomations** [OCA/l10n-italy#3993]
Ciao qualcuno ha in carico questa?
Oppure esiste un modo per gestire la cassa previdenziale? (es. ingegneri)

**Comment by SirAionTech** [comment]
Nessuno ha in carico la migrazione, puoi verificare in https://github.com/OCA/l10n-italy/issues/2967.

A quanto ne so, la cassa previdenziale si gestisce con il modulo delle ritenute:
https://github.com/OCA/l10n-italy/blob/25a54ccdfb22e6645ecd58a88cee8ded03bd4007/l10n_it_withholding_tax/models/withholding_tax.py#L80-L97

il modulo in oggetto serve a gestire la cassa previdenziale nelle fatture elettroniche in uscita.

Se ne parla anche in https://github.com/OCA/l10n-italy/issues/1924 e https://github.com/OCA/l10n-italy/issues/2766.

**Comment by francescapenso** [comment]
Grazie allora devo aver sbagliato qualcosa nella configurazione....perchè la cassa previdenzial ein alcuni casi prevee che venga calcolata l'iva anche sulla cassa

**Comment by odooNextev** [comment]
@DigitalAutomations ho appena finito la migrazione
Vuoi testarla?
https://github.com/OCA/l10n-italy/pull/4410

**Comment by SirAionTech** [comment]
Il modulo è in fase di migrazione in #4410

**Comment by apalazzi** [comment]
@SirAionTech l'issue è stata chiusa come completa ma la PR è in stato  "stale" e nel repository ramo 16.0 il modulo l10n_it_fatturapa_out_welfare non c'è... qual è la situazione?
