### ISSUE TITLE
[8.0] Electronic Invoice (FatturaPA)

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#4]
Odoo should be able to export invoices in FatturaPA XML format.
Needed for those who invoice public administrations in Italy from now on.

Some official infos: http://www.fatturapa.gov.it/export/fatturazione/it/a-2.htm

**Comment by silvioco** [comment]
Scusate se mi introduco che sappiate dirmi il modulo fatturapa esiste per la versione Odoo 8?
Sto facendo delle prove per installare la fatturapa 7  sulla 8 ma nulla da fare. Ho cercato di apportare delle modifiche ma non essendo un programmatore, ammetto che sto andando a tentoni.
Grazie dell'attenzione

**Comment by dcorio** [comment]
@silvioco https://github.com/OCA/l10n-italy/pull/98

**Comment by silvioco** [comment]
Da quello che capisco bisogna attendere perchè in fase di sviluppo giusto?

**Comment by dcorio** [comment]
@silvioco puoi comunque testarlo e dare il tuo feedback. anche se completi i moduli non vengono introdotti nella localizzazione se non dopo opportuni test.

**Comment by silvioco** [comment]
Grazie mile Davide proverò a testarlo

**Comment by eLBati** [comment]
Chiudo poichè aggiunto con https://github.com/OCA/l10n-italy/pull/137
