### ISSUE TITLE
Wrong translation Debit Credit

### ISSUE THREAD

**Issue by zeroincombenze** [OCA/l10n-italy#400]
(en)
Accounting > Adviser >Journal Entries

In Italian localization views show Debito/Credito as literal transaltion of Debit/Credit
In Italy, when Debit and Credit refer to Journal Entries, right translation MUST BE
Debit ->Dare
Credit -> Avere

Please correct soon.

Thanks
(it)
Contabilità > Contabilità > Registrazioni sezionali
appaiono le colonne Debito e Credito invece che Dare e Avere

Segnalo ai traduttori che la corretta traduzione in Italiano di Debit è Dare quando riferisce una registrazione contabile e la traduzione di Credit è Avere quando riferisce una registrazione contabile.
I testi così come sono impostati sono fuorvianti

Per favore correggere al più presto.
Grazie

**Comment by eLBati** [comment]
Ciao @zeroincombenze se i termini da correggere sono su moduli odoo cose, è possibile tradurli tramite https://www.transifex.com/odoo/
Se su OCA, https://www.transifex.com/oca/

Se vuoi provare a tradurre e riscontri difficoltà, fammi sapere.
Grazie

**Comment by paolovalier** [comment]
corretto da tafaRU:
https://www.transifex.com/odoo/odoo-10/translate/#it/$/96742658
https://www.transifex.com/odoo/odoo-10/translate/#it/$/96741369
credo si possa chiudere

**Comment by zeroincombenze** [comment]
ok
