### ISSUE TITLE
Le ricevute bancarie relative a fatture non emesse non dovrebbero essere visibili nella lista delle ri.ba. da emettere

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#4000]
## Module
l10n_it_ricevute_bancarie

## Describe the bug
Nel menu ri.ba. da emettere sono visibili e selezionabili le ri.ba. relative a fatture in bozza.

## To Reproduce
**Affected versions**:
- [ ] 14.0: #3759 
- [ ] 16.0:

1. creare una fattura in bozza con modalità di pagamento ri.ba.
2. andare nel menu di emissione ri.ba.
3. la ri.ba. è visibile e selezionabile

**Expected behavior**
La ri.ba. non è visibile.

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by francesco-ooops** [comment]
@sergiocorato chiudiamo questa e la sua PR in favore di #4150?

**Comment by sergiocorato** [comment]
Ok
