### ISSUE TITLE
legame tra fiscal position e journal

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#401]
Ciao a tutti,
esiste la possibilità di legare i journal ammessi ad una fiscal position?
grazie
claudio candito

**Comment by eLBati** [comment]
Cioè, qual è il caso d'uso? Riguarda un modulo di localizzazione?

**Comment by ccandito** [comment]
Ciao,
mi riferisco all'inserimento di una fattura passiva,
Sarebbe auspicabile che ci fosse un collegamento tra il fiscal position
(determinato automaticamente dal PO e Vendor master data) e i journal
ammessi.
In questo modo non è possibile commettere errori nella selezione del
journal.
In contabilità come localizzazione esiste il legame tra registro IVA e
journal, manca quindi, secondo me, questo ultimo pezzo.
Grazie
claudio candito

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Mail
priva di virus. www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2017-11-13 10:28 GMT+01:00 Lorenzo Battistini <notifications@github.com>:

**Comment by eLBati** [comment]
Ok. No, non sono a conoscenza di un modulo che offra tale funzionalità

**Comment by ccandito** [comment]
Ciao,
e' prevista una implementazione di questa funzionalita' nella localizzazione italiana?
grazie
claudio
