### ISSUE TITLE
Nuova installazione  - Fatturazione elettronica - modalità: Ufficiale. Operazione non valida ("A user already exists with this identification.")

### ISSUE THREAD

**Issue by amazonaward** [OCA/l10n-italy#4010]
## Module
l10n_it_edi
## Describe the bug
Dopo aver fatto test su un server dedicato ho re-installato Odoo con il modulo in questione per la fatturazione elettronica. 
Server ubuntu di nuova installazione
versione Odoo 17 di nuova installazione.

1)Installato il modulo l10n_it_edi. 
2) impostato dati aziendali in impostazioni
3) provando a impostare in Impostazione-> Fatturazione->Fatturazione elettronica italiana-> Modalità: Ufficiale e provando a salvare viene l'errore in oggetto:  

![image](https://github.com/OCA/l10n-italy/assets/27741022/c48461c1-5b05-4a07-b165-f7d8a3c3406a)

E' possibile che i dati user/company siano salvati su qualche server OCA?

Il log dice quanto segue:

odoo  | 2024-03-03 12:57:22,170 1 WARNING odoo odoo.http: A user already exists with this identification. 
odoo  | 2024-03-03 12:57:22,170 1 INFO odoo werkzeug: 192.168.1.107 - - [03/Mar/2024 12:57:22] "POST /web/dataset/call_kw/res.config.settings/web_save HTTP/1.1" 200 - 181 0.048 1.061
odoo  | 2024-03-03 13:01:29,907 1 INFO odoo odoo.addons.base.models.ir_cron: Starting job `payment: post-process transactions`. 
odoo  | 2024-03-03 13:01:29,920 1 INFO odoo odoo.addons.base.models.ir_cron: Job done: `payment: post-process transactions` (0.012s). 
odoo  | 2024-03-03 13:05:51,670 1 WARNING odoo odoo.http: A user already exists with this identification. 
odoo  | 2024-03-03 13:05:51,671 1 INFO odoo werkzeug: 192.168.1.107 - - [03/Mar/2024 13:05:51] "POST /web/dataset/call_kw/res.config.settings/web_save HTTP/1.1" 200 - 181 0.049 0.911
## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by SirAionTech** [comment]
Il modulo **l10n_it_edi** per `17.0` non è sviluppato in questo repository ma in https://github.com/odoo/odoo/tree/cb45934163c5ab3bbd9ab36c1e9ff96a13c3e325/addons/l10n_it_edi quindi dovresti aprire una issue lì.

**Comment by TheMule71** [comment]
Chiudo perché la issue non riguarda `OCA/l10n-italy`.

Vd.
https://github.com/odoo/odoo/tree/17.0/addons/l10n_it_edi
