### ISSUE TITLE
Retrodatare detrazione iva fatture 

### ISSUE THREAD

**Issue by Marianna-Marasco** [OCA/l10n-italy#4034]
**Is your feature request related to a problem?**
Retro-imputare al mese di effettuazione l’IVA detraibile relativa ai documenti di acquisto ricevuti e annotati entro il 15 del mese successivo (ad eccezione delle fatture di acquisto relative a operazioni effettuate nell’anno precedente)

**Describe the solution you'd like**
Un ulteriore campo "data iva" in fattura fornitore per far confluire l'iva del documento nel periodo precedente rispetto a quello di ricezione/registrazione
Un di più, richiesto da un cliente e che riporto perchè potrebbe essere utile, sarebbe avere sui registri iva un campo note per evidenziare le fatture confluite nella liquidazione del periodo precedente (per fini di controllo tra iva risultante dai registri iva e iva liquidata nel periodo)

**Additional context**
Questione già discussa nella issue https://github.com/OCA/l10n-italy/issues/1183 e https://github.com/OCA/l10n-italy/pull/1613

Numerazione dei documenti
L'obbligo di numerazione delle fatture ricevute è stato abrogato dall'[art. 13] del DL 119/2018, con decorrenza dal 24.10.2018.
Resta fermo l'obbligo di attribuire un ordine progressivo alle registrazioni (circ. [14/E/2019]).
Detrazione dell'IVA
Il d.l. n. 119 (cfr. l'[articolo 14]) ha operato anche in tema di detrazioni IVA, modificando l'[articolo 1], comma 1, del decreto del Presidente della Repubblica 23 marzo 1998, n. 100, il quale ora dispone che «entro il giorno 16 di ciascun mese, il contribuente determina la differenza tra l'ammontare complessivo dell'imposta sul valore aggiunto esigibile nel mese precedente, risultante dalle annotazioni eseguite o da eseguire nei registri relativi alle fatture emesse o ai corrispettivi delle operazioni imponibili, e quello dell'imposta, risultante dalle annotazioni eseguite, nei registri relativi ai beni ed ai servizi acquistati, sulla base dei documenti di acquisto di cui è in possesso e per i quali il diritto alla detrazione viene esercitato nello stesso mese ai sensi dell'[articolo 19]del decreto del Presidente della Repubblica 26 ottobre 1972, n. 633. Entro il medesimo termine di cui al periodo precedente può essere esercitato il diritto alla detrazione dell'imposta relativa ai documenti di acquisto ricevuti e annotati entro il 15 del mese successivo a quello di effettuazione dell'operazione, fatta eccezione per i documenti di acquisto relativi ad operazioni effettuate nell'anno precedente. Si applica anche a coloro che liquidano l'imposta con cadenza trimestrale.
Fonte: https://www.eutekne.it

Implementazioni fatte:
- [x] `14.0`: #4338 
- [x] `16.0`: https://github.com/OCA/l10n-italy/pull/4062

**Comment by TheMule71** [comment]
Vd. anche https://github.com/OCA/l10n-italy/pull/2208
