### ISSUE TITLE
[BUG] Codifica errata dei caratteri speciali nell'anteprima delle fatture XML

### ISSUE THREAD

**Issue by odooNextev** [OCA/l10n-italy#4039]
## Module
`l10n_it_fatturapa`

## Describe the bug
Nell'anteprima della fattura (sia standard che Assosoftware) non vengono codificati correttamente i caratteri speciali (è, é, à, ecc) sia nelle label che nei valori inseriti dagli utenti.

## To Reproduce
**Affected versions**:

- [x] 14.0: no
- [ ] 16.0: https://github.com/OCA/l10n-italy/pull/4045

1. Aprire un runboat di l10n-italy
2. Fatturazione -> fornitori -> file e-fatture in ingresso
3. Aprire un record (probabilmente bisogna togliere "da registrare")
4. Cliccare "mostra anteprima"

![image](https://github.com/OCA/l10n-italy/assets/93990941/5e5ba6b9-b604-405d-b588-d0ecfccb0803)

5. Fatturazione -> configurazione -> impostazioni
6. Raggiungere il paragrafo "Fatture elettroniche"
7. Impostare "assosoftware" nello stile formato di anteprima
8. tornare in Fatturazione -> fornitori -> file e-fatture in ingresso
9. aprire un record (probabilmente bisogna togliere "da registrare")
10. Cliccare "mostra anteprima"

![image](https://github.com/OCA/l10n-italy/assets/93990941/73b6644a-e383-49ce-8387-29f673ad3db9)

**Comment by odooNextev** [comment]
Qua c'è l'encoding, ma non mi sembra sbagliato: https://github.com/OCA/l10n-italy/blob/16.0/l10n_it_fatturapa/models/ir_attachment.py#L130

**Comment by TheMule71** [comment]
> Qua c'è l'encoding, ma non mi sembra sbagliato: https://github.com/OCA/l10n-italy/blob/16.0/l10n_it_fatturapa/models/ir_attachment.py#L130

Infatti a naso mi pare più problema di encoding del preview. L'XML dovrebbe essere a posto.

**Comment by stenext** [comment]
> Infatti a naso mi pare più problema di encoding del preview. L'XML dovrebbe essere a posto.

Esatto, i caratteri più usati vengono rappresentati correttamente nel XML.
Non so però se è giusto che l'apostrofo "al contrario" usato nella descrizione di default del prodotto "imposta di bollo 2 euro" (come segnalavo ieri in https://discord.com/channels/753902328494424064/822435512391303209) viene sostituito con "?".
Immagino ci sia da seguire una particolare codifica per standardizzare il file XML, quindi alcuni caratteri credo sia normale vengano "inibiti".

**Comment by stenext** [comment]
@matteoopenf purtroppo non sono molto esperto di codifiche, ma sto indagando, un po' perchè l'hanno notato anche i clienti e un po' perchè volevo proporre la PR su odoo/odoo per vedere gli allegati con l10n_it_edi prendendo spunto da questo codice, ma questo problema è penalizzante.
Ma la cosa che mi lascia perplesso è che sembra essere `request.env["ir.actions.report"]._run_wkhtmltopdf([html])` a non interpretare correttamente i caratteri speciali ed è un metodo di Odoo standard...
Forse bisogna passargli qualche parametro o magari posso provare a renderizzare direttamente l'HTML invece che creare un PDF

**Comment by matteoopenf** [comment]
> @matteoopenf purtroppo non sono molto esperto di codifiche, ma sto indagando, un po' perchè l'hanno notato anche i clienti e un po' perchè volevo proporre la PR su odoo/odoo per vedere gli allegati con l10n_it_edi prendendo spunto da questo codice, ma questo problema è penalizzante. Ma la cosa che mi lascia perplesso è che sembra essere `request.env["ir.actions.report"]._run_wkhtmltopdf([html])` a non interpretare correttamente i caratteri speciali ed è un metodo di Odoo standard... Forse bisogna passargli qualche parametro o magari posso provare a renderizzare direttamente l'HTML invece che creare un PDF

apri una issue su Odoo, magari spunta qualche info utile, ora ti ritrovo la mia essendo un problema simile

**Comment by matteoopenf** [comment]
@odooNextev https://github.com/odoo/odoo/issues/140145 ecco la mia di issue se puo' aiutare

**Comment by stenext** [comment]
> @odooNextev [odoo/odoo#140145](https://github.com/odoo/odoo/issues/140145) ecco la mia di issue se puo' aiutare

Ho controllato ed in locale era già presente `fonts-dejavu-core`

**Comment by matteoopenf** [comment]
> > @odooNextev [odoo/odoo#140145](https://github.com/odoo/odoo/issues/140145) ecco la mia di issue se puo' aiutare
> 
> 
> 
> Ho controllato ed in locale era già presente `fonts-dejavu-core`

Allora il problema è altrove apri la issue e vediamo se viene fuori qualcosa

**Comment by SirAionTech** [comment]
In `14.0` non succede: 
![image](https://github.com/OCA/l10n-italy/assets/143788994/43f88d9e-8282-4149-a6fc-2fe3b6406eb0)
 (da http://oca-l10n-italy-14-0-b47232dba4bb.runboat.odoo-community.org/fatturapa/preview/596)

Confermo che in `16.0` succede: 
![image](https://github.com/OCA/l10n-italy/assets/143788994/c503f7c7-12f7-4150-ac22-7cc10666a33f)
 (da http://oca-l10n-italy-16-0-a7ccab05455a.runboat.odoo-community.org/fatturapa/preview/566)

**Comment by stenext** [comment]
@SirAionTech grazie per la segnalazione, ho aggiornato le versioni coinvolte nella issue.
Tu, @TheMule71 o @eLBati sapete magari perchè è stato preferito creare un report PDF invece che renderizzare direttamente l'HTML come viene fatto anche da altre parti in Odoo con "report HTML"?

**Comment by SirAionTech** [comment]
> @SirAionTech grazie per la segnalazione, ho aggiornato le versioni coinvolte nella issue. Tu, @TheMule71 o @eLBati sapete magari perchè è stato preferito creare un report PDF invece che renderizzare direttamente l'HTML come viene fatto anche da altre parti in Odoo con "report HTML"?

Non credo ci fosse un motivo particolare, da altre parti (tipo https://github.com/odoo/odoo/blob/35d0af1a9f197a5da1c31ed10f21b59dfc245581/addons/website_sale/controllers/main.py#L1621) viene anche ritornato un PDF.
Il commit che aggiunse quella parte è https://github.com/OCA/l10n-italy/commit/f3652eb5f861a55efbec0788afa948ba3b238b39, ma non ci ho trovato nulla di particolare sul link dell'anteprima.

Per me si può anche cambiare e restituire invece un HTML (chi vuole poi si stampa il PDF dal browser).

**Comment by odooNextev** [comment]
@francesco-ooops ho aggiunto la PR
