### ISSUE TITLE
l10n_it_fiscalcode - Cambiando tipologia del partner non viene eseguito il controllo del CF

### ISSUE THREAD

**Issue by primes2h** [OCA/l10n-italy#4050]
## Module
l10n_it_fiscalcode

## Describe the bug
Partendo da un partner di tipo azienda con un CF non corretto e cambiandone la tipologia in persona fisica, al salvataggio non viene eseguito alcun controllo.
Rif. https://github.com/OCA/l10n-italy/pull/3724#issuecomment-1994632663

## To Reproduce
**Affected versions**:

Tutte.

 - [x] v12: il bug è stato scoperto inizialmente in questa versione (risolta per termine supporto)
 - [ ] v14: https://github.com/OCA/l10n-italy/pull/4180
 - [X] v16: #4076 

1. Aprire un partner di tipo azienda
2. Se il campo CF è già valorizzato e non conforme alle specifiche per le persone fisiche (es. P. IVA) non modificarlo, se è vuoto inserire un CF non conforme.
3. Cambiare la tipologia del partner in persona fisica
4. Salvare il partner
5. Il partner viene salvato senza notifiche di errore.

**Expected behavior**
Dovrebbe scattare il controllo del CF.

**Comment by SirAionTech** [comment]
Ho verificato che il problema è presente in `16.0`.
