### ISSUE TITLE
[16.0] l10n_it_fatturapa_out - Export Electronic Invoice list all actions instead of reports

### ISSUE THREAD

**Issue by mde-spring** [OCA/l10n-italy#4055]
## Module
l10n_it_fatturapa_out 

## Describe the bug
Selection list displays all ir.actions.actions instead of only ir.actions.report

## To Reproduce
**Affected versions**: 

- [x] 14.0: no
- [ ] 16.0: #4056 

1. Accounting, open an invoice
2. Action > Export Electronic Invoice
3. List available contains  ir.actions.actions 
![image](https://github.com/OCA/l10n-italy/assets/79934758/5a10f71d-3e6c-406d-af06-8f179a89b613)

**Expected behavior**
Only ir.actions.report must appear in the list

**Comment by francesco-ooops** [comment]
@mde-spring could you check if this is applicable to v14 as well? thanks!

**Comment by mde-spring** [comment]
@francesco-ooops no impact in v14
Initial rework comes from v16, with commit https://github.com/OCA/l10n-italy/commit/8621573ec2b5495dfe7c9e34fa5ad95709871799
