### ISSUE TITLE
Il campo `discount` non esiste

### ISSUE THREAD

**Issue by danielelucarelli1980** [OCA/l10n-italy#406]
Per installare il modulo devo prima abilitare lo sconto sulle righe d'ordine nelle preferenze dell'utente che sto utilizzando.
Seguendo le indicazioni di gigidn ho risolto, le riporto di seguito:

Il modulo DDT fa riferimento al campo discont che è presente solo se abiliti lo sconto nelle linee d'ordine ma nella configurazione in cui ti trovi lo sconto sulle linee d'ordine non è abilitato.

Prova a riabilitarlo ed eventualmente fai un -u all.

Se è questo il problema e si risolve fai anche una issue su github in modo tale che al prossimo aggiornamento venga messa la dipendenza o spostato il campo di aggancio sulla vista.

**Comment by eLBati** [comment]
Ciao @danielelucarelli1980 , quali sono i passi per riprodurre il problema? Su che versione di odoo?

**Comment by tafaRU** [comment]
Chiudo causa inattività.
