### ISSUE TITLE
l10n_it_delivery_note: use recipient language

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#4068]
## l10n_it_delivery_note

**Affected versions**:

 - [ ] 14.0 https://github.com/OCA/l10n-italy/pull/4069
 - [ ] 16.0

Steps:

 - Install French
 - Create a french customer, setting french language
 - Create a product and translate its name to french
 - Create a delivery order
 - Create DDT

Observed:

DDT line description is in user's language

Desired:

DDT line description is in customer's language

**Comment by francesco-ooops** [comment]
@eLBati mia ignoranza, per i trasporti internazionali si usa il DdT?

cmq poi ci traduci il modulo eh 😛 https://translation.odoo-community.org/projects/l10n-italy-14-0/l10n-italy-14-0-l10n_it_delivery_note/fr/
