### ISSUE TITLE
Errore in duplicazione DDT

### ISSUE THREAD

**Issue by luca-vercelli** [OCA/l10n-italy#407]
Ho provato a fare "Duplica" su un DDT già completato e fatturato. Mi ha copiato anche il ddt_number e l'invoice_id! E a quel punto non mi lasciava più eliminare il nuovo documento.

Se qualcuno mi dice come si fa a *non* copiare uno o più attributi durante il "Duplica", potrei provare a risolvere io il problema.

**Edit:**
Curiosamente, invece, *non* mi ha copiato le righe di Dettaglio

**Comment by sergiocorato** [comment]
ciao,
va sovrascritto il metodo copy impostando a False i campi da non copiare
tipo

@api.multi
def copy(self, default=None):
    self.ensure_one()
    default = default or {}
    default['ddt_number'] = False
    return super(classe, self).copy(default)


Sergio Corato
cel. wsp +39 348 6622 725

Il giorno 15 novembre 2017 10:04, luca-vercelli <notifications@github.com>
ha scritto:

**Comment by luca-vercelli** [comment]
Grazie. Ma ho visto ora che qualcuno ha già corretto il baco prima di me.
FYI, è stato usato un approccio diverso, hanno aggiunto "copy=False" nella definizione del campo.
