### ISSUE TITLE
16.0 fatturapa_out Bug: Duplicazione Codice ISO nel Campo VAT Fatture Elettroniche per Clienti Esteri e San Marino con Partita IVA

### ISSUE THREAD

**Issue by maxgrassi** [OCA/l10n-italy#4078]
Il problema riguarda la duplicazione del codice ISO nella sezione Identificativo Fiscale delle fatture elettroniche emesse a clienti esteri con VAT number ad esempio fatture a Ditte EU con Vat number valido o a clienti (ditte) di San Marino.

In Odoo nel campo VAT si deve inserire il VAT number comprensivo del codice ISO della nazione, ad esempio: IT12345678901 oppure DE123456789.

Per quanto riguarda le fatture elettroniche emesse a clienti italiani, funziona correttamente, in fattura elettronica si legge: IT12345678901

Per quanto riguarda le fatture elettroniche emesse a clienti esteri, l'ISO è duplicato, in fattura elettronica si legge: DEDE123456789.

La problematica è emersa con San Marino, anche a San Marino sono passati in elettronico, e ci viene segnalato che la fattura non è arrivata in elettronico in quanto è stato indicato il codice “SMSM” 2 volte.

Da un controllo fatto sulle vecchie fatture inviate a clienti UE con VAT number (non emesse con ODOO) risulta che passano tramite SDI senza errore con il VAT number inserito correttamente: DE123456789.

Anche le fatture emesse con ODOO e con vat number con iso duplicato DEDE123456789 passano tramite SDI senza errori ma il problema si pone con San Marino in quanto pare che se l'ISO è duplicato la fattura elettronica non viene ricevuta.  

 Si suggerisce di inserire sempre il VAT number corretto in fattura elettronica per tutti i clienti che hanno il campo compilato.

Grazie

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4086
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/4085

**Comment by SirAionTech** [comment]
Grazie delle segnalazione!
Forse non è proprio lo stesso problema, ma è simile a https://github.com/OCA/l10n-italy/issues/3927.

**Comment by matteoopenf** [comment]
anche noi abbiamo avuto lo stesso problema per l'xml verso san marino, sul fatto che viene ripetuto SM, bisognerebbe gestire il caso altrimenti la fattura non la ricevono

**Comment by TheMule71** [comment]
Il codice "SM" non è stato inserito due volte, sono due campi diversi con dati diversi.

Tecnicamente, `IdPaese` è il Codice della nazione in formato ISO 3166-1 del cliente (versione 2 caratteri). Vd. https://it.wikipedia.org/wiki/ISO_3166-1_alpha-2

Il formato europeo delle partite iva prevede un prefisso di 2 caratteri che invece fa un mix tra ISO 639-1 (codici delle lingue, non dei paesi) e ISO_3166-1. Nelle specifiche delle localizzazioni spesso si vedono entrambi, en_US e en_GB or anche it_IT e it_CH.  Notare come it_IT non sia una inutile ripetizione, una è una lingua, l'altro un paese.

Perché l'EU abbia deciso di fare questo mix è un mistero. Sta di fatto che le PIVA della Gran Bretagna (non Regno Unito) sono GB-qualcosa (usando il codice ISO_3166-1) mentre quelle greche sono EL-qualcosa (usando il codice ISO 639-1 - il codice ISO_3166-1 sarebbe GR).

A ciò hanno anche aggiunto delle eccezioni:
1. le partite EU- qualcosa (i soggetti sono di paesi non EU).
2. se sei in EU e commerci con l'Irlanda del Nord allora la loro PIVA da GB-qualcosa diventa IX-qualcosa.

Inutile dire che EU e IX sono codici inventati che non fanno parte né di ISO 639-1 né di ISO_3166-1.


Allo SdI si sono persi il memo. Prob. hanno letto la prima riga della pagina di wikipedia ("The full identifier starts with an ISO 3166-1 alpha-2 country code") perdendosi il resto del paragrafo (https://en.wikipedia.org/wiki/VAT_identification_number) che spiega le differenze.

Pertanto hanno imposto che `IdPaese` sia un codice ISO 3166-1 - rendendo di fatto invalide le piva EU- IX- e EL- ai fini dell'XML.

Quanto ciò sia una "svista" è però difficile determinarlo. Nella documentazione ufficiale AdE, il campo `IdPaese` è così descritto: "IdPaese: codice del _paese assegnante_ l’identificativo fiscale al soggetto cessionario/committente"

Sembra ribadire che NON è il prefisso della piva. Vogliono veramente il codice ISO 3166-1 della paese che ha rilasciato la piva. Per es. nel caso della Grecia vogliono proprio GR e non EL.

Pertanto si è deciso si seguire le specifiche alla lettera. Il campo `IdPaese` NON viene preso dalla piva, ma dall'indirizzo del cliente, pertanto rispetta sempre le specifiche ISO 3166-1.  Nel caso di IT, `IdCodice` diventa la PIVA italiana privata di prefisso IT, come da documentazione.  In caso diverso nel campo `IdCodice` viene messa la PIVA completa... se ti tratta di piva europea, avrà il prefisso relativo.  Di fatto è una combinazione di lettere e numeri sulla quale non viene effettuato alcun controllo.

Se a San Marino hanno deciso di utilizzare il formato XML della Fattura PA del nostro SdI, dovrebbero rispettarne le specifiche, ed interpretare `IdPaese` come il codice paese (SM) e `IdCodice` come il loro codice C.E.O., completo di prefisso ("SM12345").

Detto ciò è poco pratico aspettersi che a San Marino cambino qualcosa, prendiamo atto che nel leggere una nostra f.e. si aspettano il loro C.E.O. privato del prefisso da loro scelto (notare che San Marino non è EU pertanto non è obbligato ad adottare il formato EU delle VAT, anche se la loro scelta è conforme).

Sto già lavorando alle PR per introdurre il caso particolare per San Marino.

- [x] 14.0 #4086
- [x] 16.0 #4085
