### ISSUE TITLE
[14.0][16.0] l10n_it_fatturapa: warning su ftpa_preview

### ISSUE THREAD

**Issue by TennyMkt** [OCA/l10n-italy#4087]
## Module
l10n_it_fatturapa

## Describe the bug
Facendo l'upgrade del modulo compare questo warning:

```
2024-04-09 07:24:33,860 125880 WARNING mktsrl odoo.addons.base.models.ir_ui_view: ftpa_preview on fatturapa.attachment has parameters and cannot be called from a button
 
View name: Form view for SdI file
Error context:
view: ir.ui.view(5717,)
xmlid: fatturapa_attachment_view_form
view.model: fatturapa.attachment
file: /home/odoo-user/odoo/14/application-env/oca-addons/l10n-italy/l10n_it_fatturapa/views/fatturapa_attachment_views.xml
```

Mi sembra errato che la funzione `ftpa_preview` sia definita (sia nella 14 che nella 16) con il decoratore `@staticmethod` usando `self`: 

```
@staticmethod
def ftpa_preview(self):
    return {
        "type": "ir.actions.act_url",
        "name": "Show preview",
        "url": self.ftpa_preview_link,
        "target": "new",
    }

```

## To Reproduce
**Affected versions**: 
- 14.0
- 16.0

Aggiornare modulo `l10n_it_fatturapa`

**Expected behavior**
No warning

## PR
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4133
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/4132

**Comment by matteoopenf** [comment]
se togli il decoratore scompare l'errore?

**Comment by TennyMkt** [comment]
> se togli il decoratore scompare l'errore?

Sì, togliendo il decoratore non compare più il warning

**Comment by matteoopenf** [comment]
> > se togli il decoratore scompare l'errore?
> 
> Sì, togliendo il decoratore non compare più il warning

puoi fare la pr?

**Comment by matteoopenf** [comment]
inoltre continua a funzionare tutto correttamente?
Nel caso fai una pr.

**Comment by TennyMkt** [comment]
> inoltre continua a funzionare tutto correttamente? Nel caso fai una pr.

Fatto ulteriori test e creato PR sia per la 14.0 che per 16.0

**Comment by sergiocorato** [comment]
Grazie
