### ISSUE TITLE
Wizard "Crea fatture" con data passata va in errore

### ISSUE THREAD

**Issue by cstevanatonehos** [OCA/l10n-italy#4095]
## Module
l10n_it_delivery_note

## Describe the bug
Quando dal form wizard "Crea fatture" si imposta una data precedente ad oggi stesso, il form va in errore e non mi fa creare la fattura.

## To Reproduce
1. Aprire tree view DDT
2. Selezionare un DDT
3. Cliccare Azione e poi "Crea fatture"
4. Impostare "Data fattura/conto" ad un giorno precedente oggi stesso
5. Cliccare sul pulsante "Crea fattura"

Esempio http://oca-l10n-italy-14-0-223e7cecbac9.runboat.odoo-community.org/web?debug=1#action=625&model=stock.delivery.note&view_type=list&cids=&menu_id=197
con DDT/C1/00002

**Expected behavior**
La fattura dovrebbe essere creata senza nessun problema

**Additional context**
L'errore immagino riguardi gli sconti ed il modo in cui vengono calcolati, in quanto non fanno combaciare dare ed avere sui movimenti contabili della fattura creata.

**Comment by francesco-ooops** [comment]
@cstevanatonehos i runboat vengono ricreati in continuazione, se puoi mettere uno o più screenshot resta la documentazione :)

**Comment by cstevanatonehos** [comment]
![bug_crea_fatture_1](https://github.com/OCA/l10n-italy/assets/125451570/c5eb34c9-d1b9-40e1-98e9-4d3a9fabff04)
![bug_crea_fatture_2](https://github.com/OCA/l10n-italy/assets/125451570/13c87255-bfb7-484c-adf3-06858e5daaa9)
![bug_crea_fatture_3](https://github.com/OCA/l10n-italy/assets/125451570/d44f5efb-215c-499f-bf89-51596733cd5f)
