### ISSUE TITLE
l10n_it_intrastat_statement: stampa trimestrale barrare periodo di riferimento

### ISSUE THREAD

**Issue by TheMule71** [OCA/l10n-italy#4115]
## Module
l10n_it_intrastat_statement

## Describe the bug
![image](https://github.com/OCA/l10n-italy/assets/915043/0416e9ef-ef23-4a71-91e3-c440bfb64fa9)

Non mi sembra possibile barrare la casella relativa a "LE INFORMAZIONE DELLE SEZIONI 1 e/o 3 SONO DA RIFERIRSI A..."

anche a livello di XML nel template non ci scrive nulla.

## To Reproduce
**Affected versions**:
12.0 16.0 immagino anche 14.0
Basta creare una qualsiasi dichiarazione anche vuota e fare stampa modello intra-1

**Expected behavior**
Dovrebbe esserci il modo per scegliere quale casella barrare

**Comment by SirAionTech** [comment]
Questo e altro è stato segnalato anche in https://github.com/OCA/l10n-italy/issues/4131, chiudo
