### ISSUE TITLE
[16] l10n_it_fatturapa_in: 'FutureWarning' dopo aggiornamento libreria lxml

### ISSUE THREAD

**Issue by alessandro-fiorino** [OCA/l10n-italy#4125]
Testando una nuova installazione con librerie aggiornate, in particolare lxml, ricevo questo warning
OCA/l10n-italy/l10n_it_fatturapa_in/wizard/efattura.py:57: FutureWarning: This search incorrectly ignores the root element, and will be fixed in a future version.  If you rely on the current behaviour, change it to './/{*}simpleType'
La riga oggetto del warning è 
`for element_type in _root.findall("//{*}simpleType"):`

Versione lxml installata 5.2.1

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Le versioni di `lxml` da usare sono quelle indicate nel file **requirements.txt** di Odoo:
```
lxml==4.6.5 ; python_version <= '3.10'
lxml==4.9.2 ; python_version > '3.10'
```
(da https://github.com/odoo/odoo/blob/a9920aa7bb464766c64e512101ffeebfede79b13/requirements.txt#L23-L24)

Chiuderei la issue perché altre versioni semplicemente non dovrebbero essere usate, e un semplice **warning** è decisamente il minore dei problemi che potrebbe capitarti!
