### ISSUE TITLE
[l10n_it_vat_statement_communication] problema encoding file nome file e zeri nell'esportazione xml 

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#4149]
## Module
l10n_it_vat_statement_communication

## Describe the bug
Allora premessa il cliente ci ha segnalato che il file xml generato da Odoo per la dichiarazione di odoo non venisse digerito dal programma dell'ADE, inizialmente pensavo fossero multipli i problemi.
Dopo un analisi piu' precisa manca solo l'encoding all'inizio del file, per intenderci metto uno screen:
![image](https://github.com/OCA/l10n-italy/assets/43987335/c885af1d-14d1-49be-ada9-4376acde8a92)

## To Reproduce

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4148 + https://github.com/OCA/l10n-italy/pull/4317 attualmente risolve i primi due problemi, il terzo non ho ben capito come funziona la nomenclatura giusta e non mi sono sentito di fixare quella cosa
- [x] 16.0  https://github.com/OCA/l10n-italy/pull/4357

1. Creare una dichiarazione iva
2. esportare il file xml
3. testarlo con il programma messo a disposizione dall'ADE qui https://jws.agenziaentrate.it/jws/dichiarazioni/StartControlli.jnlp
4. non partono i check per dire se il file e' corretto 

**Expected behavior**
Con questa pr che aggiunge l'enconding il file viene gestito correttamente dal programma dell'ADE

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
> attualmente risolve i primi due problemi, il terzo non ho ben capito come funziona la nomenclatura giusta e non mi sono sentito di fixare quella cosa

Ora c'è solo un problema, puoi rimuovere questa parte dalla descrizione?

> Additional context
Add any other context about the problem here. (e.g. OS, Python version, ...)

Anche questo si può togliere?

**Comment by patrickt-oforce** [comment]
Fix per 16.0 #4357
