### ISSUE TITLE
[16.0] l10n_it_delivery_note: broken migration

### ISSUE THREAD

**Issue by salvorapi** [OCA/l10n-italy#4167]
## Module
l10n_it_delivery_note

## Describe the bug
The migration script fails because `is_carrier` field is missing.

https://github.com/OCA/l10n-italy/blob/dc0b0de251844e02549f023cd4753f8f35c41dc0/l10n_it_delivery_note/migrations/16.0.1.1.0/post-migration.py#L8

- [x] 14.0  #3962
- [ ] 16.0 https://github.com/OCA/l10n-italy/pull/4168

**Comment by HekkiMelody** [comment]
Direi che vada fatto il FW di https://github.com/OCA/l10n-italy/pull/3962

**Comment by francesco-ooops** [comment]
chiudo perchè tracciata in https://github.com/OCA/l10n-italy/issues/3816

**Comment by francesco-ooops** [comment]
@salvorapi puoi aprire la PR di fw-porting?

**Comment by salvorapi** [comment]
> @salvorapi puoi aprire la PR di fw-porting?

Ho aperto una PR nuova perché il fw-porting non era possibile farlo. 
La PR è la #4168
