### ISSUE TITLE
l10n_it_ricevute_bancarie / riba - non permettere emissione RiBa da fatture non validate

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#4170]
Come da oggetto

## To Reproduce
**Affected versions**:

- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4150
- [x] 16.0 #4281

**Comment by andreampiovesana** [comment]
x 16?

**Comment by francesco-ooops** [comment]
@andreampiovesana possiamo farla

**Comment by francesco-ooops** [comment]
> x 16?

@andreampiovesana https://github.com/OCA/l10n-italy/pull/4281
