### ISSUE TITLE
Errore nella stampa del Bilancio Contabile in xlsx

### ISSUE THREAD

**Issue by FrancescoGermani** [OCA/l10n-italy#4179]
## Module
l10n_it_financial_statements_report

## Describe the bug
Effettuando l'esportazione in Excel del bilancio contabile otteniamo il seguente errore:
  File "/parts/project_addons/OCA/l10n-italy/l10n_it_financial_statements_report/report/financial_statements_report_xlsx.py", line 569, in get_write_data
    if isinstance(value, int | float) and cell_type not in (
TypeError: unsupported operand type(s) for |: 'type' and 'type'

## To Reproduce
**Affected versions**:
- [x] v14: no
- [x] v16: #4178 

1. andare su Stampa Bilancio Contabile
2. clic su Esporta XLSX

**Expected behavior**
Scaricare il file senza errori

**Comment by SirAionTech** [comment]
@FrancescoGermani sai mica se va corretto qualcosa anche in `14.0`? Se lì non c'è nulla da fare puoi chiudere la issue

**Comment by sergiocorato** [comment]
Non risulta presente sulla 14.0.
