### ISSUE TITLE
account_vat_period_end_statement AttributeError: 'account.payment.term' object has no attribute 'compute'

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#4182]
## To Reproduce
**Affected versions**:

 - [x] 14.0: no
 - [x] 16.0 https://github.com/OCA/l10n-italy/pull/4183 o https://github.com/OCA/l10n-italy/pull/3729

 - Create VAT invoices
 - Create VAT statement
 - Set payment term
 - Create VAT statement entry

Get AttributeError

**Comment by SirAionTech** [comment]
In `14.0` il problema non sussiste, vedi https://github.com/OCA/l10n-italy/pull/3729

**Comment by SirAionTech** [comment]
Chiudo perché duplicata di https://github.com/OCA/l10n-italy/issues/3977
