### ISSUE TITLE
[16.0] fatturapa_in errore bloccante importazione fatture

### ISSUE THREAD

**Issue by DavideSantos** [OCA/l10n-italy#4197]
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\http.py", line 1588, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\service\model.py", line 133, in retrying
    result = func()
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\http.py", line 1615, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\http.py", line 1819, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\website\models\ir_http.py", line 237, in _dispatch
    response = super()._dispatch(endpoint)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\http.py", line 697, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\web\controllers\dataset.py", line 46, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\web\controllers\dataset.py", line 33, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 461, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 448, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\l10n_it_fatturapa_in\wizard\wizard_import_fatturapa.py", line 1940, in importFatturaPA
    invoice = self.invoiceCreate(
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\l10n_it_fatturapa_in\wizard\wizard_import_fatturapa.py", line 1319, in invoiceCreate
    self.set_roundings(FatturaBody, invoice)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\l10n_it_fatturapa_in\wizard\wizard_import_fatturapa.py", line 1485, in set_roundings
    ).create(line_vals)
  File "<decorator-gen-284>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\l10n_it_split_payment\models\account_move_line.py", line 49, in create
    lines = super().create(vals_list)
  File "<decorator-gen-232>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\account\models\account_move_line.py", line 1431, in create
    lines = super().create([self._sanitize_vals(vals) for vals in vals_list])
  File "<decorator-gen-159>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\analytic\models\analytic_mixin.py", line 86, in create
    return super().create(vals_list)
  File "<decorator-gen-69>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\addons\base\models\ir_fields.py", line 670, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\models.py", line 3964, in create
    records = self._create(data_list)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\models.py", line 4201, in _create
    field.create([
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\fields.py", line 4248, in create
    self.write_batch(record_values, True)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\fields.py", line 4274, in write_batch
    return self.write_real(records_commands_list, create)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\fields.py", line 4860, in write_real
    cr.execute(query, pairs)
  File "C:\Program Files\Odoo 16.0.20231001\server\odoo\sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.DatatypeMismatch: ERRORE:  la colonna "account_tax_id" è di tipo integer ma l'espressione è di tipo boolean
LINE 1: ...unt_move_line_id, account_tax_id) VALUES (446670, false) ON ...
                                                             ^
HINT:  Devi riscrivere o convertire il tipo dell'espressione

The above server error caused the following client error:
RPC_ERROR://localhost:8069/web/assets/795711-f1efa60/web.assets_backend.min.js:987:163)
    at XMLHttpRequest.<anonymous> (http://localhost:8069/web/assets/795711-f1efa60/web.assets_backend.min.js:995:13)

questo errore mi capita solo quando importo una singola fattura, tutte le altre fatture vanno a buon fine tranne questa. vi riporto sopra il codice di errore in modo che forse si possa trovare il problema.

**Comment by francesco-ooops** [comment]
Ciao, penso valga la pena condividere l'XML, inoltre hai verificato la colonna account_tax_id come indicato?

**Comment by DavideSantos** [comment]
no purtroppo non so dove controllare la colonna. ora elimino i dati sensibili dal xml.
`<?xml version="1.0" encoding="utf-8"?>
<FatturaElettronica xmlns:p="http://www.fatturapa.gov.it/sdi/fatturapa/v1.2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" versione="FPR12"
    xmlns="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2">
    <FatturaElettronicaHeader xmlns="">
        <DatiTrasmissione>
            <IdTrasmittente>
                <IdPaese>IT</IdPaese>
                <IdCodice>123</IdCodice>
            </IdTrasmittente>
            <ProgressivoInvio>123</ProgressivoInvio>
            <FormatoTrasmissione>FPR12</FormatoTrasmissione>
            <CodiceDestinatario>123</CodiceDestinatario>
            <ContattiTrasmittente />
        </DatiTrasmissione>
        <CedentePrestatore>
            <DatiAnagrafici>
                <IdFiscaleIVA>
                    <IdPaese>IT</IdPaese>
                    <IdCodice>123</IdCodice>
                </IdFiscaleIVA>
                <CodiceFiscale>123</CodiceFiscale>
                <Anagrafica>
                    <Denominazione>123</Denominazione>
                    <Titolo>SPS</Titolo>
                </Anagrafica>
                <RegimeFiscale>RF01</RegimeFiscale>
            </DatiAnagrafici>
            <Sede>
                <Indirizzo>123</Indirizzo>
                <CAP>123</CAP>
                <Comune>123</Comune>
                <Provincia>123</Provincia>
                <Nazione>123</Nazione>
            </Sede>
            <Contatti>
                <Telefono>123</Telefono>
                <Fax>123</Fax>
                <Email>123</Email>
            </Contatti>
        </CedentePrestatore>
        <RappresentanteFiscale>
            <DatiAnagrafici>
                <IdFiscaleIVA>
                    <IdPaese>IT</IdPaese>
                    <IdCodice>123</IdCodice>
                </IdFiscaleIVA>
                <CodiceFiscale>123</CodiceFiscale>
                <Anagrafica>
                    <Denominazione>123</Denominazione>
                </Anagrafica>
            </DatiAnagrafici>
        </RappresentanteFiscale>
        <CessionarioCommittente>
            <DatiAnagrafici>
                <IdFiscaleIVA>
                    <IdPaese>IT</IdPaese>
                    <IdCodice>123</IdCodice>
                </IdFiscaleIVA>
                <CodiceFiscale>123</CodiceFiscale>
                <Anagrafica>
                    <Denominazione>123</Denominazione>
                </Anagrafica>
            </DatiAnagrafici>
            <Sede>
                <Indirizzo>123</Indirizzo>
                <CAP>123</CAP>
                <Comune>123</Comune>
                <Provincia>123</Provincia>
                <Nazione>123</Nazione>
            </Sede>
        </CessionarioCommittente>
    </FatturaElettronicaHeader>
    <FatturaElettronicaBody xmlns="">
        <DatiGenerali>
            <DatiGeneraliDocumento>
                <TipoDocumento>TD01</TipoDocumento>
                <Divisa>EUR</Divisa>
                <Data>2024-05-23</Data>
                <Numero>006770FE</Numero>
                <ImportoTotaleDocumento>566.78</ImportoTotaleDocumento>
                <Causale>123</Causale>
                <Causale>123</Causale>
                <Causale>123</Causale>
            </DatiGeneraliDocumento>
            <DatiOrdineAcquisto>
                <IdDocumento>WEB - 123</IdDocumento>
                <Data>2024-05-22</Data>
            </DatiOrdineAcquisto>
            <DatiTrasporto>
                <DatiAnagraficiVettore>
                    <IdFiscaleIVA>
                        <IdPaese>IT</IdPaese>
                        <IdCodice>123</IdCodice>
                    </IdFiscaleIVA>
                    <Anagrafica>
                        <Denominazione>SDA Express Courier</Denominazione>
                        <Titolo>CORRIERE</Titolo>
                    </Anagrafica>
                </DatiAnagraficiVettore>
                <MezzoTrasporto>TRASPORTO TERRESTRE</MezzoTrasporto>
                <CausaleTrasporto>Scarico vend.</CausaleTrasporto>
                <NumeroColli>3</NumeroColli>
                <UnitaMisuraPeso>KG</UnitaMisuraPeso>
                <PesoLordo>30.30</PesoLordo>
                <DataOraRitiro>2024-05-23T18:22:00</DataOraRitiro>
                <DataInizioTrasporto>2024-05-23</DataInizioTrasporto>
                <TipoResa>CIP</TipoResa>
                <IndirizzoResa>
                    <Indirizzo>123</Indirizzo>
                    <CAP>123</CAP>
                    <Comune>123</Comune>
                    <Provincia>123</Provincia>
                    <Nazione>123</Nazione>
                </IndirizzoResa>
            </DatiTrasporto>
        </DatiGenerali>
        <DatiBeniServizi>
            <DettaglioLinee>
                <NumeroLinea>1</NumeroLinea>
                <CodiceArticolo>
                    <CodiceTipo>AswArtFor</CodiceTipo>
                    <CodiceValore>6F203EA</CodiceValore>
                </CodiceArticolo>
                <Descrizione>250 G9 / CELERON N4500 / 8GB / 256GB / 15.6   HD / WINDOWS 11 HOME /  1YW</Descrizione>
                <Quantita>1.00000000</Quantita>
                <UnitaMisura>PZ</UnitaMisura>
                <PrezzoUnitario>239.00000000</PrezzoUnitario>
                <ScontoMaggiorazione>
                    <Tipo>SC</Tipo>
                    <Percentuale>3.77</Percentuale>
                </ScontoMaggiorazione>
                <PrezzoTotale>229.98970000</PrezzoTotale>
                <AliquotaIVA>0.00</AliquotaIVA>
                <Natura>N6.6</Natura>
            </DettaglioLinee>
            <DettaglioLinee>
                <NumeroLinea>2</NumeroLinea>
                <CodiceArticolo>
                    <CodiceTipo>AswArtFor</CodiceTipo>
                    <CodiceValore>82TT00FTIX</CodiceValore>
                </CodiceArticolo>
                <Descrizione>TS V15 I3-1215U 8GB 256GB 15.6FHD DOS 1YDEPOT</Descrizione>
                <Quantita>1.00000000</Quantita>
                <UnitaMisura>PZ</UnitaMisura>
                <PrezzoUnitario>315.81000000</PrezzoUnitario>
                <ScontoMaggiorazione>
                    <Tipo>SC</Tipo>
                    <Percentuale>14.82</Percentuale>
                </ScontoMaggiorazione>
                <PrezzoTotale>269.00695800</PrezzoTotale>
                <AliquotaIVA>0.00</AliquotaIVA>
                <Natura>N6.6</Natura>
            </DettaglioLinee>
            <DettaglioLinee>
                <NumeroLinea>3</NumeroLinea>
                <CodiceArticolo>
                    <CodiceTipo>AswArtFor</CodiceTipo>
                    <CodiceValore>LKLOCKEY</CodiceValore>
                </CodiceArticolo>
                <Descrizione>CAVO DI SICUREZZA PER NOTEBOOK CHIUSURA A CHIAVE MT. 1,50</Descrizione>
                <Quantita>14.00000000</Quantita>
                <UnitaMisura>PZ</UnitaMisura>
                <PrezzoUnitario>3.58000000</PrezzoUnitario>
                <PrezzoTotale>50.12000000</PrezzoTotale>
                <AliquotaIVA>22.00</AliquotaIVA>
            </DettaglioLinee>
            <DettaglioLinee>
                <NumeroLinea>4</NumeroLinea>
                <TipoCessionePrestazione>AC</TipoCessionePrestazione>
                <Descrizione>Trasporto (totale Euro 6.500000)</Descrizione>
                <PrezzoUnitario>5.90671987</PrezzoUnitario>
                <PrezzoTotale>5.90671987</PrezzoTotale>
                <AliquotaIVA>0.00</AliquotaIVA>
                <Natura>N6.6</Natura>
                <AltriDatiGestionali>
                    <TipoDato>AswSpAcces</TipoDato>
                    <RiferimentoTesto>Trasporto # SP03#</RiferimentoTesto>
                </AltriDatiGestionali>
            </DettaglioLinee>
            <DettaglioLinee>
                <NumeroLinea>5</NumeroLinea>
                <TipoCessionePrestazione>AC</TipoCessionePrestazione>
                <Descrizione>Trasporto (totale Euro 6.500000)</Descrizione>
                <PrezzoUnitario>0.59328013</PrezzoUnitario>
                <PrezzoTotale>0.59328013</PrezzoTotale>
                <AliquotaIVA>22.00</AliquotaIVA>
                <AltriDatiGestionali>
                    <TipoDato>AswSpAcces</TipoDato>
                    <RiferimentoTesto>Trasporto # SP03#</RiferimentoTesto>
                </AltriDatiGestionali>
            </DettaglioLinee>
            <DettaglioLinee>
                <NumeroLinea>6</NumeroLinea>
                <Descrizione>Riga ausiliaria contente informazioni tecniche e aggiuntive del documento</Descrizione>
                <PrezzoUnitario>0.00000000</PrezzoUnitario>
                <PrezzoTotale>0.00000000</PrezzoTotale>
                <AliquotaIVA>22.00</AliquotaIVA>
                <AltriDatiGestionali>
                    <TipoDato>AswTRiga</TipoDato>
                    <RiferimentoTesto>Informazioni documento #123#</RiferimentoTesto>
                </AltriDatiGestionali>
                <AltriDatiGestionali>
                    <TipoDato>AswRelStd</TipoDato>
                    <RiferimentoTesto>Versione #Asw0100#</RiferimentoTesto>
                </AltriDatiGestionali>
                <AltriDatiGestionali>
                    <TipoDato>AswTratSco</TipoDato>
                    <RiferimentoTesto>Valori come righe sconto #PRS#</RiferimentoTesto>
                </AltriDatiGestionali>
            </DettaglioLinee>
            <DatiRiepilogo>
                <AliquotaIVA>0.00</AliquotaIVA>
                <Natura>N6.6</Natura>
                <SpeseAccessorie>5.91</SpeseAccessorie>
                <Arrotondamento>0.01</Arrotondamento>
                <ImponibileImporto>504.91</ImponibileImporto>
                <Imposta>0.00</Imposta>
                <RiferimentoNormativo>N.I. A.17 C.6 L.C
(M/Processori-NB-varie)</RiferimentoNormativo>
            </DatiRiepilogo>
            <DatiRiepilogo>
                <AliquotaIVA>22.00</AliquotaIVA>
                <SpeseAccessorie>0.59</SpeseAccessorie>
                <ImponibileImporto>50.71</ImponibileImporto>
                <Imposta>11.16</Imposta>
                <EsigibilitaIVA>I</EsigibilitaIVA>
                <RiferimentoNormativo>Aliquota IVA 22%</RiferimentoNormativo>
            </DatiRiepilogo>
        </DatiBeniServizi>
        <DatiPagamento>
            <CondizioniPagamento>TP02</CondizioniPagamento>
            <DettaglioPagamento>
                <ModalitaPagamento>MP05</ModalitaPagamento>
                <DataRiferimentoTerminiPagamento>2024-05-23</DataRiferimentoTerminiPagamento>
                <DataScadenzaPagamento>2024-05-23</DataScadenzaPagamento>
                <ImportoPagamento>566.78</ImportoPagamento>
                <IstitutoFinanziario>123</IstitutoFinanziario>
                <IBAN>123</IBAN>
                <ABI>123</ABI>
                <CAB>123</CAB>
                <BIC>123</BIC>
            </DettaglioPagamento>
        </DatiPagamento>
    </FatturaElettronicaBody>
</FatturaElettronica>`



P.S. il codice lo scritto formattato ma il risultato non è quello aspettato.
scusate e da poco che lavoro con odoo.

**Comment by TheMule71** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<FatturaElettronica xmlns:p="http://www.fatturapa.gov.it/sdi/fatturapa/v1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2" versione="FPR12">
  <FatturaElettronicaHeader xmlns="">
    <DatiTrasmissione>
      <IdTrasmittente>
        <IdPaese>IT</IdPaese>
        <IdCodice>123</IdCodice>
      </IdTrasmittente>
      <ProgressivoInvio>123</ProgressivoInvio>
      <FormatoTrasmissione>FPR12</FormatoTrasmissione>
      <CodiceDestinatario>123</CodiceDestinatario>
      <ContattiTrasmittente/>
    </DatiTrasmissione>
    <CedentePrestatore>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>123</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>123</CodiceFiscale>
        <Anagrafica>
          <Denominazione>123</Denominazione>
          <Titolo>SPS</Titolo>
        </Anagrafica>
        <RegimeFiscale>RF01</RegimeFiscale>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>123</Indirizzo>
        <CAP>123</CAP>
        <Comune>123</Comune>
        <Provincia>123</Provincia>
        <Nazione>123</Nazione>
      </Sede>
      <Contatti>
        <Telefono>123</Telefono>
        <Fax>123</Fax>
        <Email>123</Email>
      </Contatti>
    </CedentePrestatore>
    <RappresentanteFiscale>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>123</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>123</CodiceFiscale>
        <Anagrafica>
          <Denominazione>123</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>
    </RappresentanteFiscale>
    <CessionarioCommittente>
      <DatiAnagrafici>
        <IdFiscaleIVA>
          <IdPaese>IT</IdPaese>
          <IdCodice>123</IdCodice>
        </IdFiscaleIVA>
        <CodiceFiscale>123</CodiceFiscale>
        <Anagrafica>
          <Denominazione>123</Denominazione>
        </Anagrafica>
      </DatiAnagrafici>
      <Sede>
        <Indirizzo>123</Indirizzo>
        <CAP>123</CAP>
        <Comune>123</Comune>
        <Provincia>123</Provincia>
        <Nazione>123</Nazione>
      </Sede>
    </CessionarioCommittente>
  </FatturaElettronicaHeader>
  <FatturaElettronicaBody xmlns="">
    <DatiGenerali>
      <DatiGeneraliDocumento>
        <TipoDocumento>TD01</TipoDocumento>
        <Divisa>EUR</Divisa>
        <Data>2024-05-23</Data>
        <Numero>006770FE</Numero>
        <ImportoTotaleDocumento>566.78</ImportoTotaleDocumento>
        <Causale>123</Causale>
        <Causale>123</Causale>
        <Causale>123</Causale>
      </DatiGeneraliDocumento>
      <DatiOrdineAcquisto>
        <IdDocumento>WEB - 123</IdDocumento>
        <Data>2024-05-22</Data>
      </DatiOrdineAcquisto>
      <DatiTrasporto>
        <DatiAnagraficiVettore>
          <IdFiscaleIVA>
            <IdPaese>IT</IdPaese>
            <IdCodice>123</IdCodice>
          </IdFiscaleIVA>
          <Anagrafica>
            <Denominazione>SDA Express Courier</Denominazione>
            <Titolo>CORRIERE</Titolo>
          </Anagrafica>
        </DatiAnagraficiVettore>
        <MezzoTrasporto>TRASPORTO TERRESTRE</MezzoTrasporto>
        <CausaleTrasporto>Scarico vend.</CausaleTrasporto>
        <NumeroColli>3</NumeroColli>
        <UnitaMisuraPeso>KG</UnitaMisuraPeso>
        <PesoLordo>30.30</PesoLordo>
        <DataOraRitiro>2024-05-23T18:22:00</DataOraRitiro>
        <DataInizioTrasporto>2024-05-23</DataInizioTrasporto>
        <TipoResa>CIP</TipoResa>
        <IndirizzoResa>
          <Indirizzo>123</Indirizzo>
          <CAP>123</CAP>
          <Comune>123</Comune>
          <Provincia>123</Provincia>
          <Nazione>123</Nazione>
        </IndirizzoResa>
      </DatiTrasporto>
    </DatiGenerali>
    <DatiBeniServizi>
      <DettaglioLinee>
        <NumeroLinea>1</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>AswArtFor</CodiceTipo>
          <CodiceValore>6F203EA</CodiceValore>
        </CodiceArticolo>
        <Descrizione>250 G9 / CELERON N4500 / 8GB / 256GB / 15.6   HD / WINDOWS 11 HOME /  1YW</Descrizione>
        <Quantita>1.00000000</Quantita>
        <UnitaMisura>PZ</UnitaMisura>
        <PrezzoUnitario>239.00000000</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>3.77</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>229.98970000</PrezzoTotale>
        <AliquotaIVA>0.00</AliquotaIVA>
        <Natura>N6.6</Natura>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>2</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>AswArtFor</CodiceTipo>
          <CodiceValore>82TT00FTIX</CodiceValore>
        </CodiceArticolo>
        <Descrizione>TS V15 I3-1215U 8GB 256GB 15.6FHD DOS 1YDEPOT</Descrizione>
        <Quantita>1.00000000</Quantita>
        <UnitaMisura>PZ</UnitaMisura>
        <PrezzoUnitario>315.81000000</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>14.82</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>269.00695800</PrezzoTotale>
        <AliquotaIVA>0.00</AliquotaIVA>
        <Natura>N6.6</Natura>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>3</NumeroLinea>
        <CodiceArticolo>
          <CodiceTipo>AswArtFor</CodiceTipo>
          <CodiceValore>LKLOCKEY</CodiceValore>
        </CodiceArticolo>
        <Descrizione>CAVO DI SICUREZZA PER NOTEBOOK CHIUSURA A CHIAVE MT. 1,50</Descrizione>
        <Quantita>14.00000000</Quantita>
        <UnitaMisura>PZ</UnitaMisura>
        <PrezzoUnitario>3.58000000</PrezzoUnitario>
        <PrezzoTotale>50.12000000</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>4</NumeroLinea>
        <TipoCessionePrestazione>AC</TipoCessionePrestazione>
        <Descrizione>Trasporto (totale Euro 6.500000)</Descrizione>
        <PrezzoUnitario>5.90671987</PrezzoUnitario>
        <PrezzoTotale>5.90671987</PrezzoTotale>
        <AliquotaIVA>0.00</AliquotaIVA>
        <Natura>N6.6</Natura>
        <AltriDatiGestionali>
          <TipoDato>AswSpAcces</TipoDato>
          <RiferimentoTesto>Trasporto # SP03#</RiferimentoTesto>
        </AltriDatiGestionali>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>5</NumeroLinea>
        <TipoCessionePrestazione>AC</TipoCessionePrestazione>
        <Descrizione>Trasporto (totale Euro 6.500000)</Descrizione>
        <PrezzoUnitario>0.59328013</PrezzoUnitario>
        <PrezzoTotale>0.59328013</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
        <AltriDatiGestionali>
          <TipoDato>AswSpAcces</TipoDato>
          <RiferimentoTesto>Trasporto # SP03#</RiferimentoTesto>
        </AltriDatiGestionali>
      </DettaglioLinee>
      <DettaglioLinee>
        <NumeroLinea>6</NumeroLinea>
        <Descrizione>Riga ausiliaria contente informazioni tecniche e aggiuntive del documento</Descrizione>
        <PrezzoUnitario>0.00000000</PrezzoUnitario>
        <PrezzoTotale>0.00000000</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>
        <AltriDatiGestionali>
          <TipoDato>AswTRiga</TipoDato>
          <RiferimentoTesto>Informazioni documento #123#</RiferimentoTesto>
        </AltriDatiGestionali>
        <AltriDatiGestionali>
          <TipoDato>AswRelStd</TipoDato>
          <RiferimentoTesto>Versione #Asw0100#</RiferimentoTesto>
        </AltriDatiGestionali>
        <AltriDatiGestionali>
          <TipoDato>AswTratSco</TipoDato>
          <RiferimentoTesto>Valori come righe sconto #PRS#</RiferimentoTesto>
        </AltriDatiGestionali>
      </DettaglioLinee>
      <DatiRiepilogo>
        <AliquotaIVA>0.00</AliquotaIVA>
        <Natura>N6.6</Natura>
        <SpeseAccessorie>5.91</SpeseAccessorie>
        <Arrotondamento>0.01</Arrotondamento>
        <ImponibileImporto>504.91</ImponibileImporto>
        <Imposta>0.00</Imposta>
        <RiferimentoNormativo>N.I. A.17 C.6 L.C (M/Processori-NB-varie)</RiferimentoNormativo>
      </DatiRiepilogo>
      <DatiRiepilogo>
        <AliquotaIVA>22.00</AliquotaIVA>
        <SpeseAccessorie>0.59</SpeseAccessorie>
        <ImponibileImporto>50.71</ImponibileImporto>
        <Imposta>11.16</Imposta>
        <EsigibilitaIVA>I</EsigibilitaIVA>
        <RiferimentoNormativo>Aliquota IVA 22%</RiferimentoNormativo>
      </DatiRiepilogo>
    </DatiBeniServizi>
    <DatiPagamento>
      <CondizioniPagamento>TP02</CondizioniPagamento>
      <DettaglioPagamento>
        <ModalitaPagamento>MP05</ModalitaPagamento>
        <DataRiferimentoTerminiPagamento>2024-05-23</DataRiferimentoTerminiPagamento>
        <DataScadenzaPagamento>2024-05-23</DataScadenzaPagamento>
        <ImportoPagamento>566.78</ImportoPagamento>
        <IstitutoFinanziario>123</IstitutoFinanziario>
        <IBAN>123</IBAN>
        <ABI>123</ABI>
        <CAB>123</CAB>
        <BIC>123</BIC>
      </DettaglioPagamento>
    </DatiPagamento>
  </FatturaElettronicaBody>
</FatturaElettronica>
```

**Comment by TheMule71** [comment]
Sembra l'arrotondamento, è come se mancasse il conto ma i controlli ci sono e non si dovrebbe arrivare a quel punto.

Comunque l'XML che hai caricato è inutilizzabile. Non puoi semplicemente mettere 123 nei vari campi, vengono fatti dei controlli.   Ho provato a sistemare CodiceDestinatario, CodiceFiscale, CAP poi mi sono fermato.

Una prova che puoi fare è eliminare la riga:
```
        <Arrotondamento>0.01</Arrotondamento>
```
nell'originale e provare a caricarlo.

**Comment by DavideSantos** [comment]
si lo so, ho messo 123 per privacy, non mi sembra giusto mettere una fattura con tutti i dati su github.  solo che la fattura e in formato XLSX perché ha la firma digitale ed una fattura elettronica, non posso andare a modificare la fattura elettronica. non mi capita sempre questo errore ma spesso

**Comment by francesco-ooops** [comment]
> si lo so, ho messo 123 per privacy, non mi sembra giusto mettere una fattura con tutti i dati su github. solo che la fattura e in formato XLSX perché ha la firma digitale ed una fattura elettronica, non posso andare a modificare la fattura elettronica. non mi capita sempre questo errore ma spesso

Certo ma non puoi mettere 123 nel campo IBAN, devi metterci un IBAN valido, stesso per gli altri campi

**Comment by DavideSantos** [comment]
ok allora dimmi tu che dati devo oscurare sia per aiutare voi che poteri risolvere il problema, se ovviamente proviene dal modulo stesso l'errore o meno.

**Comment by francesco-ooops** [comment]
@OCA/local-italy-maintainers c'è una procedura per anonimizzare un XML o un sito dove verificarne la correttezza che possiamo passare a @DavideSantos ?

**Comment by SirAionTech** [comment]
> @OCA/local-italy-maintainers c'è una procedura per anonimizzare un XML o un sito dove verificarne la correttezza che possiamo passare a @DavideSantos ?

Procedure automatiche per anonimizzare non ne conosco.

Per verificare la correttezza ho trovato che esiste una Funzionalità di supporto **Controlla fattura**:
> Per anticipare sul proprio file i controlli effettuati dal Sistema è consigliabile sottoporre il file FatturaPA a una verifica preventiva tramite l’applicazione disponibile sul portale dell’ Agenzia delle entrate [Fatture e Corrispettivi](https://www.fatturapa.gov.it/export/linkesterni-it/sdifatturapa-Controllare) (percorso Fatturazione elettronica e Conservazione – Funzionalità di supporto (Controlla fattura)).

(da https://www.fatturapa.gov.it/it/sistemainterscambio/controlli-ed-errori/)

e ci sono delle istruzioni in https://www.agenziaentrate.gov.it/portale/web/guest/aree-tematiche/fatturazione-elettronica/guida-fatturazione-elettronica/i-servizi-dell-agenzia-fe/la-procedura-web-fe dove si vede che c'è quel servizio 
![image](https://github.com/user-attachments/assets/bea55a3d-a8e6-455d-b9ef-1a82b4f5bd83)

**Comment by DavideSantos** [comment]
allora ho provato a passare l'xml al interno della verifica ed la fa inviare tranquillamente.

**Comment by SirAionTech** [comment]
> allora ho provato a passare l'xml al interno della verifica ed la fa inviare tranquillamente.

Bene, allora adesso ti rimane da
1. anonimizzare il file
2. verificare che passi i controlli
3. verificare che importandolo in Odoo sollevi il problema di questa issue
4. includere il file anonimizzato in questa issue

Avendo un file con cui è possibile riprodurre il problema, è molto più semplice correggere.

**Comment by DavideSantos** [comment]
si certo, allora provvedo ad fare il meglio che posso ad anonimizzare il file.
