### ISSUE TITLE
[10.0] Problem with l10n_it_base_location_geonames_import

### ISSUE THREAD

**Issue by FrancoTampieri** [OCA/l10n-italy#421]
Hi, I foud a bug on the l10n_it_base_location_geonames_import.
With the inheritage of the wizard function the wizard import always the column 6 for name and column 5 for code of the downloaded geonames files, that was right only for some country, like ES, IT but not for FR and others.
If I install this module and my company have to work with FR partners I have to insert manually the data because if I import the locations with geonames, The locations have wrong name and code data.

I have make a merge proposal to make the base_location_geonames universal, and you can see here https://github.com/OCA/partner-contact/pull/529

If the merge passed the module l10n_it_base_location_geonames_import can be uninstalled and no longer required.

Regards

Franco

**Comment by OpenCode** [comment]
We will remove l10n_it_base_location_geonames_import from this repository. 

Thank you for your work and your PR.

**Comment by drdran** [comment]
As your pleasure @OpenCode +1

**Comment by sergiocorato** [comment]
chiudo per inattività
