### ISSUE TITLE
14.0 [l10n_it_fatturapa_in] importazione con minimo diventa sempre una nota di credito

### ISSUE THREAD

**Issue by matteoopenf** [OCA/l10n-italy#4228]
## Module
l10n_it_fatturapa_in

## Describe the bug
A sequito del merge di questa pr  https://github.com/OCA/l10n-italy/pull/3751 se importo una fattura al minimo ottengo sempre una nota di credito.
Perche' qui 
![image](https://github.com/OCA/l10n-italy/assets/43987335/155c9aec-e453-4463-840e-00f1964acedf)
non si controlla se ci sono righe e quindi si procede di "default"  a cambiare il tipo di documento

## To Reproduce
**Affected versions**:

- [x] 12.0 https://github.com/OCA/l10n-italy/pull/4275
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4229
- [x] 16.0 https://github.com/OCA/l10n-italy/pull/4272

1. Importare una fattura elettronica di tipo td 01 al minimo
2. dopo la creazione si nota che si ha una nota di credito anziche' una fattura
3.

**Expected behavior**
si deve creare correttamente una fattura 

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by matteoopenf** [comment]
ora apro una pr per correggere il problema

**Comment by SirAionTech** [comment]
Ho provato in runboat e confermo che il problema si verifica in `16.0` con il file https://github.com/OCA/l10n-italy/blob/1c0e8323ec675550e84129bdf9292ccd5962fb6d/l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml:
![image](https://github.com/OCA/l10n-italy/assets/143788994/dc738056-d05a-4b77-acd2-1e39fb4fbdee)
(da http://oca-l10n-italy-16-0-012e8a0d9779.runboat.odoo-community.org/web#id=19&cids=1&menu_id=140&active_id=4&model=account.move&view_type=form)

**Comment by matteoopenf** [comment]
So che si verifica anche su 16.0 ho aperto la pr ma il precommit mi ha fatto casino.Tra oggi e domani la riapro sistemando meglio ecco perché l’ho chiusa Matteo ***@***.*** Il giorno 9 lug 2024, alle ore 14:13, Simone Rubino ***@***.***> ha scritto:﻿
Ho provato in runboat e confermo che il problema si verifica in 16.0 con il file https://github.com/OCA/l10n-italy/blob/1c0e8323ec675550e84129bdf9292ccd5962fb6d/l10n_it_fatturapa_in/tests/data/IT05979361218_001.xml:
image.png (view on web)
(da http://oca-l10n-italy-16-0-012e8a0d9779.runboat.odoo-community.org/web#id=19&cids=1&menu_id=140&active_id=4&model=account.move&view_type=form)

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

Openforce Srls Unipersonale | www.openforce.it | 02 21119472 | Via Tiziano,32 20145 Milano
