### ISSUE TITLE
l10n_it_reverse_charge: importo in valuta non viene valorizzato

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#4234]
## Module
l10n_it_reverse_charge

## Describe the bug
Quando viene generato il pagamento RC l'importo in valuta non viene valorizzato.

## To Reproduce
**16.0**:

1. creazione di un'autofattura fornitore

**Expected behavior**
L'importo in valuta dovrebbe essere valorizzato.

**Additional context**
![fattura fornitore](https://github.com/OCA/l10n-italy/assets/53826275/f25e1626-621a-47f6-8956-c3ad7d2bfaea)
![fattura cliente](https://github.com/OCA/l10n-italy/assets/53826275/e071aff1-1509-491d-a207-9d78435d716d)
![reverse charge](https://github.com/OCA/l10n-italy/assets/53826275/b8d219da-971d-4bb0-83a3-1593d6509be9)

**Comment by odooNextev** [comment]
@Borruso mi sa che è quello che avevo già segnalato: https://github.com/OCA/l10n-italy/issues/4111

**Comment by Borruso** [comment]
> @Borruso mi sa che è quello che avevo già segnalato: #4111

ottimo non l'avevo trovata
