### ISSUE TITLE
Permission error while importing an incoming e-invoice

### ISSUE THREAD

**Issue by PicchiSeba** [OCA/l10n-italy#4242]
### Is your feature request related to a problem?
In some cases, importing an incoming e-invoice will show an error message stating that the user doesn't have the necessary group to edit a certain field (in my case it was `stock_valuation_layer_ids` and the user was missing the "Stock / Administrator" group)

### Describe the solution you'd like
After a bit if investigation I found out that all the fields of the invoice were being overwritten. For many of them the new value was the same as the old one.
I'd like a check to overwrite only those fields with different values

- [x] 16.0 no
- [x] 14.0 https://github.com/OCA/l10n-italy/pull/4240

**Comment by sergiocorato** [comment]
Non risulta presente il problema sulla 16.0, chiudo.
