### ISSUE TITLE
Rimozione codice inutilizzato in l10n_it_withholding_tax

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#4255]
## Module
l10n_it_withholding_tax

## Describe the bug
Nel modulo c'è del codice non utilizzato. 
La funzione _prepare_wt_values è un residuo dalla v. 8.0, in cui c'era un wizard di creazione della dichiarazione RdA, e non è più utilizzata da allora.
La funzione _compute_payment_amount non esiste più, la sua funzionalità era di impostare il valore da pagare sulla fattura al valore residuo senza ritenuta, sostituita da altre funzioni e migliorata dalla funzione aggiunta in https://github.com/OCA/l10n-italy/pull/4235

## To Reproduce
**Affected versions**:
- [x] 14.0: #4251 
- [x] 16.0: #4258

non applicabile

**Expected behavior**
Non c'è codice inutilizzato

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by andreampiovesana** [comment]
16.0: sì cosa significa?

**Comment by SirAionTech** [comment]
> 16.0: sì cosa significa?

Significa che la versione è affetta, perché sta dentro **Affected versions**
![image](https://github.com/OCA/l10n-italy/assets/143788994/4afb77fe-174e-43b2-a0d9-82d28b249666)
