### ISSUE TITLE
[16.0] l10n_it_delivery_note: 'account.move' object has no attribute ' _onchange_invoice_date'

### ISSUE THREAD

**Issue by Borruso** [OCA/l10n-italy#4269]
## Module
l10n_it_delivery_note

## Describe the bug
Quando creo la fattura dal DdT, con il wizard creazione fattura, dopo la generazione il wizard imposta la data sulle fatture create uguale a quella indicata nel wizard ma va in errore.

## To Reproduce
**Affected versions**:
- [x] 16.0: https://github.com/OCA/l10n-italy/pull/4253

1. Crea DdT
2. Fattura DdT tramite il wizard di creazione fattura

**Comment by tafaRU** [comment]
@Borruso se non erro, stamattina in call, dicevi che sulla `14.0` questo problema non esiste. Se confermi chiudiamo la issue.
Grazie.

**Comment by Borruso** [comment]
confermo
