### ISSUE TITLE
l10n_it_withholding_tax_financial_report: TypeError: _get_data() takes 7 positional arguments but 8 were given

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#4285]
This happens after https://github.com/OCA/account-financial-reporting/commit/3d492eb2361bf143569521e60c937cc8a1e63d58

**Affected versions**:

 - [x] `14.0`: no
 - [x] 16.0 https://github.com/OCA/l10n-italy/pull/4286

1. Run open_items report

**Comment by SirAionTech** [comment]
Ho verificato che in `14.0` il problema non esiste: 
![image](https://github.com/user-attachments/assets/12d19b3a-8d4e-4ab8-a1be-c0df07f0ec15)
