### ISSUE TITLE
[10.0 - 11.0] Rename of l10n_it_corrispettivi to l10n_it_receipts

### ISSUE THREAD

**Issue by FrancoTampieri** [OCA/l10n-italy#431]
Hi!

I'm rewriting the corrispettivi module for the italian account localisation, so I want to rename from corrispettivi to a generic receipt, because with this new module I will manage the registration of fiscal receipt, normal receipt, receipt that generate deferred invoices etc. etc.

What do u think about it?

Regards Franco

**Comment by eLBati** [comment]
Ok, this will probably need a migration script

**Comment by drdran** [comment]
Do u mean from the 6.1 version to the 10.0 version and so?

**Comment by OpenCode** [comment]
:+1: for me

**Comment by alessandrocamilli** [comment]
👍

**Comment by eLBati** [comment]
@drdran Il modulo l10n_it_corrispettivi è disponibile per la 8 e non per la 10. Se intendi rinominarlo per la 10, allora è necessario anche lo script di upgrade del DB.

Sulla necessità o meno dello script di upgrade, non possiamo rilasciare un modulo che rischia di rompere installazioni esistenti. Noi ad esempio abbiamo un paio di clienti che lo usano sulla 8

Ad ogni modo openupgradelib mette già a disposizioni un metodo da chiamare in questi casi:
https://github.com/OCA/openupgradelib/blob/9b5d8f9710b19339438fcd62e3f98c631086a8cf/openupgradelib/openupgrade.py#L893

Un esempio di utilizzo di openupgradelib:
https://github.com/OCA/website/blob/10.0/website_legal_page/migrations/10.0.1.0.0/pre-migrate.py

**Comment by drdran** [comment]
@eLBati grazie a questo punto mi muovo controllando anche la parte di migrazione per openupgrade.
Tuttavia a breve avrò anche la necessità di una mano per produrre i tests e per questo se c'è qualcuno interessato nella community per condividere il lavoro è ben accetto.

**Comment by sergiocorato** [comment]
chiudo per inattività
