### ISSUE TITLE
[l10n_it_asset_history_import] not compatible with python2

### ISSUE THREAD

**Issue by luk156** [OCA/l10n-italy#4325]
the module is not compatible with python 2 because f-strings are used

**Comment by matteoopenf** [comment]
Ma ormai si usa Python 3 su Odoo.
Usi ancora Python 2?

**Comment by luk156** [comment]
Ho usato l'immagine di docker con odoo12 ed è basata su python 2.7

**Comment by matteoopenf** [comment]
> Ho usato l'immagine di docker con odoo12 ed è basata su python 2.7

Aggiorna la issue, comunque Odoo 12 oltre ad essere deprecato utilizza Python 3 solitamente anche nella ci di oca c'è Python 3
Hai usato l'immagine ufficiale o una di terze parti?
Se comunque stai iniziando da capo meglio che inizi con Odoo 16

**Comment by matteoopenf** [comment]
Non oltre che Python 2.7 è deprecato a sua volta

**Comment by matteoopenf** [comment]
In ogni caso sentiti libero di fare una pr in proposito

**Comment by SirAionTech** [comment]
Chiudo perché `12.0` non è più supportata, vedi https://github.com/OCA/l10n-italy/wiki/Team-di-sviluppo#linee-guida-gestione-versioni.
