### ISSUE TITLE
 l10n_it_withholding_tax: valore raddoppiato nell'Importo a saldo

### ISSUE THREAD

**Issue by borgogelli** [OCA/l10n-italy#434]
Utilizzo Odoo 10.0 e il modulo 10n_it_withholding_tax 10.1
Quando registro il pagamento di una fattura, il sistema calcola in modo errato l'"Importo a saldo".
Risulta infatti un valore doppio rispetto a quello atteso, che dovrebbe essere pari alla ritenuta d'acconto.

![screenshot](https://user-images.githubusercontent.com/7045594/34818568-73c1a8f4-f6bb-11e7-9f81-3b8e7a5b0619.png)

Grazie per ogni eventuale suggerimento

**Comment by alessandrocamilli** [comment]
ciao @borgogelli , 
grazie per il riscontro.
C'è un PR che introduce diverse migliorie, soprattutto per quanto riguarda i pagamenti multipli e i ricalcoli dopo aver annullato le riconciliazioni dei pagamenti.
La PR è questa https://github.com/OCA/l10n-italy/pull/417

**Comment by borgogelli** [comment]
Risolto usando il codice della PR sopra indicata
Grazie mille.
