### ISSUE TITLE
Fattura acconto e fattura saldo su ordine PR4381

### ISSUE THREAD

**Issue by MaurizioPellegrinet** [OCA/l10n-italy#4382]
<Problema riscontrato a seguito verifica PR4381>

## Module
l10n_it_fatturapa_out ?

## Describe the bug
A seguito di ordine di vendita:
- se genero fattura acconto
- fattura di saldo (con storno acconto), crea nota di credito a storno fattura acconto

## To Reproduce
1. creare ordine di vendita
2. fare fattura di acconto
3. fare fattura di saldo (con storno acconto)
4. genera invece della fattura di saldo una nota di credito 

**Affected versions**:
v.16

**Expected behavior**
Al punto 3 deve generare fattura di saldo al netto della fattura di acconto (con xml corretto per invio)

https://github.com/user-attachments/assets/7edf7bd3-7604-4a04-9053-65d8988055e0

Il problema esiste anche sul runboat della PR4379 su verifica di @matteoopenf

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
In chiamata abbiamo provato sia nel runboat di `16.0` che nel runboat di https://github.com/OCA/l10n-italy/pull/4381 e abbiamo notato che veniva usato un prodotto fatturabile alla consegna: non avendolo consegnato non c'era niente da fatturare (te ne accorgi perché il pulsante **Crea fattura** non è evidenziato) quindi l'unica cosa da fare quando fai il pagamento totale è giustamente una nota di credito.

Dovresti ottenere il comportamento atteso quando il prodotto è fatturabile dall'ordine, puoi verificare?

**Comment by MaurizioPellegrinet** [comment]
Perfetto, verificato è ok.

**Comment by MaurizioPellegrinet** [comment]
Verificato: è OK

**Comment by MaurizioPellegrinet** [comment]
Verificato: è OK. Si può chiudere issue.
Grazie

**Comment by SirAionTech** [comment]
> Verificato: è OK. Si può chiudere issue. Grazie

Va bene grazie, allora chiudila pure
