### ISSUE TITLE
[10.0] error - from osv import osv non più compatibile

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#439]
https://github.com/OCA/l10n-italy/blob/e5bde455c17b7ec2ad829f411d60ca85e50d31ca/account_fiscal_year_closing/fyc.py#L30

**Comment by scigghia** [comment]
tra l'altro non so per quale motivo ma rimosso il modulo e di conseguenza l'errore, sparisce anche questo bug https://github.com/OCA/OCB/issues/693

**Comment by sergiocorato** [comment]
@scigghia essendo rimosso il modulo, direi che si può chiudere

**Comment by tafaRU** [comment]
I close as https://github.com/OCA/l10n-italy/pull/457
