### ISSUE TITLE
fiscal_epos_print 0.17 è disponibile?

### ISSUE THREAD

**Issue by VirtechSRL-ai** [OCA/l10n-italy#4437]
ma la versione fiscal epos prinyt 0.17 è disponibile?

**Comment by francesco-ooops** [comment]
Ciao, no la community lavora principalmente sulle versioni pari. Per qualsiasi domanda puoi unirti al nostro [discord](https://discord.gg/vsAAG6ywGc) o scrivere sul [forum](https://www.odoo-italia.org/forum/forum-1)
