### ISSUE TITLE
[l10n_it_fatturapa] - Problema di accesso fattura fornitore

### ISSUE THREAD

**Issue by francesco-ooops** [OCA/l10n-italy#4449]
Non ho chiari i passi per riprodurre, ma in fatture fornitore importate da xml è stato riportato per utenti con diritti di accesso più bassi un errore generico "Nessuna autorizzazione ad accedere al documento"

- [ ] 14.0 https://github.com/OCA/l10n-italy/pull/4447
- [ ] 16.0

**Comment by SirAionTech** [comment]
Nell'errore dovrebbe essere riportato quale documento (`account.move` o altro) e se c'è il debug attivo viene anche mostrata la regola colpevole, potresti recuperare queste info?

Quindi eliminando e re-esportando la stessa fattura l'errore non si ripete?

EDIT: avevo letto male e pensavo si parlasse di import, ma anche per l'export dovrebbe essere analogo

**Comment by francesco-ooops** [comment]
Ciao, purtroppo non ho tutti i dati sottomano per riprodurre, vedo solo che cercando di aggiungere un prodotto alla riga fattura l'errore visualizzato è il seguente

![image](https://github.com/user-attachments/assets/c44f938b-5f9c-4835-8ae3-9e49c1165b6a)

**Comment by SirAionTech** [comment]
> Ciao, purtroppo non ho tutti i dati sottomano per riprodurre, vedo solo che cercando di aggiungere un prodotto alla riga fattura l'errore visualizzato è il seguente
> 
> ![image](https://private-user-images.githubusercontent.com/55489873/388430733-c44f938b-5f9c-4835-8ae3-9e49c1165b6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxODA3NTEsIm5iZiI6MTczMjE4MDQ1MSwicGF0aCI6Ii81NTQ4OTg3My8zODg0MzA3MzMtYzQ0ZjkzOGItNWY5Yy00ODM1LThhZTMtOWU0OWMxMTY1YjZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIxVDA5MTQxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0MDJiZDdlYTc1MTVmMTk3MzdmOGI0NzA1NDMyM2NlYWMwMTRlNWM1MjQyYjY2OWRkYjUwYzMzYTZlNWNlYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.IEJhFtMvY9IbXTiC6teGK5MpcfzxYJoCJayXfpuDYZo)

Ok, già sapere che l'errore succede quando cerchi di aggiungere un prodotto alla riga è una info che non avevamo.

Quindi hai importato una fattura elettronica (con `l10n_it_fatturapa_in`), cerchi di aggiungere una riga e viene sollevato l'errore, e il modulo da correggere è `l10n_it_fatturapa_out`; ecco perché mi ero confuso :smile:

**Comment by francesco-ooops** [comment]
@SirAionTech suggerisci di risolvere l'errore in altro modulo?

**Comment by SirAionTech** [comment]
> @SirAionTech suggerisci di risolvere l'errore in altro modulo?

Nono, stavo solo cercando di capire meglio qual è il problema

**Comment by francesco-ooops** [comment]
@SirAionTech sbaglio o è duplicata di questa? https://github.com/OCA/l10n-italy/issues/4264

**Comment by SirAionTech** [comment]
> @SirAionTech sbaglio o è duplicata di questa? #4264

:thinking: sembra di sì; se con i passi indicati lì ottieni questo stesso problema chiudi pure questa.
Il file usato in quei test è https://github.com/OCA/l10n-italy/blob/cbf7cf14882e459e674943906100bebe5ceafb26/l10n_it_fatturapa_in/tests/data/IT02780790107_11004.xml.

**Comment by francesco-ooops** [comment]
Duplicata di https://github.com/OCA/l10n-italy/issues/4264
