### ISSUE TITLE
[10.0] l10n_it_corrispettivi Non è utilizzabile

### ISSUE THREAD

**Issue by FedericoRanieri** [OCA/l10n-italy#446]
Come vedo il modulo l10n_it_corrispettivi inserito nel branch 10.0 non ha ancora ricevuto il porting e presenta il codice scritto in old api.

Qualora non l'aveste già fatto posso procedere con la conversione in new api?

**Comment by eLBati** [comment]
@FedericoRanieri certo.

Per il porting a v10 guarda
https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0

Per qualunque dubbio chiedi

**Comment by FedericoRanieri** [comment]
@eLBati sono sul branch 10.0-mig-l10n_it_corrispettivi
Porting fatto.

**Comment by eLBati** [comment]
@FedericoRanieri ottimo. Crea pure la PR

**Comment by eLBati** [comment]
@FedericoRanieri non trovo il branch ```10.0-mig-l10n_it_corrispettivi```. Avevi fatto push da qualche parte?

**Comment by eLBati** [comment]
Allora @SimoRubi procede con il porting a v11 di ```l10n_it_corrispettivi```
