### ISSUE TITLE
Nella stampa raggruppata per conto le colone Dare-Avere non sono allineate  e viene stampata una colona in più. 

### ISSUE THREAD

**Issue by Tecsi-Alin** [OCA/l10n-italy#4469]
module: l10n_it_central_journal_reportlab
version: 16.0

**Steps to reproduce**
- Stampa raggruppata per conto

**Current behavior**
Le colone Dare-Avere non sono allineate  e viene stampata una colona in più a destra

**Expected behavior**

Il Layout di stampa dovrebbe essere uguale alla stampa in dettaglio.

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Chiudo perché è duplicata di https://github.com/OCA/l10n-italy/issues/4424, puoi seguire lì gli aggiornamenti

**Comment by Tecsi-Alin** [comment]
ok, grazie, avevo cercato prima ma non abbastanza bene. mi scuso
