### ISSUE TITLE
[8.0] Pagamento ritenute d'acconto

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#447]
Il pagamento delle fatture acquisto con ritenute d'acconto produce un errore, del tipo:

> Non è possibile applicare questa modifica su una registrazione confermata. È possibile solamente modificare alcuni dati non legali altrimenti è necessario annullare le registrazioni sezionali prima.
Movimento nome (id): xxxxx (151506).

Sono riuscito ad ovviare solamente impostando il sezionale pagamento, senza il flag "registra automaticamente i movimenti creati", poi sul pagamento in bozza risulta possibile la validazione.

**Comment by scigghia** [comment]
@alessandrocamilli @eLBati siete al corrente?

**Comment by alessandrocamilli** [comment]
Non ho mai usato la configurazione "registra automaticamente i movimenti creati", quindi non mi è capitato

**Comment by scigghia** [comment]
hai idea di come si possa risolvere?

**Comment by scigghia** [comment]
nessuno altro usa questo modulo ?

**Comment by eLBati** [comment]
@scigghia noi non sulla 8 che io sappia

**Comment by sergiocorato** [comment]
chiudo per inattività
