### ISSUE TITLE
wizard fatturazione ddt senza data

### ISSUE THREAD

**Issue by luca-vercelli** [OCA/l10n-italy#448]
Il wizard crea tutte le fatture senza data. Dal punto di vista legale è scorretto.
Credo che si potrebbe aggiungere un campo "Data fattura" sulla mappa di lancio ddt.create.invoice, e gestirla nel create_invoice().

**Comment by alessandrocamilli** [comment]
Buongiorno Luca,
i dati sono già presenti nel wizard di fatturazione DDT che esegui dall'area vendite (forse non hai l'ultima versione)
Se invece crei la fattura dal DDT, quindi una alla volta, allora penso che mettere un ulteriore wizard aumenterebbero solo i tempi.
Saluti
PS: Dal punto di vista legale, un fattura senza data sicuramente non va bene, ma quando la validi, la data viene impostata con quella odierna.

**Comment by luca-vercelli** [comment]
Buongiorno Alessandro,
hai ragione, non ho l'ultima versione. Chiudo la segnalazione.
