### ISSUE TITLE
l10n_it_asset_management: AccessError on account.move without asset_user

### ISSUE THREAD

**Issue by micheledic** [OCA/l10n-italy#4499]
## Module
l10n_it_asset_management

## Describe the bug
AccessError on account.move with asset_management installed for user not in asset_user group

## To Reproduce
**Affected versions**:
- [ ] `14.0`: ?
- [ ] `16.0`: https://github.com/OCA/l10n-italy/pull/4498

1. login with user without asset_user group
2. Access on an account.move
3. Error

**Comment by francesco-ooops** [comment]
@micheledic duplicata di https://github.com/OCA/l10n-italy/issues/4114
