### ISSUE TITLE
l10n_it_fatturapa_pec - nome file repository con carattere non valido

### ISSUE THREAD

**Issue by salvorapi** [OCA/l10n-italy#4501]
Sul modulo `l10n_it_fatturapa_pec` all'interno del path `l10n_it_fatturapa_pec/tests/data` è presente un file che contiene il carattere _colon_ (i due-punti ovvero ":" ) all'interno del nome 

[POSTA CERTIFICATA: Invio File 7339338 (base64).txt](https://github.com/OCA/l10n-italy/blob/16.0/l10n_it_fatturapa_pec/tests/data/POSTA%20CERTIFICATA%3A%20Invio%20File%207339338%20(base64).txt)

Questo potrebbe causare un problema durante il checkout su filesystem che non gestiscono questo tipo di caratteri nel nome del file.

**Comment by SirAionTech** [comment]
Grazie della segnalazione!
Ho riaperto la issue https://github.com/OCA/l10n-italy/issues/3805 che riportava proprio questo problema, usiamo quella così ci sono le correzioni che furono usate allora.
