### ISSUE TITLE
[10] l10n_it_ddt | Salto di numero

### ISSUE THREAD

**Issue by Ariz1789** [OCA/l10n-italy#466]
Quando viene creato un ddt dal movimento e si cerca di validare il movimento dalla pagina dei ddt ( **put in pack** e poi **package done**) se non c'è la disponibilità del materiale viene visualizzato l'avviso di errore, ma la sequence avanza comunque come se il ddt fosse stato confermato.

**Comment by sergiocorato** [comment]
Ho provato, non mi risulta (entrambi i bottoni non fanno nulla se non è disponibile il materiale)

**Comment by eLBati** [comment]
@Ariz1789 per ora chiudo. Se hai ancora il problema, descrivi precisamente le operazioni effettuate, il risultato osservato ed il risultato atteso
