### ISSUE TITLE
[8.0] res.partner and italian localization

### ISSUE THREAD

**Issue by gigidn** [OCA/l10n-italy#50]
2 module implement some useful extension .. pec and ateco.

But i need extension to fulfill the requirement of the fatturaPA module but this extension should be useful for other module like for example spesometro.

I mean:

1.2.4 <IscrizioneREA>
1.2.4.1 <Ufficio>
1.2.4.3 <CapitaleSociale>
1.2.4.4 <SocioUnico>
1.2.4.5 <StatoLiquidazione>

1.2.1.8 <RegimeFiscale>

The question is ... the right approach .. implement this extension inside the fatturaPA module or make a single filed extension or make a generic module whit all this extension and maybe pec+ateco?

**Comment by eLBati** [comment]
REA data: https://github.com/OCA/l10n-italy/pull/100
