### ISSUE TITLE
Ritenuta attiva

### ISSUE THREAD

**Issue by letyf1988** [OCA/l10n-italy#541]
Ciao, 
ho creato una ritenuta  con imposta 23% e coeff. imponibile 0.50.

 Eseguendo questi step:
- Creo una fattura attiva con la ritenuta d'acconto precedentemente creata
- Valido la fattura
- associo il pagamento di tutta la fattura

mi segnala un pagamento da poter riconciliare sul totale dell'imponbile e non sulla metà (se vado sulle ritenute è tutto corretto invece)
Saluti, 
Letizia
![image](https://user-images.githubusercontent.com/40765922/42168348-0a29e5cc-7e11-11e8-896a-3700b8b2dae3.png)

**Comment by jackjack82** [comment]
Salve Letizia,
 a me risulta il modulo funzioni al momento solo con le fatture passive.
Giacomo

2018-07-02 16:01 GMT+02:00 letyf1988 <notifications@github.com>:

**Comment by eLBati** [comment]
Confermo. Bisognerebbe impedire o segnalare l'utilizzo improprio nelle attive
cc @alessandrocamilli

**Comment by letyf1988** [comment]
Grazie mille, chiudo la issue.

**Comment by alessandrocamilli** [comment]
@letyf1988 https://github.com/OCA/l10n-italy/pull/600
