### ISSUE TITLE
[10.0] Data range menu duplication l10n_it_account

### ISSUE THREAD

**Issue by sergiocorato** [OCA/l10n-italy#574]
This lines [1] create a duplication in accounting menu when installed account_fiscal_year module [2]. Perhaps making l10n_it_account depending on account_fiscal_year could be a good idea.

[1]
https://github.com/OCA/l10n-italy/blob/c8a2a3f9554b0248af3754b826aaff4d675e6266/l10n_it_account/views/account_view.xml#L7-L13

[2]
https://github.com/OCA/account-financial-tools/blob/7bdbc9ada2c4bb156577c11180be1c6cdaad9ae7/account_fiscal_year/views/date_range_type.xml#L25-L29

**Comment by eLBati** [comment]
> Perhaps making l10n_it_account depending on account_fiscal_year could be a good idea

:+1:

**Comment by sergiocorato** [comment]
fatto in #577
