### ISSUE TITLE
Errore creazione nuovo Partner

### ISSUE THREAD

**Issue by acalantoni** [OCA/l10n-italy#617]
Salve quando vai per creare un nuovo partner mi da questo errore.

`Odoo Odoo Client Error

Error: Campo is_pa sconosciuto nel dominio [["is_pa","=",false]]

http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:1767
Traceback:
compute_domain@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:1767:42
compute_domain@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:2188:339
init/<@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:2222:341
trigger@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:3105:166
trigger@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:3109:115
on_form_changed@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:2138:93
load_record/<@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:2135:1
then/</</<@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:678
fire@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:541:281
add@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:542:467
then/</<@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:631
each@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:370:758
then/<@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:553
Deferred@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:548:189
then@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:518
load_record@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:2134:382
trigger@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:3105:166
trigger@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:3109:115
load_defaults/<@http://localhost:8069/web/content/570-55c1ded/web.assets_backend.js:2137:198
then/</</<@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:678
fire@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:541:281
fireWith@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:546:198
Deferred/</deferred[tuple[0]]@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:548:31
fire@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:541:281
fireWith@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:546:198
then/</</<@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:849
fire@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:541:281
fireWith@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:546:198
then/</</<@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:547:849
fire@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:541:281
fireWith@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:546:198
done@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:937:86
callback@http://localhost:8069/web/content/252-3cf7522/web.assets_common.js:957:15

`

**Comment by acalantoni** [comment]
10.0

Il mar 23 ott 2018, 09:22 Lorenzo Battistini <notifications@github.com> ha
scritto:

**Comment by eLBati** [comment]
@acalantoni appena provato sul [runbot di OCA/l10n-italy](https://runbot.odoo-community.org/runbot/repo/github-com-oca-l10n-italy-122) e non rilevo problemi.
Assicurati di avere l'ultima versione di tutti i moduli

**Comment by askweb2019** [comment]
Buongiorno,
io ho lo stesso problema identico, ma non riesco ad aggiornare manualmente l'unico modulo da aggiornare, il modulo l10n_it_ipa dalla versione 10.0.1.0.0 alla 10.0.2.0.0 perchè quando sposto i file nella cartella ADDONS ottengo un INTERNAL SERVER ERROR. Posso eventualmente allegare il log dell'errore, ma fondamentalmente dice **ProgrammingError: column res_partner.is_pa does not exist**
Qualcuno ha un idea di cosa potrebbe essere?
Grazie mille
