### ISSUE TITLE
[10.0, 11.0] l10n_it_ddt ux improvements suggestion

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#655]
Hi, i think some UX improvement could be helpful:

- shipping infos could be placed right above notebook; shown and set required if auto ddt creation is checked
- Auto ddt creation check could be moved to settings
- What's the goal for ddt_type?
- Validating picking on "Set Done" in DDT: if all products in picking have enough stock on hand for the selected warehouse picking should be validated (aka reserved_qty = initial_demand)
- amount_total, tax, amount_total on DDT Row details
- What's the goal to have DDT and Package Preparation menu item in Inventory?

Comments?

**Comment by sergiocorato** [comment]
chiudo per inattività
