### ISSUE TITLE
Verificare se la VAT della company inizia per IT

### ISSUE THREAD

**Issue by taifu** [OCA/l10n-italy#660]
Il file XML di fatturazione elettronica viene generato con un IdCodice errato se la Company ha la partita iva senza IT.

https://github.com/OCA/l10n-italy/blob/5c8aecce24cc44815fae35a87a75e094fa8e6ec4/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L128

**Comment by eLBati** [comment]
@taifu è possibile inviare fatture elettroniche al SDI se non hai una P IVA italiana?

**Comment by taifu** [comment]
Ovviamente no. Sto parlando di una Company che ha nella partita IVA un valore corretto (11 cifre) ma senza "IT". Con questa istruzione, il valore di IdCodice diventa un valore errato di 9 cifre

**Comment by eLBati** [comment]
Però odoo dovrebbe impedirti di inserite una PIVA senza IT

**Comment by taifu** [comment]
Anche nella Company?

**Comment by eLBati** [comment]
Sì

**Comment by taifu** [comment]
Sta di fatto che quel valore era presente nel database (si vede che nella migrazione da versioni precedenti non viene fatta questa correzione). Chiudi pure la issue allora.
