### ISSUE TITLE
[10.0] [11.0] [12.0] Incompatibility l10n_it_fiscalcode - l10n_it_fatturapa

### ISSUE THREAD

**Issue by eLBati** [OCA/l10n-italy#668]
Steps:

 - Install l10n_it_fatturapa
 - Go to partner list and click create
 - Set 'Subjected to electronic invoice'
 - Click 'Compute F.C.' button

Get `Il partner %s, con Codice Destinatario '0000000', deve avere o P.IVA o codice fiscale`

**Comment by sergiocorato** [comment]
chiudo per inattività
