### ISSUE TITLE
Question about dependencies for version 12.0

### ISSUE THREAD

**Issue by odlan** [OCA/l10n-italy#673]
I have Odoo 12.0 version installed and I want add l10n-italy version 12.0 when it will be ready. This module is almost ready for version 12.0 of Odoo but I see in dependencies oca_dependencies.txt that it needs some external modules (account-financial-tools and account-financial-reporting) not fully ready for version 12.0. When l10n-italy 12.0 will be ready for version 12 I can install it though if account-financial-tools and account-financial-reporting are not ready for version 12.0?

**Comment by eLBati** [comment]
@odlan You don't need all the modules of repositories `account-financial-tools` and `account-financial-reporting`. You need the modules which Italian modules depend on.
For instance, `l10n_it_account` depends on `account_fiscal_year` and `account_tax_balance`: to install `l10n_it_account`  you need those 2 modules coming from `account-financial-tools` and `account-financial-reporting` repos.

In general, modules are not released on stable branches unless their dependencies are released either
