### ISSUE TITLE
[8.0] causale con linee vuote

### ISSUE THREAD

**Issue by alxster** [OCA/l10n-italy#697]
Se la causale delle fatture ha linee vuote succede ciò che segue:
-nel branch principale c'è un errore di decodifica all'atto dell'esportazione
-nella pr 615 la fattura viene rifiutata dal sistema di controllo SDI (l'esportazione produce un tag Causal vuoto per ogni linea vuota)

In locale ho momentaneamente risolto modificando il ciclo in setDatiGeneraliDocumento:
```
            for causale in caus_list:
                if causale:
                    # Remove non latin chars, but go back to unicode string,
                    # as expected by String200LatinType
                    causale = causale.encode(
                        'latin', 'ignore').decode('latin')
                    body.DatiGenerali.DatiGeneraliDocumento.Causale.append(causale)

```

**Comment by eLBati** [comment]
@alxster grazie.
Correzione proposta: https://github.com/OCA/l10n-italy/pull/699

**Comment by eLBati** [comment]
@alxster correzione inclusa su 8.0 con https://github.com/OCA/l10n-italy/pull/615/commits/3e271eecd199027bcfff05d4ea89a841eefcec62

**Comment by sergiocorato** [comment]
chiudo perchè risolta
