### ISSUE TITLE
[10.0] l10n_it_fatturapa

### ISSUE THREAD

**Issue by lucasirtori** [OCA/l10n-italy#727]
sto cercando di installare il modulo fattura pa su odoo 10 in ubuntu 14 ma da questo errore

Successfully  imported module 'account_fiscal_year' Successfully imported module 'l10n_it_split_payment' Successfully imported module 'partner_firstname' Successfully imported module 'l10n_it_account' Successfully imported module 'l10n_it_esigibilita_iva' Successfully imported module 'l10n_it_account_tax_kind' Successfully imported module 'l10n_it_fiscal_document_type' Successfully imported module 'l10n_it_fiscalcode' Error while importing module 'l10n_it_ipa': u'"Error while validating  constraint\n\nIl campo `is_pa` non esiste\n\nContesto errore:\nVista  `res.partner.ipa.form`\n[view_id: 2496, xml_id:  l10n_it_ipa.view_partner_ipa_form, model: res.partner, parent_id:  124]\nNone" while parsing  /tmp/tmpa3fbLr/l10n_it_ipa/view/partner_view.xml:5, near\n<record  id="view_partner_ipa_form" model="ir.ui.view">\n            <field  name="name">res.partner.ipa.form</field>\n             <field name="model">res.partner</field>\n             <field name="inherit_id" ref="base.view_partner_form"/>\n             <field name="arch" type="xml">\n                 <data><field name="website" position="after">\n                     <field name="ipa_code" placeholder="IPA123"  attrs="{\'invisible\': [(\'is_pa\',\'=\', False)]}"/>\n                 </field>\n                <field name="company_type"  position="after">\n                    <div attrs="{\'invisible\':  [(\'is_company\',\'=\', False)]}" class="oe_edit_only">\n                         <field name="is_pa"/><label for="is_pa"/>\n                     </div>\n                </field>\n             </data></field>\n        </record>' Error while importing module 'date_range': u'"Error while validating  constraint\n\nIl campo `parent_id` non esiste\n\nContesto errore:\nVista  `date.range.tree`\n[view_id: 2007, xml_id:  date_range.view_date_range_tree, model: date.range, parent_id:  n/d]\nNone" while parsing  /tmp/tmpa3fbLr/date_range/views/date_range_view.xml:3, near\n<record  id="view_date_range_tree" model="ir.ui.view">\n        <field  name="name">date.range.tree</field>\n        <field  name="model">date.range</field>\n        <field name="arch"  type="xml">\n            <tree editable="bottom" string="Date  range">\n                <field name="name"/>\n                 <field name="type_id"/>\n                <field  name="date_start"/>\n                <field name="date_end"/>\n                 <field name="company_id"  groups="base.group_multi_company" options="{\'no_create\': True}"/>\n                 <field name="parent_type_id" invisible="1"/>\n                 <field name="parent_id" options="{\'no_create\':  True}"/>\n                <field name="active"/>\n             </tree>\n        </field>\n    </record>' Error while importing module 'l10n_it_fiscal_payment_term': u"Module  loading l10n_it_fiscal_payment_term failed: file  /tmp/tmpa3fbLr/l10n_it_fiscal_payment_term/security/ir.model.access.csv  could not be processed:\n Nessun record trovato per id esterno  'model_fatturapa_payment_term' nel campo 'Object'\nMissing required  value for the field 'Object' (model_id)\nNessun record trovato per id  esterno 'model_fatturapa_payment_term' nel campo 'Object'\nMissing  required value for the field 'Object' (model_id)\nNessun record trovato  per id esterno 'model_fatturapa_payment_method' nel campo  'Object'\nMissing required value for the field 'Object'  (model_id)\nNessun record trovato per id esterno  'model_fatturapa_payment_method' nel campo 'Object'\nMissing required  value for the field 'Object' (model_id)" Error while importing module 'l10n_it_fatturapa_out': u'"Error while  validating constraint\n\nIl campo `report_print_menu` non  esiste\n\nContesto errore:\nVista `Export Electronic Invoice`\n[view_id:  3529, xml_id: l10n_it_fatturapa_out.wizard_export_fatturapa_form_view,  model: wizard.export.fatturapa, parent_id: n/d]\nNone" while parsing  /tmp/tmpa3fbLr/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa_view.xml:3,  near\n<record id="wizard_export_fatturapa_form_view"  model="ir.ui.view">\n        <field name="name">Export  Electronic Invoice</field>\n        <field  name="model">wizard.export.fatturapa</field>\n        <field  name="arch" type="xml">\n            <form string="Export  Electronic Invoice">\n                <sheet>\n                     <group>\n                        <separator colspan="2"  string="If you want to add a PDF version of the invoice into the XML,  select which one"/>\n                        <field  name="report_print_menu" string="Attached report"  widget="selection"/>\n                    </group>\n                 </sheet>\n                <footer>\n                     <button name="exportFatturaPA" string="Export" type="object"  class="oe_highlight"/>\n                    <button  special="cancel" string="Cancel"/>\n                </footer>\n             </form>\n        </field>\n    </record>' Error while importing module 'l10n_it_rea': u'"Error while validating  constraint\n\nIl campo `rea_office` non esiste\n\nContesto  errore:\nVista `view_company_form_rea`\n[view_id: 3541, xml_id: n/d,  model: res.company, parent_id: 111]\nNone" while parsing  /tmp/tmpa3fbLr/l10n_it_rea/views/company_view.xml:4, near\n<record  model="ir.ui.view" id="view_company_form_rea">\n        <field  name="name">view_company_form_rea</field>\n        <field  name="model">res.company</field>\n        <field  name="inherit_id" ref="base.view_company_form"/>\n        <field  name="arch" type="xml">\n            <data><notebook  position="inside">\n                <page string="REA data">\n                     <group>\n                        <field  name="rea_office"/>\n                        <field  name="rea_code"/>\n                        <field  name="rea_capital"/>\n                        <field  name="rea_member_type"/>\n                        <field  name="rea_liquidation_state"/>\n                        <field  name="company_registry"/>\n                    </group>\n                 </page>\n            </notebook>\n             <field name="company_registry" position="replace"/>\n         </data></field>\n    </record>' Error while importing module 'l10n_it_fatturapa': u'Dipendenze modulo  non riscontrate: l10n_it_fiscal_payment_term\n'
--

**Comment by OpenCode** [comment]
@lucasirtori Essendo la issue molto vecchia e senza sollecito per adesso la chiuso. Qualora il problema persiste ti consiglio di:
- Aggiornare in ogni caso la versione del sistema operativo perché è vecchia di 5 anni
- Commentare nuovamente la issue indicando il sistema di installazione utilizzato
- Incolla il codice nella issue racchiudendolo tra i triplici apici `

Grazie e buon lavoro.
