### ISSUE TITLE
[10.0] l10n_it_fatturapa con dipendenza partner_firstname

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#728]
Il modulo **_l10n_it_fatturapa_** installa come dipendenza **_partner_firstname_** che, in fase di inserimento di un'anagrafica, rende obbligatori i campi **_First Name_** e **_Last Name_**, impedendo così la modifica di **_default user_** (_Settings > General setting > New users access rights > Related Partner_).

**Comment by eLBati** [comment]
> Mi interessava capire il motivo per cui si è scelto di impostare partner_firstname come dipendenza

Perchè nell'XML della fattura elettronica, in caso di persone fisiche, bisogna riempire i campi Nome e Cognome
