### ISSUE TITLE
[10.0] Errore campo IdTrasmittente/IdCodice

### ISSUE THREAD

**Issue by Cicciodev** [OCA/l10n-italy#747]
Buongiorno,
segnalo il seguente errore nella generazione del xml della fatturazione elettronica:
Nel campo IdTrasmittente/IdCodice viene inserito sempre il campo partita IVA, ora è vero che molte aziende hanno il campo Partita IVA e Codice Fiscale che corrispondono ma nel caso di Liberi Professionisti e di Aziende particolarmente vecchie questo non è sempre vero. 
Lo segnalo perchè in fase di validazione del xml da parte del sistema di interscambio ricevo l'errore 300 relativo appunto al campo IdTrasmittente/IdCodice errato, inserendo manualmente il Codice Fiscale nel campo, la fattura xml viene validata.
Leggendo la documentazione mi sembra di capire che quel campo deve essere popolato con il codice fiscale: https://www.fatturapa.gov.it/export/fatturazione/it/c-11.htm 

Vi chiedo quale sia il modo più corretto di procedere? Modifico la procedura in modo che peschi il codice fiscale e se assente la partita IVA?
Nel caso mi fossi perso qualche flag in configurazione che risolve il problema vi chiedo scusa in anticipo.
Grazie

**Comment by sergiocorato** [comment]
Ciao @Cicciodev , come vedi da https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L126 il campo inserito prioritariamente è il codice fiscale, poi sostituito dalla partita iva senza l'IT se mancante. Probabilmente hai inserito nel partner collegato all'azienda la partita IVA completa di IT.
Prego.

**Comment by Cicciodev** [comment]
Ciao @sergiocorato, ti ringrazio molte, pensavo che i dati fossero pescati da res.company, ma giustamente nel fattura c'è un res.partner.
Grazie molte e scusate per l'apertura dell'issue.
