### ISSUE TITLE
[11] l10n_it_account - header and footer printed more than once when more documents selected and printed

### ISSUE THREAD

**Issue by taifu** [OCA/l10n-italy#758]
@eLBati  the function subst in 11.0 l10n_it_account/reports is the 10.0 version without any modification.

This is the original Odoo 10.0 version:
https://github.com/odoo/odoo/blob/10.0/addons/report/views/layout_templates.xml#L194

These are the 10.0 and 11.0 patched versions:
https://github.com/OCA/l10n-italy/blob/10.0/l10n_it_account/reports/account_reports_view.xml#L84
https://github.com/OCA/l10n-italy/blob/11.0/l10n_it_account/reports/account_reports_view.xml#L94

These are the original Odoo 11.0 and 12.0 versions:
https://github.com/odoo/odoo/blob/11.0/addons/web/views/report_templates.xml#L104
https://github.com/odoo/odoo/blob/12.0/addons/web/views/report_templates.xml#L109

This is the 12.0 patched version:
https://github.com/OCA/l10n-italy/blob/fbb6905b0872bf1ece52e23c3e8b0b00ad7d2d2e/l10n_it_account/reports/account_reports_view.xml#L90

The fix should be a backporting "as is" of the 12.0 version to 11.0.

Unfortunately there is also a css problem as the 11.0 XML file reference a css that doesn't exist anymore in 11.0:
https://github.com/OCA/l10n-italy/blob/11.0/l10n_it_account/reports/account_reports_view.xml#L90

The 12.0 version reference a css that doesn't yet exist on 11:
https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_account/reports/account_reports_view.xml#L86

Thanks!

**Comment by sergiocorato** [comment]
chiudo per inattività
