### ISSUE TITLE
Ricevute bancarie and account_due_list

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#76]
here my PR to port account_due_list on Odoo (https://github.com/OCA/bank-payment/pull/84) 
this is needed by l10n_it_ricevute_bancarie, but if we plan to use followup (like Lorenzo says to me) i can close that PR and merge account_due_list with my account_due_list_enhanced in a single addon, to give us also print of "scadenzario"
otherwise account_due_list as part of ricevute bancarie could be a solution

wath do you think about?

**Comment by eLBati** [comment]
account_due_list is merged, I'm closing
