### ISSUE TITLE
[10.0] l10n_it_fatturapa_in  -  l10n_it_fatturapa_out  error

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#766]
whit this module installed i have the following error in log file, and the web interface, haven't link

> 
> 2019-01-03 09:27:47,848 6614 INFO ? odoo: Odoo version 10.0-20170312
> 2019-01-03 09:27:47,848 6614 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
> 2019-01-03 09:27:47,848 6614 INFO ? odoo: addons paths: ['/usr/lib/python2.7/site-packages/odoo/addons', '/var/lib/odoo/addons/10.0']
> 2019-01-03 09:27:47,849 6614 INFO ? odoo: database: odoo@default:default
> 2019-01-03 09:27:47,856 6614 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
> 2019-01-03 09:28:00,407 6614 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
> 2019-01-03 09:28:00,732 6614 INFO ? werkzeug: 127.0.0.1 - - [03/Jan/2019 09:28:00] "POST /longpolling/poll HTTP/1.1" 500 -
> 2019-01-03 09:28:00,747 6614 ERROR ? werkzeug: Error on request:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
>     execute(self.server.app)
>   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 182, in execute
>     application_iter = app(environ, start_response)
>   File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 250, in app
>     return self.app(e, s)
>   File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
>     return application_unproxied(environ, start_response)
>   File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
>     result = handler(environ, start_response)
>   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1305, in __call__
>     self.load_addons()
>   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1326, in load_addons
>     m = __import__('odoo.addons.' + module)
>   File "/usr/lib/python2.7/site-packages/odoo/modules/module.py", line 81, in load_module
>     execfile(modfile, new_mod.__dict__)
>   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/__init__.py", line 5, in <module>
>     from . import wizard
>   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/__init__.py", line 3, in <module>
>     from . import wizard_import_fatturapa
>   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 10, in <module>
>     from odoo.addons.l10n_it_fatturapa.bindings import fatturapa_v_1_2
>   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/bindings/fatturapa_v_1_2.py", line 12, in <module>
>     from . import _ds as _ImportedBinding__ds
>   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/bindings/_ds.py", line 35, in <module>
>     raise pyxb.PyXBVersionError(_PyXBVersion)
> PyXBVersionError: 1.2.5

AND  whit also l10n_it_fatturapa_out i have the following log:

> 
> > 2019-01-03 08:30:12,247 1821 INFO ? odoo: Odoo version 10.0-20170312
> > 2019-01-03 08:30:12,266 1821 INFO ? odoo: Using configuration file at /etc/odoo/odoo.conf
> > 2019-01-03 08:30:12,266 1821 INFO ? odoo: addons paths: ['/usr/lib/python2.7/site-packages/odoo/addons', '/var/lib/odoo/addons/10.0']
> > 2019-01-03 08:30:12,266 1821 INFO ? odoo: database: odoo@default:default
> > 2019-01-03 08:30:12,513 1821 INFO ? odoo.service.server: HTTP service (werkzeug) running on 0.0.0.0:8069
> > 2019-01-03 09:01:05,602 1821 INFO ? odoo.addons.bus.models.bus: Bus.loop listen imbus on db postgres
> > 2019-01-03 09:01:09,382 1821 INFO ? werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:09] "GET / HTTP/1.1" 500 -
> > 2019-01-03 09:01:09,495 1821 ERROR ? werkzeug: Error on request:
> > Traceback (most recent call last):
> >   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
> >     execute(self.server.app)
> >   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 182, in execute
> >     application_iter = app(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 250, in app
> >     return self.app(e, s)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
> >     return application_unproxied(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
> >     result = handler(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1305, in __call__
> >     self.load_addons()
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1326, in load_addons
> >     m = __import__('odoo.addons.' + module)
> >   File "/usr/lib/python2.7/site-packages/odoo/modules/module.py", line 81, in load_module
> >     execfile(modfile, new_mod.__dict__)
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/__init__.py", line 5, in <module>
> >     from . import wizard
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/__init__.py", line 3, in <module>
> >     from . import wizard_import_fatturapa
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 10, in <module>
> >     from odoo.addons.l10n_it_fatturapa.bindings import fatturapa_v_1_2
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/bindings/fatturapa_v_1_2.py", line 12, in <module>
> >     from . import _ds as _ImportedBinding__ds
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/bindings/_ds.py", line 35, in <module>
> >     raise pyxb.PyXBVersionError(_PyXBVersion)
> > PyXBVersionError: 1.2.5
> > 019-01-03 09:01:10,676 1821 INFO odoo odoo.modules.loading: loading 1 modules...
> > 2019-01-03 09:01:10,726 1821 INFO odoo odoo.modules.loading: 1 modules loaded in 0.05s, 0 queries
> > 2019-01-03 09:01:11,491 1821 INFO odoo odoo.modules.loading: loading 44 modules...
> > 2019-01-03 09:01:13,646 1821 INFO odoo odoo.addons.report.models.report: You need Wkhtmltopdf to print a pdf version of the reports.
> > 2019-01-03 09:01:14,254 1821 INFO odoo odoo.modules.loading: 44 modules loaded in 2.76s, 0 queries
> > 2019-01-03 09:01:15,206 1821 INFO odoo odoo.modules.loading: Modules loaded.
> > 2019-01-03 09:01:15,316 1821 INFO odoo odoo.addons.base.ir.ir_http: Generating routing map
> > 2019-01-03 09:01:15,316 1821 INFO odoo odoo.addons.base.ir.ir_http: Generating routing map
> > 2019-01-03 09:01:15,512 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:15] "GET /favicon.ico HTTP/1.1" 404 -
> > 2019-01-03 09:01:15,512 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:15] "GET /favicon.ico HTTP/1.1" 404 -
> > 2019-01-03 09:01:16,726 1821 INFO odoo odoo.addons.base.ir.ir_attachment: filestore gc 35 checked, 3 removed
> > 2019-01-03 09:01:17,450 1821 INFO odoo odoo.models.unlink: User #1 deleted wizard.multi.charts.accounts records with IDs: [1, 2]
> > 2019-01-03 09:01:17,816 1821 INFO odoo odoo.models.unlink: User #1 deleted account.bank.accounts.wizard records with IDs: [1, 2]
> > 2019-01-03 09:01:18,045 1821 INFO odoo odoo.addons.base.ir.ir_autovacuum: GC'd 1 user log entries
> > 2019-01-03 09:01:18,772 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:18] "GET / HTTP/1.1" 303 -
> > 2019-01-03 09:01:18,860 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:18] "GET /web HTTP/1.1" 303 -
> > 2019-01-03 09:01:19,734 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:19] "GET /web/login HTTP/1.1" 200 -
> > 2019-01-03 09:01:19,993 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:19] "GET /web/content/321-6747cb4/web.assets_frontend.js HTTP/1.1" 200 -
> > 2019-01-03 09:01:20,039 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web/content/251-e0a51d6/web.assets_common.js HTTP/1.1" 200 -
> > 2019-01-03 09:01:20,042 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web/content/320-6747cb4/web.assets_frontend.0.css HTTP/1.1" 200
> >  -
> > 2019-01-03 09:01:20,058 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web/content/246-e0a51d6/web.assets_common.0.css HTTP/1.1" 200 -
> > 2019-01-03 09:01:20,180 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web/binary/company_logo HTTP/1.1" 200 -
> > 2019-01-03 09:01:20,211 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web/webclient/qweb?mods= HTTP/1.1" 200 -
> > 2019-01-03 09:01:20,217 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "POST /web/webclient/bootstrap_translations HTTP/1.1" 200 -
> > 2019-01-03 09:01:20,241 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web_editor/static/src/xml/ace.xml HTTP/1.1" 404 -
> > 2019-01-03 09:01:20,341 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "GET /web/static/src/img/favicon.ico HTTP/1.1" 404 -
> > 2019-01-03 09:01:20,360 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:20] "POST /web/webclient/translations HTTP/1.1" 200 -
> > 2019-01-03 09:01:41,868 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:41] "POST /web/login HTTP/1.1" 303 -
> > 2019-01-03 09:01:46,036 1821 INFO odoo odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [471, 470]
> > 2019-01-03 09:01:47,468 1821 INFO odoo odoo.models.unlink: User #1 deleted ir.attachment records with IDs: [472]
> > 2019-01-03 09:01:47,713 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:47] "GET /web HTTP/1.1" 200 -
> > 2019-01-03 09:01:47,887 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:47] "GET /web/content/250-1d22b49/web_editor.assets_editor.0.css HTTP/1.1" 200 -
> > 2019-01-03 09:01:47,891 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:47] "GET /web/content/249-ac2ba23/web_editor.summernote.0.css HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,030 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/content/474-065de3e/web.assets_backend.1.css HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,063 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/content/253-ac2ba23/web_editor.summernote.js HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,092 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/content/254-1d22b49/web_editor.assets_editor.js HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,103 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/content/473-065de3e/web.assets_backend.0.css HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,151 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/content/475-065de3e/web.assets_backend.js HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,452 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/webclient/qweb?mods=account,account_bank_statement_import,l10n_it_esigibilita_iva,l10n_it_account,document,l10n_it_fatturapa,base,bus,base_import,date_range,l10n_it HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,528 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web_editor/static/src/xml/ace.xml HTTP/1.1" 404 -
> > 2019-01-03 09:01:48,571 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "POST /web/dataset/call HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,642 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web_editor/static/src/xml/editor.xml HTTP/1.1" 404 -
> > 2019-01-03 09:01:48,656 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web_editor/static/src/xml/snippets.xml HTTP/1.1" 404 -
> > 2019-01-03 09:01:48,712 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "POST /web/webclient/translations HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,772 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "POST /web/webclient/translations HTTP/1.1" 200 -
> > 2019-01-03 09:01:48,781 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/static/src/img/favicon.ico HTTP/1.1" 404 -
> > 2019-01-03 09:01:48,902 1821 INFO odoo werkzeug: 127.0.0.1 - - [03/Jan/2019 09:01:48] "GET /web/webclient/locale/it_IT HTTP/1.1" 500 -
> > 2019-01-03 09:01:48,967 1821 ERROR odoo werkzeug: Error on request:
> > Traceback (most recent call last):
> >   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
> >     execute(self.server.app)
> >   File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 182, in execute
> >     application_iter = app(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 250, in app
> >     return self.app(e, s)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
> >     return application_unproxied(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
> >     result = handler(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1306, in __call__
> >     return self.dispatch(environ, start_response)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1471, in dispatch
> >     result = ir_http._dispatch()
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
> >     return super(IrHttp, cls)._dispatch()
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 199, in _dispatch
> >     return cls._handle_exception(e)
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 169, in _handle_exception
> >     return request._handle_exception(exception)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 766, in _handle_exception
> >     return super(HttpRequest, self)._handle_exception(exception)
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_http.py", line 195, in _dispatch
> >     result = request.dispatch()
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 825, in dispatch
> >     r = self._call_function(**self.params)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 331, in _call_function
> >     return checked_call(self.db, *args, **kwargs)
> >   File "/usr/lib/python2.7/site-packages/odoo/service/model.py", line 119, in wrapper
> >     return f(dbname, *args, **kwargs)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 324, in checked_call
> >     result = self.endpoint(*a, **kw)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 933, in __call__
> >     return self.method(*args, **kw)
> >   File "/usr/lib/python2.7/site-packages/odoo/http.py", line 504, in response_wrap
> >     response = f(*args, **kw)
> >   File "/usr/lib/python2.7/site-packages/odoo/addons/web/controllers/main.py", line 491, in load_locale
> >     addons_path = http.addons_manifest['web']['addons_path']
> > KeyError: 'web'
>

**Comment by eLBati** [comment]
You have to install PyXB 1.2.5

**Comment by bitit-it** [comment]
i have upgrade 
pip install --upgrade PyXB
Requirement already up-to-date: PyXB in /usr/lib/python2.7/site-packages (1.2.6)

but don't work :(

**Comment by bitit-it** [comment]
2019-01-03 14:55:49,873 10716 INFO ? werkzeug: 127.0.0.1 - - [03/Jan/2019 14:55:49] "POST /longpolling/poll HTTP/1.1" 500 -
2019-01-03 14:55:49,886 10716 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 194, in run_wsgi
    execute(self.server.app)
  File "/usr/lib/python2.7/site-packages/werkzeug/serving.py", line 182, in execute
    application_iter = app(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 184, in application
    return application_unproxied(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/service/wsgi_server.py", line 170, in application_unproxied
    result = handler(environ, start_response)
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1305, in __call__
    self.load_addons()
  File "/usr/lib/python2.7/site-packages/odoo/http.py", line 1326, in load_addons
    m = __import__('odoo.addons.' + module)
  File "/usr/lib/python2.7/site-packages/odoo/modules/module.py", line 81, in load_module
    execfile(modfile, new_mod.__dict__)
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/__init__.py", line 5, in <module>
    from . import wizard
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/__init__.py", line 3, in <module>
    from . import wizard_import_fatturapa
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa_in/wizard/wizard_import_fatturapa.py", line 10, in <module>
    from odoo.addons.l10n_it_fatturapa.bindings import fatturapa_v_1_2
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/bindings/fatturapa_v_1_2.py", line 12, in <module>
    from . import _ds as _ImportedBinding__ds
  File "/usr/lib/python2.7/site-packages/odoo/addons/l10n_it_fatturapa/bindings/_ds.py", line 35, in <module>
    raise pyxb.PyXBVersionError(_PyXBVersion)
PyXBVersionError: 1.2.5

**Comment by eLBati** [comment]
`pip install PyXB==1.2.5`

**Comment by bitit-it** [comment]
ok.. thank you. work.
