### ISSUE TITLE
[10.0] bollo virtuale

### ISSUE THREAD

**Issue by stevech091** [OCA/l10n-italy#769]
ho installato il modulo per il bollo virtuale.
ho configurato come precisione decimale sul prezzo (product price) 4 cifre decimali
ho creato una fattura che sia soggetta a bollo virtuale.
La validazione non crea nessun problema
Quando genero il file xml mi appare questo errore
"
Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}Amount2DecimalType pattern constraint violated by value 2.0000 
"
se abbasso le precisione sul presso a 2 cifre l'errore non appare.

**Comment by SimoRubi** [comment]
ci guardo
