### ISSUE TITLE
unable to import E-Invoice with module l10n_it_fatturapa_in

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#772]
from menù
Fattura Elettronica (electronic Invoice)
---- file e fatture in ingresso ( incoming files and invoices )
---------- importa ( import) 
i  can import only .csv .xla .xlsx .ods   
NOT .xml or .p7m 

what's my error?
i have odoo10.x
Enrico

**Comment by primes2h** [comment]
You have to click on "Create", then "Load file".
