### ISSUE TITLE
https://github.com/OmniaSolutions/l10n-italy/blob/11232814c50cfecee2cbcbc672ea9c620f5990e5/l10n_it_fatturapa/models/partner.py#L81

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#782]
https://github.com/OmniaSolutions/l10n-italy/blob/11232814c50cfecee2cbcbc672ea9c620f5990e5/l10n_it_fatturapa/models/partner.py#L81
forse necessita di qualche dipendenza che non è indicata nel manifest?
al salvataggio dell'anagrafica partner ottengo il seguente errore:

> AttributeError: "Field 'lastname' does not exist in object 'browse_record(res.partner, 5196)'"

_Originally posted by @scigghia in https://github.com/OCA/l10n-italy/pull/659#issuecomment-451397818_

è necessario aggiungere questa dipendenza https://github.com/OCA/partner-contact/blob/7.0/partner_firstname/partner.py

**Comment by sergiocorato** [comment]
si, puoi fare la PR?

**Comment by scigghia** [comment]
si,
https://github.com/OmniaSolutions/l10n-italy/pull/11

**Comment by sergiocorato** [comment]
ok chiudo qui
