### ISSUE TITLE
problem in e-invoice export

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#783]
Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}ProvinciaType pattern constraint violated by value it 

I'm testing odoo for e-invoice 

i have created a invoice on draft without validations actions, 
I have tried to export into electronic invoice but i have  a error that i have wrote  above .
enrico

**Comment by sergiocorato** [comment]
il valore `it` nella provincia è chiaramente da correggere nel partner

**Comment by bitit-it** [comment]
Ho "Arezzo"  nel campo provincia del cliente.

da dove lo prende il valore?

Enrico

**Comment by bitit-it** [comment]
anche per un altro cliente con provincia "Perugia" stesso errore 
Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}ProvinciaType pattern constraint violated by value it

**Comment by eLBati** [comment]
Che versione di odoo?

**Comment by bitit-it** [comment]
10.x

**Comment by bitit-it** [comment]
Non so se è perchè è ancor ain bozze, non riesco a valdarla, perchè mi da questo messaggio 
"Occorre definire la sequenza nel sezionale relativo a questa fattura. "
che sinceramente non so cosa vuol dire :( non sono un contabile e non riesco a trovare un tutorial leggibile al riguardo .

Enrico

**Comment by bitit-it** [comment]
si "Electronic Invoices"

Enrico

**Comment by sergiocorato** [comment]
la segnalazione sulla sequenza è relativa a quella del sezionale in cui è la fattura, la sequenza `Electronic Invoices` è un numeratore per i file xml, che non c'entrano

**Comment by bitit-it** [comment]
e quindi?

scusate ma mi son proprio perso 
Enrico

**Comment by bitit-it** [comment]
adesso un altro problema,   su contabilità > configurazione  
quando provo a modificare ho questo errore:
"
Odoo Attenzione - Errore di Validazione
The code of the account must be unique per company !
"

**Comment by bitit-it** [comment]
ps. non ho messo regime ordinario ma forfettario art1 c54-89 L. 190/2014

**Comment by bitit-it** [comment]
allora, ho cancellato  tutto e ho riniziato da capo, ho provato a inserire  come documento la fattura semplificata e me la fa validare, ma rimane l'errore in esportazione.

Enrico

**Comment by bitit-it** [comment]
> adesso un altro problema, su contabilità > configurazione
> quando provo a modificare ho questo errore:
> "
> Odoo Attenzione - Errore di Validazione
> The code of the account must be unique per company !
> "

ho risolto ..

**Comment by bitit-it** [comment]
segnalo anche che nell'importazione della fattura elettronica fornitori da tiscali,  non ha importato la data della scadenza  e il preview da errore :
http://localhost:8069/fatturapa/preview/559

**Comment by bitit-it** [comment]
segnalo anche che una volta importata la fattura fornitore,  in posizione di bozza non validata, se cerco di stamparla,  da html, (non avendo le librerie Wkhtmltopdf),  ci sono i dati del fornitore ma non del destinatario . 

idem anche una volta validata, si apre la versione html senza i dati del destinatario. 
il numero fattura va a riferimento , che per altro viene scritto con  la "o" finale riportata  a capo

se clocco stampa, continua ad aprire frame html, l'unico modo per avviare la stampa è cliccare sul tasto destro> questo riquadro >stampa 
enrico 

Enrico

**Comment by bitit-it** [comment]
lo stesso mi succede per le fatture  emesse , non appare la mia ragione sociale ne la modalità di pagamento .
![screenshot_20190105_115147](https://user-images.githubusercontent.com/43685677/50723895-5c619e00-10e4-11e9-943d-2c59a7f28b60.jpg)

**Comment by eLBati** [comment]
> segnalo anche che nell'importazione della fattura elettronica fornitori da tiscali, non ha importato la data della scadenza

@bitit-it Il campo dell'XML `DataScadenzaPagamento` , essendo all'interno dell'elemento `DettaglioPagamento`, che può avere occorrenza `1.N` non è mappato direttamente nel campo scadenza della fattura, ma lo trovi, oltre che nell'anteprima, nel tab dei dettagli della fattura elettronica, sotto 'pagamenti'

**Comment by eLBati** [comment]
Tutte le altre segnalazioni sembrano legate ad una errata installazione di odoo o comunque alla configurazione di odoo in generale.

@bitit-it qualora trovassi problemi legati ai moduli di `l10n-italy`, comunque ti chiedo di aprire una issue (ancora meglio una PR) per ogni problema.
Grazie

**Comment by bitit-it** [comment]
@eLBati sicuramente i problemi sono legati ad errori miei, sono meno che esperto di python.
![screenshot_20190107_195808](https://user-images.githubusercontent.com/43685677/50788064-94213f00-12b8-11e9-8c71-9559cb48576d.jpg)

comunque il tab dettegli della fattura elettronica c'è una sezione pagamento, ma è vuota , 
ho provato a rimportare due volte la stessa fattura come vedi 
nella prima il numero fattura lo inverte con il riferimento fornitore, al posto della data di scadenza ci mette la data di emissione.

la seconda non è validata , per tanto manca il riferimento fornitore sempre al numero fattura che invece è messo al riferimento fornitore, manca la scadenza.

per l'installazione ho fatto 
pip install --pre odoo10-addon-l10n-it-fatturapa
pip install --pre odoo10-addon-l10n-it-fatturapa_in
pip install --pre odoo10-addon-l10n-it-fatturapa_put
pip install --pre odoo10-addon-l10n-it-fatturapa_pec
pip install --pre odoo10-addon-l10n-it-fatturapa_stamp

così per tutti gli altri moduli presenti nella directory 
poi ho riavviato odoo e ho aggiornato le app, installando dal'interfaccia di odoo le app di mio interesse.

ho fatto un po' di casino all'inizio creando manualmente i conti,  cancellati e rimportati quelli preinstallati.

MI suggerisci di cancellare tutto e ripartire da capo?
la procedura che ho fatto per installare i moduli ti sembra corretta?

Grazie Enrico
