### ISSUE TITLE
[10.0] [11.0] IBAN non presente nel file XML

### ISSUE THREAD

**Issue by luky0071** [OCA/l10n-italy#784]
module: l10n_it_fatturapa
version: 10.0
Riscontro qualche problema nella generazione del file XML, quando come metodo di pagamento imposto il "bonifico" ( MP05 )
sbaglio forse qualcosa o è un problema conosciuto?
**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by luky0071** [comment]
![fattura elettronica_no_iban](https://user-images.githubusercontent.com/38939370/50699874-54085500-1049-11e9-9a76-891864a8a959.PNG)

Allego foto dove il tag<IBAN> non è presente

**Comment by robyf70** [comment]
Ho appena fatto un test ed i dettagli dell'IBAN sono esportati correttamente se il conto corrente è indicato nella fattura di vendita

**Comment by luky0071** [comment]
Ti ringrazio per la risposta.
Forse mi manca qualche modulo? Ti allego la mia schermata di una classica fattura di vendita.
Se valorizzo manualmente nella tabella Account_invoice il campo "partner_bank_id", ecco che anche a me mi stampa nel file XML l'IBAN
![fattura di vendita](https://user-images.githubusercontent.com/38939370/50724860-80c57680-10f4-11e9-8740-dc0e22c254b4.jpg)

**Comment by luky0071** [comment]
Esatto, ho provato anche ad inserire a video il campo, ma non valorizza ugualmente il campo partner_bank_id sul DB.

**Comment by luky0071** [comment]
> Ho appena fatto un test ed i dettagli dell'IBAN sono esportati correttamente se il conto corrente è indicato nella fattura di vendita

@robyf70  il test di cui parli l'hai eseguito su Odoo versione 10?
Io continuo a non riuscire ad indicare il conto corrente nella fattura di vendita, saresti così gentile da postare una foto?
Grazie in anticipo

**Comment by eLBati** [comment]
Per la soluzione si potrebbe prendere spunto da https://github.com/OCA/bank-payment/tree/10.0/account_payment_partner

**Comment by luky0071** [comment]
Intanto ti ringrazio per la risposta, ho proprio installato oggi pomeriggio i moduli che mi hai appena linkato.
Devo fare qualche test.

**Comment by matteoopenf** [comment]
Buongiorno Riscontro il medesimo problema sulla versione 11

**Comment by scigghia** [comment]
è il caso di fare un modulo a parte che gestisca solo il conto bancario, in anagrafica partner e poi su fattura?

**Comment by eLBati** [comment]
@scigghia per evitare di installare `account_payment_partner` dici?

**Comment by scigghia** [comment]
@eLBati questo qui https://github.com/ApuliaSoftware/iban_invoice

**Comment by jado95** [comment]
Per me il modulo https://github.com/ApuliaSoftware/iban_invoice funziona bene e non sarebbe male averlo su OCA

**Comment by eLBati** [comment]
> (potremmo proporlo su bank-payment)

:+1: 
Ricordatevi di segnalare nel README eventuali incompatibilità con `account_payment_partner`
