### ISSUE TITLE
[8.0] Porting of l10n_it_ricevute_bancarie

### ISSUE THREAD

**Issue by scigghia** [OCA/l10n-italy#79]
here there is the work done, at the moment works these features:
- issue creation
- issue confirmation
- issue export

https://github.com/scigghia/l10n-italy/tree/8.0-riba

if anyone want to test and/or emprove, is the welcome

**Comment by scigghia** [comment]
now workflow seems to work

**Comment by eLBati** [comment]
l10n_it_ricevute_bancarie is available for 8.0
