### ISSUE TITLE
Fatturapa nota di credito

### ISSUE THREAD

**Issue by lukepower** [OCA/l10n-italy#794]
module: l10n_it_fatturapa
version: 10.0

Se si crea una nota di credito in Odoo il file XML contiene come tipo documento "TD01" invece del "TD04" che dovrebbe esserci.

**Comment by eLBati** [comment]
@lukepower non riesco a riprodurre il problema:

![nc](https://user-images.githubusercontent.com/1033131/50782309-f160c480-12a7-11e9-855f-d51e619ff261.gif)

Assicurati di avere l'ultima versione dei moduli e di indicare i passi precisi per riprodurre il problema
