### ISSUE TITLE
[10.0} FatturaPA error esportazione

### ISSUE THREAD

**Issue by lukepower** [OCA/l10n-italy#797]
When exporting an invoice I get a popup message with the following error:

Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type cannot be created from {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type: 8054701800010

I guess there is something in the invoice or the data of the company which causes this error. In Chrome's console I get this error:
----
Server application error {"message":"Odoo Server Error","code":200,"data":{"debug":"Traceback (most recent call last):\n  File \"/odoo/odoo-server/odoo/http.py\", line 642, in _handle_exception\n    return super(JsonRequest, self)._handle_exception(exception)\n  File \"/odoo/odoo-server/odoo/http.py\", line 684, in dispatch\n    result = self._call_function(**self.params)\n  File \"/odoo/odoo-server/odoo/http.py\", line 334, in _call_function\n    return checked_call(self.db, *args, **kwargs)\n  File \"/odoo/odoo-server/odoo/service/model.py\", line 101, in wrapper\n    return f(dbname, *args, **kwargs)\n  File \"/odoo/odoo-server/odoo/http.py\", line 327, in checked_call\n    result = self.endpoint(*a, **kw)\n  File \"/odoo/odoo-server/odoo/http.py\", line 942, in __call__\n    return self.method(*args, **kw)\n  File \"/odoo/odoo-server/odoo/http.py\", line 507, in response_wrap\n    response = f(*args, **kw)\n  File \"/odoo/odoo-server/addons/web/controllers/main.py\", line 899, in call_button\n    action = self._call_kw(model, method, args, {})\n  File \"/odoo/odoo-server/addons/web/controllers/main.py\", line 887, in _call_kw\n    return call_kw(request.env[model], method, args, kwargs)\n  File \"/odoo/odoo-server/odoo/api.py\", line 689, in call_kw\n    return call_kw_multi(method, model, args, kwargs)\n  File \"/odoo/odoo-server/odoo/api.py\", line 680, in call_kw_multi\n    result = method(recs, *args, **kwargs)\n  File \"/odoo/odoo-server/addons/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py\", line 814, in exportFatturaPA\n    # TODO DatiVeicoli\nUserError: (u'Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type cannot be created from {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type: 8054701800010\\t', '')\n","exception_type":"user_error","message":"Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type cannot be created from {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type: 8054701800010\t\n","name":"odoo.exceptions.UserError","arguments":["Type {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type cannot be created from {http://ivaservizi.agenziaentrate.gov.it/docs/xsd/fatture/v1.2}String35Type: 8054701800010\t",""]}}
----------

It probabily has to do something with the single lines in the invoice. I've attached a screenshot of the invoice data, maybe it helps.
![image](https://user-images.githubusercontent.com/4681903/50822489-244f9a80-1332-11e9-9521-193d78e7f4c3.png)

Thanks

**Comment by eLBati** [comment]
It seems there is an additional invalid character at the end of 8054701800010: `\t`

**Comment by lukepower** [comment]
@eLBati : But where is that character coming from? Or where shall I correct it?

**Comment by eLBati** [comment]
What is `8054701800010`?
