### ISSUE TITLE
[10]preview fattura elettronica 

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#807]
Buona sera e scusatemi ancora, ho disinstallato odoo10 completamente , cancellato tutti i file e databse re ripartito da capo., alcuni errori mi rimangono, probabilmente perchè mi manca qualcosa .

per esempio non riesco ad avere il preview della fattura elettronica.

cliccando su anteprima esce una pagina di errore. 
http://localhost:8069/fatturapa/preview/307
[ Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.]

Enrico

**Comment by bitit-it** [comment]
Vale anche per le fatture emesse non in formato elettronico nell'anteprima stampa non c'è i dati dell'azienda

Cosa ho sbagliato?
Enrico

**Comment by eLBati** [comment]
Dovresti riportare il log di odoo server relativo all'errore

**Comment by eLBati** [comment]
L'anteprima della fattura è un PDF, quindi è necessario wkhtmltopdf per generarla
