### ISSUE TITLE
[10] Controlli in fase di validazione

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#811]
Buon giorno e scusate ancora, sto continuando a testare la fatturazione elettronica so odoo10,  ripeto che non sono un esperto di odoo, paython e non sono un contabile, proprio per questo incappo in errori banali, esempio: volendo la mia azienda assoggettarsi al regime forfettario, dovrei emettere fattura senza iva;
-la prima volta ho lasciato il campo vuoto e mi ha fatto validare la fattura, dando poi un errore in fase di esportazione in fattura elettronica.
- la seconda volta ho provato con "fuori campo iva (debito)" , poi "fuori campo iva (debito) INC",
mi ha fatto validare le fatture per poi darmi errore in fase di esportazione in fattura elettronica.

Credo che i controlli che hanno generato l'errore in fase di esportazione in fattura elettronica, dovrebbero essere messi in fase di validazione, poichè una volta validate le fatture, non possono essere più cancellate, anche facendo una nota di credito per annullamento , poi la nuemrazione risulta sfalzata. 

In somma sele fatture risultanon non valide per qualche motivo è la validazione che le dovrebbe controllare, non l'esportazione in fattura elettronica.

Scusate Ancora 
Enrico

**Comment by eLBati** [comment]
Per annullare le fatture devi installare `account_cancel` e abilitare l'annullamento nel registro delle fatture clienti

**Comment by bitit-it** [comment]
come lo installo su odoo 10? nelle app non l'ho trovato

**Comment by bitit-it** [comment]
ho installato quasto modulo che dovrebbe essere la stessa cosa Cancel Journal Entries, ma non so come abilitare la funzione
