### ISSUE TITLE
[11.0] l10n_it_corrispettivi, report not working

### ISSUE THREAD

**Issue by dcorio** [OCA/l10n-italy#821]
ValueError: External ID not found in the system: report.html_container

load could not load template
Template: report.html_container

On v11 that "report" should be replaced by "web". Am I right?

**Comment by elvise** [comment]
@dcorio same here

**Comment by eLBati** [comment]
See https://github.com/OCA/l10n-italy/pull/868 for v12

**Comment by sergiocorato** [comment]
chiudo per inattività
