### ISSUE TITLE
[12.0] Tax stamp checkbox issues

### ISSUE THREAD

**Issue by primes2h** [OCA/l10n-italy#823]
- Create a new invoice
- Select  "Tax stamp" checkbox

Then:

- Add a (not stamp) new line, fill in description, press Tab.
OR
- Add a stamp new line, select a tax.

RESULT:
"Tax stamp" box gets unchecked in both cases.

**Comment by sergiocorato** [comment]
vuoi decidere a priori che sia una fattura con marca da bollo prima dell'inserimento delle righe?

**Comment by primes2h** [comment]
Nel secondo caso che ho indicato la riga bollo è già inserita.

**Comment by primes2h** [comment]
Mi 

> Nel secondo caso che ho indicato la riga bollo è già inserita.

Mi spiego meglio, nel secondo caso per poter aggiungere la riga bollo devi comunque attivare prima il flag.
Se segui i passi che ho indicato per entrambi gli scenari riesci a riprodurre il problema.

**Comment by eLBati** [comment]
@primes2h il campo `Tax Stamp` è calcolato a valle delle righe fattura, vale a dire che la modifica delle righe fattura influisce sul calcolo dell'applicabilità del bollo.

Sarebbe più chiaro se lo spostassimo "dopo" le righe fattura, ad esempio nel tab `other info`?

**Comment by primes2h** [comment]
Se l'applicabilità del bollo viene gestita in modo automatico in base alle righe fattura non capisco la necessità di avere una casella selezionabile dall'utente che può essere fuorviante.

Mi vengono in mente due soluzioni:
1) Togliere la casella di selezione. Il pulsante "Aggiungi riga bollo" compare comunque quando il calcolo delle righe ne stabilisce l'applicabilità.
2) Lasciare la casella ma impostarla come non selezionabile/modificabile dall'utente. Quando il calcolo righe stabilisce l'applicabilità del bollo la casella viene selezionata anche se non modificabile direttamente. (ma solo attraverso il ricalcolo delle righe).

La soluzione 2) probabilmente è più chiara lato utente, il fatto di visualizzare la spunta rende chiara l'apposizione del bollo virtuale.

Che ne pensate?

**Comment by eLBati** [comment]
> non capisco allora la necessità di avere una casella selezionabile dall'utente

Dopo aver compilato la fattura, indipendentemente dalla configurazione del prodotto bollo, l'utente potrebbe voler comunque applicare il bollo virtuale. Questo per gestire i casi particolari e non bloccare l'utente vincolandolo alla configurazione del prodotto bollo.

**Comment by primes2h** [comment]
> > non capisco allora la necessità di avere una casella selezionabile dall'utente
> 
> Dopo aver compilato la fattura, indipendentemente dalla configurazione del prodotto bollo, l'utente potrebbe voler comunque applicare il bollo virtuale. Questo per gestire i casi particolari e non bloccare l'utente vincolandolo alla configurazione del prodotto bollo.

Bene, mi trovi daccordo, allora però rientriamo nel problema che ho posto quando ho aperto la issue.

Mi spiego meglio:
Dopo aver installato tutti i pacchetti necessari l'utente si ritrova con un prodotto predefinito già configurato e una casella di selezione apposita nella fattura, non consapevole che il calcolo di applicabilità del bollo viene fatto in automatico in base al valore impostato.

Come giustamente dici tu, potrebbe voler comunque applicare il bollo virtuale per un caso particolare.
Il problema è che se dopo aver selezionato la casella effettua una modifica a una riga (potrebbe anche essere solo una spostamento da un campo all'altro con un tab) la casella viene deselezionata in automatico.
Imho c'è il rischio che non se ne accorga, inviando un xml privo del bollo che pensava di avere aggiunto.

**Comment by primes2h** [comment]
Penso che sia proprio il caso di spostarla. Piuttosto che metterla in un'altra scheda io la accorperei vicina al pulsante.
Sto preparando una PR a riguardo.

Tra l'altro @marcelofrare ha proposto un'idea per risolvere la deselezione della casella.

**Comment by primes2h** [comment]
Per adesso ho aperto questa PR #885.

**Comment by primes2h** [comment]
Per risolvere alla radice il problema ho pensato a questa soluzione: separare la modalità automatica da quella manuale.

Aggiungendo una casella di selezione nel prodotto predefinito abilito il calcolo automatico (True in modo predefinito). Nella fattura la casella "Imposta di bollo" è quindi visibile ma non selezionabile.
Se deseleziono la casella del calcolo automatico, entro in modalità manuale, nel prodotto non vengono visualizzati i campi di soglia minima e di imposta e nella fattura posso abilitare e disabilitare il bollo manualmente.

Ho aperto la PR #891 

Attendo commenti :-)

**Comment by primes2h** [comment]
Se non vuoi far pagare il bollo al cliente basta non aggiungere la riga bollo.

**Comment by primes2h** [comment]
Se la casella di selezione non è spuntata non ti compare neanche il pulsante "Aggiungi riga bollo".
Per quanto riguarda il movimento contabile associato non saprei risponderti, @sergiocorato 


Se hai tempo prova a testare la PR #891, ho separato la modalità automatica da quella manuale, selezionabile direttamente sul prodotto "Imposta di bollo".

**Comment by joezsweet** [comment]
Sorry, non ho ancora avuto modo di provarla

**Comment by eLBati** [comment]
@primes2h @joezsweet relativamente alle registrazioni contabili: https://trello.com/c/YO7YkWPo/41-modulo-per-gestione-bollo-virtuale

**Comment by sergiocorato** [comment]
@primes2h La scelta sul prodotto dell'addebito automatico o meno mi pare molto limitante, toglie tutta la funzionalità automatica che si voleva dare all'utente:
1. scelta addebito bollo al cliente (sapendo che la fattura lo prevede)
2. scelta di pagare il bollo (sapendo che sarebbe previsto o no)
Secondo me è utile che l'utente sappia sempre se è previsto l'addebito o no del bollo a norma di legge, poi si regola per conto proprio. Casomai si potrebbe mettere il flag e il bottone vicini, invece che in pagine diverse.

**Comment by primes2h** [comment]
> @primes2h La scelta sul prodotto dell'addebito automatico o meno mi pare molto limitante, toglie tutta la funzionalità automatica che si voleva dare all'utente:
> 
>     1. scelta addebito bollo al cliente (sapendo che la fattura lo prevede)

In che senso toglierebbe la funzionalità automatica di scelta addebito al cliente?

- modalità automatica (predefinita)
Viene calcolato automaticamente il raggiungimento della soglia sommando gli importi delle righe.
Questo abilita sia il l'immagine del bollo (che indica l'applicazione) che il pulsante di aggiunta riga bollo.

- modalità manuale
Decide l'utente quando applicare il bollo selezionando il flag nella fattura.
Questo abilita sia l'immagine del bollo (che indica l'applicazione) che il pulsante di aggiunta riga bollo.
 
>     2. scelta di pagare il bollo (sapendo che sarebbe previsto o no)

Anche qui non capisco cosa intendi.

In modalità automatica quando viene raggiunta la soglia sta all'utente decidere se pagare il bollo (non deve fare nulla) o farlo pagare al cliente (clic sul pulsante "Aggiungi riga bollo" che compare).

In modalità manuale l'utente ha ancora più libertà.
Decide lui quando applicare il bollo, facendo clic sul flag del bollo nella fattura), e se poi farlo pagare al cliente (aggiungendo una riga con un clic sul pulsante "Aggiungi riga bollo" che compare)

>        Secondo me è utile che l'utente sappia sempre se è previsto l'addebito o no del bollo a norma di legge, poi si regola per conto proprio.

Esatto, proprio per questo è tutto automatico in modo predefinito, l'unica differenza sta nel fatto che in auto-mode al posto del flag viene visualizzata l'immagine del bollo oltre al pulsante "Aggiungi riga bollo".

> Casomai si potrebbe mettere il flag e il bottone vicini, invece che in pagine diverse.

È proprio per questo che ho avuto l'idea dell'immagine del bollo che compare a fianco del pulsante.

Ho capito male quello che intendi?
