### ISSUE TITLE
Unable to send PEC via fatturapa_out - Impossibile inviare fatture elett. via pec

### ISSUE THREAD

**Issue by bullet92** [OCA/l10n-italy#832]
Hi, after installing and configuring all (REA, SDI, PEC)
i cant send e-invoice via PEC because when i send i receive an error from mail email provider:

Ciao, dopo aver installato e configurato tutti i moduli FAtturaPA con i relativi campi ( REA, SDI; PEC)
non riesco ad inviare le fatture XML via PEC perché ricevo immediatamente un errore dal mio provider mail:

> Invio Mail fallito con il server SMTP 'smtps.pec.aruba.it'. SMTPRecipientsRefused: {'sdi01@pec.fatturapa.it': (504, '5.5.2 <False-5279-fatturapa.attachment.out-2@False>: Sender address rejected: need fully-qualified address')}

This should be because odoo replace my email sender with a fake one: 'False-5279-fatturapa.attachment.out-2@False' , but this should not be allowed during the pec send

Questo accade perché odoo sostituisce il mio indirizzo di invio con uno fasullo : 'False-5279-fatturapa.attachment.out-2@False', chiaramente non riconsociuto dal mio provider  e rifiutato. Ciò non dovrebbe  avvenire durante l'invio della PEC, della quale mi fa inserire chiaramente il sender in una configurazione. 

How can I solve this issue?
Come posso risolvere questo problema?

**Comment by bullet92** [comment]
Ciao,
uso la versione 8.0, in effetti mi compare quel campo e l'ho configurato, ma viene sovrascritto.

**Comment by sergiocorato** [comment]
è stato mergiato ieri un fix #841 aggiornando va a buon fine?

**Comment by sergiocorato** [comment]
@bullet92 sono stati mergiati altri diversi fix sulla 8.0, se non riscontro segnalazioni ulteriori chiudo la issue

**Comment by sergiocorato** [comment]
chiudo per inattività
