### ISSUE TITLE
[11.0] l10n_it_corrispettivi, non funziona ricevuta di acconto

### ISSUE THREAD

**Issue by elvise** [OCA/l10n-italy#835]
Dall'ordine di vendita con cliente "usa corrispettivo" 
crea fattura>acconto>% o valore fisso> crea fattura anziché corrispettivo 

# fixes

 - [ ] v8: not available
 - [ ] v10:
 - [ ] v11: https://github.com/OCA/l10n-italy/pull/976
 - [ ] v12:

**Comment by sergiocorato** [comment]
chiudo per inattività
