### ISSUE TITLE
Tab "Fattura Elettronica" mancante in partner dopo corretta installazione

### ISSUE THREAD

**Issue by askweb2019** [OCA/l10n-italy#842]

**Comment by askweb2019** [comment]
>

**Comment by sergiocorato** [comment]
ciao @askweb2019 , il tab si vede solo se il partner ha il flag 'Soggetto a fatturazione elettronica' (oppure anche se la fattura elettronica è stata creata se passa la logica del #830 )

**Comment by askweb2019** [comment]
Perdonatemi, potete cancellare questa issues? Nei vari test ho perso le informazioni inserite. grazie
