### ISSUE TITLE
[10] importazione fattura elettronica campi errati

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#850]
due fatture differenti stesso errore; 
#NUMERO FATTURA  spostato in > RIFERIMENTO FORNITORE
#DATA SCADENZA   non presente

![screenshot_20190115_101610](https://user-images.githubusercontent.com/43685677/51171698-d991cd80-18b1-11e9-9564-981fea3ed69e.jpg)

**Comment by eLBati** [comment]
`Numero` contiene la numerazione contabile interna assegnata da odoo alla fattura.
Il numero utilizzato dal fornitore va correttamente in `riferimento fornitore`.
Per la data scadenza vale lo stesso discorso di https://github.com/OCA/l10n-italy/issues/783#issuecomment-451997308

**Comment by sergiocorato** [comment]
il campo `supplier_invoice_number` è quello che va compilato con il numero della fattura del fornitore, non il `number` nè il `reference`, a quanto mi risulta, per cui propongo #881

**Comment by bitit-it** [comment]
per me c'è un problema anche sulla data di scadenza,  nella tabella "account_invoice" non vedo traccia della data di scadenza della fattura di tiscali che mi è arrivata; campo presente in fattura nel codice xml,  ma non importato.
Enrico

**Comment by bitit-it** [comment]
@sergiocorato   però , io non ce l'ho quella prozione di codice , forse mi manca qualche cosa. 

dalla linea 829 , ho questo 
 # 2.1.1.11
        causLst = FatturaBody.DatiGenerali.DatiGeneraliDocumento.Causale
        if causLst:
            for item in causLst:
                comment += item + '\n'

        invoice_data = {
            'fiscal_document_type_id': docType_id,
            'date_invoice':
            FatturaBody.DatiGenerali.DatiGeneraliDocumento.Data,
            'reference':
            FatturaBody.DatiGenerali.DatiGeneraliDocumento.Numero,
            'sender': fatt.FatturaElettronicaHeader.SoggettoEmittente or False,
            'account_id': pay_acc_id,
            'type': invtype,
            'partner_id': partner_id,
            'currency_id': currency[0].id,
            'journal_id': purchase_journal.id,
            # 'origin': xmlData.datiOrdineAcquisto,
            'fiscal_position_id': False,
            'payment_term_id': False,
            'company_id': company.id,
            'fatturapa_attachment_in_id': fatturapa_attachment.id,
            'comment': comment
        }

**Comment by sergiocorato** [comment]
@bitit-it che versione? la PR è per la 8.0

**Comment by sergiocorato** [comment]
cmq è anche qui, vedi `'reference':
        FatturaBody.DatiGenerali.DatiGeneraliDocumento.Numero,`

**Comment by bitit-it** [comment]
Comunque se il numero fattura va sul campo reference, forse dovrebbe essere cambiata la dicitura: "riferimento fornitore "
Enrico

**Comment by eLBati** [comment]
@sergiocorato `supplier_invoice_number` non esiste sulla 10. Questa issue è etichettata `[10]`

**Comment by eLBati** [comment]
Date un'occhiata a https://github.com/OCA/l10n-italy/pull/975

**Comment by bitit-it** [comment]
fatto.. per me funziona.

Rimane poco chiaro perchè il numero della fattura del fornitore  va sul "riferimento fornitore" e il numero progressivo di riferimento del fornitore va su "Numero"; ma è un parere mio 

Enrico

**Comment by eLBati** [comment]
@sergiocorato @bitit-it infine propongo questa modifica: https://github.com/OCA/l10n-italy/issues/1536
Date un'occhiata?
