### ISSUE TITLE
l10n_it_fatturapa_out: sconti, arrotondamenti, IVA inclusa o esclusa, validazione SDI

### ISSUE THREAD

**Issue by infoitservit** [OCA/l10n-italy#853]
Prendendo una fattura ed applicando uno sconto del 100% su una riga, il nodo xml viene generato correttamente (presumo) ma la validazione non passa.

Questo il nodo xml generato per la riga:
`<Quantita>1.000</Quantita>
        <UnitaMisura>unita</UnitaMisura>
        <PrezzoUnitario>2.500</PrezzoUnitario>
        <ScontoMaggiorazione>
          <Tipo>SC</Tipo>
          <Percentuale>100.00</Percentuale>
        </ScontoMaggiorazione>
        <PrezzoTotale>0.00</PrezzoTotale>
        <AliquotaIVA>22.00</AliquotaIVA>` 

Questo è il risultato in anteprima quando si tenta di inviare la fattura in xml tramite agyo (che la scarta):
![errore](https://user-images.githubusercontent.com/3064689/51247728-4b3f4980-198e-11e9-9224-825f4ee3bea5.png)

E questo è l'errore:
Controllo corretto calcolo dell’Imposta
codice errore 00421: il valore del campo Imposta non risulta calcolato secondo le regole definite nelle specifiche tecniche

**Comment by sergiocorato** [comment]
ciao @infoitservit ho appena fatto un test sul servizio dell'Agenzia delle Entrate e il file viene validato anche con una riga con un prezzo e uno sconto al 100% e l'imposta, che è obbligatoria (v. pag. 87 delle [specifiche](https://www.agenziaentrate.gov.it/wps/file/Nsilib/Nsi/Schede/Comunicazioni/Fatture+e+corrispettivi/Fatture+e+corrispettivi+ST/ST+invio+di+fatturazione+elettronica/ST+Fatturazione+elettronica+-+Allegato+A/Allegato+A_Specifiche+tecniche+vers+1.3.pdf))
Forse l'errore che ti dà proviene da qualche altro problema

**Comment by infoitservit** [comment]
Ciao @sergiocorato , perdonami, mi dici che il test passa con "una riga **con prezzo**, sconto 100% ed **imposta**".

Il mio problema, come vedi dall'immagine sopra, è che il nodo xml esce correttamente con le info che anche tu hai testato, ma poi in fase di invio tramite Agyo sembra che il prezzo e l'imposta vengano troncati via.

Ti risulta normale/possibile?

**Comment by infoitservit** [comment]
Sto diventando scemo.
Odoo esporta il nodo xml ma poi, se analizzo il file anche con il sistema dell'agenzia delle entrate, mi restituisce il solito errore.
Qualcuno sa dirmi perchè l'xml esporta "sconto 100" e prezzo "0", nonchè "Iva 22" ma poi se vado in anteprima o faccio il controllo con il sistema dell'agenzia dell'entrate è come se questi valori diventino improvvisamente invisibili?

**Comment by sergiocorato** [comment]
mi dici dove vai a controllarlo perchè ti dia l'errore? io lo controllo da Fatture e Corrispettivi https://ivaservizi.agenziaentrate.gov.it/ser/fatturewizard/#/controllo e non dà alcun errore

**Comment by sergiocorato** [comment]
oppure girami il file che lo provo, se vuoi anche via mail sergiocorato at gmail dot com

**Comment by infoitservit** [comment]
Mail inviata.
Grazie Sergio.

**Comment by sergiocorato** [comment]
grazie, il problema che ti segnala è sul totale iva 38,60 invece di 38,62, hai abbastanza decimali nella configurazione?

**Comment by infoitservit** [comment]
![image](https://user-images.githubusercontent.com/3064689/51381871-946dd580-1b15-11e9-8ac1-e910c84f5845.png)
I prezzi sono impostati a 3 decimali...

**Comment by sergiocorato** [comment]
forse hai l'impostazione del calcolo imposta per riga invece che sul totale?

**Comment by infoitservit** [comment]
Esatto Sergio, adesso l'ho impostata sul totale e l'iva viene arrotondata a 214,16.
Provo così e ti aggiorno...

**Comment by infoitservit** [comment]
Ok, funziona!
Grazie Sergio!

Prima di chiudere (fai pure) sarei lieto di sapere se l'arrotondamento sul totale è una prassi da mantenere in linea generale o se è solo un qualcosa di cui tener conto per questa storia della fattura elettronica.

**Comment by sergiocorato** [comment]
prego :D
mi sa che a questo punto (con la fattura elettronica) sarà una cosa generale

**Comment by infoitservit** [comment]
Riapro perchè c'è un "problemone".
Come Odoo stesso consiglia, qualora si usi anche il POS con prezzi iva inclusa, è sconsigliato utilizzare l'arrotondamento sul totale.
Ho infatti potuto appurare che in tali condizioni (arrotondamento sul totale) e utilizzo del POS con prezzi iva inclusa, il totale dello scontrino è sbagliato (basta inserire 5 righe con prezzo 5€ iva inclusa e noterete come il totale finale è 20,01€).

Come posso risolvere? Ho visto che nel repository ufficiale di Odoo questo problema col POS è stato segnalato più di una volta ma non ci sono stati interventi particolari.
Qualcuno è in grado di risolvere la cosa dietro adeguato finanziamento?

**Comment by eLBati** [comment]
> Ho infatti potuto appurare che in tali condizioni (arrotondamento sul totale) e utilizzo del POS con prezzi iva inclusa, il totale dello scontrino è sbagliato (basta inserire 5 righe con prezzo 5€ iva inclusa e noterete come il totale finale è 20,01€).

Se fai lo scontrino fiscale però non fai la fattura.
Quindi ti riferisci ai casi in cui, invece dello scontrino, fai la fattura?
Ed in quei casi la fattura viene scartata dal SDI?

**Comment by eLBati** [comment]
Ah però l'arrotondamento per riga è globale in odoo, quindi se lo imposti per far funzionare il POS, poi rischi di avere fatture scartate.

Allora una soluzione potrebbe essere permettere di configurare un tipo di arrotondamento solo per il POS e un altro per tutto il resto

**Comment by infoitservit** [comment]
Si Lorenzo, il problema è che per far "quadrare" la fattura e fare in modo che non venga scartata, devo settare l'arrotondamento sul totale, ma questo poi implica il problema nel POS che ho descritto sopra.

Rimane dunque da capire se è il caso di settare l'arrotodondamento "per riga", rispettando le indicazioni di Odoo quando si usano prezzi iva inclusa nel POS, ma nel contempo aggiustare (ammesso sia possibile) gli arrotondamenti in fase di emissione della fattura elettronica.

**Comment by infoitservit** [comment]
> Ah però l'arrotondamento per riga è globale in odoo, quindi se lo imposti per far funzionare il POS, poi rischi di avere fatture scartate.
> 
> Allora una soluzione potrebbe essere permettere di configurare un tipo di arrotondamento solo per il POS e un altro per tutto il resto

Esattamente. Anche perchè non di rado capita di dover gestire i prezzi e l'iva in un modo a livello B2C e in un altro a livello B2B

**Comment by elvise** [comment]
> Ah però l'arrotondamento per riga è globale in odoo, quindi se lo imposti per far funzionare il POS, poi rischi di avere fatture scartate.
> 
> Allora una soluzione potrebbe essere permettere di configurare un tipo di arrotondamento solo per il POS e un altro per tutto il resto

Ciao Lorenzo, ci sono moltissime tipologie di attività che usano prezzi compresi iva e fanno fatture al consumatore, se si prende la strada di una configurazione separata per gli arrotondamenti del pos ci portiamo dietro comunque il problema (almeno per quelle tipologie di attività).

**Comment by elvise** [comment]
> forse hai l'impostazione del calcolo imposta per riga invece che sul totale?

Ciao @sergiocorato dove riesco a configurare il calcolo dell'imposta per totale non per riga?

**Comment by eLBati** [comment]
Qualche informazione aggiuntiva: https://www.odoo-italia.org/index.php/kunena/8-contabilita-e-finanza/15015-12-oca-arrotondamenti-e-fattura?start=6#32843

**Comment by GSLabIt** [comment]
@eLBati il sito è giù?
