### ISSUE TITLE
[10.0] problema ritorno errato fattura 

### ISSUE THREAD

**Issue by OmniaGit** [OCA/l10n-italy#866]
Dopo l'invio della fattura allo sdi abbiamo ricevuto un codice di errore per un problema di arrotondamento.
a questo punto il sistema non permette di procedere se non cancellando il file xml connesso alla fattura.
sarebbe opportuno poterlo archiviare e scollegare dalla fattura per permettere una re emissione mantenendo lo storico

ciao
Matteo

**Comment by robyf70** [comment]
Concordo completamente con te! Manca un metodo comodo per rigenerare lo stesso file dopo aver applicato i cambiamenti ad una fattura. Diventa complicato rigenerare il file xml che deve avere lo stesso numero di sequenza altrimenti l'SDI dice che la fattura è duplicata.

Una domanda, riguardo al problema di arrotondamento stai usando il modulo account_invoice_triple_discount? hai l'arrotondamento sul totale o per riga?

**Comment by primes2h** [comment]
Il giorno ven 18 gen 2019 alle ore 17:11 Roberto Fichera <
notifications@github.com> ha scritto:

> Concordo completamente con te! Manca un metodo comodo per rigenerare lo
> stesso file dopo aver applicato i cambiamenti ad una fattura. Diventa
> complicato rigenerare il file xml che deve avere lo stesso numero di
> sequenza altrimenti l'SDI dice che la fattura è duplicata.
>
Per mantenere lo stesso numero dell'xml basterebbe impostare
l'implementazione sequenza del tipo "senza spazi vuoti" invece di "normale"
nella configurazione della sequenza "Electronic Invoices". [1]

In alternativa potresti modificare il numero di sequenza successivo, sempre
nella sequenza "Electronic Invoices", e impostarlo pari al numero dell'xml
che hai appena eliminato.

[1] se non ci sono controindicazioni magari potrebbe essere l'impostazione
di default

**Comment by robyf70** [comment]
Non credo funzionerebbe perchè nel frattempo potrei avere altri invii  e questo farebbe avanzare la numerazione. La soluzione migliore è tenere il **name** (nome allegato) così come **datas_fname** (nome file) e se lo stato è **Errore di Trasmission**e, **Rifiutato** o **Not Delivered** allora consentire di rigenerare l'xml dall'account.invoice

**Comment by eLBati** [comment]
> Diventa complicato rigenerare il file xml che deve avere lo stesso numero di sequenza altrimenti l'SDI dice che la fattura è duplicata

@robyf70 questo non mi risulta. Il numero della fattura deve essere lo stesso, non il nome del file.

**Comment by eLBati** [comment]
> a questo punto il sistema non permette di procedere se non cancellando il file xml connesso alla fattura.
sarebbe opportuno poterlo archiviare e scollegare dalla fattura per permettere una re emissione mantenendo lo storico

Proposta di implementazione:
quando l'esportazione è nello stato "scartata", l'utente va nella fattura e lancia nuovamente l'esportazione. A quel punto il sistema sovrascrive il contenuto del file binario con il nuovo XML generato.
L'utente riporta l'esportazione a "pronta per l'invio" e invia nuovamente.
In questo modo il precedente invio resta allegato nel chatter dell'esportazione.

**Comment by sergiocorato** [comment]
:+1:

**Comment by sergiocorato** [comment]
chiudo per inattività
