### ISSUE TITLE
controllo di sequenzialità nella numerazione delle fatture passive

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#87]
Dalla documentazione ho capito che il modulo "Account Invoice entry Date" dovrebbe consentire di inserire la data della fattura e di rispettare la progressività nella numerazione dei registri IVA.
ho purtroppo notato le seguenti anomalie (forse ho trascurato qualche settaggio):
1) è possibile inserire la data del documento nel futuro,
2) la data di registrazione (che dovrebbe avere valenza contabile) è automaticamente inserita dal sistema pari a quella del documento,
3) la sequenzialità tra data di registrazione e numero di documento non è controllata, i.e. nessun messaggio di errore che impedisca la registrazione viene emesso dal sistema.

Sarebbe auspicabile che la data di registrazione sia impostabile manualmente e che sia non successiva all'ultima data inserita.

Grazie
claudio candito

**Comment by dcorio** [comment]
Penso ti serva questo modulo:
https://github.com/OCA/l10n-italy/tree/7.0/account_invoice_sequential_dates
ma non è ancora stato portato alla 8 mi pare.

**Comment by ccandito** [comment]
grazie
ho trovato nella versione standard il modulo "entries sequence numbering", ma non so se risponde a pieno alle esigenze italiane
appena possibile ho intenzione di testarlo
claudio
