### ISSUE TITLE
Fattura PA Out - Sconti multipli

### ISSUE THREAD

**Issue by OpenCode** [OCA/l10n-italy#896]
Apro una discussione in riferimento a questo blocco di codice:

https://github.com/OCA/l10n-italy/blob/12.0/l10n_it_fatturapa_out/wizard/wizard_export_fatturapa.py#L624

Ci sono moduli OCA che permettono di avere sconti multipli. Questo ovviamente si scontra con la generazione dell'XML poiché viene preso in considerazione solo uno sconto. Propongo di far passare la generazione del blocco ScontoMaggiorazione attraverso una funzione che può così essere ereditata da moduli aggiuntivi ed estesa con le dovute funzionalità.

**Comment by SimoRubi** [comment]
Ciao, per gli sconti tripli (di account_invoice_triple_discount) ho fatto https://github.com/OCA/l10n-italy/pull/884.
Non estrae solo la parte dello sconto ma tutta la generazione di DettaglioLinea, in modo che poi si possa fare override (cosa che poi faccio nel modulo della PR) per modificare un qualsiasi campo.

**Comment by OpenCode** [comment]
Ciao @SimoRubi,

la tua PR però non viene contro l'esigenza indicata in questa issue poiché la gestione dello sconto è sempre interna alla funziona e non è facilmente ereditabile

**Comment by SimoRubi** [comment]
Vero, non ho creato un metodo apposta per settare lo sconto, ma non l'ho fatto perché mi sembra un'esigenza troppo specifica. 
Ad esempio, perché allora non creare un metodo per ogni campo?

Il nuovo metodo `setDettaglioLinea` mi sembra abbastanza generico e permette di editare ogni riga subito dopo che è stata creata (ritornare la linea appena creata sarebbe stato meglio, ma ho preferito attenermi a come sono stati costruiti gli altri metodi del wizard). 
Per modificare lo sconto si può fare come in https://github.com/OCA/l10n-italy/pull/884/files#diff-102cc2a8f11e77cdfb4a8110c20eae74R14

**Comment by OpenCode** [comment]
Se non si vuole creare una funzione specifica allora bisogna almeno restituire l'oggetto appena creato in modo che lo stesso sia poi manipolabile. In un sistema personalizzabile questo tipo di accortezze ci permettono di operare meglio.

Fosse per me farei pure una funzione per ogni campo per raggiungere il massimo della modularità :)

**Comment by SimoRubi** [comment]
ok @OpenCode allora se vuoi puoi fare review alla mia PR per restituire l'oggetto appena creato dal nuovo metodo, poi vedremo se la modifica viene approvata o no.

**Comment by eLBati** [comment]
@OpenCode @SimoRubi questa possiamo chiuderla come duplicata della https://github.com/OCA/l10n-italy/issues/1127 ?

**Comment by SimoRubi** [comment]
Per me sì ma l'ultima parola spetta a @OpenCode in quanto OP

**Comment by OpenCode** [comment]
@eLBati Sì, chiudo. Grazie a tutti.
