### ISSUE TITLE
Consumo a commessa (Project) in Odoo V8.0

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#90]
non trovo il modo di effettuare un consumo di materiale su progetto.
ho letto dell'esistenza del modulo "Project Task Materials" che farebbe al caso, ma non l'ho trovato in V8.0. 
La soluzione estrema e non integrata sarebbe quella di registrare un movimento interno di magazzino su una location virtuale e una registrazione di partita singola in contabilità analitica.
Avete avuto modo di affrontare un problema del genere?
grazie
claudio

**Comment by dcorio** [comment]
chiudo la issue siccome è un post da forum:
http://www.odoo-italia.org/index.php/kunena/home
