### ISSUE TITLE
[10.0] Errore "riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI"

### ISSUE THREAD

**Issue by protontrigg3r** [OCA/l10n-italy#902]
Scaricando una particolare fattura elettronica d'acquisto, il server in ingresso smette di funzionare (necessita di un nuovo "_Test & Confirm_") e segnala in **_Last error message_**:

`xmlns:pfx6: 'http://www.tibco.com/ns/no_namespace_schema_location/NBS_FAT_WRITER/Schemas/XSD riepilogo_fattura_ordinaria_v1.2_mod.xsd' is not a valid URI, line 2, column 378`

A volte viene creato il relativo record in _Incoming E-bill Files_ ma senza la relativa fattura allegata (in sostanza sembra che legga correttamente il corpo della mail e si incarti poi con l'allegato).

La PEC in questione sembra uguale alle altre. Cosa posso controllare?

**Comment by sergiocorato** [comment]
chiudo per inattività
