### ISSUE TITLE
best practice per il going live

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#91]
dopo aver configurato l'ambiente di test e completato i test di accettazione utente, quale è la procedura suggerita per andare live. Mi vengono in mente:
un tool per il trasporto della configurazione?
o per l'estrazione dei db senza dati applicativi?
la possibilità di cancellare da una copia dei db i dati applicativi (transazionali e anagrafici)?
grazie
claudio

**Comment by dcorio** [comment]
Ciao, questo tipo di questioni dovrebbero essere poste sul forum:
http://www.odoo-italia.org/index.php/kunena/home

chiudo la issue
