### ISSUE TITLE
DDT Prezzi

### ISSUE THREAD

**Issue by Zephyria77** [OCA/l10n-italy#913]
Il modulo DDT riporta tra le funzioni:

È possibile aggiungere righe ad un DDT esistente usando il tab 'Dettaglio'. Le righe possono essere descrittive o collegate a prodotti. Le righe collegate ad un prodotto creeranno anche i movimenti di magazzino.

Creo direttamente il DDT senza passare dagli ordini, aggiungo righe descrittive insieme a righe collegate a prodotti (per poi scaricare il magazzino), inserisco il prezzo per ogni singola riga, metto nel pacco e fin qui tutto bene.
Quando vado a cliccare "pacco completato" quindi vado a fare i movimenti, mi ritrovo tutte le righe a zero (tranne quelle descrittive) e disordinate rispetto alla sequenza data in precedenza. Sembra che il pulsante action_done annulli il campo price_unit e l'ordinamento fornito in precedenza.

**Comment by eLBati** [comment]
@Zephyria77 su che versione?
Potrebbe essere un problema risolto da questa modifica
https://github.com/OCA/l10n-italy/pull/836/commits/7444cb72b8554fe0d2d381d1e6b7ab22aeb51522#diff-331591f80034789c070b760dadc2ee21R206

**Comment by Zephyria77** [comment]
@eLBati  ho avuto modo di notare lo stesso comportamento sia sulla 10.0 che sulla 11.0

**Comment by eLBati** [comment]
Probabilmente allora bisogna applicare la modifica che dicevo anche su quelle versioni

**Comment by DavideSavoneEVE** [comment]
Ho notato che su ddt prende i valori dall' ordine di vendita e listino associato. Nel caso non si passi da quello ci si trova con prezzi a 0 se non sbaglio

**Comment by Zephyria77** [comment]
Proprio così, solo dopo aver completato il pacco, porta i valori  a 0

**Comment by sergiocorato** [comment]
chiudo per inattività
