### ISSUE TITLE
errore in Base Location Provinces Import

### ISSUE THREAD

**Issue by ccandito** [OCA/l10n-italy#92]
propedeutico all'installazione del modulo dell'italianizzazione "Base Location Provinces Import" è necessario installare il modulo "base_location_geonames_import".
nell'installazione di quest'ultimo il seguente errore accade:
Unable to install module "base_location_geonames_import" because an external dependency is not met: No module named unicodecsv.
grazie
claudio

**Comment by dcorio** [comment]
Non è un errore, ti sta dicendo che devi installare tale libreria:
https://pypi.python.org/pypi/unicodecsv/0.9.4

pip install unicodecsv o simile risolverà il tuo problema

**Comment by ginomazzoni** [comment]
Io ho installato tutte le dipendenze necessarie, vedo la app ma senza il bottone per la installazione e cliccandoci sopra nelle informazioni tecniche mi di uninstallable. Dove sbaglio? Grazie

**Comment by eLBati** [comment]
@ginomazzoni che versione di odoo?
