### ISSUE TITLE
Intermediario con codice fiscale di San Marino non rispetta il pattern FATTURAPA_IN_REGEX

### ISSUE THREAD

**Issue by sherpya** [OCA/l10n-italy#922]
mi è arrivata una fattura di un intermediario di San Marino (è possibile?)

dovrebbe essere questo https://shop.passepartout.net/Acquisto/SceltaProdotto

il nomefile diventa `SM03473_XXXXX.xml`

ma il pattern `FATTURAPA_IN_REGEX` di aspetta 11 o 16 caratteri, qualcuno ha informazioni a riguardo?

- [x] v. 8: #1130
- [x] v. 10: #1133 
- [ ] v. 11: https://github.com/OCA/l10n-italy/pull/1179
- [x] v. 12: https://github.com/OCA/l10n-italy/pull/1178

**Comment by eLBati** [comment]
@sherpya prova a scrivere in mailing list
https://github.com/OCA/l10n-italy#contribuire

**Comment by sherpya** [comment]
a parte che secondo me questi hanno cannato perché l'identificativo è quello del mittente da usare e non l'intermediario, ma la specifica comunque dice di accettarlo

https://www.fatturapa.gov.it/export/fatturazione/it/c-11.htm

il Codice Paese va espresso secondo lo standard ISO 3166-1 alpha-2 code,
l’Identificativo univoco del Trasmittente, sia esso persona fisica o soggetto giuridico, è rappresentato dal suo identificativo fiscale (codice fiscale nel caso di soggetto trasmittente residente in Italia, identificativo proprio del Paese di appartenenza nel caso di soggetto trasmittente residente all’estero). La lunghezza di questo identificativo è di:

    11 caratteri (minimo) e 16 caratteri (massimo) nel caso di codice paese IT,
    2 caratteri (minimo) e 28 caratteri (massimo) altrimenti,

**Comment by sherpya** [comment]
a quanto pare la specifica è IT + 11,16 (anche se dice da 11 a 16) e per gli altri due lettere più da 2 28, appena posso faccio una PR

il nome file è dato dal mittente, in questo caso l'intermediario, ma potrebbe arrivare una fattura da un'entità non IT

**Comment by sherpya** [comment]
tipo una cosa del genere?
```python
FATTURAPA_IN_REGEX = r'''^(IT[A-Z0-9]{11,16}|       # IT + PIVA (11 caratteri) o CF (16 caratteri)
                         [A-Z]{2}[A-Z0-9]{2,28})    # XX + da 2 a 28 caratteri
                         _[A-Z0-9]{,5}              # Progressivo univoco del file: max 5 caratteri alpha'''

re_pattach = re.compile(FATTURAPA_IN_REGEX + r'\.(xml|zip)', re.I | re.X)
re_resp = re.compile(FATTURAPA_IN_REGEX + r'_MT_[A-Z0-9]{,3}', re.I)
```

putroppo matcha anche IT e 2-28, ma volendo fare questo check da regex divento scemo

**Comment by sherpya** [comment]
me ne stanno arrivando altre, io farei {2,28} invece di {11,16} credo che possa bastare alla fine, a proposito perché la regex è compilata dentro la funzione e non fuori?

**Comment by eLBati** [comment]
> perché la regex è compilata dentro la funzione e non fuori?

Penso possa essere messa fuori

**Comment by sergiocorato** [comment]
ho rilevato lo stesso problema, per il momento farei un regex con la specifica di San Marino

**Comment by sergiocorato** [comment]
- [ ] v. 8: #1130
- [ ] v. 10
- [ ] v. 11
- [ ] v. 12

**Comment by sergiocorato** [comment]
@sherpya @eLBati ho caricato la soluzione, ne ho ricevute anche da SE (forse Serbia?), ho anche dovuto ripristinare quelle ignorate finora :cry:

**Comment by sherpya** [comment]
@sergiocorato {2,28} ?

**Comment by sergiocorato** [comment]
> @sergiocorato {2,28} ?

@sherpya si per le non IT, l'avevi scritto sopra no?

**Comment by sergiocorato** [comment]
> > perché la regex è compilata dentro la funzione e non fuori?
> 
> Penso possa essere messa fuori

ho spostato fuori la regex

**Comment by eLBati** [comment]
@OCA/local-italy-developers 
PR per v12: https://github.com/OCA/l10n-italy/pull/1178
Qualcuno intende portare la correzione alla 11?

**Comment by labaggio** [comment]
> @OCA/local-italy-developers
> PR per v12: #1178
> Qualcuno intende portare la correzione alla 11?

posso farcela! parto da quella della 12.

**Comment by eLBati** [comment]
@labaggio grazie.

PS: hai voglia di iscriverti alla mailing list `sviluppo` su https://www.odoo-italia.org/groups ?
Così magari aboliamo il gruppo `@OCA/local-italy-developers` che penso abbia i problemi che ho scritto qua https://www.odoo-italia.org/groups/sviluppo-17/sviluppo-1187

**Comment by labaggio** [comment]
> @labaggio grazie.
> 
> PS: hai voglia di iscriverti alla mailing list `sviluppo` su https://www.odoo-italia.org/groups ?
> Così magari aboliamo il gruppo `@OCA/local-italy-developers` che penso abbia i problemi che ho scritto qua https://www.odoo-italia.org/groups/sviluppo-17/sviluppo-1187

Fatto, me l'ero persa..

**Comment by glauco70** [comment]
> > @OCA/local-italy-developers
> > PR per v12: #1178
> > Qualcuno intende portare la correzione alla 11?
> 
> posso farcela! parto da quella della 12.

Creata PR per la 11 : #1179

**Comment by eLBati** [comment]
Attenzione: https://github.com/OCA/l10n-italy/issues/1189
