### ISSUE TITLE
Fattura PA: notifica sdi non parsata se l'errore è nel nome del file

### ISSUE THREAD

**Issue by sherpya** [OCA/l10n-italy#923]
Un cliente ha inserito per sbaglio un tab alla fine del campo partita iva, l'email di notifica è arrivata con un allegato il cui nome non matcha il pattern `RESPONSE_MAIL_REGEX`, quindi viene ignorata,

si potrebbe utilizzare un pattern un po' più lascivo e magari estrarre il message type con l'espressione regolare, ad esempio roba_(NS)_roba etc

**Comment by sherpya** [comment]
il problema non è nella ricezione della notifica, ma odoo non avrebbe dovuto generare una fattura con un nome file con il tab, farò altre indagini

**Comment by sergiocorato** [comment]
chiudo per inattività
