### ISSUE TITLE
[10.0] Download fatture elettroniche di massa

### ISSUE THREAD

**Issue by luky0071** [OCA/l10n-italy#941]
module: l10n_it_fatturapa
version: 10.0

Salve a tutti, noto che non è possibile esportare N. xml già creati, come da immagine allegata.

Sono io che sbaglio qualcosa oppure non è stata sviluppata questa possibilità?

![export massivo fe](https://user-images.githubusercontent.com/38939370/52216858-8222c400-2897-11e9-987f-b3e43c417931.jpg)

**Comment by eLBati** [comment]
Al momento la funzionalità non è disponibile, ma è in programma.

**Comment by sergiocorato** [comment]
vedi #948 sulla 8.0

**Comment by sergiocorato** [comment]
#949 per la 10.0

**Comment by matteotrubini** [comment]
E' stato previsto di implementare anche l'import multiplo via zip per le fatture fornitori?

**Comment by sergiocorato** [comment]
prego :D

**Comment by sergiocorato** [comment]
> E' stato previsto di implementare anche l'import multiplo via zip per le fatture fornitori?

la pr fa entrambe le tipologie

**Comment by luky0071** [comment]
Vorrei giusto segnalare che se a fronte di più fatture dello stesso cliente, che mi vengono raggruppate in un'unico file XML, quando si esegue l'esportazione di massa delle fatture elettroniche, si verifica il download ripetitivo delle fatture che fanno riferimento allo stesso XML. ( per spiegarmi meglio, allego immagine)
In realtà non costituisce un problema vero e proprio, poichè in fase di estrazione delle fatture dal file zip, i duplicati vengono rimossi.
![file zip con duplicati](https://user-images.githubusercontent.com/38939370/52348529-d313f300-2a24-11e9-8120-66c6d77dc0f5.jpg)

**Comment by luky0071** [comment]
Vorrei giusto segnalare che se a fronte di più fatture dello stesso cliente, che mi vengono raggruppate in un'unico file XML, quando si esegue l'esportazione di massa delle fatture elettroniche, si verifica il download ripetitivo delle fatture che fanno riferimento allo stesso XML. ( per spiegarmi meglio, allego immagine)
In realtà non costituisce un problema vero e proprio, poichè in fase di estrazione delle fatture dal file zip, i duplicati vengono rimossi.
![file zip con duplicati](https://user-images.githubusercontent.com/38939370/52348729-51709500-2a25-11e9-94d6-89d2f519b717.jpg)

**Comment by matteotrubini** [comment]
> la pr fa entrambe le tipologie

@sergiocorato perdonami, ma la PR non copre solo il download degli allegati? Io intendevo di uppare in un colpo solo più fatture fornitori tramite zip

**Comment by sergiocorato** [comment]
@matteotrubini si il download di ft. acquisto e vendita, per l'upload uso il sistema della pec

**Comment by matteotrubini** [comment]
A colpo d'occhio la strada più lineare mi sembrerebbe quella di estrarre il grosso della logica questo metodo
https://github.com/OCA/l10n-italy/blob/e715051020f70a63e0ef7af8bc4c738a0ceb0079/l10n_it_fatturapa_pec/models/mail_thread.py#L174
spostandolo nel `l10n_it_fatturapa_in` e poi aggiungere la view necessaria a fare l'upload dello zip (che non serve salvare fra gli allegati).

Corretto?

**Comment by sergiocorato** [comment]
chiudo per inattività
