### ISSUE TITLE
[10.0] Generazione file xml di massa

### ISSUE THREAD

**Issue by luky0071** [OCA/l10n-italy#942]
module: l10n_it_fatturapa
version: 10.0
Riscontro qualche problema nella generazione del file XML, quando seleziono più fatture contemporaneamente.
Come da immagine allegata, se selezione ad esempio queste 3 fatture, il file XML che si genera, non rispetta il numero della fattura.
Avete qualche suggerimento per far si che la fattura A corrisponda all'xml A e la fattura B corrisponda all'xml B e così via?

![export massivo fe2](https://user-images.githubusercontent.com/38939370/52217814-8354f080-2899-11e9-9aa5-cce854ea9a11.jpg)

**Comment by sergiocorato** [comment]
la cosa non ha senso, sono dei numeratori slegati, inoltre se ci fossero 2 fatture per lo stesso partner ci sarebbe 1 solo file

**Comment by eLBati** [comment]
Confermo che la numerazione del file è indipendente da quella della fattura
