### ISSUE TITLE
[10] Stampa fatture privati manca il codice fiscale

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#954]
Nella stampa delle fatture ai privati manca il codice fiscale del cliente  e del prestatore.

Enrico

**Comment by eLBati** [comment]
@bitit-it Puoi descrivere i passi per riprodurre il problema su un nuovo DB?

**Comment by bitit-it** [comment]
Semplice, inserisci un cliente privato, quindi solo condice fiscale, prepari la fattura, la salvi, la validi e fai la stampa, il pdf che viene fuori, non ha  ne il codice fiscale del cliente sotto i dati del cliente, ne il codice fiscale del fornitore a pie di pagina dove ci sono i dati fiscali del fornitore. 
Ho anche  provato con un sistema dove non c'erano clienti inseriti,  quello con cui ho testato l'inserimento del codice fiscale dell'azienda per intenderci; quindi cliente unico, nella stampa non c'è il codice fiscale del cliente.

Enrico

**Comment by eLBati** [comment]
Per la stampa del codice fiscale in fattura c'è https://github.com/OCA/l10n-italy/tree/10.0/l10n_it_fiscalcode_invoice

**Comment by bitit-it** [comment]
mi risulta installato, devo forse configurare qualcosa?
Enrico

**Comment by OpenCode** [comment]
@bitit-it assicuati che sia installato il modulo l10n_it_fiscalcode_invoice oltre a l10n_it_fiscalcode. Chiudo poiché è un errore di mancata configurazione e non un bug.

**Comment by bitit-it** [comment]
> @bitit-it Assicurati, per cortesia, che sia installato il modulo l10n_it_fiscalcode_invoice oltre a l10n_it_fiscalcode. Chiudo poiché è un errore di mancata configurazione e non un bug.

ce li ho entrambi ma non esce fuori il codice fiscale del cliente nella stampa della fattura
