### ISSUE TITLE
Cannot Add A related Document DDT without lines

### ISSUE THREAD

**Issue by DavideSavoneEVE** [OCA/l10n-italy#956]
I 've fixed the issue because as the 1.2 document fatturapa said we could have a document with 0 lines 

l10n_it_fatturapa_out/views/account_view.xml
add: 

<page string="DDT Vuoti" attrs="{'invisible': [('electronic_invoice_subjected', '=', False)]}">
                    <group>
                        <field name="ftpa_related_ddts" nolabel="1" >
                            <tree string="DDTs">
                                <field name="name"></field>
                                <field name="date"></field>
                            </tree>
                            <form string="Attachments">
                                <group>
                                    <group>
                                        <field name="name"></field>
                                        <field name="date"></field>
                                    </group>
                                </group>
                            </form>
                        </field>
                    </group>
                </page>

and in the wizard 
l10n_it_fatturapa_out_ddt/wizard/wizard_export_fatturapa.py
 include_ddt_data = fields.Selection([
        ('dati_ddt', 'Includi Dati DDT'),
        ('dati_trasporto', 'Includi Dati Trasporto'),
        ('descrizione_ddt','Includi DDT - Descrizione')
        ],
        string="Dati DDT",
        help='Includi Dati DDT: Blocco da valorizzare nei casi di fattura '
             '"differita" per '
             'indicare il documento con cui e\' stato consegnato il bene\n'
             'Includi Dati Trasporto: Blocco valorizzabile nei casi di '
             'fattura "accompagnatoria" per '
             'inserire informazioni relative al trasporto'
    )

    def setDatiDDT(self, invoice, body):
        res = super(WizardExportFatturapa, self).setDatiDDT(
            invoice, body)
        if self.include_ddt_data == 'descrizione_ddt':
            for ddt in invoice.ftpa_related_ddts:
                DatiDDT = DatiDDTType(
                    NumeroDDT=ddt.name,
                    DataDDT=ddt.date
                )
                body.DatiGenerali.DatiDDT.append(DatiDDT)

**Comment by eLBati** [comment]
@DavideSavoneEVE riesci a creare una pull request?

**Comment by DavideSavoneEVE** [comment]
si :)

**Comment by sergiocorato** [comment]
chiudo per inattività
