### ISSUE TITLE
Fattura PA V10 IPA code

### ISSUE THREAD

**Issue by falinwasales** [OCA/l10n-italy#960]
Hi, I don't speak Italian and don't know the Italian tax system so setting up Fattura PA is complicated.

When I try to export an invoice, I am getting an error "IPA code not set on partner form". However, the client has a codice del destinario, and is not a public adminstration, so I don't see why he needs an IPA code.

Would be really grateful for some help if somebody could reach out to me :  jane.pedersen@falinwa.com

Many thanks.

**Comment by eLBati** [comment]
@falinwasales are you using the latest version of OCA/l10n-italy modules? The message `IPA code not set on partner form` is not present

**Comment by falinwasales** [comment]
Thanks for this eLBati, I will check and let you know.

**Comment by sergiocorato** [comment]
chiudo per inattività
