### ISSUE TITLE
[10] fatture ricevute due volte, file non cancellabile 

### ISSUE THREAD

**Issue by bitit-it** [OCA/l10n-italy#971]
ho ricevuto due volte 3 fatture uguali,  la prima volta regolarmente importate, la seconda volta rimangono  in file fatture ingresso , se provo ad elminarle  ho il seguente errore : 

> The operation cannot be completed, probably due to the following:
> - deletion: you may be trying to delete a record while other records still reference it
> - creation/update: a mandatory field is not correctly set
> 
> [object with reference: Invoice - account.invoice] 

se provo ad importarle ho il seguente errore: 

> Odoo Attenzione - Attenzione
> Il file IT01879020517_kaIRY.xml.p7m è già collegato alle fatture. 

dal menu unisci a fatture fornitori presenti   la tendina rimane vuota.

Enrico

**Comment by eLBati** [comment]
@bitit-it cioè hai ricevuto da SDI 3 fatture uguali?

**Comment by bitit-it** [comment]
tre fatture differenti due volte ciascuna.
non so cosà è successo .

Enrico

**Comment by sergiocorato** [comment]
chiudo per inattività
