### ISSUE TITLE
l10n_it_fatturapa: incongruenze in _compute_ftpa_preview_link tra 10.0 e 11.0

### ISSUE THREAD

**Issue by sherpya** [OCA/l10n-italy#973]
facendo il porting di asn1crypto mi sono accorto che nel file `l10n_it_fatturapa/models/ir_attachment.py`

nella 10:
```python
    @api.multi
    def _compute_ftpa_preview_link(self):
        for att in self:
            att.ftpa_preview_link = '/fatturapa/preview/%s' % self.id
```

mentre nella 11:
```python
    @api.multi
    def _compute_ftpa_preview_link(self):
        for att in self:
            att.ftpa_preview_link = '/fatturapa/preview/%s' % att.id
```

self.id vs att.id, non dovrebbe essere att.id anche sulla 10.0?

**Comment by eLBati** [comment]
> non dovrebbe essere att.id anche sulla 10.0?

Sì. Pare che questa correzione https://github.com/OCA/l10n-italy/commit/1295057c2c09b08ea40dc4b211da6c6373c93c6d non sia stata portata a 10.0

**Comment by sherpya** [comment]
vedo che è stata sistemata, chiudo
