### ISSUE TITLE
Errore Reverse charge in multicurrency 

### ISSUE THREAD

**Issue by jackjack82** [OCA/l10n-italy#993]
I create a purchase invoice in Reverse Charge in a currency different from the main company currency, using the "self-invoice" method. The sale invoice created automatically is properly created, but the account move that offsets the two invoices has not Exchange rate properly computed.

I am working on this now and soon make a PR.

 - [ ] v8
 - [x] v10: https://github.com/OCA/l10n-italy/pull/1003
 - [ ] v11
 - [x] v12: https://github.com/OCA/l10n-italy/pull/1203

**Comment by primes2h** [comment]
Si verifica anche nelle altre versioni?

**Comment by eLBati** [comment]
Sulla 12 le modifiche dovrebbero essere state incluse nella migrazione https://github.com/OCA/l10n-italy/pull/1203

**Comment by sergiocorato** [comment]
chiudo per inattività
