### ISSUE TITLE
[11.0] l10n_it_corrispettivi, arrivando da SO stampa fattura anziché ricevuta

### ISSUE THREAD

**Issue by GSLabIt** [OCA/l10n-italy#994]
Salve,

ho riscontrato un problema sulla stampa delle ricevute se si arriva da SO; stampa fattura anziché ricevuta. Video: http://recordit.co/VDpHia4ThK.

Oltre a questo, magari, sarebbe opportuno fare in modo che venga modificato il nome dei pulsanti; per l'utente potrebbe risultare forviante. Screenshot:

<img width="1252" alt="schermata 2019-02-11 alle 10 55 14" src="https://user-images.githubusercontent.com/11652845/52556808-e391e800-2ded-11e9-887b-8767e4c3a441.png">

wizard:
<img width="959" alt="schermata 2019-02-11 alle 10 55 58" src="https://user-images.githubusercontent.com/11652845/52556854-03c1a700-2dee-11e9-9cd3-98847739abc3.png">

Invoice arrivando da SO:
<img width="1250" alt="schermata 2019-02-11 alle 10 56 15" src="https://user-images.githubusercontent.com/11652845/52556882-1f2cb200-2dee-11e9-95c5-f4123bd1cf27.png">

**Comment by monen17** [comment]
Grazie @GSLabIt della segnalazione!
Verificato che succede anche in v10

**Comment by GSLabIt** [comment]
@monen17 qualche idea su come risolvere?

**Comment by monen17** [comment]
@GSLabIt idee sì: secondo me è necessario modificare/nascondere i pulsanti e le azioni che hai indicato
quando il campo `sale.order.corrispettivi` è `True`.

Ad esempio: il pulsante **3 Invoices** (che è nella vista `sale.view_order_form` e ha `name="action_view_invoice"`) va nascosto quando `sale.order.corrispettivi` è `True`, lo puoi fare modificando l'attributo `attrs` del tag `button`.
Quando questo è nascosto, sarebbe bene mostrare un altro bottone che invece mostra le view dei corrispettivi.
Questa è solo la prima possibile soluzione e non è nemmeno detto sia la migliore.

**Comment by GSLabIt** [comment]
@monen17 per il pulsante e-fatt? Come lo si potrebbe nascondere?

**Comment by monen17** [comment]
Per nascondere pulsante e-fatt: nel modulo corrispettivi_fatturapa_out erediti dalla vista del corrispettivo (perché è primary) e ci aggiungi indivisibile="True" per nascondere.

Per la stampa puoi nascondere il bottone esistente e mostrarne un altro che stampi i corrispettivi, ma mi sembrava questo fosse già fatto nel modulo dei corrispettivi

**Comment by GSLabIt** [comment]
@monen17 ora vado a memoria, mi sa che stato già fatto, se si arriva da SO cmq non lo nasconde

**Comment by monen17** [comment]
@GSLabit non lo nasconde perché il pulsante dell'ordine di vendita ancora mostra il form della fattura

**Comment by GSLabIt** [comment]
@monen17 scusa, non ho ben capito cosa intendi.

**Comment by monen17** [comment]
> @monen17 si per i pulsanti su SO ho trovato una soluzione, non riesco ancora per quelli su Invoice:
> 
> * stampa corrispettivo anzichè fattura
> * nascondere pulsante e-fatt
> 
> Suggerimenti?

Forse possiamo partire dal vedere cos'hai già iniziato a fare per i pulsanti dell'ordine di vendita, c'è una PR?

**Comment by GSLabIt** [comment]
@monen17 no, la tiro su e ti faccio sapere ..
